### ISSUE TITLE
Make sure interns know that pull requests must be merged to count

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1005]
on the First Steps page, on step 8, we have a list of what needs to be done to move on to step 9 and that list is repeated at the the beginning of Step 9. I think including this list just in step 8 would be best and to then make sure that interns know that the pull requests must be merged to count, as the list says in Step 9.

**Comment by lucy811** [comment]
I think we can slightly change in Step 9. Instead of repeating the list again in step 9, we can say "make sure you have done the list in Step 8".

**Comment by alexkarasik** [comment]
Yeah, that's along the lines of what I was thinking, but it looks like someone else has made a PR for this issue already.
