### ISSUE TITLE
Tell interns what a Rebase is before providing the links

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1007]
On the git Repositories page, we provide links to the rebase instructions and then a Note on the difference between a rebase and a merge. 
I think we need a brief explanation of what a rebase is and when and why we may need it before providing the links and the difference between a rebase and a merge.

**Comment by aurinsomnia** [comment]
I agree that this could be confusing, and a rebase is a powerful tool that should be explained before it is suggested or brought up. If you can effectively explain what a rebase is, and why we would need it in a useful way I think that would be a good change. Go ahead and make a pull request for the change.

**Comment by alexkarasik** [comment]
Here is the current explanation I have for a rebase. It is right above the first mention of rebase on the page and is just a brief additional paragraph. Please let me know what you think:

https://rawgit.com/alexkarasik/alexkarasik.github.io/rebaseline/#!pages/gitandrepositories.md
