### ISSUE TITLE
Automate install and startup of vagrant using bash script for Ubuntu users

### ISSUE THREAD

**Issue by l0rd3141** [open-learning-exchange/open-learning-exchange.github.io#1009]
Creating a bash script to run the following commands automatically would make Vagrant installation and startup easier for upcoming interns using Ubuntu and other similar variants of Linux.
![screenshot2017-06-3003 34 26](https://user-images.githubusercontent.com/9048731/27727680-1d4d1928-5d45-11e7-939f-36195f523153.png)

My proposal is to upload a bash script and provide a link to this script in [First Steps Page](http://open-learning-exchange.github.io/#!pages/firststeps.md) below step 1

**Comment by navneetkarnam** [comment]
* I think you should go ahead and make a PR for this.

**Comment by sagun98** [comment]
It would be better if you include the bash script for windows too in the same file rather than just for the Ubuntu and other Linux distribution,
