### ISSUE TITLE
Add a CD instruction to Mac OSX user Vagrant install

### ISSUE THREAD

**Issue by njanne19** [open-learning-exchange/open-learning-exchange.github.io#1012]
On the [page where it tells new interns to install Vagrant](http://open-learning-exchange.github.io/#!pages/vagrant.md), I believe that the Mac OSX instructions go in an order that is inopportune. The wiki says that you only can use vagrant in the folder it's installed in only after the user has installed it. This could lead to people installing Vagrant in a place that's either inconvenient or messy. Instead, before installing vagrant, the Wiki should say something like:

> Make a new folder on your desktop or another secure and organized location. Here you will be doing all your work and installing vagrant with the terminal. Make sure that you already have brew installed before you proceed with the steps below.

**Comment by navneetkarnam** [comment]
* @njanne19 Yes I feel the same being a Mac user. I feel you should go ahead and make a PR for this one.
