### ISSUE TITLE
Branching instructions on Github Issues

### ISSUE THREAD

**Issue by njanne19** [open-learning-exchange/open-learning-exchange.github.io#1015]
For the page about [Github Issues](http://open-learning-exchange.github.io/#!pages/githubissues.md), I think a better explanation of branching should be in order, especially for new users. This would require taking all the branch information provided, giving "Branching" it's own header, and posting links after each command to the github documentation. Additionally, I think that the screenshot I have posted below which is currently on the bottom of the page should be moved to where the branching section is, in order to give user's a crystal clear relationship picture between their branch, their local github, and the upstream github.

![image](https://user-images.githubusercontent.com/24515342/27745036-dceb4468-5d8f-11e7-871a-bfde34ace0cf.png)

**Comment by dogi** [comment]
@njanne19 go for it ;)

**Comment by alexkarasik** [comment]
This has been merged, so I am closing it.
