### ISSUE TITLE
FAQ Q2

### ISSUE THREAD

**Issue by njanne19** [open-learning-exchange/open-learning-exchange.github.io#1016]
One of the FAQ questions (Q2) asks what kinds of programs and applications will the intern be using during this internship. (See below)
![image](https://user-images.githubusercontent.com/24515342/27745371-152b0b78-5d91-11e7-8973-d9949163a2bf.png)

I think this would be a really good spot for there to be a description on OLE's ideal workflow for interns. The question currently doesn't really answer what kinds of programs interns will be using, just languages. Additionally, if there was a standardized workflow, it would be easier for interns to recieve help when needed. This could be for example, saying that all interns need to have firefox and atom, or something along those lines. This would probably require a full workflow list from a higher-up.

**Comment by kylemathias** [comment]
The workflow for each intern will differ once they are done with the first steps. For example, the Mobile Development team has a guide [here](http://open-learning-exchange.github.io/#!./pages/takeHomeInternDayToDay.md). I think no matter what team you are on you will use those languages and software on some level.
