### ISSUE TITLE
Fixing a typo and also making a sentence more understandable in Step 7 Nation Bell

### ISSUE THREAD

**Issue by apurva-g** [open-learning-exchange/open-learning-exchange.github.io#1018]
In the Introduction paragraph:
1)There is just a missing pronoun in this sentence here shown in bold: There should be constant communication between the nation and the communities. **While is** not necessary for.....

2)This sentence is too long making it difficult to understand in the first go, I am thinking if I can highlight some important part in the sentence by adding quotes:
 While is not necessary for remote communities in the field, it is ideal for our goals of improving the software and testing the increasing forms of communication and feedback between the nation and the communities.

**Comment by apurva-g** [comment]
Above mentioned both issues can be fixed as follows:

While it is not necessary for remote communities in the field, it is ideal for our goals of "improving the software and testing the increasing forms of communication and feedback between the nation and the communities".

**Comment by lucy811** [comment]
I agree with you. I correct this issue and create a pull request.

**Comment by apurva-g** [comment]
Sure, I will create a pull request. Thank you.

**Comment by lucy811** [comment]
@apurva-g Ok, I have closed my pull request about this issue, you can make a pull request .
