### ISSUE TITLE
Downloading resource files clarification

### ISSUE THREAD

**Issue by ctl74100** [open-learning-exchange/open-learning-exchange.github.io#102]
http://open-learning-exchange.github.io/ll_CC/#!pages/bellapps.md
Problem:
When I clicked the links for those example resource files, it automatically opened up the file in a new tab, so all i need to do is right click the webpage and click save. I didn't use the 'raw' function at all.
Solution:
adding a small paragraph on the tutorial telling others if clicking the link leads them opening up the file in the new tab, then just need to right click and save is good. 'raw' function will not be needed in this case.
will make a pull request soon

**Comment by DrewPerlman** [comment]
I also noticed that those links automatically open up the file, so the whole paragraph about the 'raw' button is actually unnecessary because those links will never lead to GitHub. You can update your pull request to reflect this, or I can change it if you'd like.

**Comment by Hulmani** [comment]
I believe that this : "Please click on each one of these links and you will be directed to the GitHub page. After that, you will click on the raw button as you see below" is unnecessary.
