### ISSUE TITLE
In step4 under MacOSX and Ubuntu, adding a bit more information about port number. 

### ISSUE THREAD

**Issue by apurva-g** [open-learning-exchange/open-learning-exchange.github.io#1023]
"It is important to have the correct port number otherwise, it will not work correctly."
I think after this line if I add a few more lines about a port number, that will explain as to why it is important to have a correct port number. Yeah, interns can look for that bit of information by googling but by adding those two lines there itself makes it easy to have a better understanding quickly.

**Comment by apurva-g** [comment]
A port number is a way to identify a specific process to which the Internet or other network message is to be forwarded when it arrives at a server. For the Transmission Control Protocol and the User Datagram Protocol, a port number is a 16-bit integer that is put in the header appended to a message unit.

**Comment by adhikara** [comment]
Good point, although I'd recommend that you write your own understanding of a port number to add to the wiki. That description is from the internet, and so it is not automatically appropriate for the wiki, as the second sentence in particular is a waste of space.

**Comment by apurva-g** [comment]
Sure. I can write my understanding of a port number instead of that definition.

**Comment by apurva-g** [comment]
Port number is an endpoint of communication when a host sends a service request to the server

**Comment by apurva-g** [comment]
Port number is the end point of communication when a host sends a service request to the server that service request is addressed by an application which is listening to that particular port.

Is this ok?

**Comment by kylemathias** [comment]
I believe you have explained it well, but i don't think you should add it to the guide. Know what a port number is, is not vital to getting the guide done. If someone wants to know what it is, they can look it up.

**Comment by apurva-g** [comment]
Ok. I will not make that change.
