### ISSUE TITLE
In Step3, give more general comparison between markdown and other document markup languages

### ISSUE THREAD

**Issue by lucy811** [open-learning-exchange/open-learning-exchange.github.io#1026]
When I learned in Step 3, I saw "Markdown!=HTML" this sentence in this part. I am little confused about how general different they are.  I think it is better if we can provide a general comparison between markdown and other document markup languages for a beginner.

**Comment by navneetkarnam** [comment]
@lucy811 There was a comparison showing both HTML and Markdown syntax earlier but that proved to be a bit confusing so it was removed in one of the earlier issues. I feel it's better we do not add any comparison chart in here as it would lead to more confusions. I would let this stay the way it is.

**Comment by lucy811** [comment]
@navneetkarnam Yeah, I agree with you we do not need to elaborate the difference between HTML and Markdown.  But I find it useful to give a learner a general idea, so I found a  Markdown to HTML converter link on website. I recommend we can add this converter link in the last part of useful links at the end of step 3. This converter just let us know about this general idea.
[Rawgit link](https://rawgit.com/lucy811/lucy811.github.io/lucy4_branch/#!./pages/githubandmarkdown.md)

**Comment by prajwalajayaprakash** [comment]
@lucy811 Hi! Are you still working on this issue? If not, please close it.
