### ISSUE TITLE
Typo in step 4

### ISSUE THREAD

**Issue by daisywatson** [open-learning-exchange/open-learning-exchange.github.io#1028]
In the introduction of step 4 - Bell-Apps Tutorial, the line reads "As you complete these instructions, **and** OLE administrator will complete the registration of your community with the Virtual Intern Nation."

"and" should be "an"

It should read:
As you complete these instructions, **an** OLE administrator will complete the registration of your community with the Virtual Intern Nation.

**Comment by lucy811** [comment]
Yes. I agree with you . Besides, I correct this typo and create a pull request.
