### ISSUE TITLE
Inconsistency in step 6 and 8

### ISSUE THREAD

**Issue by daisywatson** [open-learning-exchange/open-learning-exchange.github.io#1033]
In step 6, it says that the format for pull requests is to put the issue # in the **title**. 
In step 8, it says to put the issue # in the **description** of the pull request.

One of these two should be changed so that the format is consistent.

**Comment by duongdo27** [comment]
Good detection. You can open pull request for that.

**Comment by lucy811** [comment]
I prefer to put issue #in the title,so that people can see pull request to solve issue# at the first glance.
