### ISSUE TITLE
Rewrite sentence in step 6

### ISSUE THREAD

**Issue by daisywatson** [open-learning-exchange/open-learning-exchange.github.io#1034]
The sentence reads: "We suggest to include the issue for which the pull request is resolving (for example, if your pull request fixes the issue number 320, then add #320 to your pull request) to the title of your PR and also the rawgit link into the description of the pull request."

This sentence has a grammatical error and I would change it to:

"We suggest including the issue number for which the pull request is resolving in the title of your PR (for example, if your pull request fixes the issue number 320, then add #320 to the title of your PR), as well as the rawgit link in the description of the pull request."

**Comment by kylemathias** [comment]
That would be fine. Make the PR and changes
