### ISSUE TITLE
Grammar fix in step 6

### ISSUE THREAD

**Issue by daisywatson** [open-learning-exchange/open-learning-exchange.github.io#1035]
The sentence reads, "Github will render the task list in markdown and will look similar to something like the checklist shown below this paragraph."

I would change it to:
"Github will render the task list in markdown, and **it** will look similar to something like the checklist shown below this paragraph."

**Comment by navneetkarnam** [comment]
@daisywatson This is a minor change. Go ahead and make a PR for this.
