### ISSUE TITLE
Rewrite sentence in step 8

### ISSUE THREAD

**Issue by lucy811** [open-learning-exchange/open-learning-exchange.github.io#1038]
In step 8-create issues and pull request part

"Create three more issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests."

Can rewrite sentence "Create three more issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests. **Generally, you should resolve three issues which create by yourself to prevent multiple pull request for the same issue.**"

**Comment by sarah-lu102** [comment]
@lucy811 ask @dogi in the gitter chat to confirm if that's what he prefers

**Comment by lucy811** [comment]
@sarah-lu102 I have posted this question to @dogi in gitter chat.

**Comment by prajwalajayaprakash** [comment]
I am closing this issue since it has been resolved.
