### ISSUE TITLE
Vagrant installation instructions for Arch users

### ISSUE THREAD

**Issue by l0rd3141** [open-learning-exchange/open-learning-exchange.github.io#1041]
Besides Ubuntu users, new interns may be Arch Linux users as well. Maybe it will be a good idea to add installation instruction for Arch Linux on vagrant.md page.

![vagrantinstruction](https://user-images.githubusercontent.com/9048731/27845205-6285359c-60f2-11e7-9673-1a037da7474c.png)

**Comment by kylemathias** [comment]
I like the thought, but i think we are stretching the step by steps to much. If someone is on linux, im assuming they already know these commands.

**Comment by l0rd3141** [comment]
I'll keep that in mind in future issues and pull requests. Thank you for your advice!

**Comment by l0rd3141** [comment]
My apologies, I closed the issue by mistake. Should I close the issue myself? or is only a higher authority supposed to do it?

**Comment by kylemathias** [comment]
you can close it if you want.
