### ISSUE TITLE
Rephrase the sentence in step 5

### ISSUE THREAD

**Issue by lucy811** [open-learning-exchange/open-learning-exchange.github.io#1043]
Step 5, clone your github repository username.github.io part
"Both HTTPS and SSH URLs identify the same remote repositories but use different protocols to access the codebase. As an optional step explore the differences using...."

I want to change to this
"Both HTTPS and SSH URLs identify the same remote repositories but use different protocols to access the codebase. **Besides HTTPS we talked above, you can also use SSH to do the same thing. You can** explore the differences using...."

**Comment by kylemathias** [comment]
need to add a "about" to your sentence. so it would sound like this "Besides HTTPS we talked _about_ above, you can also use SSH to do the same thing"

**Comment by prajwalajayaprakash** [comment]
I am closing this issue since it has been resolved.
