### ISSUE TITLE
Add bold font under "Wait for Review" in Git Issues

### ISSUE THREAD

**Issue by njanne19** [open-learning-exchange/open-learning-exchange.github.io#1045]
This is just a minor change, but on the [Github Issues page](http://open-learning-exchange.github.io/#!./pages/githubissues.md), I think that there should be a boldface font under the "Wait for Review" section when it says "After your pull request has been approved and merged ", this way, new interns won't accidentally delete their branch. Maybe this is cherry picking but I think it could just make the site that much better.

**Comment by navneetkarnam** [comment]
@njanne19 Go ahead and make a PR for this.
