### ISSUE TITLE
Better describe where Interns can look for the buttons in repository in step 0

### ISSUE THREAD

**Issue by lucy811** [open-learning-exchange/open-learning-exchange.github.io#1051]
In step 0, old sentence:"When you are on a repository or profile page, look for these buttons in the top right of the screen. "

I think this sentence is better to add an "a" :
"When you are on a repository or **a** profile page, look for these buttons in the top right of the screen. "

**Comment by aurinsomnia** [comment]
This is personal preference, but I don't think that the 'a' works a lot better than previously. With that said, I think some of the other parts of the sentence could use some adjustment. One that pops out to me is that the phrase "in the screen" is quite awkward, as a.) the button should be on the top of the *page* not screen, and b.) generally the phrase is *on* not in the screen. I think those would be more worthwhile changes if you're up for it.

**Comment by lucy811** [comment]
@aurinsomnia Thank you for your advice. I also delete **right** in my pull request . Because I find the follow button on the profile page is on the left, not on the right.

**Comment by kylemathias** [comment]
I think it is fine as is.

> @aurinsomnia Thank you for your advice. I also delete right in my pull request . Because I find the follow button on the profile page is on the left, not on the right.

this is a different issue then what you brought up original. Are you trying to add an  "a" to a sentence? or are you trying to better explain where the delete button is? try to be as clear and concise as you possible can so when others are reading the issue you created they don't have to figure out what you are talking about.

**Comment by Ebuka-Chibueze** [comment]
@kylemathias I noticed that this sentence kinda conflates the watch button with the follow button.
> When you are on a repository or profile page, look for these buttons in the top right of the screen. 

I think @lucy811 is talking about the follow button for profile pages. Its near the top left of the page but the wiki says its in "the top right of the screen".

**Comment by Ebuka-Chibueze** [comment]
@lucy811 
> When you are on a repository or profile page, look for these buttons in the top right of the screen. 

 I don't think you have to delete **right** since it's technically true for repository pages. I think you should delete **or profile page** and mention it in a new sentence. Also change  **these buttons** to **this button**.

**Comment by lucy811** [comment]
@Ebuka-Chibueze @kylemathias 

First, I have changed the title of this issue .
Then, according to your comments, I delete “or profile page”, and change “these buttons in the top right of the screen” to”this button at the top right of the page"
Now, the new sentence is "When you are on a repository, look for this button at the top right of the page. “
