### ISSUE TITLE
Including a better Git Tutorial

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#1052]
While it is not required for aspiring interns to really learn git in order to complete the first steps since they can just use the Github online editor but knowing git can help them when they are accepted as an intern and are working in projects. There are some links to learning Git in the wiki but I have found a couple of guides that provide more hands on approach like Github's [Try Git](https://try.github.io/) and [Git-it](http://jlord.us/git-it/).

**Comment by navneetkarnam** [comment]
I just personally tried out the "Try Git" link and it looks helpful to me. I think we should add this to the first steps.

**Comment by sagun98** [comment]
The links on git tutorial looks great. Should definitely add this one on the main pages.

**Comment by navneetkarnam** [comment]
@LKhadka are making a PR for this?

**Comment by kylemathias** [comment]
@LKhadka You want to change around our git tutorial? You want to add to our tutorial? You want to replace the currently linked tutorial with different ones? Please explain a little more to what you are going to do before you go and make changes.

**Comment by LKhadka** [comment]
@navneetkarnam yes i will make one by tomorrow
@kylemathias i was thinking of adding them to the useful links section in the [Git Repositories page](http://open-learning-exchange.github.io/#!./pages/gitandrepositories.md).

**Comment by jessica-spencer** [comment]
@LKadka codeacademy also has a free tutorial on git that's very thorough.  Maybe it would be worth comparing to the resources you are proposing and the ones already listed

**Comment by LKhadka** [comment]
@jessica-spencer thanks i will include that as well
