### ISSUE TITLE
Add command to clear cache and reload the browser in same session in githubandmarkdown.md

### ISSUE THREAD

**Issue by l0rd3141** [open-learning-exchange/open-learning-exchange.github.io#1053]
Add keyboard shortcuts to reload the page with the cache cleared.

![screload](https://user-images.githubusercontent.com/9048731/27984308-61ef74fa-6398-11e7-9b1a-288fb618566c.png)

The current note simply talks about clearing cache but doesn't go into further detail. Simply adding a line with keyboard shortcut to clear cache and reload will be very helpful for new interns

**Comment by aurinsomnia** [comment]
I'm not sure how important this note truly is, but if you can keep the changes minimal, I'm all for it. Also, while you're working on it, I'd fix the spelling error that is in the screenshot. "Incongito" should be spelled *Incognito*. Go ahead and make a PR with the changes.
