### ISSUE TITLE
Unclear instructions regarding form fill up in bellapps.md

### ISSUE THREAD

**Issue by l0rd3141** [open-learning-exchange/open-learning-exchange.github.io#1054]
Current screenshot with details on how to fill index page is somewhat confusing. 

![unclearbellapps](https://user-images.githubusercontent.com/9048731/27984466-15685bd4-639c-11e7-912e-ce8a455da01d.png)

Here, administrator details have been imported for General Manager and Tech Support leading to some confusion. Interns are either supposed to manually enter dogi's detail in these fields or they are supposed to import administrator details as shown in the screenshot. This will result in them becoming their own local manager and tech support. It is unclear which one is the right step to take. Either we can use a different screenshot or add a line informing the interns about the right step.

**Comment by aurinsomnia** [comment]
I agree that this is somewhat unclear. Go ahead and make a PR with a fix you think is appropriate and we'll go from there.

**Comment by Ebuka-Chibueze** [comment]
The parts that are circled are more important. You can just import from the admin. The General Manager and Tech support section are more like placeholders.
