### ISSUE TITLE
Fixing a minor grammatical error in FAQ page: in a sentence under Q6.

### ISSUE THREAD

**Issue by apurva-g** [open-learning-exchange/open-learning-exchange.github.io#1062]
As an answer to Q6 on FAQ page
"To be more clear: the initial 10 steps are a vetting process to determine whether or not people are fit for the internship, so consider **it an** interview for the internship".
There is a missing preposition "as".

**Comment by apurva-g** [comment]
"To be more clear: the initial 10 steps are a vetting process to determine whether or not people are fit for the internship, so consider **it as an** interview for the internship".

**Comment by adhikara** [comment]
The current version is idiomatic, and is correct. Adding 'as' just sounds bizarre to me, and the internet seems to agree: https://www.englishforums.com/English/ConsiderOrConsiderAs/znrpd/post.htm

**Comment by apurva-g** [comment]
Ya makes sense. But in this particular sentence adding "as" would not make the sentence wrong.
