### ISSUE TITLE
Fixing a minor punctuation mark typo on FAQ page, under Q.10

### ISSUE THREAD

**Issue by apurva-g** [open-learning-exchange/open-learning-exchange.github.io#1064]
"Communities, which run locally on **Raspberry Pi’s** and/or laptops, are run on an intranet but are most of the time not connected to the internet". 

Here I think they mean to use the plural form of Rasberry Pi, so I feel it should not be an apostrophe s (because it makes it a possessive form).

**Comment by apurva-g** [comment]
"Communities, which run locally on **Raspberry Pis** and/or laptops, are run on an intranet but are most of the time not connected to the internet".

**Comment by kylemathias** [comment]
you can go ahead and make the change and the PR.

**Comment by apurva-g** [comment]
Sure. Thank you.
