### ISSUE TITLE
Changes for the Mac OS part of the Couchapp installation

### ISSUE THREAD

**Issue by navneetkarnam** [open-learning-exchange/open-learning-exchange.github.io#1066]
- This part of the Couchapp installation needs to be edited as ``sudo install`` does not work for Mac and we would need to use ``brew install`` instead.
- Also once installed the couchapp command doesn't work on the mac unless you do some hard coding and get into the "ole--vagrant-vi" folder on your mac and then type in 
``cd /ole/BeLL-Apps-0.12.80/node_modules/.bin/couchapp`` to launch couchapp.
<img width="936" alt="screen shot 2560-07-14 at 11 46 38 pm" src="https://user-images.githubusercontent.com/16421653/28236342-d601ab84-68f1-11e7-93ce-e3fc5b7cb508.png">

**Comment by kanishk1010** [comment]
@navneetkarnam you are right, apt-get is not available on MacOS. So, first of all we can separate Linux and MacOS instructions. However, to get Python, if not installed already installed, I would rather use official Python package from their website than use 'brew', as brew puts it in /usr/local/bin which can be overwritten easily by other applications without 'sudo'. But both ways are fine. MacOS does always have Python 2.6 or 2.7 out of the box. So, it might not be necessary anyway. 

Second, Why do you have to be in 'ole--vagrant-vi' folder to run couchapp, why not from the Couchapp directory, we just cloned?

Above being said, we definitely need to segregate Linux and MacOS instructions. Let me know what you think.

**Comment by navneetkarnam** [comment]
@kanishk1010 Yup the MacOS instructions and linux has to segregated it is a bit confusing and will take a lot of time for anyone with a mac to get thru this step. I had been away for a while and will be getting back to doing things from this week. I'm still a bit confused on running the Couchapp, that being said I will get to work on this from scratch again. Please do let me know if you come across any suggestions as to how I can go about with the Couchapp on mac.
