### ISSUE TITLE
Recommend people to start Crowdin tranlation after finishing step 4 BeLL-Apps Tutorial

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1070]
# Problem
Due to lack of context and basic understanding of what BeLL Apps do, I found it hard to translate some words (e.g. nations, communities, collection, etc.) when I started translating on Crowdin following [Step 0](http://open-learning-exchange.github.io/#!./pages/firststeps.md#Step_0_-_Introductory_Steps). I feel that I have a better understanding of what BeLL-Apps do after going through [Step 4 - BeLL-Apps Tutorial](http://open-learning-exchange.github.io/#!./pages/bellapps.md)'s introduction and videos. 

# Possible Solution
Add a sentence to the the paragraph about Crowdin translation (highlighted in bold)
> We use Crowdin to translate our user interface in many different languages. If you know another language, go to [this Crowdin link](https://crowdin.com/project/open-learning-exchange/invite) to join Crowdin by creating an account. __You may start contributing on Crowdin after finishing [Step 4 - BeLL-Apps Tutorial](http://open-learning-exchange.github.io/#!./pages/firststeps.md#Step_4_-_BeLL-Apps_Tutorial) so that you have a better understanding of what BeLL Apps do.__ It would be very helpful for you to translate some of the words and familiarize yourself with the software. It would be great to get at least 10% on a language that you speak. If you want to spend additional time, feel free to provide translations to 100%.

**Comment by kylemathias** [comment]
This change is fine. Go ahead and make the changes and pull request.

**Comment by xyb994** [comment]
@kylemathias Thanks for the comment, I've started a PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1078

**Comment by xyb994** [comment]
Just noticed that we have the link to [Planet User Manual](http://open-learning-exchange.github.io/#!pages/planetusermanual.md) at https://open-learning-exchange.github.io/#!index.md

I think it would be better to add another sentence:

> We use Crowdin to translate our user interface in many different languages. If you know another language, go to [this Crowdin link](https://crowdin.com/project/open-learning-exchange/invite) to join Crowdin by creating an account. __You may start contributing on Crowdin after finishing [Step 4 - BeLL-Apps Tutorial](http://open-learning-exchange.github.io/#!./pages/firststeps.md#Step_4_-_BeLL-Apps_Tutorial) so that you have a better understanding of what BeLL Apps do. You may also reference [Planet User Manual](http://open-learning-exchange.github.io/#!pages/planetusermanual.md) for detailed explanation of various terms.__ It would be very helpful for you to translate some of the words and familiarize yourself with the software. It would be great to get at least 10% on a language that you speak. If you want to spend additional time, feel free to provide translations to 100%.
