### ISSUE TITLE
adding to How To Preview of markdown in github

### ISSUE THREAD

**Issue by jessica-spencer** [open-learning-exchange/open-learning-exchange.github.io#1071]
The section about How to Preview markdown text should include instructions on how to preview markdown within the github browser.

**Comment by jessica-spencer** [comment]
Proposed addition:

If you are writing markdown from the [editor](https://github.com/open-learning-exchange/open-learning-exchange.github.io/new/master) in the GitHub browser interface, you are able to preview that markdown by clicking the preview button.

**Comment by kylemathias** [comment]
Please wait for approval on a issue before making changes and pull requesting. ( i know it seems like i am beating you up about this topic, i just want to be consistent. Its not a big deal, you didn't know before hand our issue fixing etiquette.)

**Comment by dogi** [comment]
@jessica-spencer I really like your suggestion of Preview,
but the place you added it (README.md)
was not the right place ...

please try to add this to a better spot inside our github.io pages

**Comment by alexkarasik** [comment]
@jessica-spencer Are you still working on this?
