### ISSUE TITLE
Clarifying cd instructions in Vagrant tutorial

### ISSUE THREAD

**Issue by jessica-spencer** [open-learning-exchange/open-learning-exchange.github.io#1079]
In pages/vagrant.md under the MacOSX instructions, it says : "Vagrant only works when you are in the same directory where your Vagrantfile is located. To make sure you are in the proper directory, open your Terminal and type cd ole--vagrant-vi." 

As it is not always true that old-vagrant-vi will be located one down from the home directory, I'd like to reword it like this to make it a bit more accurate: 

"Vagrant only works when you are in the same directory where your Vagrantfile is located. If you did not navigate to another directory to install vagrant, then your vagrantfile will be located inside the ~/ole-vagrant-vi directory.  To navigate there,  open your Terminal and type cd ole--vagrant-vi."

**Comment by jessica-spencer** [comment]
Forgot to include markdown in the change, going back and fixing it.

**Comment by kylemathias** [comment]
This change is fine. Go ahead and make the changes and pull request.

For future reference: please wait for approval on an issue before you start to make changes to code. You might be making changes to something that could be removed in the future, already could of been solved some place or for a variety of reasons you could not be aware of.
