### ISSUE TITLE
New Tabs When Clicking Links

### ISSUE THREAD

**Issue by mhalqurashi** [open-learning-exchange/open-learning-exchange.github.io#108]
When clicking on links, a new tab should open.

**Comment by i5o** [comment]
What do you mean by links? Navigation, or something like *brew* in this case:
<img width="1251" alt="captura de pantalla 2016-06-04 a las 4 59 29 a m" src="https://cloud.githubusercontent.com/assets/2650479/15798501/2398cb14-2a11-11e6-916b-04a49dcf7327.png">

**Comment by AdityaNair99** [comment]
Just for the record, ctrl+click ought to do that in chrome, but if you mean as a universal solution, this should work - just good old html. 
<a href="http://google.com/" target="_blank">Google</a>

**Comment by dogi** [comment]
hmm - this is little bit vague
@mhalqurashi wonder mostly which links you are speaking about ...
