### ISSUE TITLE
Change FAQ link to indeed job description to a markdown link

### ISSUE THREAD

**Issue by jessica-spencer** [open-learning-exchange/open-learning-exchange.github.io#1080]

**Comment by kylemathias** [comment]
What?

**Comment by alexkarasik** [comment]
@kylemathias I think she means, to just include the description from the link rather than the link itself. Is that correct @jessica-spencer ?

**Comment by xyb994** [comment]
I agree, this makes it consistent since all other external links on the same page are using Markdown format. But it looks like the [PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1081) is changing more than one file.

**Comment by kylemathias** [comment]
@alexkarasik (I think) i know what she is going to change, but there is no explanation as to why the change should be made. On top of that, @jessica-spencer went and made the changes before anyone even said anything about them.
