### ISSUE TITLE
minor grammer fix in faq

### ISSUE THREAD

**Issue by jessica-spencer** [open-learning-exchange/open-learning-exchange.github.io#1083]
first sentence of 'first steps' software Summary:
"The aim of the ‘First Steps’ is to introduce prospective interns to the software that they will be using, and make sure they are familiar with each"

I would like to change it to:
"The aim of ‘First Steps’ is to introduce prospective interns to the software that they will be using, and **to** make sure they are familiar with ** it**"

Bolded text is just to highlight the change, it will not be bolded in the update

**Comment by kylemathias** [comment]
Please wait for approval on your issue before making changes and a pull request. see my comment here: https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1079#issuecomment-316485745

**Comment by alexkarasik** [comment]
@jessica-spencer Seems like a fine change to me. Please make a PR for this by Wednesday or I will close this issue.
