### ISSUE TITLE
Inconsistent phrasing of "community BeLL" in configurations.md

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1086]
## Problem
In Step 1 [configuration page](https://open-learning-exchange.github.io/#!./pages/configurations.md), there are 6 places using "community BeLL" but following 2 places using "communityBeLL":

> ### Install a communityBeLL on your OS

> You now have a working [communityBeLL](http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html) on your OS.

## Proposed Change
> ### Install a ~~communityBeLL~~community BeLL on your OS

> You now have a working [~~communityBeLL~~community BeLL](http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html) on your OS.

**Comment by navneetkarnam** [comment]
This is a minor fix. Go ahead and make a PR for it.

**Comment by xyb994** [comment]
@navneetkarnam Thank you, just made a [PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1088)
