### ISSUE TITLE
Step 1 - BeLL installation note about Ubuntu

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1087]
## Question
What does "previously downloaded ole--vagrant-vi" mean in [Step 1 - BeLL installation](https://open-learning-exchange.github.io/#!./pages/firststeps.md#Step_1_-_BeLL_Installation)'s note? There's no prior instruction about downloading ole--vagrant-vi. 

Is this referring to `git clone https://github.com/dogi/ole--vagrant-vi.git` in [configuration.md](https://open-learning-exchange.github.io/#!./pages/configurations.md#MacOS(X)_and_Ubuntu_ONLY)? If this is the case, shouldn't this note be placed inside [configuration.md](https://open-learning-exchange.github.io/#!./pages/configurations.md) right below the Ubuntu heading?

**Comment by xyb994** [comment]
Just noticed 
> Go to [this GitHub address](https://github.com/dogi/ole--vagrant-vi) to read through the basic instructions on how to create your own digital library (what we call the BeLL, or Basic e-Learning Library). You can either scroll down to see the instructions or you can also find them in the README.md file. Do not make ANY changes to the text or files: simply read and follow the directions for your operating system.

was recently replaced with 

>  Go to the [configurations page](configurations.md) to read through the basic instructions on how to install your own digital library (what we call the BeLL, or Basic e-Learning Library). Make sure you only follow the steps for your specific operating system.

That's probably why it's more confusing now.

**Comment by navneetkarnam** [comment]
@xyb994 yes downloaded ole--vagrant-vi refers to the cloning you did before. Downloading the folder in git through the terminal is done using __git clone__ command.

**Comment by l0rd3141** [comment]
Yes, it is referring to the git clone https://github.com/dogi/ole--vagrant-vi.git. Sorry about not making it clear

**Comment by xyb994** [comment]
@navneetkarnam @l0rd3141 Thank you for clarifying my confusion. But the [bash file](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/uploads/bashScripts/instructions.sh) itself consist of installing git. And `git clone`  is not mentioned until the end of [configuration.md](https://open-learning-exchange.github.io/#!./pages/configurations.md), where it sits between all the commands in the bash file.

## Would it be better this way?
1. Add `git clone` command to the bash file: 
```bash
#! /bin/bash

sudo apt-get install git  #Install git if it is not already present
sudo apt-get install virtualbox #Install virtualbox if it is not already present
sudo apt-get install vagrant #Install vagrant if it is not already present
git clone https://github.com/dogi/ole--vagrant-vi.git # Add this line
cd ole--vagrant-vi #Change to ole directory
vagrant up #Start Vagrant
```

2. Move the "note" from firststep.md to [configuration.md](https://open-learning-exchange.github.io/#!./pages/configurations.md)  under Ubuntu heading:
> ## Ubuntu
> **NOTE**: You may [download this bash file](uploads/bashScripts/instructions.sh) to automate the installation process. Make sure that the bash file is in the directory where you would like to store the [ole--vagrant-vi](https://github.com/dogi/ole--vagrant-vi) repository. Go to terminal and use command `sudo sh instructions.sh`

**Comment by l0rd3141** [comment]
Sounds like a great idea. Makes complete sense and it will also unclutter the firststep.md. Maybe wait for approval from one of senior members before going ahead and making a PR.

**Comment by sarah-lu102** [comment]
@l0rd3141 @xyb994 sorry for the confusion, dogi has some switches in the order of instructions that I'm currently working on. I am removing the note from firststep.md to configuration.md in my branch as part of the rearranging that I'm doing.

**Comment by xyb994** [comment]
@sarah-lu102 Thank you for catching this issue and explaining the context. As I'm still on First Step - Step 8, can I work on the update I mentioned above after [your PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1091) has been merged?

**Comment by sarah-lu102** [comment]
@xyb994 are you referring to the bash file? You can work on that independently of my PR since I am only referencing a link to it- as long as you keep the name and location of the file (in github) the same, it should be fine.

**Comment by xyb994** [comment]
@sarah-lu102 I'm referring to both the bash file and the note. I have some modification suggestion to the note content too. Sorry I didn't explain it in item 2. above.

**Comment by sarah-lu102** [comment]
@xyb994 do you want them to be separate pull requests or just one? because if you only need one, then I can just put the edited note into my PR since I am editing that page anyway

**Comment by xyb994** [comment]
@sarah-lu102 I wanted to just have one PR. If you think above change to the note is fine, I can just have one PR that edits the bash file.

**Comment by sarah-lu102** [comment]
@xyb994 ok, I will make changes to the note!
