### ISSUE TITLE
Description of Sections on team.md

### ISSUE THREAD

**Issue by mhalqurashi** [open-learning-exchange/open-learning-exchange.github.io#109]
For each section on team.md, a small description is helpful.

**Comment by AdityaNair99** [comment]
I agree! At the moment it's a little vague if you haven't checked out the chat in a while

**Comment by dogi** [comment]
suggestions please

**Comment by DrewPerlman** [comment]
Section 1: Steps Completed
Section 2: Steps in Progress
Section 3: Inactive/Incomplete

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/commit/7866879c85a27dd9af987c8309b5818c423cda0f done
