### ISSUE TITLE
Add screenshot for creating dummy user in nation.md

### ISSUE THREAD

**Issue by l0rd3141** [open-learning-exchange/open-learning-exchange.github.io#1090]
Currently the instructions for creating dummy member is not accompanied with any image. 
![nation bell 1](https://user-images.githubusercontent.com/9048731/28432609-179315e6-6d4e-11e7-84f1-9e43c6811c6b.png)
While the text is self explanatory it will still be helpful to add images with instructions on them. This will also create consistency as most other steps have screenshot associated with them.

**Comment by Ebuka-Chibueze** [comment]
@l0rd3141  I agree, this would help with the consistency. I suggest making a pull request that adds the picture and mentions it in the instructions.
