### ISSUE TITLE
Extra space after left parenthesis in firststeps.md

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1094]
4 out of 11 parentheses in [firststeps.md](https://raw.githubusercontent.com/open-learning-exchange/open-learning-exchange.github.io/master/pages/firststeps.md) is having an extra space after `(`.

### Step 6
>   * 2 pull requests made ( one at step 3 and one at step 6)

### Step 7
>   * 5 merged pull requests made ( one at step 3, one at step 6 and three at step 8)
>   * 4 comments made ( one at step 6 and three at step 8)
>   * 4 issues created ( one at step 6 and three at step 8)
---
We should probably remove the extra space.

**Comment by alexkarasik** [comment]
@xyb994 that seems fine to me. Go ahead with the PR.

**Comment by xyb994** [comment]
Closing this as [PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1098) has been merged.
