### ISSUE TITLE
BeLL Community configuration page screenshots not up to date

### ISSUE THREAD

**Issue by srivirtual** [open-learning-exchange/open-learning-exchange.github.io#1102]
Steps to Reproduce:
step1.
Goto https://open-learning-exchange.github.io/#!./pages/configurations.md#User_Interface
    Check the images of Configurations.png ,Success.png (Configurations,Register)

step 2.
Goto http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html .enter your username /password .goto http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html, click on Manager and click on configurations button.the screenshot will look like
![admin_srivirtual](https://user-images.githubusercontent.com/30275122/28496965-4edf7cbe-6f2f-11e7-99d3-7eed3ce9296a.jpg)

The images in step1 should match with step2 images .There is Automatic Password Reset Duration(hr) drop down is missing in step1 images

**Comment by kylemathias** [comment]
I think you are referring to a problem that should get fixed, but the way you went about presenting it makes it difficultly for someone to understand.

- Your title should be 2-4 words describing the issue so its easy to reference later.
- Your first paragraph should describe the problem in **_concise_** details.
- Next, you should describe how you are going to solve the problem.

After you have done that, let someone from the internet team tell you to make the changes.

I would say with this issue, make the pull request and the changes so we can get a better understanding of what you are talking about. But be warned, it might not get approved.

**Comment by xyb994** [comment]
@kylemathias, I think @srivirtual is saying that [the configuration screenshot](https://open-learning-exchange.github.io/pages/uploads/images/configuration.png) and [registration success screenshot](https://open-learning-exchange.github.io/pages/uploads/images/success.png) on [Step 4 - BeLL-Apps Tutorial](https://open-learning-exchange.github.io/#!./pages/bellapps.md#User_Interface) is a little bit different from the current version of BeLL. The one on the wiki does not have `Automatic Password Reset Duration(hr) drop down`.

**Comment by kylemathias** [comment]
@xyb994 I understand what is being requested, bit just takes longer to translate what was said into what is going to be changed and why. The whole purpose of the Issue is to simply describe something you see needs changing to others.
