### ISSUE TITLE
Update note about closing issues using keywords

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1103]
Current [Commit Message Style Guide](https://open-learning-exchange.github.io/#!./pages/githubissues.md#Commit_Message_Style_Guide) in Step 6 - GitHub Issues Tutorial: 
> **NOTE**: in your commit message, if you add a keyword like "fixes" or "resolves" followed by "#" and the issue number, once your pull request is merged, the issue will automatically be closed. This is helpful because it helps declutter the issues section.

# Proposed Update
Add a link to the official GitHub help page regarding `Closing issues using keywords` to help explain how this works on GitHub
> **NOTE**: [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/): in your commit message, if you add a keyword like "fixes" or "resolves" followed by "#" and the issue number, once your pull request is merged, the issue will automatically be closed. This is helpful because it helps declutter the issues section.

**Comment by Ebuka-Chibueze** [comment]
@xyb994 I would personally arrange it like this:  
> **NOTE**: in your commit message, if you add a keyword like "fixes" or "resolves" followed by "#" and the issue number, once your pull request is merged, the issue will automatically be closed. This is helpful because it helps declutter the issues section. See more here [here](https://help.github.com/articles/closing-issues-using-keywords/).

I previewed your update on my local fork and in my opinion it looks more clean if the link is at the end of the paragraph. You could also  add the link to bottom of page in the **Useful Links** section.

**Comment by dogi** [comment]
@xyb994 I really like you suggestion - just go for it

**Comment by xyb994** [comment]
@Ebuka-Chibueze Thank you for your comment. I originally thought about putting the link at the end of the paragraph just as you suggested. But I thought it would be nice to know what the note is about at the start of the paragraph. 

After comparing both versions. I agree with you that putting it at the end looks more clean. So I'll go ahead creating the PR with the link at the end.

### Putting the link at the start
<img width="866" alt="screen shot 2017-07-24 at 19 25 43" src="https://user-images.githubusercontent.com/7483137/28549545-bc6f7d90-70a8-11e7-8444-12e78b90bbac.png">

### Putting the link at the end
<img width="860" alt="screen shot 2017-07-24 at 19 26 04" src="https://user-images.githubusercontent.com/7483137/28549549-be82440a-70a8-11e7-8dbf-422f34cde224.png">

**Comment by xyb994** [comment]
@dogi Thank you for taking a look at the issue, just created [PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1111)

**Comment by xyb994** [comment]
Closing this as PR #1111  has been merged.
