### ISSUE TITLE
Vi Cheat Sheet in FAQ page

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1104]
[Vi Cheat Sheet (JPG)](https://www.shell-tips.com/sheets/vi_help_sheet.jpg) in [faq.md](https://open-learning-exchange.github.io/#!./pages/faq.md#Helpful_Links) is linking to a low quality .jpg file. The same [pdf version](https://www.shell-tips.com/sheets/vi_help_sheet.pdf) has higher quality but someone already pointed out [an error](https://www.shell-tips.com/2006/10/29/help-sheet-for-vi-editor/) of this cheat sheet.

We should probably find an alternative version. I found a blog post about various [printable vim cheat sheets](http://www.refining-linux.org/archives/20/13-Printable-vim-cheat-sheets/). Personal I think [this](http://www2.cs.uidaho.edu/~rinker/ed03.pdf) and [this](https://www.smashingmagazine.com/wp-content/uploads/2010/05/VI-Help-Sheet-011.pdf) looks simple. But as I'm not familiar with vim, can someone pick one that's good to put in our FAQ page?

**Comment by dogi** [comment]
@xyb994 why not ;)

try to wow me with a better solution ...

**Comment by dogi** [comment]
@xyb994 why noy ;)

... try to wow us with a better solution

**Comment by alexkarasik** [comment]
@xyb994 any progress with this? I will close by Friday of not.

**Comment by xyb994** [comment]
@alexkarasik Thanks for reminding me, here's the [PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1141)
