### ISSUE TITLE
Application Cache Error:Manifest fetch failed(404) when trying to sync with nation

### ISSUE THREAD

**Issue by srivirtual** [open-learning-exchange/open-learning-exchange.github.io#1107]
Goto http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html#login
login with your admin credentials.Goto Mnanger/click sync with nation tab/select all ,click send
please see attached error
<img width="2500" alt="syncnationerror" src="https://user-images.githubusercontent.com/30275122/28538624-b4d01df0-7063-11e7-9d1e-a56abd3fbd99.png">

**Comment by kylemathias** [comment]
This might be an isolated issue. Let others comment on it so we can find out if this is a error that can be avoided.

**Comment by sarah-lu102** [comment]
@srivirtual I have the same issue as well- good catch.

**Comment by alexkarasik** [comment]
Anyone else get this error? This is either a big issue or an isolated issue. This did not happen to me.
