### ISSUE TITLE
*General Issue* Less is More!

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1108]
This is an ongoing issue, so all potential and current interns can contribute to this. Issues are not just about adding and contributing to the wiki, but can also be about removing repetitive or unnecessary content. Less is more. Anywhere that you see something that can be removed can be helpful and a valid pull request to make the steps clearer.

Thank you. :)

**Comment by kylemathias** [comment]
I know this seems silly to say, but might be good to add this to some place in the wiki to let people know they can remove things if its repetitive.

**Comment by alexkarasik** [comment]
@kylemathias sure, I'll make a PR in reference to this, but we'll keep the issue open after it gets approved.
