### ISSUE TITLE
Step 0 ordered list and screenshot size 

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1113]
# Problem
- List item 3 on [step 0](https://open-learning-exchange.github.io/#!./pages/firststeps.md#Step_0_-_Introductory_Steps) is showing as `1.` in the MDwiki page.
- Two screenshots are taking a lot of space in firststeps.md

# Proposed change
- Indenting `![Watch screenshot](uploads/images/Watch.png)`, `![Follow Screenshot](uploads/images/Follow.png)`, and removing `* * *` fixes the problem of number 3 not showing in the MDwiki page. 

- I personally think above two screenshots look better on the same line, which helps to declutter the first step page. The user could click to expand images. Red circles on the screenshots are enough to point out where to look for the appropriate buttons. See screenshots below:

## Screenshots on the same line
<img width="879" alt="screen shot 2017-07-25 at 16 46 47" src="https://user-images.githubusercontent.com/7483137/28593092-346700ce-7159-11e7-8d7e-ecfe99dba66a.png">

## Screenshots on separate lines
<img width="588" alt="screen shot 2017-07-25 at 16 51 42" src="https://user-images.githubusercontent.com/7483137/28593241-a8a887be-7159-11e7-8f9f-b24dd57b859f.png">

**Comment by alexkarasik** [comment]
I personally don't think its too confusing as it is, but if you think this is an improvement, give it a PR

**Comment by LKhadka** [comment]
I think it might be a problem on smaller screens. Maybe you could use some media queries for that?

**Comment by Ebuka-Chibueze** [comment]
I think you should definitely make a pr to change the list in step 0.

**Comment by xyb994** [comment]
@alexkarasik Yeah it's definitely not confusing as it is, but I think it could be consider a defect and the screenshots are supposed to be within item 2 anyways.

**Comment by xyb994** [comment]
@LKhadka @Ebuka-Chibueze On smaller screens, users could click on the image to view it in a bigger size. It looks like it's already responsive, see screenshots of the one line version on screen width 767px below:
<img width="867" alt="screen shot 2017-07-26 at 18 01 13" src="https://user-images.githubusercontent.com/7483137/28645683-7ea66214-722c-11e7-82a3-09adbb699dab.png">

**Comment by LKhadka** [comment]
@xyb994 looks good but it would be nice to have some gap between those two images. 
![image](https://user-images.githubusercontent.com/6295956/28647867-5da5578e-722f-11e7-82bb-442979493a13.png)

**Comment by xyb994** [comment]
@LKhadka There are no gap between these two images because I have them placed in one line and that's the way MDwiki handles it on smaller screens. To make things simple and not changing too much of the original page, I will make a PR with the version that displays [screenshots on separate lines](https://user-images.githubusercontent.com/7483137/28593241-a8a887be-7159-11e7-8f9f-b24dd57b859f.png) so there would be a gap between images no matter what the screen size is.

Reference: 
[MDwiki's quick start example about images](https://dynalon.github.io/mdwiki/#!quickstart.md#Images)

**Comment by LKhadka** [comment]
Looks good to me
