### ISSUE TITLE
BeLL-Apps Tutorial

### ISSUE THREAD

**Issue by ggwilliams** [open-learning-exchange/open-learning-exchange.github.io#1118]
After the configurations screen shot it says,
"After filling out your configurations, remember to save a screenshot of the configuration page so that you can post it on the Gitter chat after submitting your registration request".

I think it might be more helpful to mention that iterns will need to take a screenshot of this page under the User Interface header. Or maybe add another note mentioning it after the screen shot of the become an administrator page.

When I went through this step I had to press the back button and take a screen shot after I had already clicked register.

**Comment by alexkarasik** [comment]
If you think that is an improvement, go ahead and make a PR.

**Comment by navneetkarnam** [comment]
go ahead and make a PR for this. I think it is good to add in as a __"note"__ so that it just serves as a reminder before hand that they will need to take a screenshot.

**Comment by alexkarasik** [comment]
@ggwilliams Still working on this? I will close it by wednesday if not...

**Comment by xyb994** [comment]
Fixed in #1837.
