### ISSUE TITLE
Git Bash Lesson

### ISSUE THREAD

**Issue by RMDern** [open-learning-exchange/open-learning-exchange.github.io#1119]
![olegitbash](https://user-images.githubusercontent.com/3970591/28697001-1005fed8-7307-11e7-97f9-58d3bdfeba90.PNG)

Add link to Git Bash lesson for interns interested in using and learning more about the tool. I think the link should be located in a new sentence at the bottom of the pictured section of "vagrant.md".

**Comment by RMDern** [comment]
I have previously completed a short (~1 hour) course on Git Bash which is available for free on Udemy here: https://www.udemy.com/git-bash/

It is very easy to follow for beginners and provides a comprehensive setup and introduction to get people up and running with Git Bash in tandem with GitHub.

**Comment by dogi** [comment]
why not ;)

@RMDern make a PR

@/all: wonder still if we should reverse the order of cli's
I mean 1. git bash 2. powershell 3 command line ;)
I would be even so arrogant to say that `git bash` is the preferred choice
but here I wonder about feedback of you ;)

**Comment by alexkarasik** [comment]
Which section/page would we find this?

**Comment by Yurockkk** [comment]
@alexkarasik you can find it [here](http://open-learning-exchange.github.io/#!./pages/vagrant.md#Windows). People who use Windows can share their thought to @dogi !

**Comment by Ebuka-Chibueze** [comment]
@dogi I think this is a great idea. As a windows user, I personally prefer Git Bash.

**Comment by paulbert** [comment]
@dogi I agree.  I rarely use powershell or the command line.

**Comment by kylemathias** [comment]
I say remove it. i never used it.

**Comment by alexkarasik** [comment]
@RMDern are you still working on this? I don't see an open PR for it. I will close this on Wednesday otherwise.

**Comment by RMDern** [comment]
@alexkarasik My apologies, I'm just returning from overseas and didn't have a chance to make this change. Could you please re-open this and I'll make a PR?
