### ISSUE TITLE
Crossed out bit in HTML Resources page.

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1121]
I was wondering why this sentence in the HTML Resource page under the "Adding content to the app and pushing it" section has the bit in the parenthesis crossed out, (though you can't see it here it is crossed out on the page):

Now that you have generated the app, you will need to add the original app data (the one you're porting) to _attachments folder.

If there is an explanation, I am curious and if not, I think the line should be removed as it is confusing.

**Comment by LKhadka** [comment]
That part confused me too

**Comment by kylemathias** [comment]
not sure why. You can go ahead and remove it if you like.
