### ISSUE TITLE
Remind interns to use Firefox when it is time to push their first HTML5 resource to the nation

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1124]
I got stuck for a few days on Step 1 because of this... I feel silly in retrospect, but I think a note or reminder that the "Add to Nation" button will not appear unless the Firefox browser is used will be helpful for someone else in the future.

**Comment by kylemathias** [comment]
I think we mention it some place to use firefox exclusively to avoid problems like this.

**Comment by Yurockkk** [comment]
we did mentioned [here](http://open-learning-exchange.github.io/#!./pages/installation.md#MacOS(X)_and_Ubuntu_ONLY) although it's not that noticeable to me

**Comment by LKhadka** [comment]
I think it would be nice to have a small note since it could help someone who got stuck in that step
