### ISSUE TITLE
URL provided for EmilyLarkin md page shows a 404 error 

### ISSUE THREAD

**Issue by sahityaLMaruvada** [open-learning-exchange/open-learning-exchange.github.io#1128]
When I copy pasted the [URL](EmilyLarkin.github.io/pages/profiles/EmilyLarkin.md) for reference in the browser from the [githubandmarkdowndown.md](http://open-learning-exchange.github.io/#!./pages/githubandmarkdown.md). I got  a page not found error. This is what my [URL](https://github.com/sahityaLMaruvada/sahityaLMaruvada.github.io/blob/sahityamaruvada-branch-1/pages/profiles/sahityaLMaruvada.md  ) looks like 
It would be ideal if
* A  valid URL is placed there for reference
* Attaching a hyperlink would be more accessible than like plan text with a different style
![screenshot of highlighted 404 link](https://user-images.githubusercontent.com/24358427/28843559-a2192d38-76cf-11e7-84b6-df2bd8a250ea.png)

**Comment by kylemathias** [comment]
I think that is trying to show you the proper path to the location witch profile pages are stored more than getting you a proper URL. My URL is https://github.com/kylemathias/kylemathias.github.io/blob/master/pages/profiles/kylemathias.md. You can generate the URL in many ways, but i believe the way it is on the wiki is the easiest. 

You could add the beginning of the URL, https://github.com/kylemathias/ if you wanted to.

**Comment by sahityaLMaruvada** [comment]
Yeah I get that. Since it is mentioned "as an example of a link to a personal page", I think it  would be ideal if the link is valid incase someone tries to see what exactly is in there. Is it fine if I update the current URL in the page with https://github.com/kylemathias/kylemathias.github.io/blob/master/pages/profiles/kylemathias.md as a reference?

**Comment by kylemathias** [comment]
sure. go ahead.

**Comment by sahityaLMaruvada** [comment]
Done! will update it asap!
