### ISSUE TITLE
Repository(<username>.github.io) already exists  error 

### ISSUE THREAD

**Issue by sahityaLMaruvada** [open-learning-exchange/open-learning-exchange.github.io#1129]
I think its better to mention what is to be done if one already has a repository named <username>.github.io for a personal webpage or similar.   
I had the same issue so I renamed the old <username>.github.io repository to a different name since I wasn't really using it and forked the ole repository with title <username>.github.io. It isn't ideal way to do but it worked for me. Is there any other better solution you guys can think of?

**Comment by kylemathias** [comment]
if someone runs into that problem i think its safe to assume that they know how to solve the problem. This guide is intended to streamline the process for people who don't normally use GitHub.

**Comment by sahityaLMaruvada** [comment]
Okay sure.. So can we consider this as closed?

**Comment by kylemathias** [comment]
yes
