### ISSUE TITLE
Can't Merge Fork with Upstream

### ISSUE THREAD

**Issue by AdityaNair99** [open-learning-exchange/open-learning-exchange.github.io#113]
I'm not sure why, but I can't merge my forked repo with the original. It says I'm six commits ahead, but I've already sent a pull request. How do I fix this?

**Comment by AdityaNair99** [comment]
resolved

**Comment by dogi** [comment]
Hmm - this is not a problem of open-learning-exchange.github.io
maybe you could phrase it more in the way gitandrepositories.md needs improvement ...

**Comment by dogi** [comment]
... then create a "pull request" as a suggestion how to improve it
