### ISSUE TITLE
Adding direct link to next steps

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#1132]
I think it would be nice to have a direct link to go the next steps instead of going back to the first steps and clicking on the next step.
<img width="709" alt="image" src="https://user-images.githubusercontent.com/6295956/28903073-8c412c78-77c8-11e7-9aed-57ffe93d470b.png">

**Comment by alexkarasik** [comment]
Great idea! Definitely make a PR for this one

**Comment by xyb994** [comment]
I agree, it make sense to just add the link there.

But "Next Steps" is a little bit strange to me because "installation page" and "configurations page" are both under step 1... Probably this is my language issue. Does anyone else have an opinion?

**Comment by LKhadka** [comment]
@alexkarasik thanks i will make a pr for it

@xyb994 i think its because they have different pages and are too big cover them all in one page

**Comment by sahityaLMaruvada** [comment]
I think its a good idea too. It would be easy to go to next step directly than returning to the "first steps" page and checking till which step one has completed.

**Comment by LKhadka** [comment]
Do you think that there should be a direct link to the next steps in all the pages? It seems that only step 1 has a next steps section and steps 8 and 9 don't have their own pages.

**Comment by kylemathias** [comment]
Some steps have a paragraph explain what the next step entails. i would try to avoid a link to a next step where there is an explanation paragraph for it on the firststeps.md page.

**Comment by alexkarasik** [comment]
@LKhadka What is the status with this issue? I don't see a PR for this, but maybe it was done already?
