### ISSUE TITLE
Ambiguous Sentence in GitHub Issues page

### ISSUE THREAD

**Issue by sahityaLMaruvada** [open-learning-exchange/open-learning-exchange.github.io#1133]
> If you switch branches, the files on your local machine revert back to how they were before you made changes since you are no longer on that branch.

**Suggested Correction:**
If you switch back to master, the files on your local machine revert back to how they were before you made changes, since you are no longer on the new branch created.

I found the latter to be more clear and precise than the previous description 

> Context:

<img width="883" alt="screen shot 2017-08-07 at 11 46 05 am" src="https://user-images.githubusercontent.com/24358427/29034344-0f205baa-7b66-11e7-88a4-d0a65c95cf13.png">

**Comment by Ebuka-Chibueze** [comment]
@sahityaLMaruvada Yeah I see where you're coming from. Your suggestion is more explicit and leaves little room for confusion.

**Comment by sahityaLMaruvada** [comment]
@Ebuka-Chibueze  Yeah I feel the same too. So shall i go ahead and create a pull request for updating it?

**Comment by Ebuka-Chibueze** [comment]
@sahityaLMaruvada Sure.
