### ISSUE TITLE
Representation of Mac OS X in installation.md

### ISSUE THREAD

**Issue by sahityaLMaruvada** [open-learning-exchange/open-learning-exchange.github.io#1134]
**Current Content:**
> MacOS(X)
Open your Terminal. We assume that brew is already installed.

**Suggested Representation:**

> Mac OS X or OS X

Reference:
<img width="754" alt="screen shot 2017-08-07 at 12 12 31 pm" src="https://user-images.githubusercontent.com/24358427/29035512-ddd286c8-7b69-11e7-8ee6-4381e8c84351.png">

[Link to installation.md page](http://open-learning-exchange.github.io/#!./pages/installation.md)

**Comment by LKhadka** [comment]
This is more of a preference change than a functionality issue. Also, there are multiple pages where Mac OS X is spelled differently. Try to focus on issues that are unquestionably needed to be fixed.

**Comment by sahityaLMaruvada** [comment]
Thank you for the suggestion. I felt it is a "standard", rather than a preference,  so wanted to update.  I can fix it on all the pages that has the current representation if required.

**Comment by xyb994** [comment]
@sahityaLMaruvada I noticed this as well when I was on First Steps. Probably just change them to the name of the latest version `macOS` as https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1108 mentioned less is more.
