### ISSUE TITLE
_Config.yml file clarification

### ISSUE THREAD

**Issue by AdityaNair99** [open-learning-exchange/open-learning-exchange.github.io#114]
Just wanted to know where to find the _Config.yml file and if we are updated to kramdown - which would allow us to open links in new tabs as mentioned in #108

**Comment by AdityaNair99** [comment]
Seems like there is no Config.yml file anywhere in the repo (as far as I can tell)

**Comment by dogi** [comment]
please think before you trash our open-learning-exchange.github.io issue queue
maybe you could write this as comment into #108 but for sure not asking for where stuff is ...

**Comment by dogi** [comment]
... that is what https://gitter.im/open-learning-exchange/chat is for ;)
