### ISSUE TITLE
Add link to Installation page

### ISSUE THREAD

**Issue by hmly** [open-learning-exchange/open-learning-exchange.github.io#1140]
I think it would be helpful to readers if we add something like: 

"Refer to the Prerequisites Section of [Vagrant Instruct](http://open-learning-exchange.github.io/#!./pages/vagrant.md) if you encountered an error while executing `vagrant up`" 

to the "MacOS(X) and Ubuntu ONLY" section of the [installation page](http://open-learning-exchange.github.io/#!./pages/installation.md). 

The reason I brought this issue up is because when I executed `$ vagrant up` on the terminal, I encountered an error which was not addressed on the installation page (Step 1), so I had to search for a solution online. Then I found out that the same exact solution was on Vagrant instruction page (Step 2).

**Comment by alexkarasik** [comment]
Great suggestion! We are always looking to make the workflow more clear. Make the PR please :)
