### ISSUE TITLE
Typo in simpleinstall.md "diffrent"

### ISSUE THREAD

**Issue by sahityaLMaruvada** [open-learning-exchange/open-learning-exchange.github.io#1144]
Typo in simple install wiki page. Update - diffrent to different in three places

**Added Suggestion(minor):**
All the project pages just have the **title** but the Simple Install page has **Project Title : Simple Install**. It would be ideal if the uniformity is maintained for all the project page titles.

> Current:
Project Title: Simple Install  

> Suggestion:
Simple Install

**Comment by Yurockkk** [comment]
@sahityaLMaruvada Good catch! Since you are dealing with uniformity issue, you should check [raspberrypi project](http://open-learning-exchange.github.io/#!pages/raspberrypi.md) as well. Go ahead and make a PR!

**Comment by sahityaLMaruvada** [comment]
Sure! Will do it! Shall i update the title to **Raspberry Pi** instead of **Introduction to Raspberry Pi**?

**Comment by Yurockkk** [comment]
@sahityaLMaruvada It seems more consistent to me. Make a PR and let's see what others thought.

**Comment by Yurockkk** [comment]
solved by #1145
