### ISSUE TITLE
Adding a summary of the steps in 'The Steps'

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1146]
I think it would be best to let prospective interns know that the bulk of what they will be doing is filing 4 issues and making 4 pull requests on improvements for the 'First Steps' section and letting them know that this is for them to practice their ability to use Github and work in an Open Source environment. I feel like we could condense 'The Steps' section into a single paragraph as they will be learning most of the rest of what is mentioned along the way. We want to try to break things down as simple as possible and not repeat too much and I think they learn a lot about the BeLL and Vagarant stuff along the way anyway. 
I'm curious about what other people may think about this.

**Comment by kylemathias** [comment]
There is sorta of a summary there already under step 8:

>  - Once you complete Step 8 you will have:
   >  * 5 merged pull requests made (one at step 3, one at step 6 and three at step 8)
   >  * 4 comments made (one at step 6 and three at step 8)
   >  * 4 issues created (one at step 6 and three at step 8)

The goal of the first steps is to be concise and clear as possible, more emphasis on concise. We want interns to ask question and get familiar with reaching out for help when they are stuck.

**Comment by alexkarasik** [comment]
@kylemathias Yes, but I think it may be more useful to have it up earlier than that... I think we are giving folks a lot of information before they know what they are going to be doing. I think it would be an improvement to have them understand the issue/pr system as early as possible.

**Comment by kylemathias** [comment]
@alexkarasik we have had interns who skim pass everything and just do pull request and end up missing some important information because they skipped reading and just did the check list. I would prefer if the first steps became more concise to the point where needing to add the check list at the start was not necessary.

**Comment by alexkarasik** [comment]
I understand. I'm going to close this issue for now and try to think of a different way to make the First Steps more straight forward.
