### ISSUE TITLE
Ambiguity in the VIO Page

### ISSUE THREAD

**Issue by hmly** [open-learning-exchange/open-learning-exchange.github.io#1147]
**On the Virtual Intern Orientation page:**
> Every time you merge a pull request, message the author on Gitter in the chat room, make sure you include a link to the pull request and commit id.

The instruction does not specify who the author is, so I suggest we should include at least the author's name so the reader will know who to notify.

**Comment by duongdo27** [comment]
@hmly The author's name is **the person who create the pull request**. After you merge a PR you should message him/her in the **intern channel**.

**Comment by hmly** [comment]
@duongdo27 Thanks for the clarification. It seems I was reading the sentence from a different perspective.
