### ISSUE TITLE
Repetitiveness in VIO page

### ISSUE THREAD

**Issue by hmly** [open-learning-exchange/open-learning-exchange.github.io#1148]
**From the Virtual Intern Orientation page:**
> It's another way to see what needs to be done, what needs to be reviewed, what you need to work on, and what others are working on. You should be added when you become an intern, but if not message someone and they will add you to the Waffle.io page.

**Suggested Change**
> It's another way to view the projects that you and your team need to work on and review. You will be automatically added to the Waffle.io page once you become an intern. If not, then message someone on the Gitter chat and they will add you.

The change is to make the sentences less repetitive and more descriptive.

**Comment by alexkarasik** [comment]
I agree, this is an improvement. Please make a PR :)
