### ISSUE TITLE
Improving readability of objective

### ISSUE THREAD

**Issue by hmly** [open-learning-exchange/open-learning-exchange.github.io#1149]
**From Simple Install page:**
> Creating Installation processes for different OS like Linux, MAC and Windows and Working on issues at https://github.com/dogi/ole--vagrant-community/issues

**Suggested Change**
> Create installation processes for different OS such as Linux, macOS, and Windows.
Work on issues at https://github.com/dogi/ole--vagrant-community/issues.

**Comment by xyb994** [comment]
How about formatting Objectives section in following 3 projects the same way using ordered list or unordered list:
https://open-learning-exchange.github.io/#!pages/simpleinstall.md
https://open-learning-exchange.github.io/#!pages/crowdinintegration.md
https://open-learning-exchange.github.io/#!pages/htmlresources.md

**Comment by alexkarasik** [comment]
Awesome, but you can put the changes in a PR next time

**Comment by hmly** [comment]
Got it.
