### ISSUE TITLE
Formatting with providing links...

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1162]
Hey guys, I can use a little help with something. I'm trying provide links to useful Angular tutorials for the wiki, but I am having some formatting errors. This is what I am trying to add: 
## Resources for learning Angular/Tutorials

The following are some solid free resources for deepening your understanding of the fundementals of Angular in order to assist in this ongoing project:

[The Official Angular tutorial ](https://angular.io/)
[Shaping Up With Angular from Code School](https://www.codeschool.com/courses/shaping-up-with-angularjs)
[Create an Angular Component egghead.io](https://egghead.io/lessons/angular-2-create-a-simple-angular-2-component)
[AngularJS on CodeAcademy](https://www.codecademy.com/courses/javascript-advanced-en-2hJ3J/0/1)
[Coursetro Angular Course] (https://coursetro.com/courses/8/Learn-Angular-2-Development-with-our-Free-Course)

and this is what the rawgit link currently looks like and I can not figure out why the middle 3 are not formatting as I would like them to: http://rawgit.com/alexkarasik/alexkarasik.github.io/angular-links/#!pages/angular.md

Any input would be appreciated.

**Comment by xyb994** [comment]
It looks like this to me: 

<img width="856" alt="screen shot 2017-08-23 at 12 36 01" src="https://user-images.githubusercontent.com/7483137/29627320-b6d792aa-87ff-11e7-980a-e4e2720297aa.png">

Did you hard refresh (cmd/contrl+shift+R) the rawgit page in the browser? [Related Issue](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/894#issuecomment-308516613)

**Comment by alexkarasik** [comment]
Oh! That's exactly what I wanted. Going to make another Issue and PR for this then... thanks
