### ISSUE TITLE
Return to the corresponding step number

### ISSUE THREAD

**Issue by MadagascarOLE** [open-learning-exchange/open-learning-exchange.github.io#1167]
In the [Github Issues page](http://open-learning-exchange.github.io/#!./pages/githubissues.md), if one click the link __Return to [First Steps](http://open-learning-exchange.github.io/#!./pages/firststeps.md)__ at the bottom, it would be better if the page is redirected at the corresponding step number (here [step 6](http://open-learning-exchange.github.io/#!./pages/firststeps.md#Step_6_-_GitHub_Issues_Tutorial)).

**Comment by daisywatson** [comment]
Do you mean that each page should return to its corresponding step number or just step 6?

**Comment by xyb994** [comment]
I think this is a good suggestion. When I was doing FirstSteps, it did take a look of scrolling to navigate around the page, the table of content section on the left side is helpful though.

**Comment by MadagascarOLE** [comment]
@daisywatson yes,  i mean  each page  should return to its corresponding  step number

**Comment by MadagascarOLE** [comment]
I  think that adding  an anchor-like link in the form of **#Step_StepNumber_-_Title_of_the_step**  after each **(firststeps.md)** link would make each page return to its corresponding step number
