### ISSUE TITLE
Update the Logo

### ISSUE THREAD

**Issue by bsocial** [open-learning-exchange/open-learning-exchange.github.io#1168]
We need to update the default OLE logo that is used-in the user interface. 

![ole-logo](https://user-images.githubusercontent.com/4063398/29883027-e99f06aa-8d7c-11e7-978f-3370962baae7.png)

**Comment by bsocial** [comment]
See the old logo in this image. 
![logo-placement-example](https://user-images.githubusercontent.com/4063398/29883768-3f547254-8d7f-11e7-9acc-8c4546469a06.png)

**Comment by kylemathias** [comment]
were exactly dose it need to be updated? Could you enplane were exactly you want the change to take place and why?

**Comment by bsocial** [comment]
Hey Kyle. I missed categorized this issue. It should have appeared under bell-apps [here >](https://github.com/open-learning-exchange/BeLL-Apps/issues/1010)
