### ISSUE TITLE
"#" after Headers

### ISSUE THREAD

**Issue by Ahmaddahshan** [open-learning-exchange/open-learning-exchange.github.io#117]
Next to all of the assignments there is "#" that doesn't do anything.

**Comment by Ahmaddahshan** [comment]
Or is it just Markdown?

**Comment by i5o** [comment]
Look at this: http://open-learning-exchange.github.io/ll_CC/#!index.md#Assignment_#1
The # put that in the address bar, if you copy that and send it to someone, this someone will directly jump to Assignment 1

**Comment by Ahmaddahshan** [comment]
Yeah that make sense :)
