### ISSUE TITLE
Repetitive content on GitHub Issues on FirstSteps

### ISSUE THREAD

**Issue by MadagascarOLE** [open-learning-exchange/open-learning-exchange.github.io#1175]
in the introduction section of [GitHub Issues](http://open-learning-exchange.github.io/#!./pages/githubissues.md#Introduction), the sentence 
> On GitHub, each repository has a section where issues can be added, discussed, and fixed as a means of categorizing and addressing problems we find. Issues are often opened by our team to fix software bugs on the BeLL and in our code is repeated twice.  
  
**May be one should keep only one of that sentence**

**Comment by MadagascarOLE** [comment]
To fix that issue,  the repetitive sentence in the file githubissues.md should be deleted.

**Comment by kylemathias** [comment]
Nice find, i would say just delete "Issues are often opened by our team to fix software bugs on the BeLL and in our code is repeated twice." Go ahead and make the pull request and changes.

**Comment by xyb994** [comment]
Closing this as PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1180 was merged
