### ISSUE TITLE
Link to step 4 in the Sync With the Nation

### ISSUE THREAD

**Issue by MadagascarOLE** [open-learning-exchange/open-learning-exchange.github.io#1176]
In the Sync With the Nation [section](http://open-learning-exchange.github.io/#!pages/nation.md#Sync_With_the_Nation) of the Nation BeLL [step](http://open-learning-exchange.github.io/#!pages/nation.md), it would be nice to convert the Step 4 words into a link that will redirect to that step  

> In Step 4, you did 3 kinds of updates ...

That would act as a reminder of that step !!!

**Comment by MadagascarOLE** [comment]
To fix that , i'm planning to add a link to the [Different Kind of Updates to Your Community](http://open-learning-exchange.github.io/#!pages/bellapps.md#Different_Kinds_of_Updates_to_Your_Community) in the section
>In Step 4, you did 3 kinds of updates ...

**Comment by kylemathias** [comment]
This change seems fine. Go ahead and make the pull request and the change.

**Comment by xyb994** [comment]
Closing this as PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1181 was merged
