### ISSUE TITLE
Planet User Manual File don't use local file in fork (Rawgit or on personnal copy)

### ISSUE THREAD

**Issue by MadagascarOLE** [open-learning-exchange/open-learning-exchange.github.io#1177]
In the First Steps page, and on the third point of the [Introductory Steps](http://open-learning-exchange.github.io/#!pages/firststeps.md#Step_0_-_Introductory_Steps), there is a link to the [Planet User Manual](http://open-learning-exchange.github.io/#!pages/planetusermanual.md).  
The problem is that, when we work on our local repository, that link still reference the [remote link](http://open-learning-exchange.github.io/#!pages/planetusermanual.md).
If think that we should convert that link to a relative one that reference the local *planetusermanual.md*
 In doing that, we can avoid some problems that may occurs when modifying that file.

**Comment by MadagascarOLE** [comment]
Deleting the `http://open-learning-exchange.github.io` part of the link would resolve this.
>`You may also reference the [Planet User Manual](http://open-learning-exchange.github.io/#!pages/planetusermanual.md)`

**Comment by kylemathias** [comment]
Nice find. Go ahead and make the changes and the pull request.
