### ISSUE TITLE
repetitive note with missing words on gitandrepositories.md file

### ISSUE THREAD

**Issue by cramartef** [open-learning-exchange/open-learning-exchange.github.io#1178]
at the summary section, the note is written twice but the words **rebasing and merging** are missing in the first note.
>The solution is just to delete the first note. [#1179](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1179/commits/1b44995e941a5d8cf41406bdd5df401cd49eb944)

**Comment by xyb994** [comment]
Closing this as PR #1179 was merged.
