### ISSUE TITLE
Image in gitandrepositories.md Needs Update

### ISSUE THREAD

**Issue by mhalqurashi** [open-learning-exchange/open-learning-exchange.github.io#118]
The image in http://open-learning-exchange.github.io/ll_CC/#!pages/gitandrepositories.md is different from the actual page. In the actual page GitHub page, to copy a link, one must click on the green button that says Clone or Download to find and copy the link.

**Comment by dogi** [comment]
@mhalqurashi go for it

**Comment by DrewPerlman** [comment]
#126 fixed this, this issue can be closed
