### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by MbinSophie** [open-learning-exchange/open-learning-exchange.github.io#1183]
Hi everyone, 
May someone can Help me cos I start my training this morning and I couldn't install my vagrant. 
Fisrt of all my system is lunixmint (ubuntu's family),so I used all commands 
    sudo apt-get install git => ok
    sudo apt-get install virtualbox => ok
But in this last one (  sudo apt-get install vagrant) I had this problem: 
    Lecture des listes de paquets... Fait Construction de l'arbre des dépendances       
    Lecture des informations d'état... Fait
    E: Impossible de trouver le paquet vagrant

which means as my mind  that it can't find the package vagrant. 

Thanks before hand for your help and hope to hear soon from you. 
Kind regards 
Sophie (Madagascar)

**Comment by kylemathias** [comment]
Issues are for bringing up issues that need to be fixed about the Wiki. Please use our [gitter ](https://gitter.im/open-learning-exchange/chat)to get help for questions.
