### ISSUE TITLE
Indeed link no longer works

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1184]
## Problem
Links to indeed job description in following two places are no longer working:
<https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/faq.md#q3-where-can-i-find-more-information-about-this-internship>

<https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/firststeps.md#the-big-picture>

## Solution
It's likely caused by listing title change. Update the link to: 
<https://www.indeed.com/jobs?q=%22virtual%20remote%20software%20engineer%20intern%22&l=Cambridge%2C%20MA>

`[here on Indeed](https://www.indeed.com/jobs?q=%22virtual%20remote%20software%20engineer%20intern%22&l=Cambridge%2C%20MA)`

Or

get a [company page](https://www.indeed.com/hire/company-pages) and link to the company page's job section?

**Comment by ajGingrich** [comment]
I can change the link to the suggested indeed page if that is the preferred method.

**Comment by kylemathias** [comment]
Go ahead and make the pull request and change.
