### ISSUE TITLE
Format for text on First Steps (Step 6 and Step 8)

### ISSUE THREAD

**Issue by ajGingrich** [open-learning-exchange/open-learning-exchange.github.io#1185]
On `firststeps.md`, the text formatting for Step 6 and 8 isn't the most user friendly. Both are extremely large paragraphs which are hard to read. I propose that each step has two different paragraphs.

**Comment by ajGingrich** [comment]
I would like to split **Step 6** in the middle and make everything from *Contribute as much as value as you can in each issue...* into a second paragraph. 

Similarly, I would like to split **Step 8** at *Just as your learning with this Wiki was made possible...*

**Comment by kylemathias** [comment]
Sounds like a fine change, go ahead and make the pull request and reference this issue.
