### ISSUE TITLE
Do not show anchor links on hover for headers

### ISSUE THREAD

**Issue by ajGingrich** [open-learning-exchange/open-learning-exchange.github.io#1186]
I suggest that the anchor links that are used for scrolling to the correct header should not be shown. They are distracting because the user is already at that location so the link only refreshes the page with no additional help.

![ole-anchorlink](https://user-images.githubusercontent.com/22775484/30039571-568e6cf8-9190-11e7-847d-0d290ac69ebb.png)

**Comment by kylemathias** [comment]
Go ahead and make the change.
