### ISSUE TITLE
Fix/Broken Image Link on my Andrew Gingrich's Personal Page

### ISSUE THREAD

**Issue by ajGingrich** [open-learning-exchange/open-learning-exchange.github.io#1187]
I hosted my image in a public folder on Dropbox. As of Sept 1, Dropbox no longer allows this folder to be used publicly. The page can be seen here:

https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/profiles/ajGingrich.md

**Comment by ajGingrich** [comment]
I would like to replace this link with a working version - http://i.imgur.com/NOBNao6.png

**Comment by dogi** [comment]
@ajGingrich oops go for it ;)
it was your right from the get go ...

PS: @open-learning-exchange/virtual-interns tiny vote if fixes of this matter should also count as part of step8 ?
