### ISSUE TITLE
Add more instruction to firststeps.md Step 0

### ISSUE THREAD

**Issue by cramartef** [open-learning-exchange/open-learning-exchange.github.io#1195]
At [Step 0 - Introductory Steps](http://open-learning-exchange.github.io/#!pages/firststeps.md#Step_0_-_Introductory_Steps), It is better to say that we need to create a Github account. 
>2. **Create a Github account then** watch Open Learning Exchange and Follow Leonard and Dogi on GitHub. In GitHub we "Watch" organization repositories and "Follow" individuals. When you are on a repository, look for this button at the top right of the page. Also follow each other to see what others in the group are doing.

Instead of:

>2. Watch Open Learning Exchange and Follow Leonard and Dogi on GitHub. In GitHub we "Watch" organization repositories and "Follow" individuals. When you are on a repository, look for this button at the top right of the page. Also follow each other to see what others in the group are doing.

Here is [how to fix it](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1196/files)

**Comment by kylemathias** [comment]
agreed.

**Comment by cramartef** [comment]
I have done it with @Yurockkk 's suggestion.
