### ISSUE TITLE
Misspelt word at vagrant.md

### ISSUE THREAD

**Issue by cramartef** [open-learning-exchange/open-learning-exchange.github.io#1197]
There is a mispelt word at [macOS section](http://open-learning-exchange.github.io/#!./pages/vagrant.md#macOS)
>location

instead of:

>locaiton

Here is [how to fix it](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1198/files)

**Comment by kylemathias** [comment]
k. go ahead and make the fix.

**Comment by xyb994** [comment]
Closing this as [PR #1198](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1198) was merged
