### ISSUE TITLE
Add a link and more instructions at Tech genius Support section

### ISSUE THREAD

**Issue by cramartef** [open-learning-exchange/open-learning-exchange.github.io#1203]
There should be a link  to [Clone your GitHub repository username.github.io](http://open-learning-exchange.github.io/#!./pages/gitandrepositories.md#Clone_your_GitHub_repository_username.github.io) at the word **clone**
>![img0](https://user-images.githubusercontent.com/31341957/30212773-12487724-94af-11e7-8741-17864ada2802.PNG)

And It is better to add more details at Step 3 - **`If you are using windows`**. The same as:
>![img01](https://user-images.githubusercontent.com/31341957/30212963-b11bac18-94af-11e7-8085-fe77b789c31c.PNG)

And also, maybe a note that says: we need to turn off vagrant for vi, before starting the community one.
ie:
>1.vagrant halt
>2. cd ..
>3. cd ole--vagrant-community
>4. vagrant up

**Comment by bsocial** [comment]
Sweet - @cramartef knows his stuff! 

Issue 1:  A link to clone details, definitely. Please add this. 
Issue 2:  Halting the vi community. You can have two running at the same time. However, it does consume resources and the user should be aware. I agree that halting the vi community is preferable. Perhaps it needs additional language such as, 

> At this point you will have two virtual machines installed and running on your computer. In order to conserve hardware resources and to keep things clean and simple it is best to halt the original (ole--vagrant-vi) community. 

```
1.vagrant halt
2. cd ..
3. cd ole--vagrant-community
4. vagrant up
```
Would you please pull, implement and push. Each should be done as separate pull requests. 

Thanks and excellent work!

**Comment by cramartef** [comment]
thanks. I'll making the second issue

**Comment by xyb994** [comment]
Closing this as PR #1212 was merged.
