### ISSUE TITLE
Adding reference/reading-material-link to Markdown Wiki

### ISSUE THREAD

**Issue by yywmm1991** [open-learning-exchange/open-learning-exchange.github.io#121]
How about adding one more tab to the Markdown Wiki: http://open-learning-exchange.github.io/ll_CC/#!index.md , that would include all related links we can refer to and any possible reading materials which can help us understand some important concepts. For example, git/vagrant/vbox help page, reading PDFs, any potential technology related to the intern.

**Comment by DrewPerlman** [comment]
Good idea, I think a helpful link section could be useful in the FAQ.

**Comment by sthak004** [comment]
@yywmm1991 Good idea! 

However, the link you are referring to is broken. I'm assuming this post was made before the II_CC structure was removed. Perhaps you are referring to http://open-learning-exchange.github.io/#!index.md.

**Comment by aberdean** [comment]
Got it started and added a helpful videos section as well.
Before:
![links_before](https://cloud.githubusercontent.com/assets/4922217/18348277/b8e2939e-75ca-11e6-9983-8e4504e1ea91.png)

After:
![links_after](https://cloud.githubusercontent.com/assets/4922217/18348284/c181b886-75ca-11e6-818f-01d34d725054.png)

**Comment by aberdean** [comment]
Actually, I added also a cheatsheet for vi.

**Comment by aberdean** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/275/commits/5693e7a4d91fb26d44829e8f794e4cf4a2b91865
