### ISSUE TITLE
Error in Github and Markdown page

### ISSUE THREAD

**Issue by ExaMind** [open-learning-exchange/open-learning-exchange.github.io#1210]
In the [GitHub and Markdown page](https://rawgit.com/ExaMind/ExaMind.github.io/open-learning-exchange-sudarshan/#!./pages/githubandmarkdown.md) on the [Post a link to your repository in chat](http://open-learning-exchange.github.io/#!./pages/githubandmarkdown.md#Post_a_link_to_your_repository_in_chat) section the instructions say that you have to post a link to your github.io website on gitter chat. 

I think the example shown in the [Post a link to your repository in chat](http://open-learning-exchange.github.io/#!./pages/githubandmarkdown.md#Post_a_link_to_your_repository_in_chat) section   is a bit confusing:
![image](https://user-images.githubusercontent.com/11600539/30251294-fe183cbc-962a-11e7-90ff-1df1391304ae.png)

It should say @dogi look at https://EmilyLarkin.github.io and https://EmilyLarkin.github.io/#!pages/profiles/EmilyLarkin.md

**Comment by ajGingrich** [comment]
good catch. Go ahead and make the changes.

**Comment by xyb994** [comment]
Closing this as PR #1222 was merged.
