### ISSUE TITLE
Rewrite instruction in the Create a Commit section under GitHub Issues

### ISSUE THREAD

**Issue by ExaMind** [open-learning-exchange/open-learning-exchange.github.io#1211]
I think the first two sentences under [Create a Commit](https://rawgit.com/ExaMind/ExaMind.github.io/open-learning-exchange-sudarshan/#!./pages/githubissues.md#Create_a_Commit) should be replaced with the following:

After you are done with the changes use the _git status_ command to see which files in the working directory have been modified. If you wish to stage all of the modified files shown use the _git add ._  (The '.' is part of the command.) command. Otherwise you can choose only the file or files you wish to stage by using the _git add file1, file2 ..._  command.

I feel the second sentence currently in the [Create a Commit](https://rawgit.com/ExaMind/ExaMind.github.io/open-learning-exchange-sudarshan/#!./pages/githubissues.md#Create_a_Commit) is not clear.

**Comment by kylemathias** [comment]
@ExaMind i agree. Go ahead and make the change and the pull request.

**Comment by xyb994** [comment]
Closing this as PR #1220 was merged.
