### ISSUE TITLE
Need a minor edit in step0.

### ISSUE THREAD

**Issue by ExaMind** [open-learning-exchange/open-learning-exchange.github.io#1213]
I think the third sentence in step 2 of [Step 0-Introductory Steps](https://rawgit.com/ExaMind/ExaMind.github.io/open-learning-exchange-sudarshan/#!./pages/firststeps.md#Step_0_-_Introductory_Steps) needs to be changed for better clarity. The sentence can be replaced with the following:

When you are on a repository, look for the Watch button at the top right of the page.

I am explicitly mentioning which button you should be looking for.

**Comment by bsocial** [comment]
Looks good. Suggest a minor edit:

> Look for the 'Watch' button at the top right of the page when you are in a repository.

But either way works.
