### ISSUE TITLE
Formatting issue on Vagrant Tutorial

### ISSUE THREAD

**Issue by jwill12** [open-learning-exchange/open-learning-exchange.github.io#1228]
The "Note" that reminds us what the command 'vagrant destroy' is capable of, should have a space formatted before the description begins. See below.

>**NOTE**:Remember, by using `vagrant destroy`, you destroy the machine and will need to rebuild a community BeLL if you wish to use it at a later time.

**Comment by xyb994** [comment]
Make sense, go ahead and make the PR.
