### ISSUE TITLE
Formatting issue on BeLL Tutorial (Vagrant page)

### ISSUE THREAD

**Issue by jwill12** [open-learning-exchange/open-learning-exchange.github.io#1229]
Fix formatting of issues when commands are brought up, on Vagrant page Tutorial

1. 

>In case you accidentally used vagrant destroy:
-Rebuild the community BeLL following step 4
-etc....

Here 'vagrant destory' is mentioned, but we should `highlight to something like this`, to make it clear to users that this is a command.

2.

>When typing the command "vagrant up" in OSX, you may experience an error such as the following: "vi: Box 'ole/jessie64' could not be found. Attempting to find and install...". A simple solution is to perform the command below. sudo rm /opt/vagrant/embedded/bin/curl This will remove the old version of curl and vagrant should now work as usual.

And here 'vagrant up' is mentioned, and again we should `highlight`, to make it clear to users.

**Comment by xyb994** [comment]
Make sense, go ahead and make the PR.
