### ISSUE TITLE
Team member page isn't formatted like on GitHub

### ISSUE THREAD

**Issue by DrewPerlman** [open-learning-exchange/open-learning-exchange.github.io#123]
I noticed that my personal team member page on the website has some extra line breaks that aren't present on the GitHub version. Though this is a bit of a nitpicky issue, I'm not sure what's causing the discrepancy in formatting.
![teammempagecomparison](https://cloud.githubusercontent.com/assets/5914639/15843589/ef53ad96-2c28-11e6-89b7-85e9736fc205.png)

**Comment by DrewPerlman** [comment]
It seems that the GitHub version ignores whitespace in the raw markup code, but the github.io website doesn't. Though I don't know how other people want their pages formatted, I'll go ahead and fix my own page to account for the whitespace.

**Comment by dogi** [comment]
+1

**Comment by DrewPerlman** [comment]
#128
