### ISSUE TITLE
Format issue on Tutorial (BeLL Communities & Nation page)

### ISSUE THREAD

**Issue by jwill12** [open-learning-exchange/open-learning-exchange.github.io#1230]
Some other formatting issues on tutorial. Just want to highlight and make it clear when users see the "Update Available" and "Publications", they know its an instructional link to press.

>First, click the "Update Available" button and it will reload your homepage with a successful update message. An update refers to a new software update which improves the software. Next, click on "Publications", under the Manager page, and sync the publications. Publications add new resources or courses to your library. Last, repeat the process of sending an activities sync to the nation.

**Comment by ajGingrich** [comment]
Where exactly are you planning on inserting/updating this text? Can you be more specific? I also don't think an update needs to be described because this is general knowledge.
