### ISSUE TITLE
Dead links on firststeps.md

### ISSUE THREAD

**Issue by DrewPerlman** [open-learning-exchange/open-learning-exchange.github.io#124]
Many of the links on firststeps.md don't link to the right page. For example, the link to the "GitHub and Markdown page" leads to http://open-learning-exchange.github.io/ll_CC/#!pages/pages/githubandmarkdown.md instead of http://open-learning-exchange.github.io/ll_CC/#!pages/githubandmarkdown.md.

**Comment by DrewPerlman** [comment]
This happened when the assignments were moved to the new firststeps.md and index.md was made into the homepage.

**Comment by dogi** [comment]
good job please fix

**Comment by mussera** [comment]
I found a solution for the dead links and have opened a pull request for it.
