### ISSUE TITLE
Replace "Markdown Wiki" with "MDwiki" on GitHub and Markdown page

### ISSUE THREAD

**Issue by tarxv** [open-learning-exchange/open-learning-exchange.github.io#1242]
[GitHub and Markdown](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md)
"Markdown Wiki" and "MD Wiki" are never used as alternative names for MDwiki by its developers.
It would be clearer to stick with MDwiki.

**Comment by kylemathias** [comment]
Agree. Go ahead and make the changes and pull request.
