### ISSUE TITLE
Rewrite unclear note on GitHub and Markdown page

### ISSUE THREAD

**Issue by tarxv** [open-learning-exchange/open-learning-exchange.github.io#1244]
[GitHub and Markdown](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md)
> NOTE: Always pay attention when you are working on GitHub, to make sure you work on your own personal account and not on Open Learning Exchange GitHub account.
Once again, it is very important to distinguish between your personal GitHub account and the Open Learning Exchange account. As we want to keep a 'clean' version of our code, everyone forks the repositories, commit their changes to their own personal version of the repository, and then send the changes back to the Open Learning Exchange repository for approval (called a pull request), before the Open Learning Exchange code is updated.
Please, make sure to ALWAYS work on your own personal account via forking and pull requests.

I'm not sure about the meaning of this since I suppose most contributors don't have access to the OLE account

I would rewrite it as:
> NOTE: Make sure you are looking at the forked repo instead of the original Open Learning Exchange repo before working on it. Forks let you make changes to a project without affecting the original repository. You can fetch updates from or submit changes to the original repository with pull requests.

**Comment by kylemathias** [comment]
@tarxv These are the changes i really like. Taking a large chunk of text and refining it to a concise and clear few sentences. Helps remove clutter and makes things easier to read and understand. Make the changes and the PR.
