### ISSUE TITLE
Different chat windows for different topics

### ISSUE THREAD

**Issue by agaikwad4** [open-learning-exchange/open-learning-exchange.github.io#125]
I think there should be some facility to flag your messages topic wise. For e.g. I have a doubt about topic "x". Since we are discussing all the topics in the same chat window its difficult for me to go through all the messages once again and look for my topic of interest. 

But if we have flags, I can simply click on the flag "x" and there it is!! I will be able to find all the information.

**Comment by dogi** [comment]
I don't disagree, unfortunately gitter does not support this functionality.  In the future we will maybe find a better tool -- we are at the moment committed to it.

I'm going to close this issue, but feel free to continue discussing this issue here if you would like.
