### ISSUE TITLE
MDwiki Restructuring Proposal

### ISSUE THREAD

**Issue by bsocial** [open-learning-exchange/open-learning-exchange.github.io#1258]
Hi @/all,

As many of you know we are quickly adding support documents and how-to manuals for Tech Genius', and reworking existing Virtual Intern documents. Over the years many different people created document and image files.  As a result it is oven difficult or impossible to tell what purpose is served by a particular document or image. In short, the MDwiki has grown cumbersome and confusing. A quick look at the [#!pages/uploads/images/](https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/master/pages/uploads/images) folder demonstrates this nicely... ;) More importantly, we do not have a way to easily list and reference new Tech Genius related documentation. 

In an effort to bring some order to what exists and to create a place for Tech Genius on-boarding, I have taken a first attempt at this effort. Please see this background document for [a detailed overview of the proposed changes to the file structure here](https://docs.google.com/a/ole.org/document/d/1sxT_P87OlHINLk2E-Q3DMfZfeqpRfYl4sBj3zC2shXE), have a look at [the TheBigRewrite branch here](https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/TheBigRewrite), and [see the rawgit of the proposed landing page here](https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/TheBigRewrite/#!index.md). 

If at all possible I would like to push this through. The longer we wait the more changes will be made in existing files. More importantly we need to start pushing the Tech Genius documents to our partners in the field. 

You help very much appreciated!!

**Comment by bsocial** [comment]
As part of this effort I renamed most of the .md and image files. I have now touched nearly every .md page we have updating links to other pages and images. NOTE that I have not yet touched any of the profile pages. Those will likely need to be updated, too, as their locations have changed. The Members page will also need work as they have been broken out into two folders, ../techgenius/members/ and > ../vi/members/

**Comment by bsocial** [comment]
sorry - wrong path. ../techgenius/profiles/ and ../vi/profiles/ 

I looked at many of the member profiles. None of them needed updating for path issues related to the new structure.

**Comment by bsocial** [comment]
OK so... I have chased down many broken links and images. I think this is nearly ready to go. I would love to have input and/or to push it forward. 

The last remain issue is how to treat the Virtual Intern section. Right now it includes both intern-on-boarding steps (first steps) and ongoing projects (Automated Testing, Crowdin Integration, Windows Installer, etc.). Likely these need to be broken out to separate them from the intern tasks and to make the intern sub-menu more manageable. 

Thoughts on how t do this? seems that they will need their own menu item. Code Projects? Projects? Anyone?

**Comment by lmmrssa** [comment]
@bsocial One thing i would like to have changed is regarding tablet setup which says that you need USB-A to USB-C for transferring file. I don't think all tablets have USB-C to use as OTP also it will require OTP enabled. So it would be better to either elaborate or give simple solution for that, like getting from some online store or by direct connection to PC.
