### ISSUE TITLE
Update screenshot in "GitHub and Markdown"

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1261]
[This screenshot](http://open-learning-exchange.github.io/pages/vi/images/vi-create-pull-request.png) in [GitHub and Markdown](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md) is kind of confusing incoming virtual interns. See [this PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1202) and [this PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1259).

Instead of using `[description](url)`, the following is used in the screenshot.
```
[description]
(url)
```

**Comment by kylemathias** [comment]
@xyb994 Sounds like a fine fix. You can go ahead and make the changes, or a inspiring intern can.

**Comment by xyb994** [comment]
Oh, I see why it looks like that in the original screenshot. Try "Edit comment" and you'll see...

[rawgit](https://rawgit.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/profiles/YourUserName.md)
