### ISSUE TITLE
Step 0- Introductory Steps formatting issue

### ISSUE THREAD

**Issue by amanuely** [open-learning-exchange/open-learning-exchange.github.io#1266]
If you look at the Step 0- Introductory Steps found  [here](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md)
You see that the formatting looks something like this. 

Step 0- Introductory Steps
1) Send us your resume again ......
2) Create a GitHub account then watch....
1) We use Crowdin to translate our user interface ...

I think number 1 in the third line is a typo and it was supposed to be 

3) We use Crowdin to translate our user interface ...

**Comment by amanuely** [comment]
@dogi 
@xyb994

**Comment by xyb994** [comment]
If you look at the [raw document](https://raw.githubusercontent.com/open-learning-exchange/open-learning-exchange.github.io/master/pages/vi/vi-first-steps.md), it is numbered `3.` It's actually rendered correctly in [GitHub's Markdown rendering](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-first-steps.md). MDwiki has some slightly different flavored way of rendering ordered list when there are images between items. 

I actually [fixed](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1116/files) it a few month back, but it seems like this was reintroduced during the big structure change of our MDwiki. You can go ahead and fix it in whatever way it looks right in MDwiki.

Some related links:
- According to [documentation](https://daringfireball.net/projects/markdown/syntax#list) from John Gruber (Markdown's creator), the number does not even matter
- [Wikipedia Markdown - Standardization](https://en.wikipedia.org/wiki/Markdown#Standardization)

**Comment by amanuely** [comment]
@xyb994  you are right, it is rendered correctly on Github's markdown rendering.

**Comment by kylemathias** [comment]
@amanuely If you are still working on this go ahead and reopen this Issue.
