### ISSUE TITLE
Update vi "Track Progress" page

### ISSUE THREAD

**Issue by thesiege208** [open-learning-exchange/open-learning-exchange.github.io#1271]
* some minor formatting tweaks (extra spaces, capitalization, etc)  
* add link to "First Steps" page for convenience  
* update  step 3:
    > Remember, in order to complete the First steps you need atleast 5 PR's and 3 issues.

**Comment by thesiege208** [comment]
Fixed. See PR #1272.

**Comment by kylemathias** [comment]
This was fixed and merged #1272 . If you are going to re open the issue, let us know why next time.
