### ISSUE TITLE
"intern orientation document" under step 9 of "first steps" DNE

### ISSUE THREAD

**Issue by thesiege208** [open-learning-exchange/open-learning-exchange.github.io#1273]
> Once you have been added to the team, read through the [intern orientation document](http://open-learning-exchange.github.io/#!./pages/vi/vi-intern-orientation.md).  

This file does not exist and I can't find it (was it deleted or moved?).

**Comment by amanuely** [comment]
@thesiege208 Good catch. I found the document and fixed the link. See PR #1283
