### ISSUE TITLE
Add more details to step 6- Clone your github repository username.github.io

### ISSUE THREAD

**Issue by amanuely** [open-learning-exchange/open-learning-exchange.github.io#1274]
I think this [step](https://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md) is very important for anyone who has  never used git . Therefore, adding a  more detailed instruction would be helpful. 

I would add the following sentence  right after the screenshot

1) Create a new folder somewhere on your OS. Navigate to the folder using `cd`.

 Then after cloning the repository,

 2) If you  `cd  `   into your  `Username.github.io `  you can see different files which you will be working on during your internship.

**Comment by kylemathias** [comment]
Are you still working on this? If so, reopen the issue.
