### ISSUE TITLE
format/writing convention tweaks to vi faq page

### ISSUE THREAD

**Issue by thesiege208** [open-learning-exchange/open-learning-exchange.github.io#1276]
Just a few capitalization/spacing/formatting tweaks for better readability, as well as fixing the link to Q16 (currently does not work because link is missing a #).

**Comment by thesiege208** [comment]
Fixed, See #1277.

**Comment by kylemathias** [comment]
Closing this out. This was split into 2 different pull request to fix an issue. (#1295 #1299)
