### ISSUE TITLE
unnecessary linking

### ISSUE THREAD

**Issue by amanuely** [open-learning-exchange/open-learning-exchange.github.io#1282]
On [this](https://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md) page, under **Start Here** the summary of the steps are given as a link element.Those link elements don't work and I think the linking is unnecessary given that all the information is on the same page.

**Comment by bsocial** [comment]
The links are there for convenience. TOC / Anchor links.

**Comment by kylemathias** [comment]
This issue was fixed https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1283
