### ISSUE TITLE
Conference Calling Intro

### ISSUE THREAD

**Issue by bsocial** [open-learning-exchange/open-learning-exchange.github.io#1287]
I created this document to provide a brief introduction / background on conference calling via hangouts and/or other services. We seem to run into the same etiquette issues over and over - MUTE the microphone, etc. ;)

Would someone please troubleshoot the rawgit link for me? Can't figure out what I am doing wrong...

[See pull request 1286](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1286).

**Comment by xyb994** [comment]
@dogi, can we put [Conference Calling](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1286/files) under robots/resources?
