### ISSUE TITLE
Dummy user password warning

### ISSUE THREAD

**Issue by DrewPerlman** [open-learning-exchange/open-learning-exchange.github.io#130]
Since anyone logged in as an admin on the Nation BeLL can see all of the information for each community user under the "Members" tab, it would be helpful to put a warning on nation.md not to use a password for the dummy user that you wouldn't want others to see.

**Comment by DrewPerlman** [comment]
We should also consider making users' passwords hidden for Nation BeLLs used in the real world, as this is a pretty significant security/privacy issue.

**Comment by sente** [comment]
Yes. I could not agree more.

This is being implemented, the passwords won't be stored, but instead a salted hash.
