### ISSUE TITLE
Some grammar errors in tg-library-management.md

### ISSUE THREAD

**Issue by Dashlorde** [open-learning-exchange/open-learning-exchange.github.io#1307]
In the [library management](http://open-learning-exchange.github.io/#!pages/techgenius/tg-library-management.md),  _"Type the name name and description of the collection"_, there are two "name" .

**Comment by Dashlorde** [comment]
fixed, see [#1312](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1312)

**Comment by kylemathias** [comment]
Was Fixed, closing it out.
