### ISSUE TITLE
Instructions clarification on vagrant.md: vagrant up each time

### ISSUE THREAD

**Issue by DrewPerlman** [open-learning-exchange/open-learning-exchange.github.io#131]
For vagrant.md, I think it might be helpful to put a note saying that it is necessary to `vagrant up` each time you want to run the local community BeLL.

**Comment by dogi** [comment]
Hmm - this are 2 different issues
as I agree on both we maybe split them up first and then try to solve them

**Comment by DrewPerlman** [comment]
Ok, I split it into 2 issues.

**Comment by DrewPerlman** [comment]
Turns out that it mentions to vagrant up when you want to run the community BeLL on your computer on bellapps.md, so no change is needed.
