### ISSUE TITLE
Broken link to FAQ

### ISSUE THREAD

**Issue by aas919** [open-learning-exchange/open-learning-exchange.github.io#1322]
The link to FAQ in Windows section at [Configuration Guide](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations.md) is broken and displays error Sorry, the page you are looking for doesn't exist. Go home when clicked.

The link should refer to http://open-learning-exchange.github.io/#!pages/vi/vi-faq.md

**Comment by amanuely** [comment]
@aas919 Thanks for catching this issue. In the future, it would nice if you reference your PR number related to the issue in the comment section, once you resolve the issue.
e.g  see PR #1323

**Comment by kylemathias** [comment]
Closing this, it seems this was fixed.
