### ISSUE TITLE
Use which profiles folder?

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1325]
A recent structure change moved original virtual interns' profile folder to [_pages/vi/profiles_](https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/master/pages/vi/profiles). Since tech geniuses and virtual interns share the same [First Steps](http://open-learning-exchange.github.io/#!./pages/vi/vi-first-steps.md) document, maybe we should use [_pages/profiles_](https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/master/pages/profiles) as a general place to store profiles? 

Or add a _profiles_ folder to [_pages/techgenius_](https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/master/pages/techgenius)?

**Comment by dogi** [comment]
thanks @xyb994 - very good issue
@bsocial right now @MadagascarOLE and @dogi left the techgenuises in vi/profiles
but since you are the driver in the structure change wonder what you think ...

**Comment by xyb994** [comment]
@dogi I think by using _pages/profiles_ would cause less confusing and make shared documentation simpler, but it will need quite some files movement. Either way, http://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md needs some update.

**Comment by kylemathias** [comment]
Was changed and Merged. Closing
