### ISSUE TITLE
Indeed link not working again

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1332]
@dogi Maybe [https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs](https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs) is a more permanent link?

Need to fix at [two places](https://github.com/open-learning-exchange/open-learning-exchange.github.io/search?utf8=✓&q=https%3A%2F%2Fwww.indeed.com%2Fjobs%3Fq%3D%2522virtual%2520remote%2520software%2520engineer%2520intern%2522%26l%3DCambridge%252C%2520MA&type=).

**Comment by kylemathias** [comment]
@xyb994 Good fix. I say make the changes. or let some new Virtual interns take advantage of adding to there PR count.
