### ISSUE TITLE
Step 1- Installation in Ubuntu 

### ISSUE THREAD

**Issue by lorugant** [open-learning-exchange/open-learning-exchange.github.io#1339]
In the Note section, the link to downloading the bash file for installation in ubuntu does not seem to be working. It is redirecting to "Sorry page does not exist". I think the path is wrong. It is directing to pages and then techgenius in the repository but there is no uploads in techgenius and the correct link directing to the bash file would be in the repo-pages-uploads-bashscripts-installations.h. Attached are the screenshots I took while clicking the page. Let me know if this is a valid issue or not. Thanks!!!
![screenshot from 2017-10-26 08-41-30](https://user-images.githubusercontent.com/32945884/32054351-2670fb70-ba2c-11e7-841a-a594a1b86164.png)
![screenshot from 2017-10-26 08-42-02](https://user-images.githubusercontent.com/32945884/32054373-30ed9b94-ba2c-11e7-9a58-21a72f8a3ae2.png)

**Comment by kylemathias** [comment]
Go ahead and make the fix. Create a Pull request.

**Comment by xyb994** [comment]
Closing this, the installation script for Ubuntu was removed since it's not that long at all. It would be better for VI run line by line and have a sense of what they are doing.
