### ISSUE TITLE
Making reference to an existing issue

### ISSUE THREAD

**Issue by lorugant** [open-learning-exchange/open-learning-exchange.github.io#1351]
Can I make a reference to the issue #1108 in the text as shown in below screenshot. Someone might get the same doubt as me. Let me know. Thanks!!
![screenshot from 2017-11-07 14-45-01](https://user-images.githubusercontent.com/32945884/32514301-971a734a-c3ca-11e7-8e28-a9721eb2c37b.png)
![screenshot from 2017-11-07 14-43-33](https://user-images.githubusercontent.com/32945884/32514307-9a43b6ee-c3ca-11e7-97bc-695da7e95f14.png)

**Comment by kylemathias** [comment]
making a reference to the issue sounds fine. GO ahead and make the changes and a Pull request.
