### ISSUE TITLE
Add some reference profiles

### ISSUE THREAD

**Issue by lorugant** [open-learning-exchange/open-learning-exchange.github.io#1352]
Should I add some reference profile links so that it would act as a guideline for future interns to create their profile in a more creative way rather than a basic one? Can we add links to top 3 profiles? 

![screenshot from 2017-11-07 14-52-48](https://user-images.githubusercontent.com/32945884/32514734-e869bdfe-c3cb-11e7-98bb-031e51d3d55e.png)
![screenshot from 2017-11-07 14-54-30](https://user-images.githubusercontent.com/32945884/32514738-eca9e470-c3cb-11e7-875b-85e2344353da.png)

**Comment by kylemathias** [comment]
Thats a good idea. Go ahead and add some of our profiles as examples. Pick the best ones! 👍
