### ISSUE TITLE
Condensing the note

### ISSUE THREAD

**Issue by lorugant** [open-learning-exchange/open-learning-exchange.github.io#1355]
With reference to #1350, condensing the note and hint, Can we combine and write a note like 

"Use git-branch to see which branch you are in. Master is the default branch and has to clean of all changes to revert back. Make sure you are on right branch using git checkout branch-name while making  changes and while committing."

![screenshot from 2017-11-10 15-15-39](https://user-images.githubusercontent.com/32945884/32676840-1c93058a-c62a-11e7-89b5-7ac58585f252.png)

**Comment by kylemathias** [comment]
👍 go ahead and make the change and PR.
