### ISSUE TITLE
Installing command for Windows is out of date

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1367]
In step 1 - Installation page - Windows 8.1 and Above: After executing the command, the user is supposed to update VirtualBox and vagrant to newest version

**Comment by kylemathias** [comment]
@yaoxing1990 Im a little confused, Dose VirtualBox and vagrant prompt you to update to the newest version once you open it? I thought both of the scripts have you pull the latest download?

I haven't done a fresh install recently, so i could be wrong. Even if i am wrong, interns should understand already that when they work with software, they should be using updated software.

**Comment by yaoxing1990** [comment]
After I executed the command to install, the virtual machine cannot be launched. After I updated virtual box and vagrant to the newest version, the virtual machine can work normally.

Best Regards,
Xing Yao, MSCS student of UT Dallas
Github: https://github.com/yaoxing1990
LinkedIn: https://www.linkedin.com/in/xing-yao-34161878/
TEL: +1(917)478-2888

**Comment by yaoxing1990** [comment]
@kylemathias I got it. Before creating a new branch to do some changes, I should checkout master first and  then create the new branch from origin master.

**Comment by xyb994** [comment]
`choco install vagrant --version=1.9.2 -y -allowEmptyChecksums`

> we need this version cause in version 1.9.3 they broke a feature we use for windows users ... this is why we stick with 1.9.2

– dogi in gitter chat channel

@yaoxing1990 Is everything working fine for you after the update?

**Comment by yaoxing1990** [comment]
@xyb994 My vagrant version is 2.0.1 and my VirtualBox version is 5.2.0, and it is working as expected

**Comment by xyb994** [comment]
@yaoxing1990 Thanks for the info. I don't have a Windows machine to try the latest version. So maybe we leave this for future interns to verify.

@dogi Could you see any of the issues you mentioned is fixed?https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md

**Comment by xyb994** [comment]
@yaoxing1990 I talked with @dogi. Thank you for raising the issue. As this isn't really a documentation issue in our MDwiki. We'll open an issue in another repo and do more investigation on it.
