### ISSUE TITLE
Nation BeLL tutorial : in step4, no survey is mentioned

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1371]
In "Sync With the Nation" part of Nation BeLL tutorial, the first sentence mentioned 3 kinds of updates in step4. Actually, there are only 2: updates and publications

**Comment by kylemathias** [comment]
Try to screen shot and circle the issue you are talking about. If you dont, anyone who is reading this issue has to go and find what you are talking about rather then focusing on if the change is necessary or not.

This would be the correct example for this issue:
![image](https://user-images.githubusercontent.com/26488295/33041133-20d9a0ca-cdf2-11e7-8e89-194664526909.png)

In the case of this Issue, Publications and Updates Available are the 2 that are showing in that image. There is in fact 3 possible updates you can get, this image is just not showing one of them (its not showing the surveys) .
