### ISSUE TITLE
FAQ: Q3 link "here" refers to nothing

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1373]
When user click "here" in Q3 in FAQ, the page shows "no results"

**Comment by kylemathias** [comment]
It could be that the internship posting was removed. Only make a change to the link of the Wiki if we have a definitive solution to exactly were the link should lead people.

**Comment by xyb994** [comment]
@yaoxing1990 See Issue #1332

**Comment by xyb994** [comment]
Fixed in PR #1473.
