### ISSUE TITLE
Should add "previous" and "next" navigation button in each step page

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1375]
In order to increase the feasibility of the wiki, a "previous" button and a "next" button should be added in each step details page.

**Comment by kylemathias** [comment]
a Previous and next buton would be fine, SO LONG as it brings you back to the [vi-first-steps.md](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md). There is some important information before you proceed to the next step. This "previous" and "next" button could bring you to the header of the next or previous step.

I would say go ahead and make the change.

**Comment by dogi** [comment]
hmm this is a very difficult one to do right ...
