### ISSUE TITLE
"Take the Course" part is not available

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1376]
![capture](https://user-images.githubusercontent.com/10969547/33090371-5ef583f2-ceb9-11e7-89e5-3166723f41ff.PNG)

In "BeLL-Apps: Communities and Nations" section, "Take the course" seems not available, from the screenshot above, after clicking "publications", there is no "course" available.

**Comment by rkinback** [comment]
After sync Publication, click on Courses up on the top menu and your course should be in there.

STEPS:
1. Click on Courses on the top navigation
2. Find the course "Virtual Interns," click on Admission
3. Click on Open
4. Carefully finish 12 steps of the course
5. When you provide feedback, try to be as specific as possible, and include screen shots when necessary
