### ISSUE TITLE
Bad user experience to navigate to translation effort

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/open-learning-exchange.github.io#1382]
While I learning [open-learning-exchange.github.io](http://open-learning-exchange.github.io) wiki again until long time, I spot opportunity for improvement.

In here http://open-learning-exchange.github.io/#!pages/translators/la-introduction.md I think it would better if we put notes that say something like

> start translate now and join our Crowdin in
> planet here
> bell app here
> take home here

Instead of need to navigate to top toolbar and click the translate of the choice. By the way, it is good for first step pull request.
<img width="721" alt="screen shot 2017-11-25 at 10 10 00 pm" src="https://user-images.githubusercontent.com/11813607/33231779-9f3ee6c0-d22d-11e7-9326-6f740a00cfd8.png">

**Comment by kylemathias** [comment]
This whole sections looks like it needs some clarification. I would suggest, if anyone wants to take on making this section easier to read and navigate meet with @dogi in a hangout to find out what the general message this section is trying to convey.

**Comment by mappuji** [comment]
I think this already sorted.
