### ISSUE TITLE
Add "FAQ" tab in left panel

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1385]
One suggestion for main page of First Step: Because "FAQ" is important for user to refer when they have a problem, I suggest adding "FAQ" above "Step 0" in left panel.
![faq](https://user-images.githubusercontent.com/10969547/33234961-d7805322-d1f4-11e7-9493-ab1ecfea954d.PNG)

**Comment by kylemathias** [comment]
FAQ is in the drop down above. If someone was looking for a solution, i would think the drop down would be a place they would look. I think its fine as is.
