### ISSUE TITLE
Add "mailto:xxx@vle.org" in step 0 as a hyperlink

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1386]
Add "mailto:xxx@vle.org" in step 0 as a hyperlink so once user click the link, default email client will be launched.
![email](https://user-images.githubusercontent.com/10969547/33235383-3a2badc0-d1fd-11e7-82a5-89d2af17a9b6.PNG)

**Comment by kylemathias** [comment]
Sounds good to me. Make the changes and the PR.

**Comment by xyb994** [comment]
PR #1389  merged.
