### ISSUE TITLE
Bugs in check progress feature

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1390]
![step8](https://user-images.githubusercontent.com/10969547/33283139-871a4064-d370-11e7-9a98-4e282595f6ef.PNG)
Click "here"
![hint](https://user-images.githubusercontent.com/10969547/33283155-9119a3f2-d370-11e7-8b40-d986743d2029.PNG)
Then after I click "Cancel", the following appears:
![cancel](https://user-images.githubusercontent.com/10969547/33283168-9c2046d4-d370-11e7-9c92-6eaf00bb4f6b.PNG)
And I think the above alert should not appear if "Cancel" is clicked

**Comment by kylemathias** [comment]
@yaoxing1990 i think it was just a place holder response. If you would like to make a change to add a proper response that would be a good change. Go ahead and make the PR and change.
