### ISSUE TITLE
"Return" link should navigate to "First step"

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1392]
![return](https://user-images.githubusercontent.com/10969547/33300004-c1cb3eaa-d3b3-11e7-90a3-3887edac4adb.PNG)
[Check progress](http://open-learning-exchange.github.io/pages/vi/vi-track-progress.html)
After clicking "here", user will be navigated to Welcome page. However, it makes more sense to navigate the user to "First steps" page

**Comment by kylemathias** [comment]
👍

**Comment by yaoxing1990** [comment]
@kylemathias #1393
