### ISSUE TITLE
Possible misleading menu item

### ISSUE THREAD

**Issue by yaoxing1990** [open-learning-exchange/open-learning-exchange.github.io#1395]
![install](https://user-images.githubusercontent.com/10969547/33362920-d50c50ee-d4a3-11e7-970b-74c21a97e17a.PNG)
Although the menu item is for windows, the content actually seems a general guide for windows/mac/ubuntu

**Comment by kylemathias** [comment]
You could change it to just say "Community Installation". When you bring up issues, try to give a solution. go ahead and make the PR and changes.

**Comment by yaoxing1990** [comment]
@kylemathias Thank for your suggestion. And here is the pull request: https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1397

**Comment by dogi** [comment]
`c:/users/USERNAME/ole--vagrant-vi` is clearly windows one ...
anyhow in the case we change that 

we would also have to change the filename and links linking to it

**Comment by yaoxing1990** [comment]
@dogi Fixed, See #1397
