### ISSUE TITLE
Table overlapping

### ISSUE THREAD

**Issue by bani890** [open-learning-exchange/open-learning-exchange.github.io#1405]
![bh](https://user-images.githubusercontent.com/7533475/33511928-3d3e448c-d6f3-11e7-8fd9-b07a174a308c.PNG)

Because of the small size of the table, it overlaps with the left page anchor. The page below is also having the same problem.
 
![cap](https://user-images.githubusercontent.com/7533475/33511994-bfae1f18-d6f4-11e7-9bcf-3542b1716bf3.PNG)

* I   believe the ways to fix it are By changing the plugin code or by adding CSS, HTML to the markdown page.

**Comment by kylemathias** [comment]
@bani890 I agree overlapping tables are bad, but lets see how @dogi and other interns would want this to be fixed. This might be a bigger issue than just this page.

**Comment by xyb994** [comment]
@bani890 What browser are you using? What's the screen size?

**Comment by bani890** [comment]
@xyb994 my viewport size is 1280x615, I am using chrome.

**Comment by thesiege208** [comment]
My laptop screen is bigger but I use Chrome and I can't replicate this issue. When I resize the window, the page elements properly shrink and move around to fit the new window size without overlap. Doesn't seem like there's anything wrong with the HTML/CSS.
