### ISSUE TITLE
Change needed of markdown link in step 3

### ISSUE THREAD

**Issue by ddpatel6469** [open-learning-exchange/open-learning-exchange.github.io#1411]
The markdown link should be http://EmilyLarkin.github.io/#!pages/vi/profiles/EmilyLarkin.md
instead of http://EmilyLarkin.github.io/#!pages/profiles/EmilyLarkin.md in step 3.

![screen shot 2017-12-12 at 1 26 17 am](https://user-images.githubusercontent.com/25786480/33870950-5c4fa580-dede-11e7-9ee6-f2d3c7a9b8e5.png)

**Comment by kylemathias** [comment]
sounds like a simple fix, go ahead and make the change.

**Comment by ddpatel6469** [comment]
Done with changes.
PR #1416
