### ISSUE TITLE
Last two links need to navigate in step 3

### ISSUE THREAD

**Issue by ddpatel6469** [open-learning-exchange/open-learning-exchange.github.io#1413]
Last two links are not able to navigate in GitHub and Markdown page of step 3....

![screen shot 2017-12-12 at 3 07 09 pm](https://user-images.githubusercontent.com/25786480/33908009-0750b89a-df55-11e7-8b9f-fbf297fc9089.png)

**Comment by kylemathias** [comment]
What page is this?

**Comment by ddpatel6469** [comment]
Last two links....

![screen shot 2017-12-13 at 9 18 28 pm](https://user-images.githubusercontent.com/25786480/33972305-3c3daa12-e04b-11e7-822c-041ca270ebe3.png)


http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md

**Comment by kylemathias** [comment]
fixing broken links is always helpful. Go ahead and make the changes and PR.

**Comment by ddpatel6469** [comment]
Done with changes....
PR #1417
