### ISSUE TITLE
Link points to expired post

### ISSUE THREAD

**Issue by kevinnerio** [open-learning-exchange/open-learning-exchange.github.io#1422]
'More information can be found here' link points to: https://www.indeed.com/jobs?q=%22virtual%20remote%20software%20engineer%20intern%22&l=Cambridge,%20MA

Would be better off pointing to the FAQ section of virtual interns tab

<img width="916" alt="redirect link" src="https://user-images.githubusercontent.com/19421857/34323981-fe8385fe-e813-11e7-86df-f6e6c483bbc9.png">

**Comment by kylemathias** [comment]
I think it is fine as is. I FAQ is more answering questions when you get stuck on steps in the first steps.

**Comment by kevinnerio** [comment]
While this may be true about the FAQ section, it does provide more information about the internship. At least on my end, the indeed link points to a page that provides no information about the internship.
<img width="1277" alt="screen shot 2017-12-26 at 9 53 50 pm" src="https://user-images.githubusercontent.com/19421857/34372093-4996a9fc-ea87-11e7-98d4-5ef3f8ad38fa.png">

**Comment by xyb994** [comment]
@kevinnerio see https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1332, I recall asking @dogi on Hangouts and he said using https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs is fine so you could go ahead and create a PR for this.

**Comment by kevinnerio** [comment]
@xyb994 OK I see that https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs is a different link than the one that was being used previously.

**Comment by xyb994** [comment]
Fixed in PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1473
