### ISSUE TITLE
Local_Branch has no upstream 

### ISSUE THREAD

**Issue by kevinnerio** [open-learning-exchange/open-learning-exchange.github.io#1429]
I think interns(new to github) would benefit from specifying that they should push changes from the new-feature-branch, through their master branch. I am not sure if this is the only way to `git push origin name-of-branch` but it sure did make it easier for me. 

<img width="1268" alt="screen shot 2017-12-27 at 1 22 28 pm" src="https://user-images.githubusercontent.com/19421857/34432184-fb37e286-ec29-11e7-85ea-28d61ef8c237.png">

**Comment by yaoxing1990** [comment]
@kevinnerio Nice suggestion, make a pull request
