### ISSUE TITLE
Corrections needed on githubandmarkdown.md

### ISSUE THREAD

**Issue by vimalababu4** [open-learning-exchange/open-learning-exchange.github.io#143]
In GitHub and Markdown repository, capitalization is missing and i found some typos in some of the paragraphs as shown in attached files
[GitHubMarkdown-1.docx](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/310646/GitHubMarkdown-1.docx)
[GitHubMarkdown-2.docx](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/310647/GitHubMarkdown-2.docx)

**Comment by dogi** [comment]
go for it
