### ISSUE TITLE
Clarification on git Diff 

### ISSUE THREAD

**Issue by kevinnerio** [open-learning-exchange/open-learning-exchange.github.io#1430]
Maybe add a screenshot of a real example for this git diff. Or even just a link to youtube video that shows a real example for those interns who actually want to use this command. 

<img width="927" alt="screen shot 2017-12-30 at 2 08 17 pm" src="https://user-images.githubusercontent.com/19421857/34457632-40d26068-ed6b-11e7-8a55-ee5a72be9b1e.png">

**Comment by kylemathias** [comment]
I think the explanation is fin as is. Adding a video for a single git command would be over kill imo.
