### ISSUE TITLE
Formatting FAQ for file vi-faq.md

### ISSUE THREAD

**Issue by TooManySpaces** [open-learning-exchange/open-learning-exchange.github.io#1439]
Make the Answers under "General Internship Questions" inlined so they are a bit easier to read. Right now, it's a bit hard to tell where the question starts and ends off a glance.

For example: 

#### Q1: What will I be working on during this internship?

OLE virtual interns will be helping develop OLE’s BeLL (Basic e-Learning Library) software. The BeLL is a virtual library that is deployed internationally to children in countries that typically do not have access to educational resources.</dd>

Change into:

<dl>
<dt>Q1: What will I be working on during this internship?</dt>

<dd>OLE virtual interns will be helping develop OLE’s BeLL (Basic e-Learning Library) software. The BeLL is a virtual library that is deployed internationally to children in countries that typically do not have access to educational resources.</dd>
</dl>
  
I will be working on this to do my part in Step 8.

**Comment by xyb994** [comment]
There's no way to indent a paragraph using Markdown element alone, we could probably use unordered list to make it easier to read? Let's see what other VI says.

<img width="1552" alt="screen shot 2018-01-08 at 3 31 45 pm" src="https://user-images.githubusercontent.com/7483137/34690959-16b98322-f489-11e7-9040-7adc86dd04ed.png">

**Comment by kylemathias** [comment]
I say make the changes and give us what it would actually look like so we can give a fair assessments to the change.
