### ISSUE TITLE
Updates on nation.md and bellapps.md

### ISSUE THREAD

**Issue by vimalababu4** [open-learning-exchange/open-learning-exchange.github.io#144]
I found some  misspelled words  in nation.md and  bellapps.md as shown in the Attached file
[nation.docx](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/310652/nation.docx)
[bellapps.docx](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/310653/bellapps.docx)

**Comment by dogi** [comment]
go for it
