### ISSUE TITLE
Adding how to enable VT-x/AMD-V in the same paragraph in file vi-vagrant.md

### ISSUE THREAD

**Issue by TooManySpaces** [open-learning-exchange/open-learning-exchange.github.io#1440]
It mentions that VT-x/AMD-V needs to be enabled, but not how to do that. So it would be good to mention quickly how to do that. For example, instead of saying 
"Before installing Vagrant on any platform, it is necessary to check if VT-x/AMD-V instruction set is enabled on your processor"
Say 
"Before installing Vagrant on any platform, it is necessary to check if VT-x/AMD-V instruction set is enabled on your processor by checking the bios."

This saves the person reading this time as most of the things mentioned in that article did not help me. 
  
I will be working on this to do my part in Step 8.

**Comment by xyb994** [comment]
Closing this as PR #1446 was merged.
