### ISSUE TITLE
Broken link on the 'Chat' drop down - Virtual Interns

### ISSUE THREAD

**Issue by BoazOngote** [open-learning-exchange/open-learning-exchange.github.io#1443]
The Virtual Interns Chat drop down on http://open-learning-exchange.github.io/#!pages/vi/vi-chat.md is not working or rather leads to no where. The drop down should be made available and working as the ones of **General Chat** and **Tech Geniuses** 
![screenshot-2018-1-5 gitter not found](https://user-images.githubusercontent.com/10141520/34615686-d34a3274-f246-11e7-8606-a1fafce0ed94.png)

**Comment by BoazOngote** [comment]
The Virtual Interns Chat drop down on http://open-learning-exchange.github.io/#!pages/vi/vi-chat.md is not working or rather leads to no where. The drop down should be made available and working as the ones of **General Chat** and **Tech Geniuses**

**Comment by xyb994** [comment]
These links are not broken, it's about authentication. "General Chat" is available because it's a open chatroom, you could see "Tech Geniuses" chat because you are part of that group. But I do agree this is kind of confusing so maybe there's something we could do to optimize it.

**Comment by BoazOngote** [comment]
Okay 'General Chat' and 'Tech Geniuses' Chats work though the 'Virtual Interns' doesn't work....

**Comment by kylemathias** [comment]
The links for "Interns" and "Tech Genius" don't work for me. If you can find the correct working links for "Interns" and "Tech Genius" then go ahead and make the fix.

**Comment by BoazOngote** [comment]
@kylemathias could you guide...

**Comment by kylemathias** [comment]
> @kylemathias could you guide...

that's part of the process on fixing an issue 😃
