### ISSUE TITLE
Wrong example rawgit link in vi-github-and-markdown

### ISSUE THREAD

**Issue by Jackbui96** [open-learning-exchange/open-learning-exchange.github.io#1449]
Link for gitraw preview is wrong at First step -> Step 3 -> Create a new file as your personal MDwiki page and commit your changes.

![github and markdown](https://user-images.githubusercontent.com/15133304/34755529-6e18504e-f579-11e7-91b7-08153a68cdbb.png)

As its said to use this format: 
https://rawgit.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/profiles/vi/YourUserName.md

But the correct format should be:
https://rawgit.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/vi/profiles/YourUserName.md

**Comment by xyb994** [comment]
@Jackbui96 Good catch, go ahead and create a PR

**Comment by Jackbui96** [comment]
@xyb994 Okay i will work on it right away.
