### ISSUE TITLE
BeLLApp Course Grading Issue

### ISSUE THREAD

**Issue by ofrank23447** [open-learning-exchange/open-learning-exchange.github.io#1451]
## BeLLApp Virtual Intern Course Grade Issue
I noticed that grades are given after each step in the Virtual Intern Course in BeLLApp.  
However, it seems like there's something off about the grading.  
If one sees at the red box that I highlighted, I have received 33% even though there were only two questions. 
For future virtual intern course and other courses as well, there should be weights displaying what each step is worth.  
This will give the users to take the course quizzes seriously.

![image](https://user-images.githubusercontent.com/24216313/34798582-8013a1ca-f611-11e7-8db9-833fdee9e8f2.png)

**Comment by ofrank23447** [comment]
I know this is a minor issue, but I think this change will be beneficial for all the users.

**Comment by dogi** [comment]
I am very sorry @ofrank23447 but this issue you are raising has nothing to do with open-learning-exchange.github.io

**Comment by ofrank23447** [comment]
Okay, I understand.
Sorry for my misunderstanding
