### ISSUE TITLE
MD wiki issue

### ISSUE THREAD

**Issue by ofrank23447** [open-learning-exchange/open-learning-exchange.github.io#1453]
Few days I ago, I tried writing a .md file as shown in Markdown example.  
I attempted using bullet point syntax. It worked successfully via preview, but it did not work when switched to MDWiki page as noted in the pull request image. 
Maybe, there should be a note that bullet point syntax is not compatible.

![image](https://user-images.githubusercontent.com/24216313/34803020-cf9834e0-f625-11e7-8dbf-e84385ebb8b0.png)

![image](https://user-images.githubusercontent.com/24216313/34802997-92fe3ed0-f625-11e7-8618-2f7be192329b.png)

**Comment by kylemathias** [comment]
Might be a better to change the entire picture to something that is correct rather than add a note.

**Comment by ofrank23447** [comment]
I tried many ways to do bullet list, but I could not find a solution to make it work.
I will try to find other issues with solutions
