### ISSUE TITLE
Add "Back to top" link into faq page

### ISSUE THREAD

**Issue by Jackbui96** [open-learning-exchange/open-learning-exchange.github.io#1456]
Want to add "Back to top" link after every question in faq page so that the user can easily navigate throughout the page.

Final product will be something similar to this  
![jackbui96 github io-vi-faq md at master jackbui96-jackbui96 github io - mozilla firefox_019](https://user-images.githubusercontent.com/15133304/34843344-095f1d5e-f6c3-11e7-943d-ac102c56c440.png)

**Comment by xyb994** [comment]
Personally, I feel it looks a little "too much" to have "Back to top " after every single question. Moreover, another way to navigate back to FAQ list is to click one of the item on the left sidebar.

What do other VIs think?

**Comment by Jackbui96** [comment]
The "Back to top" here will not redirect the user to the top of the page, but rather to the list of questions. For example, the user finished reading question 3 of the general internship question. If the user was to click on the "Back to top", it will redirect the user to the top of the list of general internship questions, then the user can look at another question. Here is a prototype that I have made.

Gitraw preview: https://rawgit.com/Jackbui96/Jackbui96.github.io/issue1456/#!pages/vi/vi-faq.md

**Comment by lorugant** [comment]
@Jackbui96 I agree with @xyb994 . By clicking "General Internship questions" on the left side, we are automatically redirected to the top where all the questions are present.

**Comment by Jackbui96** [comment]
I see, if that is the case then I will find another issue to work with.
