### ISSUE TITLE
Link for "Markdown Tutorial" is dead

### ISSUE THREAD

**Issue by Jackbui96** [open-learning-exchange/open-learning-exchange.github.io#1457]
Link for "Markdown Tutorial" is dead in: First Step -> Step 3: Markdown and Fork Tutorial -> GitHub and Markdown page. If we hit the link, the link will send us to the "404 not found page". I am thinking of using an alternative link for the link.

Here are some of the link that might be useful:
 * http://simpleprimate.com/jekyll-for-designers/blog/markdown-basics/
 * https://www.markdowntutorial.com/
 * http://commonmark.org/help/

![github and markdown - mozilla firefox_020](https://user-images.githubusercontent.com/15133304/34846263-6ffd87e0-f6cc-11e7-8ee1-c810bd239ef9.png)

**Comment by kylemathias** [comment]
Nice find. i would use the first link.

**Comment by xyb994** [comment]
+1 for http://commonmark.org/help/

**Comment by lorugant** [comment]
@Jackbui96 I like the first one or something like https://guides.github.com/features/mastering-markdown/

**Comment by Jackbui96** [comment]
Ok I will create the PR right away. I just got back from my trip out of state, so that's why I am a bit behind of schedule.
