### ISSUE TITLE
FAQ: Q3 link is dead

### ISSUE THREAD

**Issue by ketruong** [open-learning-exchange/open-learning-exchange.github.io#1458]
In Virtual Interns -> FAQ ->Q3: 

<img width="1440" alt="screen shot 2018-01-11 at 8 11 53 pm" src="https://user-images.githubusercontent.com/22358168/34855088-c91237ec-f70b-11e7-905f-631fb4ad98d0.png">

The link in "More information about the internship can be found here." is dead.

<img width="480" alt="screen shot 2018-01-11 at 11 02 09 pm" src="https://user-images.githubusercontent.com/22358168/34859328-8ef4c90e-f723-11e7-84d7-7e034758d5d8.png">

This is where the link leads to.

<img width="822" alt="screen shot 2018-01-11 at 8 11 24 pm" src="https://user-images.githubusercontent.com/22358168/34855094-d2a0eeac-f70b-11e7-8559-15fa4ec3b770.png">

**Comment by ketruong** [comment]
The link should be changed to https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs/Virtual-Software-Engineer-Intern-0d660f98f7710439?q=Open+learning+exchange

**Comment by ketruong** [comment]
Continuation of #1422

**Comment by xyb994** [comment]
@ketruong This is not the first time we run into indeed link broken. Replacing the link with `https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs` would be a more permanent fix. As you can tell from [the link you posted](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1458#issuecomment-357137814),  `0d660f98f7710439` is random. It would change next time dogi repost the job.

**Comment by ketruong** [comment]
@xyb994 I have made the change.
