### ISSUE TITLE
Raspian Image Implementation Dead link

### ISSUE THREAD

**Issue by ketruong** [open-learning-exchange/open-learning-exchange.github.io#1463]
In Robots -> Raspberry Pi -> How can I help section

The "our implementation" link is dead.

<img width="855" alt="screen shot 2018-01-11 at 11 12 01 pm" src="https://user-images.githubusercontent.com/22358168/34859627-75c4e494-f725-11e7-8dfd-5096bf4bb3c3.png">

**Comment by xyb994** [comment]
Good catch, it was [updated recently](https://github.com/ole-vi/treehouse-builder/pull/213), the new link is https://github.com/ole-vi/treehouse-builder/blob/master/scripts.d/30_ssh_keys.sh, feel free to create a PR for that.
