### ISSUE TITLE
"Take the Course" Images/Explanation Required

### ISSUE THREAD

**Issue by ofrank23447** [open-learning-exchange/open-learning-exchange.github.io#1466]
When I was taking the virtual intern quiz from BeLLApp, I was confused what course "it" was referring to from the following paragraph and had to ask dogi to make sure the quiz I was taking was the correct one: 
![image](https://user-images.githubusercontent.com/24216313/34899442-c6bc0f16-f7ad-11e7-9a01-389a9b8834d7.png)

I request to add a screenshot of course page that virtual interns need to take like this 
![image](https://user-images.githubusercontent.com/24216313/34899462-ea5d7234-f7ad-11e7-8bb1-f405f6907e1e.png)

**Comment by xyb994** [comment]
Yes, it would definitely be helpful if "Take the Course" is more specific. Personally I would avoid adding too many images to the guide, maybe simply add the course title with bold formatting somewhere in that section? What do other VIs think?

**Comment by ofrank23447** [comment]
Instead of an image. I can list the steps to the course quiz. Let me know

**Comment by lorugant** [comment]
@ofrank23447  yes. please list the steps and create a pull request

**Comment by ofrank23447** [comment]
@lorugant @xyb994 https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1501
