### ISSUE TITLE
"Useful Links" under Github Issue section Improvement

### ISSUE THREAD

**Issue by ofrank23447** [open-learning-exchange/open-learning-exchange.github.io#1467]
I strongly believe https://opensource.guide/how-to-contribute/ should be part of one of the links in Useful Links under GitHub Issue section.  
The link discusses what are open source projects and importance of documentation.

**Comment by kylemathias** [comment]
You can add it if you like. But be aware that not everyone will read it.

**Comment by ofrank23447** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1499
