### ISSUE TITLE
Example of Issue Confirmation

### ISSUE THREAD

**Issue by ofrank23447** [open-learning-exchange/open-learning-exchange.github.io#1468]
Under Step8-Create Issues and Pull Requests, it talks about waiting for confirmation from OLE team members after creating an issue.  I think there should be another example link at the red line that shows an issue that shows the importance of waiting for confirmation by the team.  
The link can be to this issue: https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1465
![image](https://user-images.githubusercontent.com/24216313/34902259-a86a422a-f7cc-11e7-90cb-c231cb289bcf.png)

**Comment by xyb994** [comment]
Good point, but First Steps page probably shouldn't go into too much details. 

Would it be better to address the duplicate issue problem at [Create an Issue](https://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md#Create_an_Issue) in Step 8? Using a "Note" there might be able to catch aspiring virtual interns' attention. Additionally, we could probably bold the sentence before the red line.

What do other people think?

**Comment by ofrank23447** [comment]
I can make the sentence before the red line bold and create a "Note" as you mentioned.
Let me know. I will modify and PR

**Comment by lorugant** [comment]
@ofrank23447  Please make the changes and create pull request

**Comment by ofrank23447** [comment]
@lorugant @xyb994 https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1500
