### ISSUE TITLE
Remodel Git Repositories.md

### ISSUE THREAD

**Issue by Jackbui96** [open-learning-exchange/open-learning-exchange.github.io#1480]
1. Some heading needs to be bigger. The headings are:
 * Clone with HTTPS or use SSH?
 * Configure a Remote Repository for your fork
2. Make a re-direct from the heading to the reading point.  

So if the user want to read the header, the user can just click on the heading and it will jump to the corresponding place.

**Comment by Jackbui96** [comment]
Prototype: https://rawgit.com/Jackbui96/Jackbui96.github.io/issue1480/#!pages/vi/vi-github-and-repositories.md

**Comment by kylemathias** [comment]
Those changes seem fine. I would go ahead and make a Pull Request for it.
