### ISSUE TITLE
'Next' and 'Finish' buttons don't work in Virtual Intern Course Step-12

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1481]
Javascript or Node.js code may don't work. Please check.

**Comment by ybai8** [comment]
Here is the image:
<img width="1216" alt="screen shot 2018-01-14 at 3 09 37 pm" src="https://user-images.githubusercontent.com/21957889/34926508-dc7756b8-f97d-11e7-88d6-f496fc081cbc.png">

**Comment by xyb994** [comment]
What browser are you using? Could you provide some more information like error message in console?

**Comment by ybai8** [comment]
I'm using firefox. Sometimes the buttons work, sometimes not. Please check the console.
<img width="1272" alt="screen shot 2018-01-15 at 9 03 03 am" src="https://user-images.githubusercontent.com/21957889/34946031-4b484a2a-f9d3-11e7-82d6-b77ebd3550fd.png">
<img width="1277" alt="screen shot 2018-01-15 at 9 02 56 am" src="https://user-images.githubusercontent.com/21957889/34946033-4d261282-f9d3-11e7-90d4-e620593c3f77.png">
