### ISSUE TITLE
Link format error

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1483]
page/vi/vi-github-and-markdown.md (line 97)
The first image is after I changed the link format, which is "pages/vi/profiles".
The original one is "pages/profiles/vi".

<img width="916" alt="screen shot 2018-01-15 at 9 14 06 am" src="https://user-images.githubusercontent.com/21957889/34946644-ac98a476-f9d5-11e7-9cae-92667af770f5.png">

<img width="927" alt="screen shot 2018-01-15 at 9 14 22 am" src="https://user-images.githubusercontent.com/21957889/34946645-ae83042a-f9d5-11e7-82a6-87deba3b01af.png">

**Comment by ybai8** [comment]
I have fixed this error at here: https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1484

**Comment by xyb994** [comment]
This is duplicate of issue #1449, PR #1478 already opened.
