### ISSUE TITLE
Hint of fixing 404 error when access <username>.github.io in Step-3

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1485]
<img width="866" alt="screen shot 2018-01-15 at 12 26 47 pm" src="https://user-images.githubusercontent.com/21957889/34954697-6d68bf1a-f9ef-11e7-9fe9-c03159511018.png">
When I tried to access my <username>.github.io the first time, I still have the 404 error for a long time. It didn't show up as the instruction said. So I tried to run git commands. I didn't change any files, just run git add . ,git commit - m "", and git push origin master. Then the <username>.github.io page shows up. Do you think this can help other interns fix their problem?

**Comment by kylemathias** [comment]
Part of the underlining processes with the first steps is figuring out things like this on your own. I would say it would be fine to leave this out of the first steps.
