### ISSUE TITLE
Encourage interns to comment issues here in Step-8

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1486]
I found there are not enough comments on issues. How about encouraging interns to comment these issues instead of "Add comments to three other issues"? We can add "Your comments will help improve this MarkDown wiki clearer and better for future use." What do you think?
<img width="872" alt="screen shot 2018-01-15 at 1 11 10 pm" src="https://user-images.githubusercontent.com/21957889/34956123-c0fe0170-f9f5-11e7-8c12-9e51cdb0caf3.png">

**Comment by kylemathias** [comment]
We want interns to actually add comments to other issues as part of the first steps process. This helps newer interns get used to our process.

**Comment by ybai8** [comment]
Please check. I added "We want interns to actually add comments to other issues as part of the first steps process. This helps newer interns get used to our process." in the second paragraph of Step-8. Let me know if it is ok. 
https://rawgit.com/ybai8/ybai8.github.io/issue1486/#!./pages/vi/vi-first-steps.md

**Comment by ybai8** [comment]
The newest rawgit link:
https://rawgit.com/ybai8/ybai8.github.io/issue1486/#!pages/vi/vi-first-steps.md
The formal one doesn't work anymore.

**Comment by kylemathias** [comment]
@ybai8 It looks and sounds fine, but i don't know if its necessary to put my exact words in step 8. What i said contradicts what i meant behind it.

**Comment by kylemathias** [comment]
I think the lack of comments on issues is not because we didn't mention it in step 8, its a combination of other factors (not many interns at the moment, people not wanting to comment).

**Comment by ybai8** [comment]
That's fine. Thank you very much for answering! :)
