### ISSUE TITLE
Change adding images note

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1489]
I found in chat introduction, the adding images note is "To add images in the chat, just drag the image from your directory to the browser context and drop it in the messaging area or simply use Ctrl+C and Ctrl+V to paste your image", which is not the same with configuration page. Since CTRL-C and CTRL-V also can upload images, so how about changing the configuration page adding images note like this? 
<img width="849" alt="screen shot 2018-01-15 at 4 58 54 pm" src="https://user-images.githubusercontent.com/21957889/34963346-f9f336b0-fa15-11e7-960d-844ad8e2325c.png">
Original one:
<img width="843" alt="screen shot 2018-01-15 at 4 59 49 pm" src="https://user-images.githubusercontent.com/21957889/34963353-00cfd0a6-fa16-11e7-97ca-1ea112e1fa1c.png">
Here is the rawgit link:
https://rawgit.com/ybai8/ybai8.github.io/issue1487/#!pages/vi/vi-configurations.md

**Comment by ybai8** [comment]
New rawgit link:
https://rawgit.com/ybai8/ybai8.github.io/issue1489/#!pages/vi/vi-configurations.md
The formal one doesn't work anymore

**Comment by xyb994** [comment]
Nice catch, it's always good to be to consistent. Go ahead and make the PR.

**Comment by xyb994** [comment]
Closing this as #1497 was merged.
