### ISSUE TITLE
Raspberry grammar and format error

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1491]
1. A small grammar error "So our main **concerns** at the moment is getting the RPI to connect to different connectivity options such as wifi/bluetooth/ethernet automatically. " has been edited.
<img width="705" alt="screen shot 2018-01-15 at 5 28 56 pm" src="https://user-images.githubusercontent.com/21957889/34964064-9d3faae4-fa19-11e7-9a02-1e66be48ea43.png">
2. I deleted the full stop after point 5
<img width="554" alt="screen shot 2018-01-15 at 5 29 50 pm" src="https://user-images.githubusercontent.com/21957889/34964118-fb05b178-fa19-11e7-8fd2-e409f37096c8.png">
Here is the rawgit:
https://rawgit.com/ybai8/ybai8.github.io/issue1490/#!./pages/robots/rbts-raspberry-pi.md
Please tell me if it is ok or not.

**Comment by xyb994** [comment]
"getting the RPI to connect to different connectivity options" sounds like one problem to me. Can any native speaker point out if it should be "concerns" here?

Other than that, I wonder if it's better to say "So our main goal at the moment is to get ..."

**Comment by ybai8** [comment]
This sounds good. I have made the change and created a PR

**Comment by xyb994** [comment]
Closing this as ##1496 was merged.
