### ISSUE TITLE
Format error

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1492]
<img width="602" alt="screen shot 2018-01-15 at 6 01 22 pm" src="https://user-images.githubusercontent.com/21957889/34964912-35d214f0-fa1e-11e7-9640-4c19e4f848ea.png">
In robots/rbts-raspberry-pi.md page, **Building the image with treehouse-builder:** is not at the appropriate place. Please take a look.
Here is the rawgit link:
https://rawgit.com/ybai8/ybai8.github.io/issue1492/#!pages/robots/rbts-raspberry-pi.md

**Comment by xyb994** [comment]
Good catch, go ahead and open a PR.

**Comment by ybai8** [comment]
A PR has opened. Please check.

**Comment by xyb994** [comment]
Closing this as #1495 was merged.
