### ISSUE TITLE
Translation page needed

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/open-learning-exchange.github.io#15]
The virtual interns need access to the Crowdin link to work on translation. This new tab should be between "Team" and "Chat" and should provide access to Open Learning Exchange's Crowdin.

**Comment by EmilyLarkin** [comment]
Here is the URL for the Crowdin invite: https://crowdin.com/project/open-learning-exchange/invite
We should add another page under [navigation.md](https://raw.githubusercontent.com/open-learning-exchange/open-learning-exchange.github.io/master/ll_CC/navigation.md) and make the page between "Team" and "Chat". It should be called "Translate".

**Comment by dogi** [comment]
awesome :D 
go ahead @EmilyLarkin

**Comment by EmilyLarkin** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/17

Done!
