### ISSUE TITLE
HTML resources page format error

### ISSUE THREAD

**Issue by ybai8** [open-learning-exchange/open-learning-exchange.github.io#1504]
1. <img width="284" alt="screen shot 2018-01-16 at 2 14 20 pm" src="https://user-images.githubusercontent.com/21957889/35007414-a3ddfbea-fac7-11e7-81c9-6974d1e5604c.png">
The "Couchapp Installation" should be under Method 1, so I changed the format from "##Couchapp Installation##" to "###Couchapp Installation###", which is the same format with "Generating the Couchapp". It seems like this now:
<img width="297" alt="screen shot 2018-01-16 at 2 18 30 pm" src="https://user-images.githubusercontent.com/21957889/35007592-26ab1332-fac8-11e7-8591-9b85495b13a4.png">
2. I added a full stop after point 5.
<img width="862" alt="screen shot 2018-01-16 at 2 19 07 pm" src="https://user-images.githubusercontent.com/21957889/35007629-465670dc-fac8-11e7-8e54-1de0779bfbb8.png">

Here is the rawgit link: https://rawgit.com/ybai8/ybai8.github.io/issue5/#!pages/robots/rbts-html-resources.md
Please take a look.

**Comment by kylemathias** [comment]
Looks good to me. Go ahead and create the PR.
