### ISSUE TITLE
fix vagrant install for bash script

### ISSUE THREAD

**Issue by anagabriel42** [open-learning-exchange/open-learning-exchange.github.io#1506]
![screenshot from 2018-01-16 15-05-49](https://user-images.githubusercontent.com/11947390/35016733-c6da2f2c-face-11e7-897f-6ad29abc95a0.png)

```
sudo apt install vagrant
``` 
The `vagrant` package has been deprecated, and has to be installed using a different method.

I found a way to do it using the command line, using [this source](https://tutorialforlinux.com/2017/10/09/how-to-install-vagrant-ubuntu-17-10-artful-linux-easy-guide/).

I'll just add these steps to the script located on the BeLL-App installation page.

**Comment by kylemathias** [comment]
do you only need to change the one line from this:
```
sudo apt install vagrant
```
to

```
sudo gdebi ./vagrant*.deb
```
?
