### ISSUE TITLE
Auto Install Script for Virtual Box version 5.0.10 does not work in windows 10 64 bit system.

### ISSUE THREAD

**Issue by vishwakarmaanil** [open-learning-exchange/open-learning-exchange.github.io#1512]
The version of virtual box which is installed as a part of Auto Installation Script does not work in Windows 10 64 Bit system. 
![](https://image.ibb.co/dembU6/4.png)
However, This problem can be fixed by overwriting or re installing other  versions of Virtual box such as 5.1.x.

**Comment by kylemathias** [comment]
i believe it might be a better idea to fix the scrip instead of adding more to the steps.
