### ISSUE TITLE
Update Step 5 Git Repositories Page

### ISSUE THREAD

**Issue by YangLou1** [open-learning-exchange/open-learning-exchange.github.io#1521]
Under the section Summary of steps, there are two sentences need to be updated:
Clone your git \ repository and open your terminal window to it by using cd
Push the updates you just downloaded to your \ repository by using git push(info)

They symbol \ in these two sentences doesn't make sence, and it was produced by markdown syntax \<username\> in the file.

**Comment by xyb994** [comment]
I believe the original intention was to escape the `<`, but it seems it won't work on MDwiki.

**Comment by YangLou1** [comment]
@xyb994 I agree. The original intention was to show "<username>" instead of "\". I think the proposed changes in the previous comment is more clear and also consistent with previous sections on the page. Should I open a pull request to make the proposed changes?

**Comment by xyb994** [comment]
Sure, I see you already have the PR for that. But in [item 3](https://github.com/YangLou1/YangLou1.github.io/commit/cde47ac2e35ecf84a0cbe7e01fab2268894f8a2b#diff-07304ab46110a37e2644ed71d0449181R182), maybe it's not necessary to mention the repository name again.

**Comment by YangLou1** [comment]
@xyb994 I deleted the previous PR. Please review the new PR that doesn't mention the repository name in item 3.

**Comment by xyb994** [comment]
@YangLou1 Thanks for the update. This is fine, but you could have kept working on the old branch, new changes will be reflected in the PR.
