### ISSUE TITLE
Scripts to Install the Community BeLL Window8.1 and Above Doesn't Work for Windows 10

### ISSUE THREAD

**Issue by Teaganjzg** [open-learning-exchange/open-learning-exchange.github.io#1523]
Scripts to Install the Community BeLL Window8.1 and Above Doesn't Work for my windows 10. I am not sure the reason, but I tried the script below which is for window 7 and above, it worked.

**Comment by vishwakarmaanil** [comment]
Refer https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1513

**Comment by Teaganjzg** [comment]
@vishwakarmaanil Thank you for your comment. I also had virtual box installation problems by running the script (window7 and above), but the first script was not running at all. Now all the installation problems are fixed. It is not a big thing, I am just wondering that if anyone knows the reason and maybe we can make some changes to the page helping others understand.
