### ISSUE TITLE
Revise Git Repositories Page in Step 5

### ISSUE THREAD

**Issue by YangLou1** [open-learning-exchange/open-learning-exchange.github.io#1524]
Under Start here section, underscores inside "Clone_with_HTTPS_or_Use_SSH?" are unnecessary and may cause confusion.  "Clone with SSH" is more precise than "Use SSH", and "Clone with SSH" is also shown in the popup when clicking Clone or download button.

"Clone with HTTPS or Use SSH?" shows up under the section Clone Your GitHub Repository username.github.io as well.

**Comment by YangLou1** [comment]
To make the sentence more clear, under the section Start here, we should change "Clone_with_HTTPS_or_Use_SSH?" into "Clone with HTTPS or Clone with SSH?" 

Also, under the section Clone Your GitHub Repository username.github.io, we should change "Clone with HTTPS or Use SSH?" into "Clone with HTTPS or Clone with SSH?"

**Comment by CindyPSU** [comment]
I think the change in wording is a good suggestion, much clearer than the current.

**Comment by lorugant** [comment]
@YangLou1 Please make the changes and create PR

**Comment by YangLou1** [comment]
@lorugant I have made the changes and please check the PR.
