### ISSUE TITLE
error from "sync with the nation"

### ISSUE THREAD

**Issue by Teaganjzg** [open-learning-exchange/open-learning-exchange.github.io#1526]
I got an error from the "sync the nation", I followed all the instructions in Step 7. Does anyone know how to solve this? Maybe that is something we can add a note to this page.

<img width="883" alt="can t sync - step7" src="https://user-images.githubusercontent.com/31550461/35082767-d35dc7a8-fbd8-11e7-9b92-9d0901ae249e.PNG">

**Comment by xyb994** [comment]
Please provide more detail information about the problem. Some error message from console would be great.

**Comment by Teaganjzg** [comment]
@xyb994 That error message occurred when I tried to Sync with the nation. I checked on the nation side, the report shows that I've already updated. What do you think is the reason for this error message?

**Comment by xyb994** [comment]
@Teaganjzg That's why I was asking for error message in browser's console. But assuming you've already closed the window at this time. If you could replicate the problem again and get any error message from console would be great.
