### ISSUE TITLE
Minor flaw in Step 7 - Nation Bell

### ISSUE THREAD

**Issue by Teaganjzg** [open-learning-exchange/open-learning-exchange.github.io#1527]
![image](https://user-images.githubusercontent.com/31550461/35083120-b06f43be-fbda-11e7-96a3-d8e1b8b58d21.png)

Actually, in Step 4 there is no survey to be updated, "you did" is kind of confusing, we can better use "you knew" instead.

**Comment by xyb994** [comment]
Good catch, it might be better if we say it this way:  "we showed your 3 kinds of updates that you might receive..."

**Comment by Teaganjzg** [comment]
@xyb994 Thank you for your suggestion, can I make a PR on this?

**Comment by CindyPSU** [comment]
@xyb994 I believe there is a typo in your suggested text. I think it should read "we showed you 3 types of updates that you might receive..." I think the "your" should be replaced with "you" and instead of "kinds", "types" might work better for clarity here. Just a suggestion.

**Comment by xyb994** [comment]
@CindyPSU Sure, that sounds better. Thanks for catching my typo.
@Teaganjzg Yes, you can go ahead and create a pull request.
