### ISSUE TITLE
Change Step 3 Section Content on First Steps Page

### ISSUE THREAD

**Issue by YangLou1** [open-learning-exchange/open-learning-exchange.github.io#1528]
The instructions on the GitHub and Markdown page require future interns to post the following two links in the gitter.im chat:
https://YourUserName.github.io
https://rawgit.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/vi/profiles/YourUserName.md
![image](https://user-images.githubusercontent.com/35347763/35083762-b5ab43aa-fbee-11e7-9892-b16f5cbccf2f.png)

However, on First Steps page under step 3 section as the image above shows, it instructs future interns to post<username>.github.io and <username>.github.io/#!pages/vi/profiles/<username>.md in the gitter chat. It is not consistent with the instructions on the GitHub and Markdown page.

**Comment by YangLou1** [comment]
Instead of "<username>.github.io and <username>.github.io/#!pages/vi/profiles/<username>.md", we can change the content in parenthesis into "https://YourUserName.github.io and https://rawgit.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/vi/profiles/YourUserName.md"

**Comment by CindyPSU** [comment]
Good catch! I was going to add an Issue for this until I caught yours. This was definitely confusing wording/content working through the "First Steps". Clear guidance and wording is crucial. I really thought I had missed something during this step.

**Comment by lorugant** [comment]
@YangLou1  Please make the changes and create a PR. @CindyPSU Thank you for your attention. Please create issues if you feel anything needs to be changed!!

**Comment by YangLou1** [comment]
@lorugant Please check the PR, thanks.
