### ISSUE TITLE
"Virtual Interns Gitter chatroom" link is dead (404 Error)

### ISSUE THREAD

**Issue by vishwakarmaanil** [open-learning-exchange/open-learning-exchange.github.io#1531]
Here is the link to the Page "http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md".   

![](https://image.ibb.co/ejPtSR/5.png)

The **"Virtual Interns Gitter chatroom"** link is not working.

**Comment by xyb994** [comment]
- The link is not dead, you are seeing 404 because "open-learning-exchange/interns" is a private room
- In this case, it make more sense to remove the link because aspiring virtual interns don't have access to it until they finish first steps

**Comment by vishwakarmaanil** [comment]
Thanks for Updating me on this @xyb994.

**Comment by xyb994** [comment]
@vishwakarmaanil Sure, let us know after you update your pull request.

**Comment by vishwakarmaanil** [comment]
@xyb994 Since it is a private room, I will create a pull to unlink the "Virtual Interns Gitter chatroom".

**Comment by xyb994** [comment]
@vishwakarmaanil You could keep work on https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1534 as well, maybe change the title of the PR.

**Comment by vishwakarmaanil** [comment]
@xyb994  Sure, I will update the pull https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1534

**Comment by sente** [comment]
., :
