### ISSUE TITLE
Virtual Interns FAQ Q16 clarification

### ISSUE THREAD

**Issue by azywong** [open-learning-exchange/open-learning-exchange.github.io#1543]
[faq](http://open-learning-exchange.github.io/#!pages/vi/vi-faq.md)  currently reads:
>Q16: What do I do if I already have a github.io with my username?
>You have a few options:
>
>If you are not using the repo anymore you can delete it and then follow the First Steps.
>
>If you are still using it and you don't want to remember another login, you can create an organization and name the forked repo <orgname>.github.io.
>
>Or you can just create another GitHub account, and use that for OLE work.

I already had a github.io with my username and the easiest method for me was to rename my original <username>.github.io repository to something else (for now) and then continue to follow the steps from the [github and markdown page](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md)

It also might be helpful to either mention this as a prerequisite, or link to this specific FAQ question in the steps, as it was not immediately apparent to me what to do in that case.

**Comment by xyb994** [comment]
I agree with you, go ahead and create a PR.

We can have the link to Q16 in "GitHub and Markdown - Go to Settings and rename your repository."

**Comment by xyb994** [comment]
PR #1550 was merged
