### ISSUE TITLE
Put in order on firststeps.md

### ISSUE THREAD

**Issue by vimalababu4** [open-learning-exchange/open-learning-exchange.github.io#156]
In firststeps.md: under assignment5:
The order in which  set of instructions(steps) are placed  need to be fixed
I think we need to place the instructions in order.
-step 3 must follow  step 1 (Because step 3 does belong to step1)
-step 2 should go at the end,  becomes step 3
-Creating  step 4: When you are done, please let us know on the  Gitter chat

**Comment by dogi** [comment]
interesting
