### ISSUE TITLE
Adding pictures into "rbts-takehome-device-setup.md" file

### ISSUE THREAD

**Issue by Jackbui96** [open-learning-exchange/open-learning-exchange.github.io#1561]
I want to add some picture into the guide so that it is easier to follow. Since the page is mostly written words, by adding some pictures it will be easier to follow.

![android device setup - mozilla firefox_026](https://user-images.githubusercontent.com/15133304/35240434-4e009cf0-ff68-11e7-8f39-f65978cca46a.png)

Link: https://open-learning-exchange.github.io/#!./pages/robots/rbts-takehome-device-setup.md

As you can see from the screen shot there is little to no picture. That is why, I am thinking that it is not a good design. Since the guide does not have pictures, it will confuse the user and will make them lost track on which step they have taken. So if we have more pictures, it will make the guide easier to follow, plus it also make the guide less boring to read.

Fixing proposal: I can add more pictures into the guides for each step with clear description.

**Comment by Ivaylo2017** [comment]
@Jackbui96 The issues that we are documenting need to have 2 parts:
1. Present a specific issue (use markdown and links! please)
2. Propose a solution as a comment.  

Since the final solution may be different from your initial suggestion - it's good to keep it as a comment in the issue's thread. I hope this helps!
Cheers

**Comment by Jackbui96** [comment]
@Ivaylo2017 Thank you very much for your feedback, I will pay more attention to how to make my issue more clearer.

**Comment by kylemathias** [comment]
The guide is a little bland. Go ahead and find pictures to go along with the guide. Also, be on the look out for improving the wording overall on the guide.

**Comment by Jackbui96** [comment]
@kylemathias Thank you for the confirmation. I am working on the issue right now.

**Comment by Jackbui96** [comment]
This is a prototype that I have made. For those who are interested, please have a look and give me your feedback so that I can fix accordingly.
Gitraw Preview: https://rawgit.com/Jackbui96/Jackbui96.github.io/issue1561/#!pages/robots/rbts-takehome-device-setup.md
