### ISSUE TITLE
Links under Steps in vi-first-steps.md redirect to bottom of pages

### ISSUE THREAD

**Issue by Ivaylo2017** [open-learning-exchange/open-learning-exchange.github.io#1562]
When virtual interns click on links under any of the First Steps in [vi-first-steps.md](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) the next page loads at the mid-section or at the bottom and they have to scroll all the way up to start reading.

**Comment by Ivaylo2017** [comment]
Adding an anchor with id matching the top header of the other file could solve this problem as explained in [this stackoverflow](https://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown)

**Comment by lorugant** [comment]
@Ivaylo2017 It seems that links are loading and directed to the top. Anyway, please make the changes and create a PR so that it can be reviewed.

**Comment by Ivaylo2017** [comment]
@lorugant  Thank you for review.
#### Actually if you look at all the links under the Steps. (I hi-lighted just 3 here):  

> ![links](https://user-images.githubusercontent.com/29740759/35286915-2f400e28-002f-11e8-93fd-fa72f92139d2.PNG)


#### They'd take you not to the top of pages but somewhere mid-section like for example the vagrant link  

> ![mid-page anchor](https://user-images.githubusercontent.com/29740759/35286967-5a64b2f2-002f-11e8-8c91-e4bb9a6dea98.PNG)

**Comment by kylemathias** [comment]
All of the links take me to the top of the page. not sure whats happening. Anyone confirm my findings or @Ivaylo2017 ?

**Comment by xyb994** [comment]
I can sort of reproduce the problem in Firefox, it's working fine in Safari.

**Comment by Ivaylo2017** [comment]
Ok. I'm closing this issue and the related pull request then and moving onto the next one.
Thank you!
