### ISSUE TITLE
Content Editing Needed on GitHub Issues Page

### ISSUE THREAD

**Issue by CindyPSU** [open-learning-exchange/open-learning-exchange.github.io#1563]
The wording needs to be edited on the GitHub Issues Page in the last paragraph of the Introduction section. See attached image noting the suggested changes. Strikethroughs note the removal of content and the dialog symbol denotes the replacement wording suggestion.
![githubissuespageeditsuggestion](https://user-images.githubusercontent.com/35432613/35187979-e6df1b9c-fdea-11e7-9cd2-50433e42dfc3.png)

**Comment by CindyPSU** [comment]
Neglected to provide the GitHub Issues Page Link http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md

**Comment by xyb994** [comment]
@CindyPSU Thanks for catching the repetitive content, looks good, go ahead and create a PR.

**Comment by CindyPSU** [comment]
PR #1566 submitted.

**Comment by CindyPSU** [comment]
PR #1566 Merged. 22 Jan 2018
