### ISSUE TITLE
Clarification Needed for Step 0 - Introductory Steps

### ISSUE THREAD

**Issue by CindyPSU** [open-learning-exchange/open-learning-exchange.github.io#1567]
On the "First Steps" page http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md, "Step 0 - Introductory Steps" section, list item 3. for Crowdin. 

The second sentence states, "If you know another language, go to this Crowdin link to join Crowdin by creating an account." This is almost hidden information because it is not specifically called out to intern candidates as being _optional_, which I am assuming that it is? If so, it might help to note this introductory step as being _Optional_ by the addition of a note of some kind. Screenshot is included below with an example of a solution.

![crowdinclarification](https://user-images.githubusercontent.com/35432613/35191001-1732f2cc-fe2d-11e7-9923-413e8462a66b.png)

**Comment by xyb994** [comment]
@dogi Could you help clarify this?

**Comment by kylemathias** [comment]
Adding Optional is fine. I think adding something like "If you know another language, you can go to..."

**Comment by CindyPSU** [comment]
@kylemathias Thank you!
So this wording might work better for that sentence then:
"If you know another language, you can go to this Crowdin link to join Crowdin by creating an account."
