### ISSUE TITLE
Exit Button in BeLL Resource Feedback Page

### ISSUE THREAD

**Issue by CindyPSU** [open-learning-exchange/open-learning-exchange.github.io#1568]
While testing my Resource Additions to the BeLL Library, I noticed that when I select a Resource that I wish to view, view it, but then wish to Exit the Resource Page, the Exit Button does not work. Screenshot included with red circle drawn around the referenced Exit Button. 

![exitbutton](https://user-images.githubusercontent.com/35432613/35191120-b633e1b8-fe2f-11e7-8399-5ca06c743f7a.png)

Once clicked, where should this button direct a user? Back to the Library Page?

**Comment by CindyPSU** [comment]
I just realized that I probably should have submitted this bug/issue within the Feedback Option of the BeLL App, correct? If so, I will resubmit this issue through the proper channel. Just want to confirm before deleting/canceling this Issue.

**Comment by xyb994** [comment]
@CindyPSU You are right, this is something separate from the github.io repo.

A side note, we are moving towards the next iteration of BellApps https://github.com/ole-vi/planet.

**Comment by CindyPSU** [comment]
@xyb994 Thank you! I thought so, I will close this issue and submit an Issue in BeLL. 
Thanks for the heads up on the next iteration. Good news!

**Comment by CindyPSU** [comment]
Feedback submitted in MyBeLL Apps for bug. Closing this Issue since it is not MDWiki related.
