### ISSUE TITLE
Content Edit of Nation BeLL Dummy User 

### ISSUE THREAD

**Issue by CindyPSU** [open-learning-exchange/open-learning-exchange.github.io#1569]
It is clear that a user must create a Dummy User in order to sync the Community with the Nation; however, the Dummy User Screenshot Example is a little confusing and it does not convey _Required_ fields. Recommended changes to the Dummy User Example are in the included screenshot.

![adddummyuser](https://user-images.githubusercontent.com/35432613/35191240-461d8100-fe33-11e7-913e-a1925d0470b2.png)

**Comment by xyb994** [comment]
@CindyPSU Sure, go ahead and create a PR to replace the screenshot.

**Comment by CindyPSU** [comment]
Fixes completed. PR #1585
