### ISSUE TITLE
Arrows in the BeLL App inbox disappear if clicked

### ISSUE THREAD

**Issue by AdityaNair99** [open-learning-exchange/open-learning-exchange.github.io#157]
[Recording_20160616_2052.pdf](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/319763/Recording_20160616_2052.pdf)

Step Recording to show the issue

**Comment by dogi** [comment]
@AdityaNair99 wrong issue queue ;)
it was suggest to first bring up the issue in the google goc
pdf or word documents are not the way to write an issue

In other word every issue is following the markdown standard
which for formatting text is awesome
per drag and drop also pictures are supported here ...
