### ISSUE TITLE
Clarification Needed for Step 6 - GitHub Issues

### ISSUE THREAD

**Issue by CindyPSU** [open-learning-exchange/open-learning-exchange.github.io#1570]
The "Create an Issue" section on the GitHub Issues page (http://open-learning-exchange.github.io/#!pages/vi/vi-github-issues.md) has some wording that needs to be clarified in order to prevent issues with intern candidates creating issues and working on them before they are reviewed and approved for action. Wording that needs clarification is highlighted in yellow in the screenshot below.

![createanissuewording](https://user-images.githubusercontent.com/35432613/35191317-7c8a131e-fe35-11e7-804f-4af027727efa.png)

Questions:
1. When creating issues, is it preferred procedure to simply document the issue ONLY when submitting the initial new issue? 
2. Should there be any inclusion of a solution in the initial new issue submission?
3. Is it _required_, not preferred, that issues are reviewed and approved prior to any change action being taken by an intern candidate?

Based on the responses to these questions, I have a couple of ideas for content edits to make the instructions and guidance clearer. 

Suggested Edits to Content:
"After _you have submitted the new issue_, you will then research the possible solutions, or ideas, on how to address the issue, and _then_ you will write_/add_ a comment _detailing your proposed solution_, as you can see here. 

_IMPORTANT: Do not move forward with making the proposed solution until it has been reviewed and a comment added noting that it is safe to move ahead with the proposed changes, as Dogi did here._ 

Note: _Wait until someone from the OLE confirms/approves the change that your issue has brought up BEFORE you start working on the issue._ Check out this example issue that shows the importance of confirmation: (example issue #).

**Comment by Ivaylo2017** [comment]
I agree with Cindy. It's not very clear if we should make the pull request while waiting for approval for our issue. An emphasis at the exact point in these steps where prospect interns need to wait can be helpful.

**Comment by kylemathias** [comment]
1. making an issue is for documenting the problem.
2. Yes. The issue is then used to discus/find a solution and assign someone to fix it.
3. Issues are _not required_ to be approved before a pull request is made to fix it. **_But be warned, if your issue is not making a change that a OLE members dose not approve, you could be doing a lot of work for nothing._** This is the only reason we suggest that you wait for a OLE member to approve. 

Alot of new interns going through these steps suggest changes to check off the step for "creating 3 new issues and Pull Request" instead of fixing a problem or actually improving the first steps.

**Comment by CindyPSU** [comment]
@kylemathias Based on the information you provided, do you think any of the wording should be changed to make it clearer for intern candidates?

**Comment by kylemathias** [comment]
By all means, please. any place you can make something more clear and concise is the core of the intern steps.

**Comment by xyb994** [comment]
I think it's also worth noting that aspiring virtual intern should try to search to see if the issue they plan to create exists.

**Comment by CindyPSU** [comment]
@kylemathias @xyb994 @ofrank23447 I have been working on the wording based on suggestions that you have noted above. Let me know what you think.

![image](https://user-images.githubusercontent.com/35432613/35315387-62f3ff5e-0089-11e8-85b6-097dc5275c07.png)

**Comment by xyb994** [comment]
@CindyPSU Thank you! This really help clarify things up.

**Comment by CindyPSU** [comment]
@xyb994 Great! Just trying to make things clearer for Aspiring Virtual Inters like myself. Is this issue approved for its fix and PR?

**Comment by kylemathias** [comment]
Looks great.

**Comment by CindyPSU** [comment]
Fixes completed. PR #1607
