### ISSUE TITLE
Formatting is not consistent with the page 

### ISSUE THREAD

**Issue by vishwakarmaanil** [open-learning-exchange/open-learning-exchange.github.io#1571]
The formatting(Styling) of the contents are different from other contents. 

![](https://image.ibb.co/gwvATb/11.png)

Please refer this Link: http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md

**Comment by ybai8** [comment]
Can you please provide a rawgit link? Thanks

**Comment by adepojubosun** [comment]
The only problem I can see is the typographical error in instructions.

**Comment by xyb994** [comment]
Thanks for bringing it up, make sense to remove `-` and `>` here for consistency.

https://raw.githubusercontent.com/open-learning-exchange/open-learning-exchange.github.io/master/pages/vi/vi-vagrant.md

**Comment by vishwakarmaanil** [comment]
@xyb994 Thanks for the suggestion, should I create a PR reflecting these changes?
