### ISSUE TITLE
Inaccurate command need fix in vi-github-repositories.md

### ISSUE THREAD

**Issue by Ivaylo2017** [open-learning-exchange/open-learning-exchange.github.io#1572]
In Summary section in [vi-github-repositories.md](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md) item 13 is inaccurate:
![issue](https://user-images.githubusercontent.com/29740759/35196161-4ced4f60-fe9c-11e7-8428-8e2201b384d5.PNG)

`git status` should be used to check if branch is up-to-date with your github repo branch. 
`git checkout <branch_name>` is primarily used to change active branch in your local repo

**Comment by Ivaylo2017** [comment]
My suggested solution is to add another item in the list to not only fix the issue but to provide reference to one more useful command.

**Comment by xyb994** [comment]
@Ivaylo2017 Are you suggesting adding `git status` and move the note you highlighted there?

**Comment by Ivaylo2017** [comment]
@xyb994 Yes

**Comment by kylemathias** [comment]
Sounds fine, Go ahead with the changes.

**Comment by aakarnik** [comment]
I looked at this page - http://open-learning-exchange.github.io/#!pages/vi/vi-github-and-repositories.md - and the issue has still not been fixed yet. 

I would like to fix it. Should I file a separate issue or continue working on this one?

![issue 1572](https://user-images.githubusercontent.com/37878201/38688532-51defe84-3e47-11e8-8afe-9a006fc82516.JPG)

**Comment by kylemathias** [comment]
@aakarnik you can make your own branch and fix the issue there. Once you are completed then you can create a pull request that we can review.
