### ISSUE TITLE
Planet Quick Start Manual Page : Remove Intradocument Hyperlink

### ISSUE THREAD

**Issue by adepojubosun** [open-learning-exchange/open-learning-exchange.github.io#1573]
Jump-to links in hardware setup page(techgenius) are unnecessary as they are already available in the side menu. They are simply repetitions of the sidebar menus for intradocument linking. Also, the links are broken and do not work. They should not be fixed as those links are already provided in the side menu. The link can be found [here](http://open-learning-exchange.github.io/#!pages/techgenius/tg-hardware-setup.md).

**Comment by xyb994** [comment]
@adepojubosun Thanks for catching the problem, go ahead and create a PR for that.
