### ISSUE TITLE
Tg-Hardware-Setup Page : Clarification of image location

### ISSUE THREAD

**Issue by adepojubosun** [open-learning-exchange/open-learning-exchange.github.io#1574]
The instructions for setting up hardware have wrong misdirection of the image location. In the "How do I connect the planet Hardware?" section, it's stated that the image for RPI with case is on the right which is wrong. Also, the location of images for Ethernet Cable and USB cable is wrong.

**Comment by adepojubosun** [comment]
This might cause problems for users who have no preliminary basic hardware knowledge. Link can be found [here](http://open-learning-exchange.github.io/#!pages/techgenius/tg-hardware-setup.md).

**Comment by xyb994** [comment]
@adepojubosun Thanks for catching the error, go ahead and create a PR. 

Document about how to group images in MDwiki: https://dynalon.github.io/mdwiki/#!quickstart.md%23Images
