### ISSUE TITLE
Update Step 1 Configuration Guide Page

### ISSUE THREAD

**Issue by YangLou1** [open-learning-exchange/open-learning-exchange.github.io#1575]
When I clicked on the "Register" button, I didn't get the "Successfully registered." popup (see below):
![image](https://user-images.githubusercontent.com/35347763/35199818-9eacbaae-fed1-11e7-9058-4401d9881b0b.png)

Instead, I instantly got "Registration request has been accepted." popup (see below) and didn't need to wait for an admin to accept my registration request, which cause confusion.
![image](https://user-images.githubusercontent.com/35347763/35199840-f8c0c7b0-fed1-11e7-9747-943b5f8f490e.png)

**Comment by YangLou1** [comment]
**We firstly should delete the following image:**
![alt text](http://open-learning-exchange.github.io/pages/vi/images/vi-success.png)

**Then rewrite the relevant content as following:**
Then, click on the "Register" button. Your registration request for your community will be automatically accepted from the nation side. You will see the following message.
![alt text](http://open-learning-exchange.github.io/pages/vi/images/vi-registration-accepted.png)
After clicking on OK button, you will be automatically logged in.
Then, post to the Gitter chat the screenshot you took earlier.

**Comment by xyb994** [comment]
Make sense, go head and make a PR.

**Comment by YangLou1** [comment]
@xyb994 Changes have been made. Please check the PR.
