### ISSUE TITLE
Revise Take the Course Section

### ISSUE THREAD

**Issue by YangLou1** [open-learning-exchange/open-learning-exchange.github.io#1576]
See below for the result after following this instruction: "To get to Publications, click on "Manager" from the dashboard, then the publications button." It's not relevant to Take the Course Section.
![image](https://user-images.githubusercontent.com/35347763/35201062-ec22b4dc-fee5-11e7-854c-bcc7d0ea6d42.png)

Also, it's more helpful to add an image to show Take the Course steps to future interns.

**Comment by YangLou1** [comment]
We should delete this sentence: "To get to Publications, click on "Manager" from the dashboard, then the publications button.", and add the following image after the three **STEPS** items.
![ole course](https://user-images.githubusercontent.com/35347763/35201165-24747680-fee7-11e7-8b13-05cdf79ee885.png)

**Comment by ofrank23447** [comment]
Okay, adjust the changes and open a PR.

**Comment by YangLou1** [comment]
@ofrank23447 I have made the changes and please check the created PR.
