### ISSUE TITLE
Troubleshooting Information is ambigous : tg-router-config.md 

### ISSUE THREAD

**Issue by adepojubosun** [open-learning-exchange/open-learning-exchange.github.io#1582]
Information doesn't say to specifically restart configuration process after resetting router to factory default. There's only "start again" in a new paragraph with no link or information available. Issue can be found [here](http://open-learning-exchange.github.io/#!pages/techgenius/tg-router-config.md).

**Comment by adepojubosun** [comment]
I suggesting specifying more instructions after resetting the router and linking to initial steps. Gives more information on what to do after router factory reset.

**Comment by xyb994** [comment]
Good suggestion, go ahead and create a PR.
