### ISSUE TITLE
Spelling Error on Git Repositories Page

### ISSUE THREAD

**Issue by CindyPSU** [open-learning-exchange/open-learning-exchange.github.io#1586]
While reviewing the Git Repositories page "Summary", I noticed two spelling errors with the word "repository". See the highlights in the screenshots below. They just need to be fixed.

![gitrepositorysumerror](https://user-images.githubusercontent.com/35432613/35261239-8889cf54-ffcc-11e7-8ab3-60036a2fc919.png)

**Comment by ketruong** [comment]
Good catch. Make a PR.

**Comment by CindyPSU** [comment]
Fixes completed. PR #1587
