### ISSUE TITLE
Typography is not consistent 

### ISSUE THREAD

**Issue by vishwakarmaanil** [open-learning-exchange/open-learning-exchange.github.io#1588]
In tg-planet-user-manual.md, some of the subquestions have Italic Style and Some of them do not 

For example: 
It should be Like this:
**# How do I Navigate and Use Planet?**
- _How do I access Planet and become a member?_
- _What are the differences between Learners, Leaders, and Managers?_
- _How do I navigate the Dashboard?_

But Its like this:
![](https://image.ibb.co/jVQkEG/1.png)
![](https://image.ibb.co/fQ2XuG/2.png)
![](https://image.ibb.co/isQ7Tb/3.png)
Here is the [Rawgit Link](https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/master/pages/techgenius/tg-planet-user-manual.md)

**Comment by xyb994** [comment]
Sure, go ahead and create a PR.
