### ISSUE TITLE
Missing periods in the README.md

### ISSUE THREAD

**Issue by Going-Gone** [open-learning-exchange/open-learning-exchange.github.io#1590]
There are some areas that do not have a period at the end of the sentence. 
The list is one of those areas, and then the second picture could either have a period or run on with the second sentence below it. 

![screen shot 2018-01-23 at 10 48 51 am](https://user-images.githubusercontent.com/28640954/35288821-5c77bbf6-002b-11e8-848d-1cb98acac09e.png)
![screen shot 2018-01-23 at 10 49 07 am](https://user-images.githubusercontent.com/28640954/35288824-5ded0b1c-002b-11e8-9892-6b70e07c9a67.png)

**Comment by kylemathias** [comment]
Go ahead and and make a PR.
