### ISSUE TITLE
Incorrect syntax for link vi-chat.md

### ISSUE THREAD

**Issue by Going-Gone** [open-learning-exchange/open-learning-exchange.github.io#1593]
It appears that this link is showing in syntax form. 
Incorrect syntax. 
![link is wrong](https://user-images.githubusercontent.com/28640954/35292474-3754631e-0036-11e8-9071-1bf7906ada07.png)

**Comment by kylemathias** [comment]
Could you be more specific? Were is this problem exactly located in our wiki.

**Comment by Going-Gone** [comment]
Ok so, i was not seeing that the link was the chat embedded into the page. After viewing the page it does appear that this embedded link is working correctly.
