### ISSUE TITLE
Additional detail for mac users 

### ISSUE THREAD

**Issue by Going-Gone** [open-learning-exchange/open-learning-exchange.github.io#1594]
This could be adjusted to show how to copy paste with mac as well. 
![addmoreinfo](https://user-images.githubusercontent.com/28640954/35292740-21512754-0037-11e8-8c0d-3ba29b3106df.png)

**Comment by kylemathias** [comment]
I would say change it from Ctrl+C and Ctrl+V to "Copy and Paste"

**Comment by kylemathias** [comment]
Again, try to be more detailed about the issue. Link to the exact location.

**Comment by Going-Gone** [comment]
http://open-learning-exchange.github.io/#!./pages/vi/vi-chat.md

**Comment by Going-Gone** [comment]
Would a link to the actual page like this be good, along with the picture?

**Comment by kylemathias** [comment]
Yes, link to the page and location, images as well.

**Comment by xyb994** [comment]
Closing this as #1617 was merged.
