### ISSUE TITLE
Additional information for who to tag

### ISSUE THREAD

**Issue by Going-Gone** [open-learning-exchange/open-learning-exchange.github.io#1595]
I think it would be good to list that we should be tagging those with the credentials like @dogi or @xyb994 or @ketruong 

![screen shot 2018-01-23 at 12 16 46 pm](https://user-images.githubusercontent.com/28640954/35292981-dcc603d8-0037-11e8-8989-1cb2509abae8.png)

**Comment by ofrank23447** [comment]
I don't think this is necessary as the credentials might change other than dogi.

**Comment by Going-Gone** [comment]
Could we have the role, instead of specific individuals?

**Comment by ofrank23447** [comment]
What do you mean by the role?

**Comment by xyb994** [comment]
Normally we would `@` people when exchanging comments.

Looks like Gitter does [support GitHub team mentions](http://blog.gitter.im/2014/10/02/group-mentions/). But as @ofrank23447 said, this might change depending on people's availability. Newly accepted virtual interns are all asked to help with github.io.

**Comment by Going-Gone** [comment]
Thanks for the feedback!
