### ISSUE TITLE
Add github.io repo review process

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1599]

**Comment by sahilph** [comment]
Can you please explain what this issue is about ?

**Comment by xyb994** [comment]
@sahilph It's about adding more detail to "reviewing pull requests and issues" section https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/robots/rbts-intern-orientation.md#reviewing-pull-requests-and-issues
