### ISSUE TITLE
Prerequisites seems a bit long and unnecessary

### ISSUE THREAD

**Issue by pengchengzhai** [open-learning-exchange/open-learning-exchange.github.io#1604]
In Step 3, the prerequisites seem a bit long and I went through the entire section that I have been familiar with before but I was afraid that I may missed something import. The prerequisites should be couple lines of sentences with links which leads to a new tab that explain more about Markdown and note that if people who is familiar with Markdown should go ahead and jump to start step.

**Comment by xyb994** [comment]
There is a WIP [PR](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1547) that reduces some content in the section you mentioned, you are welcome to comment on it.

**Comment by xyb994** [comment]
Closing this as step 3 has been updated in PR #1547.
