### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by Going-Gone** [open-learning-exchange/open-learning-exchange.github.io#1620]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-configurations.md
![screen shot 2018-01-28 at 6 38 22 pm](https://user-images.githubusercontent.com/28640954/35490113-d8dfb1a4-0462-11e8-86ef-eb2d44f0f0d9.png)

There should be a "the" in this sentence where the "*" is.
"After clicking on * OK button, you will be automatically logged in."

**Comment by xyb994** [comment]
@Going-Gone Thanks for catching the small grammar error, go ahead and create a pull request.

**Comment by xyb994** [comment]
Closing this as #1622 was merged.
