### ISSUE TITLE
Wording change 

### ISSUE THREAD

**Issue by Going-Gone** [open-learning-exchange/open-learning-exchange.github.io#1623]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-configurations.md

Change the highlighted section in the picture below to "copy and paste" 

![screen shot 2018-01-29 at 5 15 25 pm](https://user-images.githubusercontent.com/28640954/35539676-34858d8e-0518-11e8-9bf0-ac803016af85.png)

**Comment by xyb994** [comment]
Closing this as #1624 was merged.
