### ISSUE TITLE
Github page wasn't opened after clicking link (step #2, point #3)

### ISSUE THREAD

**Issue by ArtemLee** [open-learning-exchange/open-learning-exchange.github.io#163]
When "Here is the first page of the PDF "Feelings"" link was clicked, PDF-file was opened instead of Github page. This happened when also "Here is the song "Opposite Song"", "Here is the video "Burka Avenger"" were clicked.
![issue1](https://cloud.githubusercontent.com/assets/16288650/16258181/614bd4f8-387e-11e6-9e3d-3672cb6968a3.png)
![issue2](https://cloud.githubusercontent.com/assets/16288650/16258213/89042432-387e-11e6-8f49-44b18cd1a304.png)

**Comment by ArtemLee** [comment]
@dogi @EmilyLarkin I think that new versions of browser have got pdf-reader. Because of this, pdf-files open automatically. I think that issue can be closed without dealing with code.

**Comment by dogi** [comment]
+1
