### ISSUE TITLE
Issue # already included in title

### ISSUE THREAD

**Issue by NickBratt** [open-learning-exchange/open-learning-exchange.github.io#1630]
On the introduction page under step 8, the "NOTE:" section says to include the issue number in your title but this is added automatically. The note section seems unnecessary.

**Comment by xyb994** [comment]
The note is talking about adding issue number to commit messages.
The number that gets added automatically to the title is pull request number.

An example: https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1601

**Comment by NickBratt** [comment]
So does this not apply when opening a brand new issue?

**Comment by NickBratt** [comment]
Never mind I see what you are saying now.
