### ISSUE TITLE
Adding troubleshooting information to bell configurations page

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/open-learning-exchange.github.io#1634]
In vi-configurations.md, under the Database section, troubleshooting 2 should be added from the vagrant page. 
text of troubleshooting 2:
'When trying to access http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html in step 4, you may experience an error such as the following: "no_db_found". A simple solution will be using vagrant destroy to delete the current machine, then try vagrant up to rebuild it.'
I ran into this issue while working through the Configuration Guide in step 1, and was unsure how to fix it as the solution was in step 2 Vagrant Tutorial.

**Comment by xyb994** [comment]
@ArashDai Thank you for raising this issue. For now you could go ahead and create a PR that add a troubleshooting section to https://open-learning-exchange.github.io/#!./pages/vi/vi-configurations.md like in https://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md

**Comment by xyb994** [comment]
Closing this as PR #1641 was merged.
