### ISSUE TITLE
Underline/Highlight the text on BeLL-Apps

### ISSUE THREAD

**Issue by vimalababu4** [open-learning-exchange/open-learning-exchange.github.io#164]
Under BeLL-Apps:
On paragraph 3-4:
Can we highlight the instruction : 

> **Before hitting "Submit Configurations", please take a screenshot and save for later to submit to us.**

OR,  we can add this  lines of text before beginning of "Set Configurations"  that would help new interns.  It will make them aware of taking screetshot before hiiting submit button

**Comment by dogi** [comment]
:D

**Comment by Hulmani** [comment]
I read the instructions to "share the screenshot configurations" on the BeLL Apps page twice, I would recommend that it is highlighted (for example as a header) once.
Link to the page:
 http://open-learning-exchange.github.io/#!pages/bellapps.md)

**Comment by dogi** [comment]
+1

please fix that

**Comment by Hulmani** [comment]
I tried to solve the issue by

> ### highlighting the screenshot of the SUBMIT CONFIGURATION requirement and also highlighting to submit the screenshot.
