### ISSUE TITLE
Rawgit Clarification

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/open-learning-exchange.github.io#1644]
I would like to clarify the Rawgit explanation under the GitHub-issues page, and add a small guide detailing how to use the rawgit generator on rawgit.com properly. I will start on this as soon as it is approved by 3 members.

**Comment by kylemathias** [comment]
@ArashDai You can start working on the changes any time.

**Comment by xyb994** [comment]
Closing this as PR #1648 was merged.
