### ISSUE TITLE
FAQ #3 more information about this internship

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/open-learning-exchange.github.io#1645]
I would like to change the link to lead directly to the indeed posting, instead of going to: https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs , the link would lead to: https://www.indeed.com/viewjob?jk=0d660f98f7710439&tk=1c5ovu172brecd3l&from=company 

Unless that link changes every so often. I will start work on this as soon as it is approved by 3 members.

**Comment by kylemathias** [comment]
@ArashDai this has been brought up before. the direct link has caused problems in the past. we are leaving it as is for now.

**Comment by ArashDai** [comment]
cool thank you
