### ISSUE TITLE
Highlight priority of ReadMe in Vagrant Tutorial for clarity

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/open-learning-exchange.github.io#1646]
I would like to make the ReadMe for the vagrant tutorial more prominent, before showing the abridged instructions that are on the vagrant tutorial page. As it is currently the ReadMe could be overlooked. I would fix the formatting by adding a Getting Started header, a short blurb about what vagrant is, next the prerequisite section, and after that a Vagrant Installation header that would point interns to the ReadMe before explaining there are abridged installation instructions below. I will start working on this issue as soon as it is approved by 3 members.

**Comment by kylemathias** [comment]
You could just move that section into the Prerequisites. Getting Started and Prerequisites are kinda of the same thing in this context. You can clarify the paragraph and move it to Prerequisites.

**Comment by ArashDai** [comment]
sounds good thank you
