### ISSUE TITLE
Missing step to Take The Course in Step 4 BeLL Apps

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/open-learning-exchange.github.io#1650]
In the Take The Course section of the BeLL Apps guide, in between steps 1 and 2, the user must click the Admission button, before the button to open the interns course becomes visible. I will fix this issue by adding "click the Admission button" as step 2 and shifting the rest down. I will begin work on this once approved.

**Comment by aas919** [comment]
@ArashDai Can you please paste a screenshot of the Admission button ?

**Comment by ArashDai** [comment]
The admission button no longer shows up on my BeLL, so I think I would have to vagrant destroy to get it to show up again

**Comment by xyb994** [comment]
@ArashDai If that's the procedure, go ahead and create a pull request.
