### ISSUE TITLE
fix vi-former-members.md

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1657]
- some items are not in chronological order
- end dates are missing for some VIs, look them up in their GitHub account history?

**Comment by sahilph** [comment]
Yes, I was thinking about the missing dates too. Looking up the account history seems to be a good option.

**Comment by kylemathias** [comment]
I would say adding end dates would be good if the intern has been inactive for more than 2 weeks

**Comment by aakarnik** [comment]
I would like to work on this issue.

**Comment by xyb994** [comment]
@aakarnik We could split the task or find out how to use GitHub's API to do get their latest contribution.

**Comment by aakarnik** [comment]
@xyb994 I actually looked up the history of a few members and it does not seem very difficult to locate when they had last contributed to open-learning-exchange.
![screenshot 323](https://user-images.githubusercontent.com/37878201/38687709-4c0b48fc-3e45-11e8-8cc1-255fa12924be.png)

**Comment by xyb994** [comment]
@aakarnik 

Yes, this works since most people don't have a very active public profile. Also note that `ole-vi` is also our organization. 

Please reference this issue when creating new pull request.

**Comment by aakarnik** [comment]
I have a question: Have some of the members contributed anywhere apart from GitHub? 
Some of the working periods (bold) look a little short based on the GitHub history:

![screenshot 329](https://user-images.githubusercontent.com/37878201/38749230-de1ba276-3f1e-11e8-8be0-93d8e065aac1.png)

**Comment by xyb994** [comment]
@aakarnik 

Last time Daisy was active on Sept 20 https://github.com/daisywatson?tab=overview&from=2017-09-20

I'm not sure about the other 3, but some people do join then disappear shortly after the initial meeting. I'd say use whatever date we could find, then @dogi could probably take a look before we merging

**Comment by aakarnik** [comment]
Okay, sounds good!
