### ISSUE TITLE
Update Steps for Ubuntu in BeLL Installation

### ISSUE THREAD

**Issue by sahilph** [open-learning-exchange/open-learning-exchange.github.io#1663]
I had a few issues while doing "Step 1 - BeLL Installation" of first steps. My OS is Ubuntu 16.04

After following the initial 3 installation steps for Ubuntu:
> sudo apt-get install git
> sudo apt-get install virtualbox
> sudo apt-get install vagrant

There arises a problem with "vagrant up".:

> git clone https://github.com/dogi/ole--vagrant-vi.git
> cd ole--vagrant-vi
> vagrant up     **<- This step gives error.**

It is caused as Vagrant is obsolete on Ubuntu's universe repositories with the version stuck at 1.8.2.

Thus the steps need to be updated using any one of the possible solutions:
1. Download the latest .deb file from vagrantup.com and install it.
2. Use a third party repo maintained by Wolfgang Faust at https://vagrant-deb.linestarve.com/

The advantage of the 2nd solution is that it integrates with Ubuntu's Update system and will automatically keep Vagrant up-to-date .

**Comment by xyb994** [comment]
@sahilph Thanks for catching the issue. [The problem was address before](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1509/files) but was replaced by content from somewhere else when I was revamping this step.

The fact that there's not a link to latest version of vagrant is annoying. Let's see what others think about solution 2.

**Comment by sahilph** [comment]
Another Option: 
HashiCorp Provides a JSON for all their releases at https://releases.hashicorp.com/index.json. We could use it to create our own repository. (This is also what that guy did)

**Comment by dogi** [comment]
@sahilph thanks

I suggest:
```
sudo apt-get install git
sudo apt-get install virtualbox
wget https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb
dpkg -i vagrant_2.0.2_x86_64.deb
```

**Comment by sahilph** [comment]
@dogi 
Yes. That will work for now. But it would not keep up with new releases of Vagrant. We would have to update the wiki manually as per new releases of Vagrant.

**Comment by xyb994** [comment]
@sahilph 

Yeah, @dogi and I was talking not everyone would be comfortable with adding the key.

So maybe we could ask people go to https://www.vagrantup.com/downloads.html to copy the link to the latest version and use if after `wget`.

**Comment by sahilph** [comment]
Yes we could do the `wget` option. It would install the latest version of Vagrant. Do you want me to proceed with that ?

**Comment by xyb994** [comment]
@sahilph Yes, go ahead and create a pull request.

**Comment by sahilph** [comment]
PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1675
