### ISSUE TITLE
Fix Links and images in Q14

### ISSUE THREAD

**Issue by sahilph** [open-learning-exchange/open-learning-exchange.github.io#1665]
> 1. Go to this **atlas box page.**

This link give 404 error. It should be changed to: https://app.vagrantup.com/ole/boxes/jessie64
The image should able be updated accordingly.

>You should first check if **Hashicorp's atlas** is up and running by looking at the left sidebar:

The above link also gives 404 Error.A more accurate way to check the status would be here: https://status.hashicorp.com/

**Comment by ArashDai** [comment]
Confirmed links are dead, go ahead and create a pull request

**Comment by sahilph** [comment]
PR created https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1667
