### ISSUE TITLE
Add Troubleshooting step in vi-bell-installation.md

### ISSUE THREAD

**Issue by sahilph** [open-learning-exchange/open-learning-exchange.github.io#1668]
In Ubuntu we might get this error with “vagrant up”. Virtual Box does not start:

> Stderr: VBoxManage: error: The virtual machine 'ud381_default_1463617458900_49294' has terminated unexpectedly during startup with exit code 1 (0x1) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

This is caused when Virtual Box get a minor version Update. (i.e. 5.0.x -> 5.1.x or 5.1.x -> 5.2.x) and get automatically updated by Ubuntu (or when user manually give a upgrade command). There are some old unused modules, who are not compatible with the newer version, remain installed which causes the above problem and prevent Virtual Box from starting. A system restart also does not solve the problem.

To solve it first remove the unused packages:
> sudo apt-get autoremove

Then reconfigure virtualbox to install updated modules:
>sudo /sbin/vboxconfig

I got this error yesterday when the system updated. Can this be added as a Troubleshooting step in BeLL Installation ?

**Comment by kylemathias** [comment]
It can be added. Make a PR and let us know when you do.

**Comment by sahilph** [comment]
@kylemathias Check PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1671
