### ISSUE TITLE
Duplicate Links

### ISSUE THREAD

**Issue by ArcyFlores** [open-learning-exchange/open-learning-exchange.github.io#1670]
Though trivial, there are duplicate links in the **Useful Links** section, of the [Git Repositories](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md) step. 
I think they should be removed, otherwise it seems they are additional resources when in fact, they are not. 
<img width="912" alt="screen shot 2018-03-01 at 9 47 24 am" src="https://user-images.githubusercontent.com/13513155/36850813-b27bb710-1d35-11e8-96a7-93b35e90e5a2.png">

**Comment by xyb994** [comment]
@ArcyFlores Thanks for catching the issue, go ahead and create a pull request for it.
