### ISSUE TITLE
Modifying the tracking progress script

### ISSUE THREAD

**Issue by sahilph** [open-learning-exchange/open-learning-exchange.github.io#1672]
Can the [vi-track-progress.html](http://open-learning-exchange.github.io/pages/vi/vi-track-progress.html) be modified to show Total PRs, Total Merged PRs, Total Issues all at once by entering username just one time ?
It is cumbersome and redundant to enter username ever time.

Also the script does not give any response if a invalid username is entered. (E.g. If, while entering username, someone accidentally mistypes his/her username then he/she won't get any response and would be confused about why there is no response.)
Shall this also be changed ?

**Comment by Jackbui96** [comment]
In my opinion, what you have suggested is a very good enchantment. We can save the user's info to the browser's cache so that we dont have to type the input all over again. Plus, I also agree with the valid/invalid input. What do other VI think?

**Comment by xyb994** [comment]
@sahilph Sure, the existing vi-track-progress.html could be better. Feel free to start from scratch since the existing one is not that well organized. Don't forget to keep it simple, clean, and user-friendly.

**Comment by sahilph** [comment]
@xyb994 alright. Will start working on it.

**Comment by sahilph** [comment]
Please check PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1674
