### ISSUE TITLE
add potential questions to FAQ for virtual intern

### ISSUE THREAD

**Issue by ZhekaiJin** [open-learning-exchange/open-learning-exchange.github.io#1680]
virtual interns have run into problem like :
>I deleted my ole--vagrant-vi folder by mistake. I had to download all the configs again and create a admin profile on Bell. But now it shows learner in the app. How do I create manger profile again?

why I did vagrant destroy and then vagrant up there is error saying this ?

>"A Virtual Box machine with the name 'homestead' already exists.
Please use another name or delete the machine with the existing
name, and try again.
 "
Answers should be given in the technical questions section in the FAQ page.

**Comment by ZhekaiJin** [comment]
Hi Here is a potential solution
```shell
vagrant global-status
vagrant destroy [imagename]
cd ..
rm -rf ole--vagrant-vi
git clone https://github.com/dogi/ole--vagrant-vi.git
cd ole--vagrant-vi
vagrant up
```
With replicate names : possible solution 
```shell
VBoxManage list vms && VBoxManage list runningvms
vboxmanage controlvm nameofvm poweroff
vboxmanage unregistervm NAMEOFVM --delete
```
then repeat what we did in the first step starting from cd..

**Comment by sahilph** [comment]
@ZhekaiJin Could you please provide the steps to reproduce these errors ?

**Comment by ZhekaiJin** [comment]
For the first case, it's asked by another potential virtual intern in chat. I tried the same steps but everything is fine. I guess it may depends on OS distribution and some may reserve the image info even when original file is gone. But resign your administer account in the setting will block you from setting another learner account with the same name and password/sign in with the original admin account / setting any other admin account.  So I think it is necessary to put the steps to recreate an brand new image to allow users to set up the admin page.  
         And Ctrl+C before successful compilation during vagrant up does give you an unwanted image which does not show up in 

```shell
vagrant global-status
```

 but 

```shell
VBoxManage list vms
```
.

**Comment by xyb994** [comment]
@ZhekaiJin 
I removed my ole--vagrant-vi folder and ran into the second issue you brought up.
Go ahead and create a PR to adds those two problems to FAQ.
