### ISSUE TITLE
Assuming understanding how vim works could make git beginners get stuck

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/open-learning-exchange.github.io#1688]
In http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md
Section "Sync Your Fork", describes how to get out of vim relatively gracefully (but assuming it all goes well).

This issue is a bit opinionated, but being totally new to git, vim would have freaked me out - still does at times.

I'd suggest one sentence to point people to more friendly alternatives.

**Comment by Tille88** [comment]
Vim can be difficult for people who use it first time. Some simpler text editors, and how to set them up as default editors for git are [Nano][nano-git-setup] (command line), [Atom][atom-subl-git-setup] (need to [download][atom-downl]) and [Sublime Text][atom-subl-git-setup] (need to [download][subl-downl]).

[nano-git-setup]: https://superuser.com/questions/503844/git-on-mac-how-to-set-nano-as-the-default-text-editor
[atom-subl-git-setup]: https://help.github.com/articles/associating-text-editors-with-git/
[atom-downl]: https://atom.io/
[subl-downl]: http://docs.sublimetext.info/en/latest/getting_started/install.html

Opinions?

**Comment by xyb994** [comment]
@Tille88 @Jackbui96 I'm combining your ideas, how about this?

> Vim can be difficult for people who use it first time. Check out the documentation on [Associating text editors with Git](https://help.github.com/articles/associating-text-editors-with-git/) if you would like to use a simpler text editor.

**Comment by Tille88** [comment]
@xyb994 @Jackbui96 
I think that could work. I know that people who like vim tends to **really really** like vim, and people who dislike it equally strongly dislike it - my main issue being that it is not really super clear which mode you are in (or even what modes are) if you're not used to it.

Not assuming prior knowledge of git and having someone thrown into vim is very likely to lead to:
"What is this? Nothing happens when I write. Okay, guide say press i. Oh did I just delete a tab or what? Cmd+Z Cmd+Z Cmd+Z, no doesn't work, quit? quit()? Now its even more of a mess. Need to make sure nothing of this is saved. Lookup guides. What is different between !q and q!? Damn, forgot the colon" Etc.

@xyb994's suggestion is succinct and works in my opinion, but waiting for other input before working on this.

**Comment by kylemathias** [comment]
Telling people what text editor you use is not really a priority. If we need to start telling people how to use a text editor, I think we are aiming for the wrong people to do this internship. 

If you really want to add something about a text editor, you can say something on long the lines of "use whatever editor you would like. Some suggestions would be "Nano (command line), Atom (need to download) and Sublime Text (need to download)" etc...

**Comment by Tille88** [comment]
Okay, noted @kylemathias. If no one else disagrees, this issue can safely be closed (I'll deal with that in like 24 hrs). 

It was a bit unclear which level this aimed at giving a relatively low level intro to git, which common features and customisations would be worth pointing out.
