### ISSUE TITLE
Have e.g. screenshots of current projects shown earlier to interns 

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/open-learning-exchange.github.io#1689]
To incentivise potential virtual interns, it would seem good to give a bit easier access to current projects. 

They are listed in First Steps => The Big Picture, in a link. 

However after clicking that link, and then following the "Angular Reboot" link, I still have not seen any screenshot of the Planet UI - which looks a lot more interesting to work on compared to the somewhat clunky current implementation of BeLL. For most it would take future interns to the end of Step 4 until they see what is in the pipeline. 

It would be nice to have that exposed a bit earlier. It does seem a little bit unnecessary to put it in http://open-learning-exchange.github.io/#!./pages/robots/rbts-angular.md but at the very least I think it should be shown in step 4 http://open-learning-exchange.github.io/#!./pages/vi/vi-bellapps.md for comparison.

Iif someone would have a better suggestion of where to put it, and if it could be an improvement, I would be happy to make any required changes. :)

**Comment by xyb994** [comment]
@Tille88 Great point on how to be more attractive to potential virtual interns. I agree with what you said here, not sure if there's a better place to add screenshot of Planet at this time. Once Planet matures with more features, we'll gradually replace BeLL apps with Planet in First Steps.

@dogi what do you think?

**Comment by YangLou1** [comment]
@Tille88 I like the idea that showing current projects' user interface to potential virtual interns, and this is a more exciting and intuitive way to give them a basic understanding about what we are working on.

**Comment by xyb994** [comment]
@Tille88 I think you could go ahead and add the screenshot to "Introduction to Planet" section for now.

**Comment by Tille88** [comment]
@xyb994 Ok, I'm on it :)

**Comment by Tille88** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1694
