### ISSUE TITLE
Community updates issues

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/open-learning-exchange.github.io#1690]
In http://open-learning-exchange.github.io/#!pages/vi/vi-bellapps.md
Section "Different Kinds of Updates to Your Community"

For me it didn't work to manually update (status => ) update publications in Chrome. 

It did first work when I did use Firefox. That could be the issue, or just logging in again perhaps?

Early on in the Steps, it is mentioned that Firefox is the way to go, but in the same section (again: "Different Kinds of Updates to Your Community") Chrome is mentioned, so I assumed it would be okay to use?

**Comment by Tille88** [comment]
The suggested changes depends on the likely reasons for the issues I encountered, so please someone with more insight into the inner workings of BeLL, could you help give some suggestions?

**Comment by xyb994** [comment]
@Tille88 Thanks for pointing out the issue. I was actually [going to remove Chrome in vi-bellapps.md](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1692). As far as I was told, Firefox is the browser to use with BeLL.
