### ISSUE TITLE
FAQ git/github link collection changes

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/open-learning-exchange.github.io#1691]
I have a few suggested changes for the git/github/markdown links section in the FAQ
http://open-learning-exchange.github.io/#!pages/vi/vi-faq.md. This will be a bit lengthy.

i) I am missing my all-time favorite git-resource: http://gitimmersion.com/
It gives a bit more depth than most beginner tutorials, but also not too much (covers aliases, common shortcuts, setting up a .bashrc file with non-standard git log output that can be copied, etc.). Still only about an hour commitment or so.

ii) This list is getting quite long, so it is not clear which one to start with.
I would suggest breaking it down into subcategories. I will give a suggested breakdown in a comment below for discussion. May take a few iterations to get something good for this kind of change.

iii) Breaking out Vi/Vim, since not strictly related IMHO. Would not be obvious where to find it if I was looking for it.

iv) Maybe add some reading on common git workflows? It helped me a lot when I got started with git. That could maybe be the case for others as well? 

iv) It was a long time since I looked at the Codecademy course, but from my recollection I found it to be a bit time consuming for the amount of info I was able to internalize. Anyone else have other experience from that course?

**Comment by Tille88** [comment]
## Suggested first iteration:

## **From this:**

#### *GitHub and Markdown*

- [GitHub and Markdown Short Tutorials](https://guides.github.com/)
- [GitHub Help](https://help.github.com/categories/search/)
- [GitHub's Git Tutorial](https://try.github.io/)
- [Git-it Workshop](http://jlord.us/git-it/)
- [Codecademy's Learn Git Course](https://www.codecademy.com/learn/learn-git)
- [Git Pro (Book)](https://git-scm.com/book/en/v2)
- [Git Cheat Sheet (PDF)](https://education.github.com/git-cheat-sheet-education.pdf)
- [GitHub Tips](https://github.com/git-tips/tips/blob/master/README.md)
- [Markdown Syntax](https://daringfireball.net/projects/markdown/syntax)
- [Markdown Cheat Sheet (PDF)](https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf)
- [Markdown Editor](https://jbt.github.io/markdown-editor/)
- [Vi Cheat Sheet (PDF)](https://www.shell-tips.com/sheets/vi_help_sheet.pdf)


## **To this:**

#### *GitHub and Markdown*


* #####  General
	- [GitHub and Markdown Short Tutorials](https://guides.github.com/)
	- [GitHub Help](https://help.github.com/categories/search/)
 	- [Git Cheat Sheet (PDF)](https://education.github.com/git-cheat-sheet-education.pdf)

* #####  First Steps
	- [GitHub's Git Tutorial](https://try.github.io/)
	- [Git-it Workshop](http://jlord.us/git-it/)
	- [Codecademy's Learn Git Course](https://www.codecademy.com/learn/learn-git)

* #####  Intermediate
	- [Git Immersion](http://gitimmersion.com/) (**ADDED, really good**)

* #####  Reference/Advanced
	- [Git Pro (Book)](https://git-scm.com/book/en/v2)	
	- [GitHub Tips](https://github.com/git-tips/tips/blob/master/README.md)
	- [Oh, Shit, Git](http://ohshitgit.com/) (**ADDED, lighthearted, but lifesaving at times**)
	
* #####  Git Workflow
	- [Git Workflow - High Level](https://www.atlassian.com/git/tutorials/comparing-workflows) (**ADDED**)
	- [Git Workflow - High Level, Short](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) (**ADDED**)
	- [Feature Branch Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) (**ADDED**)
 
* #####  Markdown
	- [Markdown Syntax](https://daringfireball.net/projects/markdown/syntax)
	- [Markdown Cheat Sheet (PDF)](https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf)
	- [Markdown Editor](https://jbt.github.io/markdown-editor/)

#### *Vi/Vim*
- [Vi Cheat Sheet (PDF)](https://www.shell-tips.com/sheets/vi_help_sheet.pdf)

## **Any input for this? It gets a little long, perhaps scrapping a few sections, but dividing it up into different sections I think would help still :)**

**Comment by Jackbui96** [comment]
@Tille88 Some suggestions:
1. "Github and Markdown" should be changed to "References".
2. I think we would need like 3 subcategories only: "Markdown", "Git", and "Misc."
3. Remove some of the links, or move those links to more suitable places. Such as, some link can go to [Markdown Page](http://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md), or [Github Page](http://open-learning-exchange.github.io/#!pages/vi/vi-github-and-repositories.md)
4. Try to keep it short. Because remember, these resources are redundant.

What do other vi think?

**Comment by xyb994** [comment]
@Tille88 Thank you for adding more useful links and splitting things up into sections to make things clearer. ohshitgit and atlassian workflow links are the ones I was planning to add somewhere in the First Steps too. We did receive good feedback after sending some virtual interns the forking workflow link.

@Jackbui96 If looking at the modification with context on [FAQ page](https://open-learning-exchange.github.io/#!pages/vi/vi-faq.md#Helpful_Links), @Tille88's suggestion make sense.

@Jackbui96 also brought up the point that keeping those links in FAQ might not get much attention from virtual interns. I'll probably also add some of them to the respective steps when revamping First Steps.

**Comment by Tille88** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1693
