### ISSUE TITLE
TechGeniuses => Manual/Full Installation Dead link

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/open-learning-exchange.github.io#1695]
This link is dead, and I can't find that any really suitable .md file in the repo.

http://open-learning-exchange.github.io/#!pages/techgenius/tg-installation.md

Any idea how I can get that up again? Or maybe it should be removed?

The only one I can't find linked is team viewer
http://open-learning-exchange.github.io/#!pages/techgenius/tg-teamviewer-install.md

Is that used somewhere else, or would it be good to remove that from the files?

**Comment by xyb994** [comment]
@Tille88 
Thank you for catching the dead link, it's actually http://open-learning-exchange.github.io/#!pages/vi/vi-bell-installation.md now. I renamed it at https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1659 without realizing it's on navigation. Please go ahead and fix the navigation link.

TeamViewer is actually referenced in http://open-learning-exchange.github.io/#!pages/techgenius/tg-faq.md.

**Comment by Tille88** [comment]
@xyb994 I assume this is what you meant(?):

https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1698
