### ISSUE TITLE
Formatting inconsistency of password/username in techgenius/tg-router-config.md

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/open-learning-exchange.github.io#1696]
http://open-learning-exchange.github.io/#!pages/techgenius/tg-router-config.md
Introduction section
>  The default login for TP-Link router is username: “admin” and password: “admin” without the quotation marks.

Probably easier to just change it to use same formatting as http://open-learning-exchange.github.io/#!pages/vi/vi-nation.md "Check the sync worked"

Seems like a simple fix, so will do it immediately.

**Comment by Tille88** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1697

**Comment by sahilph** [comment]
PR Merged.
