### ISSUE TITLE
issue in tg-planet-user-manual.md

### ISSUE THREAD

**Issue by rashikbariya** [open-learning-exchange/open-learning-exchange.github.io#1710]
in next step section, there is a misleading no.7, creating no.7 point to a "note"

**Comment by rashikbariya** [comment]
create a note section instead!!

**Comment by ManiBlitz** [comment]
Do you have a line number for the error or a screenshot of where the issue may be?

**Comment by xyb994** [comment]
Closing this due to no detail was provided.
