### ISSUE TITLE
Fix typos and structure of text beneath gitter chat page

### ISSUE THREAD

**Issue by gcantieni** [open-learning-exchange/open-learning-exchange.github.io#1720]
### Problem
The section below the gitter chat [here](http://open-learning-exchange.github.io/#!pages/vi/vi-chat.md) has several problems:
* It isn't clear what type of information is underneath the gitter chat because there's no heading or sections. 
* In addition, since the quote addressed to dogi isn't offset it looks like there a bunch of single line paragraphs which is uninviting to read.
* There are a couple typos (1. there's a dropped quotation mark at the end of the quote addressed to dogi and 2. on the last line "can be downloaded here" should be "*which* can be downloaded here") and there are words that can be eliminated like "relatively good amount" for conciseness. 

### Steps to reproduce the problem
N/A

### Screenshots
![chat-intro-choppy](https://user-images.githubusercontent.com/34512397/38692414-a951b81e-3e51-11e8-8064-669234344c1f.png)

### Proposed solution
* Make the quote addressed to dogi stand out more by using the block quote syntax
* Add a quotation mark at the end of the dogi quote
* Add "which" before "can be downloaded here"
* Eliminate "relatively good amount"
* Add some kind of heading to the information to tell the reader what it is such as "how to use the gitter chat"

**Comment by gcantieni** [comment]
Is the "iframe" the live feed from the gitter chat? If so, I think moving it to the bottom of the frame would be a valid way of improving the structure of the page. 

Otherwise I was thinking of adding a "how to use the gitter chat" heading. I think you're right that a horizontal line before and after would also help establish a structure. Do you have opinions over which is the best way?

**Comment by xyb994** [comment]
@gcantieni 

Yes, I was referring to line 6 of vi-chat.md.

I was working on this page but haven't push the change. Below are the screenshots of what it might look like at the bottom of the page. We probably still need more `###` to structure things.

<img width="1552" alt="screen shot 2018-04-13 at 2 58 10 pm" src="https://user-images.githubusercontent.com/7483137/38753051-2eb02d9a-3f2b-11e8-8fa1-4baea2f4b8be.png">

<img width="1552" alt="screen shot 2018-04-13 at 3 00 46 pm" src="https://user-images.githubusercontent.com/7483137/38753131-7a8cf356-3f2b-11e8-8e0b-3ab44e134080.png">

<img width="1552" alt="screen shot 2018-04-13 at 3 02 50 pm" src="https://user-images.githubusercontent.com/7483137/38753225-c62fa27c-3f2b-11e8-99b8-1989ac6e8c31.png">

**Comment by xyb994** [comment]
@gcantieni Since you are not added to the organization yet, you might not be able to make changes directly to the branch on this repo/my fork. I'll send you what I have on Gitter so you can work on it. Thanks you for helping improve the language here.

**Comment by gcantieni** [comment]
@xyb994 Sounds good! So will you just send your version of vi-chat.md, or did you have something else in mind?

**Comment by gcantieni** [comment]
@xyb994 

I used the version you sent me, restructured the page a bit, added another section, and eliminated some words. Do you think there's anything else that should go under *Best Practices*?

![updated-chat-v2](https://user-images.githubusercontent.com/34512397/38891996-04ed6852-4254-11e8-9d68-59eaac451410.png)

**Comment by xyb994** [comment]
@gcantieni The screenshot looks good. I can't think of anything else to add at this time. Please go ahead and create a pull request so others can look at the changes and give you feedback. You can always make changes after creating the pr.
