### ISSUE TITLE
Fixing 'Summary of Steps' in vi-github-and-repositories.md

### ISSUE THREAD

**Issue by aakarnik** [open-learning-exchange/open-learning-exchange.github.io#1721]
### Problem
The page that explains how to work with git commands and Github - http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md - there are two sections: *Summary* and *Summary of Steps* which essentially have the same purpose. The sections also have a considerable amount of repetition, which could be avoided to make the page more concise.

### Steps to reproduce the problem
N/A

### Screenshots
![issue3](https://user-images.githubusercontent.com/37878201/38745814-ae443096-3f13-11e8-8ecf-72b54f010f50.JPG)

![issue3 1](https://user-images.githubusercontent.com/37878201/38745815-ae5a11c2-3f13-11e8-8950-ad820ccc0e8b.JPG)

### Proposed solution
I would like to combine the sections to create one concise "Summary of Steps" section by adding the links from the "Summary" section to the "Summary of Steps" section.

**Comment by xyb994** [comment]
@aakarnik 
Yes, what yo said make sense. Please go ahead and create a pull request to combine those two sections together.
