### ISSUE TITLE
Merge Summary for Keeping Fork Updated

### ISSUE THREAD

**Issue by rhuturajm** [open-learning-exchange/open-learning-exchange.github.io#1732]
### Problem
In "Keeping Fork Updated", there are two summaries - "Summary" and "Summary of steps" which is not required as they can be merged into one complete summary.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="595" alt="untitled" src="https://user-images.githubusercontent.com/38227119/38842557-ad09cc84-41b8-11e8-8df2-dbb008ace3d8.png">

### Proposed solution

Step 1 of "Summary of Steps" can be merged with step 1 of "Summary"
Step 2 of "Summary of Steps" can be merged with step 12,13,14 of "Summary"
Step 3 of "Summary of Steps" can be added as with step 16 of "Summary"

**Comment by ManiBlitz** [comment]
I think that the "summary of steps" can be kept because it refers to the most important points of the "summary" part.

**Comment by rhuturajm** [comment]
Yes, but it looks more clean if you have just one summary
