### ISSUE TITLE
Change link at clone method HTTPS or SSH in vi-github-and-repositories.md

### ISSUE THREAD

**Issue by ManiBlitz** [open-learning-exchange/open-learning-exchange.github.io#1735]
### Problem
The link provided that is supposed to explain the difference between cloning with SSH and cloning with HTTPS just refers to the basis of cloning with SSH.
### Steps to reproduce the problem
N/A
### Screenshots
<img width="874" alt="screen shot 2018-04-18 at 12 29 52 am" src="https://user-images.githubusercontent.com/26188374/38911815-b37c0338-429f-11e8-84b6-ffe0bfb3fd69.png">

---

<img width="1680" alt="screen shot 2018-04-18 at 12 30 08 am" src="https://user-images.githubusercontent.com/26188374/38911821-bfe21c34-429f-11e8-9a54-a232559083e6.png">

### Proposed solution
Replace the link by this one, [SSH or HTTPS](https://help.github.com/articles/which-remote-url-should-i-use/), which contains more resources and details concerning the difference between both.

**Comment by ManiBlitz** [comment]
The amount of information to change is really small (just a link)

**Comment by xyb994** [comment]
@ManiBlitz Make sense, go ahead and create a PR.
