### ISSUE TITLE
Minor change to vi-github-and-markdown.md

### ISSUE THREAD

**Issue by rhuturajm** [open-learning-exchange/open-learning-exchange.github.io#1737]
### Problem
In vi-github-and-markdown.md, after you create profile and put it in the pull request, it says "Once everything looks good, the reviewer will merge your Markdown profile with the main repository. After the pull request is merged, you'll be able to see your personal page at open-learning exchange.github.io/#!pages/vi/profiles/<YourUserName>.md." But it does not specify how many review it requires before a pull request can be merged with the main repository.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="795" alt="untitlecacd" src="https://user-images.githubusercontent.com/38227119/38953160-d630d198-431b-11e8-9440-76fc0f9f914b.png">

### Proposed solution

Change the line to  "Once everything looks good after 3 reviews, one of the reviewer will merge your Markdown profile with the main repository. After the pull request is merged, you'll be able to see your personal page at open-learning exchange.github.io/#!pages/vi/profiles/<YourUserName>.md."

**Comment by xyb994** [comment]
@rhuturajm Go ahead and create a PR. Please use "3 approving reviews" instead of "3 reviews".

**Comment by rhuturajm** [comment]
@xyb994 Thanks will do!
