### ISSUE TITLE
vi-vagrant.md bullet point edit for Up, Suspend, Halt, and Destroy

### ISSUE THREAD

**Issue by rhuturajm** [open-learning-exchange/open-learning-exchange.github.io#1739]
### Problem
In vi-vagrant.md, under heading "Up, Suspend, Halt, and Destroy", instead of the paragraph it would look better if the information is put into the existing bullet point format

### Steps to reproduce the problem

N/A

### Screenshots

<img width="887" alt="untitvdsled" src="https://user-images.githubusercontent.com/38227119/38959237-da56818e-432d-11e8-9bc7-de00d8d32065.png">

### Proposed solution

The proposed bullet point structure is as follows :
- vagrant up will turn the virtual machine back on if it's currently "poweroff" when you to access your community BeLL again
- vagrant suspend will suspend the "running" virtual machine, its state will become "saved".
- vagrant halt will shut down the "running" virtual machine to conserve hardware resources of your computer, its state will become "poweroff".
- vagrant destroy will delete the virtual machine entirely. To use community BeLL again, we will have to rebuild a new machine from scratch using vagrant up.

**Comment by xyb994** [comment]
@rhuturajm The reasons highlighted paragraph in the screenshot is not incorporated together with the rest of bullet points are that:
- bullets points give a general review of these vagrant command.
- the paragraph emphasis on the most common commands we might need to interact with the community BeLL VM we created.

Let's see what other virtual interns think about this issue. @ManiBlitz @aakarnik could you comment on this?

**Comment by aakarnik** [comment]
@rhuturajm 
I agree with @xyb994 about keeping the sections separate.
But if you wanted to create a list out of the paragraph, give it a subtitle like "Commands used for BeLL VM" and break down the paragraph. It isn't absolutely necessary, but it is a proposed approach to go about it.

**Comment by sahilph** [comment]
Yes keeping them separate make more sense.

**Comment by ManiBlitz** [comment]
I also agree with @xyb994 concerning keeping the paragraph as it is. The emphasis proposed by the paragraph is proper to those two commands as they are the most used once the virtual machine is installed and Bell App is used.

**Comment by xyb994** [comment]
Thank you all for the input here. I'll close this issue.
