### ISSUE TITLE
Small change in vi-bellapps.md

### ISSUE THREAD

**Issue by aakarnik** [open-learning-exchange/open-learning-exchange.github.io#1741]
### Problem
This is a minor issue in vi-bellapps.md - http://open-learning-exchange.github.io/#!./pages/vi/vi-bellapps.md. 

The section explaining `Publication` and `Updates` tabs in the BeLL app is very crammed together. Between the explanation for `Updates` button and the note following the paragraph do not emphasize the `Publication` tab as needed.

### Steps to reproduce the problem
N/A 

### Screenshots
![issue 4](https://user-images.githubusercontent.com/37878201/38961176-543f7cec-4335-11e8-9b93-2f0e5f72e806.JPG)

### Proposed solution
 Just move the text around by placing the `Updates` button explanation and the note one after the another and a separate paragraph for Publication.

**Comment by xyb994** [comment]
@aakarnik There's an open PR #1692 addressing this issue, please take a look at https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/update-bell-apps-tutorial/#!pages/vi/vi-bellapps.md and let me know if you have further suggestions.

**Comment by aakarnik** [comment]
I think it looks good now. I would have moved the "Publications" step after the Blue Note box, but it isn't absolutely necessary. :+1:
