### ISSUE TITLE
Typo on vi-github-and-markdown.md

### ISSUE THREAD

**Issue by rhuturajm** [open-learning-exchange/open-learning-exchange.github.io#1745]
### Problem
There is a typo on vi-github-and-markdown.md under the heading Open a pull request. The typo is "Clink".

### Steps to reproduce the problem

N/A

### Screenshots

<img width="812" alt="unticsdvtled" src="https://user-images.githubusercontent.com/38227119/39007361-a6733e42-43d3-11e8-8c21-8c64d652225b.png">

### Proposed solution

Correct the typo!

**Comment by kylemathias** [comment]
Sure, go ahead.
