### ISSUE TITLE
Creating branches correctly while creating PRs

### ISSUE THREAD

**Issue by aakarnik** [open-learning-exchange/open-learning-exchange.github.io#1746]
### Problem
I noticed that it is a tendency to branch off of the working branch instead of the master branch while working on multiple pull requests at the same time on Step 8 of the new Interns steps. This includes more commits and changes than required when the files are pushed from the local repo to the remote.

### Steps to reproduce the problem
N/A

### Screenshots
N/A

To see what the issue was: https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1723#issuecomment-381381249

### Proposed solution

Add a note to the vi-github-issues.md about branching from the right branch and including steps similar to the this [comment](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1723#issuecomment-381381249) by @xyb994 explaining how to revert the changes.

**Comment by xyb994** [comment]
Yes, this is a common mistake VIs tend to make.

There's already a note at the end of [Create a New Branch](https://open-learning-exchange.github.io/#!pages/vi/vi-github-issues.md#Create_a_New_Branch) section.

It might help to clean up Create a New Branch section to emphasize `git checkout master` before `git checkout -b name_of_your_new_branch`.

**Comment by aakarnik** [comment]
Okay, I can do that. :+1:
