### ISSUE TITLE
Ambiguous language and dull tone in Step 0 translation section

### ISSUE THREAD

**Issue by gcantieni** [open-learning-exchange/open-learning-exchange.github.io#1755]
### Problem
The language at the end of the translating section of Step 0 is ambiguous as to what "get 10%" or "translate to 100%" means. Additionally, the tone of the section is very curt. For example, "feel free to translate to 100%" is hardly inspiring, instead we should be *thanking* people if they devote their valuable time to translation.

### Steps to reproduce the problem

N/A

### Screenshots

![step0_unclear_language](https://user-images.githubusercontent.com/34512397/39285631-95a519b4-48e7-11e8-9c2e-b89f455a3b62.png)

### Proposed solution

Make it clear what 10% and 100% mean--e.g. instead of  "get 10%", use instead "get 10% of the words on our website translated"

Additionally, make the tone of the section more excited to inspire people to translate instead of saying that they can "feel free" to do it.

**Comment by xyb994** [comment]
@gcantieni Go ahead and create a PR, please also consider fixing the issue mentioned in #1567
