### ISSUE TITLE
Tech genius current members has odd format

### ISSUE THREAD

**Issue by gcantieni** [open-learning-exchange/open-learning-exchange.github.io#1761]
### Problem
The tech geniuses section has *Active Tech Geniuses* list populated and *Tech Geniuses* list totally empty, which makes no logical sense: How could you have fewer all-time members than active members? 

Additionally, there's an odd and redundant arrow sign/label at the top of the *Active Tech Geniuses* list. There's no need to say that this is a tech geniuses list as it is under a huge heading that already says so.

### Steps to reproduce the problem

N/A

### Screenshots

![tech_geniuses](https://user-images.githubusercontent.com/34512397/39399502-c68ed64e-4aec-11e8-89c1-273d8504de77.png)

### Proposed solution

Add the active members to the all time members list,  and update the all time members list if appropriate. Also get rid of the weird arrow/label.

**Comment by xyb994** [comment]
@gcantieni 

Yes, you can go ahead and implement the proposed solution.

I don't have the full context on this. I believe when we started working with Madagascar last year, we asked people from there to go through our First steps to get familiar with BeLL. Tech geniuses started before that date did not have to go through First steps so they are not on the list.

**Comment by gcantieni** [comment]
@xyb994 
So do you think I should just add Madagascar and the other to the list, or is there someone who has a more complete list?

**Comment by xyb994** [comment]
@gcantieni 

I'd say start the PR first, if we get more info on this you can still fix it before merging.
