### ISSUE TITLE
Link cannot found on BeLL tutorial of step 2 and step 10

### ISSUE THREAD

**Issue by doonnoop** [open-learning-exchange/open-learning-exchange.github.io#1765]
### Problem
* On step 2, if I click the link, it shows the page not exists.
* And the same thing happen to step 10
* In some steps, the radio buttons are not in the same line with the content. The content are a little higher than radio button. See screenshots.

### Steps to reproduce the problem

N/A

### Screenshots

![step2](https://i.imgur.com/0kyNXot.png)
![step10](https://i.imgur.com/iU8YjKv.png)
![radio](https://i.imgur.com/z39XOhS.png)

### Proposed solution

To add css style for the radio and the content
> \<style="vertical-align:middle;">

before adding the style:
![before](https://i.imgur.com/r4acxK1.png)
after adding the style:
![after](https://i.imgur.com/fEfgjmb.png)

**Comment by xyb994** [comment]
@dongpeng92 Thanks for raising the issue. I went into the course and fixes the links you mentioned.

Please note that BeLL is on feature freeze and we are rewriting it in Angular at [planet repo](https://github.com/open-learning-exchange/planet/). We look forward having you join the Angular and/or Systems team :)
