### ISSUE TITLE
Update Create an Issue Section

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/open-learning-exchange.github.io#1772]
### Problem
Under http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md the issue description is not correct to how the new issue tab is created. we should update the image and description to refelct our auto-generated template.

### Screenshots
![image](https://user-images.githubusercontent.com/26488295/39716293-d085ba42-51e4-11e8-96d6-296e9fbe3b91.png)

### Proposed solution
Add this image as an update to the section and change the wording to more accurately reflect the process of creating an issue.
![image](https://user-images.githubusercontent.com/26488295/39716424-2e213d66-51e5-11e8-9e2b-c7877288a701.png)

**Comment by NirmalKumarJoshi** [comment]
@kylemathias  I would like to work on it. Can I proceed?

**Comment by kylemathias** [comment]
sure, go ahead 👍
