### ISSUE TITLE
update take-home link on techgenius/tg-tablet-config.md

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#1773]
### Problem
In http://open-learning-exchange.github.io/#!pages/techgenius/tg-tablet-config.md
the take-home link should point to https://github.com/open-learning-exchange/take-home/releases

### Proposed solution

use https://github.com/open-learning-exchange/take-home/releases/latest instead

**Comment by NirmalKumarJoshi** [comment]
@dogi  Can I take over this issue?

**Comment by kylemathias** [comment]
sure, go ahead
