### ISSUE TITLE
No link to Vagrant website in tg-install.md file

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [open-learning-exchange/open-learning-exchange.github.io#1781]
### Problem
There is no link to [Vagrant Website ](https://www.vagrantup.com/) in the install guide.

### Steps to reproduce the problem

N/A

### Proposed solution

The link can be added to the **Vagrant** heading in step-3 tg-install.md and can be redirected to https://www.vagrantup.com/

**Comment by NirmalKumarJoshi** [comment]
Working on it.

**Comment by xyb994** [comment]
@NirmalKumarJoshi Were you referring to https://open-learning-exchange.github.io/#!pages/techgenius/tg-install.md this page? Vagrant would already be installed in its "Step 1 - Prerequisites".

**Comment by demuze28** [comment]
I think it would make more sense to post a link to https://www.vagrantup.com/ at the bottom of this page (https://open-learning-exchange.github.io/#!pages/techgenius/tg-install.md) under a new heading called 'Helpful Resources'. Just a thought.

**Comment by singharpita** [comment]
can use the "vagrant" keyword as link (to the vagrant site) to maintain uniformity throughout the page.

**Comment by demuze28** [comment]
Okay will do.
