### ISSUE TITLE
githubissues.md: word choice

### ISSUE THREAD

**Issue by sthak004** [open-learning-exchange/open-learning-exchange.github.io#179]
This issue stems from my own confusion when I was reading the page.

First the half of the page describes what an issue is and how one can create one in a GitHub repository. In the second half,  when we are given the task, the sentence 
> "On your own fork of the correct repository, **go and make the proposed changes** and commit them once you have finished."

is a bit ambiguous. The reason I say this is because at the time, I was inclined to think we had to make those exact changes shown to us in the example, in our forked repository when we actually had to just find a small mistake and fix it.

---
My suggestion would be to alter the part of the sentence to say 
>"On your own fork of the correct repository, go and make **a proposed change** and commit it once you have finished."

since that is the task.

I understand that I could have misinterpreted the wording however, I believe this might have been (or is) an issue for a few students. Before I submit a fix, I believe it's better to wait and see whether this a reasonable issue.

**Comment by dogi** [comment]
@sthak004 :)

you have a point here

my only problem is that people then would always go for minimal effort and do just one ...
when want them to show me that they feel comfortable in using git, github, github issues and markdown

if you can add that tweak ;)

this will be an awesome change

**Comment by sthak004** [comment]
@dogi Sorry for the delay in the reply. I see your point here.

How about I make the proposed change I mentioned in my previous post and add this tweak:

After the last sentence

> "After this, a staff member will accept the pull request and will normally close the issue. You can see the process here."

We add this

#### NOTE:

> **This is an exercise to help familiarize yourself with GitHub issues, committing, and creating pull requests. This is a common process in large open source projects as there is always room for improvement. So, we strongly encourage you to follow this process and continue to post issues and resolve them.**

**Comment by sthak004** [comment]
@dogi I have sent a pull request regarding this issue. https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/207
Let me know what you think.
