### ISSUE TITLE
Description is not precise on "Course Credits" page.

### ISSUE THREAD

**Issue by RichardHty** [open-learning-exchange/open-learning-exchange.github.io#1792]
### Problem

Description is not precise on "Course Credits" page. 
In "Virtual Intern" course, after I submit a text answer, I can use "submission" button on dashboard to see my submissions. And it will take me to "Course Credits" page where I can find "Grade" button under "Action" column. But when I click it, it takes me to the page displaying detailed information about my submitted answer, rather than let me grade it or actually show the grade.

### Steps to reproduce the problem

Submit an answer and click submission button on dashboard. Then click "Grade" button on "Course Credits" page. It will take you to your answer.

### Screenshots

<img width="1191" alt="screen shot 2018-05-10 at 11 53 34 pm" src="https://user-images.githubusercontent.com/32426247/39906139-d5ff282e-54ae-11e8-86d8-3ec135bd28ab.png">
<img width="1242" alt="screen shot 2018-05-11 at 12 01 57 am" src="https://user-images.githubusercontent.com/32426247/39906143-d97ef61e-54ae-11e8-93dc-40b8657e1744.png">

### Proposed solution

- If we don't have permission to grade this answer, the text of these buttons should be changed from "Grade" to "View Your Answer" or "View Key".
- If we want the user to use these buttons to actually grade these answers, we should link the button to another page that allows user to grade.

**Comment by xyb994** [comment]
@RichardHty Thank you for bringing up the issue, this is out of scope of this repo and please note that bell is on feature freeze.

**Comment by xyb994** [comment]
@RichardHty 
I'm closing this issues so other VIs don't get confused about what issue to create for first steps. I do agree with you that some UI are confusing in bell. I'll watch this type of issues closely and provide feedback to the [planet](https://github.com/open-learning-exchange/planet) team, you are welcome to provide feedback about planet as well.
