### ISSUE TITLE
After "Configurations" viewed/changed, the page should be able to go back to the previous menu 

### ISSUE THREAD

**Issue by RichardHty** [open-learning-exchange/open-learning-exchange.github.io#1793]
### Problem

After "Configurations" viewed/changed, the page should be redirected to the previous menu 

### Steps to reproduce the problem

In dashboard, click "manager" next to your name. Click "Configurations". Scroll down to the bottom, there is only one button called "Register". Click that button the page stays there with no other button to take you to previous menu.

### Screenshots

<img width="985" alt="screen shot 2018-05-11 at 12 39 48 am" src="https://user-images.githubusercontent.com/32426247/39907072-6030eac8-54b4-11e8-916c-f6dd6caed81c.png">

### Proposed solution
- After the "Register" button call is finished, the page should be redirected to previous menu or dashboard automatically.
- Or add another button to make user jump to the previous menu.

**Comment by xyb994** [comment]
@RichardHty Thank you for bringing up the issue, this is out of scope of this repo and please note that bell is on feature freeze.

**Comment by xyb994** [comment]
@RichardHty I'm closing this issues so other VIs does not get confused about what issue to create for first steps. I do agree with you that navigating around bell could be hard sometimes, especially not able to go back to previous menu. Please watch closely how our rewrite [planet](https://github.com/open-learning-exchange/planet) goes, I'll watch out for this issue as well.
