### ISSUE TITLE
note Planet VM will take about 10 mins

### ISSUE THREAD

**Issue by RichardHty** [open-learning-exchange/open-learning-exchange.github.io#1794]
### Problem
Planet VM setting up using "Vagrant up" command get stuck for about 10 minutes(as is shown in the seond screenshot) and will cost large amount of memory.

### Steps to reproduce the problem
On macOS High Sierra, version 10.13.4, using "Vagrant up" command under planet/ 

### Screenshots

<img width="1280" alt="screen shot 2018-05-11 at 1 17 14 am" src="https://user-images.githubusercontent.com/32426247/39907952-c3feb4a4-54b9-11e8-8111-5c08d4fd4a11.png">
<img width="1280" alt="screen shot 2018-05-11 at 1 17 37 am" src="https://user-images.githubusercontent.com/32426247/39907953-c40cfaaa-54b9-11e8-96d6-4ced408d7f01.png">

### Proposed solution
N/A

**Comment by xyb994** [comment]
It does take some time to install node packages, can you do `vagrant destroy` then `vagrant up` again?

**Comment by RichardHty** [comment]
Yes, in my computer it stuck there and took almost 10 minutes to finish.

**Comment by xyb994** [comment]
We will note that it will take about 10 mins to finish using `vagrant up`.

**Comment by Emiton** [comment]
@RichardHty I also experience this when first booting up a VM using ```vagrant up```. It seems that this is normal, as the system must be provisioned before it is ready for use. @xyb994 can this issue be closed? It seems as if this is just a normal part of the setup process.
