### ISSUE TITLE
Planet: There was an error creating planet 

### ISSUE THREAD

**Issue by RichardHty** [open-learning-exchange/open-learning-exchange.github.io#1795]
### Problem
Planet: There was an error creating planet. When I tried to register it gives me an error saying that I'm not a server admin.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="1280" alt="screen shot 2018-05-11 at 1 28 40 am" src="https://user-images.githubusercontent.com/32426247/39908415-ffff7932-54bb-11e8-97d0-1fa83f45bed6.png">
<img width="1280" alt="screen shot 2018-05-11 at 1 35 58 am" src="https://user-images.githubusercontent.com/32426247/39908419-02e861c2-54bc-11e8-870a-52c9da959af3.png">

### Proposed solution
N/A

**Comment by xyb994** [comment]
This is not really the right place for this issue, but thanks for reporting it. I was having the same issue a few weeks ago.

**Comment by cquarte1** [comment]
You need to speak to @lmmrssa to fix that issue.
