### ISSUE TITLE
Regarding Compare & Pull request after mentioning a new issue

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1803]
### Problem
If we just create a new issue and following the steps I understood that we have to make an issue in the master but it was not clear that we have to make an issue locally first and then push it in the master.

### Steps to reproduce the problem

Just follow the GitHub Issue step 6 from First step.
### Proposed solution

N/A

**Comment by akshayuncc** [comment]
The proposed solution should be to mention to follow the steps in the diagram or to mention to make the changes in local issue then push that issue in the master.

**Comment by xyb994** [comment]
Is this related to https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1801? Could you clarify the issue?
