### ISSUE TITLE
The "List of Relevant Repositories & Links" on the left side bar has the same effect as "Brief Rundown of Treehouse-Builder" 

### ISSUE THREAD

**Issue by RichardHty** [open-learning-exchange/open-learning-exchange.github.io#1805]
### Problem
The "List of Relevant Repositories & Links" on the left side bar has the same effect as "Brief Rundown of Treehouse-Builder" .

### Steps to reproduce the problem

In "Contributors" drop down, open "Raspberry Pi", click "List of Relevant Repositories & Links" has the same effect as click "Brief Rundown of Treehouse-Builder".

### Screenshots

<img width="748" alt="screen shot 2018-05-16 at 2 43 46 pm" src="https://user-images.githubusercontent.com/32426247/40137092-a04d0daa-5917-11e8-8635-699cc4648f8e.png">
<img width="794" alt="screen shot 2018-05-16 at 2 44 38 pm" src="https://user-images.githubusercontent.com/32426247/40137124-aed8e312-5917-11e8-90ce-8bd4b94f2fed.png">

### Proposed solution

fix the link of the button.

**Comment by RichardHty** [comment]
When I'm testing, I can see the `class="active"`. And this question does not happen. 
<img width="908" alt="screen shot 2018-05-16 at 4 36 06 pm" src="https://user-images.githubusercontent.com/32426247/40142737-8346f2ba-5927-11e8-8dc4-2c7b1d57a2c2.png">

**Comment by xyb994** [comment]
@RichardHty Oh I see, so it behaves a bit differently in Chrome and Firefox.

**Comment by xyb994** [comment]
What I described was in Chrome. So it looks like `class="active"` would only be added when the subheading requires page scrolling.

**Comment by xyb994** [comment]
Closing this as it is a MDwiki problem.
