### ISSUE TITLE
Router Configuration Page url is misleading

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/open-learning-exchange.github.io#1809]
### Problem
In the Router Configuration section under Tech  Geniuses section,  the link http://tplinklogin.net is specific to TP-Link Routers.

### Steps to reproduce the problem
On the OLe markdown wiki page ,  click on Techgeniuses in the navigation bar and select Router/Lan Configuration . Click on the link    http://tplinklogin.net  under "Router Configuration | Assigning a Dedicated IP address to the Community" section. 

### Screenshots
![screenshot 17](https://user-images.githubusercontent.com/39105848/40320360-71abc4b0-5cf9-11e8-8629-05de06fbdf0e.png)
![screenshot 16](https://user-images.githubusercontent.com/39105848/40320373-7b238352-5cf9-11e8-81e4-4b29b2464571.png)

### Proposed solution
Do one of the following:
1. Remove the Router specific link.
2. Clarify that link only applies to TP-Link routers.

**Comment by xyb994** [comment]
@sjkadali The original text already said "or" but it could be a bit clearer. Go ahead and create a PR for this. Please go with solution 2 because if we are sending out routers, it would mostly likely to be TP-Link brand.

**Comment by sjkadali** [comment]
@xyb994 thanks. Will go with solution2.
