### ISSUE TITLE
Invalid URL in the "Tech Geniuses" introduction page

### ISSUE THREAD

**Issue by onlyserenity** [open-learning-exchange/open-learning-exchange.github.io#1811]
### Problem
The hyperlink leads to HTTP 404, or page not found. I've searched that chat room in Gitter but didn't find it. It's either it no longer exists or the url for it has changed, either way it needs to be adjusted according to the reason.

### Steps to reproduce the problem
Click on the "Tech Genius Gitter chatroom" text to replicate the issue.

### Screenshots
![issue](https://user-images.githubusercontent.com/19535323/40337736-401a1514-5d3f-11e8-876c-a62ce5a122eb.png)

It redirects you to this below:
![issue2](https://user-images.githubusercontent.com/19535323/40337870-05e84cc0-5d40-11e8-94ca-c610d381380b.png)

### Proposed solution
Fix the href if the chat room still exists.

**Comment by xyb994** [comment]
@onlyserenity Thank you for raising the issue. The chat room is invite-only, feel free to create a PR and edit that sentence to indicate it's invite only.

**Comment by onlyserenity** [comment]
@xyb994 Working on it
