### ISSUE TITLE
Make Sure User Includes Configurations Screenshot!

### ISSUE THREAD

**Issue by yvaishnavi** [open-learning-exchange/open-learning-exchange.github.io#1812]
### Steps to reproduce the problem

It happened to me and I was very confused for awhile and accidentally ended up deleting my account. I want to make sure this doesn't happen to anyone else that joins.
### Screenshots

N/A

### Proposed solution

- Add on the Introductions/First Step page under step 1: "Do not forget to take a screenshot of the Configuration Page!" 
- Also add on the Bell Installation page (Step 1), "In case you forgot to take the screen shot of your configurations, go to the dashboard, click on manager, click on the configurations tab, take a screen shot of the page, and send it to the Gitter chat". It says that in Step 4 but that is several steps away and a long time for potential users to be left confused like myself. I think it would be more helpful to the user if we added this clarification under this step (1, Bell Installation), along with under step 4.

**Comment by xyb994** [comment]
@yvaishnavi 

In step 4, could you move the paragraph about screenshot to preparation section? We as potential VIs to post a screenshot in Gitter so we know which step they are at.

In BeLL Configurations, I think it would help if we emphasis (bold the text) taking screenshot before the example configuration image.

**Comment by yvaishnavi** [comment]
Yes I will!

**Comment by yvaishnavi** [comment]
@xyb994 do you mean to bold the text after the example configuration page, instead before? I highlighted the text in the screenshot I have attached. Or do you mean move the text before the configuration page, and then bold it?
![bell screenshot](https://user-images.githubusercontent.com/32888918/40414286-af2e5c9c-5e2c-11e8-9f02-e22dff1847b3.JPG)

**Comment by xyb994** [comment]
Sorry about the confusion. I meat move the highlighted text above example configuration image and bold part of the text.
