### ISSUE TITLE
What to do if you accidentally delete your BeLL Account

### ISSUE THREAD

**Issue by yvaishnavi** [open-learning-exchange/open-learning-exchange.github.io#1813]
### Steps to reproduce the problem

Accidentally deleting the account and then recreating it will cause this problem. 

### Screenshots

learner account V.S. manager account
![learner account](https://user-images.githubusercontent.com/32888918/40354529-e7cc9b82-5d68-11e8-8ea9-dd758e4d979e.JPG)
![manager account](https://user-images.githubusercontent.com/32888918/40354537-ea2d36fc-5d68-11e8-82f9-da633f8d9ab5.JPG)

### Proposed solution

The best way is to solve this issue is to start over and create a new community. Use the following git commands.
-  Make sure you are in the right directory, you should be in the ole--vagrant-vi folder
- Use the command: vagrant destroy 
- Then use: vagrant up
I would add this in a troubleshooting section under BeLL Installation

**Comment by xyb994** [comment]
@yvaishnavi 

Sure, go ahead and create a PR. Make sure it's short and simple. Can we add it to https://open-learning-exchange.github.io/#!./pages/vi/vi-configurations.md?  as admin account is not created until this step.
