### ISSUE TITLE
Grammer problems on intern-orientation page.

### ISSUE THREAD

**Issue by jiajunc** [open-learning-exchange/open-learning-exchange.github.io#1819]
### Problem
Several grammer problems on page http://open-learning-exchange.github.io/#!pages/robots/rbts-intern-orientation.md

### Steps to reproduce the problem

N/A

### Screenshots

<img width="722" alt="screen shot 2018-05-22 at 3 35 38 pm" src="https://user-images.githubusercontent.com/31739437/40388741-e8f420f8-5dd5-11e8-9570-0c2fd862d8a1.png">
'an virtual intern' --> 'a virtual intern'
<img width="756" alt="screen shot 2018-05-22 at 3 34 37 pm" src="https://user-images.githubusercontent.com/31739437/40388779-07aa4c70-5dd6-11e8-8246-15cc46055854.png">
'3 month' --> '3 months'
<img width="734" alt="screen shot 2018-05-22 at 3 34 54 pm" src="https://user-images.githubusercontent.com/31739437/40388803-185780a6-5dd6-11e8-8906-8626f6d67c28.png">
'be place' --> 'be placed'

### Proposed solution

Solutions have been written under the images above.

**Comment by xyb994** [comment]
Good catch, go ahead and create a PR.
