### ISSUE TITLE
Potentially Elaborate on the Summary Section of the First Steps Page

### ISSUE THREAD

**Issue by yvaishnavi** [open-learning-exchange/open-learning-exchange.github.io#1831]
### Steps to reproduce the problem

(N/A)

### Screenshots

![summary of gitter chat](https://user-images.githubusercontent.com/32888918/40403692-588d0d6c-5e08-11e8-93da-dc8ea1668ba5.JPG)
The area I have highlighted in yellow is where I would place the information.

### Proposed solution

Under the area I have indicated in yellow I would add:
"You should also have sent the following in the gitter chat:
- Screenshot of your BeLL Configuration Page (Step 1)
- Links to your github.io and your personal .md page, as well as your pull request (Step 3)
- Screenshot of Planet after installing it and logging in (Step 4)
- A link for every issue you create (Steps 6 and 8)
- A link for every comment you make on someone else's issue (Steps 6 and 8)
- A link for every pull request for others to review and approve (Steps 3, 6, and 8)
- Indication that you have completed Step 8
- Any questions or concerns you have!"

**Comment by xyb994** [comment]
The main purpose we ask VIs to post links/screenshots is to keep us informed of their progress. It won't work if we put it at the end of the page.

What do you think about highlighting `We also want you to keep us updated a relatively good amount in the Gitter chat as you complete these steps` in https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md?

**Comment by yvaishnavi** [comment]
@xyb994 Yes sure I can do that! On another hand what do you think about adding this information at the top of the page (https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) just below the sentence you just indicated? If you do not prefer this I can always just highlight the sentence like you said.

**Comment by yvaishnavi** [comment]
@xyb994 Yes okay I will do so! Would like me to highlight it as well like you said before?

**Comment by xyb994** [comment]
@yvaishnavi Whatever you think it looks right :) But please fix your fork's master branch first.
