### ISSUE TITLE
Planet Manual Page Note section missing "You"

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1843]
### Problem
It is " We recommend that talk to OLE technical".

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40463584-0e144f02-5ee4-11e8-8eba-88a2351e2e34.png)

### Proposed solution

It should be " We recommend that you talk with an OLE technical" or  "We recommend that talk to an OLE technical"

**Comment by xyb994** [comment]
Good catch, go ahead and create a PR.

**Comment by xyb994** [comment]
This is actually in tg-hardware-setup.md well. Could you fix this issue together with https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1842 in one PR?

**Comment by akshayuncc** [comment]
Ok, But i was hoping if I could do it separately then I would have two PR's and complete my first step.
