### ISSUE TITLE
Dead Link on "Configuring Router/Network for Planet" page and Grammer problem

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1844]
### Problem
1. Link "http://tplinklogin.net" is a dead link.  
2.It is "On a laptop open a web browser". 

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40465171-5f2852f4-5eed-11e8-90cf-76b5faa484ef.png)

![image](https://user-images.githubusercontent.com/25532941/40465052-bc7d6896-5eec-11e8-9251-9c508903fcfe.png)

### Proposed solution

For number 2. It should be "Open a web browser and type... ".

**Comment by xyb994** [comment]
Problem 1 would be fixed once https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1822/files is merged.

Go ahead and create a PR for problem 2.
