### ISSUE TITLE
Grammar Issues On the Take Home App Page

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/open-learning-exchange.github.io#1845]
### Problem
1. Under the **Android Device Setup** section , in the first sentence  the word *actually* has wrong usage.. Second sentence also has the same wrong usage.
2. In the second sentence of the same section, *getting* has wrong usage.
3. Under the **Take Home Documentation** section,  in the second sentence the words *with, in* has wrong usage.

### Steps to reproduce the problem

On the OLe markdown wiki page , click on **Contributors** in the navigation bar and select **Take Home**. First two problems can be found under the **Android Device Setup** section and third problem under **Take Home Documentation** section.

### Screenshots

![screenshot 19](https://user-images.githubusercontent.com/39105848/40487606-b755efbe-5f32-11e8-9dd4-a72c5f2a6974.png)

### Proposed solution

1. For problem 1, the word *actually* can be changed to *actual*.
2. For second problem, the word *getting* can be changed to *get*.
3. For third problem, the words *with, in* can be replaced by *within*.

**Comment by xyb994** [comment]
Good catch, go ahead a create a PR for this.

**Comment by sjkadali** [comment]
@xyb994 sure,, will do that.
