### ISSUE TITLE
Incorrect/dead links on the "GitHub and Markdown" page

### ISSUE THREAD

**Issue by onlyserenity** [open-learning-exchange/open-learning-exchange.github.io#1851]
### Problem
The steps in the "Start Here" section of the page redirects the user to url that are either dead or incorrect.

### Steps to reproduce the problem

1. Go to [Here](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md)
2. Scroll down to "Start Here" section
3. Click on each steps to reproduce the problem

### Screenshots

![issue6](https://user-images.githubusercontent.com/19535323/40503042-c31d6be2-5f5a-11e8-8f18-e8efac003cfe.png)

### Proposed solution

Redirect the user to the correct links. For example, the first one "Login to GitHub with your username and password" send the user to www.github.com etc...

**Comment by xyb994** [comment]
These links are meant to be the sub-directory of `## Start Here`. They worked well for me on Chrome, Firefox, and Safari, which browser are you using?

**Comment by onlyserenity** [comment]
@xyb994 Never mind. I tried it now on Chrome it worked. Sorry
