### ISSUE TITLE
Wrong Usage Of the Word *listed* on Tech Geniuses User Manual Page.

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/open-learning-exchange.github.io#1852]
### Problem
On the Tech Geniuses Admin user manual page,  the word *listed* is  redundant.

### Steps to reproduce the problem

On the OLe markdown wiki page , click on **Tech Geniuses** in the navigation bar and select **Admin User Manual**. Under the  **What is the Library** section.,  it says **Resources are listed alphabetized**.

### Screenshots

![screenshot 21](https://user-images.githubusercontent.com/39105848/40503644-c418a24e-5f5c-11e8-9221-2ccfb36300fc.png)

### Proposed solution

It can either be changed to **Resources are listed alphabetically** or **Resources are alphabetized**

**Comment by xyb994** [comment]
Go ahead and create a PR for this.

**Comment by sjkadali** [comment]
@xyb994 sure, will do.
