### ISSUE TITLE
Remove unnecessary punctuation marks 

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1855]
### Problem
There is an unnecessary punctuation mark on Open Learning Exchange page at "At the core of Planet is a repository of free, open access, and".

### Steps to reproduce the problem

Go to page Open Learning Exchange you can find it under What is the OLE Planet Learning System (Planet)? description. (Second paragraph).

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40512786-dfb9d7a6-5f71-11e8-9cc1-93dca7ca9e50.png)

### Proposed solution

Remove the punctuation mark.

**Comment by xyb994** [comment]
I don't see anything wrong with this sentence. 

> At the core of Planet is a repository of *free, open access, and public domain resources* designed to ...

**Comment by akshayuncc** [comment]
@xyb994 Should it not be "At the core of Planet is a repository of free, open access and public domain resources designed to " instead of "At the core of Planet is a repository of free, open access, and public domain resources designed to ". I think there should not be a "," after "open access" and an "and". If you need a "," then why do we need an "and" there?.
If you think if I am incorrect then I will find a new issue.
Thank you.

**Comment by xyb994** [comment]
@akshayuncc Found an article about it https://www.grammarly.com/blog/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/ 

Please create another issue.

**Comment by akshayuncc** [comment]
ok thank you
