### ISSUE TITLE
Deadlink on GitHub Issues under "Preview Changes Locally" 

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1857]
### Problem
There is a link under "Preview Changes Locally" which takes you to how to view changes locally FAQ's.
At the bottom of the page you will find "[www.notesync.org]: http://www.notesync.org/" this is a deadlink.

### Steps to reproduce the problem

Goto github issues page you will find this redirecting link under "Preview Changes Locally". If you click on "how to view changes locally" you will find "[www.notesync.org]: http://www.notesync.org/" at the bottom of the page.

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40516830-7fdbc7ea-5f80-11e8-8212-02f352b2a329.png)

![image](https://user-images.githubusercontent.com/25532941/40516836-86ca7c54-5f80-11e8-83f1-e4e97059479b.png)

### Proposed solution

N/A

**Comment by akshayuncc** [comment]
@xyb994  If accepted then I can provide a solution.
Thank you.

**Comment by xyb994** [comment]
@akshayuncc Please note that the dead link you found is not even on our repo...

**Comment by akshayuncc** [comment]
Yes, hence I mentioned "if accepted". We could raise an issue for them. :)

**Comment by xyb994** [comment]
Oh, sorry I didn't understand what you mean by "if accepted".

It's up to you if you want to create an issue there. You'll get an extra green dot on your GitHub contribution graph ;)
