### ISSUE TITLE
Grammer issue on page "tg-teamviewer-install.md" 

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1858]
### Problem
It is "OLE may ask your to install ".

### Steps to reproduce the problem

Goto page "tg-teamviewer-install.md"

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40517286-7a6ebc70-5f82-11e8-8fdf-e7df2e760e5a.png)

### Proposed solution

It should be "OLE may ask you to install".

**Comment by xyb994** [comment]
Good catch, go ahead and create a PR.

**Comment by akshayuncc** [comment]
Sure @xyb994 , thank you :).
