### ISSUE TITLE
"FAQ" page: Fourth way to deploy OLE on GitHub

### ISSUE THREAD

**Issue by onlyserenity** [open-learning-exchange/open-learning-exchange.github.io#1860]
### Problem
I found a new way to set up the forked repo if someone already have Username.github.io used. Because I host my personal portfolio on Username.github.io, I had to find another way to deploy the forked repo. This way can be done using GitHub Pages. Basically you can deploy the forked repo in this manner: https://onlyserenity.github.io/onlyserenity-ole.github.io/

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Add a forth suggestion on page "FAQ" under Q16 _What do I do if I already have a github.io with my username?_

"4. If you are still using it and you don't want to overwrite it, you can go to the forked repository settings rename the repository to `YourUsername-ole.github.io` then deploy it to GitHub Pages by selecting "master branch" under the GitHub Pages settings. By doing that, you can access the forked OLE repository with this link https://_YourUsername_.github.io/onlyserenity-ole.github.io/"

I can add screen shots to assist with this mini-guide

**Comment by xyb994** [comment]
@onlyserenity Great, go ahead a create a PR for this. Actually move your solution to item 1 since it's the best. Please also remove the third solution since that one requires will make things more complicated. Please don't add screenshot unless it's absolutely necessary.
