### ISSUE TITLE
Found Several Grammar mistakes on Virtual intern orientation page.

### ISSUE THREAD

**Issue by nikskushwah** [open-learning-exchange/open-learning-exchange.github.io#1869]
### Problem

Several grammar problem on http://open-learning-exchange.github.io/#!pages/robots/rbts-intern-orientation.md

### Steps to reproduce the problem
N/A

### Screenshots

Including screenshots with solutions:-

1) 
![1](https://user-images.githubusercontent.com/6128590/40600368-bf34fa68-6216-11e8-95b9-bb7e304c680c.jpeg)

solution - is opportunity --> is an opportunity

2) 

![2](https://user-images.githubusercontent.com/6128590/40600404-e8785168-6216-11e8-8b59-a31704eb0c81.jpeg)

solution - at early --> at an early

3)

![3](https://user-images.githubusercontent.com/6128590/40600497-425ec37e-6217-11e8-8c01-995f0baa6193.jpeg)

solution - as public --> as the public

4) 

![4](https://user-images.githubusercontent.com/6128590/40600581-9991d56e-6217-11e8-960f-eeb816eaec3b.jpeg) 

solution - add keyword --> add a keyword

### Proposed solution

Solution written under screenshots

**Comment by xyb994** [comment]
Looks good, go ahead and create a PR. For item 3, can we change it to `as a public member`?

**Comment by nikskushwah** [comment]
Then maybe we can change the whole line to " mark yourself as a public member in the list of OLE contributors" ??
