### ISSUE TITLE
githubandmarkdown.md: reference to old ll_CC structure

### ISSUE THREAD

**Issue by Hulmani** [open-learning-exchange/open-learning-exchange.github.io#187]
on the GitHub and MarkDown page page ( http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md )  it is mentioned to open II_CC folder in the pages folder, 

there is no II_CC folder

**Comment by dogi** [comment]
@Hulmani please fix this

**Comment by sente** [comment]
@Hulmani, I would simply remove the `Create a New Wiki` and `Getting Started` sections.

**Comment by Hulmani** [comment]
@sente I don't understand.

**Comment by dogi** [comment]
@hulmani wonder if you can suggest and improvement

**Comment by Hulmani** [comment]
@dogi I fixed it and requested a pull, now its been fixed!

**Comment by DrewPerlman** [comment]
[This commit](https://github.com/open-learning-exchange/open-learning-exchange.github.io/commit/dfdf8adebcc1f57a1306c2cfdea8a171726bdb5f) fixed this issue
