### ISSUE TITLE
Simple dev install page grammar problems

### ISSUE THREAD

**Issue by nikskushwah** [open-learning-exchange/open-learning-exchange.github.io#1870]
### Problem

There are few grammar problems on simple dev install page http://open-learning-exchange.github.io/#!pages/robots/rbts-simple-install.md

### Steps to reproduce the problem

N/A

### Screenshots

Solutions for each grammar mistake included with the screenshot.

1)
![untitled 2](https://user-images.githubusercontent.com/6128590/40602437-1b0fab42-621e-11e8-9560-ca42d168d791.jpeg)

execute --> executes

2)
![2](https://user-images.githubusercontent.com/6128590/40602460-3d0fe568-621e-11e8-84db-10985130c07c.jpeg)

any --> an

3)
![3](https://user-images.githubusercontent.com/6128590/40603096-84ac44dc-6220-11e8-9515-393b431ff6c6.jpeg)

overall --> the overall

4) 
![4_new](https://user-images.githubusercontent.com/6128590/40603186-ddbdc848-6220-11e8-94b6-a3448b1d176e.jpeg)

project --> the project

5)
![5](https://user-images.githubusercontent.com/6128590/40603220-f73fba24-6220-11e8-9e25-76df441bb304.jpeg)

executable --> an executable

### Proposed solution

Solution written under screenshots

**Comment by xyb994** [comment]
Looks good, go ahead and create a PR. Please also update punctuation and fix spaces as needed.

**Comment by nikskushwah** [comment]
Its fixed, Kindly review at https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1873
