### ISSUE TITLE
Spelling mistakes on Virtual interns Page

### ISSUE THREAD

**Issue by nikskushwah** [open-learning-exchange/open-learning-exchange.github.io#1871]
### Problem

Few spelling mistakes on the virtual intern page http://open-learning-exchange.github.io/#!pages/vi/vi-faq.md

### Steps to reproduce the problem

N/A

### Screenshots

1)
![1](https://user-images.githubusercontent.com/6128590/40606007-9c69e3e6-6229-11e8-98c2-8d7d1478fbcb.jpeg)

repostiroy --> repository

2)
![2](https://user-images.githubusercontent.com/6128590/40606026-b67cb812-6229-11e8-810c-0dc11e9df559.jpeg)

fodler --> folder

### Proposed solution

Solutions are written under screenshots

**Comment by xyb994** [comment]
Go ahead and create a PR
