### ISSUE TITLE
Virtual Intern First Step Page Grammar and Punctuation Mistakes

### ISSUE THREAD

**Issue by nikskushwah** [open-learning-exchange/open-learning-exchange.github.io#1875]
### Problem

There are several grammar and punctuation mistakes in the virtual intern first step page.
http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md

### Steps to reproduce the problem

N/A

### Screenshots

1)
![1](https://user-images.githubusercontent.com/6128590/40630127-90c74d82-6295-11e8-974f-bcc2a0b92ac6.jpeg)

at --> in

2)
![2](https://user-images.githubusercontent.com/6128590/40630131-a3173c90-6295-11e8-976d-07b4c20c09b0.jpeg)

in --> for

3)
![3](https://user-images.githubusercontent.com/6128590/40630145-b91b10ac-6295-11e8-9a0f-0fe3a5a9aa45.jpeg)

in --> on

4)
![4](https://user-images.githubusercontent.com/6128590/40630150-c641f7be-6295-11e8-889b-b4b7e86db663.jpeg)

on --> with

5)
![5](https://user-images.githubusercontent.com/6128590/40630156-d13d1d6a-6295-11e8-8a05-f74dfeec2302.jpeg)

time --> the time

6)
![6](https://user-images.githubusercontent.com/6128590/40630220-672f016c-6296-11e8-83eb-6e60d5cad302.jpeg)

Github --> Github,

7)
![7](https://user-images.githubusercontent.com/6128590/40630232-7ba4f002-6296-11e8-9aff-1623d94a4168.jpeg)

Also --> Also,

8)
![8](https://user-images.githubusercontent.com/6128590/40630238-86f0bbda-6296-11e8-963c-dcd9cf10d1a3.jpeg)

out, --> out

9) 
![9](https://user-images.githubusercontent.com/6128590/40630245-9b3662d4-6296-11e8-8e6c-21967f18ee9a.jpeg)

tradition, --> tradition

10)
![10](https://user-images.githubusercontent.com/6128590/40630250-a82d2194-6296-11e8-9655-aa49e1d3f278.jpeg)

requests, --> requests

### Proposed solution

Solution Available under screenshots

**Comment by xyb994** [comment]
Can we use "about" for item 4?
I dont't see any issue in screenshot with item 8, 10.

**Comment by nikskushwah** [comment]
Yeah we can. Will use about in item 4. Item8, 10 had punctuation mistake just needed to leave some space. That's it.

**Comment by xyb994** [comment]
Sounds fine to me, ahead and make a PR.
