### ISSUE TITLE
Understanding the Nation and Community

### ISSUE THREAD

**Issue by Hulmani** [open-learning-exchange/open-learning-exchange.github.io#188]
### Your Side

1) When you are done with instructions on the BeLL-Apps page, you have a local copy of the software.
2) Here you create `your community`. This community essentially will have `your name`
3) There will be members in your community, you can think as you are the community head.
### Remote Side

1) `Nation Side` is a group of `communities`.
2) As soon as you create `your community` Emily or Dogi add `your community`  in the list of communities which essentially form the `Nation`

Periodically you must sync `your community` as the Manager with the `Nation`

**Comment by aberdean** [comment]
This is interesting. We probably should add some more info addressing the explanation of nation and community.

**Comment by mepda** [comment]
Could this be appended to nation.md or would this necessitate another tutorial page?

**Comment by aberdean** [comment]
I think the first part (your side) should be added to bellapps.md and the remote side to nation.md. Or, perhaps, even both sides to bellapps.md.
It could also be reworded nicely and included in the most appropriate place in the page.

**Comment by waryhermit** [comment]
What if the start of bellapps.md was changed to a mix of what it is now and what @Hulmani wrote. For example something like this:

> # Communities and Nations
> 
> The BeLL (Basic e-Learning Library) is not only a library, but also an individualized learning system, where students can select their own books and courses to target their individual goals. The two kinds of BeLL apps are described below.
> 
> **BeLL Communities (Local)**
> - Communities are how the BeLL functions on a local network, with users connecting to a community using either a laptop or a RPi and a router.
> - Periodically communities sync with Nations on the internet, which includes sending and receiving educational materials.
> - In step 1 you created a BeLL community on your computer. As you follow the steps on this page you will access and configure your community.
> 
> **BeLL Nations (Internet)**
> - Nations are BeLL apps for the Internet, allowing communities to interact with each other.
> - Nations are over a group of communities, and can run reports on any communities it owns.
> - As you complete these instructions, and OLE administrator will complete the registration of your community with the Virtual Intern Nation.

**Comment by dogi** [comment]
@waryhermit I really like that and I also think this is ready to be a `pull request` ;)

Anybody I allowed to create a PR on this issue using @waryhermit 's **last** suggestion

**Comment by sarvanivadali** [comment]
Hi @dogi, @waryhermit Suggested content is ready and approved. Can I create PR for this?

**Comment by dogi** [comment]
@sarvanivadali go for it ;)
