### ISSUE TITLE
GitHub Issues Page "Introduction": Repeated Sentence 

### ISSUE THREAD

**Issue by saavfoxdev** [open-learning-exchange/open-learning-exchange.github.io#1884]
### Problem

Repeated sentence in GitHub Issues page. Was this intentional, or should it be fixed? If not then I would consider this being part of issue #1108 

### Steps to reproduce the problem

N/A

### Screenshots

![issue](https://user-images.githubusercontent.com/31100486/41343210-d3b87f3e-6eb2-11e8-83fe-b5340c153397.PNG)

### Proposed solution

Remove first instance of the sentence.

**Comment by NirmalKumarJoshi** [comment]
Yeah, you can work on this.
