### ISSUE TITLE
Adding information to provide interns with solutions to the Virtual Intern course not showing up on their BeLL

### ISSUE THREAD

**Issue by Vncentou422** [open-learning-exchange/open-learning-exchange.github.io#1886]
### Problem
It also might be useful to mention in the Markdown Wiki of what to do when the Virtual Intern course is not on your community BeLL.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="864" alt="screen shot 2018-06-14 at 4 17 26 am" src="https://user-images.githubusercontent.com/5431055/41400031-f52e3172-6f89-11e8-8ae3-03ae51bcd109.png">

### Proposed solution
Provide subsequent info or solutions such as contacting admins to send you the proper publication.

**Comment by xyb994** [comment]
@Vncentou422 Sure, you can go ahead and add a short sentence for that.
