### ISSUE TITLE
Spelling Errors in "vi-vagrant.md" and "vi-github-issues.md"

### ISSUE THREAD

**Issue by gowiredu** [open-learning-exchange/open-learning-exchange.github.io#1887]
### Problem
Just a couple of spelling errors. Most of the First Steps files are fine, grammatically speaking, which makes the spelling mistakes below stand out a little to me.

### Steps to reproduce the problem
N/A

### Screenshots
![gowiredu-issue-1-1](https://user-images.githubusercontent.com/10681719/41474071-0934bf92-7089-11e8-8621-b1b10195dd9b.png)

![gowiredu-issue-1-2](https://user-images.githubusercontent.com/10681719/41474079-0cfff38a-7089-11e8-9633-982ce605977d.png)

### Proposed solution
Edit files and correct misspellings.

**Comment by xyb994** [comment]
Thanks for catching the typo. Go ahead and create a PR for this.

**Comment by gowiredu** [comment]
Okay. I'll take care of it. Thanks.
