### ISSUE TITLE
Fix unclear sentence in vi-bell-installation page

### ISSUE THREAD

**Issue by saavfoxdev** [open-learning-exchange/open-learning-exchange.github.io#1891]
### Problem
Referring to #1108  ,  Unclear sentence in Virtual Interns/ Step 1 Bell Installation & Configuration page.

### Steps to reproduce the problem

N/A

### Screenshots

![spelling fix](https://user-images.githubusercontent.com/31100486/41690413-44fff3be-74aa-11e8-9eeb-b7e06490352c.PNG)

### Proposed solution

Will make sentence a little bit more clear. Will apply fixes to vi-bell-installation.md

Suggestion: "Make sure you cd to the designated OLE directory you created earlier."

**Comment by xyb994** [comment]
@saavfoxdev Make sense, go ahead and create a PR.
