### ISSUE TITLE
spelling error in vi-github-issues.md 

### ISSUE THREAD

**Issue by saavfoxdev** [open-learning-exchange/open-learning-exchange.github.io#1893]
### Problem

Referring to #1108 , fix  spelling error in pages/vi/vi-github-issues.md  **step 3** 

### Steps to reproduce the problem

N/A

### Screenshots

![error](https://user-images.githubusercontent.com/31100486/41692222-d9c8c440-74b3-11e8-9ed3-a4c9cca6b476.PNG)

### Proposed solution

Change to: Fill out the details for the pull request according to the given structure and also create a checklist for other's understanding.

**Comment by xyb994** [comment]
@saavfoxdev Thanks for catching the typo, go ahead and create a PR.
