### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by saavfoxdev** [open-learning-exchange/open-learning-exchange.github.io#1895]
### Problem
Spelling error in vi/vi-github-and-repositories.md
Referring to #1108 

### Steps to reproduce the problem

N/A 

### Screenshots

![error2](https://user-images.githubusercontent.com/31100486/41699187-82245be0-74d7-11e8-8313-b7afba3529a9.PNG)

### Proposed solution

Suggested change: Developers should always sync their fork and make sure their repositories are up to date with GitHub every time they begin to work. This way we as a team can minimize data loss, and can save you some time.

**Comment by xyb994** [comment]
@saavfoxdev Good catch, go ahead and create a PR.
