### ISSUE TITLE
Clarification at "Once you complete Step 'X'" parts of First Steps.

### ISSUE THREAD

**Issue by gowiredu** [open-learning-exchange/open-learning-exchange.github.io#1896]
### Problem
On First Steps, the "Once you complete" parts can be clarified just a little more. Although they say, 

> "Once you complete Step 'X', you should have... 'X' comment made"

they could say, 

> "Once you complete Step 'X', you should have... 'X' comment made (on another issue)"

I realize it says so earlier to comment on other issues instead of your own but I just thought it would serve as a good reminder if it was put down there too. 

### Steps to reproduce the problem
N/A

### Screenshots
![gowiredu-issue-1](https://user-images.githubusercontent.com/10681719/41734958-75ddb604-7556-11e8-9dd6-1fdb4e839c8e.png)
![gowiredu-issue-2](https://user-images.githubusercontent.com/10681719/41734960-79b84dde-7556-11e8-84d6-904c67b74868.png)

### Proposed solution
On Step 6, change

> "Once you complete Step 6, you should have... 1 comment made"

to

> "Once you complete Step 6 you should have... 1 comment made (on an issue you didn't create)"

and on Step 8, change 

> "Once you complete Step 8 you should have... 4 comments made (one at step 6 and three at step 8)"

to

> "Once you complete Step 8 you should have... 4 comments made (on issues you didn't create, one at step 6 and three at step 8)"

**Comment by xyb994** [comment]
@gowiredu Good catch, I noticed a lot of perspective virtual interns ignored this requirement. Go ahead and create a PR to make it clearer.
