### ISSUE TITLE
macOS Vagrant Download Section in Step 1 Needs A Header

### ISSUE THREAD

**Issue by gowiredu** [open-learning-exchange/open-learning-exchange.github.io#1897]
### Problem
Just a slight formatting change suggestion to Step 1 for organization and readability. The highlighted part in the screenshot is a little close to the "For Ubuntu" instructions above it.

### Steps to reproduce the problem
N/A

### Screenshots

![gowiredu-issue-3](https://user-images.githubusercontent.com/10681719/41736049-551294dc-7559-11e8-950e-03cc4c6c91e5.png)

### Proposed solution
Add a _"Vagrant Download"_ header right above the highlighted part of the screenshot and make it the same font size as "For macOS" and "For Ubuntu".

**Comment by xyb994** [comment]
Vagrant download page is intended for Ubuntu only. For macOS it's installed by a brew formula.

**Comment by gowiredu** [comment]
Oh okay. I'll close this issue then. Thanks.
