### ISSUE TITLE
"communityBeLL" in "vi-faq.md" should be "community BeLL" to match the rest of First Steps

### ISSUE THREAD

**Issue by gowiredu** [open-learning-exchange/open-learning-exchange.github.io#1902]
### Problem

> "communityBeLL"

in _"vi-faq.md"_ should be

> "community BeLL"

See first screenshot.

Just a minor issue. It's _community BeLL_ in every other part of "First Steps" and that's why I brought it up.

### Steps to reproduce the problem
N/A

### Screenshots
![gowiredu-issue-9](https://user-images.githubusercontent.com/10681719/41765250-8b58f1c6-75d1-11e8-9045-0ccb409168b7.png)
![gowiredu-issue-7](https://user-images.githubusercontent.com/10681719/41765652-b12b5096-75d2-11e8-810e-64749aa8456b.png)
![gowiredu-issue-8](https://user-images.githubusercontent.com/10681719/41765653-b1463212-75d2-11e8-9efa-6aa06beda65b.png)

### Proposed solution
Change

> "communityBeLL"

to

> "community BeLL"

in _"vi-faq.md"_

**Comment by xyb994** [comment]
There are actually 2 places: https://github.com/open-learning-exchange/open-learning-exchange.github.io/search?q=communityBeLL&unscoped_q=communityBeLL

Go ahead and create a PR.

**Comment by gowiredu** [comment]
Okay. I'll fix both of them.
