### ISSUE TITLE
Understanding the syncing process with the fork

### ISSUE THREAD

**Issue by Hulmani** [open-learning-exchange/open-learning-exchange.github.io#191]
Here is nice tutorial I found to understand synching process with the fork. 
We can put a link on the GitHub repository page. Here is the [Video] (https://www.youtube.com/watch?v=-zvHQXnBO6c)

**Comment by DrewPerlman** [comment]
Sure, feel free to link that video at the bottom of gitandrepositories.md.

**Comment by Hulmani** [comment]
Will do.. Thanks

**Comment by DrewPerlman** [comment]
[This commit](https://github.com/open-learning-exchange/open-learning-exchange.github.io/commit/789698a95a60d775c348c6eded44ae512ce3a5b1) fixed this issue.
