### ISSUE TITLE
Virtual Intern MDWiki Step 3 link to github.io

### ISSUE THREAD

**Issue by rkinback** [open-learning-exchange/open-learning-exchange.github.io#1911]
### Problem
In Step 3 the directions have that the interns should make a link to their github.io page in the form of https://YourUserName.github.io , and add that link to the Gitter chat, but this is not the exact link to the interns gitter.io page. 

### Steps to reproduce the problem
N/A

### Screenshots
![step 3](https://user-images.githubusercontent.com/40527513/42003032-52080320-7a1e-11e8-990c-ceb7ecd5873e.PNG)

### Proposed solution
In the place of this example link https://YourUserName.github.io , put https://github.com/YourUserName/YourUserName.github.io as the example link instead.

**Comment by xyb994** [comment]
Actually `https://YourUserName.github.io` is the right link, we wanted to make sure VIs have the github.io page setting right so we can visit their forked github.io page. In your case https://rkinback.github.io/ is working so we know you have the repo setting configured right.

**Comment by rkinback** [comment]
Oh ok, when I click on the link it goes here: 
![linkresult](https://user-images.githubusercontent.com/40527513/42003737-cf334500-7a21-11e8-92c0-589b536160cc.PNG) . Im not sure why.

**Comment by xyb994** [comment]
@rkinback Could you explain what you expect to see?

**Comment by rkinback** [comment]
I could be wrong but I expected to see : 
![expectedtosee](https://user-images.githubusercontent.com/40527513/42003909-677b8bce-7a22-11e8-9bd1-bb9bcfbf8258.PNG)

**Comment by xyb994** [comment]
@rkinback Your screenshot is showing the forked repo. We are assuming nothing would go wrong with forking, since it's only clicking a button. Plus the first PR itself will show that the VI have forked the repo.

Coming back the "Problem" you mentioned in the original issue comment, https://YourUserName.github.io is link to the intern's github.io page. You may read more at https://pages.github.com/

**Comment by rkinback** [comment]
@xyb994  Ok thanks.
