### ISSUE TITLE
MyBell Virtual Interns Course Step 11 Links

### ISSUE THREAD

**Issue by rkinback** [open-learning-exchange/open-learning-exchange.github.io#1912]
### Problem
In Step-11 on the Virtual Interns Course the question says "Here are some links to help about how to efficiently use google search:." There are no links in the Resources section of the Step.
 
### Steps to reproduce the problem
N/A

### Screenshots
![question11](https://user-images.githubusercontent.com/40527513/42005929-c68a7ff4-7a2b-11e8-9ce2-8f8aef25b5ed.PNG)

### Proposed solution
Add this link https://www.lifehack.org/articles/technology/20-tips-use-google-search-efficiently.html and an example link such as https://www.google.com/search?q=how+to+fork+a+repo+in+git&rlz=1C1CHBF_enUS766US766&oq=how+to+fork+a+repo+in+git&aqs=chrome..69i57j0l4.7104j0j4&sourceid=chrome&ie=UTF-8

**Comment by Vncentou422** [comment]
I think the first link should be more than enough

**Comment by xyb994** [comment]
@rkinback Thanks for raising the issue, I'll add the first link to the course on VI nation.

**Comment by xyb994** [comment]
@rkinback It's updated on VI nation, future VIs will receive the new version.
@Vncentou422 thank you for the comment.
