### ISSUE TITLE
remove item 4 in FAQ Q16 

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#1913]
### Problem
In [FAQ16: What do I do if I already have a github.io with my username?](https://open-learning-exchange.github.io/#!pages/vi/vi-faq.md#Q16:_What_do_I_do_if_I_already_have_a_github.io_with_my_username?)
A few solutions are already provided. It's not necessary to include the last option there.

### Proposed solution

Remove FAQ Q16 item 4

**Comment by Vncentou422** [comment]
Am I allowed to work on this issue?

**Comment by xyb994** [comment]
@Vncentou422 sure, go ahead
