### ISSUE TITLE
vi first steps.md Step 1 typo

### ISSUE THREAD

**Issue by rkinback** [open-learning-exchange/open-learning-exchange.github.io#1914]
### Problem
This is a very small issue. In Step 1 there is a lowercase w on "we" after a period as shown in the screenshot.

### Steps to reproduce the problem

N/A

### Screenshots

![issueone](https://user-images.githubusercontent.com/40527513/42067002-d6733d66-7af8-11e8-83e0-a9c37ac2e624.PNG)

### Proposed solution

Just turn the lowercase w into uppercase W

**Comment by xyb994** [comment]
@rkinback Good catch, go ahead and create a PR.
