### ISSUE TITLE
Virtual Intern MDWiki Step 8 Clarification

### ISSUE THREAD

**Issue by Vncentou422** [open-learning-exchange/open-learning-exchange.github.io#1915]
### Problem
"Create three more issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests. You should resolve three issues created by yourself, and make sure you mention in the issue you are working on, that you are in fact working on it."

These two sentences feel too clunky and it feels very repetitive to mention that you should solve three issues twice. 
### Steps to reproduce the problem
N/A

### Screenshots
<img width="896" alt="screen shot 2018-06-29 at 1 14 15 am" src="https://user-images.githubusercontent.com/5431055/42074500-9ca379c4-7b3a-11e8-973e-eca33d365bc2.png">

### Proposed solution
"Create three more issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests. Make sure you mention in the issue you are working on and that you are in fact working on it."

**Comment by rkinback** [comment]
@/Vncentou422 I agree, your proposed solution is easier to read and understand what to do for this step. 
In this sentence here:
> "Make sure you mention in the issue you are working on and that you are in fact working on it." 

It should be: 
>"Make sure you mention in the issue you are working on, that you are in fact working on it."

**Comment by xyb994** [comment]
I'm still a bit confused by "Make sure you mention in the issue you are working on and that you are in fact working on it". Does it mean post a comment in the issue that you are working on it?

**Comment by Vncentou422** [comment]
So right now I have 
"Create three more issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests. Make sure you mention in the issue you are working on, that you are in fact working on it"

Is there anything else I should adjust?

**Comment by leahphuong** [comment]
Maybe clarify how they should *mention* in the issue to let other people know they are working on it? for example: add a comment, or edit the issue...etc

**Comment by xyb994** [comment]
@Vncentou422 

How about this:
> Create three more issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests. **Make sure you add the issue number right after `Fixes #` in the pull request description template so others know you are working on it.**

**Comment by lmmrssa** [comment]
@Vncentou422 Better way to let other know that you are working on it is to Assign yourself. So mentioning something like **Assign yourself on the issues that you are actually working** could be more clear

**Comment by rkinback** [comment]
@Vncentou422 could it be,
>Make a note in the issue that lets others know that you are working on fixing the issue. Then when you fix the issue, make sure you add the issue number right after `Fixes #` in the pull request description template.
