### ISSUE TITLE
First Steps Markdown Big Picture put software and languages in a list

### ISSUE THREAD

**Issue by rkinback** [open-learning-exchange/open-learning-exchange.github.io#1918]
### Problem
When you read the third paragraph in the Big Picture section there are 13 software programs and languages listed in sentence form. This would seem to be a good place to use markdown lists to make this section easier to read. Possibly each of these in the list could be links to each main site describing the software and languages. 

### Steps to reproduce the problem

N/A

### Screenshots

![issuetwo](https://user-images.githubusercontent.com/40527513/42111241-99698fce-7b98-11e8-96a3-2e2384aed153.PNG)

### Proposed solution

Once accepted, you and your team will work on an assignment, and we’ll switch up the assignments each week. As part of this internship, you will have the opportunity to work with software and languages including:
  * [Git](https://en.wikipedia.org/wiki/Git) 
  * [GitHub](https://github.com/)
  * [Markdown](https://daringfireball.net/projects/markdown/syntax)
  * [Vagrant](https://www.vagrantup.com/)
  * [VirtualBox](https://www.virtualbox.org/)
  * [Command Line/Terminal](https://en.wikipedia.org/wiki/Command-line_interface)
  * [Command Line/Terminal Scripts](https://www.codecademy.com/articles/command-line-commands)
  * [Vim](https://www.vim.org/)
  * [CouchDB](http://couchdb.apache.org/)
  * [Docker](https://www.docker.com/)
  * [HTML5](https://html5demos.com/)
  * [JavaScript](https://www.javascript.com/)
  * [Node.js](https://nodejs.org/en/)
  * [Angular](https://angular.io/)

**Comment by rkinback** [comment]
Yea, I was wondering that too. I was going to try flatten out the list horizontally and see if that is better.

**Comment by rkinback** [comment]
or a table might work better for that.

**Comment by xyb994** [comment]
I think we can certainly make them stand out by making those text bold or italic and and link them to their respective website. 

![image](https://user-images.githubusercontent.com/7483137/42125881-fdd1181a-7c4c-11e8-8c62-d001c3f1f0cf.png)
![image](https://user-images.githubusercontent.com/7483137/42125883-0a719edc-7c4d-11e8-892a-d6244b6e8370.png)
