### ISSUE TITLE
Planet User Manual missing verb

### ISSUE THREAD

**Issue by rkinback** [open-learning-exchange/open-learning-exchange.github.io#1920]
### Problem
The sentence is describing what the library is, but the sentence in the Planet User Manual is a sentence fragment. It is missing the verb "is." 

### Steps to reproduce the problem

N/A

### Screenshots

![issuethree](https://user-images.githubusercontent.com/40527513/42117086-93daf568-7baf-11e8-953c-3985626dd2d6.PNG)

### Proposed solution

This sentance
>The library where learning Resources are stored and categorized within the Planet system.

should read
>The library is where learning Resources are stored and categorized within the Planet system.

**Comment by xyb994** [comment]
@rkinback go ahead and create a PR.
