### ISSUE TITLE
add link to download Firefox if VIs don't already have it

### ISSUE THREAD

**Issue by leahphuong** [open-learning-exchange/open-learning-exchange.github.io#1921]
### Problem
In `http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations.md` page, there is an instruction for **VIs** to 
> open Firefox (download if you don't already have it - it is VERY important that you always use the BeLL in Firefox to limit errors).

but provide no links to download Firefox.
### Steps to reproduce the problem
N/A

### Screenshots
<img width="862" alt="screen shot 2018-06-29 at 6 22 38 pm" src="https://user-images.githubusercontent.com/13629659/42117532-1248c450-7bcb-11e8-80e2-5bcf0364c914.png">

### Proposed solution
For better user experience, I suggested that we include a link to download Firefox like this:  
> open Firefox ([download](https://www.mozilla.org/en-US/firefox/new/) if you don't already have it - it is VERY important that you always use the BeLL in Firefox to limit errors)

**Comment by rkinback** [comment]
That makes sense to me.

**Comment by Vncentou422** [comment]
Good idea

**Comment by leahphuong** [comment]
should I create a separate issue to add the Firefox link to `https://open-learning-exchange.github.io/#!pages/vi/vi-bell-installation.md`?

**Comment by xyb994** [comment]
@leahphuong I think we'd better make the language explicit and link prospective virtual interns to download Firefox in vi-bell-installatin. It's not necessary to link it at multiple places since the steps are in order and it's easy to search for Firefox download link.

**Comment by leahphuong** [comment]
ya that makes sense, I'll add Firefox link to `vi-bell-installation` instead
