### ISSUE TITLE
Typo in Bell Apps: Communities and Nations 

### ISSUE THREAD

**Issue by rkinback** [open-learning-exchange/open-learning-exchange.github.io#1922]
### Problem
In http://open-learning-exchange.github.io/#!./pages/vi/vi-bellapps.md under the Introduction to Planet there is a small typo. It has "cerate" instead of "create"

### Steps to reproduce the problem

N/A

### Screenshots

![issuefour](https://user-images.githubusercontent.com/40527513/42118015-04e6c78c-7bb5-11e8-995f-144fdbd2210c.PNG)

### Proposed solution

change 
> cerate

to 
>create

**Comment by Vncentou422** [comment]
good catch
