### ISSUE TITLE
Removal of redundant information on Step 8 of MDWiki

### ISSUE THREAD

**Issue by Vncentou422** [open-learning-exchange/open-learning-exchange.github.io#1930]
### Problem
"You must have made your pull requests and have them approved by at least three others and merged to the upstream repository. Just as before, announce your Pull Request on the Gitter chat and wait for at least three others to approve it. "

This sentence contains redundant information and is confusing to read. 

### Steps to reproduce the problem
N/A

### Screenshots
<img width="865" alt="screen shot 2018-07-02 at 5 17 33 pm" src="https://user-images.githubusercontent.com/5431055/42186790-f057075a-7e1b-11e8-914f-7ea2c94053b8.png">

### Proposed solution
You must have made your pull requests and have them each approved by at least three others in order for it to be merged to the upstream repository. Just as before, announce your Pull Request on the Gitter chat so others can review it.

**Comment by leahphuong** [comment]
I'd suggest to clarify the term **others** here as well,  **others** as in "OLE team members/interns" maybe?
