### ISSUE TITLE
Tracking progress username clarification

### ISSUE THREAD

**Issue by leahphuong** [open-learning-exchange/open-learning-exchange.github.io#1931]
### Problem
In `https://open-learning-exchange.github.io/#!pages/vi/vi-track-progress.md`, in order to track progress, user is asked to enter a username, but not clear what kind of username so it's a little confusing for someone who uses it for the first time.

> Type in a valid username

### Steps to reproduce the problem

N/A

### Screenshots

<img width="650" alt="screen shot 2018-07-02 at 4 17 44 pm" src="https://user-images.githubusercontent.com/13629659/42184796-b7dab518-7e14-11e8-8e9a-9109b243f57f.png">

### Proposed solution

Clarify that user needs to enter a Github username.
> Type in a valid Github username

**Comment by dogi** [comment]
@leahphuong also this issue is a go ;)

**Comment by leahphuong** [comment]
sweet I'll start working on it
