### ISSUE TITLE
Community BeLL - Learner password

### ISSUE THREAD

**Issue by leahphuong** [open-learning-exchange/open-learning-exchange.github.io#1932]
### Problem
In `http://open-learning-exchange.github.io/#!pages/vi/vi-nation.md`, user is asked to create a dummy user (Learner level) but advised not to use a real password because people who are logged in as *admin* maybe able to see the password. 

This prompted a question from the user "Would they (admin) be able to see Manager level account password too?" 

### Steps to reproduce the problem

N/A

### Screenshots

<img width="855" alt="screen shot 2018-07-02 at 5 39 41 pm" src="https://user-images.githubusercontent.com/13629659/42188014-30bd0732-7e20-11e8-92ba-2e840e6393dc.png">

### Proposed solution

Provide an answer to the question above and edit the paragraph. Something like this:

> **NOTE**: After you register your community, but before you can sync with the nation, you need to create an additional dummy user on your community. Therefore, create a quick additional user under "Become a Member" on the login page (HINT: When creating the dummy user, don't give it a password that you actually use, as other people logged in as admin may be able to see it **(they won't however be able to see your Manager level user password)** -- you won't need the password in the future so don't worry about having to remember or save it after this one time). Then, login and double-check that you're listed under Members. Then, log out and log back in with your admin account. Now that your community has a user, you can sync with the nation.

**Comment by akshayuncc** [comment]
@leahphuong Currently BELL is at stand still. There are no different level as of now. Please create another issue.
Thank you.
