### ISSUE TITLE
Virtual Intern Course Step 9 Answering Problem

### ISSUE THREAD

**Issue by Sriharsha-Singam** [open-learning-exchange/open-learning-exchange.github.io#1933]
### Problem
The Question in the virtual intern course is "How many ways can you create a pull request from this page? (how many buttons do you see that allow you to create a pull request?)."

To answer the question there is only __one__ button that allows you to upload an image.

### Steps to reproduce the problem

N/A

### Screenshots

![screen shot 2018-07-03 at 1 42 11 pm](https://user-images.githubusercontent.com/14966231/42236375-b8ce7a36-7ec8-11e8-8ad6-e38709ac01e2.png)

### Proposed solution

I think a proposed solution is that we put either multiple choice answers or a text box to input an answer.

**Comment by dogi** [comment]
@Sriharsha-Singam I due no understand can you explain more

**Comment by Sriharsha-Singam** [comment]
@dogi  Well it seems like the question is asking for a number of buttons available to create a pull request. As such shouldn't there be a text box to enter the answer (e.g: 3 pull request buttons).

**Comment by BhargaviNadendla** [comment]
@Sriharsha-Singam  I think the question could be rephrased as " How many ways can you create a pull request from this page? (Mark the buttons you see that allow you to create a pull request from the below screenshot and upload it.)

**Comment by lmmrssa** [comment]
@BhargaviNadendla yes that sounds good.

**Comment by Emiton** [comment]
@Sriharsha-Singam I also had trouble using the upload button for any of the other questions. I tried uploading various file types, but it didn't work at all. I might have to create a separate issue for the upload button.

**Comment by demuze28** [comment]
I experienced this issue during the survey as well and also provided feedback on it. I agree that the question should explicitly tell the user what it is looking for (for example, telling the user to upload a screenshot of the buttons circled or a textbox that asks the user for a numeric value.)

**Comment by jimkosh** [comment]
I wonder if just having a multiple choice option with numerical answer values might be more concise?

**Comment by coder8102** [comment]
> @dogi I mean that the question is _asking_ for a **numeric answer** but the _available answer tools_ are just **one upload** button as seen in the screenshot.

This question text is confusing. This is how I interpreted. Question is asking to upload screenshot of buttons to allow creating pull requests on the page.

**Comment by lmmrssa** [comment]
closing this issue as this is related to BellApps and now we work on planet.
