### ISSUE TITLE
Nation BeLL - edit step header

### ISSUE THREAD

**Issue by leahphuong** [open-learning-exchange/open-learning-exchange.github.io#1934]
### Problem
In `http://open-learning-exchange.github.io/#!pages/vi/vi-nation.md`, one of the steps' title was written as
> Check the Sync Worked

which is slightly confusing?

### Steps to reproduce the problem

N/A

### Screenshots

<img width="861" alt="screen shot 2018-07-03 at 7 21 47 pm" src="https://user-images.githubusercontent.com/13629659/42249065-0e9e7762-7ef7-11e8-8946-e66dbcb3c03e.png">

### Proposed solution

Add *IF* to the phrase to make it clearer
> Check If the Sync Worked

or 
> Check Sync Status

and maybe add a Troubleshooting section?

**Comment by Sriharsha-Singam** [comment]
I think the 
> Check If the Sync Worked

works better than the

> Check Sync Status

**Comment by dogi** [comment]
:) both are fine
I like `Check Sync Status`
because it is short
