### ISSUE TITLE
BeLL-Apps: Communities and Nations - Preparation step could be written more clearly

### ISSUE THREAD

**Issue by leahphuong** [open-learning-exchange/open-learning-exchange.github.io#1935]
### Problem
In `http://open-learning-exchange.github.io/#!./pages/vi/vi-bellapps.md`, Preparation step could be written more clearly.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="816" alt="screen shot 2018-07-04 at 12 16 54 am" src="https://user-images.githubusercontent.com/13629659/42256544-059a55fe-7f20-11e8-9b07-d8ecc9c554f7.png">

### Proposed solution

Rewrite it as follow:
> Please go to http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html or run `vagrant global-status` in the command line to see if your community BeLL is currently running. If not, please `cd` into `ole--vagrant-vi` directory in your local machine and run `vagrant up`.

**Comment by Sriharsha-Singam** [comment]
__What if to make it a bit more easier (changes in the last sentence of blockquote):__

> Please go to http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html or run ```vagrant global-status``` in the command line to see if your community BeLL is currently running. If not, please run ```cd ole--vagrant-vi``` in the command line to go to the community BeLL directory in your local machine and then run ```vagrant up```.

**Comment by lmmrssa** [comment]
@leahphuong yes you can make the changes.

**Comment by dogi** [comment]
@leahphuong this issue is a go
