### ISSUE TITLE
BeLL Installation Terminal Commands

### ISSUE THREAD

**Issue by Sriharsha-Singam** [open-learning-exchange/open-learning-exchange.github.io#1940]
### Problem
As you look in the **first screen shot** the terminal commands are written in a list:
1. `cd Desktop `
2. `mkdir OLE`
 
but in the **later screen shot** the terminal commands are written in this format:
```terminal
cd Desktop
mkdir OLE
```

### Steps to reproduce the problem

N/A

## _terminal commands are written in a list:_

![screen shot 2018-07-06 at 12 19 52 am](https://user-images.githubusercontent.com/14966231/42359801-62cc3ae2-80b2-11e8-8683-cf098401ed5e.png)

 ## _but in the later screen shots the terminal commands are written in this format:_

![screen shot 2018-07-06 at 12 19 58 am](https://user-images.githubusercontent.com/14966231/42359812-785c87a4-80b2-11e8-81f2-c0db8efebdd3.png)

### Proposed solution

Set the format to the **second** format since it is used more often and frankly gives a better look at entering the commands in the terminal/command prompt.

**Comment by lmmrssa** [comment]
@Sriharsha-Singam yes you can work on it
