### ISSUE TITLE
Better Wording For First Steps - Step 8

### ISSUE THREAD

**Issue by Sriharsha-Singam** [open-learning-exchange/open-learning-exchange.github.io#1942]
### Problem
The second bullet point currently says this:

- 4 comments made (on issues you didn't create, one at step 6 and three at step 8)

But it probably should say something like this:

- 4 comments made on *issues you didn't create* (one at step 6 and three at step 8)

The reason I say this is that all the parenthesizes in this list include only how many of each at which step and **not that extra part** : *issues you didn't create*

### Steps to reproduce the problem

N/A

### Screenshots

![screen shot 2018-07-06 at 3 46 00 pm](https://user-images.githubusercontent.com/14966231/42402231-75f8b0e2-8147-11e8-9a73-22a0e4cc5892.png)

### Proposed solution

The second bullet point currently says this:

- 4 comments made (on issues you didn't create, one at step 6 and three at step 8)

But it probably should say something like this:

- 4 comments made on *issues you didn't create* (one at step 6 and three at step 8)

**Comment by lmmrssa** [comment]
yes make these changes
