### ISSUE TITLE
Vagrant Instructions - Commands Title

### ISSUE THREAD

**Issue by Sriharsha-Singam** [open-learning-exchange/open-learning-exchange.github.io#1943]
### Problem
**Title Words** should probably allude to what the **list actually talks about** rather than **actually listing the list out**

Meaning instead of the title saying: 

> Up, Suspend, Halt, and Destroy

It should probably say:

> Common Vagrant Commands

or

> Necessary Vagrant Commands

or

> Vagrant Commands

### Steps to reproduce the problem

N/A

### Screenshots

![screen shot 2018-07-06 at 6 44 18 pm](https://user-images.githubusercontent.com/14966231/42403096-dc54ca2e-814c-11e8-906e-ae568bb7da86.png)

#### I feel like it should be one of the options above.

**Comment by akshayuncc** [comment]
@Sriharsha-Singam Ok. Vagrant Commands seems good. Go ahead create a PR.
