### ISSUE TITLE
GitHub Issues Tutorial Missing Command

### ISSUE THREAD

**Issue by Sriharsha-Singam** [open-learning-exchange/open-learning-exchange.github.io#1945]
### Problem
The **summary of steps to follow** at the bottom of the GitHub Issues Tutorial has a **missing step** related to **syncing with the master.** 
_This missing step actually got me confused for sometime while trying to finish a Pull Request for a different issue._

### Steps to reproduce the problem

N/A

## The steps currently include:

![screen shot 2018-07-08 at 1 03 20 am](https://user-images.githubusercontent.com/14966231/42416981-0455d640-824b-11e8-9f03-727ffbab4e2f.png)

## when at the end of all **step 1** it should include _this line of code_:

![screen shot 2018-07-08 at 1 05 46 am](https://user-images.githubusercontent.com/14966231/42416986-24667e08-824b-11e8-878b-4d5c8fd3849f.png)

### Proposed solution

I think the step one to the summary of steps should be **changed** to this:

_(I am not sure if this is totally necessary but I feel this is a good way to make sure that the Personal GitHub fork `master` is up-to-date with the upstream `master`)_

### 1. Create a branch 
  1.  Open an issue within the right repository (upstream repository) and explain the problem. If the issue is approved, `cd` to `yourusername.github.io` directory and sync with the upstream repository using `git fetch upstream` , `git checkout master`, and `git merge upstream/master`, and **then** `git push origin master` to sync it with the remote forked repository.

_Please Do Input Any Suggestions!_

**Comment by lmmrssa** [comment]
I think it will be good to add git push origin but you do not need last part **to sync it with the remove forked repository** as it is already mentioned before that commands are to sync with upstream
