### ISSUE TITLE
Text formatting in Bell apps course instructions

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/open-learning-exchange.github.io#1953]
### Problem
The instructions for working with Bell, Planet or GitHub are formatted in the same way by highlighting the possible buttons or clicks which looks so good and are easy to grasp. But this formatting was missed at "Take the course" instructions. The difference can be seen in the following screenshots.

### Steps to reproduce the problem
N/A

### Screenshots
_Missed formatting in:_

![image](https://user-images.githubusercontent.com/25775298/42734265-a57b7118-8806-11e8-92c2-2f325bae5762.png)

_Correct formatting in:_

![image](https://user-images.githubusercontent.com/25775298/42734272-cf41de24-8806-11e8-9dff-2359f40828f0.png)

### Proposed solution
The first one can be formatted as the second one which gives a uniform and better look and feel

**Comment by akshayuncc** [comment]
@BhargaviNadendla Seems good to me.
