### ISSUE TITLE
OLE Planet - edit description 

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/open-learning-exchange.github.io#1954]
### Problem
I found a minor mistake in the description of OLE Planet, it states "At the core of Planet is a repository of free, open access..." which can be rephrased. Here, I attach the screenshot of it.

### Steps to reproduce the problem
N/A

### Screenshots

![image](https://user-images.githubusercontent.com/25775298/42738315-7397dff6-8847-11e8-860a-b2ceb8bf1f2a.png)

### Proposed solution
It can be rephrased as 

> At the core, Planet is a repository of free, open access,....

or

> At the core of Planet, it is a repository of free, open access,...

**Comment by akshayuncc** [comment]
@BhargaviNadendla Good job. Go ahead and create a PR.

**Comment by akash1525** [comment]
Hi Team,
I see that you are all doing a great job but Is there a way I can start contributing again? I went off for some time due to personal commitments but would love to start working with you all again Please let me know how and when can I contribute.

**Comment by aakarnik** [comment]
@akash1525 please join us on the[ gitter chat](https://gitter.im/open-learning-exchange/chat)
