### ISSUE TITLE
Tech Geniuses Introduction - Grammatical Error

### ISSUE THREAD

**Issue by Emiton** [open-learning-exchange/open-learning-exchange.github.io#1955]
### Problem
There is a small grammatical error in the tech geniuses introduction. 

The original statement is: 

>As a means of communication, we encourage you to subscribe to the notification in Tech Genius Gitter chatroom once you are invited to the channel.

The wording "to the notification" is slightly incorrect.

### Steps to reproduce the problem
Navigate to the [Tech Geniuses Introduction](http://open-learning-exchange.github.io/#!pages/techgenius/tg-introduction.md) on the wiki.

### Screenshots
![tech-genius-support-issue](https://user-images.githubusercontent.com/31858709/42769915-a65b15f2-88f1-11e8-829c-f500727f8674.PNG)

### Proposed solution
The correct wording should be:
>As a means of communication, we encourage you to subscribe _**to notifications**_ in Tech Genius Gitter chatroom once you are invited to the channel.

This is a minor change, but unless referring to a single notification, 'notifications' are referred to in the plural form.

**Comment by aakarnik** [comment]
@Emiton Good catch, you can go ahead and make a pr.
