### ISSUE TITLE
Referencing a block in "create a commit" GitHub Issues step

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/open-learning-exchange.github.io#1959]
### Problem
To create a commit for a fix, the command to be used is `git commit -m "commit message"` (Given in GitHub issues). The instructions on how to write a `commit message` are given below but they are not referenced here and the rest of the commands to be used are continued. 

### Steps to reproduce the problem
N/A

### Screenshots

![image](https://user-images.githubusercontent.com/25775298/42789908-840bfe12-892d-11e8-9cfb-fa026c600afe.png)

### Proposed solution
The commit message guidelines can be referenced(so as to see them before using the command with a custom message). This will be much clearer

>`git commit -m "commit message"` (refer the commit message guidelines below)

**Comment by Sriharsha-Singam** [comment]
Seems good.
