### ISSUE TITLE
githubandmarkdown.md: minor image edit

### ISSUE THREAD

**Issue by sthak004** [open-learning-exchange/open-learning-exchange.github.io#196]
In the ![GitHub and Markdown](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/githubandmarkdown.md) page, the last image shows a sample markdown file that the interns should create.

Here is the picture I am specifically referring to:
![alt text](https://raw.githubusercontent.com/open-learning-exchange/open-learning-exchange.github.io/master/pages/uploads/images/Edit.png)

Next to the branch selection tab, it shows the path of the file. I understand that we removed the *II_CC* page structure so, I believe we should alter the picture to match that change, as students might be confused upon reading the instructions and viewing the image.

Here is my suggestion:
![alt text](https://ibin.co/2nGZWaxo1txo.png)

I would go ahead and create a pull request but, the image refers to @EmilyLarkin's account and I feel that it should remain that way. So this is just a heads up.

**Comment by sthak004** [comment]
Actually, I just realized that I can make the change myself. I'll go ahead and do that.

**Comment by DrewPerlman** [comment]
Good point @sthak004, that picture is old and needs replacing. @i5o's page is an [example of a good member page](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/i5o.md), so I'd suggest replacing the image with a screenshot of his MD file.

**Comment by sthak004** [comment]
Sure, I will get that done.

**Comment by sthak004** [comment]
Have submitted a pull request:
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/201
