### ISSUE TITLE
Grammatical Error - Planet Quick Start Manual

### ISSUE THREAD

**Issue by Emiton** [open-learning-exchange/open-learning-exchange.github.io#1961]
### Problem
Incorrect grammar is used in the Planet Quick Start Manual

The current wording is "As you can see on the back of the router in the image below, there are a number of available ports and different uses for these port".

### Steps to reproduce the problem
Navigate to [Planet Quick Start Manual](http://open-learning-exchange.github.io/#!pages/techgenius/tg-hardware-setup.md)

### Screenshots
![planet-quickstart-issue](https://user-images.githubusercontent.com/31858709/42841706-eaa673fe-89d8-11e8-9de5-7991b077035d.PNG)

### Proposed solution
The word "port" should be changed to "ports". It should be plural in this case.

**The wording should be:**

"As you can see on the back of the router in the image below, there are a number of available ports and different uses for these _**ports**_."

**Comment by aakarnik** [comment]
@Emiton Good catch! You can also rephrase and say "there are a number of available ports with different uses for each port".

Go ahead and create a PR :)
