### ISSUE TITLE
Wording Error - Planet Quick Start Guide

### ISSUE THREAD

**Issue by Emiton** [open-learning-exchange/open-learning-exchange.github.io#1962]
### Problem
Incorrect wording is used in the Planet Quick Start Guide

The current wording is:

"If your RPi and router connections look like the picture below then should be connected properly to your router. Congratulations!"

### Steps to reproduce the problem
Navigate to [Planet Quick Start Guide](http://open-learning-exchange.github.io/#!pages/techgenius/tg-hardware-setup.md)

### Screenshots
![planet-quickstart-issue-2](https://user-images.githubusercontent.com/31858709/42844395-c9fa1b12-89e0-11e8-8176-327bba4e64e5.PNG)

### Proposed solution
The wording would be better if it was changed to something like the following:

"If your RPi and router connections look like the picture below, then your RPi should be properly connected to your router. Congratulations!"

**Comment by aakarnik** [comment]
@Emiton It's okay even if you only add the word "it" - "...then **it** should be properly connected...". Good catch, go ahead and create a PR.
