### ISSUE TITLE
Formatting Issue - Planet Quick Start Guide

### ISSUE THREAD

**Issue by Emiton** [open-learning-exchange/open-learning-exchange.github.io#1963]
### Problem
The word "Background" is lacking proper format. It is bolded, but needs further formatting in order to follow an intuitive convention.

-Missing a colon

### Steps to reproduce the problem
Navigate to [Planet Quick Start Guide](http://open-learning-exchange.github.io/#!pages/techgenius/tg-hardware-setup.md)

### Screenshots
Photo 1 - A picture of the incorrect formatting
![planet-quickstart-issue-3](https://user-images.githubusercontent.com/31858709/42845188-2836e30c-89e3-11e8-8a17-c9972aa38a50.PNG)

Photo 2 - A picture of correct formatting taken from another part of the Wiki
![planet-quickstart-issue-3-b](https://user-images.githubusercontent.com/31858709/42845535-40b6405c-89e4-11e8-8ea7-9309c7addcb6.PNG)

### Proposed solution
At the least, a colon should be added at the end like this ➡️ **Background:**

It would be nice if the information started on the next line as it does in Photo 2. In Photo 2, there is a colon separating the title from the information. Then the paragraph starts on the following line. This is much clearer than just bolding a word that is not a part of the sentence.

**Comment by aakarnik** [comment]
@Emiton I think it would be better to use a colon as the section also includes setting up Planet Hardware.
If you want to start the info on the next line, then I suggest you add a heading after the images of the RPi (something like "The Setup") to separate the `Background` section from the `Setup` section.

It's a good idea, go ahead and create a PR :)
