### ISSUE TITLE
Fixing Wording and punctuation errors in vagrant environment installation

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/open-learning-exchange.github.io#1964]
### Problem
The below paragraph lacks proper wording and could be rephrased. Can add the directory name in specific, change the punctuation "(In Windows)",.. to "(in Windows)",.. and remove the directory name in the next line.

### Steps to reproduce the problem
N/A

### Screenshots

![image](https://user-images.githubusercontent.com/25775298/42852295-53db64ee-89f5-11e8-91c5-682523a1d94a.png)

### Proposed solution

>If you have completed the installation guide, then you will find the directory `ole--vagrant-vi` at `c:\users\USERNAME\ole--vagrant-vi` (in Windows) or `Users/USERNAME/ole--vagrant-vi` (in Mac) or `/home/USERNAME/ole--vagrant-vi` (in Ubuntu) under your file system. This directory indicates that the corresponding community is attached to the development environment that OLE uses for training and to develop, test, and deploy new features.

**Comment by Emiton** [comment]
@BhargaviNadendla which line would you like to remove the directory name? Also, if you do change (In Windows) to (in Windows), please make sure to do it for "In Mac" and "In Ubuntu" as well. Good catch.

**Comment by BhargaviNadendla** [comment]
@Emiton yeah! I have changed it for Mac and Windows too.. but, for reference, I just added "in windows"
