### ISSUE TITLE
fixing all the minor typos in the 'Admin user manual'

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/open-learning-exchange.github.io#1965]
### Problem
Found a couple of typos and grammatical errors that need a fix

### Steps to reproduce the problem
Navigate to [planet-user-manual](http://open-learning-exchange.github.io/#!pages/techgenius/tg-planet-user-manual.md)

### Proposed solution

Re-occurance of 'in' could be deleted

![image](https://user-images.githubusercontent.com/25775298/42853409-d7a2800e-89fb-11e8-90b0-8ae8a62ecff6.png)

**Correcting 'installations' to 'installation'**

![image](https://user-images.githubusercontent.com/25775298/42853434-0888ec12-89fc-11e8-8926-de0b11ced8e5.png)

**'Functionality are' to 'functionality is'**

![image](https://user-images.githubusercontent.com/25775298/42853467-3f439bf8-89fc-11e8-921a-7fe7098dd664.png)

**'Resources may also stored' to 'be stored'**

![image](https://user-images.githubusercontent.com/25775298/42853508-8005fffa-89fc-11e8-9b92-860af8ce2ec0.png)

**'protects us violating' to 'protects us from violating'**

![image](https://user-images.githubusercontent.com/25775298/42853536-a9d9a110-89fc-11e8-8038-bbbb64efe280.png)

**Comment by Sriharsha-Singam** [comment]
Looks good to me.
