### ISSUE TITLE
Forked Repo Link Still Not Ready in Step 3 of "VI First Steps"

### ISSUE THREAD

**Issue by jimkosh** [open-learning-exchange/open-learning-exchange.github.io#1979]
### Problem
The link that VI Candidates send to the Gitter chat on step 3 takes a long time to load  (mine took more than a day to load). After creating a Markdown profile and pull request, readers may not remember the disclaimer about the 404 error given earlier. 

### Steps to reproduce the problem

1.) Note the gitter message provided on the "Github and Markdown" page of step 3:
>@/all I'm on step 3 - GitHub and Markdown, please look at https://YourUserName.github.io and review my profile pull request LinkToYourPullRequest  

2.) The link:  "https://YourUserName.github.io" using your own username, may still not be running.

### Screenshots

![image](https://user-images.githubusercontent.com/20807563/43300701-811c1f9e-9115-11e8-8a2b-9d5c17d730ca.png)

### Proposed solution

1.) Add another quick reminder that link may not be ready yet.

**Comment by lmmrssa** [comment]
@jimkosh Once you create profile account of yours it should not take longer for it to be publicly available. But yes you can put the reminder note that it might take sometime for link to be available.

**Comment by jimkosh** [comment]
@lmmrssa Okay sounds good! yeah, for some reason mine took a really long time to become available
