### ISSUE TITLE
Arrow button to return to the top of page is broken on mobile

### ISSUE THREAD

**Issue by demuze28** [open-learning-exchange/open-learning-exchange.github.io#1985]
### Problem

The button to return to the top of the page on the mobile version(320x480p resolution) does not work properly. When i opened the link in a new tab I got the message in the second screenshot. 

### Steps to reproduce the problem

Go to the first steps page on a phone (I used chrome on android), Scroll down to any step, and click the arrow button under the step. 

### Screenshots

<img width="317" alt="screen shot 2018-07-28 at 11 20 37 pm" src="https://user-images.githubusercontent.com/31854572/43362625-00bd058a-92bd-11e8-95a6-fc4bd480e609.png">
<img width="629" alt="screen shot 2018-07-28 at 11 20 52 pm" src="https://user-images.githubusercontent.com/31854572/43362626-03035ad8-92bd-11e8-8a28-2d2c11045ec7.png">

### Proposed solution

To go through the function's code and debug.

**Comment by BhargaviNadendla** [comment]
It's working fine on ios. You can proceed with this issue for Android. Good catch!

**Comment by lmmrssa** [comment]
@demuze28 fix it to be link of same page anchor tag.

**Comment by demuze28** [comment]
Will do!

**Comment by demuze28** [comment]
I couldn't figure out where the problem is occurring. I believe its somewhere in the scrollTop function.

**Comment by cquarte1** [comment]
I did mines on my iPhone, but I refer doing it on my laptop instead.

**Comment by bnmounir** [comment]
there were some anchor tags on the FAQ page that didn't work but now are fine.
