### ISSUE TITLE
Firefox Browser Doesn't Scroll to Top After Clicking on Link

### ISSUE THREAD

**Issue by jimkosh** [open-learning-exchange/open-learning-exchange.github.io#1986]
### Problem
Firefox automatically scrolls to a random point in the page when clicking on external links. 

### Steps to reproduce the problem

1. Open Firefox, and navigate to [first steps](http://open-learning-exchange.github.io/#!./pages/vi/vi-first-steps.md#Step_4_-_BeLL-Apps_and_Planet_Tutorial)
2. Scroll to "Step 2" and click on __Planet Installation and Configuration__.
3.  Note that you will be automatically scrolled to some mid point on the page. (See pic below)
4. Try this for all other links.

### Where my browser scrolls to after clicking "__Planet Installation and Configuration__"
![image](https://user-images.githubusercontent.com/20807563/43362687-94a5e7b6-92a5-11e8-9040-0ad7fd5b6411.png)

### Proposed solution

This seems to be browser specific to Firefox, as this is not an issue on Chrome.  Not sure how to fix this or where to start but here is a helpful link I've found:
* [Prevent Automatic Autoscroll](https://stackoverflow.com/questions/7035331/prevent-automatic-browser-scroll-on-refresh)

Other option would be to recommend in "The Big Picture" to go through instructions using Chrome.

**Comment by lmmrssa** [comment]
@jimkosh Specific links are taking to the related section of the page. Which is intended to happen so that they do not need to search for the section. If any page are scrolling to the unrelated section then you can fix those links.

**Comment by jimkosh** [comment]
@yeah, so asides from the links that take you to specific parts of the page, the links that redirect you to other pages automatically scrolls you to the middle of the page after it loads.
