### ISSUE TITLE
Link to OLE Github Repo Redirects out of First-Step page

### ISSUE THREAD

**Issue by jimkosh** [open-learning-exchange/open-learning-exchange.github.io#1987]
### Problem
For the introductory steps, clicking the github links in the paragraph below should open them in new tabs since there is no way redirect back into the "first steps" page, except to click back.  The __Open Learning Exchange's github.io__ redirects you out of the website.

>2. Create a GitHub account then watch __Open Learning Exchange's github.io__ repo and Follow Leonard and Dogi on GitHub. In GitHub, we "Watch" organization repositories and "Follow" individuals. Look for the "Watch" button at the top right of the page when you are in a repository. Also, follow each other to see what others in the group are doing. (Click on the image to enlarge.)  

### Steps to reproduce the problem

1.) Click the __Open Learning Exchange's github.io__  link (step 0), and note that it redirects you out of the website.

### Screenshots

N/A

### Proposed solution

Add a "target ="_blank" attribute to the anchor tag.

**Comment by lmmrssa** [comment]
@jimkosh Yes you can add `_blank` tag if it is taking to different page. If its the same page anchor then don't change those.
