### ISSUE TITLE
Emojis not displayed in rawgit files

### ISSUE THREAD

**Issue by aakarnik** [open-learning-exchange/open-learning-exchange.github.io#1991]
I have seen quite a few interns, including myself, come across this issue while creating the profile - markdown emojis do not show up in the Rawgit files.

### Steps to reproduce the problem
NA

### Screenshots
NA

### Proposed solution
Creating a note in Step 3 on the [Github and Markdown page](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md) mentioning this. 

P.S. Any virtual interns completing the First Steps are free to address this issue.

**Comment by demuze28** [comment]
I experienced this problem as well, I found that copying the actual emoji instead of the markdown code works.

**Comment by leahphuong** [comment]
@demuze28  yup that's what I did too!

**Comment by VishalSundarrajan** [comment]
@demuze28 Thanks for that. I think it'll be useful for others if mentioned in http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md

**Comment by aakarnik** [comment]
@VishalSundarrajan you can complete this pr. It can be one of the issues you complete for the first steps.
