### ISSUE TITLE
Couple of weird markdown images in vi-github-and-markdown.md

### ISSUE THREAD

**Issue by VishalSundarrajan** [open-learning-exchange/open-learning-exchange.github.io#1997]
### Problem
While the other images are just as fine to click on it to expand, there are two images under Markdown section that actually reduces its size after clicking on it. (Tag line also says 'Click to expand' but it does not).

### Steps to reproduce the problem

Click on the image to see the blurring/shrunk image. This happens only to two images in the markdown section. 

### Screenshots

N/A

### Proposed solution

I suggest three improvements (3rd is optional):
1. Better format all the texts inline so that users could see image without having to expand or click. 
2. 'Click to expand' is totally misleading (must be removed). 
3. Replace the image with a better one or the same with increased dimensions.

**Comment by lmmrssa** [comment]
Click to expand is ok. Also image has not shrunk down its actual size is same so it looks smaller when going full screen. We can replace it with larger picture if experience is not good.

**Comment by VishalSundarrajan** [comment]
@lmmrssa I checked the source but the can't find the original image. Also I find that click to expand is misleading if not replaced by a larger image.
