### ISSUE TITLE
Issue with Space (%20) urlencode link address for Virtual Intern Quiz page in Firefox browser

### ISSUE THREAD

**Issue by davidnhem** [open-learning-exchange/open-learning-exchange.github.io#1998]
PC environment:
OS: Windows 10 64-bit
Firefox Quantum: 61.0.1 (64-bit)

### Problem
The urlencode %20 converts to space in the browser link address box after user enters the page. Therefore, the resulted page displays blank contents. 

### Steps to reproduce the problem
1. Go to community Home Page.
2. Click on Virtual Interns (0/12) in My Courses Progress

### Screenshots
![image](https://user-images.githubusercontent.com/26916281/43641921-4af0a3c0-96da-11e8-95e0-08afc86608ce.png)

![image](https://user-images.githubusercontent.com/26916281/43641967-77362770-96da-11e8-9c6a-959956d656b0.png)

### Proposed solution

N/A

**Comment by nadaa** [comment]
Thanks @davidnhem , I tried but the content appears. Which browser do you use?
