### ISSUE TITLE
Add description to Tech Genius "support" page

### ISSUE THREAD

**Issue by demuze28** [open-learning-exchange/open-learning-exchange.github.io#2001]
### Problem

The tech genius support page (http://open-learning-exchange.github.io/#!pages/techgenius/tg-introduction.md) is extremely empty and I think we should start adding stuff to it.

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

I think it would be a good idea to properly introduce tech geniuses by giving a brief description as to what exactly a tech genius is and does.

**Comment by lmmrssa** [comment]
This page is not introduction of Tech Genius instead its the home page for support of Tech genius. If there is any stuff that will explain Tech Genius support then please go ahead.
