### ISSUE TITLE
Add a warning for destroy command

### ISSUE THREAD

**Issue by VishalSundarrajan** [open-learning-exchange/open-learning-exchange.github.io#2003]
### Problem

Readers should be warned of `vagrant destroy` command. This is added under vagrant commands but it is appropriate to be added as a note or warning so that to be wary before executing this command.

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

An additional note or warning is required in the vagrant command section about `vagrant destroy`.

**Comment by lmmrssa** [comment]
Detail of command already mention that it deletes virtual machine completely. You can highlight delete completely term so that it gets more focus.

**Comment by VishalSundarrajan** [comment]
Is it not the case that you have to reconfigure your bell community once after `vagrant destroy` command.
