### ISSUE TITLE
Categories issue

### ISSUE THREAD

**Issue by sorensht** [open-learning-exchange/open-learning-exchange.github.io#2014]
It is  little difficult scrolling through the steps, programs such as vagrant and docker. It is little complicated for the beginners.

###  Some of the problems that i think that can be solved are:
* By properly arranging the steps and making it more reliable for users.
* Even uploading guide videos to make much more understaning.
* Making good interface with the contents and making it more attractive and pointing the important words that may be useful.

### Screenshot of the problem:

![issue](https://user-images.githubusercontent.com/41897876/44337301-e85a8c80-a499-11e8-8c48-b50190c2fbe5.png)

**Comment by inDepthh** [comment]
I think that the categories can be made more attractive. In my opinion, they are clear and easy to understand despite how good they look. Its appearance is part of the theme that the whole page has. Changing that theme would not be a bad idea. Can you pleases explain how they can be more reliable or arranged? "...properly arranging the steps and making it more reliable for users."

**Comment by YuserahN** [comment]
@sorensht Can you provide a few examples?
