### ISSUE TITLE
Troubleshooting Categories

### ISSUE THREAD

**Issue by lawliet1997** [open-learning-exchange/open-learning-exchange.github.io#2015]
This is the issue i found in the Troubleshooting portion of BeLL Installation from the Step 1 section 1. As the installation of Bell is categorized in Windows, Mac Os and Ubuntu. Although the installation is categorized, the troubleshooting portion is not.

![issue](https://user-images.githubusercontent.com/41874655/44336690-fa3b3000-a497-11e8-886b-229ea0d6120c.png)

### Proposed solution
I think the Troubleshooting portion below the installation portion should also consist of Categories as per the:

1. Windows Troubleshooting
2. Mac OS Troubleshooting and
3. Ubuntu Troubleshooting

And under the Windows Troubleshooting, all Troubleshooting of Windows, under MacOS Troubleshooting, all the Troubleshooting of Mac OS and Ubuntu Troubleshooting, all the Troubleshooting of Ubuntu should be listed properly. 

I hope to get the positive response from you guys. This is just a minor issue but would help the coming interns to understand the Troubleshooting process more easily. 
Thank You!

**Comment by janamr** [comment]
This could be helpful, as I’ve added an issue #2038 with additional troubleshooting for mac, making 2 troubleshooting bulletpoints for mac, and 2 already existing for Windows. Would be easier on the eyes and brain; better organized.
