### ISSUE TITLE
Docker log

### ISSUE THREAD

**Issue by lawliet1997** [open-learning-exchange/open-learning-exchange.github.io#2016]
### Problem
During the installation of planet in step 2. The user are not fully aware when to press Ctrl+ c to stop the logs. 

### Proposed solution
The user needs to press Ctrl+z only when the certain code is seen in the screen as in the screenshot below:

![issue 1](https://user-images.githubusercontent.com/41874655/44394481-03d79d00-a557-11e8-91ed-378eccc95011.jpg)

After seeing this screenshot, the user can press Ctrl+c then move on to the next process.

**Comment by lmmrssa** [comment]
Looks good but breaking command is Ctrl+C not Z

**Comment by janamr** [comment]
@lmmrssa shall I begin a pull request for this change?
