### ISSUE TITLE
Docker toolbox IP issue

### ISSUE THREAD

**Issue by sorensht** [open-learning-exchange/open-learning-exchange.github.io#2017]
During installation of the docker there are two method of installing the docker as shown in the step 2.
So if the docker is running without the docker toolbox then the given IP (http://127.0.0.1) in the planet configuration will run. 
 
However if you are using the docker tool box then the above IP address will not open. So we should use the IP address given by the docker tool box as in the screenshot below:
![error](https://user-images.githubusercontent.com/41897876/44395016-59607980-a558-11e8-90f0-ab147fc52cd2.PNG)

NOTE: It is only applicable if you are using docker toolbox on windows.

This note should  be added while configuration of the planet.

**Comment by lmmrssa** [comment]
Please add the note on that it is only applicable if using docker toolbox on windows.
