### ISSUE TITLE
No proper Explanation

### ISSUE THREAD

**Issue by lawliet1997** [open-learning-exchange/open-learning-exchange.github.io#2023]
### Problem
In Step 6 - Github Issues, after creating a branch there is no proper explanation on how to make changes into the PC/laptop of a user. Since all the begineer intern may not be expert, they may get lost with no guidance presented on how to make changes in the laptop of a user. I had faced the same problem thus, this issue was born.

### Proposed solution
What i want to propose is that there should be separate Title "**Changes in your end**". And then display step wise process of where the path is of the changes that the vi should make in their laptop.

### Screenshot 

![New Title](https://user-images.githubusercontent.com/41874655/44977500-ec9da400-af87-11e8-8501-e15f24ba07a3.png)

**Comment by nadaa** [comment]
I see what you mean @lawliet1997.  Actually, the page contains most of the required information to start with Git, maybe it needs reorganizing.

What kind of "changes in laptop" you made?
For me, I just created a directory and then clone the OLE repo to it.

**Comment by jazdao** [comment]
I also think that this could be a good idea.  The line telling you to make changes to your local files does sum up the next step, but maybe it could be made more specific?  For example- how to access your local repository on your computer, how to find the specific files to be changed (file name and URL of the page?), and perhaps what kind of IDE to use to make the changes.

**Comment by lmmrssa** [comment]
@jazdao there is already a link that will take you to github page for details about using git.
Regarding changing which file it depends on issue one will work on. For IDE different developers have their own preferences.
