### ISSUE TITLE
Github Issues Step 6 and Step 8 

### ISSUE THREAD

**Issue by lawliet1997** [open-learning-exchange/open-learning-exchange.github.io#2024]
### Problem
This is not much of an issue but a way to simplify the first step page. 

### Screenshots
![step 6 and 8 merge](https://user-images.githubusercontent.com/41874655/45088370-7e441780-b128-11e8-9bc9-0fbf89047aee.png)

### Proposed solution
Since Step - 6 and Step - 8 are almost same. We can combine both steps into one and have the vi to create 4 issues and 4 merge pull requests in the step 6 itself that will reduce the one step from the whole first step and simplifies the page.

**Comment by svlesiv** [comment]
Thumb up from 'not yet intern';) I also think that it will simplify the first step page avoiding content repetition.

**Comment by lmmrssa** [comment]
@lawliet1997 @svlesiv It will be nice if you can provide which portions do you want to combine into one. We want context to be descriptive enough so new person can understand on own.

**Comment by cquarte1** [comment]
I was thinking the same thing. I had to go back so many times to make sure I under step 6 and 8.
