### ISSUE TITLE
Upload Resources

### ISSUE THREAD

**Issue by sorensht** [open-learning-exchange/open-learning-exchange.github.io#2025]
## Problem
Uploading different media like audio and video is shown in  the upload resources section. It has just guided how to upload it. As for the beginners they may get doubts on it.  

## Solution
 For the beginners there should be mention about the use of it like what can we do with this audio and videos. There should be a little more guide on it.

![resource](https://user-images.githubusercontent.com/41897876/45088812-e1827980-b129-11e8-85b4-8c8111a43d66.png)

**Comment by lmmrssa** [comment]
@sorensht This is just step to make you familiar with what you can do with application.
