### ISSUE TITLE
Planet installation failure on mac

### ISSUE THREAD

**Issue by janamr** [open-learning-exchange/open-learning-exchange.github.io#2026]
### Problem
Errors in the terminal while installing Planet; no solution from Google was able to solve the problem. Posted the problem in the chat and got various answers, one of which worked. 
One suggestion was to create folder /etc/planet as well as add it under shared folder of docker app; however as a newbie more information would have been helpful - I created this folder in two separate (wrong?) locations but this didn't solve the problem.
I could not move forward with my "First Steps" until this issue was solved.

### Steps to reproduce the problem
- Install Docker first time on macOS High Sierra
- Follow steps to install Planet on mac

### Screenshots
<img width="1258" alt="screen shot 2018-08-29 at 1 44 28 pm" src="https://user-images.githubusercontent.com/13737915/45132887-9f285f00-b160-11e8-96d5-226162d46f34.png">
<img width="671" alt="screen shot 2018-08-30 at 7 38 41 am" src="https://user-images.githubusercontent.com/13737915/45132978-faf2e800-b160-11e8-9905-04ee50368f0d.png">
<img width="820" alt="screen shot 2018-09-05 at 10 26 45 pm" src="https://user-images.githubusercontent.com/13737915/45132983-0219f600-b161-11e8-834b-11d2c531424b.png">

### Proposed solution
This extra step (of removing a line of code or adding the folder in Docker) should be included in detail in either "Install Docker" or "Planet Installation" instructions. What worked for me was editing the planet.yml file and removing the line starting with - "/etc/planet

**Comment by lmmrssa** [comment]
@janamr If you change /etc/planet to /Users/<username>/planet all places then it will just work. This will still have the volume mounted. So make this note for Mac OS. <username> should be your username. you can check it by `cd ~` and then `pwd`. This will give the path

**Comment by janamr** [comment]
Thanks @lmmrssa should I create a pull request and make these changes? I am a bit confused on the next steps here..

**Comment by lmmrssa** [comment]
Sure @janamr please do.
