### ISSUE TITLE
Bell my app issue

### ISSUE THREAD

**Issue by sorensht** [open-learning-exchange/open-learning-exchange.github.io#2027]
### Problem

In this bell my app we are asked to sync the my bell app with the nation. After the sync it does not show whether its synced or not. If we again try to sync it repeats the same process of syncing.

### Solution

If bell my app is already synced then there should be displayed a message "already synced" in the the option sync with nation

![syncc](https://user-images.githubusercontent.com/41897876/45167851-bf682480-b219-11e8-9287-3aad254d5cd2.png)

**Comment by lmmrssa** [comment]
@sorensht This issue is not related to open-learning-exchange First Steps so closing it here
