### ISSUE TITLE
useful link issue

### ISSUE THREAD

**Issue by sorensht** [open-learning-exchange/open-learning-exchange.github.io#2028]
### Problem
The links given in the useful links in the nation bell is very useful for the previous steps  so the beginners cannot get those links until they reach the steps to nation bell.

### Solution
The link should be provided in above  steps so that the beginners can get more information about it.

![crop](https://user-images.githubusercontent.com/41897876/45169244-e2480800-b21c-11e8-83d1-fd2649519b4a.png)

**Comment by nadaa** [comment]
Thanks, @sorensht. I think useful links is used for someone who couldn't understand from the OLE tutorial. So, they can follow the provided steps first, then if they want to understand deeply, they go further with other GitHub resources.
