### ISSUE TITLE
Links for screenshots

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/open-learning-exchange.github.io#2032]
### Problem
Might be not very clear how many and how often screenshots need to be posted in the Gitter chat.

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Create links to the Gitter chat at the end of each page, as a reminder to send a screenshot, where it needed.

**Comment by lmmrssa** [comment]
@svlesiv Yes please mention any pages where screenshot is not asked for and make that portion linked to gitter channel instead of separate link of gitter on bottom of each page.

**Comment by svlesiv** [comment]
@lmmrssa On pages [BeLL Configurations](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations.md) and [Planet Installation and Configuration](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-and-configuration.md) Gitter chat can be highlighted as a link. Also, specific phrases for the chat can be added. 
### BeLL Configurations
![bell](https://user-images.githubusercontent.com/35533801/45527033-b93cef80-b7a7-11e8-9bed-1a10cff767f4.jpg)

### Planet Installation and Configuration
![planet](https://user-images.githubusercontent.com/35533801/45527048-c35eee00-b7a7-11e8-9e68-f50a004e6b27.jpg)

**Comment by lmmrssa** [comment]
@svlesiv Yes please add the links to it but for message may be we should let them write on their own. That will improve their communication instead of giving them fix thing they copy paste. We may instead say post screenshot and inform the team.
