### ISSUE TITLE
NOTE icon

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/open-learning-exchange.github.io#2033]
### Problem
UX design.

### Steps to reproduce the problem
N/A

### Screenshots
![note](https://user-images.githubusercontent.com/35533801/45373890-84217900-b5be-11e8-91e9-8d892b2b1a01.png)

### Proposed solution
Substitute word NOTE to an icon.

**Comment by lmmrssa** [comment]
@svlesiv Right now highlighted box is supposed to be UX presentation of **NOTE** If you have better presentation then please do send screenshot or rawgit of how it will display so we can decide on implementation.

**Comment by svlesiv** [comment]
@lmmrssa and @dogi, it might look something like this:
![icon](https://user-images.githubusercontent.com/35533801/45766227-0df7c480-bc05-11e8-8b9e-1b3375ac9390.jpg)

Design of the icon can be different. If this issue will be approved, I either find a free icon or make one by myself.

**Comment by lmmrssa** [comment]
@svlesiv that looks good

**Comment by svlesiv** [comment]
@lmmrssa Thank you, I will be working on it.

**Comment by svlesiv** [comment]
I tried to incorporate an icon into markup, but after some research, I found that word 'Note' is essential to make a note (Gimmicks alert). I'm closing the issue.
