### ISSUE TITLE
Consistency between articles

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/open-learning-exchange.github.io#2034]
### Problem
Absence of section 'Objectives' in Step 1 and Step 2 articles.

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Add 'Objectives' section in Step 1 and Step 2 articles to be consistent with the articles from the next Steps.

**Comment by lmmrssa** [comment]
Could you please point to the page. I don't see Objectives on steps of Getting Started.

**Comment by janamr** [comment]
@svlesiv @lmmrssa some examples:
<img width="1202" alt="screen shot 2018-09-19 at 1 01 08 pm" src="https://user-images.githubusercontent.com/13737915/45769060-7b5b2380-bc0c-11e8-9de1-4b8903ea1dca.png">

<img width="1203" alt="screen shot 2018-09-19 at 12 58 39 pm" src="https://user-images.githubusercontent.com/13737915/45769005-54045680-bc0c-11e8-829e-827db658b3b1.png">
<img width="1213" alt="screen shot 2018-09-19 at 12 58 20 pm" src="https://user-images.githubusercontent.com/13737915/45768961-3afba580-bc0c-11e8-9bc3-c5fb723d4b88.png">

**Comment by lmmrssa** [comment]
@janamr Sure we will have these on individual pages. But don't get about Objectives on Step 1 and Step 2 as they are on First Step page which is overview of all steps and we don't have Objectives there

**Comment by svlesiv** [comment]
@lmmrssa I can add objectives to the next pages:
1. [BeLL Installation](http://open-learning-exchange.github.io/#!./pages/vi/vi-bell-installation.md)
## Objectives
* Set up an environment for Bell
* Install Community Bell

2.[Vagrant Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md)
## Objectives
* Learn about Vagrant
* Learn Vagrant commands 

3.[Planet Installation and Configuration](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-and-configuration.md)
## Objectives
* Install Docker
* Install and configure Planet
* Let us know in Gitter chat

4.[Docker Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md)
## Objectives
* Learn about Docker and Docker Compose
* Learn Docker and Docker Compose commands
