### ISSUE TITLE
repetitive content 

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/open-learning-exchange.github.io#2035]
### Problem
On the First Steps page description of Step 6 might be too long.

### Steps to reproduce the problem
N/A

### Screenshots
![screen shot 2018-09-12 at 5 08 11 pm](https://user-images.githubusercontent.com/35533801/45453448-d346d700-b6ae-11e8-8fa2-8d07d901e11d.png)

### Proposed solution
Reduce the amount of repetitive content.

**Comment by lmmrssa** [comment]
@svlesiv Content seems to be descriptive and looks ok. If you have any suggestion how we can reduce its size then please do post it.

**Comment by svlesiv** [comment]
@lmmrssa Please take a look if a short version of Step 6 description delivers the main points without cutting useful information. 

## Step 6 - GitHub Issues Tutorial

Follow the tutorial under the [GitHub Issues tab](vi-github-issues.md) to create at least one issue. Post a link in [Gitter](https://gitter.im/open-learning-exchange/chat) whenever you create an issue or when you comment on someone else's issue. You are encouraged to post as many issues as you can for improving the page as well as for personal practice. No issue is too big or too small to be filed and it is OK if you are not sure how to fix it yourself. If you know how to solve an issue, be sure to provide a detailed account of your research and show how to fix it. It is ok to file an issue about minor typos and very small changes, but do not make this the case for all of the issues that you file.

Make sure you have created at least one issue, resolved it, commented on an issue you didn't create and have a pull request with the fix merged before proceeding to the next step.
- Once you complete Step 6 you will have:
   * 2 pull requests made (one at step 3 and one at step 6)
   * 1 comment added (on an issue you didn't create)
   * 1 issue created

**Comment by lmmrssa** [comment]
@svlesiv looks good one of missing point is about working with any issue that you haven't created. If you add that it should be good

**Comment by svlesiv** [comment]
@lmmrssa and @dogi,  please take a look on an updated version. 
Let me know if you would like to make this change or leave the original description of Step 6 as it is.

## Step 6 - GitHub Issues Tutorial

Follow the tutorial under the [GitHub Issues tab](vi-github-issues.md)  to create at least one issue. Post a link in [Gitter](https://gitter.im/open-learning-exchange/chat) whenever you create an issue or when you comment on someone else's issue. You are encouraged to post as many issues as you can for improving the page as well as for personal practice. No issue is too big or too small to be filed and it is OK if you are not sure how to fix it yourself. If you know how to solve an issue, be sure to provide a detailed account of your research and show how to fix it. It is ok to file an issue about minor typos and very small changes, but do not make this the case for all of the issues that you file. You can also work on issues that you didn't create.

Make sure you have created at least one issue, resolved it, commented on an issue you didn't create and have a pull request with the fix merged before proceeding to the next step.

- Once you complete Step 6 you will have:
   * 2 pull requests made (one at step 3 and one at step 6)
   * 1 comment added (on an issue you didn't create)
   * 1 issue created

**Comment by lmmrssa** [comment]
@svlesiv yes you can go ahead with this
