### ISSUE TITLE
Addition to Step 1 - Troubleshooting VirtualBox Install

### ISSUE THREAD

**Issue by janamr** [open-learning-exchange/open-learning-exchange.github.io#2038]
### Problem
Step 1 - BeLL Installation - troubleshooting for macOS at `brew cask install virtualbox`
I spent a couple days troubleshooting this issue - so it would be good for future interns to know.
See screenshots below for error message.

### Steps to reproduce the problem
Install VirtualBox on macOS High Sierra

### Screenshots
<img width="1440" alt="screen shot 2018-08-28 at 12 47 40 pm" src="https://user-images.githubusercontent.com/13737915/45773849-6fc22980-bc19-11e8-8b54-dd172ad07e49.png">
<img width="879" alt="screen shot 2018-08-28 at 12 18 41 pm" src="https://user-images.githubusercontent.com/13737915/45773859-7b155500-bc19-11e8-91f8-f98a10f3d3b1.png">

### Proposed solution
What worked for me eventually: Continually ejecting the program and clicking "Allow" in `System Preferences > Security & Privacy` as suggested in [this thread](https://apple.stackexchange.com/questions/301303/virtualbox-5-1-28-fails-to-install-on-macos-10-13-due-to-kext-security)
This should be added to Troubleshooting section under macOS.

**Comment by lmmrssa** [comment]
@janamr Please add it under VM installation
