### ISSUE TITLE
Grammatical improvements 

### ISSUE THREAD

**Issue by janamr** [open-learning-exchange/open-learning-exchange.github.io#2040]
### Problem
Incorrect grammar can be confusing and misleading.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="924" alt="screen shot 2018-09-19 at 12 31 44 pm" src="https://user-images.githubusercontent.com/13737915/45775969-6a67dd80-bc1f-11e8-8730-2104d0232f21.png">

### Proposed solution
Fix the errors in Step 1. Example fixed paragraph (shown above in screenshot):
This is caused when VirtualBox gets a minor version update (i.e. 5.0.x -> 5.1.x or 5.1.x -> 5.2.x). 
There are some old unused modules, which are not compatible with the newer version. They remain installed, which causes the above problem and prevents VirtualBox from starting.

**Comment by nadaa** [comment]
@janamr, thanks for catching this mistakes. I agree the grammar is important, but sometimes learner won't realize it while focusing on the meaning.

**Comment by svlesiv** [comment]
@janamr,  I'm not an intern yet, but I think this is a good issue to work on.

**Comment by lmmrssa** [comment]
@janamr it looks good to work on.

**Comment by janamr** [comment]
Thanks for your comments @lmmrssa @svlesiv @nadaa 
Will work on this now!

**Comment by simily00** [comment]
Another typo:

![typo](https://user-images.githubusercontent.com/17802123/46386194-e711a780-c674-11e8-9811-4e1ff8e093c0.jpg)

**Comment by janamr** [comment]
Thanks @simily00 I've corrected that one as well !
