### ISSUE TITLE
Edit commit message after push

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/open-learning-exchange.github.io#2041]
### Problem
Users may want to fix mistakes in a commit after push.

### Steps to reproduce the problem
N/A

### Screenshots
![1](https://user-images.githubusercontent.com/35533801/45776033-a8650180-bc1f-11e8-9545-a9c337dd59c6.jpg)

### Proposed solution
Based on StackOverflow solution, add that solution to the page which describes how to create a commit.

**Comment by lmmrssa** [comment]
@svlesiv Commit edit and Force push might cause issues for beginner's so we didn't introduced it. Also we have given more details on https://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#Helpful_Links

**Comment by svlesiv** [comment]
@lmmrssa Alright, thank you. I will try to think about some other issue. I'm closing this one.
