### ISSUE TITLE
Write about powershell upgrade 

### ISSUE THREAD

**Issue by nadaa** [open-learning-exchange/open-learning-exchange.github.io#2046]
### Problem
  In step1 *BeLL and Vagrant*, running Vagrant requires Powershell version 3. In case you have a lower version, the installation will stop. 

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
I propose to add more details about how to update PowerShell to version 3, and it can be added under the Troubleshooting section.

**Comment by lmmrssa** [comment]
You can add it under troubleshoot. Also add a link under Windows installation to take it to troubleshoot
