### ISSUE TITLE
Confusing paragraph in step 4

### ISSUE THREAD

**Issue by nadaa** [open-learning-exchange/open-learning-exchange.github.io#2047]
### Problem
I found a confusing paragraph in step 4 about taking a screenshot, please check the image below.
Why do we need to remind the learner about the previous step?
Also, this section is about BeLL apps tutorial, and the previous step is about Planet configuration, which causes a confusion.

### Steps to reproduce the problem
N/A

### Screenshots
![](https://i.imgur.com/GDFcCVk.png)

### Proposed solution
Remove the paragraph.

**Comment by lmmrssa** [comment]
@nadaa its not planet configuration. Configuration is related to BeLL-Apps previously created. Please change the words instead so that it is clear to configuration screenshot is of BeLL-Apps
