### ISSUE TITLE
Clarifying common names used in git (step 5)

### ISSUE THREAD

**Issue by nadaa** [open-learning-exchange/open-learning-exchange.github.io#2052]
### Problem
Git has many terms  (eg. master, origin, upstream, ..etc), understanding their meaning is essential to understand Git workflow. 

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Adding a list of Git terms with their meaning at the top before "start here"

**Comment by lmmrssa** [comment]
@nadaa words you mentioned are generally used values not terms of git
`master`: `branch`
`origin` `upstream`: `remote`
And its not rule that these needs to be used you can use any branch name or remote name.
So adding meanings does not sound right. Instead if you want it to be easier for user then you can provide how we are using these values.
So put a note that these are generally used values for workflow which does not mean it always needs to be used, there could be different values used on different projects

**Comment by nadaa** [comment]
Thanks @lmmrssa for clarifications. Yes, I agree with you, I will do it.
