### ISSUE TITLE
Better organization of GitHub Issues article (Step 6) 

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/open-learning-exchange.github.io#2053]
### Problem
GitHub Issues article has too many headers which can be overwhelming for the reader.

### Steps to reproduce the problem
N/A

### Screenshots
![step_6](https://user-images.githubusercontent.com/35533801/45957654-85519d80-bfe3-11e8-9649-eedbb70ad538.jpg)

### Proposed solution
Reorganize content, substitute some headers to subheaders and make emphasis on the main points of the article.

The structure can be next:
# GitHub Issues
## Create a New Branch
* Preview Changes Locally
## Create a Commit and Push the Changes
* Commit Message Style Guide
* Rawgit
   * Rawgit Generator
## Useful Links

**Comment by lmmrssa** [comment]
@svlesiv looks good

**Comment by svlesiv** [comment]
@lmmrssa, thank you. I will be working on it.
