### ISSUE TITLE
Unclear steps of sync Bell-Apps with Nation

### ISSUE THREAD

**Issue by nadaa** [open-learning-exchange/open-learning-exchange.github.io#2056]
### Problem
I tried to follow the steps in step 7(Nation BeLL), but I got an error when I click on sync with the nation.
Besides, the text is not clear how to know if the sync went well or not. What I suppose to see in the Nation after successfully send the update from my community.

### Steps to reproduce the problem
N/A

### Screenshots
![](https://i.imgur.com/9dXtiZl.png)

### Proposed solution
First, I need to fix why the sync with nation doesn't work, then specify clearly how to check if the updates were sent successfully to the Nation or not.

**Comment by jazdao** [comment]
I've also had some problems with Step 7.  I think that a lot of the instructions and screenshots for the Planet are outdated, or don't provide quite enough information to confirm whether you succeeded or not...
