### ISSUE TITLE
Add about renaming ole repo (step3)

### ISSUE THREAD

**Issue by nadaa** [open-learning-exchange/open-learning-exchange.github.io#2059]
### Problem
In step 3 (Markdownand GitHub), interns need to rename their ole repo after forking using their GitHub usernames, but if they already in use. 

### Steps to reproduce the problem
N/A

### Screenshots
![](https://i.imgur.com/N48pj6R.png)

### Proposed solution
I found the solution is already in FAQ, Q16. I suggest mentioning this in step 3 by adding a link.

**Comment by svlesiv** [comment]
Hi @nadaa, I also had the same problem with renaming. I think this is a good idea to add a link to the page with a solution to the problem.

**Comment by lmmrssa** [comment]
Sure @nadaa add a link for troubleshoot which states if you have issue please look into Step16 of FAQ
