### ISSUE TITLE
'Git Repositories' spelling and grammar corrections

### ISSUE THREAD

**Issue by mwweber** [open-learning-exchange/open-learning-exchange.github.io#206]
I am suggesting the following high priority changes to clarify and correct some areas of the 'Git Repositories' page. The next step (for which I will make a separate issue) will be to make the instructions a little more clear by focusing on paragraph structure and general layout.

> Normally, we do not rename but as Markdown wikis are slightly different, we renamed in the repository in that example.

We do not typically rename repositories, but Markdown wikis are slightly different.
(_More concise_)

> You will use whichever URL you need to clone the proper repository; you will obviously not type mine.

Be sure to use the correct URL to clone your repository (you will obviously not type my username).
(_Clarified "whichever", "proper", and "mine"_)

> You know have

You now have

> three different levels of GitHub repositiory:

three different Github repository levels:
(_Grammar and spelling_)

> you will need to update the fork continuously so that your fork and clone are not behind.

you will need to frequently update the fork so that your fork and clone are not behind.
(_Clarified "continuously"_)

**Comment by DrewPerlman** [comment]
Nice finds @mwweber, I agree with all of these corrections.
However, I think the "know" to "now" typo has already been fixed. Sync your fork with the main project so the change is reflected in your repo.

**Comment by mwweber** [comment]
Thanks @DrewPerlman. After about 5 hours of wrestling with git (and going down the rabbit hole of errors with vim, rebasing, remotes, etc), I finally fixed the page and submitted a pull request.

**Comment by DrewPerlman** [comment]
Awesome job @mwweber! Definitely let me know if you're having troubles with git in the future, I or someone else on the team will for sure be able to help you out so it's not too much of a hassle.
