### ISSUE TITLE
How to sync Planet online

### ISSUE THREAD

**Issue by davidochiel** [open-learning-exchange/open-learning-exchange.github.io#2069]

**Comment by tommyprevatt** [comment]
Hey! I'm not sure if you accidentally commented out the details of this issue, but there is nothing showing. Maybe you should check and see if your details are commented out?

**Comment by inDepthh** [comment]
@davidochiel You should outline the exact issue that you are having. You did not add any information to this issue. I was able to sync planet with no issue by following the instructions. What exactly is not working for you?

**Comment by davidochiel** [comment]
@inDepthh kindly send me the link

**Comment by inDepthh** [comment]
The first steps were updated here

https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-first-steps.md

**Comment by YuserahN** [comment]
Which step is this in?

**Comment by coder8102** [comment]
> Which step is this in?

Under "Step 7 - Nation Planet"
