### ISSUE TITLE
Various broken links through out site

### ISSUE THREAD

**Issue by simily00** [open-learning-exchange/open-learning-exchange.github.io#2079]
### Steps to reproduce the problem
n/a

### Screenshots
*Under Contributors/Orientation tab
![brokenlinkspt2 1](https://user-images.githubusercontent.com/17802123/47958695-aff12780-df8d-11e8-8029-582521b116d4.jpg)

![scroll down page until you arrive at the _review pull request and issues1](https://user-images.githubusercontent.com/17802123/47958711-15451880-df8e-11e8-9abf-86161621f34f.jpg)

![reviewd](https://user-images.githubusercontent.com/17802123/47958650-9bf8f600-df8c-11e8-947e-ba2f6ef06186.jpg)

### Proposed solution
update the links

**Comment by simily00** [comment]
Various inactive links that need updating. (..more on the way)

**Comment by lmmrssa** [comment]
* http://talk.ole.org is working might have been down for sometime
* https://gitter.im/open-learning-exchange/standup is valid link you will not be able to get it until you are part of it as its private channel. After you are enrolled as VI then only you are added here.

All of your errors seem to be these links which are valid.

For the last link it is not valid link, it the sample link which shows how link of PR will be. Virtual intern is supposed to look for similar link for PR he/she create

@simily00  Hope this clear your confusion. Closing this issue.

**Comment by simily00** [comment]
@lmmrssa Clear! Thanks!
