### ISSUE TITLE
Minor clarification fix

### ISSUE THREAD

**Issue by simily00** [open-learning-exchange/open-learning-exchange.github.io#2085]
### Problem
Clarification on which account to login to

### Steps to reproduce the problem
Nation Bell Section:
![screen shot 2018-11-08 at 4 34 31 pm](https://user-images.githubusercontent.com/17802123/48240260-15c32200-e387-11e8-92f6-1e30dc4cf211.jpg)

### Screenshots
![screen shot 2018-11-08 at 4 46 24 pm](https://user-images.githubusercontent.com/17802123/48240266-1d82c680-e387-11e8-8fb5-582e510d33bd.jpg)

### Proposed solution
![new 2fold](https://user-images.githubusercontent.com/17802123/48240275-2a9fb580-e387-11e8-8eee-f96013c06317.jpg)

**Comment by lmmrssa** [comment]
instead of just saying dummy account, make it *dummy account you just created*

**Comment by simily00** [comment]
> instead of just saying dummy account, make it _dummy account you just created_
Will do!

**Comment by simily00** [comment]
> instead of just saying dummy account, make it _dummy account you just created_
Will do!

**Comment by simily00** [comment]
@lmmrssa I didn't italicize, shall I go back in and change it?
