### ISSUE TITLE
Minor clarification #2 fix 

### ISSUE THREAD

**Issue by simily00** [open-learning-exchange/open-learning-exchange.github.io#2086]
### Problem
Instructions lack some direction.

### Steps to reproduce the problem
Nation BeLL:
Section near the bottom of page~

### Screenshots
![screen shot 2018-11-08 at 6 57 36 pm](https://user-images.githubusercontent.com/17802123/48240645-68510e00-e388-11e8-9e0f-9fb58649cb7c.jpg)

### Proposed solution
![findname](https://user-images.githubusercontent.com/17802123/48240982-d21de780-e389-11e8-926e-00bf1dc46764.jpg)

Add, "find your name".

**Comment by lmmrssa** [comment]
Finally you should see a list of communities and the option to generate a report of community you created.

**Comment by simily00** [comment]
*Ignore previous commit
