### ISSUE TITLE
Update Vi-Nation.md

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/open-learning-exchange.github.io#2096]
Please change from line

> Then, click on "Communities" to access reports from various communities on the nation.

and replace it with content and images below

-----

Then, click on "Report Details" to access reports from various communities on the nation.
![vi-nation-sync](https://user-images.githubusercontent.com/2909490/48755250-d072ee80-ecbc-11e8-9b3a-74fa76586d2b.png)
Finally you should see a report of communities.
![screen shot 2018-11-15 at 21 43 09](https://user-images.githubusercontent.com/2909490/48755430-542cdb00-ecbd-11e8-8b4e-a18d6cfb84e9.png)

**Comment by simily00** [comment]
Currently working on fix.
