### ISSUE TITLE
Rewording a section in step 2

### ISSUE THREAD

**Issue by seanwu20** [open-learning-exchange/open-learning-exchange.github.io#2100]
### Problem

In the Planet Installation and Configuration page (Step 2, http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-and-configuration.md), under the Planet Installation section, step 3 asks us to "Clone the planet repository: git clone https://github.com/open-learning-exchange/planet.git".

We already cloned this repository in Planet Installation (Step 1, http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md).

Having the instructions like this may confuse users unfamiliar with GitHub and they may potentially clone the planet repository twice. 

### Steps to reproduce the problem

Check under the Planet Installation section
http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-and-configuration.md

Check under the Install a Community Planet section
http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md

### Screenshots

N/A

### Proposed solution

Change to something like "Go to the directory where you cloned the planet repository in step 1"

**Comment by svlesiv** [comment]
Hi @seanwu20, seems to be a good issue to work on.
