### ISSUE TITLE
First Steps: The Big Picture Faulty Link

### ISSUE THREAD

**Issue by scohen40** [open-learning-exchange/open-learning-exchange.github.io#2108]
The second paragraph of "The Big Picture" section, at the very beginning of the "First Steps" has a link what seems to be to show what current Virtual Interns are working on. However, it takes the user right back to the same page.
Here's a picture of the described issue:

<img width="947" alt="screen shot 2018-12-20 at 14 56 26" src="https://user-images.githubusercontent.com/19376710/50307843-7ace6500-0467-11e9-8aca-3b4e4bff17e6.png">

**Comment by scohen40** [comment]
The problem can be found here:

https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-first-steps.md#!./pages/robots/rbts-intern-orientation.md#Familiarize_Yourself_with_Current_Projects_and_Issues



Proposed solution:
* find a page of current projects being worked on by interns i.e. https://github.com/open-learning-exchange/myplanet
* replace the current link with a link to that page


###

**Comment by lmmrssa** [comment]
Link is working as expected. If you are looking it from open-learning-exchange.github.io then that link takes you to `http://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md#Familiarize_Yourself_with_Current_Projects_and_Issues` which has list of all projects.
