### ISSUE TITLE
Formatting issue with 'Install a Community Planet' section in Step 1.1

### ISSUE THREAD

**Issue by jazdao** [open-learning-exchange/open-learning-exchange.github.io#2111]
### Problem  
In [Step 1.1](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md) of [First Steps](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md), the **Install a Community Planet** section is a subsection under the **macOS or Ubuntu** section, which can make it confusing for Windows users.  

### Steps to reproduce the problem  

N/A

### Screenshots  

![issue1](https://user-images.githubusercontent.com/22950070/50456712-43e6cc00-090b-11e9-8c72-57214a5eacd7.JPG)
![issue2](https://user-images.githubusercontent.com/22950070/50456642-daff5400-090a-11e9-9cd0-f484bfbf822a.JPG)

### Proposed solution  

Isolate **Install a Community Planet** in its own section, or create a more divisive page for different operating systems.

**Comment by inDepthh** [comment]
👍
