### ISSUE TITLE
Navigation menu for First Steps 

### ISSUE THREAD

**Issue by jazdao** [open-learning-exchange/open-learning-exchange.github.io#2113]
### Problem  
When you scroll down to Step 9 in the [First Steps](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md), the navigation bar disappears to the top and remains there until you refresh the page.

### Steps to reproduce the problem

On the [First Steps](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) page, scroll down until you reach Step 9.

### Screenshots

**First Steps**
<img width="559" alt="issue1" src="https://user-images.githubusercontent.com/22950070/50494110-36e2df00-09d6-11e9-82d8-21ba217350ee.png">

**Other Pages**
<img width="557" alt="issue2" src="https://user-images.githubusercontent.com/22950070/50494118-42360a80-09d6-11e9-95ba-f0b75129e572.png">

### Proposed solution

Fix the styling for the navigation menu so that it hovers at your position on the page even after you have reached the bottom.

**Comment by empeje** [comment]
I don't get it, somehow I can't replicate or I can't understand the issue @jazdao

**Comment by jazdao** [comment]
@empeje It seems to happen no matter what browser I use, and only on the First Steps page.  I don't have any other devices to check it on though, so it might be a unique issue.  Here's a [screen recording](https://drive.google.com/open?id=1PtkaeHtZ6jomCDHzwTKam8dtJenF3Rxt).

**Comment by zelmi** [comment]
@jazdao This doesn't seem a problem for me. I use both *Firefox* and *Safari* on Mac and they work fine. I also notice that this issue is from a while back but cannot find a pull request that has fixed it. Are you still seeing the problem?

**Comment by lmmrssa** [comment]
closing this issue as it seems to be working fine.
