### ISSUE TITLE
Clarify Planet Configurations in Steps 1.2 and 2.1

### ISSUE THREAD

**Issue by jazdao** [open-learning-exchange/open-learning-exchange.github.io#2114]
### Problem  
In the [First Steps](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md), you are asked to configure your Planet in both [Step 1.2](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md) (Vagrant) and [Step 2.1](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-and-configuration.md) (Docker).  Since the steps are so similar, it is unclear whether or not you are supposed to create another admin account to register your community Planet in 2.1.

### Steps to reproduce the problem

N/A

### Screenshots

**1.2 - Planet Configurations (Vagrant)**  
![issue1](https://user-images.githubusercontent.com/22950070/50503038-bee9d880-0a18-11e9-90ce-d73e87ec3bd1.JPG)

**2.1 - Planet Installation and Configuration (Docker)**
![issue2](https://user-images.githubusercontent.com/22950070/50503049-d88b2000-0a18-11e9-927d-841ae2568e99.JPG)

### Proposed solution

Clarify whether or not the instructions from 1.2 should be repeated in 2.1 when configuring the Planet.  If so, either omit the repetitive information and link back to 1.2, or acknowledge that certain instructions should be repeated and emphasize any additional information.  If not, remove the **Planet Configuration** section in 2.1.

**Comment by lmmrssa** [comment]
@jazdao These are two different ways of installing planet application. One using Vagrant and another using Docker. Application both run will have almost same features (might vary based on versions).
But we can not link 2.1 back to 1.2 as other details of this section will differ and if taken back user will assume its same task which they have already done.
Regarding repetitive context, we tried to keep it there so it will be easier for users. User might not recall all they did previously, so will miss few things. Such as notifying about new configuration, configuration structure etc.

**Comment by jazdao** [comment]
Hi @lmmrssa, thanks for the clarification!
