### ISSUE TITLE
Remove Windows Docker installation

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/open-learning-exchange.github.io#2116]
`
Windows
For 64bit Windows 10 Pro, Enterprise and Education 1607 Anniversary Update, Build 14393 or later, please use one of the following 2 methods to installs Docker for Windows:
Follow the official Install Docker for Windows guide
Chocolatey – the package manager for Windows was installed to your machine in the previous step. Please read What to know before you install and run choco install docker-for-windows
If you do not have Windows version specified above, you will need to install Docker Toolbox. Please follow the official guide Install Docker Toolbox on Windows.
`
We can remove **Docker for windows** context and just keep **Docker Toolbox** context. People are trying to use Windows Docker and facing issues as they have Virtualization enabled for Vagrant which does not work with Hyper-V required for Windows Docker.

**Comment by inDepthh** [comment]
Is there any benefit to using windows docker with Hyper-V vs Dockertool, such as performance?

**Comment by lmmrssa** [comment]
@inDepthh Docker was developed for Linux system, so Dockertool was provided for Windows users so they can use docker by using Virtualization. Later windows introduced Hyper-V which is different virtualization method and is not compatible with VMWare or VMBox. So for those who prefer or need to run Hyper-Virtualization for different other purpose Windows Docker was developed. Have not done test on which is better for performance, but Hyper-V requires specific windows versions and one of our step Vagrant requires VM we are trying to make user stick with only one virtualization method.

**Comment by cquarte1** [comment]
I had issue this as well. But I had to make sure to download Docker Toolbox for windows.
