### ISSUE TITLE
Outdated section in Step 6

### ISSUE THREAD

**Issue by jazdao** [open-learning-exchange/open-learning-exchange.github.io#2119]
### Problem
A particular section in [Step 6](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md) detailing the instructions to submit a new issue appears to be outdated.  The 'proposed solution' section is now included with the original issue instead of in an additional comment, so the instructions may be misleading.

### Screenshots
    
![issue2](https://user-images.githubusercontent.com/22950070/50624295-8f811300-0ed3-11e9-853d-96cfb3b7a76c.JPG)  
![issue](https://user-images.githubusercontent.com/22950070/50622727-60af7080-0ec4-11e9-8450-718b732e5603.JPG)

### Proposed solution

Rewrite the paragraph above the screenshot in Step 6 so that it includes the necessary information, and use a newer issue as an example.

**For example:**  
First, you will need to open an issue within the right repository ([upstream repository](https://github.com/open-learning-exchange/open-learning-exchange.github.io)) and explain the problem. If you are explaining a bug or how to replicate an issue, please be as explicit as possible and use pictures as necessary.  You will then research the possible solutions or ideas on how to address the Issue before detailing your proposed solution, as you can see here (<- link here). Someone else will hopefully provide input (as Dogi did here), and then you can move ahead with making the proposed changes.

**Comment by lmmrssa** [comment]
You can work on this. If you are pointing to new Issue try to pick one with good example and also comments or reviews on it.

**Comment by jazdao** [comment]
@lmmrssa Alright, I'll work on this one then.  And got it, thanks!
