### ISSUE TITLE
Suggestion to add sub-step in Step 0 

### ISSUE THREAD

**Issue by jazdao** [open-learning-exchange/open-learning-exchange.github.io#2121]
### Problem
It was difficult for me to find the [Planet User Manual](http://open-learning-exchange.github.io/#!./pages/techgenius/tg-planet-user-manual.md) again when I was looking for that link in the [First Steps](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md).  In my opinion, that particular section is important enough to merit its own sub-step in Step 0, but is easy to overlook because it is grouped with the information for Crowdin.

### Screenshots

![issue](https://user-images.githubusercontent.com/22950070/50741346-f1ca6400-11b0-11e9-93a3-d1ec8847cb21.JPG)

### Proposed solution

Isolate the Planet User Manual reading in its own sub-step.

**Comment by inDepthh** [comment]
I think making it a note would be a good idea

**Comment by jazdao** [comment]
Hi @inDepthh, should I make that section a note while keeping the same wording?

**Comment by lmmrssa** [comment]
@jazdao Yes that could be better.

**Comment by jazdao** [comment]
@lmmrssa Okay, I'll work on that then!
