### ISSUE TITLE
Clarification About VM When Installing Docker 

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/open-learning-exchange.github.io#2143]
### Problem
On Step 2 - Planet Installation and Configuration, there are steps that guide you through installing Docker. But I noticed (through the Gitter chat) that a couple of people ran into some errors when attempting to install Docker, myself included. This problem has to do with installing VM with the Docker Toolbox when VM Virtual Box is already on your system. There is a link provided to docker docs (https://docs.docker.com/toolbox/toolbox_install_windows/), which does mention: "If you have a previous version of VirtualBox installed, do not reinstall it with the Docker Toolbox installer. When prompted, uncheck it." However, there isn't enough attention given to this step and people seem to miss it due to the lack of emphasis on it.  

### Steps to reproduce the problem

Install Docker Toolbox with VM as part of the package when VM Virtual Box is already installed on the system. 

### Screenshots

![image](https://user-images.githubusercontent.com/21087353/51945293-ecdd8680-23e3-11e9-8bf7-400dbea6abdc.png)
![image](https://user-images.githubusercontent.com/21087353/51945302-f2d36780-23e3-11e9-9460-2dec5e6b3237.png)

### Proposed solution
 
The following should be added for Step 2 on the 'Planet Installation and Configuration' page: 
"**NOTE:** If you have a previous version of VirtualBox installed, do not reinstall it with the Docker Toolbox installer. When prompted, uncheck it."

**Comment by jazdao** [comment]
Hi @YuserahN- The current note under the Windows section is also referring to a similar issue.  I think that it could be a good idea to add the warning under it, or to rewrite them together.  

However, this doesn't seem to be the main problem with installing Docker on Windows for most people.  An alternate solution to the Docker installation issue has also been detailed in #2116.

**Comment by YuserahN** [comment]
@jazdao Should I go ahead and create a pull request to add the warning under the current note, as you've suggested?
