### ISSUE TITLE
Further Information on Crowdin in Step 0

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/open-learning-exchange.github.io#2144]
### Problem
Under Step 0 - Introductory Steps, there seems to be a lack of information on how to utilize Crowdin. There is an invitation link. And while a user can sign up and explore the website on their own to figure out how to contribute, I think it would be helpful if there was also a direct link to the Crowdin Documentation webpage. This page details the translation process and how to get started. It contains several other helpful links as well. 

### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/21087353/52024678-4a96cf00-24c7-11e9-87cb-4f6072dea060.png)

### Proposed solution

Along with the current information on Crowdin, I would simply add something along the lines of: 
"Check out this [link](https://support.crowdin.com/) to learn how you can start contributing."

**Comment by lmmrssa** [comment]
Yes this looks nice
