### ISSUE TITLE
Need Logout button

### ISSUE THREAD

**Issue by bhaktaravin** [open-learning-exchange/open-learning-exchange.github.io#215]
The interns need to see a logout button rather than a picture that leads them to pricing. After logging in, in the upper right corner, the word logout should appear.

The logout button should be added in the navigation.md file. More specifically, it should be changed from the picture to actual words so that people don't get confused.

**Comment by DrewPerlman** [comment]
@bhaktaravin Not entirely sure what you mean by "pricing." What link would this logout button lead to?
