### ISSUE TITLE
Vagrant Explanation Under Windows

### ISSUE THREAD

**Issue by ulaurent** [open-learning-exchange/open-learning-exchange.github.io#2151]
### Problem

Under the Planet Installation section for Windows, the explanation for what Vagrant is can be more explanatory . Not only is it used for building development environments, but also for maintaining portable virtual software environments.  

### Steps to reproduce the problem

Revise the element tag that displays this code. Simple revision of a sentence

### Screenshots

##An Explanation of what we have
![vagarnt explanation](https://user-images.githubusercontent.com/39177018/52313265-d2735200-297b-11e9-887e-fa80f4acb431.PNG)

##What we can add to the description
![vagrant deep expo](https://user-images.githubusercontent.com/39177018/52313285-e5862200-297b-11e9-81d7-9613a3e5b5a7.PNG)

### Proposed solution
Add to the description of Vagrant for more detailed understanding for users on it's purpose.

**Comment by jazdao** [comment]
Hi @ulaurent, this information is actually already included in the [Vagrant Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md) section of Step 1.

**Comment by lmmrssa** [comment]
@ulaurent we can keep the current description as it is. There is already link to vagrant so they can look in its official site.
