### ISSUE TITLE
Update http link to https in README.md

### ISSUE THREAD

**Issue by coder8102** [open-learning-exchange/open-learning-exchange.github.io#2154]
### Problem
In README.md, under "What is this?", link provided is http link (http://open-learning-exchange.github.io/). It should be https link as https://open-learning-exchange.github.io/

### Steps to reproduce the problem

N/A

### Screenshots

![issue](https://user-images.githubusercontent.com/41846764/52522065-2a44de00-2c46-11e9-9e04-faf060eecae1.PNG)

### Proposed solution

Replace http link with https link as https://open-learning-exchange.github.io/

**Comment by jazdao** [comment]
Hi @coder8102, I'm not sure I see the problem with the current link.  It leads to the organization page for OLE, whereas the proposed URL would link back to itself in the repository where the README.md page is.

**Comment by coder8102** [comment]
The problem is that current link referred is with protocol http which leads to insecure page navigation from secure page (https) which should be fixed. Any navigation from https page should be to https page.

**Comment by coder8102** [comment]
Closed issue as per comments from jazdao.
