### ISSUE TITLE
Update broken link on Vagrant tutorial page

### ISSUE THREAD

**Issue by coder8102** [open-learning-exchange/open-learning-exchange.github.io#2155]
### Problem
In First-steps, under Vagrant Tutorial page (http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md), link for "Step 1 - Planet Installation with vagrant" under Introduction is broken. Link currently goes to broken url: http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation.md

### Steps to reproduce the problem

=> On First steps page (http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md), Under step-1, click 3 - which will open Vagrant tutorial page

=> On Vagrant tutorial page, click on link - "Step 1 - Planet Installation with vagrant"

### Screenshots

![step-1](https://user-images.githubusercontent.com/41846764/52524772-8ae41300-2c66-11e9-9e29-111db3e73c88.PNG)
![step-2](https://user-images.githubusercontent.com/41846764/52524775-8d466d00-2c66-11e9-84d7-90b8e9c18ca5.PNG)
![brokenlink](https://user-images.githubusercontent.com/41846764/52524731-1a3cf680-2c66-11e9-8459-9127533cb392.PNG)

### Proposed solution

Link "Step 1 - Planet Installation with vagrant" under Introduction on Vagrant Tutorial page ("http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md") should be updated as "http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md"

**Comment by jazdao** [comment]
Good catch! 👍
