### ISSUE TITLE
About website

### ISSUE THREAD

**Issue by bhaktaravin** [open-learning-exchange/open-learning-exchange.github.io#216]
There should either be a What we do page or About us page, dictating what it is that Crowdin does. This page should be added under the navigation.md file and should be added before the Features tab or after the Customers but before the Contact tabs on the top of the page.

**Comment by DrewPerlman** [comment]
@bhaktaravin I think the faq.md page is our substitute for an "About Us" page. Are you suggesting we add some information explaining what the purpose of Crowdin is?

Also, I don't know what you mean by "Features," "Customers," and "Contact" tabs. Are you on the correct webpage?

**Comment by bhaktaravin** [comment]
I meant to say that. I apologize for the way that I said it.
