### ISSUE TITLE
git diff command not working

### ISSUE THREAD

**Issue by cquarte1** [open-learning-exchange/open-learning-exchange.github.io#2161]
### Problem
I tried to use the git diff command in the command prompt and no response at all. 

### Screenshots

![image](https://user-images.githubusercontent.com/11522529/52584130-4770dc80-2dff-11e9-8657-3e5d67da87be.png)

![image](https://user-images.githubusercontent.com/11522529/52584237-8acb4b00-2dff-11e9-811f-d90108ef69a1.png)

### Proposed solution

I need some solution.

**Comment by YuserahN** [comment]
Well, git diff shows the changes between commits. If there are no changes, it displays nothing. That seems to be the case here. 
It might be better to ask this in the gitter chat, as it's not really an issue with the command itself. Rather, it is a question that you have.
