### ISSUE TITLE
Creating "Useful links " at bottom of page in vagrant.md

### ISSUE THREAD

**Issue by Neha1990** [open-learning-exchange/open-learning-exchange.github.io#217]
The purpose of creating this issue is to available more resources to new interns and new software developers to understand the vagrant tool.
Like 
README.md link in vagrant.md.
Why to install Vagrant?
Vagrant Wikipedia for more information about tool that are using currently for development.

**Comment by DrewPerlman** [comment]
Good idea. Maybe these can go in the [faq.md](http://open-learning-exchange.github.io/#!pages/faq.md) under "Helpful Links."

**Comment by Neha1990** [comment]
So should I include that in FAQ? Actually when user any read article, it usually search easy way to find that links. For this reason I feel I should add it at the bottom of page.

**Comment by DrewPerlman** [comment]
Yes, I definitely agree with that. Sounds good!
