### ISSUE TITLE
vagrant up prod command won't execute.

### ISSUE THREAD

**Issue by cquarte1** [open-learning-exchange/open-learning-exchange.github.io#2170]
### Problem
vagrant up prod command won't execute. I click enter to get the command to execute still nothing happens

### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/11522529/52831414-8bcfd700-30a2-11e9-97c6-8a86fe261b1c.png)

### Proposed solution

I restarted my laptop and restart the command prompt. Now the command executed.

**Comment by cquarte1** [comment]
I restarted my laptop and restart the command prompt. Now the command executed.

**Comment by lmmrssa** [comment]
@cquarte1 could not figure what is the problem? Could you mention steps you did. Did it happened immediately after you installed vagrant? Because most of software require restart to be able to reflect changes.

**Comment by cquarte1** [comment]
Yes. After I restart my laptop it been work.
