### ISSUE TITLE
Can't get Planet Learning to open in Microsoft Edge 

### ISSUE THREAD

**Issue by cquarte1** [open-learning-exchange/open-learning-exchange.github.io#2172]
### Problem
Can't get Planet Learning to open in Microsoft Edge 

### Steps to reproduce the problem

I use Google Chrome to open Planet Learning. 

### Screenshots

N/A

### Proposed solution

I use Google Chrome to keep this issue under control.

**Comment by lmmrssa** [comment]
It is already mentioned to prefer firefox for planet.
