### ISSUE TITLE
Failed to load resources

### ISSUE THREAD

**Issue by bnmounir** [open-learning-exchange/open-learning-exchange.github.io#2177]
### Problem

- some content failed to load 

### Steps to reproduce the problem

- on the first steps page 

### Screenshots

<img width="1425" alt="screen1" src="https://user-images.githubusercontent.com/40181209/52918235-dc257f80-32c2-11e9-9273-ac52f7c2f936.png">

### Proposed solution

 - does anyone knows how to go about this problem?
 - also trying to figure out if I need to install the dependencies and run it (open-learning-exchange.github.io version on my machine) for debugging and testing if so, what steps to follow?

**Comment by jazdao** [comment]
Hi @bnmounir, those image files seem to belong to Step 0.  Are they not loading for you even when you refresh the page?  Also, if you have questions about the steps, please ask them on the Gitter chat instead.

**Comment by empeje** [comment]
@bnmounir great you catch some errors 🎉 

It seems we call something that already deleted which are `vi-watch.png` and `vi-follow.png`, could you help to fix this issue by creating a pull request?

---
@empeje , volunteer at @open-learning-exchange/developers

**Comment by bnmounir** [comment]
<img width="812" alt="screen2" src="https://user-images.githubusercontent.com/40181209/52977608-e0719b80-339b-11e9-943b-340741f99669.png">

seems to me like there's a call inside a minified script, and it's making the call from the wrong path `images/vi-follow.png` instead of `pages/vi/images/vi-follow.png` 

- any ideas if this is fixible and how?

---

**Comment by bnmounir** [comment]
it's recurring in different pages initiated at index line 151

<img width="857" alt="screen3" src="https://user-images.githubusercontent.com/40181209/52977960-44e12a80-339d-11e9-836d-2590b1779abe.png">
