### ISSUE TITLE
Install bot to manage issue life-cycle

### ISSUE THREAD

**Issue by empeje** [open-learning-exchange/open-learning-exchange.github.io#2179]
### Problem

A lot of issue without any follow up.

### Steps to reproduce the problem

- Open https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues

### Screenshots

N/A

### Proposed solution

- Install issue lifecyle bot
- Possible solution: https://github.com/probot/stale

**Comment by dogi** [comment]
I like ... @lmmrssa is managing this repo ;)
