### ISSUE TITLE
manager settings

### ISSUE THREAD

**Issue by bnmounir** [open-learning-exchange/open-learning-exchange.github.io#2183]
### Problem

<img width="342" alt="manager" src="https://user-images.githubusercontent.com/40181209/53033261-adccaf00-343e-11e9-9990-a350334cff64.png">

Adding steps to see the Manager Settings in the navbar (if it's not there)
I encountered this myself and found the solution in the gitter chat, maybe we can incorporate it inside the  Planet Tutorial

- by going inside couchDB to user settings  

<img width="330" alt="screen shot 2019-02-19 at 12 08 14 pm" src="https://user-images.githubusercontent.com/40181209/53033514-30556e80-343f-11e9-9612-eccc8c7b25c5.png">

- then clicking on: org.couchdb.user:<YourUserName> 
- checking that `"isUserAdmin"` is set to ` true `

<img width="207" alt="screen2" src="https://user-images.githubusercontent.com/40181209/53033888-19634c00-3440-11e9-824e-59b41d801119.png">

**Comment by lmmrssa** [comment]
@bnmounir We actually do not want people to play with database in this 10 steps. Also we do not have much troubleshoot document on planet. May be we will create troubleshoot doc in planet and we can have link that will point to that path to check if they have any issues with planet application.

**Comment by bnmounir** [comment]
I personally faced this problem last week and found this solution in gitter chat, so I thought It would be good to have it available for others, but I see your point @lmmrssa .
