### ISSUE TITLE
Troubleshooting in Planet Configurations

### ISSUE THREAD

**Issue by bnmounir** [open-learning-exchange/open-learning-exchange.github.io#2184]
### Steps to reproduce the problem

- in ./pages/vi/vi-configurations-vagrant.md 
- Planet Configurations 
- Troubleshooting section

### Proposed solution 

- adding a note: after finishing step 3 in Troubleshooting that you need to post the new username on gitter chat for approval.

##### also 
- pages/vi/vi-planetapps.md 
- Planet Tutorial
- Different Kinds of Updates to Your Community section

<img width="571" alt="1" src="https://user-images.githubusercontent.com/40181209/53036398-a8269780-3445-11e9-8137-da69e0c41778.png">

- adding a note: if you don't see all the options in ` Manager Settings ` it means the account hasn't been approved yet.

**Comment by lmmrssa** [comment]
This section is described on http://open-learning-exchange.github.io/#!pages/vi/vi-nation.md but may be we can find good way to point to describe it here as well.

**Comment by bnmounir** [comment]
I was referring to the fact that after using vagrant destroy you will have to post the new username in gitter

<img width="910" alt="02" src="https://user-images.githubusercontent.com/40181209/53120836-bb5a6580-3520-11e9-9ac9-90b2edd59aaa.png">

**Comment by lmmrssa** [comment]
Yes you can work on this one. Posting new configuration on gitter is good.
