### ISSUE TITLE
Step 3 Markdown & Fork Tutorial (Improvement)

### ISSUE THREAD

**Issue by cquarte1** [open-learning-exchange/open-learning-exchange.github.io#2185]
### Problem
Need to be clear/understandable for beginner

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

N/A

**Comment by lmmrssa** [comment]
Could you explain which part needs improvement? Any suggestion to improvement

**Comment by cquarte1** [comment]
It need to have step by step (Photos) to make sure that everyone is on the right track. Beginners like myself might not know if they doing everything correctly.

**Comment by lmmrssa** [comment]
I don't think adding image for every step is right approach. There will always be different scenarios that will come for each individual which might not occur for others. So it will be difficult to make sure everything is tackled by images and also to make sure that individual does not get confused by images that he does not see at all.
