### ISSUE TITLE
Conflicting meaning to right repository.

### ISSUE THREAD

**Issue by rockink** [open-learning-exchange/open-learning-exchange.github.io#220]
> First, you will need to open an issue within the right repository and explain the problem. If you are explaining a bug or how to replicate an issue, please be as explicit as possible and use pictures if possible. 

I couldn't actually identify which is the **right** repository, as to consider mine right, or the main one as the right. I couldn't find Issues tab in my repository, so I believe **this** is the right one.

**Comment by DrewPerlman** [comment]
Yes, this is the correct repository. Perhaps you can put a sentece or two on githubissues.md to clarify that that you are meant put issues about the MD wiki on this repository,
