### ISSUE TITLE
Step 6 Github Issues Tutorial

### ISSUE THREAD

**Issue by cquarte1** [open-learning-exchange/open-learning-exchange.github.io#2200]
### Problem
The instructions need to be more clearer for beginner to understand what they are doing. 

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

N/A

**Comment by lmmrssa** [comment]
@cquarte1 could you explain what is the issue here? This issue does not explain anything. Issue should explain what needs to be improved on VI steps.
