### ISSUE TITLE
Directions Clarification

### ISSUE THREAD

**Issue by bnmounir** [open-learning-exchange/open-learning-exchange.github.io#2204]
### Problem, Proposed solution and Screenshots

- mentioning **Merged** needed to complete the first steps

<img width="763" alt="screen shot 2019-02-28 at 11 16 48 am" src="https://user-images.githubusercontent.com/40181209/53584590-f1679d00-3b51-11e9-85b4-e3dfaf955cc2.png">

<img width="872" alt="screen shot 2019-02-28 at 12 10 27 pm" src="https://user-images.githubusercontent.com/40181209/53584619-ffb5b900-3b51-11e9-8bae-b86df215bc46.png">

- there's a style tag that could be removed 

<img width="573" alt="screen shot 2019-02-28 at 12 09 54 pm" src="https://user-images.githubusercontent.com/40181209/53584610-fcbac880-3b51-11e9-9e19-c5d17b0d6929.png">

- there's an html file with the same name containing only a meta tag (is that related to the fact that the md file contains html tags and javascript?

<img width="917" alt="screen shot 2019-02-28 at 12 09 36 pm" src="https://user-images.githubusercontent.com/40181209/53584606-fa586e80-3b51-11e9-8438-a6c5e307dbbf.png">

**Comment by lmmrssa** [comment]
@bnmounir make it `valid PR`.
Also yes you can remove style but leave html as it is.
