### ISSUE TITLE
Update Planet Tutorial (Step 4) instructions on how to 'get a course'

### ISSUE THREAD

**Issue by zelmi** [open-learning-exchange/open-learning-exchange.github.io#2211]
### Problem

The version of Planet used in step 4 tutorial is outdated. This is mentioned at the beginning of the tutorial, however, the method of how to ‘get’ courses has changed a lot, and can confuse a new user.

### Steps to reproduce the problem

Go to [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md) on ‘First Steps’ and look at the given instructions on how to ‘get a course’. Then open Planet and try to join a course. You will find that the process is very different from the one used in the tutorial.

##### The version of Planet shown in the tutorial:

![image](https://user-images.githubusercontent.com/29234807/54249114-630df680-4515-11e9-822f-9ca3f832f109.png)

##### The current working version of Planet:

![image](https://user-images.githubusercontent.com/29234807/54249168-8cc71d80-4515-11e9-82db-627ead27b4a2.png)

### Proposed solution
Update the Planet tutorial to include screenshots and step-by-step process on how to ‘get a course’ in the current running version of planet.

**Comment by lmmrssa** [comment]
@zelmi This section of getting course from **Get Course** will only show when nation sends you courses.
**List Courses** is the one from where you can get course on your own.

NOTE: Get Courses now has been changed to **Fetch Items**

**Comment by zelmi** [comment]
It took me a while to find how to get courses when I was in that step. I eventually:

1. Went through the list of courses and found the correct one.
2. Clicked the checkbox beside the course.
3. Hit 'Join Selected'.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29234807/54293884-22e75c00-4587-11e9-96da-dcd10590d5f9.png">

I think it would be helpful if this was explained in the [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md), which is why I wish to update the page and have it reflect these new changes. Do you think it is unnecessary?

**Comment by lmmrssa** [comment]
@zelmi One you pointed on the screen is different than what **Get Courses** is pointing. They are two different functionality. Join Selected is just adding that course to your dashboard. Course is already in your Planet Community.
**Get courses** from manager page is about getting Course that you do not have on your community at all. And you get courses from Nation (VI).

Yes we do have more courses that teach how to use Planet application, which we will try to sent just as we sent Virtual Intern course.

Also regarding this issue. You can update images with latest one but **Join Courses** is not what is related to this issue :)

**Comment by zelmi** [comment]
Thank you for explaining @lmmrssa. I had misunderstood the differences between **Get Courses** and **Join Courses**. I will close this issue and open a new one.
