### ISSUE TITLE
Issue with 'Start Here' links on 'GitHub and Markdown' and 'Git Repositories' pages.

### ISSUE THREAD

**Issue by zelmi** [open-learning-exchange/open-learning-exchange.github.io#2212]
### Problem

The ‘Start Here’ links found in the pages [GitHub and Markdown](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md), and [Git Repositories](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md) which are supposed to jump to a particular section of the current page, do not work when opened in a new tab.

### Steps to reproduce the problem  

1. Go to either of these two pages: [GitHub and Markdown](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md) or [Git Repositories](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md).
2. Go to the ‘Start Here’ section.
3. Try opening any of the given links in a new tab. 

##### Open any of the links in a new tab
<img width="1440" alt="Screen Shot 2019-03-13 at 9 00 56 PM" src="https://user-images.githubusercontent.com/29234807/54324403-f7d72980-45d3-11e9-969e-14306744a63d.png">

##### The page that will appear:
<img width="1440" alt="Screen Shot 2019-03-13 at 9 03 32 PM" src="https://user-images.githubusercontent.com/29234807/54324430-15a48e80-45d4-11e9-9093-4529f1590a0d.png">

### Proposed solution
Fix the links so that opening them in a new tab will open the correct page at the correct section.

**Comment by lmmrssa** [comment]
Link was supposed to navigate on section of the same page. It is not opening different page. So this link is ok if you just click it. But if you want links to be able to open on new tab then you can make changes. just make sure that it is not breaking navigation.

**Comment by zelmi** [comment]
Thank you :)
