### ISSUE TITLE
GitHub Issues page Create an Issue paragraph Capitalisation Consistency

### ISSUE THREAD

**Issue by Kid243** [open-learning-exchange/open-learning-exchange.github.io#2230]
### Problem
The problem I found was that the word "issue" in the paragraph at the third sentence is written with an uppercase for no reason. I would understand if that was the first time using the word but even in the paragraph itself, "issue" is used with a lowercase in previous sentences.

### Steps to reproduce the problem
N/A

### Screenshots
![2019-04-04](https://user-images.githubusercontent.com/22855384/55583892-94c74700-56e8-11e9-8d7c-884b74a8a168.png)

### Proposed solution
Lowercase "Issue"

**Comment by YuserahN** [comment]
@Kid243 You can go ahead and do that.

**Comment by lmmrssa** [comment]
@Kid243 you can work on issue.
