### ISSUE TITLE
Suggestion to improve First Steps guide

### ISSUE THREAD

**Issue by ibnahmadbello** [open-learning-exchange/open-learning-exchange.github.io#2231]
### Problem
It can be confusing when a user click a step in the left hand side navigation bar listing. If a user click on Step 8 or Step 9; it is Step 7 that get highlighted.

### Steps to reproduce the problem
Navigate to the [First Step Page](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) and select Step 8 or Step 9; it is Step 7 that get highlighted.

### Screenshots
![image](https://user-images.githubusercontent.com/14893581/55737059-6b762600-5a1c-11e9-9b81-c9435f55042b.png)

### Proposed solution

The written code should be made to highlight any of the step when any of the steps is selected just as it is highlighted when Step 0 - Step 7 is selected.

**Comment by zelmi** [comment]
This isn't the case for me when I use Safari or Firefox on mac... which browser are you using?

**Comment by ibnahmadbello** [comment]
@zelmi I use Firefox browser. I also did not notice the issue when using my Laptop but the issue is noted when browsing on my Desktop with Monitor size of 21.5''

**Comment by singharpita** [comment]
@ibnahmadbello Looks like you reached the end of the page. And browser will not scroll once page ends :) So this is not the issue.

**Comment by lmmrssa** [comment]
as stated by @singharpita this is the case of you reaching end of page. So closing this issue.
