### ISSUE TITLE
Numbering Issue

### ISSUE THREAD

**Issue by ibnahmadbello** [open-learning-exchange/open-learning-exchange.github.io#2233]
### Problem
The Step 4 of the *Take the Course* section listed number of steps as 12 instead of 11.

### Steps to reproduce the problem

Click on Step 4 listed among the first steps to be taken by intern which then link you to the [Planet Tutorial Page](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md)

### Screenshots

![image](https://user-images.githubusercontent.com/14893581/55893534-5a5e1e00-5bb0-11e9-9a89-3f9499fa055c.png)

### Proposed solution

![image](https://user-images.githubusercontent.com/14893581/55893650-a1e4aa00-5bb0-11e9-8dd6-b61e6528b654.png)
There are 11 steps in the screenshot. Correct 12 to 11.

**Comment by lmmrssa** [comment]
@ibnahmadbello make it **Carefully finish all steps of the course** instead of having Step number.

**Comment by zelmi** [comment]
Nice catch!

**Comment by ibnahmadbello** [comment]
@lmmrssa Will do so.
@zelmi Thanks. Another little catch!
