### ISSUE TITLE
Improve Intern Experience

### ISSUE THREAD

**Issue by ibnahmadbello** [open-learning-exchange/open-learning-exchange.github.io#2235]
### Problem
The word "Manager" is confusing as there is no "Manager" in the screenshot

### Steps to reproduce the problem

Among the listed steps for first intern, Click on step 7 which contains a link taking you to the [Nation Planet page](http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md), then the section `Sync With the Nation` is where the issue is observed.

### Screenshots

![image](https://user-images.githubusercontent.com/14893581/56025891-fbf98280-5d0a-11e9-93b7-cbf47475c576.png)

### Proposed solution

The word "Manager" should be change to "Settings icon".

**Comment by singharpita** [comment]
@ibnahmadbello That icon is Manager icon not setting icon. So instead you can update the image with highlight on that icon and update the text to say "manager" as shown on image below.

**Comment by ibnahmadbello** [comment]
Okay

**Comment by singharpita** [comment]
@ibnahmadbello you can start working on this issue. And create PR

**Comment by diabagatekelly** [comment]
@ibnahmadbello This is a good issue to point out, it caused some confusion for me as well. I had to hover over every icon in Planet before I found it.

**Comment by diabagatekelly** [comment]
@singharpita In your comment from 4 days ago you refer to an "image below" but I can't find the image. Did you mean the image above?

**Comment by ibnahmadbello** [comment]
Thanks. @singharpita I will make the changes and do PR ASAP. @diabagatekelly Glad that you recognize it as an issue.
