### ISSUE TITLE
Improve Intern Experience - Planet Tutorial Page

### ISSUE THREAD

**Issue by diabagatekelly** [open-learning-exchange/open-learning-exchange.github.io#2242]
### Problem
In the [Planet Configuration Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md), it says: "Your registration request for your community will be send to nation side for approval." At first, I was not able to complete some parts of the [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md), specifically the part under "Different Kinds of Updates to Your Community" and "Take the Course" because on the Manager page I only had access to three buttons: Feedback, Configuration and Members. I thought this was due to some mistake I made, so I spent a lot of time trying to figure it out. Then my Community was approved, and all the other buttons appeared on their own. 

### Screenshots

![image](https://user-images.githubusercontent.com/41132296/56301954-760c7b80-60fe-11e9-9ed4-d92224f4835e.png)

### Proposed solution

Clarify on Planet Tutorial in the section "Different Kinds of Updates to Your Community" that if all the buttons are not showing, the intern needs to ask for his Community to be approved before proceeding:
1. In the section "Different Kinds of Updates to Your Community", under the first sentence "There are three important kinds of updates that you may receive on the community side: updates, resources/courses and sync.", add: "If you do not see the buttons highlighted in the picture below on your Manager page, click on the "Feedback" button to ask for your Community to be approved. After your Community is approved, the buttons should appear."

**Comment by zelmi** [comment]
This section slowed me down for a bit as well, I think that tip could be very useful.

**Comment by lmmrssa** [comment]
@diabagatekelly feedback will not come to us until community is approved and synced, so they should escalate it on gitter chat channel

**Comment by diabagatekelly** [comment]
Ok so the sentence should say this instead? "If you do not see the buttons highlighted in the picture below on your Manager page, post a message to the Gitter Chat channel to get help.” 
Can I start working on it?
