### ISSUE TITLE
Improve Intern Experience - Docker tutorial page links

### ISSUE THREAD

**Issue by diabagatekelly** [open-learning-exchange/open-learning-exchange.github.io#2244]
### Problem
The [Vagrant Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md) has some Useful Links at the bottom of the tutorial. It would be useful to do the same for the [Docker Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md) page.

### Screenshots

![image](https://user-images.githubusercontent.com/41132296/56305898-d0a9d580-6106-11e9-81ad-ada0fe658978.png)

### Proposed solution

At the bottom of the Docker Tutorial page, above "Return to First Steps", add the following:
## Useful Links
[Why install Docker?](https://www.docker.com/why-docker)
[Wikipedia page on Docker](https://en.wikipedia.org/wiki/Docker_(software))
[Other useful Docker tutorial](https://scotch.io/tutorials/getting-started-with-docker)

**Comment by zelmi** [comment]
There are already some useful links given within the tutorial page:

<img width="974" alt="Screen Shot 2019-04-17 at 3 20 33 PM" src="https://user-images.githubusercontent.com/29234807/56314989-99e2b800-6124-11e9-875a-82b76ffdbf56.png">

However, adding some more or making a section at the bottom for a quick summary might be a good idea.

**Comment by lmmrssa** [comment]
@diabagatekelly as @zelmi mentioned all links are there in the docker page. Introduction, Installation, Docker commands So you can just list those below if that makes it more visible.
