### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by ibnahmadbello** [open-learning-exchange/open-learning-exchange.github.io#2245]
### Problem
Steps Number 2 of the 'Take the Course' should not have comma after the word "Virtual Intern".

### Steps to reproduce the problem

Visit the [Planet Tutorial Page](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md). Go to 'Take the course' section. For the listed steps, number 2 shouldn't have comma after "Virtual Interns".

### Screenshots

![edit-planet-app](https://user-images.githubusercontent.com/14893581/56321417-83f1e900-615e-11e9-92e9-d50c99d18f42.png)

### Proposed solution

The comma should be deleted.

**Comment by lmmrssa** [comment]
Find the course "Virtual Interns" is one sentence and Click on Join is after that.
So there is comma, but yes comma should be after "
This can also be updated to make sure they know how to join course.
So you can add that point. **Select checkbox next to course and then click on Join.**

**Comment by ibnahmadbello** [comment]
Okay. I will work on it.
