### ISSUE TITLE
Add link

### ISSUE THREAD

**Issue by ibnahmadbello** [open-learning-exchange/open-learning-exchange.github.io#2246]
### Problem
In the third paragraph of the 'Explanation About Repositories and Syncing Process'; it starts with "First, the GitHub help section and ..."
The word "GitHub help section" should be converted to a link leading to GitHub help section site. This would improve user experience as a user might hover his/her mouse over the wordings expecting it to be a link.

### Steps to reproduce the problem

Visit [Git Repositories page](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md) Goto the subsection "Explanation About Repositories and Syncing Process" of the "Start Here" section

### Screenshots

![edit-github-repositories](https://user-images.githubusercontent.com/14893581/56323794-d7673580-6164-11e9-94f1-34982435adec.png)

### Proposed solution

Convert the wordings "GitHub help section" to link. Something like this will do: [GitHub help section](https://help.github.com/en)

**Comment by lmmrssa** [comment]
@ibnahmadbello you can work on this issue

**Comment by ibnahmadbello** [comment]
Okay
