### ISSUE TITLE
Import an image in step 4

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/open-learning-exchange.github.io#2258]
### Problem
Actually it's a suggestion. The first time I want to find the manager setting button in my planet community, I took some time. 

### Screenshots

![1556230835564](https://user-images.githubusercontent.com/31773567/56772090-bb1f5600-676d-11e9-8c5b-bbee0ef08119.jpg)

### Proposed solution

So, i suggested we can add the icon of manger setting button
![1556228965382](https://user-images.githubusercontent.com/31773567/56772158-f457c600-676d-11e9-8d51-05cb2b5d9a75.jpg)
to the http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md. And other virtual intern will find it more quickly.

**Comment by ibnahmadbello** [comment]
@ScottHuangNYU  There is a screenshot at [Step 7](http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md) of the first steps; it has the manager icon highlighted.

**Comment by ScottHuangNYU** [comment]
@ibnahmadbello yes, I just go through step 7 and I saw the highlight of manager setting icon

**Comment by ScottHuangNYU** [comment]
@ibnahmadbello  and I think other interns will follow the order of step to go through each step. So I think it should be more clearer if I highlight it on step 4 page.

**Comment by singharpita** [comment]
@ScottHuangNYU you can just link the same image here.
