### ISSUE TITLE
Step #7 Sync With the Nation 2nd step

### ISSUE THREAD

**Issue by Kid243** [open-learning-exchange/open-learning-exchange.github.io#2259]
### Problem
In Sync With the Nation the second step says click on "Sync with Nation" which is not represented in the picture or when virtual interns go through the actual step.

### Screenshots

![2019-04-25 (1)](https://user-images.githubusercontent.com/22855384/56773706-efead780-6784-11e9-91c1-c1b2a83205aa.png)

### Proposed solution

Change click on "Sync with Nation" to click on "Manage Sync"

**Comment by ScottHuangNYU** [comment]
yeah, the "Sync with Nation" will mislead other interns. But when I went through the step 7, I didn't notify this problem, since the screenshot bring me to the right place. Anyway, Change click on "Sync with Nation" to click on "Manage Sync" will be more clearly.

**Comment by svlesiv** [comment]
Hi @Kid243, looks like a good issue.
