### ISSUE TITLE
Step 4 Planet Tutorial Suggestion

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/open-learning-exchange.github.io#2261]
### Problem
Actually it's a suggestion. 
1. At step 4 Planet Tutorial, I saw all word which is a button will use charactering shading style(code) to highlight. And the Manage Sync(as blow screenshot) used bold to highlight. I think all of those should be used same way to highlight.
2. At the same screenshot, I think adding a word 'page' after manager settings will be more easier to understand.

### Steps to reproduce the problem

![1556310227339](https://user-images.githubusercontent.com/31773567/56836520-5aa31e00-682c-11e9-895a-b64b20a4c35d.jpg)

### Proposed solution

I suggest make a change as following screenshot.
![1556312896645](https://user-images.githubusercontent.com/31773567/56836676-e0bf6480-682c-11e9-98ee-a3740e63db24.jpg)
![1556312935007](https://user-images.githubusercontent.com/31773567/56836682-e5841880-682c-11e9-9a00-7772de2c8f30.jpg)

**Comment by svlesiv** [comment]
Good eye:) This is a nice issue to work on.

**Comment by singharpita** [comment]
@ScottHuangNYU sure please make changes
