### ISSUE TITLE
Improvement on Step 7

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/open-learning-exchange.github.io#2262]
### Problem
After created a dummy account, we need to check to member list. But the description about how to check the member list isn't very clearly. 

### Screenshots

![1556318082298](https://user-images.githubusercontent.com/31773567/56839818-2da93800-6839-11e9-83f5-c21cf3de232e.jpg)

### Proposed solution

I can add some explanation about how to check members as blow screenshot
![1556318535137](https://user-images.githubusercontent.com/31773567/56839996-19196f80-683a-11e9-85a0-e9858ecf850e.jpg)

**Comment by singharpita** [comment]
@ScottHuangNYU Lets make it `listed under Members on Manager page`
