### ISSUE TITLE
More explanation about 'Watch' button on step 0

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/open-learning-exchange.github.io#2264]
### Problem
When I was on step, I am wonder why I need to choose to watch the open-learning-exchange repository.

### Screenshots

![1556663064721](https://user-images.githubusercontent.com/31773567/56997259-0ebde500-6b5c-11e9-8f8b-2c60e8628066.jpg)

### Proposed solution

I think add some explanation about the purpose or advantage of choose watch the repository will be better for other to understand. like we could notify by email at the first time when someone pull an issue, pull request or make a comment on this repository.

**Comment by singharpita** [comment]
@ScottHuangNYU you can just reference to https://help.github.com/en/articles/watching-and-unwatching-repositories

**Comment by ScottHuangNYU** [comment]
@singharpita So I just need to add the link above to make the explanation? No extra word explanation?
