### ISSUE TITLE
Add a resource about Nginx

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/open-learning-exchange.github.io#2265]
### Problem
The Planet is served by Nginx, I need more information about Nginx like how it work. 

### Screenshots

![1556666299882](https://user-images.githubusercontent.com/31773567/56999442-f651c880-6b63-11e9-9339-648f727db0ab.jpg)

### Proposed solution

add a link(https://www.vagrantup.com/intro/vs/docker.html) about what is Nginx, how it work and what different between Nginx and Apache.
![1556666225470](https://user-images.githubusercontent.com/31773567/56999490-3c0e9100-6b64-11e9-9cd0-9845f82460b2.jpg)

**Comment by svlesiv** [comment]
Hi @ScottHuangNYU, looks like a good issue to work on. Probably you meant to use this link: https://kinsta.com/knowledgebase/what-is-nginx/

**Comment by singharpita** [comment]
Link in proposed solution is not related to nginx, but one @svlesiv looks like the one you showed on image. @ScottHuangNYU you can just make nginx text to link this url.

**Comment by ScottHuangNYU** [comment]
@svlesiv yeah, I copy the wrong link. your link is I want to use

**Comment by ScottHuangNYU** [comment]
@singharpita yeah, I copied the wrong link. I will use this one https://kinsta.com/knowledgebase/what-is-nginx/

**Comment by singharpita** [comment]
@ScottHuangNYU please go ahead and make changes
