### ISSUE TITLE
Misspelled words on githubissues.md and FirstStep.md

### ISSUE THREAD

**Issue by cw-lin** [open-learning-exchange/open-learning-exchange.github.io#228]
Two words we can correct on these two pages

On githubissues.md
---
The line near the bottom of the page

> After this, you will then research the possible solutions or ideas on how to address the issue and write a comment with this information, as you can see here. Someone else will **hopefuly** provide input (as Dogi did here) and then you can move ahead with making the proposed changes.

**Hopefuly** should be **Hopefully**

On FirstStep.md
---
The line in the last step

> I gave you some stones to cross **ther** river but we're trying to build the bridge.

**Ther** should be **the**

**Comment by DrewPerlman** [comment]
Nice finds, thanks @cw-lin!
