### ISSUE TITLE
System does not accept same name on re-registration configuration setting

### ISSUE THREAD

**Issue by odsantos** [open-learning-exchange/open-learning-exchange.github.io#2280]
### Problem
System does not accept the same name on a re-registration of a same user.

### Steps to reproduce the problem

$ vagrant destroy prod
$ vagrant up prod
open 'http://localhost:3100/' in browser
(new registration procedures should appear)
(for 'Set Up Configuration', it is suggested to use the GitHub username for 'Name')
Snce it is a re-registration the GitHub username should not be accepted because a sort of 'Name already exists in the system' error

### Screenshots

![ole planet - odsantos_1](https://user-images.githubusercontent.com/8807117/57575831-437a4800-744a-11e9-9df9-d02ca52ba60a.JPG)
)

### Proposed solution

A check could be done to verify if the value for 'Name' and the email address entered at the previous step ('Create Admin') would match the values on record and if they did, the 'Name' value should be accepted, otherwise the current implementation code would be allowed to run.

**Comment by lmmrssa** [comment]
@odsantos name on previous page is admin username which is just for your community (planet) so it is not required to validate it for unique. whereas Name on this screen is what will connect it with Nation (planet) so it needs to be unique. And it is already mentioned on step that if name is not allowed when you destroy you should add some characters.

**Comment by odsantos** [comment]
@lmmrssa you are right. I had not confirmed the data on the first screen before.
Would it be useful to swap the third and second registration screens (Set Up Configuration and Contact Details) and follow the same reasoning for this issue? Meaning,  if they matched it would be considered a re-registration, but if not then it should be considered a new registration and that 'Name' value should not accepted (with a different email address).

**Comment by lmmrssa** [comment]
@odsantos it does not matter about email or any other details. Each configuration is different community. Only thing that identify community unique is **Name** and **code** of planet (community). Other than that you can repeat all details.

**Comment by odsantos** [comment]
@lmmrssa I am closing this issue then. Thank you.
