### ISSUE TITLE
Planet seems unable to run after an upgrade

### ISSUE THREAD

**Issue by odsantos** [open-learning-exchange/open-learning-exchange.github.io#2281]
### Problem
Planet seems unable to run afer an upgrade.
Ran after same problem on first configuration and re-registered, but the issue repeated.

### Steps to reproduce the problem

Tried to follow instructions under the heading "Different Kinds of Updates to Your Community",
on the page at [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md)

Not knowing how to reboot the system, ran "vagrant halt prod", but "vagrant up prod" appears not to work anymore.

### Screenshots

![upgrade_succ](https://user-images.githubusercontent.com/8807117/57660222-6a1cb800-75dd-11e9-9ca5-897e5ecaebd8.JPG)

![vagrant_halt_prod](https://user-images.githubusercontent.com/8807117/57660566-16ab6980-75df-11e9-9add-3fec80a4cebd.JPG)

![vagrant_up_failure](https://user-images.githubusercontent.com/8807117/57660259-9df7dd80-75dd-11e9-8a3f-629e24dda48b.JPG)

![system_failure_after_upgrade](https://user-images.githubusercontent.com/8807117/57660328-05159200-75de-11e9-98e4-68a10c326c20.JPG)

### Proposed solution

On the page (link above, on steps to reproduce) where it is asked to upgrade the system, it would be recommended to explain how to reboot the system.

If issue might happen, a trobleshoot section would be recommend on that page with suggested steps to fix it.

**Comment by lmmrssa** [comment]
@odsantos looks like it is something related to your password. that is a good catch on error of product we will try to replicate it. But it will not be part of the documentation on first step.
`vagrant halt prod` and `vagrant up prod` is what you need to run.

**Comment by Liew211** [comment]
@odsantos I've found that after restarts if the url doesn't work properly, try going to localhost:3100/eng/login

**Comment by odsantos** [comment]
@lmmrssa You might be right and after running those commands the error continues. Attached is a copy of the shell window. Since the error continues, should I destroy and re-build the system for Planet again? Is the'$' sign the unaccepted caracter?
Does this also mean that I should leave this issue open, and open another one for possibly working on it till its completion? Thanks.

[vagrant_up_prod_error.log](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/3186063/vagrant_up_prod_error.log)

**Comment by odsantos** [comment]
@Liew211 As you might confirm by the attached documentation, the virtual machine fails to run, so the localhost page does not open. Thanks.

**Comment by lmmrssa** [comment]
@odsantos I wanted to say that those are only commands required to run. But for you it will not work right now because of the password. We will look into the issue on application itself as it is part of application issue. And not part of the documentation related to application.
For you, solution will be destroy your planet (community) using `vagrant halt prod` `vagrant destroy -f prod` and then `vagrant up prod`.
You will have to reconfigure again. And try not to put special characters on password for now.
We appreciate that you found out this error, we will try to resolve it soon.

**Comment by odsantos** [comment]
@lmmrssa I shall try to do it, and open another issue. I would also appreciate if you could close this issue at your convenience.
Thank you.

**Comment by odsantos** [comment]
I would like to remember that when the Planet system was first configured or re-configured, since I shall have to configure it for the third time because the same occurred after the first configuration, the password kept working on successive 'up prod's.

It simple stops working (and I destroy and re-build the Planet system) after a successful upgrade is done via a system's webpage (I believe the page URL is [](localhost:3100/eng/upgrade)).
So, the bug might have been introduced by new settings brought with the upgrade.

Regards.
