### ISSUE TITLE
"Get courses" button missing from manager settings

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/open-learning-exchange.github.io#2282]
### Problem
"Get Courses" button is missing from the Manager Settings Menu

### Steps to reproduce the problem
1. Followed instructions on [First Steps](http://open-learning-exchange.github.io/#!./pages/vi/vi-first-steps.md) to set up planet community

2. Community was approved and updated

### Screenshots
![Screenshot_2019-05-14 Planet Learning(1)](https://user-images.githubusercontent.com/43839884/57746977-8f72fa00-76a1-11e9-9d22-1dfa7732d998.png)

### Proposed solution
Implement a method of manually adding courses from the nation to the community

**Comment by Liew211** [comment]
After repeated restarts and log ins, the needed courses have appeared in the "Add new courses" menu, which was previously empty.

**Comment by lmmrssa** [comment]
@Liew211 you need to force reload the page to clear cache. Most browser tries to serve from cache which will not reflect new updates. `Shift+refresh` will clear the cache and reload. We can mention about it on upgrade step.
Regarding **Get Courses** it is not changed to **Fetch Item** and will only show if there are anything send to community. So note will be good to add in.
