### ISSUE TITLE
Ease of navigation between steps

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/open-learning-exchange.github.io#2286]
### Problem
It would be more convenient to navigate between steps if at the end of each page, there is a link to the next section.  Currently, this only exists in Step 1, in [Planet installation with Vagrant](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md#Next_Section_), and [Planet configurations](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md#Next_Section_)

### Screenshots

![Screen Shot 2019-05-17 at 11 04 48 AM](https://user-images.githubusercontent.com/43839884/57937335-bb55d180-7893-11e9-91b6-39a3f76d3ee2.png)

### Proposed solution

Add a link to the next step at the end of each of the First Steps.

**Comment by ScottHuangNYU** [comment]
@Liew211 It's good improvement. Try it!

**Comment by lmmrssa** [comment]
@Liew211 looking at the implementation, it looks like there is chance of user skipping details mentioned on **First Step page** if they go through next link taking them to another markdown page.
For Step 1 these links are there as all of them are sub pages of step1.
So let's not try to add link. Instead we can just explain what next step will be and ask them to go to first page to move on next step.

**Comment by Liew211** [comment]
@lmmrssa 👍 I'll work on that then
