### ISSUE TITLE
Link to git diff description on Git Repositories page

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/open-learning-exchange.github.io#2287]
### Problem
In the "Summary of Steps" section of the [Git Repositories page](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md#Summary_of_Steps), some of the git commands have links to another web page with more detailed information.  As `git diff` is a bit more complicated, I think we should include a link describing it as well.

### Screenshots

![Screen Shot 2019-05-17 at 2 23 14 PM](https://user-images.githubusercontent.com/43839884/57948330-57d99d00-78af-11e9-8895-fd2a96af7fb3.png)

### Proposed solution

Add link next to `git diff` in the summary section for more info, similar to some of the other commands in that same section

**Comment by Liew211** [comment]
link would be [here](https://git-scm.com/docs/git-diff)

**Comment by lmmrssa** [comment]
@Liew211 please add more info similar to git pull and git push
