### ISSUE TITLE
Spelling mistake in URL, GitHub Issues Page

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/open-learning-exchange.github.io#2290]
### Problem
Says "YouGitHubUsername" instead of "YourGitHubUsername"

### Screenshots

![Screen Shot 2019-05-20 at 6 07 48 PM](https://user-images.githubusercontent.com/43839884/58054948-47812680-7b2a-11e9-9030-55e805a435ee.png)

### Proposed solution

Fix spelling error

**Comment by Kid243** [comment]
Nice catch there!

**Comment by singharpita** [comment]
@Liew211 you can work on this
