### ISSUE TITLE
Grammar issue at Step 6 Create a Pull Request

### ISSUE THREAD

**Issue by Kid243** [open-learning-exchange/open-learning-exchange.github.io#2292]
### Problem
In the fourth sentence at the "Create a Pull Request" paragraph it says, "you can change the title and comments." It's not right to have an "s" in "comments" in this case because it's not conjugated at the third person.

### Steps to reproduce the problem

N/A

### Screenshots

![2019-05-20](https://user-images.githubusercontent.com/22855384/58114518-83190080-7bbd-11e9-8c7d-8693d71a0207.png)

### Proposed solution

Erase the s from comments

**Comment by Liew211** [comment]
@Kid243 How about changing the sentence to "In this new page, give the PR a title and description"

**Comment by singharpita** [comment]
@Liew211 nice suggestion.
@Kid243 please work on suggestion by liew211

**Comment by Kid243** [comment]
On it
