### ISSUE TITLE
Docker Tutorial Improvement

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/open-learning-exchange.github.io#2295]
### Problem
Some arriving interns may not understand how to install docker or believe docker does not need to be installed to be used

### Screenshots
<img width="921" alt="Screen Shot 2019-05-22 at 11 16 38 PM" src="https://user-images.githubusercontent.com/43349314/58223472-c96a7e80-7ce7-11e9-9d33-47a9e7bdf54b.png">

### Proposed solution
Could implement a few screenshots of the docker website to download and setup docker

**Comment by singharpita** [comment]
@samuelchen1213 we have this document to give idea about docker and some commands of docker. If you go through document it explains that docker is already part of vagrant and we are not suggesting to install docker.
If someone is curious about installing docker then there is link which will take you to page which guide on installing docker.

**Comment by samuelchen1213** [comment]
@singharpita Understood! I will close this issue!
