### ISSUE TITLE
Rewording in step 1.2 macOS and Ubuntu

### ISSUE THREAD

**Issue by jfonta9** [open-learning-exchange/open-learning-exchange.github.io#2299]
### Problem
In step 1 section 2, the instructions to deal with vagrant on macOS or Ubuntu can be quite confusing, especially the second sentence. There is a much better worded example in step 4 we could use.

### Steps to reproduce the problem
N/A

#### Current:
![Screenshot from 2019-05-24 13-30-32](https://user-images.githubusercontent.com/44035296/58356184-89141900-7e2b-11e9-8553-05757fe88ce9.png)

#### Step 4 instructions we can use:
![Screenshot from 2019-05-24 14-05-48](https://user-images.githubusercontent.com/44035296/58356741-3a677e80-7e2d-11e9-8252-582dbd08d6a3.png)

### Proposed solution
replace under macOS and Ubuntu with "Please go to [http://localhost:3100](url) or run `vagrant global-status` in the command line to see if your community Planet is currently running. If not, please `cd` into `planet` directory in your local machine and run `vagrant up prod`. Make sure to have the correct port number(3100), or it will not work."

**Comment by samuelchen1213** [comment]
I agree to give the user the simplified step to first attempt localhost before using the vagrant command. This is much clearer

**Comment by Liew211** [comment]
@jfonta9 This certainly does improve clarity in this section.  Go ahead and work on this.
