### ISSUE TITLE
Suggestion for "First Steps" instructions - Github, master/forked IO, MDWiki, Vagrant

### ISSUE THREAD

**Issue by rachelpei** [open-learning-exchange/open-learning-exchange.github.io#230]
![image](https://cloud.githubusercontent.com/assets/20692531/17266246/d226a6aa-55c3-11e6-9eea-b1cc02816e94.png)

For visual learners, it may be helpful to have an overview flowchart/schematic somewhere in the First Steps page. I'm not sure if the above example is correct, but the activity of putting it together helped me begin to visualize the pieces better. What else could be added/clarified/corrected in order for it to be useful? For example, I think it would be especially helpful to have a way to distinguish the various layers of "nation" versus "community," the various configuration settings, maybe a breakdown of the routes pull requests and issues are sent through to make changes, etc.

**Comment by DrewPerlman** [comment]
@rachelpei Wow, this is great! This diagram is very clear and accurate, good job. Submit a pull request so we can include it on the MD wiki.
And yes I agree, it would be helpful to have another similar diagram that distinguishes the relationship between community and nation, etc. Good start!

**Comment by rachelpei** [comment]
![image](https://cloud.githubusercontent.com/assets/20692531/17346161/79dcd0f2-58d7-11e6-8c66-2c604e2d0e19.png)

There's already a really good picture of how multiple users make parallel changes with their forked/cloned repositories and then send changes back to the master repository. I think the above is more like a supplement to the fork/clone/syncing video tutorial.



![image](https://cloud.githubusercontent.com/assets/20692531/17346880/c8e291fc-58da-11e6-8238-f67418886067.png)

Here is how I'm understanding the nation/communities. All communities are parallel versions of the master Wiki, and in order to add new a new community in another language (e.g. Spanish), you use the translation tool Crowdin. The CouchDB database holds all the versions of the BeLLs and helps to sync them all. Community users can get library resources from the nation and can upload new resources that can be synced either to the nation or other communities (although I'm thinking it's probably back to the nation and then to the other communities, not sure). I'm not sure if this is the actual flow, just a best guess!


I can start by trying a pull request to add the first picture to the steps (need to think about how/where). Please let me know what you think about the new pictures.

Thanks!

**Comment by DrewPerlman** [comment]
@rachelpei Awesome, I love these diagrams! I think visuals will definitely help reduce confusion on the wiki. However, I think the above 2 figures you've just attached need some further corrections.

Would you mind opening a new issue and then copying a pasting what you've said in your second comment, since they don't have as much to do with your first comment (for organizational purposes)?

**Comment by DrewPerlman** [comment]
In fact, it actually might be more helpful to have 3 separate issues. One for each of your diagrams :wink:!

**Comment by rachelpei** [comment]
@DrewPerlman I was just at OLE today when you replied to the thread! :) Will create two more issues and copy the pictures over (I can also include the PPT draft in case you would like to mess with it). I think I have a clearer idea from @dogi and @EmilyLarkin about how the nation and communities "talk" to each other but can focus on hammering that out in the other issues' threads. Thanks!

**Comment by rachelpei** [comment]
[flow-chart_master-fork.pptx](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/400605/flow-chart_master-fork.pptx)

**Comment by DrewPerlman** [comment]
Thanks for splitting these up @rachelpei! I must have missed you when you came in yesterday, I was on the 9th floor :/

I'll merge your pull request and close this issue, since this picture looks good.

**Comment by rachelpei** [comment]
Thanks @DrewPerlman
