### ISSUE TITLE
Step 4 - Planet Tutorial (Make getting courses and upgrade clearer)

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/open-learning-exchange.github.io#2301]
### Problem
For many people, the get courses button does not show, instead they can just go directly to the courses page. This should be clearly addressed

### Steps to reproduce the problem
N/A

### Screenshots
<img width="873" alt="Screen Shot 2019-05-25 at 10 10 36 AM" src="https://user-images.githubusercontent.com/43349314/58370570-26c42280-7ed6-11e9-9446-01995b8417af.png">

### Proposed solution
Instead state:

1. Click the "Upgrade" button on Manager page and it take you to upgrade page. An update refers to a software update which improves the Planet (Note: If you do not see "Upgrade" button then simply carry on). It will then ask you for verification.
2. After the upgrade is complete, undergo `vagrant halt prod`, `vagrant up prod`, and log out and in again.
3. Go back to the Manager page and click on "Get Courses". (Note: If you do not see "Get Courses" button then simply carry on)

**Comment by jfonta9** [comment]
I agree this step can be confusing. Especially when the instructions say to notify the chat if you do not see the get courses button. I like your solution, other than the steps about approving your community. I believe that is part of a previous step, you shouldn't have to get approval for an update, just restart vagrant.

**Comment by samuelchen1213** [comment]
> I agree this step can be confusing. Especially when the instructions say to notify the chat if you do not see the get courses button. I like your solution, other than the steps about approving your community. I believe that is part of a previous step, you shouldn't have to get approval for an update, just restart vagrant.

Thank you for the reply! I made a small mistake, just updated the issue!

**Comment by Liew211** [comment]
>Furthermore, after upgrading the user's community must be approved before moving on. 
The user's community must be approved before any other functions are available, and at this point in the step, this should already have been done.  
>Note: You may need to wait a few minutes after completing step 1 for you to be able to get the courses after logging out and in.
This note is not necessary, the current existing note asks you to refresh while clearing cache to fix this problem.  
I think the rest of the solution is a good fix, work on this.

**Comment by samuelchen1213** [comment]
@Liew211 On it right now!

**Comment by jfonta9** [comment]
@samuelchen1213  @Liew211 there is a section in Step 7 - Nation Planet called "Update your community" that explains really well how to upgrade your community. Maybe we can put a link to that for people who need further instructions on upgrading their community. 

Another possible solution could be to move the instructions from Step 7 into Step 4 and add a link to Step 7. It doesn't make sense to me that we have vague instructions early on and then very good instructions on later steps that accomplish the same thing.
