### ISSUE TITLE
Step 3 - Clearer picture for where to put profile

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/open-learning-exchange.github.io#2302]
### Problem
The picture shows where to edit the profile file in __username.github.io/pages/profiles__ even though it should be __username.github.io/pages/vi/profiles__. This has caused a few people to place their profiles in the incorrect folder. (Someone has made a profile folder in pages, not vi)

### Steps to reproduce the problem
N/A

### Screenshots
<img width="921" alt="Screen Shot 2019-05-26 at 4 18 57 PM" src="https://user-images.githubusercontent.com/43349314/58386756-5eb09000-7fd2-11e9-8c64-e10b29750b98.png">

### Proposed solution
Replace the picture with an accurate picture of username.github.io/pages/vi/profiles and also *delete* the Profile folder in username.github.io/pages (Unless it is needed)

**Comment by singharpita** [comment]
@samuelchen1213 Picture seems to have wrong path so you can fix it with new image.

**Comment by samuelchen1213** [comment]
Working on this right now!
