### ISSUE TITLE
Clarity of uploading resources for planet tutorial

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/open-learning-exchange.github.io#2303]
### Problem
The website currently states:

Fill out the information:
- As we are just doing this as a practice, accuracy of information/source of content is not very important.
- Make sure to have something in all of the drop-down menus and text boxes.
- Next, click on Submit. You have now uploaded the resource. You should be able to find the resource in Library, make sure that you can open it. Repeat the same process for all three resources.

The problem with this, is that it does not clearly state to upload the downloaded files from the previous step and many may make a mistake and not upload anything. I personally made this mistake as I did not know this step was related to the downloaded files. Although a small fix, the solution will make this step much clearer.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="888" alt="Screen Shot 2019-05-26 at 5 42 24 PM" src="https://user-images.githubusercontent.com/43349314/58387549-3a5ab080-7fde-11e9-9c42-dd5c9e36bc9c.png">

### Proposed solution
A simple rewording can fix this:

Fill out the information:
1. Fill in all of the text boxes and drop-down menus (As this is just practice, accuracy of information is not important)
2. Be sure to **upload** one of the `PDF - "Feelings"`, `mp3 song - "Opposite Song"`, or `mp4 video - "Burka Avenger"` files.
3. Next, click on Submit. You have now uploaded the resource.
4. Repeat this until all three files have been uploaded as resources.

**Comment by singharpita** [comment]
@samuelchen1213 looks good you can work on this

**Comment by samuelchen1213** [comment]
Working on it immediately!
