### ISSUE TITLE
Nation Planet Tutorial Formatting

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/open-learning-exchange.github.io#2307]
### Problem
The pictures are so large and without format, it is hard to see the text. The first few steps followed a style of picture on the right and text on the left. I plan to format the entire page like this. (See screenshots)

### Steps to reproduce the problem
N/A

### Screenshots
Currently most steps look like this: 
<img width="1280" alt="Screen Shot 2019-05-27 at 12 14 47 PM" src="https://user-images.githubusercontent.com/43349314/58431067-25335f80-807a-11e9-8cdd-0c6dcde009c1.png">

I want to format them to look like this:
<img width="870" alt="Screen Shot 2019-05-27 at 12 15 09 PM" src="https://user-images.githubusercontent.com/43349314/58430898-5d866e00-8079-11e9-9a28-2e1a52dd1208.png">

### Proposed solution
- Reformatting (Check screenshots)
- I would either need to use HTML or a CSS style sheet which needs to be approved

**Comment by SNutakki** [comment]
I think this is a good idea overall just to make it easier to see what text corresponds to each image. The images will be smaller, but it shouldn't be an issue since they can be expanded if necessary.

**Comment by lmmrssa** [comment]
@samuelchen1213 if you have solution please create PR and we can look into it. Try to not use HTML on the pages, we want to maintain it with markdown not HTML

**Comment by samuelchen1213** [comment]
@lmmrssa I have attempted to format it, but it seems it cannot be done properly without HTML. I will be closing this issue
