### ISSUE TITLE
Rawgit inaccurately mentioned in Steps 3 and 6

### ISSUE THREAD

**Issue by SNutakki** [open-learning-exchange/open-learning-exchange.github.io#2308]
### Problem
Rawgit is mentioned multiple times in the tutorial even though the website is no longer supported and raw.githack is used elsewhere in the tutorial instead.

### Steps to reproduce the problem
Simply go to steps 3 and 6 of the tutorial and search for rawgit. The issue is not present in other tutorial steps.

### Screenshots
![Screen Shot 2019-05-27 at 11 38 17 AM](https://user-images.githubusercontent.com/13606819/58435110-d4b90380-8073-11e9-8d5d-7091667db15e.png)
![Screen Shot 2019-05-27 at 11 39 15 AM](https://user-images.githubusercontent.com/13606819/58435194-282b5180-8074-11e9-9e1b-d8b2df7d02ab.png)
![Screen Shot 2019-05-27 at 11 40 11 AM](https://user-images.githubusercontent.com/13606819/58435196-29f51500-8074-11e9-8737-58a3ef101aa6.png)
![Screen Shot 2019-05-27 at 11 40 41 AM](https://user-images.githubusercontent.com/13606819/58435202-2bbed880-8074-11e9-8d5d-56ec709f86c6.png)

### Proposed solution
I would propose simply replacing all instances of rawgit with raw.githack.

**Comment by samuelchen1213** [comment]
Small change, but really makes everything clearer 👍🏻

**Comment by jeevast** [comment]
Even I had a difficulty trying to interpret this when following this step. Nicely done!

**Comment by Liew211** [comment]
@SNutakki good catch, you can work on this 👍

**Comment by lmmrssa** [comment]
@SNutakki also update images which refer to rawgit link
