### ISSUE TITLE
Misspelled words on crowdinintegration.md and htmlresources.md

### ISSUE THREAD

**Issue by cw-lin** [open-learning-exchange/open-learning-exchange.github.io#231]
**crowdinintegration.md**
---

This title is under Objective section
> **Taggin**

The title **Taggin** should be **Tagging**

This line is near the bottom of the page
> 2.2.5-Save your tags by **clickin** the Save button on the upper-right corner of the page.

**clickin** should be **clicking**

This line is near the end of the page 
> 2- Go throught the list of strings, click Edit Text (see the figure below), and write good context of the strings.

**throught** should be **through**

**htmlresources.md**
---

This is near the top of the page
> There's a good amount of **prerequesites** for the couchapp installation on Windows.

**prerequesites** should be **prerequisites**

**Comment by DrewPerlman** [comment]
This issue looks great! Thanks @cw-lin.
