### ISSUE TITLE
Update forked repository using github

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/open-learning-exchange.github.io#2310]
### Problem
An intern's forked repository can actually be update on github alone instead of using git bash or terminal. This would be at the end of **step 5: "keeping repositories updated"**

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
-----------------------------------------------------------------------------------------------
# Updating forked branch using github
**1. Open username.github.io**

**2. Click the compare button.**
This will open a page titled Comparing Changes and if you look carefully you'll have jumped to the upstream version of the repository. If you were to do a regular pull request then this makes sense as you'd be bringing your changes into the upstream version. But in this case we want to flip the direction and pull changes from the original version to our fork.
<img width="1008" alt="Screen Shot 2019-05-27 at 10 37 38 PM" src="https://user-images.githubusercontent.com/43349314/58446910-943ba300-80d0-11e9-99d4-8b7c916f6ef3.png">

**3. Change the base fork to your repository**
You're now back to your fork but you've also asked to compare two identical repositories so GitHub thinks you care about branches not forks. Click on *
<img width="1026" alt="Screen Shot 2019-05-27 at 10 39 05 PM" src="https://user-images.githubusercontent.com/43349314/58446920-9f8ece80-80d0-11e9-9e30-595bcc2b9c64.png">
<img width="1005" alt="Screen Shot 2019-05-27 at 10 41 10 PM" src="https://user-images.githubusercontent.com/43349314/58446928-a289bf00-80d0-11e9-94c8-dcfb48a6399b.png">

compare across forks* to get back your base fork option.

**4. Change the head fork to the upstream (original) repository**

**5. You'll see one of two options:**
1. "There isn’t anything to compare" This means you're up to date and you don't have to do anything.
2. A list of commits. These are the changes that have happened in the repository since you forked your version. _Go to next step_.

**6. Create a pull request**
Note that this pull request is to you! So you can confirm that it's ok and merge it when necessary. And if there are any merge conflicts then it's up to you to figure out what's gone wrong and sort them out.

**Comment by Liew211** [comment]
@samuelchen1213 I think you should keep the directions already there, but include this as a suggestion at the end :+1:

**Comment by lmmrssa** [comment]
@samuelchen1213 we want people to get familiar with **cli** not just Github UI. Yes Github UI looks more simple but learning to do it from **cli** is more important as developer

**Comment by samuelchen1213** [comment]
@lmmrssa so should I still implement this or would it be more beneficial not to?

**Comment by lmmrssa** [comment]
@samuelchen1213 if we introduce it on wiki people will be more inclined to use GUI and not learn CLI so lets not have it here. Also CLI is just 2-3 commands so it should just be fine.

**Comment by samuelchen1213** [comment]
@lmmrssa No problem! I will close this issue
