### ISSUE TITLE
Consistency Fix in step 5

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/open-learning-exchange.github.io#2315]
### Problem
Although it is just a small issue, I believe the points that are numbered / bullets should be consistent throughout this page. Many people have worked on the page, so sometimes, information shown are bullets and sometimes they are numbered.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="903" alt="Screen Shot 2019-05-28 at 7 56 57 PM" src="https://user-images.githubusercontent.com/43349314/58519781-0371cf80-8183-11e9-9d05-48f95074b731.png">

As you can see in **"Configure the upstream repository to your fork"**, the last step references step 2, but it's a bullet point. It is obvious anybody will be able to understand what the sentence meant, but the solution can make everything flow much smoother.

### Proposed solution
For the points that are specifically *steps* I will change them to numbered. For those that are just points, I will leave them as bullet points. As said again, really small inconsistency issue.

**Comment by Liew211** [comment]
@samuelchen1213 for clarity's sake, I'd suggest to remove "as step 2".  For the rest, go ahead with the bullet/numbering.

**Comment by samuelchen1213** [comment]
@Liew211 on it right now!
