### ISSUE TITLE
Explanation for Raw git

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/open-learning-exchange.github.io#2318]
### Problem
This page [github and markdown](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md) in step 3 when speaking of *Create a new file as your personal MDwiki page and commit your changes* there's simply a statement saying to check your page at "https://raw.githack.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/vi/profiles/YourUserName.md". I think it's necessary to explain what is raw.githack there instead leaving it vague.

### Steps to reproduce the problem

N/A

### Screenshots

![vagrant 5](https://user-images.githubusercontent.com/14145400/58582163-2487fe00-821f-11e9-950f-660dda2428db.png)

### Proposed solution

Add a simple point at the end about RawGit.

**Comment by Liew211** [comment]
@jeevast good idea, I suggest adding a sentence like "The raw.githack link allows reviewers to preview your changes" or something along those lines.  Go ahead and work on this 👍

**Comment by jeevast** [comment]
@Liew211 alright
