### ISSUE TITLE
Online Environment for Markdown in Github issues tab

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/open-learning-exchange.github.io#2320]
### Problem
In [github issues](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md) at the **Preview Changes Locally** section provides the option of previewing through HTTP server. Another simple way to preview is to use the [online environment](https://dillinger.io/) which would make still simpler. 

### Steps to reproduce the problem

N/A

### Screenshots

![vagrant 6](https://user-images.githubusercontent.com/14145400/58587145-a2053b80-822a-11e9-834c-3f8378f83416.png)

### Proposed solution

In the same section providing the link to online environment solves this issue.

**Comment by lmmrssa** [comment]
Looks good

**Comment by sjson421** [comment]
I didn't know about this. Looks really convenient!
