### ISSUE TITLE
Reverting the changes before commit.

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/open-learning-exchange.github.io#2323]
### Problem
I see in this page [GitHub Issues tab](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md) how to commit changes, but I also prefer adding up a [link](https://githowto.com/undoing_local_changes)  how to revert the changes in a file before staging it.

 

### Steps to reproduce the problem

N/A

### Screenshots

![vagrant 7](https://user-images.githubusercontent.com/14145400/58606122-3f329500-8268-11e9-9b66-9bb77b615068.png)

### Proposed solution

A simple note at the end, showing the link how to revert changes before staging would be helpful in case when someone come up with the wrong edit.

**Comment by lmmrssa** [comment]
@jeevast please go ahead
