### ISSUE TITLE
User not registered although approved

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/open-learning-exchange.github.io#2327]
### Problem
Sometimes upon registering an account as specified on the [Planet Configurations page](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md) and having it approved, it will afterwards say that the user is not registered, and the site will break permanently upon refresh. This is fixed upon recreating the account through "vagrant destroy prod" and "vagrant up prod" but this is not under the problems listed under Troubleshooting.

### Steps to reproduce the problem
N/A

### Screenshots
![Screenshot (3)](https://user-images.githubusercontent.com/22685147/58672048-259a5780-8313-11e9-8146-6d419e83537e.png)
![Screenshot (4)](https://user-images.githubusercontent.com/22685147/58672123-7611b500-8313-11e9-843f-d54932d684c3.png)

### Proposed solution
Include an additional point under Troubleshooting for cases where "the member is not registered" although he or she is already approved. Perhaps add the above screenshots as well.

**Comment by jeevast** [comment]
@sjson421 yes it'd be very helpful for future interns

**Comment by lmmrssa** [comment]
@sjson421 if you could provide steps you followed to produce this error will be helpful. It should not usually be a case. Did you halt vagrant or have you upgraded software. Also which version is planet on?

**Comment by sjson421** [comment]
@lmmrssa For me, it happened after my first vagrant halt then vagrant up. I followed the steps very much in chronological order so I had not upgraded it yet; I have now, so I can't check which version I was on when I first saw this. I am currently on 0.8.5.
