### ISSUE TITLE
Orthograph at Update Resources in Planet Tutorial

### ISSUE THREAD

**Issue by Kid243** [open-learning-exchange/open-learning-exchange.github.io#2330]
### Problem
At the Planet Tutorial page at the 2nd paragraph of Update Resources at "the three type," "type" is missing an -s

### Steps to reproduce the problem

N/A

### Screenshots

![2019-05-31](https://user-images.githubusercontent.com/22855384/58736430-6ce02100-83c3-11e9-9fa2-f3e733da757d.png)

### Proposed solution

Adding an -s to "type"

**Comment by Liew211** [comment]
@Kid243 You can work on this.

**Comment by Kid243** [comment]
Alright on it
