### ISSUE TITLE
Repeated instructions on Step 4 and Step 7

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/open-learning-exchange.github.io#2332]
### Problem
Redundancy in the procedures of Step 4 ([Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md)) and Step 7 ([Nation Planet](http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md)).

Both steps ask for an Upgrade, with it being under "Different Kinds of Updates to Your Community" for Planet Tutorial and under "Update your community" for Nation Planet. This is redundant.

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Remove the Upgrade section in Step 7; the application will have already been updated by then.

**Comment by lmmrssa** [comment]
@sjson421 We are continuously having new release so there could be multiple updates. Also if they have already updated and no new version is available then they will not see **Upgrade** option, which is mentioned there stating if you do not see upgrade just move on. So there is no change to be made here.
