### ISSUE TITLE
Out-of-order Instructions for Managing Sync

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/open-learning-exchange.github.io#2333]
### Problem
In Step 4 [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md), under "Different Kinds of Updates to Your Community", step 4 mentions that:

>Finally, repeat the process of sending an activities sync to the nation using Manage Sync.

But this process is not explained until further on, in Step 7 [Nation Planet](http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md), under "Sync With the Nation".

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Move the section of "Sync with the Nation" to Step 4. Have a referral back to Step 4 for Syncing instructions on Step 7.

**Comment by lmmrssa** [comment]
There is not much to be explained regarding **Manage Sync** on step 4. You can just mention to trigger **Run sync** inside Manager Sync page. All other details on Step 7 are not required here as they are already on Manager page.

**Comment by Liew211** [comment]
@sjson421 I'd suggest just removing "repeat the process of" since this is the first time syncing.

**Comment by sjson421** [comment]
Will do.
