### ISSUE TITLE
Step 7 Nation Planet typo

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/open-learning-exchange.github.io#2334]
### Problem
In [Nation Planet](http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md), right above "Check Sync status", it says: "You will be **prompt** to provide Administrator password." This is grammatically incorrect

### Steps to reproduce the problem

N/A

### Screenshots

![Capture](https://user-images.githubusercontent.com/22685147/58755482-0803f400-84b3-11e9-9997-2e7295decc51.PNG)

### Proposed solution

Change the word "prompt" to "prompted"

**Comment by Liew211** [comment]
@sjson421 good catch, go ahead and work on this.
