### ISSUE TITLE
Error on number of approvals required for pull request to merge

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/open-learning-exchange.github.io#2335]
### Problem
On Step 8, under [First Steps](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md), the number of approvals required for a pull request to merge is said to be three. It is, in fact, two.

### Steps to reproduce the problem

N/A

### Screenshots

![Three](https://user-images.githubusercontent.com/22685147/58755876-caa36480-84ba-11e9-877c-56076abb9d4e.png)

![Two](https://user-images.githubusercontent.com/22685147/58755889-f32b5e80-84ba-11e9-94d0-f04a48f36706.PNG)

### Proposed solution

Change the aforementioned text to be "at least **two** other OLE team members/interns"

**Comment by Liew211** [comment]
@sjson421 you can work on this.
