### ISSUE TITLE
Move image labels to the left of the image

### ISSUE THREAD

**Issue by SNutakki** [open-learning-exchange/open-learning-exchange.github.io#2343]
### Problem
Labels for some of the images in the Markdown Tutorial section are to the right of the image when they're supposed to be to the left.

### Steps to reproduce the problem

Go to http://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md.

### Screenshots

![Screen Shot 2019-06-03 at 7 32 10 AM](https://user-images.githubusercontent.com/13606819/58810042-f402e400-85d1-11e9-9ec9-619f7245d24f.png)

### Proposed solution

Move labels to the left of the images.

**Comment by samuelchen1213** [comment]
@SNutakki I believe what they meant was how the markdown is rendered as HTML on the right, not the picture itself

**Comment by SNutakki** [comment]
> @SNutakki I believe what they meant was how the markdown is rendered as HTML on the right, not the picture itself

I meant how the labels for images are on the right side when it seems like they should be on the left. Here's another example.

![Screen Shot 2019-06-03 at 7 32 10 AM](https://user-images.githubusercontent.com/13606819/58843993-fa24af00-8629-11e9-9250-0aae8aec9020.png)

**Comment by lmmrssa** [comment]
@SNutakki It is not an issue.
