### ISSUE TITLE
Alter description in 'Find and fork the correct repository'

### ISSUE THREAD

**Issue by SNutakki** [open-learning-exchange/open-learning-exchange.github.io#2344]
### Problem
A description in this section uses a run-on sentence that can be unclear.

### Steps to reproduce the problem

Go to http://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md.

### Screenshots

![Screen Shot 2019-06-03 at 7 36 34 AM](https://user-images.githubusercontent.com/13606819/58810262-74c1e000-85d2-11e9-9914-201eb6fc7ddc.png)

### Proposed solution

Break up the run-on sentence into separate lines for each step. The altered description:

NOTE: It is very important you distinguish between your personal GitHub account and OLE's account. First, you should fork the repository to create your own 'clean' version of the code. You should commit any changes you make to a branch on this version of the repository. These changes should be sent back to OLE's repository through pull requests. OLE's code will be updated when the pull requests are approved.

**Comment by Kid243** [comment]
You're right about the run-on happening. For purely personal aesthetic reasons I wouldn't use bullets here, however seeing the result might be great.

**Comment by samuelchen1213** [comment]
@SNutakki Yeah, as @Kid243 said, you should try typing out exactly how you would like to phrase it in the proposed solution! Then we can decide if this is an issue to fix!

**Comment by SNutakki** [comment]
> @SNutakki Yeah, as @Kid243 said, you should try typing out exactly how you would like to phrase it in the proposed solution! Then we can decide if this is an issue to fix!

I've posted what the modified description would look like. If it's alright, I can post the PR.

**Comment by samuelchen1213** [comment]
@SNutakki It does make it clearer. You can work on this! 👍🏻
