### ISSUE TITLE
Remove Manual/Full Installation

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/open-learning-exchange.github.io#2349]
Under **Tech Geniuses** menu there is **Manual/Full Installation** which leads to page not found. So that link needs to be removed.
<img width="975" alt="Sketch (47)" src="https://user-images.githubusercontent.com/2909490/58952028-603c3e00-87b2-11e9-9bbb-9ff34b57e383.png">

**Comment by smem22** [comment]
I'm on it

**Comment by lillyxxx** [comment]
I noticed this problem hasn't been resolved, can I be assigned to this issue?

**Comment by lmmrssa** [comment]
@smem22 mentioned he is on it but havent seen any PR for it yet. So yes @lillyxxx you can take this one
