### ISSUE TITLE
Virtual Interns Step 2; Docker tutorial

### ISSUE THREAD

**Issue by hiroTochigi** [open-learning-exchange/open-learning-exchange.github.io#2352]
### Problem 
If people already configure their Planet in Step 1 Docker command `docker-compose -f planet.yml -p planet up -d --build` might break the configuration. 

### Steps to reproduce the problem

In Step 1, people follow the instructions and configure their Planet. 
Then, in Step 2, they follow the tutorial for Docker section and run `docker-compose -f planet.yml -p planet up -d --build`.

### Screenshots

![Issue](https://user-images.githubusercontent.com/44413241/58995577-62a29600-87ba-11e9-93d2-c40045e6c613.jpg)

### Proposed solution

Explain more clearly. 
For example, "(If you configure Planet in Step 1, you should not run `docker-compose -f planet.yml -p planet up -d --build`)"

**Comment by ScottHuangNYU** [comment]
@hiroTochigi yes, I think add a explanation will be more clearly.
