### ISSUE TITLE
Clarify requirements for MD profile page

### ISSUE THREAD

**Issue by SNutakki** [open-learning-exchange/open-learning-exchange.github.io#2356]
### Problem
The requirements for our Markdown profile page in Step 3 are not clear. It's initially said that 5 elements are recommended (not required) while later on, the user is asked to ensure that they have 3-5 Markdown elements. It's unclear how many elements are actually necessary

### Steps to reproduce the problem

N/A

### Screenshots

![Screen Shot 2019-06-06 at 8 43 06 AM](https://user-images.githubusercontent.com/13606819/59046586-1fd2d380-8837-11e9-9a06-9808e3b6e1f6.png)
![Screen Shot 2019-06-06 at 8 43 25 AM](https://user-images.githubusercontent.com/13606819/59046589-22352d80-8837-11e9-9ba3-efd8879b992f.png)

### Proposed solution

Modify both descriptions above to state that N elements (not sure how many) are required. Emphasize the requirement by putting it in the initial bullet list. It might also be useful to clarify exactly what is considered to be a Markdown element.

**Comment by jeevast** [comment]
@SNutakki  you can say "you used more than 3 markdown elements in your profile" or something like that.

**Comment by SNutakki** [comment]
> @SNutakki you can say "you used more than 3 markdown elements in your profile" or something like that. you can work on it.

So three elements are good enough? I used at least three when I first submitted mine (header, bold emphasis, bullet list, and horizontal rule) and still had to add a picture and caption to get it approved.

**Comment by jeevast** [comment]
@SNutakki it's recommend you have 5 to give best impression. but, more than 3 is a better statement for least case.

**Comment by Liew211** [comment]
@SNutakki Might as well change it to 5.  To make it more clear, I'd recommend that you say "5 *different* markdown elements"
