### ISSUE TITLE
Course Manual

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/open-learning-exchange.github.io#2360]
**NOTE:** If it is too big to work on you can even push once part of it is complete.

Should be made on file `pages/manual/planet/course.md`
Page should contain explanation about
* Getting to Courses page
  * From **Menu**
  * From **Dashboard Tile**
* List of Courses
* Different actions on list page
  * Action Menu
  * Rating
  * Selection
  * Add to myCourse
  * Removing from myCourse
  * Filter/Search
  * Pagination
* Adding Course
   * Concept of Steps
   * Linking Resource
   * Adding Exam
   * Adding Survey
* Using collection of course
* Course View
   * Taking exam
   * Taking survey

**Comment by lmmrssa** [comment]
Reference
https://docs.moodle.org/37/en/Main_page
https://docs.moodle.org/37/en/Manual_enrolment

**Comment by sjson421** [comment]
@lmmrssa What is meant by "List of Courses" here?

**Comment by Liew211** [comment]
@sjson421 I'm pretty sure it means the list view of the courses

**Comment by sjson421** [comment]
@Liew211 Yeah I was just confused on what I would need to explain here.
