### ISSUE TITLE
Team Manual

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/open-learning-exchange.github.io#2361]
**NOTE:** If it is too big to work on you can even push once part of it is complete.

Should be made on file `pages/manual/planet/team.md`
Page should contain explanation about
* Getting to Team page
  * From **Menu**
  * From **Dashboard Tile**
* All Member feature
* Different actions on list page
  * Add to team
  * Leaving team
  * Filter/Search
  * Pagination
* Adding Team
* Manage Team
   * Adding member
   * Adding course to team
   * Accepting member
   * Adding Message in team

**Comment by lmmrssa** [comment]
Reference
https://docs.moodle.org/37/en/Main_page
https://docs.moodle.org/37/en/Manual_enrolment

**Comment by samuelchen1213** [comment]
@lmmrssa What does "All Member feature" include?
