### ISSUE TITLE
Achievement Manual

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/open-learning-exchange.github.io#2365]
Should be made on file `pages/manual/planet/achievement.md`
Page should contain explanation about
* Getting to Achievement page
  * From **Dashboard Tile**
  * From **Member Profile**
* Add/Edit Achievement
   * Adding reference
   * Adding Achievement
   * Attaching Resources

**Comment by lmmrssa** [comment]
Reference
https://docs.moodle.org/37/en/Main_page
https://docs.moodle.org/37/en/Manual_enrolment

**Comment by samuelchen1213** [comment]
@lmmrssa I cannot access achievements on profile. And on the achievements page, I cannot add any achievements.
<img width="1236" alt="Screen Shot 2019-06-08 at 2 47 01 PM" src="https://user-images.githubusercontent.com/43349314/59151163-4c841800-89fc-11e9-8c9f-79fa59091b65.png">
<img width="1271" alt="Screen Shot 2019-06-08 at 2 46 47 PM" src="https://user-images.githubusercontent.com/43349314/59151165-4ee67200-89fc-11e9-9ea5-6baeb224b8f0.png">

**Comment by lmmrssa** [comment]
@samuelchen1213 are you running production version or dev version? Also Achievement is available on your dashboard.

**Comment by samuelchen1213** [comment]
@lmmrssa This is production version
