### ISSUE TITLE
Manager Manual

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/open-learning-exchange.github.io#2367]
Should be made on file `pages/manual/planet/manager.md`
Page should contain explanation about
* Detail about Manager role
* Getting to Manager Dashboard page
* Different features in Manager Dashboard
* Looking all members
* Promote/Demote member
* Syncing data with nation

**Comment by lmmrssa** [comment]
Reference
https://docs.moodle.org/37/en/Main_page
https://docs.moodle.org/37/en/Manual_enrolment

**Comment by DavidMcKissick** [comment]
This would definitely be a useful set of changes
