### ISSUE TITLE
Library and resources overview grammatical errors

### ISSUE THREAD

**Issue by DavidMcKissick** [open-learning-exchange/open-learning-exchange.github.io#2370]
### Problem
There are a few minor errors on the page "Library and Resources Overview" accessed via Tech geniuses>Content and library management. 

These include "sub-set" vs "subset" and a typo with 2 duplicate "the" instances next to each other.

### Steps to reproduce the problem
See "Tech Geniuses" > Content and library management. 

### Screenshots

![ca1](https://user-images.githubusercontent.com/25361438/59072219-a0fd8b00-8876-11e9-8421-c767c49fe04e.PNG)
---
![ca2](https://user-images.githubusercontent.com/25361438/59072220-a0fd8b00-8876-11e9-958d-4e33f981221e.PNG)

### Proposed solution

A simple rewrite of the instances in question to "subset" and "make of the library"

**Comment by sjson421** [comment]
You can work on this.
