### ISSUE TITLE
Clarify community updates in the Planet Tutorial

### ISSUE THREAD

**Issue by SNutakki** [open-learning-exchange/open-learning-exchange.github.io#2372]
### Problem
The first paragraph says to get help if any of the three buttons are missing. This is not necessary if "Fetch Items" is missing.

There are also a few instances where "update" is mentioned where it would be clearer to use "upgrade" (due to how it's referred to on Planet).

### Steps to reproduce the problem

N/A

### Screenshots

![Screen Shot 2019-06-07 at 10 08 29 AM](https://user-images.githubusercontent.com/13606819/59121255-73632100-890c-11e9-980a-275acf568083.png)

### Proposed solution

Change the initial paragraph to:
'There are three important kinds of updates that you may receive on the community side: upgrades, resources/courses and sync. Go to your Manager page and search for the buttons highlighted in the picture below. You may not see the Fetch Items button if nation has not sent anything to the community. If you do not see the other two highlighted buttons, post a message to the Gitter Chat channel to get help.'

Additionally, replace instances of 'update' with 'upgrade' as necessary to make the tutorial consistent with Planet.

It might also be a good idea to change the 3rd item below the pictures to just:
"If Fetch Items is available on the Manager page, click on it and download the courses offered (2nd picture)."
The note at the end of the 3rd item might not be necessary if we change the 1st paragraph.

**Comment by sjson421** [comment]
Sounds good to me, but I want to have someone else also give an approval. Probably @lmmrssa

**Comment by DavidMcKissick** [comment]
This is definitely a needed change, it has already caused some confusion in the gitter.

**Comment by Liew211** [comment]
I’d suggest that you come up with a rewrite that doesn’t make the steps afterward repetitive, go ahead with a fix.
