### ISSUE TITLE
vi-first-steps.md English quality fixes

### ISSUE THREAD

**Issue by DavidMcKissick** [open-learning-exchange/open-learning-exchange.github.io#2373]
### Problem
There are a handful of issues with the English grammar and syntax within the first steps page. These include lack of hyphenation (high-quality), and 3 article issues (E.G. "complete the step 3 you will" is incorrect.) Specific instances in screenshots.

### Steps to reproduce the problem

N/A

### Screenshots

![ca1](https://user-images.githubusercontent.com/25361438/59138019-788d9380-893f-11e9-9633-52ad9bfeb2e1.PNG)
---
![ca4](https://user-images.githubusercontent.com/25361438/59138020-788d9380-893f-11e9-8a95-4845052bdee9.PNG)
---
![ca3](https://user-images.githubusercontent.com/25361438/59138021-788d9380-893f-11e9-86e3-dc6b12bcba72.PNG)
---
![ca2](https://user-images.githubusercontent.com/25361438/59138023-788d9380-893f-11e9-9379-2b3a1ca4af0d.PNG)

### Proposed solution

Fixing syntax issues in vi-first-steps.md

**Comment by DavidMcKissick** [comment]
I'll be working on this one once I get approval.

**Comment by Liew211** [comment]
I don’t think the hyphenation is necessary, but the other changes are good.

**Comment by DavidMcKissick** [comment]
Thanks, I'll get on it. That said here's a Grammarly article on proper use of hyphens in compound words: https://www.grammarly.com/blog/hyphen-in-compounds-with-high-low/

**Comment by Liew211** [comment]
Huh, thanks for the tip, I wasn’t aware of that.  Go ahead with the hyphen then 👍🏻
