### ISSUE TITLE
Suggestion for "First Steps" instructions - OLE/forked/cloned repositories and actions

### ISSUE THREAD

**Issue by ghost** [open-learning-exchange/open-learning-exchange.github.io#238]
![image](https://cloud.githubusercontent.com/assets/20692531/17386169/f7375214-59b5-11e6-810b-dd22e455b993.png)

Rough draft OLE/forked/cloned repositories and actions

**Comment by rachelpei** [comment]
[flow-chart_repositories.pptx](https://github.com/open-learning-exchange/open-learning-exchange.github.io/files/400606/flow-chart_repositories.pptx)

**Comment by aberdean** [comment]
No longer relevant (already included in first steps).
