### ISSUE TITLE
FAQ "how to preview changes" spelling error

### ISSUE THREAD

**Issue by AlekseiKorolev** [open-learning-exchange/open-learning-exchange.github.io#2383]
### Problem
Instead Faceb***o***k need Faceb***oo***k

### Steps to reproduce the problem
Change word spelling

### Screenshots
![2019-06-09_05-58-58](https://user-images.githubusercontent.com/42728999/59154854-2900b200-8a7c-11e9-96d5-cd92fa95b122.png)

**Comment by Liew211** [comment]
@AlekseiKorolev This page is linked from one of our first steps, but is not actually OLE's.  Please try to find an issue within open-learning-exchange.github.io
