### ISSUE TITLE
Confusion with the paths to install planet

### ISSUE THREAD

**Issue by AlekseiKorolev** [open-learning-exchange/open-learning-exchange.github.io#2384]
### Problem
In Step1 > Planet Installation > Prerequisites offer to make dir "OLE" on desktop
In Step 1 > Vagrant Tutorial > Stay at the Right Directory offer to have dir in path *C:\Users\YOUR_USERNAME\planet*

### Steps to reproduce the problem
Choose one of

### Screenshots
![issue2](https://user-images.githubusercontent.com/42728999/59155040-e93bc980-8a7f-11e9-979e-8b8c32b6fd9c.png)

**Comment by Liew211** [comment]
@AlekseiKorolev `planet` is the name of the repository, so that will remain the same regardless.  I'm on macOS, but I'm pretty sure the file path on Windows should be `C:\Users\YOUR_USERNAME\desktop\OLE\planet`, please correct me if I'm wrong?

**Comment by Liew211** [comment]
Again, at this point planet should have been installed already through `git clone`

**Comment by AlekseiKorolev** [comment]
> 
> 
> @AlekseiKorolev `planet` is the name of the repository, so that will remain the same regardless. I'm on macOS, but I'm pretty sure the file path on Windows should be `C:\Users\YOUR_USERNAME\desktop\OLE\planet`, please correct me if I'm wrong?
You're right

**Comment by Liew211** [comment]
@AlekseiKorolev ok in that case, you can go ahead and work on this issue.

**Comment by AlekseiKorolev** [comment]
@Liew211 Ok, I'm on it
