### ISSUE TITLE
vi-github-issues.md english and clarity QOL changes

### ISSUE THREAD

**Issue by DavidMcKissick** [open-learning-exchange/open-learning-exchange.github.io#2385]
### Problem
There are numerous issues within the document. Notable examples include:
* > If you notice something, but are not sure how to solve it
Unnecessary comma between something and but.

* > working on these issue,
these issue vs these issue**s**

* > sync your repo using next commands:
Grammar is incorrect

There are a few other examples in the document that need fixes for clarity and writing quality.

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Rewritting some paragraphs for clarity (Already available issues subsection,) Fixing one off English errors.

**Comment by DavidMcKissick** [comment]
I'll get this one done asap after approval

**Comment by Liew211** [comment]
@DavidMcKissick Go ahead
