### ISSUE TITLE
vi-faq.md english QOL fixes

### ISSUE THREAD

**Issue by DavidMcKissick** [open-learning-exchange/open-learning-exchange.github.io#2386]
### Problem
3 issues that I caught. 

~~1. 16 hour should be hyphenated (word compounding)~~ CORRECTION: This was incorrect, I misremembered a rule. Thanks to @ChiragAwale for reminding me.
2. virtualbox (Product names should be capitalized per the branding. In this case VirtualBox)
3. > of the standardized development environment that Vagrant/VirtualBox provide, (This should be ***provides*** instead of provide.)

This one is pretty small but I'm mostly going through the wiki looking for QOL fixes to increase the overall wiki quality.

### Steps to reproduce the problem

N/A

### Screenshots

![ca2](https://user-images.githubusercontent.com/25361438/59163318-47829f80-8ab4-11e9-9208-307bc38d399c.PNG)
![ca3](https://user-images.githubusercontent.com/25361438/59163319-47829f80-8ab4-11e9-8df7-caf4dc32106c.PNG)
![ca1](https://user-images.githubusercontent.com/25361438/59163320-47829f80-8ab4-11e9-8055-605d307cf38c.PNG)

### Proposed solution

Fixing these minor issues in the document (16 hour>16-hour, virtualbox>VirtualBox, provide>provides)

**Comment by DavidMcKissick** [comment]
I'm not entirely sure on provide vs provides so any input is helpful, thanks.

**Comment by ChiragAwale** [comment]
According to the screenshot, provides would be better I believe but I don't really think word compounding is necessary for this situation.

**Comment by DavidMcKissick** [comment]
Ah yea sorry I just remembered in this case it's not a direct adjective. Thanks for the input

**Comment by Liew211** [comment]
@DavidMcKissick Sorry just saw this, go ahead with the changes.
