### ISSUE TITLE
Bug in "take test buttons" and navigating between questions in virtual interns course

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/open-learning-exchange.github.io#2387]
## Problem
While clicking on the *Take Test* button it just anchors to a **_div_** a little above the button and does not take us to the *testing page*, One way to actually get to the step is by *clicking on the view step* on the top right part of the course navigation section.

#### Similar Problem
The other problem that is closely related is that first 8 questions can be navigated to with the help of the arrows but we cannot get to the 9th question after that as the next arrow gets disabled while we can move back to 8 from 9.

### Steps to reproduce the problem

N/A

## Before clicking on  _Take test_  button
<img width="1411" alt="Screen Shot 2019-06-07 at 1 53 03 PM" src="https://user-images.githubusercontent.com/19680263/59163224-badfdd80-8ac3-11e9-923f-ecb78b97ee8b.png">

## After clicking on _Take test_  button
<img width="1394" alt="Screen Shot 2019-06-06 at 6 28 48 PM" src="https://user-images.githubusercontent.com/19680263/59163225-be736480-8ac3-11e9-8567-c10a379e78ee.png">

## Arrow to question 9 is disabled
<img width="1428" alt="Screen Shot 2019-06-07 at 1 54 49 PM" src="https://user-images.githubusercontent.com/19680263/59163226-c7fccc80-8ac3-11e9-8554-2e89b6e00c87.png">

## Arrow to question 8 is available
<img width="1428" alt="Screen Shot 2019-06-07 at 1 56 51 PM" src="https://user-images.githubusercontent.com/19680263/59163231-cfbc7100-8ac3-11e9-8203-bdfe2d4515c6.png">

### Proposed solution

* Fix the broken links on the take test button
* Make the 8th arrow point towards question 9

**Comment by lmmrssa** [comment]
@ChiragAwale this is not an issue. you can only move between steps when exam of step is complete. It is not question that you are navigating.
Closing issue
