### ISSUE TITLE
A small suggestion regarding adding a link on Step 3

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/open-learning-exchange.github.io#2393]
#### It is not really a problem but having a link for confirming the number of pull requests made right below the point listing (In the screenshot) 
* Once you complete Step 3 you will have: 
   * 1 Pull request made
### Steps to reproduce the problem

N/A

### Screenshots

<img width="887" alt="Screen Shot 2019-06-10 at 5 18 10 PM" src="https://user-images.githubusercontent.com/19680263/59230838-652f3200-8ba4-11e9-9799-f52b3f5013ee.png">

### Proposed solution

Adding this link [Check here](http://open-learning-exchange.github.io/#!pages/vi/vi-track-progress.md)

**Comment by DavidMcKissick** [comment]
This would definitely be a strong quality of life change

**Comment by Liew211** [comment]
@ChiragAwale Go ahead with the fix.

**Comment by lmmrssa** [comment]
Not required :)

**Comment by ChiragAwale** [comment]
Okay :) @lmmrssa
