### ISSUE TITLE
Small grammar fix in Vagrant Tutorial

### ISSUE THREAD

**Issue by hiroTochigi** [open-learning-exchange/open-learning-exchange.github.io#2397]
### Problem
Minor grammar errors in Vagrant Tutorial
Before: some basic instruction
After: some basic instructions

Before: **Git Bash**: This is our recommended command line program. GitBash is already installed along with planet installation script. After you open **Git Bash** ...

After: **Git Bash**: This is our recommended command line program. **Git Bash** is already installed along with planet installation script. After you open **Git Bash** ...

### Steps to reproduce the problem

N/A

### Screenshots

#![Grammer Error](https://user-images.githubusercontent.com/44413241/59234349-0ec8f000-8bb2-11e9-96ee-c902546e71d0.png)

## Proposed solution

Fix these errors

**Comment by Liew211** [comment]
@hiroTochigi Go ahead with the fix.
