### ISSUE TITLE
Confusion in FAQ Questions Q15 and Q16

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/open-learning-exchange.github.io#2405]
### Problem
  When I was going over the FAQ sections of VI, on  **question 15** I saw that the answer says to delete the repo and start over in case of a spelling error. But the next question, which is **16** says we can rename the repository in a similar circumstance. I might be mistaken but I believe that we can definitely rename the repository in the situation of question 15. 

_Please do correct me if I am wrong._

### Steps to reproduce the problem

N/A

### Screenshots

<img width="847" alt="Screen Shot 2019-06-10 at 11 10 20 PM" src="https://user-images.githubusercontent.com/19680263/59243467-ccb1a580-8bd5-11e9-81f2-9565d1d22660.png">

### Proposed solution

* Update the answer on question 15.

**Comment by lmmrssa** [comment]
@ChiragAwale **Q15** is when you do not have any repository under username.github.io
where as **Q16** is when you already have another repository under username.github.io so you need to have another name for ole project.

Yes it could be possible to rename old repository but it will be clean as well as simple if you delete repository and fork again. You can update it stating that **it is possible to rename but you can delete and have a clean start by .....**

**Comment by ChiragAwale** [comment]
Got it, thank you so much. :D
