### ISSUE TITLE
Small grammar fixes in the Planet Configurations tutorial 

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/open-learning-exchange.github.io#2406]
### Problem
Potential grammatical errors were found in the screenshot below.

### Steps to reproduce the problem
N/A

### Screenshots

![Alt text](https://user-images.githubusercontent.com/19641684/59243942-726a1200-8be0-11e9-9b97-07dd6756b6ab.jpg)

### Proposed solution
Here is a suggested fixed for the issues. 

Next, you will see a form that requires the contact details for the administrator (maintainer) of the community. The information provided should be your contact details.

**Comment by ChiragAwale** [comment]
The '**a**' is required whereas from my understanding we can use either '**for**' or '**of** 'before administrator and a '**the**' is good to place there.

**Comment by ChiragAwale** [comment]
Also I would suggest the second sentence to be something like '**Provide your contact information.'**

**Comment by Liew211** [comment]
@ChiragAwale Looks good, go ahead with the fix.

**Comment by perryc85** [comment]
I can make changes.

Charles J. Perry
Seidenberg School of Computer Science and Information Systems | M.S. Computer Science | 2019
(914) 406 - 3852 | charles.j.perry@pace.edu<mailto:charles.j.perry@pace.edu>

________________________________
