### ISSUE TITLE
Small grammatical errors in Planet Installation with vagrant section

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/open-learning-exchange.github.io#2411]
### Problem
Small grammatical errors in _Planet installation with Vagrant section_ of **Step 1.**

**In "For Ubuntu"** 
Refer this image - > Refer **to** this image  

**In Windows under Dependencies**
You need to install following programs on your computer:
 -> You need to install  **the** following programs on your computer:

### Steps to reproduce the problem

N/A

### Screenshots

<img width="841" alt="Screen Shot 2019-06-11 at 8 06 08 PM" src="https://user-images.githubusercontent.com/19680263/59316559-bd3d6580-8c84-11e9-8ce2-5a69d1b010ae.png">

<img width="872" alt="Screen Shot 2019-06-11 at 8 03 46 PM" src="https://user-images.githubusercontent.com/19680263/59316560-bd3d6580-8c84-11e9-8477-0e0450fea368.png">

### Proposed solution

Add the preposition and the article in the respective places.

**Comment by ScottHuangNYU** [comment]
Good eye, please work on it.

**Comment by ChiragAwale** [comment]
@ScottHuangNYU Sure. :D
