### ISSUE TITLE
Same style for sentence in second item in step 0

### ISSUE THREAD

**Issue by AlekseiKorolev** [open-learning-exchange/open-learning-exchange.github.io#2413]
### Problem
For consistency need wrap in link word "Follow" in paragraph 2
It was --> In GitHub, we ["Watch"][1] organization repositories and "Follow" individuals.
has become --> In GitHub, we ["Watch"][1] organization repositories and [**"Follow"**][2] individuals.

Alternative solution - remove the link with the word **"Watch"**

### Steps to reproduce the problem
Wrap word in link  _https://help.github.com/en/articles/following-people_

### Screenshots
![issue3](https://user-images.githubusercontent.com/42728999/59320800-ea633580-8ccf-11e9-8233-03572885df84.png)

[1]: https://help.github.com/en/articles/watching-and-unwatching-repositories
[2]: https://help.github.com/en/articles/following-people

**Comment by samuelchen1213** [comment]
Looks good! PIease work on this.
