### ISSUE TITLE
Planet installation; terms lunux/ubuntu shell/terminal Macintosh/masOs

### ISSUE THREAD

**Issue by AlekseiKorolev** [open-learning-exchange/open-learning-exchange.github.io#2414]
### Problem
Just one place in this page mentioned _linux_ and in others cases _ubuntu_, just like in the case _shell_ - _terminal_ accordingly. Тhe explanation would be clearer if one term was used
The same things about _Macintosh_ and _masOs_

#### First  
Original text 
...Or you could open `Terminal`(macOS), `cmd`(Windows), or `Shell`(Linux) and use..

Change linux --> ubuntu and shell --> terminal 
* ...Or you could open `Terminal`(macOS), `cmd`(Windows), or **`Terminal`(Ubuntu)** and use..
* ...Or you could open `Terminal`(macOS **and** **Ubuntu**), `cmd`(Windows) and use..

Preferred last option because the systems masOS and Ubuntu are considered together further in the document.

#### Second
Original text 
...If so, here are instructions to enable virtualization on Windows | Ubuntu | Macintosh...

Change Macintosh --> macOS
...If so, here are instructions to enable virtualization on Windows | Ubuntu | **macOS**...

### Screenshots
![issue4_1](https://user-images.githubusercontent.com/42728999/59323633-cc9bcd80-8cdb-11e9-971c-05d8f7546239.png)
![issue4_2](https://user-images.githubusercontent.com/42728999/59323637-cefe2780-8cdb-11e9-8349-009ee10ceee9.png)

**Comment by Liew211** [comment]
@AlekseiKorolev You can work on this.

**Comment by ChiragAwale** [comment]
Yes using one term would make it clearer. Nice one.
