### ISSUE TITLE
Grammatical error/typo - Nation Planet (Step 7)

### ISSUE THREAD

**Issue by ArranHL** [open-learning-exchange/open-learning-exchange.github.io#2416]
### Problem
There are three grammatical errors in the "Update your community" section of the Nation Planet (Step 7):

![image](https://user-images.githubusercontent.com/47016295/59383880-1dccb100-8d1e-11e9-991d-43c0e262f800.png)

### Steps to reproduce the problem

Go to http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md

### Screenshots

![Annotation 2019-06-12 132428](https://user-images.githubusercontent.com/47016295/59383780-dd6d3300-8d1d-11e9-8a8a-f7e54a1abfbc.jpg)

### Proposed solution

Simple change to text

**Comment by ChiragAwale** [comment]
Good eye, there is another one too near the last line. It should be 'exists'. 
<img width="947" alt="Screen Shot 2019-06-12 at 3 55 04 PM" src="https://user-images.githubusercontent.com/19680263/59385991-355e6680-8d2b-11e9-9b75-dcfade882119.png">
 :D.

**Comment by ArranHL** [comment]
Pull request [#2420](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/2420#issue-287705419) addresses this issue.

**Comment by ArranHL** [comment]
> Good eye, there is another one too near the last line. It should be 'exists'.
> <img alt="Screen Shot 2019-06-12 at 3 55 04 PM" width="947" src="https://user-images.githubusercontent.com/19680263/59385991-355e6680-8d2b-11e9-9b75-dcfade882119.png">
> :D.

Thanks for the extra pair of eyes, I've included it in the change :)
