### ISSUE TITLE
Make Note in Introduction of Nation Planet Tab (Step 7) clearer

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/open-learning-exchange.github.io#2419]
### Problem
I think if the wordings of the **Note:** in _Introduction_ section of _Nation Planet tab(Step 7)_ were like this. It would be much clearer and more efficient.

**Current :**
After you register your community, but before you can sync with the nation, you need to create an additional dummy user on your community. Therefore, create a quick additional user under "Become a Member" on the login page (HINT: When creating the dummy user, don't give it a password that you actually use).

**Update:**
Before you can sync your community with the nation, you will need to create an additional dummy user on your community. Therefore, create one by clicking on "Become a Member" under the SIGN-IN button. Then fill out the details and press the "Become a Member" button. (Tip: When creating the dummy user, don't put a password that you actually use). 

### Steps to reproduce the problem

N/A

### Screenshots

<img width="846" alt="Screen Shot 2019-06-12 at 4 13 54 PM" src="https://user-images.githubusercontent.com/19680263/59388586-c5071380-8d31-11e9-9ea6-54719a0756da.png">

### Proposed solution

Change the wordings.

**Comment by jeevast** [comment]
Please, go ahead with the change.

**Comment by ChiragAwale** [comment]
@jeevast Done! :D . Please have a look at the pull request.
