### ISSUE TITLE
Grammatical errors - Vagrant Tutorial

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/open-learning-exchange.github.io#2423]
### Problem
There are a couple of grammatical errors in the "Stay at the Right Directory" section of the tutorial. Please review the screenshot below to see what they are. 
I also made some style changes. Please review the proposed solution section of this document to see my edits. 

### Steps to reproduce the problem

N/A

### Screenshots

![Alt text](https://user-images.githubusercontent.com/19641684/59399362-b33d6480-8d61-11e9-86a5-3cb9bb06305e.PNG)

### Proposed solution

**Original**: 
## Stay at the Right Directory. 

A lot of Vagrant commands require us to specify a target machine or run from a directory with target machine's Vagrantfile, otherwise you might encounter error like "A Vagrant environment or target machine is required." Please go to the directory that contains our Vagrantfile:
- Windows user: `cd C:\Users\YOUR_USERNAME\Desktop\OLE\planet`
- macOS or Linux user: `cd` to where you `git clone` the `planet` repository in Step 1 - Planet Installation

**Suggestion**: 
## Stay in the Right Directory.

A lot of Vagrant commands require us to specify a target machine. We can also run those commands from a directory with the target machine’s Vagrant File. Otherwise, you may encounter an error like "A Vagrant environment or target machine is required." Please go to the directory that contains our Vagrant file:
- Windows users should: `cd C:\Users\YOUR_USERNAME\Desktop\OLE\planet` 
- macOS or Linux users should: `cd` into the location where they ran `git clone` to copy the `planet` repository back in Step 1 - Planet Installation.

**Comment by Liew211** [comment]
@perryc85 You can work on this.

**Comment by perryc85** [comment]
@Liew211 Sure thing. Thank you for looking.
