### ISSUE TITLE
Add question in FAQ

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/open-learning-exchange.github.io#2431]
### Problem
Adding and answering a question that solves the problem I and @perryc85  had, and maybe a lot of others might have **when trying to create a dummy account in step 7.**

The few steps taken from the Troubleshooting guide as guided by @lmmrssa  helped out a lot. I would like to make it easier for anyone else who would face the issue and save the trouble for admins of giving the solutions every time.

**A good question would be:**
 I cannot create a dummy account. My community does not sync with the nation. _Tips requested for the question to be put. Thanks in advance_
**The steps that I used that worked are:** 

**Note: Before trying the steps below, make sure your planet is up to date.**
```
cd planet
git pull
```
**Then,** 
```
vagrant halt prod 
vagrant up prod.
```

**If it still does not work please follow the steps below. Assuming you are already in the planet directory,**
```
vagrant ssh prod
cd /vagrant
sudo rm -rf node_modules/*
sudo npm install --unsafe-perm
```

**If this too does not work.** 
```
cd planet 
vagrant destroy prod
```
Please follow the instructions [here](http://open-learning-exchange.github.io/#!pages/vi/vi-planet-installation-vagrant.md) to reinstall planet. (**Warning!** this wipes all your progress in the virtual intern course as well.)

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Add a question and its answer in the FAQ section.

**Comment by perryc85** [comment]
Excellent idea. I think we should also include this in the actual tutorial as a troubleshooting section.

**Comment by ArranHL** [comment]
Yep seems like a good call, especially in the instance of multiple users encountering the same issue.

**Comment by ChiragAwale** [comment]
@Liew211 @dogi @lmmrssa Any feedbacks?

**Comment by Liew211** [comment]
@ChiragAwale this looks good, you can work on this.  I suggest that you include other troubleshooting tips as well, such as making sure your planet is up to date, restarting planet with `vagrant halt prod` `vagrant up prod`, doing a hard refresh with `command+shift+r` or `control+shift+r`, and pulling latest planet code with `cd planet` and `git pull`.

**Comment by perryc85** [comment]
Maybe we should put this in the actual tutorial as well?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Liew211** [comment]
@perryc85 the FAQ page is already linked at the bottom of the pages, in the "Helpful Links" section, so I don't think this is too necessary.

**Comment by perryc85** [comment]
Okay. That makes more sense.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ChiragAwale** [comment]
@Liew211  Got it. WIll include those too, thank you. I want to wait for one other admin to approve this so I can start working on it

**Comment by ChiragAwale** [comment]
@Liew211  Please check the updated Note above

**Comment by DavidMcKissick** [comment]
Not an admin but another VI like liew, go ahead and work on it with @Liew211 notes.

**Comment by ChiragAwale** [comment]
@DavidMcKissick Thank you. Got it :D.

**Comment by ChiragAwale** [comment]
@Liew211 @DavidMcKissick @lmmrssa  @sjson421 @dogi @jeevast Please look at the updated issue. Thank you. Any feedback is appreciated.
