### ISSUE TITLE
Two different user/planet names in use

### ISSUE THREAD

**Issue by ArranHL** [open-learning-exchange/open-learning-exchange.github.io#2433]
### Problem
Planet is showing two different user/planet names in use. 
I originally created a planet called ArranL however as it was not approved I created a second, ArranHL

### Steps to reproduce the problem

Simply logging in to my http://localhost:3100/eng/
Can also be seen on https://planet.vi.ole.org/eng/

### Screenshots
It seemed that the ArranL credential were those approved in the system as ArranHL is not recognized as a registered member:

![arranhl not registered ](https://user-images.githubusercontent.com/47016295/59530601-429d6180-8ea1-11e9-9957-5caab26c4e29.jpg)

Logging in with these credentials works fine:

![arranl logged in](https://user-images.githubusercontent.com/47016295/59530768-a4f66200-8ea1-11e9-8da6-3eff1fa96471.jpg)

However the activity for this profile is recorded as ArranHL

![Arran HL activity](https://user-images.githubusercontent.com/47016295/59530847-d3743d00-8ea1-11e9-9377-e31989abb963.jpg)

And  https://planet.vi.ole.org/eng/ recognizes arranl@arranhl

![arranl@arranhl](https://user-images.githubusercontent.com/47016295/59530872-e424b300-8ea1-11e9-9a41-34f0cf972520.jpg)

Which leads me to believe my login credentials are different from my planet 

### Proposed solution

Re-naming my planet or having ArranHL approved as an Admin

**Comment by ArranHL** [comment]
As an alternative and perhaps simpler solution, removing ArranL as a planet value should allow the planet name to be changed:
![image](https://user-images.githubusercontent.com/47016295/59531817-38309700-8ea4-11e9-9aa4-165f59ea398c.png)

**Comment by Liew211** [comment]
@ArranHL The username that you use to login is different from the name of the community that you set in the configuration.

**Comment by ArranHL** [comment]
> @ArranHL The username that you use to login is different from the name of the community that you set in the configuration.

@Liew211 so is this not an issue?

**Comment by Liew211** [comment]
@ArranHL that is correct.  The username you use to log in should be unique among members in your community, but the name on the configuration page is the name of the community itself, and therefore only needs to be unique among the other communities.  The username and community name can be the same for convenience, but if you recreate your planet you will need to make a new name for your new community.

**Comment by ArranHL** [comment]
@Liew211 wonderful! Thanks!
