### ISSUE TITLE
Adding missing step to Planet Installation

### ISSUE THREAD

**Issue by ArranHL** [open-learning-exchange/open-learning-exchange.github.io#2434]
### Problem
Within the Planet Installation the virtualization step states:

"Before installing Vagrant on any platform, it is necessary to check if VT-x/AMD-V instruction set is enabled on your processor by checking the BIOS. This is a requirement for installing Vagrant on any platform since Vagrant is a type of virtualization software that utilizes VirtualBox."

However, steps to check if VT-x/AMD-V are enabled is not provided, which could cause confusion.

### Steps to reproduce the problem

Head over to http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md

### Screenshots

![image](https://user-images.githubusercontent.com/47016295/59554162-36c2a580-8f5c-11e9-8014-d4830fe92e31.png)

### Proposed solution

I suggest that three separate links be provided for potential VI's to check if their system has VT-x/AMD-V enabled.
 
I think the following links could help with this:
 
[Windows](https://techiesdigest.com/how-to-check-if-virtualization-is-enabled/)
 
[Ubuntu](https://www.cyberciti.biz/faq/linux-xen-vmware-kvm-intel-vt-amd-v-support/)
 
[Mac](https://apple.stackexchange.com/questions/224870/how-to-check-vt-x-status-on-macbook-pro/224879)

**Comment by DavidMcKissick** [comment]
Good idea, Go ahead and work on it.
