### ISSUE TITLE
Note on forward and back slashes in 

### ISSUE THREAD

**Issue by ArranHL** [open-learning-exchange/open-learning-exchange.github.io#2435]
### Problem
In the "Vagrant Tutorial" section of the first steps, the recommended Windows –   command line program is Git Bash. 
 
However, further down the page in the "Stay in the Right Directory" section, the provided way of going to your directory is:
cd C:\Users\YOUR_USERNAME\Desktop\OLE\planet
 
Which utilizes back and not forward slashes, this way of getting to the directory absolutely works in Git Bash for windows, however most subsequent documentation VI's will encounter within the internal OLE steps and external docs will rely on using forward slashes.

### Steps to reproduce the problem

Head on over to http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md 

### Screenshots

![image](https://user-images.githubusercontent.com/47016295/59554523-69bb6800-8f61-11e9-9ff6-a07f5750a244.png)

### Proposed solution

Firstly, I recommend making a distinction between PowerShell/Command Prompt and Git Bash early on as to not confuse VI's and introduce forward slashes early.
 
 In the "Stay in the Right Directory" section we should provide two options: 

Windows PowerShell/Command Prompt users should: 
 cd C:\Users\YOUR_USERNAME\Desktop\OLE\planet
 
Windows Git Bash users should: 
C/Users/YOUR_USERNAME/Desktop/OLE/planet

Secondly a note should be added at the bottom of the “Preparation Windows – Pick your command line program” section that notes the distinction between PowerShell/Command Prompt and Git Bash directories. 

“Note: PowerShell and Command Prompt users will have to substitute forward slashes “/” for  backslashes “\” throughout these introductory steps as it pertains to file paths. “

**Comment by DavidMcKissick** [comment]
Sounds good but I feel like I should get a second opinion from somebody who's been here a bit longer on this one. @Liew211 what are your thoughts here?

**Comment by ArranHL** [comment]
@DavidMcKissick I created a PR #2440 for this but in the event it's a no go that's ok :)

**Comment by Liew211** [comment]
@ArranHL @DavidMcKissick  I think this is a pretty good fix, since Git Bash uses the Linux directory stye.

**Comment by Liew211** [comment]
@ArranHL Also, the note is incorrect; it should be Git Bash users, not Powershell or Command Prompt.

**Comment by ArranHL** [comment]
> note is incorrect; it should be Git Bash users, not Powershell or Command Prompt

Well although the file directories are provided as standard windows filepathes in this section, the rest of the instructions as it pertains to code throughout on-boarding steps seems to be for Git Bash users, 
@Liew211 would you like me to change it around in #2440 ?
