### ISSUE TITLE
Moving note in GitHub Issues

### ISSUE THREAD

**Issue by ArranHL** [open-learning-exchange/open-learning-exchange.github.io#2441]
### Problem
In GitHub Issues - Step 6:
The note and provided link to discarding local changes is placed after the section on commiting changes and I think it would be better to place this before as this is applicable only before committing the change.

### Steps to reproduce the problem

Go to https://open-learning-exchange.github.io/#!pages/vi/vi-github-issues.md 

### Screenshots

![image](https://user-images.githubusercontent.com/47016295/59566554-ff68fd00-901e-11e9-8d89-188e8bba9d67.png)

### Proposed solution

The Note should be moved above the Create a Commit and Push the Changes section

**Comment by hiroTochigi** [comment]
I think that it is a good idea.

**Comment by DavidMcKissick** [comment]
Good catch. Go ahead and work on it.
