### ISSUE TITLE
Step 3 Markdown and Fork Tutorial: Possible missing step

### ISSUE THREAD

**Issue by irisb1701** [open-learning-exchange/open-learning-exchange.github.io#2443]
### Problem
OLE > pages > vi > vi-github-and-markdown.md
On Step 3 (Markdown and Fork Tutorial) of First Steps, in the directions describing how to create a new markdown file, there is no final step indicating to "commit changes" when finished.

### Steps to reproduce the problem
N/A

### Screenshots
![issue](https://user-images.githubusercontent.com/16839815/59569023-d9108500-9051-11e9-9957-fc6ba34deb4a.jpg)

### Proposed solution
Include line and image demonstrating final step to commit changes when finished

![suggestedchange](https://user-images.githubusercontent.com/16839815/59569062-618f2580-9052-11e9-9ccc-3149069431ef.jpg)

**Comment by samuelchen1213** [comment]
Good catch! This will make it clearer, please work on this!
