### ISSUE TITLE
Grammatical error - GitHub and Markdown tutorial 

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/open-learning-exchange.github.io#2445]
### Problem

I caught a grammatical error while I was reading over the tutorial. 

I found it in the heading for the “Check if you github.io works” section. 

Please review the screenshot below to see what the error is.

I also made some style changes. 

Please review the proposed solution section of this document to see my edits.

### Steps to reproduce the problem

N/A

### Screenshots

![Alt text](https://user-images.githubusercontent.com/19641684/59570849-4204f680-906c-11e9-85be-8b33fdc9b52e.PNG)

### Proposed solution

**Original**:
# Check if you github.io works
After renaming your forked repository, go to `https://YourUserName.github.io` and make sure it works.

Don't worry if you see a **404** when you access the link, it will take a while for the page to be up and running. Make sure in **Settings > GitHub Pages**, the **source** is set to *__master__* branch.

**Suggestion**:
# Check if your github.io works
After renaming your forked repository, go to `https://YourUserName.github.io` and make sure it works.

Don't worry if you see a "**404** page not found error". When you access the link, it will take a while for the page to load and run. Make sure in **Settings > GitHub Pages**, the source is set to *__master__* branch.

**Comment by DavidMcKissick** [comment]
the word error in "404 page not found error" should be outside of the double quotes, but otherwise it looks good. Go ahead.

**Comment by perryc85** [comment]
Got it. Thank you for the feedback.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by perryc85** [comment]
Also made an additional edit to the heading. Instead of Check if your github.io works. I changed it to Check to see if your github.io works!
