### ISSUE TITLE
Step 7 Nation Planet: Dummy Account 

### ISSUE THREAD

**Issue by irisb1701** [open-learning-exchange/open-learning-exchange.github.io#2451]
### Problem
User is advised to log in to Dummy account in order to view it under the member section of the Manager tab

### Steps to reproduce the problem

View in Nation Planet the line that reads: 

"Then, login to dummy account you just created and double-check that you're listed under Members on Manager page. Then, log out and log back in with your admin account. " 

### Screenshots
N/A

### Proposed solution

Because there is no Manager section in the Dummy profile since it is not an admin page, the line should read: 

 "Next, log back in to your admin account and double-check that your dummy account is listed under Members on the Manager page."

**Comment by perryc85** [comment]
Good catch. The change will be helpful and essential for future interns that will complete the first steps.

**Comment by Liew211** [comment]
@irisb1701 good fix, you can work on this 👍
