### ISSUE TITLE
Step 1.2 Planet Configurations: Note on "become a member"

### ISSUE THREAD

**Issue by irisb1701** [open-learning-exchange/open-learning-exchange.github.io#2452]
### Problem
After registering as Admin, it should be noted to not select "become a member" when presented with the "sign in screen" below and to *log in only* with the admin credentials just created. In some cases where the admin credentials give an error like in the second screenshot, it might seem like selecting "become a member" may be a possible solution.

### Screenshots
![screenshotA](https://user-images.githubusercontent.com/16839815/59969676-9f43f080-9521-11e9-8541-d15cb22f5248.png)

![issue3](https://user-images.githubusercontent.com/16839815/59647994-5e2b9500-914b-11e9-8f04-25e4b3b8abd5.png)

### Steps to reproduce the problem
> Register as admin
> Click submit
> See *Sign In* screen 
> log in with credentials just created
> Get error message "member is not registered" (screenshot above)
> Select "become a member" as possible solution 
> System allows the creation of member profile even with the same admin credentials just previously registered a moment ago 
>User won't find out until step 4 that profile was created incorrectly

### Proposed solution
Include note on final step right before "Troubleshooting" section begins that says "if experiencing issues logging in with your newly created admin credential, do not select "become a member" and please read the troubleshooting options below.

**Comment by ChiragAwale** [comment]
Become a member is more like sign up thing so I am not sure if it requires a Troubleshooting section.

**Comment by irisb1701** [comment]
There already is a troubleshooting section, my suggestion is to just include a note before that section advising the user to not select become a member and keep reading below if having issues. The trouble shooting section then details how to destroy and rebuild the planet.

**Comment by lmmrssa** [comment]
It should be clear to login if user wants to use system and to become member if they are not. So it does not look like issue.
