### ISSUE TITLE
Step 6 Github Issues Tutorial: Git line of code 

### ISSUE THREAD

**Issue by irisb1701** [open-learning-exchange/open-learning-exchange.github.io#2453]
### Problem
More of a suggestion:

On step 6, the git line that reads

>git checkout -b <name_of_your_new_branch>

 may benefit from removing < & >. Not everyone will read them as place holders since git does use a lot of different characters as part of its commands while also being sensitive to proper formatting 

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Replace line to read:

>git checkout -b name_of_your_new_branch

**Comment by Liew211** [comment]
@irisb1701 good idea, go ahead with a fix.
