### ISSUE TITLE
Planet Configurations: Note on setting up account configurations 

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/open-learning-exchange.github.io#2454]
### Problem
**Suggestion**:

In step 2, new admins must complete the form to set up their account configurations. I understand there is a note below the first screenshot which states:
>Your name must be the same and should match your GitHub name, so we can easily locate your community in Virtual Intern Nation. 

I think we should add the note above the first screenshot. The change will prevent new admins from creating a username that is different from their GitHub username, *especially if they fail to read the note before moving on to the next step.* The change is also necessary since the username on the first form has to match the name on the second form. 

### Steps to reproduce the problem

N/A

### Screenshots
![Alt text](https://user-images.githubusercontent.com/19641684/59654954-81b00900-9166-11e9-8351-844d22bef072.PNG)

### Proposed solution

First, fill out the admin registration form below. Your chosen username should match your GitHub username. 

![Alt text](https://user-images.githubusercontent.com/19641684/59654642-25001e80-9165-11e9-932c-0c068c2f5f77.PNG)

Next, fill out the configuration's form. Your name must be the same as your username, so we can easily locate your community in the Virtual Intern Nation. Then select **(vi)** for the Nation(s) option. See the example below for additional details. **After filling out the form, remember to save a screenshot of the configuration page so you can post it on the [Gitter chat](https://gitter.im/open-learning-exchange/chat) after submitting your registration request.**

![Alt text](https://user-images.githubusercontent.com/19641684/59654796-cab38d80-9165-11e9-92b8-94e12fb89c37.PNG)

**Comment by Liew211** [comment]
@perryc85 This is not necessary. The username on the first page is simply used to log into planet, and can be anything you want.  The requirement is only for the second page, where the name is the name of your community, which is what will show up in the Virtual Intern Nation itself.

**Comment by perryc85** [comment]
@Liew211 Thanks for the feedback.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
