### ISSUE TITLE
Adding a note in the Planet Configuration’s troubleshooting section

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/open-learning-exchange.github.io#2460]
### Problem
I’d like to add a note about clearing cookies as a potential solution, following an issue I recently faced trying to access the planet. I wasn’t experiencing any of the other errors listed in the troubleshooting section, even though I was not able to access the planet after multiple attempts. *My account was approved and I was fully registered*. I tried shutting the virtual machine down and bringing it back up. That didn’t work. Rebooting my computer was also not a solution. My final solution was to clear the cookies from my browser. That worked and the page loaded without any problems.

**Suggested point add**:

5. When you are trying to access http://localhost:3100 the page may not load at all, even if your account was configured correctly and fully approved. A first step would be to run `vagrant halt prod`. Then, you should proceed to clear the cookies from your browser. This step will be different for each browser. Finally, you should run `vagrant up prod` to restart the VM before you reopen the browser to access the Planet again. 

**If this does not work, follow the previous steps above to rebuild your planet account.**

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Add the suggestion to the troubleshooting section.

**Comment by SNutakki** [comment]
You don't need to do vagrant up prod twice. Other than that, it looks good and you can get started.

**Comment by perryc85** [comment]
Got it. Thank you for the feedback. Will start working on it.
