### ISSUE TITLE
Troubleshooting for VirtualBox installation for Linux

### ISSUE THREAD

**Issue by hiroTochigi** [open-learning-exchange/open-learning-exchange.github.io#2461]
### Problem
Linux users might face an installation problem of VirtualBox.
Because of this, they cannot start vagrant properly.
They might get the below warning
```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error.
```
I struggled with the installation process. 
Other Linux users who are not familiar with virtualization might face the same problem. 

### Steps to reproduce the problem

If a computer with Linux is booted in secure mode, the computer fails to launch VirtualBox.  

### Proposed solution

Disable secure boot or create a MOK(Machine Owner Key)
Add the relevant reference on vi-planet-installation-vagrant.md
[Managing EFI Boot Loaders for Linux: Dealing with Secure Boot](https://www.rodsbooks.com/efi-bootloaders/secureboot.html#using_signed) explains why this phenomenon happens and how to disable Secure Boot.
[VirtualBox + Secure Boot + Ubuntu = fail](https://stegard.net/2016/10/virtualbox-secure-boot-ubuntu-fail/) and [Vagrant and VirtualBox with Secure Boot in Ubuntu 16.04
](https://era86.github.io/2018/01/24/vagrant-virtualbox-secureboot-in-ubuntu-1604.html) explain how to create a MOK

**Comment by perryc85** [comment]
This is good to know. Thanks for sharing this information!

**Comment by SNutakki** [comment]
Sounds good. Feel free to work on this.

**Comment by hiroTochigi** [comment]
> ### Problem
> Linux users might face an installation problem of VirtualBox.
> Because of this, they cannot start vagrant properly.
> They might get the below warning
> 
> ```
> The provider 'virtualbox' that was requested to back the machine
> 'default' is reporting that it isn't usable on this system. The
> reason is shown below:
> 
> VirtualBox is complaining that the installation is incomplete. Please
> run `VBoxManage --version` to see the error message which should contain
> instructions on how to fix this error.
> ```
> 
> I struggled with the installation process.
> Other Linux users who are not familiar with virtualization might face the same problem.
> 

This Problem already mentioned on vi-planet-installation-vagrant.md.
However, the way to make MOK is not mentioned yet.
It might help the users who use a dual-booted computer with Windows and Linux.
