### ISSUE TITLE
Improving the text-box entry for courses in Planet Learning

### ISSUE THREAD

**Issue by hemu-codes** [open-learning-exchange/open-learning-exchange.github.io#2473]
### Problem
When writing responses for Planet Learning courses, the text-box entry does not provide a way with uploading images - it is required that you use Markdown (which can only be figured out by clicking on the question mark) to upload these images and so if it is a local image, to get the link you have to upload to imgur - which could sometimes be unsafe, especially if the screenshot contains some important information. 

### Steps to reproduce the problem

N/A

### Screenshots

<img width="1410" alt="Screen Shot 2019-06-26 at 7 53 05 AM" src="https://user-images.githubusercontent.com/35182550/60190806-1ca08700-97e8-11e9-9d6d-9adbf43b244b.png">

**Proposed Solution Image**:
<img width="1410" alt="Screen Shot 2019-06-26 at 7 53 05 AM" src="https://user-images.githubusercontent.com/35182550/60192829-6f2f7280-97eb-11e9-9077-f4ec1b61bbdb.png">

### Proposed solution

The proposed solution is to add an option to upload an image from local computers (as shown by the second screenshot). This will make the entire process much easier and faster - instead of leaving the window to go to another site to upload an image from your local machine, you can do so from the Planet Learning window itself.

**Comment by lmmrssa** [comment]
@hemu-codes you are creating issue for planet which you will not be able to work on. This is first steps for virtual intern and you are supposed to improve this wiki
