### ISSUE TITLE
Adding more details to Step 6: Github Issues

### ISSUE THREAD

**Issue by hemu-codes** [open-learning-exchange/open-learning-exchange.github.io#2474]
### Problem
For Step 6 of the First Steps, the guidelines state that every time we want to work on an issue, we should create a new branch for that issue to keep it separate from everything else. Although it mentions we have to create the branch, it doesn't provide any images on how to and not everyone might remember how they did so in the previous step. 

### Steps to reproduce the problem

N/A

### Screenshots

<img width="978" alt="Screen Shot 2019-06-26 at 10 50 45 AM" src="https://user-images.githubusercontent.com/35182550/60202836-4ebde300-9800-11e9-99f0-8d3df973ad64.png">

### Proposed solution

To make it easier, we can include the above screenshot in Step 6: Create a New Branch. If someone wants to do it remotely through their terminal we can include a screenshot of the commands to do so from this link: https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches

**Comment by SNutakki** [comment]
Detailing how to create a new branch directly on GitHub is a good idea and a screenshot would be helpful here. It would add be a good idea to add extra text to explain the process and make sure the tutorial is clear. I don't think you need to add any screenshots on how to do it through the terminal though. The commands are already listed so the process should be clear.

You can go ahead and get started if you're fine with this.

**Comment by raisinman99** [comment]
As someone who is working on step six, I think this is a good issue since it is not completely clear on how to create a branch to fix an issue.
