### ISSUE TITLE
Step 1 Navigation Bar Nested List 

### ISSUE THREAD

**Issue by irisb1701** [open-learning-exchange/open-learning-exchange.github.io#2475]
## Problem 
In the navigation bar, when selecting the Virtual Interns drop down, there is no link for the 3 separate parts of Step 1. 

### Steps to reproduce the problem
N/A

### Screenshots
![screenshotissue6](https://user-images.githubusercontent.com/16839815/60226018-62e0ff00-9857-11e9-8c1b-7c5364766f45.png)
![screenshotissue5](https://user-images.githubusercontent.com/16839815/60226019-64122c00-9857-11e9-84b0-4a2356d0bd0c.png)

### Proposed solution
Include a nested list within step 1 for the 3 substeps

**Comment by ChiragAwale** [comment]
That would be easier to navigate. You can work on it.
