### ISSUE TITLE
Manager Settings unclickable 

### ISSUE THREAD

**Issue by raisinman99** [open-learning-exchange/open-learning-exchange.github.io#2479]
### Problem

The manager settings button (second from right) is unclickable. Nothing happens when it is clicked upon so I have to manually type in http://localhost:3100/eng/manager in the URL.

### Steps to reproduce the problem

Go to home page on Planet Learning and go to the top right and click on the manager settings button on the top right.

### Screenshots

![](https://i.imgur.com/IgTsidS.png)

### Proposed solution

Look through the code and debug.

**Comment by hkcyf369** [comment]
I am able to click the manager settings button. 
I still agree with you that you can look through the code.

**Comment by Liew211** [comment]
@raisinman99 please try to find issues within the first steps wiki :) The issues on planet are for the planet team, which you can join after completing these first steps.
