### ISSUE TITLE
Adding a screenshot in Step 4

### ISSUE THREAD

**Issue by hkcyf369** [open-learning-exchange/open-learning-exchange.github.io#2480]
### Problem
In Step 4-Different Kinds of Updates to Your Community, perhaps we can add a screenshot showing the page of `upgrade` such that people will be easier to follow the steps. 
Moreover, in bullet point 3, we can change it to:

> If Fetch Items is available on the Manager page, click on it and download the courses offered (2nd picture), if not, just go ahead to the next step.

### Screenshots

<img width="667" alt="OLESTEP4" src="https://user-images.githubusercontent.com/47688356/60330154-ab2b1a80-9946-11e9-8fdd-1fff7209ddfa.PNG">
 

### Proposed solution

Add this screenshot: 
<img width="920" alt="OLECAP2" src="https://user-images.githubusercontent.com/47688356/60330661-c77b8700-9947-11e9-9397-273cb91d4f5b.PNG">

**Comment by Liew211** [comment]
@hkcyf369  This is a good fix, you can work on this.

**Comment by raisinman99** [comment]
I agree, this well help people not get confused.

**Comment by hemu-codes** [comment]
Maybe adding a screenshot of while its updating might also be helpful for users to get a confirmation that they are doing it right.

**Comment by lillyxxx** [comment]
I think this new screenshot is useful. When I first looked at the 2 screenshots provided I got confused - I thought the second image is what I was looking for.
