### ISSUE TITLE
Mistake in vi-vagrant.md

### ISSUE THREAD

**Issue by raisinman99** [open-learning-exchange/open-learning-exchange.github.io#2483]
### Problem
In vi-vagrant.md it says "We have a Vagrant virtual machine called prod running in VirtualBox." but in the output, we can see that the virtual machine is called dev. I believe this may cause some confusion for people doing the first steps.

### Steps to reproduce the problem

N/A

### Screenshots

![](https://i.imgur.com/uPTuHq3.png)

### Proposed solution

Go through md file and change dev to prod

**Comment by 275vytran** [comment]
I found the same issue with you and also put them in my pull request.

**Comment by perryc85** [comment]
Good catch. Go ahead with the fix.
