### ISSUE TITLE
Add more information when creating dummy account in Step 7 - Nation Planet

### ISSUE THREAD

**Issue by 275vytran** [open-learning-exchange/open-learning-exchange.github.io#2496]
### Problem
There is a possible error which is can not create dummy user. 

### Steps to reproduce the problem

Step 7

### Screenshots

![Untitled (1)](https://user-images.githubusercontent.com/49819696/60390859-3d960000-9aa6-11e9-836b-521d86ce5697.png)

### Proposed solution

So, in this NOTE, we should detail this case so that learner can easier to solve their problem by themselves. We can append the solution to NOTE: "If you can not create dummy user, please click on the helpful links and videos under the Useful Links section at the bottom of the Nation Planet page. Once there, scroll up to Q22 for a solution, which is located under the Technical questions section."

**Comment by raisinman99** [comment]
I think this is a useful issue so that future interns don't get stuck on this and ask for help.
