### ISSUE TITLE
Adding diagrams to "Explanation About Repositories and Syncing Process" in Step 5

### ISSUE THREAD

**Issue by 275vytran** [open-learning-exchange/open-learning-exchange.github.io#2499]
### Problem
I would like to add two diagrams to the "Explanation About Repositories and Syncing Process" in Step 5 - Git Repositories so that learner can clearer understand the explanation.

### Steps to reproduce the problem

Step 5

### Screenshots

![vi-forking-and-updating-a-repo](https://user-images.githubusercontent.com/49819696/60404104-13f2dc80-9b6b-11e9-8832-620e676153a3.png)

![vi-sync-a-fork](https://user-images.githubusercontent.com/49819696/60404105-16553680-9b6b-11e9-9f70-b38bb2dced64.png)

### Proposed solution
Add two diagrams to the explanation

**Comment by raisinman99** [comment]
This makes more sense to me. I like these better than the provided diagrams.

**Comment by Liew211** [comment]
@275vytran I think adding these, but not removing the existing diagrams would be pretty helpful.  @lmmrssa What do you think?
