### ISSUE TITLE
Adding troubleshooting steps to vi-nation.md

### ISSUE THREAD

**Issue by raisinman99** [open-learning-exchange/open-learning-exchange.github.io#2502]
### Problem
For me, I was using chrome browser and was not able to go to do manager settings on Planet Learning. When I clicked on it nothing would happen. So I switched to Firefox and I could access the manager settings.

### Steps to reproduce the problem

N/A

### Screenshots

![](https://i.imgur.com/MsyIYhP.png)
This gif shows the problem I was having https://i.imgur.com/EzKKWot.gif

### Proposed solution

I will add a line at the end of "Sync with Nation" that says: If you are not able to access the manager settings, try switching your browser.

**Comment by 275vytran** [comment]
it is helpful

**Comment by SNutakki** [comment]
You can work on this. It's already mentioned elsewhere that Planet might not work on Chrome, but it wouldn't hurt to mention it again here.

**Comment by ChiragAwale** [comment]
Do work on it.
