### ISSUE TITLE
Possible confusion in vi-docker-tutorial.md

### ISSUE THREAD

**Issue by raisinman99** [open-learning-exchange/open-learning-exchange.github.io#2503]
### Problem
As seen in the screenshot, the attention block should be moved to after step 5 because it pertains to that instruction. The attention block says not to run "docker-compose -f planet.yml -p planet up -d --build" if you followed step 1 but it only tells you that after step 5 has been done. I believe the attention block should be put after step 5 so people don't execute that command and then after step 7 they find out that they did not need to execute it.

### Steps to reproduce the problem

N/A

### Screenshots

![](https://i.imgur.com/nrmfzgb.png)

### Proposed solution

I will go through the markdown file and move the attention block to under step 5.

**Comment by 275vytran** [comment]
I did make that mistake before. After I turn off and turn on my computer again, the Planet got error and I had to get rid of my Plannet and installed it again

**Comment by Liew211** [comment]
@raisinman99 This is a good change.
