### ISSUE TITLE
Markdown vs HTML

### ISSUE THREAD

**Issue by raisinman99** [open-learning-exchange/open-learning-exchange.github.io#2504]
### Problem
In the text to the right of the screenshot, I think it would be helpful to explicitly state that the right side is HTML to further help differentiate Markdown and HTML.

### Steps to reproduce the problem

N/A

### Screenshots

![](https://i.imgur.com/NuOj3zS.png)

### Proposed solution

I will change the text to: Example of Markdown syntax on the left side and the way it is rendered to HTML on the right side (click on image to expand):

**Comment by SNutakki** [comment]
This is a minor change, but it does help a little. You can work on this.
