### ISSUE TITLE
Adding "Next Section" to bottom of Nation Planet Page And Links 

### ISSUE THREAD

**Issue by fernandamarr** [open-learning-exchange/open-learning-exchange.github.io#2515]
#### Problem
All sections of First Steps for Virtual Interns has a "Next Section" portion at the bottom of the page except for Nation Planet, which doesn't make it consistent.

Additionally, none of the "Next Section" text leads to the next page. I have to navigate back to the "First Steps" page in order to move forward. I feel it would be easier to navigate to the next section rather than back and forth.

### Steps to reproduce the problem
Go to the First Steps page (I used Chrome on Ubuntu). On left side, click on Step 7 - Nation Planet. Scroll to the bottom of the page. 

### Screenshots
![add-next-section-OLE](https://user-images.githubusercontent.com/34196754/60614315-acbb6f00-9d9a-11e9-99b8-c625efe21cee.png)

### Proposed solution
Add "Next Section" and a clickable link that will take you to the next page instead of the first steps page.

**Comment by SNutakki** [comment]
This issue seems to have been worked on previously (#2288). Apparently the links aren't there at the suggestion of @lmmrssa.

**Comment by Liew211** [comment]
@fernandamarr This is because Step 8 doesn't have its own page; all that's required of Step 8 is just to file more issues and pull requests, which you have done previously in step 6.

**Comment by johnmdrake1** [comment]
Though this would be a seemingly good functionality to have, I prefer a workflow where "First Steps" is open in a different tab and I can return, read the short description on the "First Steps" page, and then click on its relevant tutorial page. For example, I am working on step 6 and some important information is contained in its description here Screen Shot 2019-07-03 at 9.15.27 PM on what exactly I need to do to complete my Virtual Intern Step, that is not explicitly stated on the [GitHub Issues Page](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md) 

Additionally, notice that whenever the relevant page for a step is opened, it does not state on the page which step it correlates to. This may be for a reason, or may be worth me opening an issue of my own to make it clear what tutorial you are currently viewing for what step.

**Comment by lmmrssa** [comment]
@fernandamarr these pages you are no is not actually a step. They are just part of step. And as these links come in between the detail of Step and there could be other pages or links which are part of same step, we take people back to main page so that they can proceed from where they left.
If we just take people to next page then some of details we added on overview page will be missed by people.
