### ISSUE TITLE
Adding Step Number to Tutorial Page Titles

### ISSUE THREAD

**Issue by johnmdrake1** [open-learning-exchange/open-learning-exchange.github.io#2516]
### Problem
On the [First Steps Page](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) , each step is clearly labeled with a step number and title, along with a description and link to the relevant tutorial page, such as 
<img width="826" alt="Screen Shot 2019-07-03 at 9 36 59 PM" src="https://user-images.githubusercontent.com/32374869/60636097-bbc21180-9dda-11e9-9486-410d3104057f.png">

but when going to the appropriate tutorial page, in this case the [Docker Tutorial Page](http://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md) , 

the "title" is simply 
<img width="298" alt="Screen Shot 2019-07-03 at 9 39 41 PM" src="https://user-images.githubusercontent.com/32374869/60636192-1c514e80-9ddb-11e9-9bd3-8f23f96b3d3e.png"> 

Would it make it clearer to aspiring interns that may get confused to add the step name to the title? i.e. The title saying on the [Docker Tutorial Page](http://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md) **Step 2- Docker Tutorial** instead, so it will be clearer which step the aspiring intern is learning more about? I understand that the same page can be referenced multiple times, such as in steps 6 and 8, where the same [Docker Tutorial Page](http://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md) is referenced in both steps. In this case, perhaps a note at the top of the tutorial page that states what steps are relevant to that tutorial? This has not been a personal issue, but those with other workflows with their tabs may get confused.

### Steps to reproduce the problem
1. Go to the [First Steps Page](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) 

2. Click on one of the hyperlinks contained in one of the step descriptions to be taken to a tutorial page, such as [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md) in step 4.

3. The discrepancy between 
<img width="332" alt="Screen Shot 2019-07-03 at 9 51 39 PM" src="https://user-images.githubusercontent.com/32374869/60636600-cc738700-9ddc-11e9-84e3-d8f087b2fd2f.png"> 
and 
<img width="269" alt="Screen Shot 2019-07-03 at 9 51 21 PM" src="https://user-images.githubusercontent.com/32374869/60636640-eb721900-9ddc-11e9-9b9d-43edb0c2dd18.png">

can be observed, and is what I reference here.

### Screenshots

See above, but the dropdown menu on the "Virtual Interns" portion of the navbar on the OLE Support Page may be taken into account-what they are numbered as and what they are linked to:

<img width="303" alt="Screen Shot 2019-07-03 at 9 54 59 PM" src="https://user-images.githubusercontent.com/32374869/60636719-3c820d00-9ddd-11e9-9b68-7cc6bbc9a7ca.png">

### Proposed solution
Somehow making the tutorial pages clearer and more consistent with their corresponding "First Steps" steps. This could be easily done by changing the tutorial page titles, which I could  work on if approved, though consistent naming between hyperlinks, page titles, and bold titles on the First Steps page should be verified.

Alternatively, it could be noted somewhere visible or near the top of the page that the tutorial the user is currently viewing correspond with step x(or step(s) x and x, if applicable like 6 and 8).

Any suggestions on alternative ways to do this are welcome. It is one of a few clarity issues I feel could improve the wiki for future Virtual Interns taking their first steps, though I have been careful and it has not caused confusion for me.

**Comment by lmmrssa** [comment]
@johnmdrake1 it is something similar to #2515 These are not completely steps these are just part of step. And these pages could be called from different pages or sections. These are tutorial pages not step pages. That's why we do not add Step number there. Step page is the first page only, all other pages are tutorial pages which might be called from different pages or following other steps such as TechGenius steps as well.
