### ISSUE TITLE
Better navigation under "First Step"

### ISSUE THREAD

**Issue by lillyxxx** [open-learning-exchange/open-learning-exchange.github.io#2528]
### Problem

When I'm doing with different steps, it is easy to get lost and forget which step I was located. We have the "Return to First Steps" button to navigate us back to the steps we're located at, but I just found the truth by testing it and have no idea of that before I test it. 

It does confuse me a lot when a section is relatively long, and the next section description is not obvious enough to let me find the next section in a quick time and we don't have a "quick navigator" to go to the next section.

### Steps to reproduce the problem

N/A

### Screenshots

Here's an example for the end of a step:
![image](https://user-images.githubusercontent.com/33206707/61011464-8617ae00-a32f-11e9-9fd9-9509e8a3f1ac.png)
Clicked on" First Steps" =================>

![image](https://user-images.githubusercontent.com/33206707/61011482-9891e780-a32f-11e9-8238-f68f3760bf34.png)

### Proposed solution

Add some text as a reminder of the next section like this:

*Suppose we're on step 5:*
>  ## Next Section *(Step 6)* **→**

### Related questions
I also read issue #2067 and #2115 , these issues also show that people do have confusing while navigating through the first step.
For #2067 , it seems that the current version of MDwiki is not supported with that feature and for #2115 , it is a great idea to have specific numbers for each step, but I don't think this will help a lot to sections with single link/step, like Section/Step 2,3,4,5,6,7.

So as my point of view, the overall problem is the same but my issue is not duplicated because it is another approach to realize the clearer navigation.

**Comment by siqiuma** [comment]
I understand what you are saying as users could forget which section/step they were at when they click on "Return to First Steps", so you would like to add "Next section -Step 6" at the end of Step 5 page. 

However, I do see that when you click on "Return to First Steps" from Step 5 page, "Step 5 - Keeping Fork Updated" will be highlighted on the left navigation panel. 
![Screen Shot 2019-07-15 at 12 46 40 AM](https://user-images.githubusercontent.com/38894754/61196121-759e6500-a69a-11e9-9919-31c066c875e8.png)
Therefore, I believe users can track which section/step they were at from seeing that. Also, even if we put "Next section-Step 6" at the end of Step 5 page, users can still forget it after they are redirected. For this reason, I think the original design solves the confusion problem better.

**Comment by lillyxxx** [comment]
@siqiuma Thank you for pointing out this highlight - I didn't notice that until you point it out. It is true that when you be navigated back to first steps, it will go back to the steps we're located at, as well as the highlighted text highlight. But as for me, I have such kind of problems and probably others will feel the same way( like other 2 issues). I think the best way to solve the problem is that we have a link that will go directly to the next step, but the structure of the first steps made it hard to realize. So I come up with this solution - though as you said maybe they will forget it later, it does can help someone when they get lost.
