### ISSUE TITLE
Changing the position of the Markdown links 

### ISSUE THREAD

**Issue by hemu-codes** [open-learning-exchange/open-learning-exchange.github.io#2531]
### Problem
Currently, in the Github and Markdown page, there are only 2 links that direct you to a Markdown syntax page. However, I feel like some of the links that are posted towards the end of the page in the Useful Links section are more informative. And as a new intern, you might not be aware that there are links to more guides that are posted towards the end and try to find more links on your own and end up wasting some time on that - especially if this is your first time using Markdown.

### Steps to reproduce the problem

N/A

### Screenshots

**Current links in the Markdown section:**
<img width="935" alt="Screen Shot 2019-07-09 at 8 56 04 PM" src="https://user-images.githubusercontent.com/35182550/61107144-03c4e200-a434-11e9-8b5a-20d338611fb4.png">

**Which links should be added to the section:**
<img width="935" alt="Screen Shot 2019-07-09 at 8 56 41 PM" src="https://user-images.githubusercontent.com/35182550/61107493-e3e1ee00-a434-11e9-96c9-2485581616f7.png">

### Proposed solution

The screenshot indicates which links could be moved up and be in the same section as the other guides so that the interns are aware that there are more than 2 guides to learn about Markdown.

**Comment by SNutakki** [comment]
This seems useful. You can go ahead and work on it.

**Comment by poiuy999** [comment]
please remove me from this repo
