### ISSUE TITLE
Checking Containers in Docker Tutorial

### ISSUE THREAD

**Issue by tdecelle** [open-learning-exchange/open-learning-exchange.github.io#2535]
### Problem
In the Docker Tutorial, virtual interns are asked to check whether docker containers are running using `docker ps`, but that wouldn't show an exited container if they used `vagrant up prod`. The example interns are shown to check against shows that exited container.

### Steps to reproduce the problem
1. Run `vagrant up prod` on a virtual machine with the state "poweroff".
2. Ssh into the planet.
3. Run `docker ps`

### Screenshots

![Docker all](https://user-images.githubusercontent.com/31163139/61174952-b85e2100-a564-11e9-9030-cf3fff6c4ec0.png)

### Proposed solution

Change the `docker ps` to `docker ps -a` which would show the exited container if the intern ran `vagrant up prod`.

**Comment by raisinman99** [comment]
This is a good issue
