### ISSUE TITLE
Duplicate Markdown Resource Listed

### ISSUE THREAD

**Issue by siqiuma** [open-learning-exchange/open-learning-exchange.github.io#2539]
### Problem
On the page "GitHub and Markdown", under the two screenshots for Markdown syntax, there's a list of links for resources to learn Markdown. However, "Markdown Tutorial - An interactive tutorial to learn Markdown" appeared twice and both links direct to the exact same page. 

### Steps to reproduce the problem

Go to [GitHub and Markdown](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md), and scroll down until after the two screenshots for Markdown syntax. Click on the "Markdown Tutorial - An interactive tutorial to learn Markdown" on the second line of the list, and you will be directed to [this page](https://tylingsoft.github.io/tutorial.md/#whats-markdown). Go back to the same list and click on the "Markdown Tutorial - An interactive tutorial to learn Markdown" on the fourth line of the list, you will be also directed to [the same page](https://tylingsoft.github.io/tutorial.md/#whats-markdown). 

### Screenshots

![Screen Shot 2019-07-15 at 12 17 49 AM](https://user-images.githubusercontent.com/38894754/61195604-0e32e600-a697-11e9-9e5d-fe8eac59ca75.png)

### Proposed solution

Delete "Markdown Tutorial - An interactive tutorial to learn Markdown" either on the 2nd line or on the 4th line.

**Comment by perryc85** [comment]
Good catch. You can work on it.
