### ISSUE TITLE
Software download links not working

### ISSUE THREAD

**Issue by lillyxxx** [open-learning-exchange/open-learning-exchange.github.io#2541]
### Problem
Under `Tech Genius -> Tablet Configuration `, it provides 4 links corresponding to download _Firefox Web Browser, Adobe Flash, Office Suite_, and _OLE Take Home App_. But only the last link, which is for _OLE Take Home APP_, is working.

### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/33206707/61267906-932d0680-a74e-11e9-8654-ea8c24701e49.png)

For all first 3 links, they will give the same response:
![image](https://user-images.githubusercontent.com/33206707/61250641-13327c80-a70d-11e9-9991-5a02a30f621b.png)

### Proposed solution

Update them with new links:
Firefox Web Browser - https://www.mozilla.org/en-US/firefox/new/
Adobe Flash - https://get.adobe.com/flashplayer/
Office Suite - https://www.officesuitenow.com/download/

But with the usage of the above links, we also need to modify the sayings:
![image](https://user-images.githubusercontent.com/33206707/61251387-25adb580-a70f-11e9-8d31-a22cb2980c76.png)
It needs to be changed to:
> You can download the needed files via the links below.

**Comment by siqiuma** [comment]
Yes, the first 3 links don't work for me either.
