### ISSUE TITLE
In consistency in Step 3 requirement

### ISSUE THREAD

**Issue by lillyxxx** [open-learning-exchange/open-learning-exchange.github.io#2542]
### Problem
The requirement for info need in Gitter Chat in step 3 is inconsistent with the overview of step 3.

In the overview, it asks for links of github.io and raw.githack links, while in the detail of Step 3, it asks for links of github.io and pull request.

### Steps to reproduce the problem

N/A

### Screenshots

Overview of step 3:
![image](https://user-images.githubusercontent.com/33206707/61251823-69ed8580-a710-11e9-9b4e-e61311cdffeb.png)
Inside step 3:
![image](https://user-images.githubusercontent.com/33206707/61251859-85f12700-a710-11e9-844c-295bc2fa0ad9.png)

### Proposed solution

Change the overview to the same as inside/detailed step 3. Because the Raw.githack link is available in PR.
The overview will be:
> Make sure that you've linked to your github.io and pull request link on the Gitter chat (https://YourUserName.github.io and `LinkToYourPullRequest`). Also include Raw.githack link in your pull request( https://raw.githack.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/vi/profiles/YourUserName.md).

**Comment by siqiuma** [comment]
I agree with what is said in this issue. It will be more clear for the reader after the change.

**Comment by leahphuong** [comment]
Will someone please respond and stop this list ?
