### ISSUE TITLE
More Info Needed re: Using Firefox for Planet

### ISSUE THREAD

**Issue by siqiuma** [open-learning-exchange/open-learning-exchange.github.io#2550]
### Problem
The instruction on [Planet Installation](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md) does not mention anything about the version of Firefox to use for community planet. 

I used Firefox to access community planet. However, community planet did not work properly. It was because I was using a very old version of Firefox without realizing it. Community planet works perfectly fine after I updated my Firefox to the latest version. 

### Steps to reproduce the problem

Make sure community planet is installed, and then use a very old version of Firefox to access community planet. 

### Screenshots

![Screen Shot 2019-07-16 at 1 38 16 AM](https://user-images.githubusercontent.com/38894754/61268760-7a324e80-a76a-11e9-87f1-f74b2b8657d6.png)

### Proposed solution

Add the the sentence "If you are using Firefox and community planet is not working properly, please update your Firefox to the latest version and then try again." after "If you don't have Firefox already, you may want to download it."

**Comment by lillyxxx** [comment]
This issue is very useful. I think the FAQ page should also include Firefox version information too for troubleshooting.

**Comment by perryc85** [comment]
This is a good idea. You can work on it.
