### ISSUE TITLE
More Info for After Reinstalling Planet

### ISSUE THREAD

**Issue by siqiuma** [open-learning-exchange/open-learning-exchange.github.io#2551]
### Problem
(#2110 discusses this problem but did not provide any solution. This issue provides instructions for users who have this problem.)

The instructions for reinstalling planet in Q22 on [FAQ page](http://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#Helpful_Links) does not mention anything about how to register as admin and log in again after the reinstallation. 

### Steps to reproduce the problem

1. Go to terminal and cd to the directory for planet, then use "vagrant destroy prod" to destroy planet. 
2. Use command "vagrant up prod" to reinstall planet
3. Go go http://localhost:3100 
4. You will see the screen asking you to register as admin, and before you do that, you cannot log in

### Screenshots

![Screen Shot 2019-07-16 at 1 55 23 AM](https://user-images.githubusercontent.com/38894754/61269506-d72f0400-a76c-11e9-8c93-6b22ba56b93e.png)

### Proposed solution

Replace "**Warning!** this wipes all your progress in the virtual intern course as well." using the following paragraphs: 

**Notice:** After planet reinstallation, you will need to register as admin a second time as you did in step [Planet Configurations](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md). However, you cannot use the same "Name" in Set up Configuration step because that "Name" already exists. You may instead use YourName01 or add any other number you like at the end of your original "Name". This should allow you to register as the admin and log in your community planet. 

Also, the 3 resources you uploaded to Library, the Virtual Intern course you added to myCourses, and all your progress in the Virtual Intern course will be gone.

**Comment by bradlet** [comment]
I created an issue (#2556) just now that is similarly motivated. The same thing can happen during step 2 -- the docker tutorial. If you use the volatile docker-compose command you can destroy your configuration. 

I like your idea of referring users who did this back to the Planet Configurations page. I just went back to the page on my own, but it would still be a good idea to specifically refer users to that page.

**Comment by ChiragAwale** [comment]
You can work on it. It should be helpful.
