### ISSUE TITLE
A Second Place to Mention Firefox Version for Planet

### ISSUE THREAD

**Issue by siqiuma** [open-learning-exchange/open-learning-exchange.github.io#2552]
### Problem
(Similar to #2550, but at a different step)

The instruction on page [Nation Planet](http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md) says "It is recommended that you use Firefox since Planet is only guaranteed to run properly on Firefox" but does not mention anything about the version of Firefox to use for community planet.

I used Firefox to access community planet. However, community planet did not work properly. It was because I was using a very old version of Firefox without realizing it. Community planet works perfectly fine after I updated my Firefox to the latest version.

### Steps to reproduce the problem

Make sure community planet is installed and running, and then use a very old version of Firefox to access community planet.

### Screenshots

![Screen Shot 2019-07-16 at 2 20 52 AM](https://user-images.githubusercontent.com/38894754/61270678-5e31ab80-a770-11e9-9e07-fc5aa5c79ee9.png)

### Proposed solution

Add the the sentence "If you are using Firefox and community planet is not working properly, please update your Firefox to the latest version and then try again." after "It is recommended that you use Firefox since Planet is only guaranteed to run properly on Firefox."

**Comment by perryc85** [comment]
This change isn’t necessary since you are going to address it with your other issue (#2550). Plus, Aspiring Interns will know about the update after reading your note in step 1.
