### ISSUE TITLE
When it is OK to Move on during First Steps Needs to be Specified

### ISSUE THREAD

**Issue by johnmdrake1** [open-learning-exchange/open-learning-exchange.github.io#2554]
### Problem
On the First Steps page, or elsewhere on the wiki, I have not seen a statement that it is ok to move forward while waiting on an Issue or Pull request approval. Approvals for step 3, where Aspiring Interns make their first pull request with their profile, seem to go through quickly and seamlessly. Other Issues, Fixes, and Pull Requests, can take time, however, especially those on step 6 where the Aspiring Intern makes their first change to the wiki for future Interns. 

Interns need to know that they are allowed to move on to step 7, and create more Issues and Pull requests, before their approval has been completed for the one Pull Request Step 6 calls for.

### Steps to reproduce the problem

When Creating My Issue for step 6, https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/2519 , I thought I was being given approval for the "rewording" portion of my fix. `But if you can improve wording on this section then please propose the changes you will make we will check if that sounds good.` signaled to me that it was time to make a branch, make my "rewording" changes, and create my Pull Request for step 6. I did so, at https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/2521 .

One approval was granted right away, pending my fix of a minor spelling mistake. I still needed one approval after my first one was granted, and had a back and forth with my other reviewer. I kept waiting on this reviewer's responses and was eager to know what changes should be made. The Pull request ended up being closed by the reviewer after our back and forth 9 days later.

I was told by two members of the OLE chat a week after my PR was first created that it was ok to move on to step 7 and beyond while waiting for approval, but I did not know that until then. Had I known, I would not have spent over a week waiting for a Pull Request that ended up not being approved by a second reviewer. The language here is the main thing that made me believe steps had to be completed in order, found on First Steps:
<img width="465" alt="Screen Shot 2019-07-16 at 3 58 40 AM" src="https://user-images.githubusercontent.com/32374869/61312639-74665880-a7be-11e9-9dca-ee74d0662f50.png">

I was very sure to take note of this warning on http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md 

<img width="832" alt="Screen Shot 2019-07-16 at 11 41 59 AM" src="https://user-images.githubusercontent.com/32374869/61312818-cd35f100-a7be-11e9-8c28-08e2dfaed303.png">

I thought the comment I received on my *Issue* , `But if you can improve wording on this section then please propose the changes you will make we will check if that sounds good.` was the approval I needed(the Issue is still open here https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/2519 , but all I changed in my PR was some wording, as stated.) I was very careful to follow the warning above.

I feel foolish for "wasting"(though I would not call it that, because it was a learning experience) a week I could have been moving on in the first steps. Aspiring Interns need to know they can move on, if the information I received in chat in fact makes it ok to do so.

### Screenshots

<img width="864" alt="Screen Shot 2019-07-16 at 11 50 33 AM" src="https://user-images.githubusercontent.com/32374869/61313396-f86d1000-a7bf-11e9-8e9f-40ca327474df.png">

Note how it specifically says **`Make sure you have created at least one issue, resolved it, commented on an issue you didn't create and have a pull request with the fix merged before proceeding to the next step.`**

My reviewer did not seem to understand why I was not moving on. This is why. I really wish I had known my issue would be closed after 9 days of waiting, and I'm sure other Aspiring Interns would as well.

### Proposed solution

Changing the wording of
<img width="864" alt="Screen Shot 2019-07-16 at 11 50 33 AM" src="https://user-images.githubusercontent.com/32374869/61313612-66b1d280-a7c0-11e9-8c87-6755a1939fb7.png">

Specifically, saying with an additional bullet point:

- It is OK to move on to step 7 and make other issues and pull requests while you are waiting, do not get hung up on this step.

(or something of that sort) 

and completely removing **"before proceeding to the next step"** from `Make sure you have created at least one issue, resolved it, commented on an issue you didn't create and have a pull request with the fix merged before proceeding to the next step.`

Something needs to be changed here, I understand I can move on before completing a step now but am frustrated at myself for wasting a week because I did not know.

**Comment by perryc85** [comment]
Hello @johnmdrake1. I understand where you are coming from with this suggestion. I believe anyone completing the steps is expected to wait until their pull request is approved and merged. I also think Aspiring Interns are allowed to move to the next step once they are given permission to proceed. 

I’m not sure about the change. @lmmrssa - What are your thoughts regarding this issue?

**Comment by johnmdrake1** [comment]
Thank you for your understanding @perryc85 . I had a lengthy discussion with @lmmrssa about this last night, but it ended up further confusing me in some ways. He asked why I hadn't been working on other pull requests and moving on to the next steps, and said he didn't understand why I was so hung up on this one merge. He closed my pull request that was open for 9 days because of one part that had to do with uploading pictures, because it  would have to be a change made to Planet, not the Wiki. I made other changes in that pull request completely unrelated to the uploading pictures on Planet portion, that would have made some things clearer to interns, and got a quick approval from one reviewer, but it was still closed after 9 days. It should definitely be one or the other-the wiki can't explicitly state not to move on from step 6, yet have it expected of the aspiring Interns to move on. Nothing lets them know this is ok. 

Sorry if I sound frustrated. I thought that after the 9 days, I was just fixing up a few things and finally getting step 6 merged so I could move on. Based on my conversation with @lmmrssa , however, it appears I waited all that time in vain. Actually, I don't know if I have a clear answer to whether I am done with step 6 or not, but here is not the place to discuss that. Thank you again for your comment @perryc85

**Comment by johnmdrake1** [comment]
If the result ends up being that Interns must wait before moving on(By Official Decision from OLE Staff), then my next issue and change will be to the part of the FAQ that states most Aspiring Interns complete the steps in 7-8 days. If they must wait on one pull request for longer than that to move ahead, that is very inaccurate, and I may expect step 8 alone to take weeks.

**Comment by ChiragAwale** [comment]
@johnmdrake1 I am not sure about what happened in the discussions, but you can work on other issues and create pull request no matter what step you are in. And as you flow through the steps, if the steps require a certain count then your Approved PRs and Issues will all be counted.

**Comment by ChiragAwale** [comment]
I think it would be helpful to add that creating issues and working on there is not exactly tied and bound by steps.

**Comment by perryc85** [comment]
@johnmdrake1 - I agree with the note @ChiragAwale added here.

**Comment by johnmdrake1** [comment]
@perryc85 @ChiragAwale Ok, thank you. I will try to find a good place to make a standout note about that. Maybe on the first steps page(around the step 6 area, as if I put it at  the top they may not know what I'm referring to yet). And a note at the top of the Github Issues Wiki Page would be a good addition. I'll work on it and make a PR when ready.

**Comment by johnmdrake1** [comment]
@ChiragAwale @perryc85 see my pull requests where I added some notes to fix this here: https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/2591
