### ISSUE TITLE
Manager Settings Visibility

### ISSUE THREAD

**Issue by bradlet** [open-learning-exchange/open-learning-exchange.github.io#2555]
### Problem
It isn't well communicated how to access Manager Settings within the planet. For low-resolution or small monitors, the typical gear representing "settings" is not as visible since it only makes up the corner of a small icon. There have been issues discussing bugs with the icon not appearing at all in the past; this is a separate issue entirely focused on the icon's ability to convey its functionality.

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/47132003/61392657-2744be00-a874-11e9-8424-c4a1927450a1.png)

### Proposed solution
There are two or three separate ways to address this. It isn't a huge issue, but merely a small inconvenience for first time users / new interns. 

1. Implement pop-up text boxes that appear when hovering over icons with the mouse. This could be implemented for all icons on the planet.

2. Move Manager Settings to be a part of the drop-down menu found under the user/profile icon found in the top-right hand of the screen.

3. Change the manager settings icon to be only a gear. The gear icon is a relatively universal indicator of *settings*, so it may be better to simply focus on that and let the users infer that the *settings* being referenced are "manager settings". I don't think the trade-off of lack of visibility from having a person+small gear icon to represent manager settings is worth the lesser ability to communicate that the icon handles settings.

As stated previously, all 3 solutions would help new users, but the issue should be overcome individually rather quickly. So, perhaps it isn't worth changing considering how small the issue is.

**Comment by SNutakki** [comment]
This is an issue with Planet. If you haven't finished the initial steps yet, you need to find and work on issues with the OLE website.

**Comment by bradlet** [comment]
> This is an issue with Planet. If you haven't finished the initial steps yet, you need to find and work on issues with the OLE website.

Okay, thank you! I'll leave this open as a reminder for when I do complete the first steps!
