### ISSUE TITLE
Warning text in Docker Tutorial poorly positioned.

### ISSUE THREAD

**Issue by bradlet** [open-learning-exchange/open-learning-exchange.github.io#2556]
### Problem
Many new virtual interns will follow all the steps sequentially in "The First Steps." Because of this they likely have configured their planet in Step 1, before starting the Docker tutorial in step 2. There is a warning not to use the docker-compose command listed in the docker tutorial if you already configured your planet; however, it is positioned after the new intern is told to enter 
`docker-compose -f planet.yml -p planet up -d --build`
This makes it easy for new interns to need to destroy, recreate and reconfigure our planet.

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/47132003/61394200-750ef580-a877-11e9-840b-1274bd4ed649.png)

### Proposed solution
Just move it above the line instructing new interns to use the volatile docker-compose command. I'd be happy to do it myself upon this issue reviewer's request!

**Comment by SNutakki** [comment]
This seems like useful change. You can work on it.

**Comment by bradlet** [comment]
I figured I would do this on the same branch I made for my firstSteps -- bradletFirstSteps -- but I didn't realize that my personal page hadn't had a successful pull yet. I'd appreciate it if you could just use the existing pull-request (#2553) as I could move this all to a separate branch; however, it makes sense to have them both exist in the same pull-request as my personal .md page addition isn't changing any existing files (and was already waiting a second reviewer).
