### ISSUE TITLE
Minor Change in Github Issues page

### ISSUE THREAD

**Issue by hemu-codes** [open-learning-exchange/open-learning-exchange.github.io#2563]
### Problem
Although this is a minor change, in the Github Issues page, where it explains how you create a new branch, it doesn't emphasize that we have to create a new branch for any new issue we create. 

### Steps to reproduce the problem

N/A

### Screenshots

<img width="1040" alt="Screen Shot 2019-07-17 at 10 35 15 PM" src="https://user-images.githubusercontent.com/35182550/61431725-5a726600-a8e3-11e9-8d4b-f8bd2ed1861c.png">

### Proposed solution

Bolding this sentence will make the interns understand the significance/importance of creating a new branch for each issue.

**Comment by perryc85** [comment]
This could be helpful. You can work on it.
