### ISSUE TITLE
Changing the Note section in Nation Planet Page

### ISSUE THREAD

**Issue by hemu-codes** [open-learning-exchange/open-learning-exchange.github.io#2566]
### Problem
The information that is given in the Nation Planet page section about creating a dummy user account is lumped into a Note section as a huge paragraph. 

### Screenshots

<img width="847" alt="Screen Shot 2019-07-17 at 11 37 03 PM" src="https://user-images.githubusercontent.com/35182550/61434845-e5eff500-a8eb-11e9-809a-939368d3eb85.png">

### Proposed solution

I think it would be easier to read and understand if the information is given in a bullet point fashion where each of the steps would be easier to follow.

**Comment by perryc85** [comment]
These changes sound helpful. You can work on it.

**Comment by biswasshrestha** [comment]
@hemu-codes I agree with your suggestions. If you have bullet points, may be you could also consider adding screenshots?
