### ISSUE TITLE
Consistently name <username>, YOUR_USERNAME, YourUsername in git repo tutorial

### ISSUE THREAD

**Issue by chase-metzger** [open-learning-exchange/open-learning-exchange.github.io#2568]
### Problem
I noticed while following along with the "Git Repositories" tutorial that goes with Step 5 of VI's first steps, that there are inconsistent ways of referring to the readers Github username as a placeholder. Despite being quite familiar with navigating Github and using git cli this led to a little confusion on my part because it's referring to the same username, I believe, all the time.

### Steps to reproduce the problem

open http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md

### Screenshots
Two examples below -

![Screen Shot 2019-07-18 at 8 05 44 PM](https://user-images.githubusercontent.com/47169887/61506760-14c3a500-a998-11e9-8b79-b5db65b3c9f7.png)

![Screen Shot 2019-07-18 at 8 07 23 PM](https://user-images.githubusercontent.com/47169887/61506761-14c3a500-a998-11e9-841c-b223fd7f7e16.png)
### Proposed solution

Rewrite vi-github-and-repositories.md to be most consistent about how to refer to the readers Github username (where applicable).

I'm not sure of what I would call the shared username across the sections yet.

Suggestions?

**Comment by Liew211** [comment]
@chase-metzger I think `your_username` would be fine.  Go ahead and work on this.

**Comment by chase-metzger** [comment]
@Liew211 Thanks, will do

**Comment by chase-metzger** [comment]
I'm noticing one thing that makes some sentences read odd with `your_username` as the consistent choice.

There are multiple instances where the word "your" is preceding the `username.github.io` that is already there. See below for how it would read now.

![Screen Shot 2019-07-18 at 9 00 44 PM](https://user-images.githubusercontent.com/47169887/61508541-2fe5e300-a99f-11e9-83cf-3af606067fa9.png)

**Comment by Liew211** [comment]
@chase-metzger hmm in that case just make all of them `username`

**Comment by lmmrssa** [comment]
`<>` symbol was added so people know that it is variable not static text. And this is general concept when you refer to commands.

**Comment by wanglihe2010** [comment]
I think this issue was solved and can be closed?

**Comment by wanglihe2010** [comment]
@chase-metzger I just noticed in the FAQ page of virtual intern, username in Q15 and Q16 are not consistent with what you changed in this issue. It will be better to change them too.

**Comment by robinGiri** [comment]
@wanglihe2010 its not Q15 and Q16 but Q16 and Q17

**Comment by AdhamElAsfar99** [comment]
There are still multiple instances where different styles are used to indicate that the "GitHub username" should be placed as highlighted below:

- **Step 1**
        ![image](https://github.com/user-attachments/assets/29978cfa-cce1-4dad-983e-4684178de89e)

- **Step 5**
        ![image](https://github.com/user-attachments/assets/a03678ab-3798-4688-82c0-12091d61e210)

- **Step 6**
        ![image](https://github.com/user-attachments/assets/371b3f3c-8f31-4d18-b410-1832775ce3d7)
 
I believe unifying the method used would clear any possible confusion. I can work on it if no one has already been assigned for this issue.

#### Proposed Solution

Using angle brackets `<>` since they are considered placeholders in general in git documentation and declaring this in a note at the beginning of the steps would make the process easier for everyone.

**Comment by xyb994** [comment]
@AdhamElAsfar99 Yes, you can claim this issue. Go ahead and create a pull request!
