### ISSUE TITLE
Inconsistency in Next Section --> 

### ISSUE THREAD

**Issue by siqiuma** [open-learning-exchange/open-learning-exchange.github.io#2570]
### Problem
Due to Pull Request #2533, currently there is inconsistency in the "Next Section -->" part among all the pages with instructions for the first steps. More specifically, [Planet Installation](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md) and [Planet Configurations](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md) do not specify what the next section number is (see the first screenshot for reference), while all the other pages do specify the next section number (see the second screenshot as an example). 

### Steps to reproduce the problem

1. Go to [Planet Installation](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md) and [Planet Configurations](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md), and scroll down to the bottom to see "Next Section -->"
2. Go to all other first step pages and scroll down to the bottom to see "Next Section -->". These pages include [Nation Planet](http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md), [Github Issues](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md), [Git Repositories](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md), [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md), [Github and Markdown](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md), [Docker Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md), [Vagrant Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-vagrant.md)

### Screenshots

[Planet Installation](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md) and [Planet Configurations](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md): 
![Screen Shot 2019-07-19 at 6 03 51 PM](https://user-images.githubusercontent.com/38894754/61568049-a6dab480-aa4f-11e9-96b8-2b02ca9b5c28.png)

All other First Step pages:
![Screen Shot 2019-07-19 at 6 04 52 PM](https://user-images.githubusercontent.com/38894754/61568066-bb1eb180-aa4f-11e9-947e-08c671378c70.png)

### Proposed solution

1. On page [Planet Installation](http://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md), replace "Next Section -->" with "Next Section (Step 1.2) -->". 
2. On page [Planet Configurations](http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md) replace "Next Section -->" with "Next Section (Step 1.3) -->".

**Comment by ChiragAwale** [comment]
Go ahead also maybe consider putting in the word subsection as well
