### ISSUE TITLE
Typos in the Planet User Manual

### ISSUE THREAD

**Issue by biswasshrestha** [open-learning-exchange/open-learning-exchange.github.io#2573]
### Problem
The Planet User Manual page [http://open-learning-exchange.github.io/#!./pages/techgenius/tg-planet-user-manual.md](url) referenced in the NOTE section in Step 0 has few typos and errors.

### Errors

1. "a" and "the" are used together in "Planet currently follows a the Library of Congress "
2. ...at any time by click on “Feedback”...

### Screenshots

1. 
![image](https://user-images.githubusercontent.com/52227513/61573834-c667f080-aad4-11e9-9070-644dcc7e6af0.png)

2. 
![image](https://user-images.githubusercontent.com/52227513/61573831-b2bc8a00-aad4-11e9-9949-5b8168560c4d.png)

### Proposed solution

Make the following corrections:
1. "Planet currently follows the Library of Congress "
2. ...at any time by clicking on “Feedback”...

Please let me know if I can start fixing it.

**Comment by sjson421** [comment]
@biswasshrestha Go right ahead.
