### ISSUE TITLE
Update the Outdated Image for GitHub Notifications Options

### ISSUE THREAD

**Issue by biswasshrestha** [open-learning-exchange/open-learning-exchange.github.io#2576]
### Problem
The image shown on the First Steps page for Step 0 http://open-learning-exchange.github.io/#!./pages/vi/vi-first-steps.md#Step_0_-_Introductory_Steps is outdated as GitHub has added one more option for being notified for "Releases only" which is a great improvement from GitHub  because it reduces the large number of emails into the most important ones.

### Steps to reproduce the problem

Compare the screenshot featured on the First Steps page (also listed below) with the current options provided by GitHub (see the second screenshot below).

### Screenshots

What is in the First Steps page:
![image](https://user-images.githubusercontent.com/52227513/61582238-d7057e80-ab47-11e9-85aa-67e638e279c0.png)

What is currently available on GitHub:
![image](https://user-images.githubusercontent.com/52227513/61582243-e684c780-ab47-11e9-8c8c-1e29fdbf3d4a.png)

### Proposed solution

In light of the update from GitHub, I believe it is time to incorporate the updated image into the First Steps page and maybe providing prospective interns to select the new option of "Releases only" as well.

Please let me know if I can start working on it and also if you have any feedback. Thank you.

**Comment by aasenomad** [comment]
I think it's a good idea. I also noticed that some pages still have outdated images and I think It's time to update them all with a new version image.
