### ISSUE TITLE
Make the Layout of the Images Consistent

### ISSUE THREAD

**Issue by biswasshrestha** [open-learning-exchange/open-learning-exchange.github.io#2577]
### Problem
The last two images on the Email Overview section of the Planet User Manual Page http://open-learning-exchange.github.io/#!./pages/techgenius/tg-planet-user-manual.md#Email_Overview are stacked side by side and the description for the second image is placed on its right side. This section can be made more readable by making it consistent with the rest of the page.

### Steps to reproduce the problem

See the image at the link mentioned in the Problem part. The image is also provided in the Screenshots section below.

### Screenshots

![image](https://user-images.githubusercontent.com/52227513/61582297-e20cde80-ab48-11e9-8e50-80a276bc9d4e.png)

### Proposed solution

To promote clarity and improve consistency with the rest of the images, I propose moving the second image and its description below the first image.

**Comment by bradlet** [comment]
I, too, think this would be more clear. I think focusing on top-down order over left-right is better for readability in most cases in web pages.
