### ISSUE TITLE
Add Reminder to a More Appropriate Step

### ISSUE THREAD

**Issue by biswasshrestha** [open-learning-exchange/open-learning-exchange.github.io#2579]
### Problem
The Step 0.3 of First Steps asks the aspiring interns to checkout a link after finishing Step 4. Since the user might not recall this statement once they reach Step 4, I propose moving the statement with the link to Step 4 or at least adding a reminder. 

### Steps to reproduce the problem

See "After finishing Step 4 - Planet Tutorial, check out this link to learn how you can start contributing on Crowdin." at http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md

### Screenshots

![image](https://user-images.githubusercontent.com/52227513/61604872-f7762b80-ac62-11e9-8456-27bd21902a67.png)

### Proposed solution

Move the highlighted statement to the end of Step 4 or adding a reminder as: "Once you are done with Step 4 - Planet Tutorial, you may check out the link to learn how you can start contributing on Crowdin as mentioned in Step 0.3."

Please let me know if I can correct this.

**Comment by ChiragAwale** [comment]
You can work on it
