### ISSUE TITLE
Add Hyperlinks in the Nation Planet page

### ISSUE THREAD

**Issue by biswasshrestha** [open-learning-exchange/open-learning-exchange.github.io#2580]
### Problem
The Nation Planet page has a NOTE section which says: "If you can not create dummy user, please click on the helpful links and videos under the Useful Links section at the bottom of the Nation Planet page. Once there, scroll up to Q22 for a solution, which is located under the Technical questions section." It would be more convenient for the users if we add hyperlinks to the said pages.

### Steps to reproduce the problem

See the NOTE section in the Nation Planet page at: http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md

### Screenshots

![image](https://user-images.githubusercontent.com/52227513/61604964-3d32f400-ac63-11e9-820f-9c875c5ce066.png)

### Proposed solution

Add a hyperlink to http://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md#Useful_Links where it is mentioned.

Please let me know if I can correct this.

**Comment by aasenomad** [comment]
True. That will be really helpful since they can directly get to the page.
