### ISSUE TITLE
Information on committing and pushing changes

### ISSUE THREAD

**Issue by balabhv** [open-learning-exchange/open-learning-exchange.github.io#259]
In gitandrepositories.md, there should also be information about committing files from the local command line and pushing them up to the user's fork prior to making a pull request.

**Comment by dogi** [comment]
hmm - agree

tell us more ;)

**Comment by mappuji** [comment]
@dogi I want to add the following instruction from the @balabhv  recommendations:

> * Before you can push a local change of your work to the remote repository, you should *add* and *commit* your local changes in the local repository.
> `git add <the_file_name>`
> * After you add your work you can commit the changes with the following command:
> `git commit -m "<your_messages_here>"`
> * After that you can push your changes to your remote fork using the following command:
> `git push origin master`
> * Great! you have successfully push your changes to your remote fork. Now you can create a pull request regarding your change.

**Comment by dogi** [comment]
@mappuji sorry I just realized that this issue makes no sense
sorry again
