### ISSUE TITLE
Small typo in the planet user manual page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2595]
### Problem

In the middle of this page http://open-learning-exchange.github.io/#!./pages/techgenius/tg-planet-user-manual.md, it has a small typo.

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2019-07-23 14-26-14](https://user-images.githubusercontent.com/37007141/61738195-bdd31c80-ad57-11e9-9baa-ecbf65090b48.png)

### Proposed solution

Just delete the typo.

**Comment by 275vytran** [comment]
Good catch

**Comment by aasenomad** [comment]
I already fixed it but there was another extra commit under this PR so I'm going to close this one.
