### ISSUE TITLE
Include command to delete remote repository

### ISSUE THREAD

**Issue by bradlet** [open-learning-exchange/open-learning-exchange.github.io#2598]
### Problem
The "Delete Branch" section of **Step 6 - Github Issues Tutorial** instructs new interns on how to delete a local branch from the command line, and then the remote branch using Github. This step would just include 2 command-line alternatives to delete the remote branch.

### Screenshots
![image](https://user-images.githubusercontent.com/47132003/61755567-1660e480-ad6d-11e9-94b2-81ba6bbac6d5.png)

### Proposed solution
My proposal is to mention "_git fetch -p_" to prune all 'stale' - or unused - remote branches. It may be worthwhile mentioning in he **"Delete the branch from your local repository"** section, that the intern can use the command "_git push [remoteName] :[branchName]_" to update the remote repo, deleting the remote branch.

*In my opinion these should be appended to the **"Delete the branch from your local repository"** section.*

**Comment by ChiragAwale** [comment]
You can work on it
