### ISSUE TITLE
Include a link to Github's cheat sheet

### ISSUE THREAD

**Issue by bradlet** [open-learning-exchange/open-learning-exchange.github.io#2599]
### Problem
There is a markdown cheat sheet, but no Github equivalent!

### Steps to reproduce the problem
N/A

### Screenshots
[Link to the cheat sheet](https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf)

### Proposed solution
Add the link that I included under "Screenshots" either directly beneath the Markdown cheat sheet, or in the **useful links** section (I prefer the latter).

**Comment by aasenomad** [comment]
I think it will be great to add that link. It will be very useful for some people.

**Comment by ChiragAwale** [comment]
@bradlet good idea.
