### ISSUE TITLE
Updating an old link and image from vi github issue page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2600]
### Problem

It seem like all images are up to date except one image from this page ( http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md ) so I think it might be a good idea to update this one too.

### Screenshots

![Screenshot from 2019-07-23 20-25-06](https://user-images.githubusercontent.com/37007141/61756342-841b0980-ad89-11e9-8166-62de602db73d.png)

### Proposed solution

For the example link, I can either use mine ( https://raw.githack.com/aasenomad/aasenomad-ole.github.io/aasenomad-patch-1/#!index.md ) or some other intern links. Just let me know.

![Screenshot from 2019-07-23 20-33-21](https://user-images.githubusercontent.com/37007141/61756274-428a5e80-ad89-11e9-9c7c-e296e007091d.png)

**Comment by bradlet** [comment]
I glazed over this and didn't even realize the existing githack link was an example of the planet. I'd call this a good change.
