### ISSUE TITLE
No details for surveys in planet user manual page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2601]
### Problem
I noticed that there are no details for the survey part in user manual page ( http://open-learning-exchange.github.io/#!pages/manual/planet/overview.md ).

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2019-07-23 22-43-21](https://user-images.githubusercontent.com/37007141/61761032-72daf880-ad9b-11e9-9dc5-4eb3069bf687.png)

### Proposed solution

Since there is no surveys.md yet, 

![Screenshot from 2019-07-23 22-45-09](https://user-images.githubusercontent.com/37007141/61761142-cf3e1800-ad9b-11e9-9a4d-491b1f721b38.png)

I know that the teams are currently working on the survey manual page but I think it might be best to put WIP (work-in-progress) for the detail part instead of leaving it blank so that people are not wondering what happened. Let me know if I can add that. Thank

**Comment by lmmrssa** [comment]
@aasenomad Manual section is being worked on so right now there is only placeholder in some places. And we are right now not referencing anyone to it.
So closing it for now.
