### ISSUE TITLE
Meetup.md link is broken in planet user manual page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2602]
### Problem

Meetups.md link is broken in Planet User Manual page (http://open-learning-exchange.github.io/#!pages/manual/planet/overview.md)

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2019-07-23 22-58-38](https://user-images.githubusercontent.com/37007141/61762005-863b9300-ad9e-11e9-9b39-0ba2c20f3b79.png)

![Screenshot from 2019-07-23 23-01-20](https://user-images.githubusercontent.com/37007141/61762009-8b98dd80-ad9e-11e9-9d32-6f28a949115b.png)

### Proposed solution

Fixing will be very simple since I noticed that it just minor typo that cause not to connected to meetups page. Let me know if I can fix that. Thank

**Comment by lmmrssa** [comment]
@aasenomad Yes please work on this.
