### ISSUE TITLE
Labeling option 1 and 2, when directing how to get into courses page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2606]
### Problem

On this page ( http://open-learning-exchange.github.io/#!./pages/manual/planet/./course.md ), when it giving out 2 ways to get into courses page It label as 1 [Image] and 1 [Image]. I think it can be a little bit confusing for the first time readers.

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2019-07-24 23-47-49](https://user-images.githubusercontent.com/37007141/61844690-480da480-ae6e-11e9-879e-71fa3337f67a.png)

![Screenshot from 2019-07-24 23-48-05](https://user-images.githubusercontent.com/37007141/61844696-4cd25880-ae6e-11e9-9783-2dbe24cfcbb1.png)

### Proposed solution

We can make a little bit more clear by adding [Option 1] and [Option 2] lable/note before the start of the sentences. Let me know If I can add that, Thank.

**Comment by ChiragAwale** [comment]
Good catch. You can work on it.
