### ISSUE TITLE
Update the image on achievement page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2608]
### Problem
On the achievements page ( http://open-learning-exchange.github.io/#!./pages/manual/planet/achievement.md ) It telling us 2 options we can do in this particular section in Planet but without highlighting them inside the picture so I think it will be good idea to higlight them just like some of the pictures.

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2019-08-03 00-24-20](https://user-images.githubusercontent.com/37007141/62407351-163ec100-b585-11e9-9175-8051bac4dc3a.png)

### Proposed solution

 update the first image with this,

![imageedit_15_6385317407](https://user-images.githubusercontent.com/37007141/62407331-944e9800-b584-11e9-9585-a2fb977e96c4.jpg)

**Comment by lmmrssa** [comment]
@aasenomad Not sure why are you asking to remove this number. These are two different features. (1) is feature to add achievement and (2) is to add reference

**Comment by ChiragAwale** [comment]
@lmmrssa @aasenomad I am not sure about the numbers, but you change the image as it highlights the buttons

**Comment by ChiragAwale** [comment]
<img width="532" alt="Screen Shot 2019-07-31 at 9 45 00 AM" src="https://user-images.githubusercontent.com/19680263/62221859-fe462200-b377-11e9-9ee9-35a8a920c59c.png">
Also I see the number "1" twice

**Comment by aasenomad** [comment]
@lmmrssa @ChiragAwale I was thinking about removing the number because it said " On this page, you will be able to Enter an Achievement **or** Enter a Reference"

I guess we can just change OR to AND.  let me know, Thank

**Comment by aasenomad** [comment]
@ChiragAwale : Yup I been seeing that a lot. I'm not sure why it does that. I check it on Github but it's fine (I see 1 & 2 ) but on the actual page it sees #1 twice too.
