### ISSUE TITLE
Static Server in Master Branch

### ISSUE THREAD

**Issue by benjammin12** [open-learning-exchange/open-learning-exchange.github.io#261]
##Master Branch Server

There has to be a way to create a static server and display your website using github.io inside the master branch instead of gh-pages for easier syncing.

**Comment by benjammin12** [comment]
These look promising..  

https://pages.github.com/

https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by dogi** [comment]
hui

that;s awesome

@benjammin12 can you make suggestions how to redesign the steps based on this?

**Comment by benjammin12** [comment]
# Step 1: Go into settings under on the main page of your repository that you want hosted with github pages

<img width="1042" alt="screen shot 2016-08-28 at 7 34 18 pm" src="https://cloud.githubusercontent.com/assets/13541660/18037656/a1699a62-6d57-11e6-8b9a-30c5716434a4.png">

# Step 2: Scroll down to github pages and change the source to 'Master Branch' and select save.

<img width="740" alt="screen shot 2016-08-28 at 7 35 13 pm" src="https://cloud.githubusercontent.com/assets/13541660/18037666/d2c8a878-6d57-11e6-8563-1a7e9c392065.png">

# Step 3: Click on the newly created link.  

<img width="735" alt="screen shot 2016-08-28 at 7 35 51 pm" src="https://cloud.githubusercontent.com/assets/13541660/18037674/f9ffbff8-6d57-11e6-8f0a-d1c0679a3b39.png">

###  You can add the link to your README.md file.  From your terminal navigate to your repository then enter

echo "link that was created in step 3" >> README.md

**Comment by benjammin12** [comment]
@dogi

**Comment by dogi** [comment]
@benjammin12 awesome steps ;)
wonder how we should change our http://open-learning-exchange.github.io/#!pages/newfirststeps.md

**Comment by aberdean** [comment]
Solved.
