### ISSUE TITLE
Typo number on the feedback page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2616]
### Problem

Just a small typo on the feedback page (Giving feedback to different items section). Number 3 are duplicated. Let me know, If I can work on it. Thank

Just FYI

* I'm not sure why, If you look the issue using this link ( https://open-learning-exchange.github.io/#!./pages/manual/planet/feedback.md ), number 1 will be duplicated for all the steps. I have seen this many time in different pages but still can't figure out the reasons yet.

BUT

* If you look at the code on github (https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/manual/planet/feedback.md), the number will listed correctly except the duplicated number 3.

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2019-08-03 19-10-12](https://user-images.githubusercontent.com/37007141/62417650-e645fb00-b622-11e9-8e57-57d3111c1559.png)

### Proposed solution

Just change it to 4.

**Comment by ChiragAwale** [comment]
I am not sure about the second issue but you can change the 3 to 4.
