### ISSUE TITLE
Clarifying the Path variable 

### ISSUE THREAD

**Issue by Ebuka-Chibueze** [open-learning-exchange/open-learning-exchange.github.io#262]
It would help to mention how to add virtualbox to path environment variables in [Step # 1](https://github.com/dogi/ole--vagrant-bells)  since that is where the  vboxmanage --version command is mentioned first.

**Comment by Ebuka-Chibueze** [comment]
Unlike Vagrant, VirtualBox does not automatically commands your system path. For Git commands, it depends on its installation setup. This could make some potential stumbling blocks for windows users for using VirtualBox and Git on the command prompt. 

Here are my suggestions:

- Explaining how to add VirtualBox to path environment variables

- Explaining how your set up for Git affects your PATH environment(see picture below)

![pic](http://i.stack.imgur.com/5szjG.png)

**Comment by dogi** [comment]
@Ebuka-Chibueze that's a good one
keep going on this issue (-> pull request)

by the way for git install last option
"Run Git and include Unix tools fromthe Windows Command Prompt" is my favorite

**Comment by aberdean** [comment]
No longer relevant with new simpleinstall.
