### ISSUE TITLE
Missing Exams title and description on Manual Page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2623]
### Problem

On this page ( https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md ) there is a list of features listed with a number and you will see Exams on no.3 but you not gonna see that on the below where there is the title and descriptions.

### Screenshots

![1](https://user-images.githubusercontent.com/37007141/62977140-37f14100-bdec-11e9-83bb-9cecfe9203d8.png)

![2](https://user-images.githubusercontent.com/37007141/62977474-f9a85180-bdec-11e9-8fde-d13436bd540c.png)

### Proposed solution

I know that, the team is developing Surveys page so I think we can just add the Exams title just like the Surveys without any description. We can add the descriptons for Exams later when we make a new Exams page.

**Comment by raisinman99** [comment]
Good catch I think you should work on this
