### ISSUE TITLE
Typo error on orientation page

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/open-learning-exchange.github.io#2627]
### Problem
"Planet" is in red color and not capitalized

### Steps to reproduce the problem

N/A

### Screenshots

<img width="1594" alt="Screen Shot 2019-08-14 at 10 06 20 PM" src="https://user-images.githubusercontent.com/11765890/63070608-787eb680-bee1-11e9-8088-01b27282bc0b.png">

### Proposed solution

Capitalize initial P should solve the issue

**Comment by raisinman99** [comment]
This is a very small issue but you can still work on it

**Comment by aasenomad** [comment]
Yup agree, a small change but having consistency is the key.

**Comment by wanglihe2010** [comment]
@raisinman99 Hi, I just fixed the issue, can you review? https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/2630

**Comment by raisinman99** [comment]
@wanglihe2010 Approved from me
