### ISSUE TITLE
organized  as step and sub step instead of section

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/open-learning-exchange.github.io#2629]
### Problem
Since the "first steps" page is organized as "steps" instead of "sections", it would make more sense to keep it consistent by using "sub-steps" instead of "sections" in step 1. Accordingly, I would suggest to replace all the "section" with "step" in the step detail page.

### Steps to reproduce the problem
visit page : https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md

### Screenshots

<img width="906" alt="Screen Shot 2019-08-15 at 10 03 26 PM" src="https://user-images.githubusercontent.com/11765890/63140770-a5e26780-bfa8-11e9-8d10-13f8d16cbe20.png">

<img width="1137" alt="Screen Shot 2019-08-15 at 3 47 00 PM" src="https://user-images.githubusercontent.com/11765890/63125873-5124f980-bf74-11e9-8aa6-b91022837e98.png">

### Proposed solution

1. replacing all "section" to "step".
2. In the step 1, change section to step 1.1, 1.2, 1.3

**Comment by raisinman99** [comment]
I think this would be helpful but for the first sentence you can write "There are 3 sub-steps in this step". Do work on this.

**Comment by wanglihe2010** [comment]
@raisinman99 Hi, Faraz, I fixed the issue, can you approve the PR?
