### ISSUE TITLE
Attention on Docker tutorial

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/open-learning-exchange.github.io#2633]
### Problem
The "Attention" in the first screenshot below should be highlighted in a brighter color, like the orange color in the second screenshot, so that it can bring viewers’ attention more effectively. The reason I brought this up was because I did not get to see this warning at all, which led me accidentally deleted planet configuration. 

Also it should provide solutions as to how to get this resolved if planet configuration is deleted accidentally

### Steps to reproduce the problem

visit page https://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md#Docker_&_Planet

### Screenshots

<img width="1147" alt="Screen Shot 2019-08-16 at 12 00 54 AM" src="https://user-images.githubusercontent.com/11765890/63144705-be0eb280-bfb9-11e9-938b-44d6f4952294.png">
<img width="1097" alt="Screen Shot 2019-08-16 at 12 00 34 AM" src="https://user-images.githubusercontent.com/11765890/63144710-c0710c80-bfb9-11e9-832b-20c8ae4abd85.png">

### Proposed solution

Change "Attention" to "Warning", and change background color to orange.
According to @dogi , the easiest to way to solve it is recreating a new planet configuration with a slightly different name. We can say "If you are in this situation, look at the second and third element of Troubleshooting in this page" and add a link referring to page https://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md#Troubleshooting. This will be consistent with above warning screenshot.

**Comment by perryc85** [comment]
You can work on this.

**Comment by wanglihe2010** [comment]
@perryc85  Hi, Charles, I just fixed the issue and made a pull request, please review.
