### ISSUE TITLE
Small typo on team page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2634]
### Problem
There is a small typo on the team page ( https://open-learning-exchange.github.io/#!./pages/manual/planet/teams.md ). It should be 3 instead of 2 again.

I created a new branch from my repo and already try to fix it and it really work unlike other similair issue I created in the past. You will see the number change when I'm done fixing it.

Let me know if I can work on it. Thank

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot_2019-08-16_15-26-44](https://user-images.githubusercontent.com/37007141/63193009-66fcf200-c03a-11e9-8385-5be97d017244.png)

### Proposed solution

Just change 2 to 3.

**Comment by raisinman99** [comment]
You can work on this.

**Comment by Mattmtech** [comment]
good catch!
