### ISSUE TITLE
Small typo on issues page

### ISSUE THREAD

**Issue by Mattmtech** [open-learning-exchange/open-learning-exchange.github.io#2638]
### Problem
There's small capitalization typos on the [issues page](https://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md) the words circled in red in my screenshot below should be lowercase

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/44531565/63216909-c9fd9000-c0f1-11e9-8f8c-292ea506ac1b.png)

### Proposed solution
edit the words to their lowercase counterparts to ensure consistency for future readers

**Comment by perryc85** [comment]
Good catch. You can work on this.

**Comment by wanglihe2010** [comment]
good catch
