### ISSUE TITLE
typo error capitalization on title

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/open-learning-exchange.github.io#2640]
### Problem
small typo error. Title should be capitalized initial. 

### Steps to reproduce the problem

visit page https://open-learning-exchange.github.io/#!pages/vi/vi-chat.md

### Screenshots

<img width="1523" alt="Screen Shot 2019-08-17 at 10 28 04 PM" src="https://user-images.githubusercontent.com/11765890/63219760-a280e480-c13e-11e9-8dab-d4c028b0291f.png">

### Proposed solution

change to "Open-Learning-Exchange/Chat"

**Comment by ChiragAwale** [comment]
I dont think that is necessary, it is also how the naming convention is in gitter itself so.
