### ISSUE TITLE
Updating pic and info on News page

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2642]
### Problem
On the bottom of this page (https://open-learning-exchange.github.io/#!./pages/manual/planet/news.md) you will see Editing or Deleting Stories section but I noticed that the picture and information are outdated. I think it will be a great idea to update using the current version. Let me know if I can work on it. Thanks

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot_2019-08-18_12-54-52](https://user-images.githubusercontent.com/37007141/63227697-69d12180-c1b7-11e9-8ca7-f857e34163d3.png)

### Proposed solution

![imageedit_3_4232607986](https://user-images.githubusercontent.com/37007141/63227856-4313ea80-c1b9-11e9-8395-9ddfbd0a0dd9.png)

Change the tittle to: Reply, Edit and Delete Stories
Change the information to: You can reply a story by clicking reply icon on the post (Purple circle), edit a story by clicking the pencil icon (Red circle) and delete a story by clicking the garage can icon (Blue circle)

**Comment by ChiragAwale** [comment]
@aasenomad You can work on it
