### ISSUE TITLE
Fix error in step7 nation planet

### ISSUE THREAD

**Issue by Mattmtech** [open-learning-exchange/open-learning-exchange.github.io#2643]
### Problem
incorrect instructions for step 2. In order to view the manager settings page you need to be logged on an admin account not logged in the dummy account. https://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md
### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/44531565/63230007-ee25a380-c1bb-11e9-8b4c-bce0c6695090.png)

### Proposed solution

instruct future interns to log onto their admin account to view the members of their planet

**Comment by wanglihe2010** [comment]
I think the step 2 was to make sure dummy account is a member/ leaner. And step 3 was to log in admin account and find dummy account listed under Members on the Manager settings page. Maybe we need step 4 to start sync with nation.

**Comment by Mattmtech** [comment]
@wanglihe2010 maybe, but then it is confusing since step 2 says "...double-check that you're listed under Members on the Manager Settings page." but there is no manager settings page as a learner. As a learner to see the members you can click on either "teams" or "my teams" then click on "all members" to show the members

**Comment by ChiragAwale** [comment]
@Mattmtech  Good catch. It should be logged in as admin account. You can work on it.
