### ISSUE TITLE
add emphasis for step 6

### ISSUE THREAD

**Issue by Mattmtech** [open-learning-exchange/open-learning-exchange.github.io#2645]
### Problem
text should be bold to better attract interns attention and to better communicate that it is recommended to continue working on other steps while waiting for pull request to merge. https://open-learning-exchange.github.io/#!./pages/vi/vi-first-steps.md#Step_7_-_Nation_Planet

### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/44531565/63234992-ac612100-c1ec-11e9-9a29-6204e87afb30.png)

### Proposed solution

Bold the text that is circled in red

**Comment by wanglihe2010** [comment]
I agree with you, bold text will have emphasis effect.

**Comment by ChiragAwale** [comment]
@Mattmtech Go ahead.

**Comment by johnmdrake1** [comment]
I added some of that wording as I also felt the need for increased clarification that it is OK to move on, but did not think to bold portions, great idea. The line beginning "Please Note" is another portion I added in a previous merge, if you find anything in that sentence/paragraph that needs more emphasis, bold it as you see fit as part of your fix. I am glad there are other aspiring interns that agree Step 6 in particular needs some emphasis, good on you for noticing and fixing it.
