### ISSUE TITLE
Change Submissions to my Submissions in Step 4

### ISSUE THREAD

**Issue by 007HD** [open-learning-exchange/open-learning-exchange.github.io#2646]
first step intern
### Problem
In Step 4 - [Planet Tutorial](https://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md) page under
 **Take the Course**, Step 5: - 

5. To verify that your course answers were submitted, click on `Home`, then on `Submissions`

![Screenshot (1113)](https://user-images.githubusercontent.com/36314732/63247524-16dc8600-c21a-11e9-8692-ffd24e8ebb59.png)

`Submissions` *should be changed to* `my Submissions` as shown in the attached screenshot

### Steps to reproduce the problem
N/A

### Screenshots
![Screenshot (1112)](https://user-images.githubusercontent.com/36314732/63246320-42aa3c80-c217-11e9-84c0-82d335ad0bb4.png)

### Proposed solution
5. To verify that your course answers were submitted, click on `Home`, then on `Submissions`
_Should be changed to_
5. To verify that your course answers were submitted, click on `Home`, then under `myLife` click on `my Submissions`   
And [Screenshot 7](https://open-learning-exchange.github.io/pages/vi/images/vi-planet-submissions-button.png) in [Planet Tutorial](https://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md) should also be updated with the attached screenshot

**Comment by raisinman99** [comment]
You can do this

**Comment by 007HD** [comment]
@raisinman99 OK, I will create a PR for this issue and start working on it.
