### ISSUE TITLE
Index suggestion/ typo

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/open-learning-exchange.github.io#2647]
### Problem
Index of trouble shooting is 1,2,3,4,1 as indicated in the screenshot. I think the last one should be index 5 or index 4.1 or no index.

### Steps to reproduce the problem

Visit page : https://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md

### Screenshots

<img width="634" alt="Screen Shot 2019-08-19 at 2 37 45 PM" src="https://user-images.githubusercontent.com/11765890/63294119-2ea22180-c28f-11e9-8693-8c47d79bf230.png">

### Proposed solution

change last index 1 to 5 or 4.1 or delete.

**Comment by raisinman99** [comment]
Yes it should be changed to 5. Please work on this.

**Comment by Mattmtech** [comment]
nice catch!

**Comment by wanglihe2010** [comment]
@raisinman99 Hi, Faraz, I fixed the issue, can you approve the PR?
