### ISSUE TITLE
outdated picture

### ISSUE THREAD

**Issue by Mattmtech** [open-learning-exchange/open-learning-exchange.github.io#2650]
### Problem
there is an outdated picture in the how to become a member section of the planet. https://open-learning-exchange.github.io/#!./pages/techgenius/tg-planet-user-manual.md

### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/44531565/63314265-ee0ccd00-c2bb-11e9-8407-5bb82abb625e.png)

### Proposed solution

use this picture instead
![image](https://user-images.githubusercontent.com/44531565/63314296-011f9d00-c2bc-11e9-87b0-61a069f3b11c.png)

**Comment by ChiragAwale** [comment]
@Mattmtech Go ahead with this. Nice one.

**Comment by Mattmtech** [comment]
@ChiragAwale Thank you!
