### ISSUE TITLE
Typo in Virtual Intern Course Step 7

### ISSUE THREAD

**Issue by saraive16** [open-learning-exchange/open-learning-exchange.github.io#2651]
### Problem
In Step 4 Planet Tutorial in the Virtual Intern course Step 7: Github - Branching, there is a typo in Preview Question 3 first answer option.

The first answer should say "Fork" not "ork" in the first answer of Question 3.

### Steps to reproduce the problem
1. Log into Planet
2. Add Virtual Intern Course to myCourse
3. Begin course and continue until Step 7 
4. Step 7 press "preview test" button. Problem occurs in question 3

### Screenshots

![image](https://user-images.githubusercontent.com/53923848/63371123-5600f900-c338-11e9-89fc-8ecc273d9ad0.png)

### Proposed solution
Change word from "ork" to "Fork" in the answer option.

**Comment by raisinman99** [comment]
This is a problem on the Planet application. You should look for issues with the OLE wiki instead. Once you are an intern then you can work on Planet.
