### ISSUE TITLE
Typo in Virtual Interns Introduction/First Steps Page under Step 1 - Planet and Vagrant

### ISSUE THREAD

**Issue by saraive16** [open-learning-exchange/open-learning-exchange.github.io#2652]
### Problem
Typo in Virtual Interns Introduction/First Steps Page under Step 1 - Planet and Vagrant. All of the times "Vagrant" is mentioned it is capitalized except in Step 1 - Planet and Vagrant in the step 1. Planet Installation with vagrant section. 

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/53923848/63380108-a8e3ac00-c34a-11e9-863a-8a1f3f36c5e9.png)

### Proposed solution
Change "Planet Installation with vagrant" to "Planet Installation with Vagrant".

**Comment by raisinman99** [comment]
You can work on this
