### ISSUE TITLE
Planet Installation Consistency

### ISSUE THREAD

**Issue by saraive16** [open-learning-exchange/open-learning-exchange.github.io#2653]
### Problem
The use of "community Planet" capitalization is not consistent in the Planet Installation Page. 

### Steps to reproduce the problem
N/A

### Screenshots

![image](https://user-images.githubusercontent.com/53923848/63384733-53140180-c354-11e9-96da-04e65ff2c16e.png)

### Proposed solution
Change all mentions of "community planet" to "community Planet".

**Comment by raisinman99** [comment]
Do work on it

**Comment by johnmdrake1** [comment]
Good catch, I have noticed some inconsistencies on capitalization(not just lowercase things that should be uppercase, but also inconsistent capitalization of things that should probably not be capitalized) Fixing every occurrence of what I'm describing would be a lot of files to change in one merge, but this is a great start.

Something that may help you while you work on this: ctrl+f(on pc) or command+f(on mac) will let you search for occurrences of a word or phrase, in this case "community planet", in most browsers and text editors like Sublime. This should help you when going through and changing, if you didn't already know that trick :)
