### ISSUE TITLE
Fixing Incorrect Username Prompt On Tracking Progress Page

### ISSUE THREAD

**Issue by johnmdrake1** [open-learning-exchange/open-learning-exchange.github.io#2655]
### Problem
On the "Tracking Progress" page at https://open-learning-exchange.github.io/#!pages/vi/vi-track-progress.md , when an incorrect username is entered, "ERROR: User baduser598 does not exists." is returned.

### Steps to reproduce the problem

Enter a bad GitHub Username on the Tracking Progress page

### Screenshots

<img width="347" alt="Screen Shot 2019-08-20 at 4 33 08 PM" src="https://user-images.githubusercontent.com/32374869/63391764-a4c68700-c368-11e9-95d2-2f2efad99c0f.png">

### Proposed solution

I would like to change the error portion of the vi-track-progress.md file(I've already isolated it) to remove the "does not exists"(improper grammar, should be "does not exist"). I would like to change it to say something along the lines of "Error: baduser598 is not a valid GitHub Username. Make sure you are entering a valid GitHub Username. 

I can make this change as soon as I get the go-ahead. Thanks!

**Comment by raisinman99** [comment]
This is a good fix. You can work on this.

**Comment by saraive16** [comment]
This is a great suggestion. Accuracy is always a better solution.

**Comment by johnmdrake1** [comment]
@raisinman99 @saraive16 I'm on it, I apologize as I was out of internet access for several days but will now work on this.

**Comment by raisinman99** [comment]
@johnmdrake1 no problem :)
