### ISSUE TITLE
Writing, Grammar, Making things Clearer on Nation Planet Page

### ISSUE THREAD

**Issue by johnmdrake1** [open-learning-exchange/open-learning-exchange.github.io#2656]
### Problem
I pride myself in excellent writing, grammar, and proofreading skills, and have been wanting to lend what I can to how certain parts of the Wiki are written. I figured instead of making one issue for proofreading all wiki pages, I should isolate each one I may want to change. 

I figure Step 7-Nation Planet is a good page for me to do, as even though the page is already very good, it can be made better.

### Steps to reproduce the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-nation.md

### Proposed solution

I propose correcting grammar mistakes where they are present and making the overall writing of the page better. Here are a few examples, though it will be clearer when I get to work and do the whole vi-nation.md page(I tried to bold parts with my changes, though, of course, bolding that was originally present on the page will be preserved):

Old: "Then go to Manager Page. You should see option to Upgrade.
If you do not see Upgrade button please check Nation version and Local version. If both of those are same your planet is already upto-date. In case you see any other message below Version, then send a message on chat channel along with screenshot."

New: Then go to **the** Manager Page. You should see **an** option to **perform an** Upgrade.
If you do not see **the** Upgrade button, please check **your current** Nation version and Local version. If both **versions appear to be the same, this indicates** your **Planet** is already **up-to-date**. **If you see any other message(s) below your**  version, **please send a message on the Gitter Chat Channel along with a screenshot of what you are seeing.** 

Old: Click on Upgrade button and you will see upgrade page. Click Start Upgrade button.

New: Click on **the Upgrade button and you will be presented with the Upgrade page. Click on the Start Upgrade button.**

Old: You should see log of upgrade process along with progress bar. Once upgrade is complete you will see the message saying upgrade was successful.

New: You should **then see a log of the current upgrade proccess** along with **a** progress bar. Once **the upgrade has completed, a message will appear informing you that the upgrade was successful.**

**Comment by lmmrssa** [comment]
sure you can work on it

**Comment by johnmdrake1** [comment]
> sure you can work on it

Ok, I am on it and will be fixing it and submitting a pull request. Thank you.

**Comment by smitshrestha101** [comment]
the fix on the issue looks good. great job!

**Comment by johnmdrake1** [comment]
Thank you @smitshrestha101 and reviewers! I'm very happy to help, and like doing this kind of stuff even if it isn't directly coding related :)
