### ISSUE TITLE
Docker Need Not be Started Manually

### ISSUE THREAD

**Issue by johnmdrake1** [open-learning-exchange/open-learning-exchange.github.io#2657]
### Problem
I have worked on projects that use Docker before, and for those projects I had to open docker 
<img width="149" alt="Screen Shot 2019-08-20 at 7 30 03 PM" src="https://user-images.githubusercontent.com/32374869/63395434-f11dc100-c380-11e9-83e2-d2cae1e17413.png">

and then have it running in my task bar as so

<img width="224" alt="Screen Shot 2019-08-20 at 7 30 58 PM" src="https://user-images.githubusercontent.com/32374869/63395474-1c081500-c381-11e9-9025-9c7d27de950e.png">

before using Docker commands.

Since the aspiring interns, who also may have used Docker in this manner before, do not need to do this in the Docker tutorial located at https://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md , perhaps it should be clarified that starting the "GUI" version of Docker before doing anything is not necessary, as the instructions all go through the CLI. 

I was a little confused about my existing installations of VirtualBox and Docker back when I was doing the earlier steps, but through following the directions I realized it was not necessary to start either application manually.

### Steps to reproduce the problem

N/A

### Proposed solution

Adding a clarification to the "Docker Tutorial" page that the actual Docker application, if the aspiring VI already has it, does not need to be started manually as shown in the screenshots above.

Suggestions about how to make this clarification would be appreciated!(Should the same be noted about the VirtualBox GUI???)

**Comment by ChiragAwale** [comment]
@johnmdrake1  You can work on it,

**Comment by lmmrssa** [comment]
@johnmdrake1 We are not using docker on itself. Docker is currently implemented inside vagrant (VirtualBox) That's why you do not need to run docker or install docker on your machine.
This point is already mentioned in https://open-learning-exchange.github.io/#!pages/vi/vi-docker-tutorial.md but if that is not being clear then you can highlight it

**Comment by johnmdrake1** [comment]
> @johnmdrake1 We are not using docker on itself. Docker is currently implemented inside vagrant (VirtualBox) That's why you do not need to run docker or install docker on your machine.
> This point is already mentioned in https://open-learning-exchange.github.io/#!pages/vi/vi-docker-tutorial.md but if that is not being clear then you can highlight it

Is it ok if I still highlight it in that page? I apologize this is late I was out of internet access for several days
