### ISSUE TITLE
Update Planet Home Screen Image

### ISSUE THREAD

**Issue by saraive16** [open-learning-exchange/open-learning-exchange.github.io#2658]
### Problem
The image for planet home screen is no longer up to date in the Planet Tutorial under the Take the Course Step 5. 

### Steps to reproduce the problem
N/A

### Screenshots
Currently the image looks like this
![image](https://user-images.githubusercontent.com/53923848/63397024-fe857c00-c37d-11e9-9c0d-64dbb071e098.png)

but it should look like this
![image](https://user-images.githubusercontent.com/53923848/63396979-d0a03780-c37d-11e9-8e5c-3508880548c2.png)

### Proposed solution
Add an updated image to the page

**Comment by raisinman99** [comment]
Good catch. Do work on this!

**Comment by 007HD** [comment]
@raisinman99 @saraive16 I already pointed out this issue yesterday and working on it https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/2646#issue-482157017.

**Comment by saraive16** [comment]
Duplicate issue. Closing.
