### ISSUE TITLE
Tracking who clones the repository at Github

### ISSUE THREAD

**Issue by Littslynn** [open-learning-exchange/open-learning-exchange.github.io#266]
Assume the repository is private, and then it makes sense that its owner might want to track who has cloned it.

For a purely GitHub based repository, you can look at the network section in order to get an idea of who has forked your repository. Have a look at the network graph for this repository as an example:

https://github.com/cake-build/cake/network

This only gives you the most basic overview of people who have forked your repository, people who have simply cloned the repo locally won't show up on this list.

**Comment by aberdean** [comment]
I think that only the owner of the repository can see that information. 
If you check your own repos, under the Graph tab, you'll see another tab called Traffic, that shows you who cloned your repo. 
When you look at other people's repos, though, you cannot see the Traffic tab.
