### ISSUE TITLE
Add more helpful links to FAQ Page

### ISSUE THREAD

**Issue by saraive16** [open-learning-exchange/open-learning-exchange.github.io#2661]
### Problem
Want to keep all the helpful links in one convenient section. Need to add a Docker and Planet helpful link section to FAQ Page. 

### Steps to reproduce the problem
N/A

### Screenshots

![image](https://user-images.githubusercontent.com/53923848/63399465-7c00ba80-c385-11e9-84ee-27b1fcea66f2.png)

### Proposed solution

Add a Docker section with links to Docker information and add Planet section with helpful links in the FAQ Helpful Links page.

**Comment by 007HD** [comment]
I think, this I a good idea.

**Comment by raisinman99** [comment]
This is helpful. Work on this.
