### ISSUE TITLE
Update OLE Page upload a resource

### ISSUE THREAD

**Issue by saraive16** [open-learning-exchange/open-learning-exchange.github.io#2663]
### Problem
The image on the OLE Page under the How do I upload a Resource? contains an old image that needs to be updated. 

### Steps to reproduce the problem
N/A

### Screenshots

Current image
![image](https://user-images.githubusercontent.com/53923848/63400967-8f625480-c38a-11e9-9de1-90e8bedd5c44.png)

But should be
![image](https://user-images.githubusercontent.com/53923848/63400998-aa34c900-c38a-11e9-9ade-1329ea183bf8.png)

### Proposed solution

Add updated image with numbers that correspond to the appropriate section.

**Comment by Mattmtech** [comment]
good job, that picture is very outdated

**Comment by 007HD** [comment]
I agree the picture is too old. Good catch

**Comment by raisinman99** [comment]
That picture is outdated. Please work on this.
