### ISSUE TITLE
Complete Manage Sync instructions for Step 4 - Planet Tutorial

### ISSUE THREAD

**Issue by 007HD** [open-learning-exchange/open-learning-exchange.github.io#2666]
### Problem
In Step 4 - Planet Tutorial, under **Different Kinds of Updates to Your Community** section, 
4. Finally, send an activities sync to the nation using `Manage Sync`.
Shouldn't we clarify whether to `Run Sync` or not as once the VI is in this step he gets confused whether to click on `Run Sync` or not? At least I was.    

### Steps to reproduce the problem

N/A

### Screenshots

![](https://open-learning-exchange.github.io/pages/vi/images/vi-nation-sync-send.png)

### Proposed solution

Either Delete step 4 as the same step is explained clearly in Step 7 - Nation Planet or 
Mention whether to click on `Run Sync` or not, for clarification.

**Comment by 007HD** [comment]
@raisinman99 @singharpita @lmmrssa Can you please review this issue and comment on it. So that I can start working on it. Thank you!

**Comment by raisinman99** [comment]
You can work on this. You should just mention whether to click run sync or not.

**Comment by 007HD** [comment]
@raisinman99 Ok, thanks! I will go ahead and make this change in the next commit.
 4. Finally, send an activities sync to the nation using `Manage Sync` and then click on `Run Sync` as seen in the screenshot.
![image](https://user-images.githubusercontent.com/36314732/63555966-cc982500-c4f7-11e9-9cab-e86b85d0a170.png)
