### ISSUE TITLE
Include Delete remote Branch tutorial in Step 3 - Markdown and Fork Tutorial 

### ISSUE THREAD

**Issue by 007HD** [open-learning-exchange/open-learning-exchange.github.io#2668]
### Problem
The Virtual Intern, need to be aware of how to delete a branch from a remote repository after the first pull request is merged in Step 3.

### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/36314732/63422332-00236400-c3bf-11e9-95fb-d9003e0c01a5.png)

### Proposed solution

**Delete the branch from your remote repository.**
After your pull request has been approved and merged by OLE staff, you might want to delete the branch that is associated with your pull request. It can keep your remote (yourUserName.github.io on GitHub) repository away from a mess of defunct branches. To delete the defunct branch in your remote repository, you can click the "Delete branch" button in your pull request (see the picture in screenshot).

**Comment by raisinman99** [comment]
This is helpful. You can work on this.

**Comment by 007HD** [comment]
@raisinman99 I will start working on it. Thank you!
