### ISSUE TITLE
Update Planet tutorial dashboard image

### ISSUE THREAD

**Issue by saraive16** [open-learning-exchange/open-learning-exchange.github.io#2673]
### Problem
Out of date image for navigate dashboard image in Open Learning Exchange page.

### Steps to reproduce the problem

N/A

### Screenshots

Current image
![image](https://user-images.githubusercontent.com/53923848/63624043-12b0bf80-c5b0-11e9-8249-5510a3010c25.png)

What image should be
![image](https://user-images.githubusercontent.com/53923848/63623986-f0b73d00-c5af-11e9-9180-634016f00379.png)

**Comment by raisinman99** [comment]
Please work on this.

**Comment by ChiragAwale** [comment]
@saraive16 Please work on it.

**Comment by lmmrssa** [comment]
@saraive16 you have not mentioned which page it is showing but it looks like its from techgenius page. Anyway you can go ahead and change it to new image.
