### ISSUE TITLE
Q13 in FAQ is outdated and inaccurate 

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/open-learning-exchange.github.io#2679]
### Problem
I think Q13 in the [FAQ page](https://github.com/wanglihe2010/wanglihe2010.github.io/blob/issue-2632/pages/vi/vi-faq.md) is for the old version BELL and the address needs to be updated
Q13 is mentioned in the [Planet configuration](https://wanglihe2010.github.io/#!pages/vi/vi-configurations-vagrant.md#Windows)
### Steps to reproduce the problem

visit page https://github.com/wanglihe2010/wanglihe2010.github.io/blob/issue-2632/pages/vi/vi-faq.md

### Screenshots

<img width="953" alt="Screen Shot 2019-08-25 at 2 24 08 AM" src="https://user-images.githubusercontent.com/11765890/63646907-9a491c00-c6df-11e9-8541-359a7370c2b3.png">

### Proposed solution

I do not really know how to solve this solution since it is referred by the issue in Windows platform and I am using Macbook. Below is my proposed solution:
Because a Community is run locally on your machine, you need to `vagrant up prod` in the directory where the Planet is located. You can then see if your Community is running by going to 127.0.0.1:3100 in Firefox.

**Comment by Mattmtech** [comment]
Q13 seems to be outdated, I tried following the instructions in Q13 but they did not work. Definitely needs some updating

**Comment by saraive16** [comment]
I agree definitely needs some updating and conversion from the old BELL version.

**Comment by lmmrssa** [comment]
sure go ahead and change it to reflect Planet

**Comment by nvrqt03** [comment]
I would like to see if I can resolve this.

**Comment by perryc85** [comment]
@nvrqt03 You can work on this.
