### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Ebuka-Chibueze** [open-learning-exchange/open-learning-exchange.github.io#268]
I found a potential issue with the [vagrant.md](http://open-learning-exchange.github.io/#!pages/vagrant.md) page. I think the Windows section should mention editing the `Path` variable in the system variables not `PATH` in user variables.

**Comment by dogi** [comment]
@Ebuka-Chibueze go for it - try doing a "pull request"

**Comment by aberdean** [comment]
No longer relevant with the new simpleinstall.
