### ISSUE TITLE
Changing naming conventions for something a bit more data type friendly.

### ISSUE THREAD

**Issue by dogeTheCoder** [open-learning-exchange/open-learning-exchange.github.io#2683]
### Problem
specific naming conventions for void function and ArrayOfStrings in the main grunt js file for future reference. 

### Steps to reproduce the problem

Change of names

### Proposed solution

change function naming conventions to something a bit more useful for new eyes.

**Comment by dogeTheCoder** [comment]
I'll just ignore the grunt file then. Thanks for the response! @paulbert

**Comment by paulbert** [comment]
Ok closing this issue, then
