### ISSUE TITLE
Adding a Note for Create a Commit and Push the Changes (Step 6 - GitHub Issues Tutorial)

### ISSUE THREAD

**Issue by pattanawadee88** [open-learning-exchange/open-learning-exchange.github.io#2687]
# Problem
Add a Note to tell new interns that " repeat this steps every time after you make a change!! "
It would be useful to tell new interns that they need to follow those steps to be able to see the changes. 

### Steps to reproduce the problem
N/A

### Screenshots
<img width="844" alt="Screen Shot 2019-08-28 at 6 08 22 PM" src="https://user-images.githubusercontent.com/52762574/63896061-ff8e5d00-c9be-11e9-94ce-5fc888556fe5.png">

### Proposed solution
Add a Note

**Comment by lmmrssa** [comment]
NOTE is not required here as this is the general procedure of git. Which means its always needed to be done. So putting note is not required.
