### ISSUE TITLE
Adding description for Exams and Surveys features in Planet User Manual  

### ISSUE THREAD

**Issue by pattanawadee88** [open-learning-exchange/open-learning-exchange.github.io#2688]
### Problem
A description should be added under Exams and Surveys features in Planet User Manual for a reader's understanding 

### Steps to reproduce the problem
N/A

### Screenshots

<img width="1060" alt="Screen Shot 2019-08-28 at 8 07 57 PM" src="https://user-images.githubusercontent.com/52762574/63901571-20f94400-c9d3-11e9-8a2f-be411cdb4bd0.png">

### Proposed solution
Add descriptions

**Comment by lmmrssa** [comment]
sure @pattanawadee88 you can start working on it :) But it will also require related page not just the text on this section.

**Comment by pattanawadee88** [comment]
> sure @pattanawadee88 you can start working on it :) But it will also require related page not just the text on this section.

Yes, I can work on that. But I am not sure what exactly Exam is.
