### ISSUE TITLE
Providing a link of the next step 

### ISSUE THREAD

**Issue by pattanawadee88** [open-learning-exchange/open-learning-exchange.github.io#2689]
### Problem
We should provide a link of the next step at the end of a previous step, so a new intern doesn't need to go back to the First Steps page

### Steps to reproduce the problem
N/A

### Screenshots 
For example: Suppose I finished working on step 3, I can click on a link of the next step.
<img width="1110" alt="Screen Shot 2019-08-28 at 8 53 15 PM" src="https://user-images.githubusercontent.com/52762574/63902156-02487c80-c9d6-11e9-85a2-cb683baf12d5.png">

### Proposed solution
Providing a link of the next step

**Comment by lmmrssa** [comment]
@pattanawadee88 Return to First Steps is already taking you to different page for further steps.
