### ISSUE TITLE
Update images on Markdown tutorial

### ISSUE THREAD

**Issue by pattanawadee88** [open-learning-exchange/open-learning-exchange.github.io#2691]
### Problem
Images are not shown.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="1228" alt="Screen Shot 2019-08-29 at 12 31 21 PM" src="https://user-images.githubusercontent.com/52762574/63958930-1a151480-ca59-11e9-8ac1-f67a39fe647e.png">

### Proposed solution
Update images

**Comment by ChiragAwale** [comment]
@pattanawadee88 Please write down steps to reproduce problem, as to the link to this page and such

**Comment by pattanawadee88** [comment]
Here is the link to the page: https://tylingsoft.github.io/tutorial.md/#whats-markdown

**Comment by pattanawadee88** [comment]
> @pattanawadee88 Please write down steps to reproduce problem, as to the link to this page and such

I couldn't find the Markdown tutorial code. I think because the code is in repository tylingsoft.github.io.

**Comment by lmmrssa** [comment]
@pattanawadee88 this link is not related to open-learning-exchange.github.io And as it is different repository we should not be trying to fix it
