### ISSUE TITLE
Update Planet dashboard image in Admin User Manual 

### ISSUE THREAD

**Issue by pattanawadee88** [open-learning-exchange/open-learning-exchange.github.io#2693]
### Problem
Outdated Planet dashboard images

### Steps to reproduce the problem
N/A

### Screenshots

<img width="1239" alt="Screen Shot 2019-08-29 at 1 28 22 PM" src="https://user-images.githubusercontent.com/52762574/63967359-43d73700-ca6b-11e9-9b24-7496dd18bfd4.png">
<img width="868" alt="Screen Shot 2019-08-29 at 1 28 55 PM" src="https://user-images.githubusercontent.com/52762574/63967386-4fc2f900-ca6b-11e9-8efe-d908bb8f19be.png">
<img width="833" alt="Screen Shot 2019-08-29 at 1 32 35 PM" src="https://user-images.githubusercontent.com/52762574/63967387-4fc2f900-ca6b-11e9-84c7-f76c75eafc68.png">

Planet dashboard images need to change
Language Overview

<img width="1189" alt="Screen Shot 2019-08-29 at 2 44 53 PM" src="https://user-images.githubusercontent.com/52762574/63967602-c4963300-ca6b-11e9-9e7b-31ac0cfca464.png">

Calendar Overview and Email Overview

There are no Calendar and Email in the latest version of Planet

<img width="1194" alt="Screen Shot 2019-08-29 at 2 49 15 PM" src="https://user-images.githubusercontent.com/52762574/63967870-5140f100-ca6c-11e9-83fc-36fed457aeff.png">

### Proposed solution
Update Planet dashboard images

**Comment by ChiragAwale** [comment]
@pattanawadee88 Do work on it
