### ISSUE TITLE
Outdated image on Planet tutorial

### ISSUE THREAD

**Issue by smitshrestha101** [open-learning-exchange/open-learning-exchange.github.io#2696]
### Problem
The image on Preparation tab of Step 4: Planet Tutorial is outdated

### Steps to reproduce the problem
Go to link (https://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md) and pres son Preparation tab on the left or scroll down to Preparation tab.

### Screenshots
The image on the page:
![Screenshot (27)](https://user-images.githubusercontent.com/24301429/64079017-b896b500-cca7-11e9-82a9-018fcde9d628.png)

The real image on Planet Learning:
![Screenshot (28)](https://user-images.githubusercontent.com/24301429/64079020-c9dfc180-cca7-11e9-8fb9-33006e3df472.png)

### Proposed solution
Change the image to a latest screenshot of Planet Learning page.

**Comment by ChiragAwale** [comment]
You can work on it
