### ISSUE TITLE
Update myPlanet User Manual in Admin User Manual

### ISSUE THREAD

**Issue by pattanawadee88** [open-learning-exchange/open-learning-exchange.github.io#2700]
# Problem
There is no content in myPlanet User Manual.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="1280" alt="myPlanet-user" src="https://user-images.githubusercontent.com/52762574/64086848-80738e80-cd08-11e9-9985-9dc48450f92d.png">

### Proposed solution
Delete myPlanet User Manual menu or Adding some content

**Comment by ChiragAwale** [comment]
You could just add something saying yet to be updated or something like that
