### ISSUE TITLE
Update the step to subscribe to OLE events in Google Calendar 

### ISSUE THREAD

**Issue by 007HD** [open-learning-exchange/open-learning-exchange.github.io#2701]
### Problem
In [Virtual Intern Orientation](https://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md) page, update the way of adding OLE calendar to your Google calendar. 

Under Weekly Calendar section one of the bullet points is as follows:
- In Google Calendar, paste ole.org_u2koassrool56icb7fqko9abac@group.calendar.google.com into "Add a friend's calendar" and hit Enter (do not click the + sign).
There is no **Add a friend's calendar** option in the Google Calendar. Maybe this was an older way. The new way to subscribe to OLE events calendar is in the solution 
### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/36314732/64090946-ad24a780-cd02-11e9-9751-52727483c162.png)

![image](https://user-images.githubusercontent.com/36314732/64090949-b44bb580-cd02-11e9-86c1-11d7bd1a2291.png)

### Proposed solution

- In Google Calendar, click on the **+** sign next to the **Other calendars** section on the left side as seen in the screenshot 1. Select **Subscribe to calendar** from the dropdown
-  Paste `ole.org_u2koassrool56icb7fqko9abac@group.calendar.google.com` under "Add calendar" and hit `Enter` as seen in the screenshot 2

**Comment by lmmrssa** [comment]
you can work on this

**Comment by 007HD** [comment]
@lmmrssa All right! I will start working on it. Thank you!
