### ISSUE TITLE
Fix the redundancy on "git repositories" page

### ISSUE THREAD

**Issue by smitshrestha101** [open-learning-exchange/open-learning-exchange.github.io#2706]
### Problem
There is an extra redundant "on" in one of the lines in "git repositories" tutorial page.

### Steps to reproduce the problem
Go to link (https://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md) and on the tab "Start here", go to "Explanation about Repositories and Syncing Process" and the line will be 2 paragraphs below the picture on the second line of the paragraph.

### Screenshots

![Screenshot (30)](https://user-images.githubusercontent.com/24301429/64278196-cb142700-cf11-11e9-8d02-8fea6b852086.png)

### Proposed solution

Remove "on" from the line infront of Github.

**Comment by ChiragAwale** [comment]
Go ahead on the fix, also try looking for grammatical errors on the same page, so you can do it in one go.
