### ISSUE TITLE
Missing articles and redundancy on Nation Planet page

### ISSUE THREAD

**Issue by smitshrestha101** [open-learning-exchange/open-learning-exchange.github.io#2711]
### Problem
There should be a 'an' preceding Administrator and a 'a' preceding whole. Also, the phrase 'a number of' can be changed to a shorter word for conciseness.

### Steps to reproduce the problem

Go to Step 7: Nation Planet tab and before the title "Check Sync Status", the paragraph with the missing articles is situated.

### Screenshots

![Screenshot (31)](https://user-images.githubusercontent.com/24301429/64389510-a5b61480-d008-11e9-9137-82b9c302aa02.png)

### Proposed solution

Add 'an' before Administrator, a before whole and change 'a number of ' to several.

**Comment by ChiragAwale** [comment]
Go ahead with the fix
