### ISSUE TITLE
Page titles in browser tab

### ISSUE THREAD

**Issue by aberdean** [open-learning-exchange/open-learning-exchange.github.io#272]
When keeping several browser tabs open, having the same title in every tab is a bit confusing.
It would be better if each browser tab would reflect the actual title of the page it refers to.

**Comment by aberdean** [comment]
This clearly is a problem with MDwiki, not with our steps, but I was just wondering if we could fix it on our version.

It has been tagged as enhancement in 2014 in MDwiki repository, but doesn't seem to have received much love: [See MDwiki Repo](https://github.com/Dynalon/mdwiki/issues/145)

Digging into the code, it seems that perhaps a modification to this portion of the code could do the trick:

`function(a) {
        function b() {
            var b;
            if (a.md.config.title && a("title").text(a.md.config.title), b = a("#md-content h1").eq(0), a.trim(b.toptext()).length > 0) {
                a("#md-title").prepend(b); {
                    b.toptext()
                }
            } else a("#md-title").remove()
        }`

**Comment by dogi** [comment]
@aberdean I very like this ... go on try it out
if you think you have a good solution create a "pull request"

**Comment by hikaruit15** [comment]
Could we set title like this?
``` javascript
function b() {
            var b;
            if (a.md.config.title && a("title").text(a.md.config.title), b = a("#md-content h1").eq(0), a.trim(b.toptext()).length > 0) {
                a("title").(b.text());
                a("#md-title").prepend(b); {
                    b.toptext()
                }
            } else a("#md-title").remove()
        }
```

**Comment by aberdean** [comment]
@hikaruit15 did you test it?

**Comment by hikaruit15** [comment]
@aberdean I tested it with my repo. It will work on page that have [the right format](http://dynalon.github.io/mdwiki/#!layout.md). 
> All pages should start with a 1st heading, which is turned into the page title. To devide the page into sections, use 2nd degree headings.
However, I saw some of pages doesn't meet that.

**Comment by aberdean** [comment]
@hikaruit15 That is totally awesome! I so much liked to see this happening!

If you like, you can go ahead and add/change the missing or incorrectly formatted titles into 1st headings.
Also, we should add a note to the README.md page, so that when we update the MDWiki, we know what to modify again (basically, the line of code you posted above).
Then, you can do a pull request. I would really love to see that!
