### ISSUE TITLE
Potential fix for clicking Logo on navbar

### ISSUE THREAD

**Issue by Justin-Singh125125** [open-learning-exchange/open-learning-exchange.github.io#2730]
###Problem
On logo click, redirect to broken page

### Steps to reproduce the problem

anywhere on site, click the logo

### Screenshots
<img width="164" alt="Screen Shot 2019-09-12 at 7 12 33 PM" src="https://user-images.githubusercontent.com/41179777/64833076-5c7a3d80-d591-11e9-8689-b9c5d714cbe0.png">
<img width="1046" alt="Screen Shot 2019-09-12 at 7 12 50 PM" src="https://user-images.githubusercontent.com/41179777/64833079-5f752e00-d591-11e9-81de-b83d7f8746f6.png">

### Proposed solution
I think when this button is clicked, it should be redirected to the index page, or http://ole.org/. I am not sure but I can fix this if you want!

**Comment by ChiragAwale** [comment]
It is working fine in mine though.
