### ISSUE TITLE
Remove outline on navbar brand

### ISSUE THREAD

**Issue by Justin-Singh125125** [open-learning-exchange/open-learning-exchange.github.io#2731]
### Problem
When you click on the navbar brand titled "OLE Support", there is an outline of the element that appears. Clicking on any of the other elements on the navbar do not have this issue.

### Steps to reproduce the problem
On any page, click the navbar brand that is titled "OLE Support". You will then see an outline of the element.

### Screenshots
<img width="187" alt="Screen Shot 2019-09-16 at 12 49 19 PM" src="https://user-images.githubusercontent.com/41179777/64988713-f2a7af80-d880-11e9-9169-3c4b6c076776.png">

### Proposed solution
I can remove the outline off that element. I know this is a small fix however none of the other elements on the navbar have a visible outline when clicked. I feel this fix can help with consistency.

**Comment by ChiragAwale** [comment]
@Justin-Singh125125 Could you post a picture with the outline.

**Comment by Justin-Singh125125** [comment]
> @Justin-Singh125125 Could you post a picture with the outline.

If you click on the picture and look closely, you will see a faint black outline. It is kind of hard to see.

**Comment by lmmrssa** [comment]
@Justin-Singh125125 let not focus on all minute details of design. We are not trying to make a best promotional site here :) We are trying to have people get started with technology required to work with us.
