### ISSUE TITLE
Planet tutuorial - virtual intern quiz

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/open-learning-exchange.github.io#2738]
### Problem

Answers do not appear to be saved once answered. When you go back to revisit a question, your previous answer is not populated.  It is unclear if the quiz keeps your answers, or resets the answer if you revisit the question. 

### Steps to reproduce the problem  

- for virtual intern quiz - go to planet learning homepage 
- select my submissions at bottom of page  
- click on the title of the question. the selected question will pop up, however there will be no answer selected. 

 
### Screenshots

![planet tutorial homepage](https://user-images.githubusercontent.com/22177989/65897561-269ccd80-e375-11e9-8211-1ff624c15e46.png)  

![planet tutorial submissions](https://user-images.githubusercontent.com/22177989/65897571-2ef50880-e375-11e9-9488-1893a1ec26ff.png)  

![planet tutorial - blank answer](https://user-images.githubusercontent.com/22177989/65897579-35838000-e375-11e9-9a2c-44eec152294b.png)
  
### Proposed solution
 - Unsure how to solve this issue.

**Comment by Liew211** [comment]
@nvrqt03  for the issues during these first steps, please keep them to issues within the steps themselves 😃 you can file and work on planet issues on [open-learning-exchange/planet](https://github.com/open-learning-exchange/planet) once you're part of the team.
