### ISSUE TITLE
Searchbar Placeholder

### ISSUE THREAD

**Issue by choiwhmarco** [open-learning-exchange/open-learning-exchange.github.io#2739]
### Problem
On Teams, Surveys, Meetups page, the search bar placeholder text is still English after I selected a different language.

### Steps to reproduce the problem
* Select a language that is not English on top right next to the icon.
* Click Teams or Surveys or Meetups tabs on top.
* The  search bar placeholder text is English.

### Screenshots

![Capture](https://user-images.githubusercontent.com/22423089/65920064-dd5b7680-e392-11e9-82b4-33896fae7bf2.PNG)
![111](https://user-images.githubusercontent.com/22423089/65920067-dfbdd080-e392-11e9-99c8-76eb305fbb47.PNG)
![222](https://user-images.githubusercontent.com/22423089/65920071-e2202a80-e392-11e9-978f-b542b443439d.PNG)

### Proposed solution

N/A

**Comment by Liew211** [comment]
@choiwhmarco for the issues during these first steps, please keep them to issues within the steps themselves 😃 you can file and work on planet issues on [open-learning-exchange/planet](https://github.com/open-learning-exchange/planet) once you're part of the team.
