### ISSUE TITLE
OLE Homepage - How to navigate the dashboard - confusing

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/open-learning-exchange.github.io#2740]
### Problem
The navigation picture has items numbered and explanations for each number describing the widgets on the dashboard. This may be an old picture, and is also numbered in a confusing way. 1 - 9 are down the side, 10 is near the top but skips to 12.  

### Steps to reproduce the problem  

* Visit [OLE](https://open-learning-exchange.github.io/#!./pages/techgenius/tg-planet-user-manual.md)  
* scroll down to **How do I Navigate and Use Planet**? 

### Screenshots

![ole-dashboard](https://user-images.githubusercontent.com/22177989/65925327-fc1f3480-e3b5-11e9-94a2-66857b918543.png)

![ole-dashboard-numbers](https://user-images.githubusercontent.com/22177989/65925409-659f4300-e3b6-11e9-87a0-a43cade6bdc7.png)

### **Below is my current dashboard.**

![myoledashboard](https://user-images.githubusercontent.com/22177989/65925359-21ac3e00-e3b6-11e9-88b9-633a4de20276.png)

### Proposed solution
* if necessary, update with new screenshot of OLE dashboard
* re-number screenshot accordingly - number in an order that is easier to read.

**Comment by perryc85** [comment]
Good catch. You can work on this.
