### ISSUE TITLE
First Steps - The Big Picture - JavaScript/CLI links update

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/open-learning-exchange.github.io#2744]
### Problem

* The JavaScript and command line interface links are to wikipedia pages. This is ok, but I think a better option might be to use more informative links such as MDN and W3 schools. 

### Steps to reproduce the problem

* First steps home page, under the first heading [The Big Picture](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) 

### Screenshots

![First steps homepage](https://user-images.githubusercontent.com/22177989/66063084-47495c80-e508-11e9-8956-9569886c7b8a.png)

### Proposed solution
* Update the JavaScript link to [MDN](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)  
* Update the CLI link to [w3schools](https://www.w3schools.com/whatis/whatis_cli.asp)

**Comment by perryc85** [comment]
You can work on this.
