### ISSUE TITLE
Clarifying raw.githack - Markdown presentation mode

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/open-learning-exchange.github.io#2745]
### Problem

* Step 5 of the Raw.githack could use some clarity. After reading the step, it would be good to see an example of  where exactly to put the #!. 

### Steps to reproduce the problem

* In the Github Issues section, scroll down to Create a Commit and Push the Changes/Raw.githack [here](https://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md) 

### Screenshots

![github issues raw githack](https://user-images.githubusercontent.com/22177989/66081828-770b5b00-e52e-11e9-9218-6727a2d0c4fe.png)

### Proposed solution

* Add the following code snippet and image as an example of how to get the markdown in presentation  mode. 
https://raw.githack.com/YourUsername/YourUsername.github.io/yourBranchName/#!pages/folder/folderName.md

![insert here](https://user-images.githubusercontent.com/22177989/66082069-f6009380-e52e-11e9-999e-6510a7fcaea0.png)

**Comment by garret123h** [comment]
I think that would be a good change because I was recently doing that page myself and also found that part a bit confusing. Having a clear example would help.

**Comment by perryc85** [comment]
You can work on this.
