### ISSUE TITLE
Virtual Intern tutorial steps. The arrow at the bottom of the page that points to the next step could be a link that navigates you to the next step

### ISSUE THREAD

**Issue by garret123h** [open-learning-exchange/open-learning-exchange.github.io#2747]
### Problem
When I was doing the step by step instructions, I would get to the bottom of the page and expect to be able to click on a link or button to the next step but I had to go back up and find the next step. 

### Steps to reproduce the problem

Go to each step after step one and scroll to bottom 

### Screenshots

<img width="906" alt="Screen Shot 2019-10-02 at 10 32 00 PM" src="https://user-images.githubusercontent.com/41763904/66101649-7b526b00-e564-11e9-904e-d195a054b924.png">

### Proposed solution

Either make a HTML arrow/image that can take you to the next step or make the "Step #" be a link to the next step.

**Comment by ChiragAwale** [comment]
You can work on it

**Comment by sjkadali** [comment]
This change will be helpful in navigating to the next step directly, instead of going back and finding the next step.

**Comment by sauravghosal** [comment]
I ran into this issue as well! I think that adding a arrow link feature would be helpful in maintaining a sense of flow between the tutorial steps.
