### ISSUE TITLE
Raw.githack clarification 

### ISSUE THREAD

**Issue by garret123h** [open-learning-exchange/open-learning-exchange.github.io#2752]
### Problem
When I was trying to view the raw.githack markdown files I had trouble generating the URL when having to change the path to where the file was located. The section addresses that part " You may need to change the link slightly depending on where the file you want to view is located" But after some testing I found out how to correctly put the path in. I think a simple example of where to put the path could help future interns view there files. 

### Steps to reproduce the problem

Under virtual interns, step 6 under Raw.githack section.

### Screenshots

![image](https://user-images.githubusercontent.com/41763904/66250169-8ab3ee80-e6f3-11e9-9d76-7124c0890368.png)

### Proposed solution

Show an example URL where the user can tell where to put the path in.

**Comment by perryc85** [comment]
You can work on this.
