### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by garret123h** [open-learning-exchange/open-learning-exchange.github.io#2754]
### Problem
On the Github and Markdown tutorial page I think including a link to a markdown editor would be useful for new interns learning markdown. They have an easy to use editor online called markdownlivepreview.com.The link could be in the "Useful Links" area. 

### Steps to reproduce the problem

Go to step three and scroll all the way to the bottom of the page

### Screenshots

![image](https://user-images.githubusercontent.com/41763904/66265206-4134d380-e7c7-11e9-8829-36142e904292.png)

### Proposed solution

Add a link in "Useful Links" to the Editor.

**Comment by perryc85** [comment]
You can work on this.
