### ISSUE TITLE
Vi/VIM helpful link

### ISSUE THREAD

**Issue by garret123h** [open-learning-exchange/open-learning-exchange.github.io#2757]
### Problem
I believe it can be difficult for a new intern to struggle with using VIM. One helpful website that helped me was a VIM adventures game where it teaches you the basics of VIM commands. It is very beginner friendly.

### Steps to reproduce the problem

In the FAQ page under helpful links you can find Vi/VIM category. 

### Screenshots

![image](https://user-images.githubusercontent.com/41763904/66275268-bb9f3b00-e83b-11e9-954d-65c5c7c26bae.png)

### Proposed solution

Add a link to the game so if future interns need to get familiar with VIM they can try using this tool.

**Comment by perryc85** [comment]
You can work on this.
