### ISSUE TITLE
Useful links for JavaScript, HTML5, CouchDB, Angular, Node.js on faq page

### ISSUE THREAD

**Issue by choiwhmarco** [open-learning-exchange/open-learning-exchange.github.io#2760]
### Problem
There is no link to JavaScript, HTML5, CouchDB, Angular, Node.js, and Terminal for helpful links on the FAQ page. Since there are some links for Vagrant, VirtualBox, and Git.

### Steps to reproduce the problem
Scroll down to the bottom on FAQ page.

### Screenshots
![Capture](https://user-images.githubusercontent.com/22423089/66347974-55351e00-e90a-11e9-961c-2318d29e2b29.PNG)

### Proposed solution

Add links for [JavaScript](https://www.w3schools.com/js/default.asp), [HTML5](https://www.w3schools.com/html/html5_intro.asp), [CouchDB](https://www.tutorialspoint.com/couchdb/index.htm), [Angular](https://angular.io/tutorial), [Node.js](https://www.tutorialspoint.com/nodejs/index.htm)

**Comment by paulbert** [comment]
No need for Node.js, and I would add:

- [CouchDB official](http://docs.couchdb.org/en/stable/intro/why.html)
- [TypeScript](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)
- [RxJS](https://angular.io/guide/rx-library)

This looks good to work on, thanks!

**Comment by sjkadali** [comment]
Links would be helpful for quick reference to beginner virtual interns.
