### ISSUE TITLE
Adding anchor for helpful links on FAQ Page

### ISSUE THREAD

**Issue by choiwhmarco** [open-learning-exchange/open-learning-exchange.github.io#2766]
### Problem
There are anchors for questions on FAQ page, so I would want to update it with adding anchors for helpful links and helpful videos.

### Steps to reproduce the problem
Scroll down to the bottom on FAQ page.

### Screenshots
![Capture](https://user-images.githubusercontent.com/22423089/66440105-b8947e00-e9e6-11e9-8197-8f7a0664eb2f.PNG)
![21](https://user-images.githubusercontent.com/22423089/66440106-bb8f6e80-e9e6-11e9-8776-f8f225447574.PNG)

### Proposed solution
adding anchors for helpful links and helpful videos at the top of FAQ page.

**Comment by anikx7** [comment]
This is an excellent idea. I believe we can add two anchors just after Technical Questions.

**Comment by paulbert** [comment]
@choiwhmarco There are links to those sections already in the side navigation, so I'm not sure what you are proposing to add.

![image](https://user-images.githubusercontent.com/9203229/66537838-f7fac180-eaef-11e9-89d8-de95ee1182d3.png)

**Comment by choiwhmarco** [comment]
I meant adding things like Angular, HTML. Making a list for helpful links like those questions
