### ISSUE TITLE
Missing an article on Step 5 - Git Repository

### ISSUE THREAD

**Issue by anikx7** [open-learning-exchange/open-learning-exchange.github.io#2768]
# # Problem
There is an article missing in this sentence: "Below is an example of git diff command showing difference in the file of local and remote repository."

### Steps to reproduce the problem
Go to the first steps page (I used Mozilla firefox), Scroll down to step 65, and click the Git Repository.

### Screenshots
![1](https://user-images.githubusercontent.com/26880012/66511862-6498a080-ea9d-11e9-8e35-1580d5abfd50.JPG)

### Proposed solution
I think we can add an article just before the difference.
"Below is an example of git diff command showing the/a difference in the file of local and remote repository."

**Comment by paulbert** [comment]
My suggestion for an improvement would be:
> Below is an example of **the** git diff command showing **the** difference...

This is good to work on.
