### ISSUE TITLE
Adding basic command line commands list in the FAQ/Helpful Links

### ISSUE THREAD

**Issue by anikx7** [open-learning-exchange/open-learning-exchange.github.io#2769]
### Problem
To complete 10 steps and virtual internship,  learners need a good understanding of command-line commands. For example, how to change directory, who create a new folder using command line commands. For this reason, I think we can add a link for the basic command list and their meaning.
### Steps to reproduce the problem
Go to the first steps page (I used Mozilla firefox), and click on the FAQ page. Then scroll down to the Helpful Links or click on the left sidebar Helpful links.

### Screenshots
![2](https://user-images.githubusercontent.com/26880012/66520140-37a0b980-eaae-11e9-8558-4b4f404bed03.JPG)

### Proposed solution
I think we can add a section named Command line commands at the beginning of the Helpful Links and attached following link: https://www.codecademy.com/articles/command-line-commands

**Comment by paulbert** [comment]
Ok this looks good to work on.

**Comment by choiwhmarco** [comment]
I think the link is already attached on first step page already.
