### ISSUE TITLE
Adding a local environment to the gitandrepositories.md page

### ISSUE THREAD

**Issue by aberdean** [open-learning-exchange/open-learning-exchange.github.io#277]
Since we're starting to work from the command line, it would be useful to add a local environment to be able to check the modifications locally.

I use [Node.js](https://nodejs.org/en/) and [Browsersync](https://www.browsersync.io/).
It works on Windows, Mac, and Linux, and Browsersync can be used also with any other local server.

**Comment by dogi** [comment]
@aberdean good idea but think https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/458 is better ;)
