### ISSUE TITLE
Adding Tracking Progress link on the FAQ page

### ISSUE THREAD

**Issue by anikx7** [open-learning-exchange/open-learning-exchange.github.io#2770]
### Problem
I think we can add the following question in the FAQ/General Questions section:
"Q10. How can I keep track of 10 step vetting progress?"
 At the time of completing the 10 steps process, I couldn't found a link to keep track of my progress. I found the Tracking Progress link when I was at step 8.

### Steps to reproduce the problem
Go to the first steps page (I used Mozilla firefox), and click on the FAQ page.

### Screenshots
![3](https://user-images.githubusercontent.com/26880012/66523062-99fcb880-eab4-11e9-9796-fb0213a4bb8f.JPG)

### Proposed solution
We provide the Tracking Progress link:
https://open-learning-exchange.github.io/#!./pages/vi/vi-track-progress.md

**Comment by paulbert** [comment]
This is ok to work on

**Comment by sjkadali** [comment]
Adding the link to the FAQ page would be helpful to the interns if they need to track the progress.
