### ISSUE TITLE
Adding hyphen and "yourself" on the Step 6 - Github issues page

### ISSUE THREAD

**Issue by anikx7** [open-learning-exchange/open-learning-exchange.github.io#2771]
### Problem
At the bottom of Step 6 - Github Issues page, there is hyphen missing between the word open and source. Another suggestion would be adding "yourself" in the following sentence.
"This is an exercise to help you familiarize "yourself" with GitHub issues, committing, and creating pull requests." 
### Steps to reproduce the problem
Go to the first steps page (I used Mozilla firefox), and click on Step 6 - Github Issues page. Then scroll down the bottom of the page. 

### Screenshots
![4](https://user-images.githubusercontent.com/26880012/66523946-b26dd280-eab6-11e9-9e34-00dd2f5f0151.JPG)

### Proposed solution
We can add "yourself" and hyphen.

**Comment by paulbert** [comment]
Open source is more commonly used without a hyphen, so let's not change that.

We can add "yourself" to the sentence referenced above.
