### ISSUE TITLE
Non-functional links on Courses page of Planet User Manual

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/open-learning-exchange.github.io#2778]
### Problem
The links under Topics on Courses page are non-functional.

### Steps to reproduce the problem

Go to Planet User Manual page. Click on Courses and go to the Courses page.  The links list under Topics are non-functional.

### Screenshots

![Screenshot from 2019-10-10 15-58-01](https://user-images.githubusercontent.com/39105848/66603209-adbe2280-eb79-11e9-9d56-8dafd3cee284.png)

### Proposed solution

These links are redundant , so the Topics list with links can be removed.

**Comment by anikx7** [comment]
Yes, all 7 links are not functioning.

**Comment by lmmrssa** [comment]
@sjkadali you can work on this
