### ISSUE TITLE
Non-functional links on Teams page of Planet User Manual

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/open-learning-exchange.github.io#2779]
### Problem
The links under Topics on Teams page are non-functional.
### Steps to reproduce the problem

Go to Planet User Manual. Click on Teams and go to the Teams page.  click on links under Topics.

### Screenshots

![Screenshot from 2019-10-10 16-30-45](https://user-images.githubusercontent.com/39105848/66604105-7badc000-eb7b-11e9-972d-e1fe29e61471.png)

### Proposed solution

Since the links are redundant and non-functional, can be removed.

**Comment by anikx7** [comment]
Suggestion,
we can make those links functional. I think to make those functional you just need to change hyphen("-") to underscore ("_")
![6](https://user-images.githubusercontent.com/26880012/66706972-97da6a00-ecff-11e9-96f8-3f77589c74ec.JPG)

**Comment by lmmrssa** [comment]
@sjkadali you can work on this
