### ISSUE TITLE
Non-functional links on Meetups page of Planet User Manual

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/open-learning-exchange.github.io#2780]
### Problem
The links on Meetups page of Planet User Manual are non-functional.

### Steps to reproduce the problem

Go to Planet User Manual. Click on Meetups and go to the Meetups page. Click on the links under Topics.

### Screenshots

![Screenshot from 2019-10-10 16-31-06](https://user-images.githubusercontent.com/39105848/66604431-33db6880-eb7c-11e9-8e9a-6d51262716fc.png)

### Proposed solution

Since the links are non-functional and redundant can be removed.

**Comment by anikx7** [comment]
Suggestion:
you can make this link functional. I think to make those functional you just need to change hyphen("-") to underscore ("_").
![6](https://user-images.githubusercontent.com/26880012/66707010-11725800-ed00-11e9-81c7-6a50c9eaba3a.JPG)

**Comment by sjkadali** [comment]
@anikx7 thanks for the suggestion.  But the pages would have a consistent
look without the links listed as topics at the top.
