### ISSUE TITLE
Data not updated under Tech Geniuses/members

### ISSUE THREAD

**Issue by gyawaliamit7** [open-learning-exchange/open-learning-exchange.github.io#2801]
### Problem
> Under the menu tech Geniuses /members, there are two subheaders for tech geniuses and active tech geniuses. Both the subheader data look like they are not being updated.

### Steps to reproduce the problem
>NA

### Screenshots
<img width="1290" alt="Screen Shot 2019-10-23 at 7 01 39 AM" src="https://user-images.githubusercontent.com/34220616/67391049-71b89380-f563-11e9-9428-3a302454b1c5.png">
<img width="1235" alt="Screen Shot 2019-10-23 at 7 01 48 AM" src="https://user-images.githubusercontent.com/34220616/67391069-78dfa180-f563-11e9-825a-80aca26547a1.png">

### Proposed solution
> Update the data.

**Comment by Sachit1137** [comment]
@gyawaliamit7 I agree. This data should be updated regularly to provide information about past and current tech geniuses.
