### ISSUE TITLE
"The Big Picture" section 'Markdown' link

### ISSUE THREAD

**Issue by jholtkort** [open-learning-exchange/open-learning-exchange.github.io#2803]
### Problem
The link labeled markdown goes to the syntax tab of Darling Fireball instead of the main tab, which is inconsistent with the other links in this section that just go to that concept's/ technology's home page.  This could be confusing to someone not familiar to markdown.

### Steps to reproduce the problem

Click on the 'Markdown' link in 'The Big Picture' section of vi-first-steps.md.

### Screenshots

N/A

### Proposed solution

Either change the link to the home page tab, or link to the Markdown Wikipedia page (found on vi-github-and-markdown.md in the 'Preparation' section)

**Comment by SAI-JAHNAVI** [comment]
@jholtkort  the issue is trivial and a good catch, though!
