### ISSUE TITLE
Insufficient Information under vi/step7

### ISSUE THREAD

**Issue by gyawaliamit7** [open-learning-exchange/open-learning-exchange.github.io#2808]
### Problem

On the notes section where they ask to create a dummy section. The information was not clear enough to approach the solution. There were some errors while following the instructions.

### Steps to reproduce the problem
NA

### Screenshots
<img width="775" alt="Screen Shot 2019-10-24 at 2 39 34 AM" src="https://user-images.githubusercontent.com/34220616/67463715-90706600-f607-11e9-8e25-7cb0cb1f6fe8.png">
<img width="348" alt="Screen Shot 2019-10-24 at 2 40 44 AM" src="https://user-images.githubusercontent.com/34220616/67463829-c31a5e80-f607-11e9-97ee-7d06854b4caa.png">
<img width="597" alt="Screen Shot 2019-10-24 at 2 41 03 AM" src="https://user-images.githubusercontent.com/34220616/67463834-c57cb880-f607-11e9-8940-8fadaafa5784.png">

### Proposed solution
Remodify the instructions and use more screenshots.

**Comment by Sachit1137** [comment]
I am also experiencing this issue.
