### ISSUE TITLE
Clearing Up When to Send Survey Request in Step 7

### ISSUE THREAD

**Issue by TheShed412** [open-learning-exchange/open-learning-exchange.github.io#281]
I was a little confused while reading through nations.md and I thought I could request the Survey on gitter after the 7th step and then just filled it out after the 8th step. I just want to make the wording more clear that you request and fill out the survey after the 8th step.

**Comment by dogi** [comment]
@TheShed412 :)

like I explained in the chat think you are mostly confused cause you jumped steps ...
since I assume this your first issue of step 5 you are not totally offroad, but without more concrete explainations I don't how this issuewill ever make into a "pull request"
