### ISSUE TITLE
Track Progress UI

### ISSUE THREAD

**Issue by gyawaliamit7** [open-learning-exchange/open-learning-exchange.github.io#2814]
# Problem
The UI of track progress can be worked to make them more user-friendly.

### Steps to reproduce the problem
N/A

### Screenshots
<img width="1075" alt="Screen Shot 2019-10-26 at 4 39 27 AM" src="https://user-images.githubusercontent.com/34220616/67617639-beda7680-f7aa-11e9-8669-15fe3d13eea3.png">

### Proposed solution

Add input box to get username .

**Comment by Sachit1137** [comment]
Instead of taking input in the popup box, we can create an input box on the web page. That will be more user friendly.
