### ISSUE TITLE
Add information about BeLL in Step 6

### ISSUE THREAD

**Issue by SAI-JAHNAVI** [open-learning-exchange/open-learning-exchange.github.io#2817]
### Problem
No information is provided about BeLL in first steps. So when it is mentioned in Step 6, users will get confused( I got confused and read the whole document again to see if I missed any info. about BeLL but I could not find any. I searched for it on internet and found http://bell.macwill.in/ as relavent)

### Steps to reproduce the problem

Under first steps open Step 6 GitHub Issues

### Screenshots

![Screenshot (89)_LI](https://user-images.githubusercontent.com/51455166/67701369-cbfb8f00-f97d-11e9-905f-93b92c9fe08b.jpg)

### Proposed solution

Providing overview about BeLL by adding a link in Step 6. Please check http://bell.macwill.in/ this link. If you find it relevant I will add this or if it is not related provide me with the correct information. I will add it there. I think this will be helpful for interns

**Comment by robinGiri** [comment]
I think BeLL should not be written anywhere since its the old name of planet .

**Comment by SAI-JAHNAVI** [comment]
@robinGiri please check #2823. This issue is already addressed there.
