### ISSUE TITLE
The position of Planet User Guideline step 0

### ISSUE THREAD

**Issue by gyawaliamit7** [open-learning-exchange/open-learning-exchange.github.io#2824]
The
### Problem
It will be good if the note of Planet Guideline could be placed just below step 1 so the user will read it with more importance.

### Screenshots
<img width="924" alt="Screen Shot 2019-10-29 at 6 05 45 PM" src="https://user-images.githubusercontent.com/34220616/67816097-e1081900-fa76-11e9-843c-14777226aff8.png">

### Proposed solution
Move the note down under step 1.

**Comment by Sachit1137** [comment]
@gyawaliamit7 can you please remove unnecessary words from the issue description ("The" at the top) and please write N/A where ever not applicable like in "Steps to produce".
