### ISSUE TITLE
GitHub Issues Page: planet or community should be written instead of BeLL 

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/open-learning-exchange.github.io#2835]
### Problem
* Go to step 6 on GitHub issue page
* On line number 2 of Introduction BeLL is written

### Screenshots
![bell](https://user-images.githubusercontent.com/45058288/68384523-e3a5f500-017f-11ea-89f1-a325bf91f6a4.PNG)

### Proposed solution
Rename BeLL with Planet/Community

**Comment by anishregmee** [comment]
ok @robinGiri work on it.

**Comment by SAI-JAHNAVI** [comment]
@anishregmee  @robinGiri Please check #2823 BeLL is already changed to Planet

**Comment by perryc85** [comment]
@robinGiri - Looks like this issue was addressed.
