### ISSUE TITLE
Recommend IDE or text editor 

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/open-learning-exchange.github.io#2836]
### Problem
* Go to step 6 and look at create new branch section
* In this section there are only two IDE or text editor are mentioned.

### Screenshots
![editor](https://user-images.githubusercontent.com/45058288/68450915-ce2eda80-0214-11ea-985f-fbe4d31c4fb8.PNG)

### Proposed solution
Mention text editor which are suitable for beginner like.
[vscode](https://code.visualstudio.com/download)
[sublime text](https://www.sublimetext.com/3)

**Comment by perryc85** [comment]
@robinGiri, you can work on this. I would just add them in addition.
