### ISSUE TITLE
Topic buttons at top of Achievement page are broken

### ISSUE THREAD

**Issue by Crittenbach1** [open-learning-exchange/open-learning-exchange.github.io#2861]
### Problem
The 3 links at the top of the page under Topics are not working properly.  When I click them the page does not forward me to the topic.  When I opened the links in a new tab I got the message in the second screenshot.

### Steps to reproduce the problem
https://open-learning-exchange.github.io/#!./pages/manual/planet/achievement.md

Go to the Planet User Manual page on Firefox or Chrome.  Click the here button under Achievement to go to the Achievement page.  Click the links under Topics

### Screenshots

![Screenshot_2019-12-01 Achievements](https://user-images.githubusercontent.com/24684803/69920720-36aa5980-1459-11ea-84e7-def895cf0062.png)
![Screenshot_2019-12-01 open-learning-exchange github io](https://user-images.githubusercontent.com/24684803/69920717-327e3c00-1459-11ea-96a5-b6708bfabcb9.png)

### Proposed solution

Go through code and debug.

**Comment by nvrqt03** [comment]
Please include the link to the page where the links aren't working.

**Comment by Crittenbach1** [comment]
updated with link included

**Comment by mattscodeans** [comment]
Just a suggestion, but I think these links can be removed entirely. On the Achievement Page, there is a column on the left hand side that allows the user to navigate between the different sections. The links seem like a redundant feature to me.
