### ISSUE TITLE
Spelling Error in "Navigating To The Achievment Page"

### ISSUE THREAD

**Issue by mattscodeans** [open-learning-exchange/open-learning-exchange.github.io#2865]
### Problem
In the Planet User Manual, there is a spelling error in the title "Navigating To The Achievment Page". 
Achievment should be spelled Achievement. 

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/42992553/70926506-1befed00-1fe2-11ea-93ed-0d3900bf4cba.png)

### Proposed solution
Fix the spelling error.

**Comment by perryc85** [comment]
You can work on this
