### ISSUE TITLE
Title bar covered tile in different browser size

### ISSUE THREAD

**Issue by RyanDu** [open-learning-exchange/open-learning-exchange.github.io#2869]
### Problem
When switch the size of the browser, the title bar will not collapse in a burger button. it would changed to two separate lines and covered the title of the webpage.

### Steps to reproduce the problem

1. make a change in the javascript code of burger button
2. change the css of title bar in order to satisfy the order of collapse

### Screenshots

![屏幕快照 2019-12-17 下午10 21 27](https://user-images.githubusercontent.com/38671873/71055716-48a81f80-211c-11ea-922f-c578efcee799.jpg)

### Proposed solution

Go through code and debug.

**Comment by zc87-Leo** [comment]
This problem seems not exist.
<img width="597" alt="截屏2020-01-14下午4 54 14" src="https://user-images.githubusercontent.com/58234859/72385988-93eb2900-36ee-11ea-8af2-dd863d96536f.png">

**Comment by singharpita** [comment]
We should not focus on mobile design. This is related to template we are using.
