### ISSUE TITLE
Links to the top of the page are not working in mobile

### ISSUE THREAD

**Issue by MehdiHellal** [open-learning-exchange/open-learning-exchange.github.io#2870]
### Problem
When you are in the first steps page and using mobile device, the links which back you up to the top of the page are bot working.

### Steps to reproduce the problem

1. Go to:  https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md
2. Right click and inspect.
3. Click on the mobile icon on the top left of the inspection page then right click on the refresh icon of the page and click empty cache and hard reload.
4. Click on any step you would like.
5. Click on the green arrow oriented to the top.
Nothing will happen !! It supposed to get you back to the top of the page.

### Screenshots

<img width="818" alt="link issue" src="https://user-images.githubusercontent.com/35744446/71430321-a5fa1e80-2690-11ea-8ccb-7f207d6a0e5b.png">

### Proposed solution

Assign an ID  to the top (h1) element of the page and link that ID using # to all the [ ↑ ]

**Comment by mattscodeans** [comment]
When I look through the markdown in the vi-first-steps.md, there seems to be no specific link "[ ↑ ]" pointing to the top of the page. I believe these links to the top of the page are generated from the JavaScript(js) files. It might be a good idea to look at the .js files to find what code is generating the "[ ↑ ]" links to the top of the page.

**Comment by MehdiHellal** [comment]
I am not sure if I can access to the Js files though. If I am able would tell me where I can find them.

**Comment by singharpita** [comment]
This is not the task we should focus on. As this step requires computer anyway.
