### ISSUE TITLE
Footer Content displayed in the middle of the page

### ISSUE THREAD

**Issue by MehdiHellal** [open-learning-exchange/open-learning-exchange.github.io#2875]
### Problem
In some pages that don't have enough content, the footer will be shown high in the page while it should be stack at the bottom of the page.

### Steps to reproduce the problem
 https://open-learning-exchange.github.io/#!pages/techgenius/tg-faq.md 

### Screenshots

<img width="953" alt="footer-issue" src="https://user-images.githubusercontent.com/35744446/71860050-e4430500-30b6-11ea-9463-8ab1b37857d4.png">

**Comment by zc87-Leo** [comment]
We usually write a fragments file to unite the style of head, navigation bar, footer and so on. But we have no way to make it recognize whether the footer of the current page is at the bottom. I can provide another solution for you, you can add more <br> above the footer in pages which have less content.

**Comment by singharpita** [comment]
The page ends at that point so footer is coming there. As this not a highly design focused page. It should be ok to have it this way.
