### ISSUE TITLE
Change the font color of important information and add links.

### ISSUE THREAD

**Issue by zc87-Leo** [open-learning-exchange/open-learning-exchange.github.io#2878]
### Problem
In step 3, 6 & 8, user need to submit some links into Gitter chat , or the work of the users will be vain.  But the font color of the hint at the end of this paragraph is the same as the other parts, and it doesn't stand out. So may users can easily ignore these tips and forget to submit some important content.

### Steps to reproduce the problem

Firstly, click the link: https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md#Step_0_-_Introductory_Steps.

Secondly, see the ends of step 2, 6 & 8.

### Screenshots

<img width="433" alt="截屏2020-01-09下午5 03 47" src="https://user-images.githubusercontent.com/58234859/72108703-32981400-3302-11ea-8376-234edc4d1d0d.png">
<img width="548" alt="截屏2020-01-09下午5 03 55" src="https://user-images.githubusercontent.com/58234859/72108744-3f1c6c80-3302-11ea-8b00-55ec743cce47.png">
<img width="749" alt="截屏2020-01-09下午5 04 02" src="https://user-images.githubusercontent.com/58234859/72108755-45124d80-3302-11ea-95ca-43adc65eb5ab.png">

### Proposed solution

I think we can change the font color of these hints to red to make it more eye-catching. And we also can add some links for each content which users need to submit into the chat, which will help users quickly find what they are missing.

**Comment by mattscodeans** [comment]
I personally think this is a great idea, but I have a suggestion. I think red might be very distracting when trying to the read the hints. It might be better to highlight this section with yellow or light blue, drawing attention to this part of the steps while not being to distracting to read.

**Comment by zc87-Leo** [comment]
Hi, I post the problem of the first step page in my issue. Could you tell how to fix this problem in my local repo? I didn't find relevant md or html files.

**Comment by mattscodeans** [comment]
I believe you can find it inside of the github.io folder you created on your local repo. What you are looking for is the following file path:
pages -> vi ->vi-first-steps.md
The vi-first-steps.md is the markdown file for the first step page.

**Comment by zc87-Leo** [comment]
Thank you so much bro！

**Comment by dev2020-ui** [comment]
Good idea to change the font or highlight it which would make it stand out. I believe it would help people remember that it is important to post in Gitter.
