### ISSUE TITLE
Multiple typos/grammer errors in bughunt.md

### ISSUE THREAD

**Issue by sldaiute** [open-learning-exchange/open-learning-exchange.github.io#288]
The errors are as follows:
1. **"Clearly describe exactly what the bug is, the number of the test case, and the step that fail or produce unexpected output."**   This should say either "steps that fail" or "step that fails."
2. **"Make sure that your description of the bug is easily understandable, and describes the issue. Feel free to use images, to supplement your description."**  There should not be a comma after "understandable" or "images."
3. **"Even though the test cases already have the steps outlined. It's always a good idea to provide more detailed description and pictures to help the developer to understand the situation."** This should read "Even though the test cases already have the steps outlined, it's always a good idea..."
4. **"See the previous wiki to see how to write a good issue"**  This is missing a period.

**Comment by prmurphy** [comment]
I found another one as well. "One of its component, Selenium WebDriver, is a server written in Java that accepts commands for the browser via HTTP." should read "one of its components..."

**Comment by aberdean** [comment]
@sldaiute @prmurphy You guys can add those corrections and submit a pull request.
