### ISSUE TITLE
Next Section - embedd link so it goes to next step

### ISSUE THREAD

**Issue by dev2020-ui** [open-learning-exchange/open-learning-exchange.github.io#2881]
### Problem
When going through the Virtual Interns steps some of the pages have next section column on the left side. When you click the next section tab it takes you to the bottom of the page which says go to next step. It might be useful to maybe embed the link to the next step on the left side column as well. 

### Steps to reproduce the problem

Go to the Virtual Interns steps and on the left side column press next section which takes you to bottom of page to go to next step. 

### Screenshots

![image](https://user-images.githubusercontent.com/59748526/72303897-cb999880-363c-11ea-84a4-97237e26a1a7.png)
![image](https://user-images.githubusercontent.com/59748526/72303956-04397200-363d-11ea-8484-dfd59384baba.png)

### Proposed solution

It might be useful to embed a link which would take you to the next step instead of scrolling down

**Comment by AntonSynytsia** [comment]
I like that idea. I personally prefer previous and next buttons in the menu. The column of headers is generated by [mdwiki](http://dynalon.github.io/mdwiki/#!index.md). If there is a way to edit the columns, it would indeed improve usability.

**Comment by zc87-Leo** [comment]
I like this idea. It merge two steps into one. And embed a link is not a difficult work.

**Comment by dogi** [comment]
hmm ... I do not know if that is doable with our mdwiki
maybe it is easy

**Comment by singharpita** [comment]
Next Section is created by template itself due to use of header markdown. And it is supposed to take to you that specific header. Instead we can make Next Section to use lower header tag so it does not show up on sidebar menu.

**Comment by coreyuw** [comment]
I like your suggestion. I was thinking that maybe we could add a new navigation bar that lays horizontally at the top of every page (under the dark blue OLE navigation bar). The new bar will have links to Step 1-9, so that during any step, we can jump to any other specific step if we want to.
