### ISSUE TITLE
Suggest to Add Vagrant to ENV PATH for Windows 10 Users

### ISSUE THREAD

**Issue by AntonSynytsia** [open-learning-exchange/open-learning-exchange.github.io#2882]
### Problem
When I followed the steps for [Planet and Vagrant Installation](https://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md) on Windows 10, I was not able to access the `vagrant` command from my powershell (even after restarting the powershell).

This occurs due to `vagrant.exe` not being added to the ENV PATH variable.

### Steps to reproduce the problem
You must have Windows 10 to actually see the problem. I am not sure if this happens on everyone's system, but on my system, after installing Vagrant, the `vagrant` command was not accessible. In either case, starting fresh, do the following to reproduce the problem:
1. Download and install vagrant as indicated at https://www.vagrantup.com/downloads.html
2. Open powershell and type `vagrant`. You should get an error indicating that the command is unknown.

### Proposed solution
To fix the issue, manually add folder containing `vagrant.exe` to `Path` environment variable. In my case I had to access the environment variables window and add *C:\HashiCorp\Vagrant\bin* to the `Path` variable. After performing this step and restarting powershell, I was able to access `vagrant` from the powershell. See the attached screenshot:
![AddVagrantToPath](https://user-images.githubusercontent.com/2840847/72324931-e3831380-3660-11ea-964c-f221ea4de66b.jpg)

It will help to include these ENV requirements as a note for Windows 10 users on [Planet and Vagrant Installation](https://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md) page.

**Comment by zc87-Leo** [comment]
I recommend to add ur solution of this problem into the website. Although most users  choose Mac today, we still can not promise every one use Mac . So people who use windows may meet similar problems like u, they need some tips.

**Comment by singharpita** [comment]
In most of cases we have not seen this problem and vagrant is added in environment by default. Bu t you can add it as optional step and mention that after restart if vagrant command is not identified then they can go to environment and add it there

**Comment by dev2020-ui** [comment]
I used windows 10 and did not have this problem. Some systems may still have this problem so I think it would be useful to mention this in an additional step.

**Comment by lmmrssa** [comment]
Closing as no update since long time
