### ISSUE TITLE
Add specific path of first-step files in "GitHub Issues" Page

### ISSUE THREAD

**Issue by zc87-Leo** [open-learning-exchange/open-learning-exchange.github.io#2884]
### Problem
In step 6 & 8, we need find some problems, post issues and fix these problems. However, although the tutorial view the first-step carefully and find disadvantages, some users may not know the location of  first-step files in their local repositories. This will prevent them from completing the tutorial.

### Steps to reproduce the problem

click into “GitHub Issues”(link) which embedded in step6 content.

### Screenshots

<img width="1008" alt="截屏2020-01-14下午6 46 55" src="https://user-images.githubusercontent.com/58234859/72392490-3fe84080-36fe-11ea-8dbe-b122f9d70bfd.png">

### Proposed solution

We can add specific path of first-step files in "GitHub Issues" Page.

**Comment by dev2020-ui** [comment]
Adding specific paths could be useful or just to mention it again in an additional step to give a reminder.

**Comment by coreyuw** [comment]
That is a good observation and suggestion. We could also add a navigation bar throughout the tutorial pages for new interns.
