### ISSUE TITLE
Step 4 Planet Tutorial spelling error

### ISSUE THREAD

**Issue by dev2020-ui** [open-learning-exchange/open-learning-exchange.github.io#2885]
### Problem
Firefox is spelled Fiefox

### Steps to reproduce the problem

Go to step 4 Planet Tutorial and at Upload Resources at Note Firefox is spelled incorrectly

### Screenshots

![image](https://user-images.githubusercontent.com/59748526/72479397-548e0c80-37c2-11ea-8bf4-27241285a981.png)

### Proposed solution

Fix the spelling error.

**Comment by singharpita** [comment]
@dev2020-ui you can work on this
