### ISSUE TITLE
too many profiles in folder

### ISSUE THREAD

**Issue by LordJashin32** [open-learning-exchange/open-learning-exchange.github.io#2887]
Profiles directory is full of profiles that have no link on the site to them. They are just there. Lots of people that didn't join the teams or retired from them. Taking up a lot of space.

**Comment by dev2020-ui** [comment]
I agree it takes a lot of space and could easily be removed.

**Comment by coreyuw** [comment]
That is a good idea. I also noticed that a lot of the profiles are not grouped correctly in the alphabetic order.

**Comment by avin-sharma** [comment]
Agreed, there are a lot of profiles but how will we figure out if they are not interested in contributing anymore? Deleting their profiles removes the work they might have done to complete one of the first steps(Step 3).

**Comment by spykim2003** [comment]
I agree with it too. It would be better to make a separate folder called "old" and move unused profiles into it.

**Comment by rheam97** [comment]
i second the use of a separate folder called old interns. But i also think because the onboarding is so flexible, avin is right that it may be difficult to discern who is not interested in contributing.
