### ISSUE TITLE
Clarification in simpleinstall.md

### ISSUE THREAD

**Issue by sldaiute** [open-learning-exchange/open-learning-exchange.github.io#290]
Under "Prerequisites" in simpleinstall.md is:

**Check out your system RAM as Multiple machines are running at same time.**

I might add a quick clarifying note on what looks good as far as system RAM and what might be concerning.

**Comment by prmurphy** [comment]
There doesn't appear to be a simple answer to how much ram you need for each machine, but this page has some good information on it http://askubuntu.com/questions/150105/how-much-memory-ram-should-i-allocate-to-the-virtual-machine
I guess it mostly depends on how much ram the process needs, which I am unsure of right now.

**Comment by aberdean** [comment]
@sldaiute That depends on the RAM available on the host system. Since we cannot know how much RAM each person has on her/his system, it's not possible to provide an answer.

Also, that line doesn't exist anymore, so this issue is now outdated.
