### ISSUE TITLE
My profile page too simple (practice for Step 6)

### ISSUE THREAD

**Issue by coreyuw** [open-learning-exchange/open-learning-exchange.github.io#2916]
### Problem
My profile coreyuw.md is too simple. I added more features as a practice for step 6.

### Steps to reproduce the problem

N/A

### Screenshots

**Before**:
<img width="1112" alt="Screen Shot 2020-04-12 at 17 21 14" src="https://user-images.githubusercontent.com/39231660/79083314-68261200-7ce2-11ea-8701-093965c1e7de.png">

**After**:
<img width="558" alt="Screen Shot 2020-04-12 at 17 23 08" src="https://user-images.githubusercontent.com/39231660/79083301-58a6c900-7ce2-11ea-9630-8023c9dfee6d.png">

### Proposed solution

N/A

**Comment by lmmrssa** [comment]
This is not a valid issue. It is still part of first pull request to be not a new issue.
