### ISSUE TITLE
Step #5 Summary of the steps bullet points

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2917]
**Problem:**
In step #5 of the First steps(Git repositories). I found it to be confusing that the bullet points describing what steps one needs to perform are actual links to the steps on the same page.
My first instinct was to click them & open them in a new tab( to read more about each step). I did that and then realized they don't go to a new webpage.

**Steps to reproduce the problem:**
Clicking on the steps link

**Screenshots:**

![links in step 5](https://user-images.githubusercontent.com/40531136/79140725-6b72d980-7d86-11ea-95d3-51705e6cc01a.png)

![links in a new tab step 5](https://user-images.githubusercontent.com/40531136/79140615-40888580-7d86-11ea-8d00-02b2628580ce.png)

**proposed solution:**

Have the bullet points be just regular black unclickable text. You have to do them in the correct order/ one at the time anyway.

**Comment by Haoran-Hu** [comment]
I think those bullet points are supposed to be used as a navigation bar, with all the information being on the same page, you can skip some steps that you already knew and directly go to the part you need by clicking on the link. It is faster than scrolling up and down trying to find certain steps.

**Comment by chtelmko** [comment]
Then maybe the instructions should say "click to skip to a certain step or keep on reading for a detailed explanation for each step". to me if people don't follow each step in the order shown they can end up at different stage of the process.

**Comment by mdwattendorf** [comment]
I agree with chtelmko.  This is not the functionality used by MDwiki, see how their about page works:
http://dynalon.github.io/mdwiki/#!index.md
The links in a bulleted list under "credits/technologies" go to a different page.

I think the best solution would be to split these steps into sub-steps with separate pages (and call each sub-step 5.1, 5.2, 5.3, 5.4, and 5.5) then have the links go to those pages.  This matches the pattern in step 1.  

At the very least, the steps should be numbered, both in the links and in their headers.
