### ISSUE TITLE
Inconsistency of usage on the Planet User Manual page

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/open-learning-exchange.github.io#2919]
### Problem  

On the Planet User Manual page [link](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md), the navigation bar on the left side contains all the list group items and the detailed information for those items are on the right side of the page.  

If you choose to click on the items on the navbar to get to different sections, the chosen item will get highlighted, however, after some certain items, the selected elements would not get highlighted (**only underlined**, see screenshots).  **In my case**, the item is **Library**. Also, on the right side, the information about each item will move to the top of the page once it gets selected, but after **Library**, this feature is not working since the page already contains all the remaining contents after **Library**.  

If you choose to scroll down the page, similarly, when you get to a certain section, the corresponding element on the navbar on the left side will get highlighted. In my case, after the item **Course**, no more item would get highlighted correspondingly since the bottom of the page was reached.  

Again, the situation might be different depending on the size of the browsers that are being used, I am using a **15in MacBook pro** with the **full screen** browser when I am testing.

Hence, after you get to **Library** or **Course** (cases may vary), the navbar seems kind of redundant. Also, the functionality of the page is not consistent since all items should be highlighted when it gets selected and the corresponding section should move to the top of the page.

### Steps to reproduce the problem

On the top navbar, select **Manual**, and in the dropdown list, select **Planet User Manual**. Try to interact with the page using both navbar and scrolling down method.

### Screenshots
<img width="1654" alt="Screen Shot 2020-04-14 at 1 39 02 PM" src="https://user-images.githubusercontent.com/57075986/79261125-603ead00-7e5d-11ea-874c-da0f0353eced.png">
<img width="1650" alt="Screen Shot 2020-04-14 at 1 39 58 PM" src="https://user-images.githubusercontent.com/57075986/79261175-73517d00-7e5d-11ea-8573-fc096a58deab.png">
<img width="1629" alt="Screen Shot 2020-04-14 at 1 40 23 PM" src="https://user-images.githubusercontent.com/57075986/79261219-83695c80-7e5d-11ea-805b-e5b06ba87f0d.png">
<img width="1560" alt="Screen Shot 2020-04-14 at 1 42 05 PM" src="https://user-images.githubusercontent.com/57075986/79261250-8d8b5b00-7e5d-11ea-879b-223d64b4815a.png">

### Proposed solution
Make the **Features of Planet** a dropdown list, and put all the features into the dropdown list.

**Comment by chtelmko** [comment]
That a good idea about making the left side be a drop down menu. But I like all the information on one main page, that eliminates having to click every couple of minute to read about a new topic. I would change the left side(to the drop down), but keep right side as is.
