### ISSUE TITLE
More typos/grammar errors in bughunt.md

### ISSUE THREAD

**Issue by favour-nerrise** [open-learning-exchange/open-learning-exchange.github.io#292]
1. **"Create a project in eclipse"** 'eclipse' should be capitalized.
2. **"To create an WebElement to save the element on the web page and interact with it later"** 'an' should be 'a'.
3. **"To interact with WebElement"** There should be an 'a' before WebElement, and it should be on a separate bullet list.
4. **" Like the search bar of Google"** This should be in parentheses after the last sentence and state 'like Google's search bar'.
5. **"[other interactions]"** This should not be enclosed in brackets, and it should open up a link in a new tab.
6. **"2. Basic Tutorial for TestNG"** Below this title should be a sentence stating that annotations and methods for test cases and their uses will be described below.
7. **"@BeforeTest: when you put this annotation above a method, the method will be executed before the whole test begin"** 'begin' should have an 's' at the end.
8. **"a method that close the browser in the end,etc)"** 'close' should have an 's' at the end, there should be a space after the comma, and 'etc' should have a full stop. 
9. **"see [other asserts]"** 'see' should be capitalized, 'other asserts' should not be enclosed in brackets, and the following link in parentheses should be hyperlinked and open in a new tab.
10. **"To organize everyone’s the automated tests better, please try to follow the rules below"** There should be no 'the' before 'automated' and there should be a colon after 'below'.
11. **"Control + Shift +F on eclipse to make your code look better ;D"** 'eclipse' should be capitalized, and the emoticon should be properly formatted.
12. **"How to report issues"** The corresponding title on the sidebar menu should show an active state when this section is reached.
13. **"Be aware not to pick a functionality that is under construction or is already found buggy."** This should read "Be aware of picking a functionality that is under construction or has previously been found buggy."
14. **"If a bug is found, describe the bug in this google doc first:"** 'google doc' should be capitalized.

**Comment by favour-nerrise** [comment]
Apart from the suggested grammar corrections that are self-explanatory, I would improve this page by doing the following:
5. **"[other interactions]"** would become ["Other Interactions"](http://seleniumhq.github.io/selenium/docs/api/java/)
6. The short description of the following steps would state: "Listed below are annotations for manual test cases and how/when to use them:"
9. **"see [other asserts]"** would become ["See Other Asserts"](http://testng.org/javadocs/org/testng/Assert.html)

**Comment by dogi** [comment]
@favour-nerrise go for it ;) - create me a "pull request" for this
