### ISSUE TITLE
"Planet Configuration" wiki (Step 1.2) link typo

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/open-learning-exchange.github.io#2921]
### Problem
On step 1.2 "Planet Configuration", in the "Windows" section, it directs the user to navigate to "localhost:3100" in the browser, and if the user is unable to connect, then it says "check out Q13 in FAQ". Q13 in the FAQ is an issue with the submit button in the survey, while **Q14** is the issue regarding being unable to connect in Firefox.

### Steps to reproduce the problem

Go to the Windows section of [Planet Configurations](https://open-learning-exchange.github.io/#!./pages/vi/vi-configurations-vagrant.md) to see the "check out Q13 in FAQ". Then click on the FAQ link and navigate to Q13 & Q14, or go directly to the [FAQ](https://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#Technical_Questions), and then navigate to Q13 & Q14.

#### Planet Configurations page
![Step6_issue](https://user-images.githubusercontent.com/54686871/79265877-4f566180-7e86-11ea-8e13-5808d4eccd66.png)

#### FAQ page
![Step6_issue2](https://user-images.githubusercontent.com/54686871/79265910-59786000-7e86-11ea-9c67-85742b090589.png)

### Proposed solution

Go into the pages/vi/vi-configurations-vagrant.md file and change **Q13** to **Q14**

**Comment by chtelmko** [comment]
That makes sense, good catch.
