### ISSUE TITLE
Awkward formatting on Planet(Angular)

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/open-learning-exchange.github.io#2925]
### Problem  

On **Planet(Angular)** page, in section **Ways to Contribute**,  for the first way indicated on the page, the word **Including** starts in a new line, however, there is no reason to start a new line for just a single word.  Also, the sublist uses numbers as well, which is repeated. 

### Steps to reproduce the problem

Select Contributors, select **Planet(Angular)**, you can see under section **Ways to Contribute**.  

### Screenshots
<img width="1452" alt="Screen Shot 2020-04-15 at 2 29 52 PM" src="https://user-images.githubusercontent.com/57075986/79376032-8f215580-7f27-11ea-85d2-e412516fa8c8.png">
<img width="1399" alt="Screen Shot 2020-04-15 at 2 30 12 PM" src="https://user-images.githubusercontent.com/57075986/79376058-96e0fa00-7f27-11ea-942e-06fcacce685b.png">

### Proposed solution  
Delete the new line, use bullet points for the sublist.

**Comment by lmmrssa** [comment]
You can make change on this.
