### ISSUE TITLE
Add resource screenshot out of date

### ISSUE THREAD

**Issue by mdwattendorf** [open-learning-exchange/open-learning-exchange.github.io#2926]
### Problem
The screenshot used to show how to add a resource does not match the UI in current use. 

### Steps to reproduce the problem

1. Login as a member and select "Library"
2. Select the "+" button to add a resource.
3. You should see this:
<img width="1276" alt="Screen Shot 2020-04-15 at 3 47 53 PM" src="https://user-images.githubusercontent.com/27507807/79392341-7bc6b800-7f30-11ea-98d0-6774d79fe2e3.png">
4. In the wiki, under Tech Geniuses/Content and Library Management/How do I add a resource?, this is the screenshot of the UI
<img width="786" alt="Screen Shot 2020-04-15 at 3 50 47 PM" src="https://user-images.githubusercontent.com/27507807/79392614-e24bd600-7f30-11ea-91e4-bd6d8bd6f5c0.png">

### Proposed solution
Replace screenshot and update instructions to match.
It looks like this was supposed to be solved with issue #962, but it is now closed.

**Comment by lmmrssa** [comment]
@mdwattendorf you can work on this. #962 was when we had older version of application. Now with this current application

**Comment by anthonyhvo12** [comment]
@lmmrssa @mdwattendorf It seems like this issue has not been resolved. Can I work on it?

**Comment by mdwattendorf** [comment]
Absolutely.
