### ISSUE TITLE
Add collections screenshots out of date

### ISSUE THREAD

**Issue by mdwattendorf** [open-learning-exchange/open-learning-exchange.github.io#2927]
### Problem
The screenshots used to show how to add a collection do not match the UI on the manager account.

### Steps to reproduce the problem
1. Login as a manager and go to the library page.
2. In a separate window, go to https://open-learning-exchange.github.io/#!pages/techgenius/tg-library-management.md and scroll to "How do I create and use collections?"
3. Compare the screenshot examples to the UI (see below)
4. Select "collections" and compare the screenshot examples to the UI (see below)
5. Select "create new collection" and compare the screenshot examples to the UI (see below)

### Screenshots
####First comparison:
Actual:
<img width="1276" alt="Screen Shot 2020-04-15 at 5 02 16 PM" src="https://user-images.githubusercontent.com/27507807/79397289-fb598480-7f3a-11ea-9249-38527a9e0107.png">
vs.
Example:
<img width="811" alt="Screen Shot 2020-04-15 at 4 59 21 PM" src="https://user-images.githubusercontent.com/27507807/79397114-91d97600-7f3a-11ea-8f34-727b5491b29a.png">

####Second comparison:
Actual:
<img width="1272" alt="Screen Shot 2020-04-15 at 5 02 28 PM" src="https://user-images.githubusercontent.com/27507807/79397320-0f04eb00-7f3b-11ea-9fb3-c0ebd73834ab.png">

vs.
Example:
<img width="822" alt="Screen Shot 2020-04-15 at 4 59 33 PM" src="https://user-images.githubusercontent.com/27507807/79397122-99008400-7f3a-11ea-88fb-f8bf20131376.png">

####Third comparison:
Actual:
<img width="1272" alt="Screen Shot 2020-04-15 at 5 02 49 PM" src="https://user-images.githubusercontent.com/27507807/79397335-162bf900-7f3b-11ea-9d06-c7ce87f64b7c.png">
vs.
Example:
<img width="822" alt="Screen Shot 2020-04-15 at 4 59 33 PM" src="https://user-images.githubusercontent.com/27507807/79397122-99008400-7f3a-11ea-88fb-f8bf20131376.png">

### Proposed solution
Update screenshots, adjust directions to match.

**Comment by lmmrssa** [comment]
@mdwattendorf You can update with new screenshots

**Comment by anthonyhvo12** [comment]
@lmmrssa @mdwattendorf Can I work on updating the screenshots as mentioned in the issue?

**Comment by mdwattendorf** [comment]
Yes
