### ISSUE TITLE
Missing Header

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/open-learning-exchange.github.io#2928]
### Problem  

The header of **Community Installation** page is missing. 

### Steps to reproduce the problem  

Click **Tech Geniuses** and select **Community Installation**.

### Screenshots  
<img width="1453" alt="Screen Shot 2020-04-15 at 8 29 54 PM" src="https://user-images.githubusercontent.com/57075986/79401899-56e63b00-7f58-11ea-8c5d-52b3ad7fbfd4.png">
<img width="1464" alt="Screen Shot 2020-04-15 at 8 30 05 PM" src="https://user-images.githubusercontent.com/57075986/79401901-59489500-7f58-11ea-83b8-712de2f96172.png">

### Proposed solution  

The header should be added for consistency.

**Comment by lmmrssa** [comment]
@Haoran-Hu you can work on this

**Comment by Haoran-Hu** [comment]
@lmmrssa I'm on it.
