### ISSUE TITLE
Tacking a screenshot for feedback

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2929]
**Problem:**
In Step 4(Planet Tutorial) of the First steps. The two pictures linked under point 6, that states that
"When you provide feedback, try to be as specific as possible, and include screenshots when necessary" are not clear to show which one is the correct way of taking a screenshot. Also the screenshots are from a different part of the tutorial and don't fit with the subject of that step.

**Steps to reproduce the problem:**
NA

**Screenshots:**
![step 4 be specific screenshot](https://user-images.githubusercontent.com/40531136/79402757-d543dc80-7f5a-11ea-8cdd-2ce58cbafea2.png)

![step 4 be specific with suggestion screenshot](https://user-images.githubusercontent.com/40531136/79402765-d83ecd00-7f5a-11ea-8b8d-c2b6b21c6843.png)

**proposed solution:**
Have the picture indicate which screenshot is better and use a screenshot from the same step. Or zoom in more in the second picture, to make it clear what the screenshot was referring to.

**Comment by lmmrssa** [comment]
This part is not explaining which way is good way of taking screenshot. It is trying to show that you can take screenshots when giving feedback to understand the problem
