### ISSUE TITLE
Formatting of links in faq.md

### ISSUE THREAD

**Issue by favour-nerrise** [open-learning-exchange/open-learning-exchange.github.io#293]
In faq.md:

The last two sections, **'Helpful Links'** and **'Helpful Videos'**, contain multiple links. 

I would suggest that each of the links should open up in a new tab so that the reader should not be led away from OLE.

**Comment by favour-nerrise** [comment]
To open each link in these sections in a new tab, I will use the following syntax: 

> `<a href="http://example.com/" target="_blank">Hello, world!</a>`

This HTML syntax is supported by Github-flavored Markdown as seen here: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L44-L106

**Comment by mepda** [comment]
I like this idea, but wonder if the same thing could be accomplished in markdown.  It looks like the effectiveness of using 
```[link](url){:target="_blank"} ```
is debatable.

source: [stackoverflow](http://stackoverflow.com/questions/4425198/markdown-target-blank)

**Comment by aberdean** [comment]
I don't think that mixing HTML and Markdown is a good idea.
Just Right Click -> Open Link in New Tab is enough to address the issue.
