### ISSUE TITLE
vagrant up prod error in Step 1

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2931]
**Problem**
In step 1(Planet Tutorial) of the First steps. When running  "vagrant up prod" command, it gives the following error message: "Destroying VM and associated drives..."

**Steps to reproduce the problem:**
running "vagrant up prod" command.

**Screenshots**
![vagrant file #1](https://user-images.githubusercontent.com/40531136/79403154-14bef880-7f5c-11ea-8ffb-1df0a38ee50d.png)

![vagrant file #2](https://user-images.githubusercontent.com/40531136/79403159-17215280-7f5c-11ea-9f69-61fcf0cdf56f.png)

**Proposed solution:**
At the bottom of the tutorial in the troubleshooting section. Add item #8, saying " On Windows machines, if you get the following error: "Destroying VM and associated drives..." when you try to run "vagrant up prod" from command line(and you followed all prier steps having Git, Vagrant, and VirtualBox already installed). Try going into the vagrant file in the planet folder of the OLE and changing the local host address from 0,0,0,0 to 127,0,0,1.

**Comment by lmmrssa** [comment]
@chtelmko there is already part of content on vagrant installation where we are asking to download 2.2.4 or lower as newer version has issues.
