### ISSUE TITLE
Sync your fork step in step 4

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2933]
**Problem:**
In step 4(Planet Tutorial) of the First steps. The "Sync Your Fork" step is not clear, to explain what your "git fetch upstream" command should look like exactly.
  
**Steps to reproduce the problem:**
NA

**Screenshots:**

![step 4  screenshot #1](https://user-images.githubusercontent.com/40531136/79403674-8d728480-7f5d-11ea-8472-10722a861c59.png)

![step 4  screenshot](https://user-images.githubusercontent.com/40531136/79403669-8b102a80-7f5d-11ea-8ac3-b2d6317f57cb.png)

**proposed solution:**
Split the one step into two separate steps (the "git fetch upstream" and the "git checkout master"). Have the gray box showing what the print out, after the each of the steps would look like( similar to how the "Configure a Remote Repository for Your Fork" in step 3 was done).

**first command should be "git fetch upstream open-learning-exchange.github.io.git"
and the shown print out should read something similar to this :**

remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 6 (delta 4), reused 4 (delta 4), pack-reused 2
Unpacking objects: 100% (6/6), 1.25 KiB | 23.00 KiB/s, done.
From https://github.com/open-learning-exchange/open-learning-exchange.github.io
   93abc92..35966c1  master     -> upstream/master
   
**Second command should be "git checkout master"
and the shown print out should read something similar to this :**

Already on 'master'
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)
   
Updating 93abc92..35966c1
Fast-forward
pages/vi/profiles/jsschf.md | 21 +++++++++++++++++++++
1 file changed, 21 insertions(+)
create mode 100644 pages/vi/profiles/jsschf.md
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/chtelmko/chtelmko.github.io.git
   ca750f4..35966c1  master -> master

**Comment by Haoran-Hu** [comment]
I think they just combine two commands and their outputs together in a single grey box. It might seem a little confused at first but it does not affect the delivery of the tutorial.
