### ISSUE TITLE
Open a pull request buttons

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2935]
**Problem:**
In step 4(GitHub and Markdown) of the First steps. The picture linked under "Open a pull request" highlights two buttons.
  
**Steps to reproduce the problem:**
NA

**Screenshots:**

![pull request highlight only one button](https://user-images.githubusercontent.com/40531136/79474746-c863cf00-7fd4-11ea-8398-c3c3116fbd3e.png)

**proposed solution:**

highlight only one button to make the tutorial easier to follow.

**Comment by meharshahani** [comment]
Those are just two ways that you can create a pull request. I don't think we need to change anything in the screenshot. Though writing something like "the two highlighted buttons can be used interchangeably in order to create a pull request" would convey your point better.

**Comment by chtelmko** [comment]
then the instructions should cha, right now they read:
Open a pull request
Once you have your profile ready, it's time to create a pull request. Click on one of the "Pull request" button as highlighted in the screenshot below.

**Comment by chtelmko** [comment]
maybe they just meant to say "buttons". but to me it would still be confusing because only one of the highlighted buttons says "pull request" the other says "compare & pull request".

**Comment by meharshahani** [comment]
Ya makes sense, probably manipulating the words a little would solve that issue.

**Comment by Haoran-Hu** [comment]
It says "one of" and both bottoms contain "pull request" so it may be fine.
