### ISSUE TITLE
Creating issues checklist

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2936]
**Problem:**
In step 6(GitHub Issues) of the First steps. The instructions checklist and the screenshot have the same items. Seems redundant.

Steps to reproduce the problem:
NA

**Screenshots:**

![checklist for issue creation](https://user-images.githubusercontent.com/40531136/79478781-d36d2e00-7fd9-11ea-8820-24df5fbb4875.png)

**proposed solution:**

Remove the checklist or move it down after this paragraph :
 "Additionally, creating a checklist will help others understand what you have done and what needs to be done - it helps you coordinate with your team members with the issues you are facing in an organized manner. GitHub will render the task list in markdown, and it will look similar to something like the checklist shown below this paragraph."
Or remove the written checklist and attach a link to a blank reusable template which has all the checklist points.

**Comment by meharshahani** [comment]
Seems like a valid change. I think the checklist within the preview element can stay since that will give interns an idea as to what their pull request should look like.
