### ISSUE TITLE
OLE myPlanet User Manual

### ISSUE THREAD

**Issue by meharshahani** [open-learning-exchange/open-learning-exchange.github.io#2945]
### Screenshots
<img width="1422" alt="Screen Shot 2020-04-16 at 5 48 35 PM" src="https://user-images.githubusercontent.com/45812963/79513952-b00ea700-800a-11ea-94ca-29a860abccd9.png">

### Proposed solution
Instead of having the user click on that link and then turns out that the page is being updated and is currently unavailable, we can rather remove the link from the dropdown until the page has been fixed/updated. This will reduce time loss and will make the website more precise.

**Comment by Haoran-Hu** [comment]
This makes sense but maybe leave the link there would keep the entire website more intact and it is also a reminder of what is being updated for both administrators and the users.

**Comment by meharshahani** [comment]
That's right! I thought of that too. What would you recommend then as a solution to this?

**Comment by Haoran-Hu** [comment]
@meharshahani I would suggest keeping the link for now, but removing the link is also reasonable since it might cause confusion because of the similarity of the names, namely **Planet** and **myPlanet**.

**Comment by meharshahani** [comment]
How about we have a (Under Construction ⚠️) next to it!

**Comment by chtelmko** [comment]
@meharshahani I think under construction symbol, is a great idea. because it would be more work to take the link out and then putting it back up.

**Comment by meharshahani** [comment]
Perfect! Made a pull request for it.

Here's the raw.githack link : https://raw.githack.com/meharshahani/meharshahani.github.io/meharshahani-2945(1)/#!index.md

**Comment by lmmrssa** [comment]
We should try to put content instead of just adding icon. So closing this issue

**Comment by meharshahani** [comment]
> We should try to put content instead of just adding icon. So closing this issue

Hey, didn't really understand what you are trying to convey?

**Comment by singharpita** [comment]
@lmmrssa Is trying to say, we should start adding tutorial for myplanet. Not to make changes on menu

**Comment by meharshahani** [comment]
@lmmrssa @singharpita oh okay understood!
