### ISSUE TITLE
Planet User Manual page

### ISSUE THREAD

**Issue by meharshahani** [open-learning-exchange/open-learning-exchange.github.io#2949]
### Screenshots
<img width="1436" alt="Screen Shot 2020-04-16 at 7 46 43 PM" src="https://user-images.githubusercontent.com/45812963/79520160-9e81cb00-801b-11ea-9c3a-6d8cb641ddee.png">

### Proposed solution
In place of the numbered list, we can have a line that reads "The features with their explanation are mentioned below."

**Comment by Haoran-Hu** [comment]
I actually created a similar issue a couple of days ago but I think your explanation is better and it would be easier to modify the page in your case. My main focus for that issue was on the navbar on the left side of the page, and I did mention the redundancy of the content.

**Comment by meharshahani** [comment]
Oh, I didn't check your issue! Thanks for the feedback

**Comment by lmmrssa** [comment]
@meharshahani you can add more details to feature. Feature list should be anchor that takes you to detail of each feature.
