### ISSUE TITLE
Tablet Config Page

### ISSUE THREAD

**Issue by meharshahani** [open-learning-exchange/open-learning-exchange.github.io#2958]
### Problem
If you read the highlighted part - it says "Double tap on firefox-54.0.1.android-arm to launch the firefox installer". However, the screenshot attached below it is for Adobe Flash Player and not for Firefox. 

### Screenshots

<img width="1129" alt="Screen Shot 2020-04-20 at 2 12 50 AM" src="https://user-images.githubusercontent.com/45812963/79724106-955b5d00-82ac-11ea-98ad-377f97b283c0.png">

### Proposed solution
My solution would be to:
1.  Change the text to match the screenshot
2. Change the screenshot to match the text 

Ideal would be to change the text as it is less time consuming.

**Comment by Haoran-Hu** [comment]
The text is corresponding to the screenshot above it.
