### ISSUE TITLE
Feedback links

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2960]
**Problem:**
Feedback steps links are not working.

**Steps to reproduce the problem:**
Going to https://open-learning-exchange.github.io. Using the dropdown to select Planet User Manual Feedback under Manual tab and clicking the Feedback link .

**Screenshots:**

![feedback don't go anywhere](https://user-images.githubusercontent.com/40531136/79751160-1f70e900-82e0-11ea-9c12-32a231819c59.png)

![user manual](https://user-images.githubusercontent.com/40531136/79751564-cbb2cf80-82e0-11ea-95f9-9a250cc8e484.png)

![how to get to links](https://user-images.githubusercontent.com/40531136/79751508-af169780-82e0-11ea-85cd-8505ec0775ac.png)

**proposed solution:**

Fix the links

**Comment by LordJashin32** [comment]
This is similar to your other issue. Since the links are there. I don't see a problem with this. Should be good to work on.
