### ISSUE TITLE
Achievement Links

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2961]
**Problem:**
Achievement steps links are not working.

**Steps to reproduce the problem:**
Going to https://open-learning-exchange.github.io. Using the dropdown to select Planet User Manual Feedback under Manual tab and clicking the achievement link .

**Screenshots:**

![achievement links don't go anywhere](https://user-images.githubusercontent.com/40531136/79751953-79be7980-82e1-11ea-807f-9e9a529a8f97.png)

![user manual](https://user-images.githubusercontent.com/40531136/79751564-cbb2cf80-82e0-11ea-95f9-9a250cc8e484.png)

![how to get to links](https://user-images.githubusercontent.com/40531136/79751508-af169780-82e0-11ea-85cd-8505ec0775ac.png)

**proposed solution:**

Fix the links

**Comment by LordJashin32** [comment]
Seems like the underscores in the href anchor are missing. This seems good to work on.

**Comment by anthonyhvo12** [comment]
Has there been any fix for this issue? On my end it looks like the link is working properly now.

**Comment by chtelmko** [comment]
The links I was refering to, have been removed. I am not sure if there was a fix for this.
