### ISSUE TITLE
Typo in step 4 of first steps

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2965]
**Problem:**
In step 4(GitHub and Markdown) of the First steps. There is a typo, the step says 

Once you have your profile ready, it's time to create a pull request. Click on one of the "Pull request" _button_ as highlighted in the screenshot below.

but should say

Once you have your profile ready, it's time to create a pull request. Click on one of the "Pull request" _buttons_ as highlighted in the screenshot below.

**Steps to reproduce the problem:**
NA

**Screenshots:**

![highlight only one button](https://user-images.githubusercontent.com/40531136/79883820-5ae3e400-83c2-11ea-8d6a-cec1e89218d6.png)

**proposed solution:**
Change "button" to  "buttons".

**Comment by robinGiri** [comment]
Closing this since it is addressed in #2966.
