### ISSUE TITLE
Add helpful resources for mozilla developer network

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/open-learning-exchange.github.io#2993]
### Problem
Add new resources as helpful links for the [virtual interns faq helpful links section](https://open-learning-exchange.github.io/#!pages/vi/vi-faq.md)
Resources from Mozilla developer network that are very rich in content for:
- html
- css
- js

### Steps to reproduce the problem
N/A

### Screenshots

![issuefaqlinks](https://user-images.githubusercontent.com/48474421/80810786-390e0c80-8bcd-11ea-9c2a-91fddf2fa9d1.png)

### Proposed solution
Add links to resources from mozilla developer network docs as part of helpful links in virtual interns faq section to complete the links to w3schools
- [html](https://developer.mozilla.org/en-US/docs/Web/HTML)
- [css](https://developer.mozilla.org/en-US/docs/Web/CSS)
- [js](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)

**Comment by Mutugiii** [comment]
Will be working on it if approved

**Comment by LordJashin32** [comment]
Sure
