### ISSUE TITLE
Links within courses page non-functional

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/open-learning-exchange.github.io#2995]
### Problem
All the links or words styled as links do not work.

### Steps to reproduce the problem
Click on manual, planet user manual and [courses section](https://open-learning-exchange.github.io/#!./pages/manual/planet/./course.md). Links within the courses page do not work.

### Screenshots
![collectionherelink](https://user-images.githubusercontent.com/48474421/80846766-0f2d0800-8c16-11ea-9e2f-2835e53c541e.png)

![coursecollectionlinks](https://user-images.githubusercontent.com/48474421/80846712-dee56980-8c15-11ea-8f5b-23a5735c9deb.png)

![coursecollectionslinks2](https://user-images.githubusercontent.com/48474421/80846715-e3118700-8c15-11ea-9a34-c63bfb0640fe.png)

![coursesjoinlink](https://user-images.githubusercontent.com/48474421/80846718-e573e100-8c15-11ea-95b5-e72651e3f921.png)

### Proposed solution
Properly redirect the links or remove link styling

**Comment by Mutugiii** [comment]
Will work on redirecting or removing links based on feedback given

**Comment by Haoran-Hu** [comment]
@Mutugiii You can work on that.

**Comment by Mutugiii** [comment]
@Haoran-Hu I have opened a pr for this [here](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3013#issue-412677552)
