### ISSUE TITLE
Take home day to day page references

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/open-learning-exchange.github.io#2996]
### Problem
Links to mobile interns in the take home intern day to day page, lead to GitHub accounts that are not found

### Steps to reproduce the problem
Click on Contributors, [Takeout(android)](https://open-learning-exchange.github.io/#!pages/robots/rbts-takeout.md), [Take Home](https://open-learning-exchange.github.io/#!./pages/robots/rbts-takehome.md), [Take Home intern day to day](https://open-learning-exchange.github.io/#!./pages/robots/rbts-takehome-intern-day-to-day.md). It displays 3 Mobile leads with links to GitHub that are not working.

### Screenshots
![mobileintern1](https://user-images.githubusercontent.com/48474421/80847559-cdea2780-8c18-11ea-94b1-6d5d06d19cb1.png)
![mobileintern2](https://user-images.githubusercontent.com/48474421/80847566-d04c8180-8c18-11ea-852c-cff61cd19251.png)
![mobileintern3](https://user-images.githubusercontent.com/48474421/80847569-d2aedb80-8c18-11ea-8ca2-86e9f1fe6276.png)

### Proposed solution
Remove links to accounts that return 404 or implement based on guidance received

**Comment by Mutugiii** [comment]
Will work on it on confirmation of action to take

**Comment by gautamsethi1** [comment]
I think this is a good catch. It is good to update their contact information in case anyone wants to reach out to them. Good job on finding this issue.
