### ISSUE TITLE
Typo on First Steps Page

### ISSUE THREAD

**Issue by Sachit1137** [open-learning-exchange/open-learning-exchange.github.io#3000]
### Problem
There is a grammatical error in the marked sentence. The comma after the word "steps" should not be there.

### Steps to reproduce the problem

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/55988870/80855701-6086c880-8c11-11ea-9b77-3e5a9a7d3916.png)

### Proposed solution

There should not be a comma after "steps" in the marked sentence.

**Comment by LordJashin32** [comment]
I typically don't like sentences like this that have multiple and's. I'd rather have more separate sentences personally. More periods.

**Comment by Sachit1137** [comment]
@LordJashin32 Thanks for you feedback. Is the below statement better?

"Please note that creating and working on Issues are not exactly bound by the "Step" you are in. Feel free to move on to other steps while you wait on OLE approval for your merge(s). You can also add more Issues and PR's in the meantime."
