### ISSUE TITLE
Update First Steps on homepage

### ISSUE THREAD

**Issue by wehsu** [open-learning-exchange/open-learning-exchange.github.io#302]
It might be easier to just get rid of the old Start Here, so people don't accidentally click the wrong one, which I did the first time, or just move the New Start Here to the top.

**Comment by wehsu** [comment]
I guess we can remove the Start Here in navigation.md and rename it Start Here or just keep it as it is.

**Comment by dogi** [comment]
@wehsu all of it is fine

**Comment by dogi** [comment]
please create a pull request

**Comment by wehsu** [comment]
@dogi  I just updated them and let me know if they look good to you.  Thanks !

**Comment by aberdean** [comment]
@dogi @wehsu Re: #303 I really like this idea!
At this point, wouldn't it be better to delete firststeps.md and rename newfirststeps.md to firststeps.md? Just to make a clean job and avoid dangling pages?

**Comment by wehsu** [comment]
@dogi  @aberdean #303 Yeah sure ! If that's okay with you both, I'll go ahead deleting it and rename it to firststeps.md.
