### ISSUE TITLE
Wrong screenshot on Feedback page

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/open-learning-exchange.github.io#3024]
### Problem
Wrong screenshot on Feedback page.

### Steps to reproduce the problem
Go to **Manual** tab -> Click on **Planet User Manual** -> Scroll down to **Feedback** and click the link that says **here** -> Scroll down to **Giving Feedback to Planet**. The red box on the screenshot highlights the sync button instead of the feedback button.

### Screenshots
<img width="1288" alt="Issue #1_Wrong Button" src="https://user-images.githubusercontent.com/43098273/81463606-ad761c00-9188-11ea-8de3-97e06763dc23.png">

### Proposed solution
Change the screenshot to point to the correct icon as follows.
<img width="1236" alt="Screen Shot 2020-05-09 at 12 14 43 AM" src="https://user-images.githubusercontent.com/43098273/81463797-5c672780-918a-11ea-89b6-8c1b16a11402.png">

**Comment by robinGiri** [comment]
@anthonyhvo12 its a good catch, you can work on this.
