### ISSUE TITLE
Creating a New Tab For Helpful Links/Videos

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/open-learning-exchange.github.io#3033]
### Problem
I believe that the helpful links/videos can prove to be very beneficial for other Virtual Interns. However, their placement makes them hard to find and thus negates their effect. 

### Steps to reproduce the problem
Click on the Virtual Interns Tab
Then choose FAQ
Afterward, scroll to the bottom of the page to find the helpful links/videos

### Screenshots
<img width="1677" alt="Screen Shot 2020-05-14 at 3 39 33 AM" src="https://user-images.githubusercontent.com/33525794/81924899-95d9d180-9594-11ea-89a3-2178160d3001.png">
![Uploading Screen Shot 2020-05-14 at 3.36.38 AM.png…]()
<img width="1505" alt="Screen Shot 2020-05-14 at 3 37 05 AM" src="https://user-images.githubusercontent.com/33525794/81924607-311e7700-9594-11ea-9411-9bc18186bb36.png">

### Proposed solution
Creating a tab titled: "Helpful Links/Videos"

**Comment by anthonyhvo12** [comment]
@gautamsethi1 That is a very good point. An alternative I would suggest is to create a separate tab for the entire FAQ section, as the page is quite frequently visited.

**Comment by gautamsethi1** [comment]
That is an interesting idea. However, there are multiple FAQ pages and thus it is better to keep the FAQ pages separated based on the audience.
