### ISSUE TITLE
Out of date instructions on Admin User Manual

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/open-learning-exchange.github.io#3035]
### Problem
The instructions for the **How do I create and use Collections?** on the Admin User Manual page are out of date. The screenshots and numbering are off, too.

### Steps to reproduce the problem
Click on **Tech Geniuses** tab -> Choose **Admin User Manual** -> Click on **How do I create and use Collections?** on the left sidebar.

### Screenshots
![Screen Shot 2020-05-14 at 2 07 56 PM](https://user-images.githubusercontent.com/43098273/81969922-acac1280-95ec-11ea-9312-1a4e96f250f0.png)
![Screen Shot 2020-05-14 at 2 08 18 PM](https://user-images.githubusercontent.com/43098273/81969923-acac1280-95ec-11ea-95fe-8e86e592a948.png)

### Proposed solution
Edit the instructions to reflect the current version and update the screenshots as follows:
![Screen Shot 2020-05-14 at 12 07 21 PM](https://user-images.githubusercontent.com/43098273/81970165-12000380-95ed-11ea-92ea-a333212290c3.png)
![Screen Shot 2020-05-14 at 2 05 16 PM](https://user-images.githubusercontent.com/43098273/81970168-12989a00-95ed-11ea-84f0-e8366dae3c4e.png)

**Comment by gautamsethi1** [comment]
Good point. Updating the screenshots will make it easier for people to complete the steps in the future. Completely agree with your solution.

**Comment by lmmrssa** [comment]
yes this can be worked on

**Comment by JonathanKoerber** [comment]
Great catch. The new screenshots make it much clearer.
