### ISSUE TITLE
Adding Another Troubleshoot Step

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/open-learning-exchange.github.io#3044]
## Problem
I tried to access http://localhost:3100, however, it did not load. I then tried to do: vagrant halt prod, vagrant up prod. An error popped up and I was unable to access http://localhost:3100.

### Steps to reproduce the problem
Restart your MacBook. 
Then, try to use the commands vagrant up prod or vagrant halt prod in Terminal. 

### Screenshots
<img width="558" alt="Screen Shot 2020-05-16 at 3 55 38 AM" src="https://user-images.githubusercontent.com/33525794/82118008-1cbfb300-9729-11ea-88a0-c3eab64726bb.png">

### Proposed solution
Adding steps to troubleshoot this issue on the Wiki.

**Comment by lmmrssa** [comment]
@gautamsethi1 this is the problem that came because you tried to run it not from the project folder but instead from github.io folder which is not where planet project is

**Comment by gautamsethi1** [comment]
I understand that. But isn't the solution I proposed another way to access http://localhost:3100? Terminal stated that I needed to either use the solution I detailed, or try to switch directories. After I encountered this problem, I found that the solution I proposed is a common way people get around the error that is detailed above and was actually recommended with Terminal. And I can still access http://localhost:3100, with the GitHub directory still visible. Please let me know where I am misunderstanding the problem. Thank you.

**Comment by gautamsethi1** [comment]
I would also like to add that the only troubleshooting steps I found for my problem were to use vagrant halt prod, and vagrant up prod which clearly didn't work. Since I use the vagrant up [id], am I not able to get around the incorrect directory issue that you suggested?
