### ISSUE TITLE
Fixing a Typo

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/open-learning-exchange.github.io#3046]
### Problem
In the GitHub Issues tab, there was a typo. 

### Steps to reproduce the problem
Click on the Virtual Intern tab. 
Then, choose Step 6. 
Scroll to the **Create a New Branch** tab.

### Screenshots
<img width="833" alt="Screen Shot 2020-05-16 at 4 14 25 AM" src="https://user-images.githubusercontent.com/33525794/82118444-6362dc80-972c-11ea-9605-f1120d4cf3b7.png">

### Proposed solution
Replace "next" with "the".

**Comment by sncarlson** [comment]
Nice catch!

**Comment by anastasia21112** [comment]
Good catch! This makes the instructions sound clearer.
