### ISSUE TITLE
Out of date Members Menu instructions

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/open-learning-exchange.github.io#3055]
### Problem
Out of date instructions on how to navigate the Members Menu on **Admin User Manual** page.

### Steps to reproduce the problem

Click on **Tech Geniuses** -> **Admin User Manual**. Click **Members Menu** on the left sidebar.

### Screenshots

Old Screenshot & Instructions:
![Screen Shot 2020-05-17 at 11 27 51 AM](https://user-images.githubusercontent.com/43098273/82152897-5cbe8d00-9832-11ea-83ee-a4a199cc83af.png)

Screenshots from current Planet version:
![Screen Shot 2020-05-17 at 11 28 31 AM](https://user-images.githubusercontent.com/43098273/82152939-8f688580-9832-11ea-917f-66a2139835e2.png)
![Screen Shot 2020-05-17 at 11 28 59 AM](https://user-images.githubusercontent.com/43098273/82152899-5d572380-9832-11ea-9441-fe8c06ad4c66.png)

### Proposed solution
Update the section with new screenshots and instructions.

**Comment by anastasia21112** [comment]
This is a great way to fix this! Keeping elements updated is vital. Maybe include arrows in the screenshots so that the reader knows what tabs to click on.

**Comment by vinitnprabhu** [comment]
Yes, keeping the instructions and screenshots updated is very important. It makes it much easier for the vi to follow steps.
