### ISSUE TITLE
VirtualBox Required Storage Warning On Mac

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/open-learning-exchange.github.io#3059]
### Problem
When installing VirtualBox/Vagrant on Step 1, there is no warning about how much disk space is required. This could lead to errors during installation claiming that the user does not have enough disk space to install the application. The required disk space to install vagrant and virtual box is around 6GB on mac. 

### Steps to reproduce the problem
N/A

### Screenshots
![Screen Shot 2020-05-19 at 10 51 48 PM](https://user-images.githubusercontent.com/49795308/82406246-5cd1af00-9a23-11ea-8fa2-c376112d4ea8.png)

### Proposed solution
Add a section under the Prerequisites in Step 1 about making sure you have the right storage space to minimize errors during the download. OR this could be added under the Preparation header. 

Another alternative is to add this at the very beginning of the steps with a slight warning saying that the new intern should have a laptop with about 7 GB free on their disk in order to install all of the software required. 

We could also add some steps to clearing storage on mac such as using CleanMyMac or how to access their storage and clear some extraneous files.

**Comment by robinGiri** [comment]
It sounds good to me. Writing in prerequisites may be better solution. Just warning with 7 GB free space may be enough.
