### ISSUE TITLE
Clarifying Requirements for Virtual Interns

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/open-learning-exchange.github.io#3061]
### Problem
So as I was going through the FAQ section for virtual interns, I noticed that one of the requirements it stated was having 5 PRs. However, the actual requirement is 5 **merged** PRs. This difference may confuse some new interns. 

### Steps to reproduce the problem
Click on the Virtual Intern tab. 
Then choose FAQ. 
Afterward, go to Q8.

### Screenshots
<img width="870" alt="Screen Shot 2020-05-20 at 12 31 09 AM" src="https://user-images.githubusercontent.com/33525794/82418328-b50fad80-9a31-11ea-9e2f-a95ae5f9ad2a.png">

### Proposed solution
Add the word merged, to ensure that there is no confusion.

**Comment by anastasia21112** [comment]
This is a great clarification!
