### ISSUE TITLE
Add a Table to the Bottom of "The Steps" Section on the First Steps Page

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/open-learning-exchange.github.io#3064]
### Problem
There is a lot to read for "The Steps" section and the requirements for PR's, issues, and comments is not explicitly stated in the paragraph. I am currently working on the fix. 

### Steps to reproduce the problem
Check out and read "The Steps" section on the First Steps page and view the requirements mentioned. 

### Screenshots
![Screen Shot 2020-05-20 at 3 13 34 PM](https://user-images.githubusercontent.com/49795308/82498054-8edb2380-9aac-11ea-83d4-5a5148fd13f8.png)

### Proposed solution     
Add a table at the bottom of the section to refresh the reader of their requirements/expectations so that they have a better recollection of what they should do while reading the steps. The table would look somewhat like this:   
*****
|Requirements|Expectations|
|--------------|-------------|
| 5 PRs | Thoughtfulness|
 | etc. |        etc. |

**Comment by gautamsethi1** [comment]
I'm not sure that this would be necessary as there is already a bulleted list of requirements in Step-8. 

<img width="863" alt="Screen Shot 2020-05-21 at 2 35 57 AM" src="https://user-images.githubusercontent.com/33525794/82545639-cf1dbe80-9b0b-11ea-9836-db3ea9ec0f1b.png">

**Comment by vinitnprabhu** [comment]
I agree with Gautam

**Comment by anastasia21112** [comment]
unnecessary and issue already created for this (issue 2807)
