### ISSUE TITLE
Add Note to myPlanet Tutorial Page

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/open-learning-exchange.github.io#3068]
### Problem
myPlanet is only available to people with access to an Android device. People who don't have access to an Android device should know that this step is not required for them. Although the exclusivity is mentioned, it is not explicitly said that this is not required for non-Android users. 

### Steps to reproduce the problem
Look at the myPlanet Tutorial for Step 4. 

### Screenshots
![Screen Shot 2020-05-21 at 10 12 53 AM](https://user-images.githubusercontent.com/49795308/82579898-addcc280-9b4b-11ea-8b2a-f154696271b9.png)

### Proposed solution
Add a disclaimer/note at the top of the tutorial mentioning that this step is only applicable to Android users and is not required.

**Comment by vinitnprabhu** [comment]
Yes, explicitly saying it is not required for non-Android user would make instructions clearer to a vi

**Comment by AbdulkadirAbdullahi** [comment]
Good suggestion

**Comment by avin-sharma** [comment]
@anastasia21112 @lmmrssa  I will do it. Where would be a good place to put the note? At the very top or after it is mentioned that it is only available on Android under the Preparation section.

**Comment by anastasia21112** [comment]
@avin-sharma I think after the "only for Android" limitation is mentioned would be great. However, either way works!
