### ISSUE TITLE
Include Examples of Text Editors

### ISSUE THREAD

**Issue by vinitnprabhu** [open-learning-exchange/open-learning-exchange.github.io#3076]
### Problem

Examples of good text editors are not included, for someone who does not have a text editor installed.

### Steps to reproduce the problem

Click on the Virtual Intern tab.
Then, choose Step 6.
Scroll to the Create a New Branch tab.

### Screenshots

<img width="663" alt="issueTE" src="https://user-images.githubusercontent.com/59180367/82744519-40918300-9d3f-11ea-87ed-b1bacf138210.PNG">

### Proposed solution

Change to "You can use any text editor, like Atom or Sublime Text"
With Atom and VS code being links to their respective installation pages.

**Comment by anastasia21112** [comment]
I think that's an amazing addition! You can also suggest text editors like emacs/aquamacs for Mac or maybe sublime text.
