### ISSUE TITLE
Archived project Takeout listed under Active Projects

### ISSUE THREAD

**Issue by avin-sharma** [open-learning-exchange/open-learning-exchange.github.io#3105]
### Problem
The archived project [Takeout](https://github.com/ole-vi/takeout) is listed under Active projects on [Virtual Intern Orientation](https://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md) page.

### Steps to reproduce the problem

Visit [Virtual Intern Orientation](https://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md) page for listing and  [Takeout](https://github.com/ole-vi/takeout) to verify its status on Github.

### Screenshots

<img width="1920" alt="Screen Shot 2020-06-21 at 5 22 06 PM" src="https://user-images.githubusercontent.com/6264813/85235749-7cbf0e80-b3e5-11ea-8a7b-0d6cf785b69c.png">

<img width="1920" alt="Screen Shot 2020-06-21 at 5 20 06 PM" src="https://user-images.githubusercontent.com/6264813/85235757-8a749400-b3e5-11ea-9a2f-05c77851a745.png">

### Proposed solution

A possible solution would be to replace [Takeout](https://github.com/ole-vi/takeout) with [myPlanet](https://github.com/open-learning-exchange/myplanet).

**Comment by anastasia21112** [comment]
This is a fantastic idea!!
