### ISSUE TITLE
No mention of languages/tech for Android app development in Virtual Intern First Steps

### ISSUE THREAD

**Issue by avin-sharma** [open-learning-exchange/open-learning-exchange.github.io#3108]
### Problem
There is no mention of Android or languages used in Android App Development in the Big Picture section of [First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) which gives the impression that nothing related to Android is being actively worked on.

### Steps to reproduce the problem

Visit [First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) and take a look at languages/tech in the very first section of the page, before the note.

### Screenshots

<img width="1920" alt="Screen Shot 2020-06-22 at 4 40 05 PM" src="https://user-images.githubusercontent.com/6264813/85338326-14892f00-b4b0-11ea-9bae-bfff13979f4e.png">

### Proposed solution

Add [Java](https://www.codecademy.com/learn/learn-java), [Kotlin](https://kotlinlang.org/) to the list.

**Comment by anthonyhvo12** [comment]
Good catch - feel free to work on it.

**Comment by avin-sharma** [comment]
Thanks, working on it now!
