### ISSUE TITLE
Adding a line to clarify that MD is not HTML

### ISSUE THREAD

**Issue by mepda** [open-learning-exchange/open-learning-exchange.github.io#311]
Several interns, myself included, thought that MD was just some version of HTML, as the cheat sheet could be interpreted as being the output of the HTML listed.

I suggest putting a line at the start of the explanation saying

**Comment by aberdean** [comment]
Sure! Actually, we've been wondering why that page was confusing some interns, and didn't think about that.      
Please, go ahead and post a pull request (just remember that Markdown is one word).
