### ISSUE TITLE
Add more content to myPlanet Tutorial

### ISSUE THREAD

**Issue by avin-sharma** [open-learning-exchange/open-learning-exchange.github.io#3111]
### Problem
Right now [myPlanet Tutorial](https://open-learning-exchange.github.io/#!./pages/vi/vi-myplanet.md) gives us the link to the app on the Play Store. I think it would be really helpful if there were tips on how to use the app, for example, a tutorial on logging into the app which details how to find the server address, who the administrator might be to ask for a pin.

### Steps to reproduce the problem

Visit [myPlanet Tutorial](https://open-learning-exchange.github.io/#!./pages/vi/vi-myplanet.md).

### Screenshots

<img width="1920" alt="Screen Shot 2020-06-22 at 8 06 13 PM" src="https://user-images.githubusercontent.com/6264813/85346583-e0b80480-b4c3-11ea-813e-f95c339a2bcd.png">

### Proposed solution

Add a tutorial with screenshots and an example of how to log in.

**Comment by spykim2003** [comment]
It's a good idea! Someone who has an Android phone can work on it?

**Comment by JonathanKoerber** [comment]
Good catch there definitely be more content here. Could this be solved by adding links tutorials else ware in the site? Then is a good tutorial to tablet configuration under Tech Geninese> Tablet Configuration. Also some good information in the myPlanet README file.

**Comment by lmmrssa** [comment]
There is myPlanet tutorial section https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md if we start putting content there then we can refer that link for more details on using myPlanet.
Tablet configuration is also outdated so we will have to update it as well.

For a start we can put link of myplanet github for connecting myplanet with planet.
