### ISSUE TITLE
Update Take Home Intern Day-to-Day Page

### ISSUE THREAD

**Issue by avin-sharma** [open-learning-exchange/open-learning-exchange.github.io#3112]
### Problem
Since [take-home](https://github.com/open-learning-exchange/take-home) is now archived the [Take Home Intern Day-to-Day Page](https://open-learning-exchange.github.io/#!/pages/robots/rbts-takehome-intern-day-to-day.md) page is outdated.

### Steps to reproduce the problem

Visit [Take Home Intern Day-to-Day Page](https://open-learning-exchange.github.io/#!/pages/robots/rbts-takehome-intern-day-to-day.md).

### Screenshots
<img width="1920" alt="Screen Shot 2020-06-22 at 8 21 55 PM" src="https://user-images.githubusercontent.com/6264813/85347339-43120480-b4c6-11ea-953f-897b4fe466ad.png">

### Proposed solution

Update [Take Home Intern Day-to-Day Page](https://open-learning-exchange.github.io/#!/pages/robots/rbts-takehome-intern-day-to-day.md) page or remove it if it is not being used anymore.

**Comment by anastasia21112** [comment]
Oh yes! This is in dire need of an update... however, it may be a load to take on to rewrite a whole page. I might suggest putting a large note at the very top telling the user to go to the myPlanet repository on the open-learning-exchange github and reading the readME for instructions! Although, if you want to rewrite the whole page, have at it! :)

**Comment by JonathanKoerber** [comment]
Good catch! It is confusing to have this page here. A note to navigate users back the myPlanet repository, as anastasia21112 noted,  would solve the issue nicely. I had a difficult time finding the on the page within the site. I could only navigate to it by way of Contributers> TakeOut(Android) >Take Out.

**Comment by lmmrssa** [comment]
First thing we can start changing it to change **Take home** to **myPlanet** as Take Home is older version of myplanet. And then changing links to relevant myPlanet
