### ISSUE TITLE
Confusing abbreviation in step 1-2: Planet configurations

### ISSUE THREAD

**Issue by spykim2003** [open-learning-exchange/open-learning-exchange.github.io#3115]
### Problem

In step 1-2: Planet configurations, there is an ambiguous abbreviation called "RPi". It would be hard to understand for members who are not familiar with Raspberry Pi. 

### Steps to reproduce the problem

[Planet Configurations](https://open-learning-exchange.github.io/#!pages/vi/vi-configurations-vagrant.md)
### Screenshots

<img width="1245" alt="Screen Shot 2020-06-26 at 8 49 12 PM" src="https://user-images.githubusercontent.com/47366411/85912104-9dc19e00-b7ef-11ea-992b-3f1195826e8f.png">

### Proposed solution

Option 1: Use full naming instead of the abbreviation

Communities are how the Planet functions on a local network, with users connecting to a community using either a laptop or a `Raspberry Pi` and a router.

Option 2:  Add full name with the abbreviation

Communities are how the Planet functions on a local network, with users connecting to a community using either a laptop or a `RPi(Raspberry Pi)` and a router.

Option 3: Put the Wiki page link on the abbreviation "RPi".

Communities are how the Planet functions on a local network, with users connecting to a community using either a laptop or a [RPi](https://en.wikipedia.org/wiki/Raspberry_Pi) and a router.

I personally prefer option 1.

**Comment by robinGiri** [comment]
I also prefer option 1. Its meaningful and simple to understand to everyone right.
