### ISSUE TITLE
Inefficient link in the First Step - Big Picture

### ISSUE THREAD

**Issue by spykim2003** [open-learning-exchange/open-learning-exchange.github.io#3117]
### Problem

From the First Step - Big Picture, there is a sentence:

"Once accepted, you and your team will work on an assignment, and we’ll switch up the assignments each week. As part of this internship, you will have the opportunity to work with software and languages including Git, GitHub, Markdown, Vagrant, VirtualBox, Command Line/Terminal, Command Line/Terminal Scripts, Vim, CouchDB, Docker, HTML5, JavaScript, Node.js, Angular, [Java](https://www.codecademy.com/learn/learn-java), and Kotlin."

When I click the link of Java, the website will redirect to the Java tutorial on the Codecademy website.
Users might want to briefly take a look at the syntax for Java if they are not familiar with it.
However, it requires login to the website to take some lessons. It is inefficient for the link.

### Steps to reproduce the problem

[First Step - Big Picture](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md)

### Screenshots

<img width="905" alt="Screen Shot 2020-06-28 at 4 41 15 PM" src="https://user-images.githubusercontent.com/47366411/85959545-b30b0980-b962-11ea-8e9d-e5893ec63e53.png">

<img width="1263" alt="Screen Shot 2020-06-28 at 4 42 03 PM" src="https://user-images.githubusercontent.com/47366411/85959606-067d5780-b963-11ea-9daa-7081fc8b8be2.png">

<img width="1023" alt="Screen Shot 2020-06-28 at 4 42 10 PM" src="https://user-images.githubusercontent.com/47366411/85959630-1e54db80-b963-11ea-96fd-6b53fc48a0ce.png">

### Proposed solution

Change the link to Java tutorial on Tutorial Point instead of Codecademy.
Java tutorial on Tutorial Point doesn't require a login, and it's easy to take a look at the definition of Java and tutorials.

"Once accepted, you and your team will work on an assignment, and we’ll switch up the assignments each week. As part of this internship, you will have the opportunity to work with software and languages including Git, GitHub, Markdown, Vagrant, VirtualBox, Command Line/Terminal, Command Line/Terminal Scripts, Vim, CouchDB, Docker, HTML5, JavaScript, Node.js, Angular, [Java](https://www.tutorialspoint.com/java/index.htm), and Kotlin."

**Comment by anastasia21112** [comment]
Good suggested improvement!
