### ISSUE TITLE
A link doesn't include the word "Gitter" in a note of the First Steps - The Big Picture

### ISSUE THREAD

**Issue by spykim2003** [open-learning-exchange/open-learning-exchange.github.io#3118]
### Problem

In a note of First Steps - The Big Picture,

"NOTE: This is an unpaid but intensive internship that requires 16 hours of work each week. More information about the internship can be found in our FAQ. If you have further questions, don’t hesitate to ask other members in the Gitter [chat](https://open-learning-exchange.github.io/#!./pages/vi/vi-chat.md)!"

The link of "Gitter chat" only displays for the word "chat" and excludes the word "Gitter".

### Steps to reproduce the problem

[FirstSteps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md)
<img width="882" alt="Screen Shot 2020-06-28 at 5 25 34 PM" src="https://user-images.githubusercontent.com/47366411/85959929-2150cb80-b965-11ea-905a-f33175e5669a.png">

### Proposed solution

Include the link for the word "Gitter" too.

"NOTE: This is an unpaid but intensive internship that requires 16 hours of work each week. More information about the internship can be found in our FAQ. If you have further questions, don’t hesitate to ask other members in the [Gitter chat](https://open-learning-exchange.github.io/#!./pages/vi/vi-chat.md)!"

**Comment by anastasia21112** [comment]
Looks good!!
