### ISSUE TITLE
Edit links to open in new windows

### ISSUE THREAD

**Issue by JonathanKoerber** [open-learning-exchange/open-learning-exchange.github.io#3126]
### Problem
On the first steps page the links for FAQ, useful links and video tutorials, and gitter chat navigates
 users away from the first steps page.

### Steps to reproduce the problem

NA 

### Screenshots

![Screenshot_2020-07-10 First Steps](https://user-images.githubusercontent.com/14159224/87164909-3b03e400-c27e-11ea-9ea6-0bc03f9bab1a.png)

### Proposed solution

Edit the markup to have the links open a new tab.

**Comment by gautamsethi1** [comment]
Looks like a good function to add!

**Comment by JonathanKoerber** [comment]
Great I'll get on it!
