### ISSUE TITLE
Add archived heading to takeout app documentation

### ISSUE THREAD

**Issue by JonathanKoerber** [open-learning-exchange/open-learning-exchange.github.io#3129]
![image](https://user-images.githubusercontent.com/14159224/87554106-9102ce00-c668-11ea-8551-2b124b0949bb.png)

### Problem
OLE has archived the Takeout repository, but through the Contributors tab, users can still navigate to the documentation.

### Steps to reproduce the problem

On the [open-learning-exchange.github.io](https://open-learning-exchange.github.io/#!index.md) users can click on the Contributor>Takeout(Android) >TakeHome

### Screenshots

![image](https://user-images.githubusercontent.com/14159224/87555117-e095c980-c669-11ea-8a69-aa0848abc768.png)

![image](https://user-images.githubusercontent.com/14159224/87557086-569b3000-c66c-11ea-9b41-a7bb6a030b27.png)

### Proposed solution

Add a link info box at the top on the page explaining that the repo has been archived and direct users to [myPlanet.README.md](https://github.com/open-learning-exchange/myplanet) on page [rbts-takeout.md](https://open-learning-exchange.github.io/#!pages/robots/rbts-takeout.md) and [rbts-takehome.md](https://open-learning-exchange.github.io/#!./pages/robots/rbts-takehome.md) as sugested by @anastasia21112 and @avin-sharma in issure #3112.

**Comment by anastasia21112** [comment]
This is very much needed! When doing the PR make sure to close both this issue and avin's!

**Comment by robinGiri** [comment]
Fixes with #3131
