### ISSUE TITLE
Clarification on final picture/Survey in Nation.md

### ISSUE THREAD

**Issue by mepda** [open-learning-exchange/open-learning-exchange.github.io#313]
The final diagram of the nation step shows "release notes" which may not show up on all computers (it didn't on mine). Also it might be helpful to state that the Survey is sent out manually*.

*according to my understanding

**Comment by aberdean** [comment]
Good catch! That's a leftover of when the survey was sent out automatically.    
Let's not change the picture, just add an explanation.
