### ISSUE TITLE
Link for myPlanet app for Android devices. 

### ISSUE THREAD

**Issue by MosesBaleke** [open-learning-exchange/open-learning-exchange.github.io#3145]
The link in the image below does not work as indicated in the documentation (You can find myPlanet application in play store). 
I have also went to google play store but could not seem to find the right app (myPlanet).

![appurl](https://user-images.githubusercontent.com/47113095/154626702-2f0cbd7e-4a99-4f52-9fde-429520d93a27.PNG)

### When the link is clicked, the following page displays. 

![urlapp2](https://user-images.githubusercontent.com/47113095/154626718-f3ed80e5-1403-40b9-822f-f6e196a1c49c.PNG)
### Proposed solution
1. If the url changed, provide a valid URL that links to the registered app in google play store.
2. If the app is usually down momentarily, a note should be included in the documentation next to the link (to caution users about this issue).

**Comment by johnbeatrice** [comment]
This didn't work for me either. Good catch! Additionally, I could not find the myPlanet app even when I searched the name directly from the google play store.

**Comment by Kuljeet1998** [comment]
Can I be redirected to this page? Will be happy to take this up if still unresolved.

**Comment by xyb994** [comment]
The link is working as of now so I'm closing this issue.
