### ISSUE TITLE
Typo in link

### ISSUE THREAD

**Issue by johnbeatrice** [open-learning-exchange/open-learning-exchange.github.io#3147]
### Typo on page https://open-learning-exchange.github.io/#!pages/robots/rbts-myplanet.md

At the bottom of the page there are three links. The middle link reads "myPlanet Turtorial" when is should read "myPlanet Tutorial"

### Steps to reproduce the problem
Follow link above

### Screenshots

![typo](https://user-images.githubusercontent.com/81265448/155003490-9dd1327a-a1cd-401d-b690-5a1e5e0e0240.png)

### Proposed solution
The correct file can be edited to fix the typo.

**Comment by lmmrssa** [comment]
@johnbeatrice sure you can work on this one
