### ISSUE TITLE
Incorrect URL example on "Github and Markdown" page (Step 3) 

### ISSUE THREAD

**Issue by prmurphy** [open-learning-exchange/open-learning-exchange.github.io#315]
I noticed at the very end of the "Github and Markdown" page (here: http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md) that the URL example given is incorrect. Right now it has this <username<.github.io/pages/<username<.md 
but if I type that into my address bar using my user name then I get a page without any markdown applied. Take a look:
https://prmurphy.github.io/pages/prmurphy.md    

The correct URL would look like this:
https://prmurphy.github.io/#!pages/prmurphy.md

So the correct example URL should be as such:
<username<.github.io/#!pages/<username<.md

I think this change can avoid confusion for other interns going through the First Steps.

**Comment by aberdean** [comment]
Absolutely! Go ahead and post a pull request!

**Comment by aberdean** [comment]
PR #316 commit https://github.com/open-learning-exchange/open-learning-exchange.github.io/commit/4ab1c6d5041778bfbd0f93e137c2a3e078ab2dd5
