### ISSUE TITLE
Can add links in Troubleshooting in planet installation or separate sections for different OS

### ISSUE THREAD

**Issue by rheam97** [open-learning-exchange/open-learning-exchange.github.io#3151]
### Problem
The trouble shooting section is very dense with information about Windows, OS, and Ubuntu. I think that these can be divided as it is just before with bold headers so that it is easier to follow instructions.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="815" alt="Screen Shot 2022-02-28 at 1 26 45 PM" src="https://user-images.githubusercontent.com/94139372/156038110-e04512e8-437d-44ec-934f-7faa2f917549.png">

### Proposed solution

Use bold headers, more spacing, or nav link to redirect to correct OS instructions.

**Comment by lmmrssa** [comment]
@rheam97 sure you can put some highlight to make it clear that those errors are coming for specific platforms
