### ISSUE TITLE
Can add Git cheat sheet link to Git repositories in step 5

### ISSUE THREAD

**Issue by rheam97** [open-learning-exchange/open-learning-exchange.github.io#3152]
### Problem
I think there should be downloadable resources that interns can use so they dont have to sort endlessly through the pages of the steps. I believe that there can be either 1) downloadable resources added to the steps or 2) some of the content in the steps themselves can be added to downloadable pages for interns.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="791" alt="Screen Shot 2022-02-28 at 1 43 00 PM" src="https://user-images.githubusercontent.com/94139372/156040535-058cef07-7628-4d12-8382-cf19080f9b72.png">

### Proposed solution

Add downloadable links, create files with step content to be downloaded and kept for reference.

**Comment by lmmrssa** [comment]
@rheam97 these are contents which are being continuously improved by interns as they find improvement to be done. And this page serves as platform to learn and practice markdown along with learning about planet system. Its not the fixed document that is once created will work for long term without change. So creating downloadable document is not something we are looking at.

**Comment by rheam97** [comment]
got it @lmmrssa . I see now that there's a cheat sheet on step 3 i believe, so i will close this issue
