### ISSUE TITLE
Make the "right repository" more clear in step 6

### ISSUE THREAD

**Issue by rheam97** [open-learning-exchange/open-learning-exchange.github.io#3153]
### Problem
I saw that someone else was confused by this and I think it could be really easy to be confused with terms such as "upstream" etc. when working with git for the first time. I think it could be worth specifying that it is the open-learning-exchange repo and then in parentheses adding "upstream repository" with the link.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="797" alt="Screen Shot 2022-02-28 at 1 51 44 PM" src="https://user-images.githubusercontent.com/94139372/156041594-2ab54ac3-2a4c-4885-957c-cba6b58cccd2.png">

### Proposed solution

adding the name of the upstream repo for extra clarification

**Comment by lmmrssa** [comment]
@rheam97 purpose of the markdown is it make familiar with the technologies we use and terms for those technology. If you see adding repository name makes it clear you can create a PR for it so we can evaluate. But we don't want to remove upstream term.

**Comment by rheam97** [comment]
yes @lmmrssa, wasn't going to delete the upstream just add the name of the upstream repo
