### ISSUE TITLE
vi first steps pages could let you know what step you are currently on

### ISSUE THREAD

**Issue by johnbeatrice** [open-learning-exchange/open-learning-exchange.github.io#3155]
### Problem
I found myself getting confused and lost while going through the tutorials. Sometimes I couldn't remember if I was in the official step (i.e. "Step 6" ) or another tutorial from one of the many helpful links on each page. There is a link to the next step at the bottom of the page, which is great, but it can be a lot of scrolling, and still confusing because some steps have sub steps like "3.1", "3.2", "3.3" etc...

### Steps to reproduce the problem

N/A

### Screenshots

Here is an example from step 6 "github issues"

![Screenshot from 2022-03-01 17-44-22](https://user-images.githubusercontent.com/81265448/156263560-5b9a21f4-e8ab-4bc5-a6ac-738b0c0a2997.png)

### Proposed solution

There is a really nice menu on the left of the screen that is "fixed" perhaps the top segment or bottom segment, could show what section you are currently in ("Step 6" etc)  
I think this would help with overall navigation and ease of use. Interns can immediately understand where they are in relation to all 9 steps, especially because there are so many links that the potential intern is moving back and forth with.

**Comment by johnbeatrice** [comment]
@lmmrssa this is for step 8, per instructions, if this is something agreed upon to fix, can I work on it?

**Comment by rheam97** [comment]
@johnbeatrice you can work on this issue if you like, but the next step shows at the bottom.
