### ISSUE TITLE
grammatical error on virtual interns/First Steps/The big picture

### ISSUE THREAD

**Issue by johnbeatrice** [open-learning-exchange/open-learning-exchange.github.io#3156]
### Problem
Under the first section "The big picture" the last line of the second (middle) paragraph reads:
"Our current projects could be found here."

which is grammatically incorrect

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2022-03-01 18-13-29](https://user-images.githubusercontent.com/81265448/156264984-0bbf94f5-5ac0-47cf-b8b9-041f0302a396.png)

### Proposed solution

Fix the error to instead read: 

"Our current projects can be found here." (CAN instead of COULD).

**Comment by johnbeatrice** [comment]
@lmmrssa If approved, can I work on this issue?

**Comment by rheam97** [comment]
@johnbeatrice go ahead
