### ISSUE TITLE
typo on contributers/raspberry pi/So what is the rasberry pi?/Your First Steps

### ISSUE THREAD

**Issue by johnbeatrice** [open-learning-exchange/open-learning-exchange.github.io#3157]
### Problem

Typo on the raspberry pi page.
Heading "Your First Steps" currently reads "Your Fist Steps".

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2022-03-01 18-21-51](https://user-images.githubusercontent.com/81265448/156265597-64def4e6-8940-433f-ab0a-46b0e9f67db0.png)

### Proposed solution

Change typo from "Your Fist Steps" to "Your First Steps"  ("FIRST" instead of "FIST")

**Comment by johnbeatrice** [comment]
@lmmrssa if approved, can I work on this issue?

**Comment by rheam97** [comment]
@johnbeatrice go ahead and fix this
