### ISSUE TITLE
Add a config file in the .github package to file different issues 

### ISSUE THREAD

**Issue by CalebKL** [open-learning-exchange/open-learning-exchange.github.io#3191]
### Problem
We can add a .config.yml file such on the .github package, such that someone can have different options when filling an issue. Example: 
1. File a bug 
2. Feature Request
3. Help needed(This we can redirected the OLE support)

This is a suggestion and I am open to hear your **thoughts**

**Comment by xyb994** [comment]
Thank you, this is closed by #3299
