### ISSUE TITLE
Sections below Exam Section Not Highlighted in Planet User Manual

### ISSUE THREAD

**Issue by animeshsingh75** [open-learning-exchange/open-learning-exchange.github.io#3211]
### Problem
In the Planet User Manual, under the Manual section, the sections below Exams section is not highlighted in bold when selected.

### Steps to reproduce the problem
- Go to this https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md page
- Click on the any section below Exam option.
- Observe that the section is not highlighted in bold when selected.

### Screenshots
<img width="1300" alt="Screenshot 2024-05-07 at 11 41 06 PM" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/51756525/a4deb55d-5976-4db2-85cb-241b8c03e498">

### Proposed solution
The `**This portion needs to be worked on** ` might be causing some issues so might try `<b>` tag instead

**Comment by xyb994** [comment]
This is likely a MDwiki issues though. Check one of their official docs page https://dynalon.github.io/mdwiki/#!download.md

**Comment by axzhir** [comment]
Just wanted to clarify on this issue. I feel like for the exams portion, that should be removed completely and added later if completed. Keeping it there would probably leave some people confused.
