### ISSUE TITLE
"Return to First Steps" Missing in Step 3 - myPlanet and Android Studio

### ISSUE THREAD

**Issue by animeshsingh75** [open-learning-exchange/open-learning-exchange.github.io#3212]
### Problem
In Step 3 of the myPlanet and Android Studio instructions, the "Return to First Steps" navigation option is missing at the end of the page. This issue disrupts the navigation experience and prevents users from easily returning to the first steps page and it inconsistent with rest of the pages

### Steps to reproduce the problem
https://open-learning-exchange.github.io/#!./pages/mi/mi-myplanet-and-android-studio.md

### Screenshots
<img width="1403" alt="image" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/51756525/33a61217-a1c2-4fd8-b939-d3bb567f4114">

### Proposed solution
- Add a navigation link to the "Return to First Steps" option at the end of Step 3 in the myPlanet and Android Studio page.

**Comment by xyb994** [comment]
Sure, go ahead and create a pull request for it
