### ISSUE TITLE
FAQ Link on Steps Page Should Open in New Tab or Have "Return to First Steps"

### ISSUE THREAD

**Issue by animeshsingh75** [open-learning-exchange/open-learning-exchange.github.io#3213]
### Problem
On the Steps page the FAQ link should either:
Open in a new tab to provide seamless navigation, or Include a "Return to First Steps" navigation option at the bottom of the FAQ section to help users return easily.

### Steps to reproduce the problem

- https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md go to this page
- Find and click the FAQ link.
- Observe that the link navigates away from the Steps page without opening in a new tab or providing a "Return to First Steps" option.

### Screenshots
N/A

### Proposed solution

- Open FAQ Link in a New Tab by adding target =_blank
- Add a "Return to First Steps" link at the bottom of the FAQ section

**Comment by xyb994** [comment]
Not sure if solution 1 is achievable without adding html code to the markdown file.
Please go ahead with solution 2!
