### ISSUE TITLE
Tracking Progress Section Dialog Box Should Open Empty Instead of Showing "dogi" Placeholder

### ISSUE THREAD

**Issue by animeshsingh75** [open-learning-exchange/open-learning-exchange.github.io#3214]
### Problem
In the "Tracking Progress" section, when the "Track Progress" button is clicked, a dialog box opens with "dogi" as the placeholder. Instead, the dialog box should be empty to provide a clean slate for user input.

### Steps to reproduce the problem
https://open-learning-exchange.github.io/#!./pages/mi/../track-first-steps-progress.md

### Screenshots
![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/51756525/a6508d5d-84f1-44fc-9423-f580fec907d8)

### Proposed solution

- Initialize the user variable as this  ` var user = "";` instead of this  ` var user = "dogi";` in track-first-steps-progress.md

**Comment by dogi** [comment]
@animeshsingh75 :)
ya and no
---
I think ideally we would be able to detect your github username over the browser and fill that one in
that could work if you are logged into github
if not I want dogi there so people see how it works by one click

**Comment by xyb994** [comment]
> the dialog box should be empty to provide a clean slate for user input

@animeshsingh75 Is `dogi` in the dialog box not already selected by default for you? I'm seeing it preselected and easy to type and replace with Chrome, Firefox, and Safari browser.
