### ISSUE TITLE
mi step 2: add instruction to enroll in beta testing

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#3216]
# Problem

We'd like to ask our prospective mobile interns to enroll in beta testing for myPlanet app in step 2.

Join on Android
Testers can join your test using Google Play on Android
https://play.google.com/store/apps/details?id=org.ole.planet.myplanet

Join on the web
Testers can join your test on the web
https://play.google.com/apps/testing/org.ole.planet.myplanet

**Comment by animeshsingh75** [comment]
Can I pick up this issue?

**Comment by xyb994** [comment]
> Can I pick up this issue?

Yes!

**Comment by axzhir** [comment]
Am I also able to pick up on this issue as well?
