### ISSUE TITLE
mi step 2: spend some time with the app

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#3219]
In mi step 2, we'd like to ask prospective mobile interns to spend some time with the app and take screenshots, ask them try to crash the app by clicking around.

To be able to explore around the app, they need to sync with the default server config and create a user like in https://open-learning-exchange.github.io/#!./pages/mi/mi-step4.md

At the end, update us in discord with a message "on step 2, spent xxx min/hour and crashed it when I xxx" or "did not crash it after spending 15min..."

**Comment by rlam20** [comment]
For clarification, we could also ask the prospective interns to screen record or document each step they took before the crash. We should also see if the prospective interns can replicate the issue. This process might help determine the reason for the crash if the initial hypothesis of why the app crashed is incorrect.

**Comment by ewhang5** [comment]
I think @rlam20 suggestion of possibly using videos of crashes is a good idea. I also think that asking the potential interns to come up with a reasoning/solution for the crash would be interesting. As this is their first time exploring the app, their idea does not need to work or be correct, but I think this would be a good way to see problem solving abilities of the potential interns. In addition, I think that this would push the potential interns to think about how the app may be working.

**Comment by priya0030** [comment]
Even if the app did not crash, interns should feel free to suggest any modifications or point out any mistakes they noticed that should be changed. Interns can provide detailed feedback on their experience with the app. This feedback will help us understand how familiar they are with the app and whether they spent sufficient time exploring it.
