### ISSUE TITLE
Incorrect port for connecting to vi.ole.org

### ISSUE THREAD

**Issue by mepda** [open-learning-exchange/open-learning-exchange.github.io#322]
On the nation.md page when you go to click the link to vi.ole.org, it connects to: "http://vi.ole.org:5999/apps/_design/bell/MyApp/index.html"
Shouldn't this be "http://vi.ole.org:5985/apps/_design/bell/MyApp/index.html"?

**Comment by dogi** [comment]
thanks

I broke that 5 days ago
as part of our overhauling process

`http://vi.ole.org` is now redirecting to the wrong place
so now you need to use the full url port and subdirectories
`http://vi.ole.org:5985/apps/_design/bell/MyApp/index.html`

@mepda go for this PR
