### ISSUE TITLE
Some steps show examples in embedded images while some don't.

### ISSUE THREAD

**Issue by axzhir** [open-learning-exchange/open-learning-exchange.github.io#3224]
### Problem

Some steps given show images of examples while some steps don't.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="717" alt="Screenshot 2024-05-08 at 20 50 31" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/550822b2-48a3-4ef3-8c26-072a5f128633">

### Proposed solution

I believe that for the steps, the examples should be shown a little after the description is written. This is so that the user who's reading can see what they need to do immediately, instead of having to open it in another tab. (This can also prevent the user from accidentally skipping the highlighted link to the examples).

This could also be prevented by making each image for each step have a link directing to another tab. Either solution would work fine.

**Comment by xyb994** [comment]
closing this as the branch creation confusion was addressed in #3290
