### ISSUE TITLE
Step 8 Issue II: Tutorial Images have the potential of becoming tutorial videos.

### ISSUE THREAD

**Issue by axzhir** [open-learning-exchange/open-learning-exchange.github.io#3226]
### Problem

There are tutorial images on each step that show the user how to do something. Even though they're already very useful, turning them into tutorial videos would help even more

### Steps to reproduce the problem

N/A

### Screenshots

<img width="708" alt="Screenshot 2024-05-09 at 20 00 17" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/fc62b36c-b7f7-4aa1-90bf-af91da3b9c5a">

<img width="563" alt="Screenshot 2024-05-09 at 20 00 48" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/2ae0391f-864d-47db-b689-cb755bf4c4b3">

### Proposed solution

We can have someone record the tutorial videos for each step and replace the images with the tutorial videos. This will allow more space onto the site, and it would have users go back a bit to look at what they've missed. (I can make those videos.)

**Comment by xyb994** [comment]
Good idea on adding videos and reducing images. This would reduce clutter and make the steps easier to follow without being too detailed on the texts.

Did you had trouble following the instruction to connect myPlanet to Planet? I understand the screenshot is outdated and needs to be updated. I feel the steps in strait forward currently so it probably does not warrant a video yet.

Although I agree that having a video for Step 8 would be beneficial, it's currently packed with content, and some cleanup might be necessary. My suggestion is to tackle this as your final pull request. This way, you can get a feel for the flow and it'll likely result in a smoother video recording, requiring less editing.

**Comment by Kuljeet1998** [comment]
Since, I went through the steps just a few minutes back, I didn't face any issues as such. But a video to demonstrate would be a good way to interact with new users.
