### ISSUE TITLE
Step 8 Issue III: FAQ Page should be emphasized on the left side section on the first steps page.

### ISSUE THREAD

**Issue by axzhir** [open-learning-exchange/open-learning-exchange.github.io#3227]
### Problem

The FAQ Page is an important page for anyone who has a question or is curious about something related to OLE. The FAQ page is seen as just a highlighted link in the "The Steps" section.

### Steps to reproduce the problem

Scroll to "The Steps" and read/skim through it until you see "FAQ Page" highlighted

### Screenshots

<img width="747" alt="Screenshot 2024-05-09 at 20 19 18" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/992991fe-3162-45f1-809f-034f785fb438">

<img width="541" alt="Screenshot 2024-05-09 at 20 19 27" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/89a13eae-4aec-47b8-9730-daa82af6addc">

### Proposed solution

The "FAQ Page" should have its own separate section on the first steps page. You can write "FAQ - Frequently Asked Questions" In between the steps section and the "step 0" section. (Where this screenshot shows)
<img width="547" alt="Screenshot 2024-05-09 at 20 20 35" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/dcf3856d-0699-421b-8f75-7da78d977803">

We can also add the FAQ Page into this column where each step is emphasized. This is so that it could be easily accessible.
<img width="189" alt="Screenshot 2024-05-09 at 20 21 27" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/90860899-6f74-4e01-93bf-e6a9fd7c6e47">

**Comment by xyb994** [comment]
- Yes, the FAQ page could probably be highlighted a little more on the mi-10-steps.md page.
- Please note that the page menu on the left is generated by MDwiki for anything H2 in the page with a `##`.

Please go ahead and add "FAQ - Frequently Asked Questions" before "step 0". Use the following text and remove the relevant text from "The Steps" so it's not repetitive:
```
Our FAQ page is a comprehensive resource containing answers to common questions about the internship and First Steps. It also features additional helpful links and video tutorials aimed at familiarizing you with the tools and languages integral to our work.

If you have general internship inquiries and can't find the information you need on the FAQ page, please don't hesitate to reach out to us via Discord. Try to avoid DMs as others might have the same question!

For technical questions not covered in the FAQ, in addition to contacting us on Discord, Google and Stack Exchange serve as excellent supplementary resources to explore.
```
