### ISSUE TITLE
mi step 5: Dead link to the First Steps at the bottom of page. 

### ISSUE THREAD

**Issue by rlam20** [open-learning-exchange/open-learning-exchange.github.io#3234]
### Problem
When on step 5, if you scroll to the bottom of the page and click on the link to return to the first steps, 'Return to First Steps,' you are taken to a page that does not exist. 

### Steps to reproduce the problem
Go to Step 5 on the First Steps page, scroll to the bottom, and click on the link in the following text:  'Return to First Steps'
https://open-learning-exchange.github.io/#!./pages/mi/mi-github-and-repositories.md

### Screenshots

Navigate to Step 5 on the First Steps page for Mobile Interns 
![Screenshot 2024-05-16 212536](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/52076121/7db71076-6908-4c97-98b0-289719fd4c9e)
Scroll to the bottom until you reach the 'useful links' category
Click on the link that says 'Return to First Steps' at the bottom of the page 
![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/52076121/cd79b0d6-4937-483f-9a5a-9c7b2b57fdcb)

### Proposed solution
Replace the link that 'First Steps' takes you to and update it to the actual First Steps link,

**Comment by xyb994** [comment]
Thanks for catching this!
