### ISSUE TITLE
Step 6 - Dead links and/or needs clarification on Translation Support page

### ISSUE THREAD

**Issue by strawberrybread** [open-learning-exchange/open-learning-exchange.github.io#3241]
### Problem
When on the *Introduction* page under the **Translators** tab, the links to the Crowdin translation projects are dead or requires permission to view.

### Steps to reproduce the problem
Navigate to the **Translators** tab and select *Introduction*. Scroll to the bottom of the page and click the "Planet", "Take Home", and "Remote" links under *Start Translating*.

### Screenshots
![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/112584985/3db16982-c991-4c0e-a8c7-d9847deadbc7)

From the description on this page, it gives me the impression that the links should be accessible to anyone that would like to view it.

![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/112584985/f02aa5e9-3d34-42d3-a8ce-5748f1dc94d6)

When clicking on any of the Crowdin links, this is what shows on the page.

### Proposed solution

1. If the projects no longer exist or have been moved to a different location, we should update the page by taking down the links and replacing with the proper links if applicable.
2. If special access is required for viewing, this should be made more clear on the page and an option for requesting access should be added in. If the requirement for special access was a mistake, this should be remedied to be open to the public for viewing.

**Comment by xyb994** [comment]
@dogi Should we move everything under Translators navigation under Archives?

**Comment by xyb994** [comment]
@dogi: Good catch on this. Please limit the issues raised to pages about mobile interns, in other words, things are are linked from mi-10-steps.md page.
I will create an issue for this.

It looks like removing `/invite` from the urls would fix the issue. Please go ahead and create a pull request for it.
