### ISSUE TITLE
Dropdown links for "Translators" redirect user to error page

### ISSUE THREAD

**Issue by ewhang5** [open-learning-exchange/open-learning-exchange.github.io#3251]
### Problem

The dropdown links (Planet, Take Home, Remote) under "Translators" do not work.

### Steps to reproduce the problem

Click one of the dropdown options under "Translators".

### Screenshots

<img width="1718" alt="Screenshot 2024-05-21 at 10 40 05 AM" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/59347000/731bae54-6143-4faf-bc61-f074ffaed5b4">

### Proposed solution

Check the redirect link and confirm that we are redirecting to the intended URL.

**Comment by xyb994** [comment]
duplicate of #3241
