### ISSUE TITLE
Adding discord channel invite link to the "Helpful Links" section of FAQ

### ISSUE THREAD

**Issue by ewhang5** [open-learning-exchange/open-learning-exchange.github.io#3262]
### Problem

I think it would be nice to have the discord channel invite link in the "Helpful Links" section of FAQ. Though it may not be used that frequently, an invite link to the discord channel is really important and could be added to this section just in case.

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Add in a section for the discord channel link and possibly also discord installation links.

**Comment by xyb994** [comment]
A little background story: Our current process for inviting mobile virtual interns involves them filling out a Google form. Upon submission, they see a special invitation link. When they join Discord through this link, a bot automatically assigns them the vi-mobile role, granting access to the lagrangelounge channel.

Although there are two Discord invitation links in mi-faq.md, they are different from the one provided after the Google form submission. We should probably maintain this distinction to ensure that only individuals who have been invited and completed the Google form can join the lagrangelounge channel for prospective mobile interns.

Finding Discord installation links is straightforward, so it's not a major concern. However, we can add the link (https://discord.com/download) to Step 0, item 3 (Discord installed), as it won't take up any extra space.

**Comment by ewhang5** [comment]
Okay sounds good! I will close this issue down then since that change seems like a repeat of [this issue](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/3217).
