### ISSUE TITLE
Adding information on expectations for interns

### ISSUE THREAD

**Issue by ewhang5** [open-learning-exchange/open-learning-exchange.github.io#3263]
### Problem

As a potential intern, it is hard to know what the company is looking for in terms of our work during the First Steps. Providing expectations of how a successful potential intern would go about completing the First Steps would provide guidance for potential interns' works. It also allows them to produce work that aligns with what the company is looking for.

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Add information about expectations of a successful potential intern either in FAQ or early in the First Steps page.

**Comment by xyb994** [comment]
We do have this paragraph in `## The Steps`
> These steps may seem simple, but we expect high-quality work, which might require extra time. We want to see that you can use, or learn to use, these tools effectively — including writing clear GitHub issues, creating proper pull requests, navigating Planet, using Vagrant and Docker, etc. Just passively following the steps is the bare minimum; instead, aim to impress us with excellent GitHub etiquette and well-structured Markdown.

Though `using Vagrant and Docker` could probably be removed, and we could expand the list to better reflect what's currently invilved in the mi first steps.

**Comment by ewhang5** [comment]
Oh okay! This does address the issue. Thanks for clearing that up!

**Comment by xyb994** [comment]
You can still work on this though, perhaps we can bold the paragraph? Add a FAQ question and copy most of that paragraph over?

**Comment by ewhang5** [comment]
> You can still work on this though. Perhaps we can bold the paragraph? Move it to the end of `## The Steps` and Give it a h4 header `#### `? Add a FAQ question and copy most of that paragraph over? What do you think would be the best?

I think that bolding it would be great! I think keeping the FAQ concise might be best, so maybe it wouldn't be the best idea to add it there.
