### ISSUE TITLE
Add "verify email" to prerequisites on GitHub and Markdown page

### ISSUE THREAD

**Issue by prmurphy** [open-learning-exchange/open-learning-exchange.github.io#327]
You need to verify your email as a prerequisite, otherwise you wont be able to rename you forked repository. I ran into this problem and it took me awhile to realize what the problem was. I think something as simple as
"Already created Username on Github or Set up Github account with verified email address."
would help other avoid this problem.

**Comment by aberdean** [comment]
Sure! That's a great idea!
