### ISSUE TITLE
Step 8 - Add images and/or videos to Step 3 myPlanet and Android Studio

### ISSUE THREAD

**Issue by strawberrybread** [open-learning-exchange/open-learning-exchange.github.io#3275]
### Problem
For users who are unfamiliar with Android Studio, they might struggle to navigate it without images to images to help show what to click.

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Add in images for parts 4-7 to show how to set up an emulator, select the run configuration, and what the emulator should look like after it starts running.

**Comment by xyb994** [comment]
Good point, go ahead and create a pull request for this!
