### ISSUE TITLE
Step 8 - Add external links to FAQ #12

### ISSUE THREAD

**Issue by strawberrybread** [open-learning-exchange/open-learning-exchange.github.io#3276]
### Problem
The instructions use only a few sentences to describe how to get to bios and turn on virtualization. This can be very confusing for those who have never used bios. The location to enable this can also differ depending on the make of the CPU - Intel/AMD.

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/112584985/f5300f53-7164-4514-a37f-050b9331b8d1)

### Proposed solution
Add external links for detailed instructions on how to turn virtualization on for Intel and AMD.

**Comment by xyb994** [comment]
mi-faq.me is copied over from vi-faq.md. While we currently do not have any steps involving vagrant for mobile intern, we might in the future.

Go ahead and add some relevant info and link about AMD CPU. Please keep in mind that we want to keep things concise and we expect prospective virtual interns able to resolve issues they encounter with online searches.
