### ISSUE TITLE
Add hyperlinks to "Summary of Steps" on gitandrepositories.md

### ISSUE THREAD

**Issue by prmurphy** [open-learning-exchange/open-learning-exchange.github.io#328]
I noticed that headings in markdown actually get links, so you can link to a heading and it will show up at the top of your page. I think gitandrepositories.md would be easier to navigate if all of the steps under "start here" were hyperlinks to their respected sections. I am specifically talking about these.

Clone your git repository username.github.io
Read explanation to understand repositories and syncing process
Configuring a remote for fork
Syncing a fork

on the last one for example, the markdown would look like this:
* [Syncing a fork](gitandrepositories.md#Syncing_a_fork)  

> * [Syncing a fork](gitandrepositories.md#Syncing_a_fork)

**Comment by aberdean** [comment]
I totally agree. Just one thing. We have two pages with the same "start here" setup, githubandmarkdown.md and gitandrepositories.md. So, it would be awesome to add the links to both pages for consistency.
