### ISSUE TITLE
Step - 3 add Update Android Studio (if already installed)

### ISSUE THREAD

**Issue by priya0030** [open-learning-exchange/open-learning-exchange.github.io#3285]
### Problem
Update Android Studio (if already installed) to latest version as the older one is not supporting.

### Proposed solution
Open Android Studio.
Navigate to Help -> Check for Updates. Android Studio will check for any available updates.
If updates are found, follow the prompts to download and install them. This ensures you have the latest version with all the new features, bug fixes, and compatibility improvements.

**Comment by xyb994** [comment]
Good point about the reminder to update Android Studio if already installed. Go ahead and create a pull request for it! Please keep it short and concise though, we can assume and expect prospective virtual interns know how to update it.

**Comment by iAlphaKing** [comment]
Older versions of Android Studio can cause the gradle build to fail. Interns can be suggested to update the studio if their build fails. If the issue is not being resolved still, re-installing Android Studio will fix the issue.
