### ISSUE TITLE
Markdown for new interns

### ISSUE THREAD

**Issue by cosmicvista** [open-learning-exchange/open-learning-exchange.github.io#329]
I think that the Markdown is not easily enough understood by new interns. Even after completing the markdown page, I am still not sure how and why it is used. Many people who are visual learner would gain the benefit of learning markdown by watching a markdown tutorial, only 12 minutes, at:

https://www.youtube.com/watch?v=_gknWWa2OF0

After watching this, markdown is a lot clearer to me, and I'm sure would be for new interns as well.

**Comment by prmurphy** [comment]
Thats a good video, I think most of the information can be found on the site linked from the markdown https://guides.github.com/features/mastering-markdown/ although like you said some people are more visual learners so a video could be a good addition

**Comment by aberdean** [comment]
Probably, you guys didn't notice, but there is an entire YouTube video-series tutorial on Markdown linked from the FAQ page.

**Comment by hikaruit15** [comment]
I think learning by doing is a good way. 
[http://www.markdowntutorial.com/lesson/1/] (Markdown Tutorial)
This website helps us learn interactively.

**Comment by aberdean** [comment]
@hikaruit15, that's a very nice tutorial! Please, submit a pull request to add the link to the faq.md page.
