### ISSUE TITLE
Outdated and unnecessary images - 'Create a Pull Request'

### ISSUE THREAD

**Issue by Kuljeet1998** [open-learning-exchange/open-learning-exchange.github.io#3307]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document.
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-github-issues.md

### Problem

The images and description seems outdated. The images seem unnecessary as the steps are self explanatory. 

### Screenshots (when necessary)

![Screenshot 2024-06-20 at 10 25 14 PM](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/47841620/fc04162d-b82e-40a4-8eed-23a7441ff6a2)

### Proposed solution(s)

- Generalize the steps (eg. Instead of `Click the blue "Compare & pull request" button.` -> `Click the "Compare & pull request" button.` ) (removed keyword 'blue' so that if color changes in future (green now) it still holds true).
- Get rid of images as it can get outdated over time (some of them alr are)

**Comment by xyb994** [comment]
> * Generalize the steps (eg. Instead of `Click the blue "Compare & pull request" button.` -> `Click the "Compare & pull request" button.` ) (removed keyword 'blue' so that if color changes in future (green now) it still holds true).

The screenshot was captured recently by a prospective virtual intern. I initially thought it appeared blue in a forked repo, but upon further investigation, it seems the color depends on the user's theme preference. Therefore, removing the color reference is a good idea.
