### ISSUE TITLE
Note to rotate device to view the hidden tabs - Home, Library, Courses in mobile app.

### ISSUE THREAD

**Issue by Kuljeet1998** [open-learning-exchange/open-learning-exchange.github.io#3308]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document.
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-myplanet-course.md

### Problem

During exploring the app and following the steps from the document, it took me a while to figure out where the Courses tab was. I kept landing on 'My courses' instead of all 'Courses'. Then after rotating device to landscape it popped up and I was able to proceed further. 

### Screenshots (when necessary)

![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/47841620/93222952-b3e2-4853-a724-02f07d093800)

![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/47841620/2758aea4-b3a1-483f-9c68-a1473960afc3)

### Proposed solution(s)

Adding a Note asking user to shift to landscape to find the tabs seems like a good idea

**Comment by Okuro3499** [comment]
@Kuljeet1998 on small screens if you click this icon you get a menu with `courses` included not necessary to rotate your screen
![imageedit_4_4295137073](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/64019708/f18c345c-d3a0-437a-9d0b-002f1017267d)

![Screenshot_20240621_123930](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/64019708/a6bb9848-3855-497c-abd2-8409d4c39287)
