### ISSUE TITLE
Outdated picture in Step 3 - myPlanet and Android Studio

### ISSUE THREAD

**Issue by iAlphaKing** [open-learning-exchange/open-learning-exchange.github.io#3317]
### Please verify the following:

- [x] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document.
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-myplanet-and-android-studio.md

### Problem

In Step 3 - myPlanet and Android Studio, the picture associated with task 5 is outdated and misleading. There is a change in position for the run option for 'app' button.

### Proposed solution(s)

Upload a new picture to associate with the task 5. The picture can be wider to cover more screen while highlighting the approx position of the 'app' button.
<img width="811" alt="Screenshot 2024-07-03 at 1 09 12 AM" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/112287182/0bf0c81f-b8fe-45e2-8d6d-31710379a0d0">

**Comment by xyb994** [comment]
Thank you for raising this issue @iAlphaKing. The screenshot was added fairly recently in #3282. I don't believe your Android Studio layout is the typical default setting (or it's outdated?). However, circling out the run configuration is a good idea. Go ahead and create a pull request highlighting it on the original screenshot.

**Comment by iAlphaKing** [comment]
@xyb994 I have just updated my Android Studio so I'm fairly certain that there's some cosmetic changes. Also my attached screenshot covers more screen area which can help new interns locate the button with easy. I can also update on the older one though. Please suggest.

**Comment by xyb994** [comment]
Sure, go ahead and use the new one. Please keep the image height fairly short so it does not take as much space in the page.  You'd need to add an empty line before where we link the image to make it not showing up as in-line image.
