### ISSUE TITLE
Learning objectives states on index.md

### ISSUE THREAD

**Issue by mepda** [open-learning-exchange/open-learning-exchange.github.io#332]
The main objectives of the pre-internship trials are 
1) Learn Markdown
2) Setup Vagrant
3) Learn Github
4) Setup / Learn Vagrant BeLLs community/nation

Should we explicitly state this in index.md as learning goals? Might make it easier for people to keep track of what they've learned, and what's left to come.

**Comment by mepda** [comment]
hm, I'm looking over the FAQ, and I guess these steps can be inferred... just my teachers instinct kicking in thinking learning objectives should always be stated at the start of a lesson :)

**Comment by aberdean** [comment]
I'm not sure if many people even read index.md. Perhaps, firststeps.md would be more appropriate.
Point 2 is no longer relevant to Windows users, and soon enough it wouldn't be for the others, either. So, I would avoid it. Unless you change it into learn about Vagrant, which would still be relevant.

**Comment by mepda** [comment]
oh jeez, that's right about point 2

**Comment by waryhermit** [comment]
Personally I found the first paragraph of `firststeps.md` to explain what you are expected to learn and accomplish. Perhaps it just needs to be made more readable or use a bullet point or something?

**Comment by waryhermit** [comment]
@dogi I think `index.md` is good how it is, and the first paragraph in `firststeps.md` explains what you will learn well enough. I put stuff in bold to explain what I mean:

> Welcome to the first steps for becoming an OLE Virtual Intern! We treat these first steps as a vetting process to prove that you can follow simple steps before you can progress to working on harder projects in bigger teams. Because these steps are simple, we expect high quality work, which may take a longer time. **We want to see that you are capable of using or learning how to use these tools (writing good GitHub issues, creating pull requests, navigating the BeLL, etc.).** These steps may seem easy, but we want you to impress us with **good GitHub etiquette and quality Markdown.** The bare minimum would be to just passively follow the steps; you should do further reading about the tools/languages we use so you can further your understanding and relieve confusion if you're unclear about how something works. 

@dogi Feel free to reopen if you feel otherwise.
