### ISSUE TITLE
mi-github-and-markdown & mi-github-issues: redundant instructions

### ISSUE THREAD

**Issue by AdhamElAsfar99** [open-learning-exchange/open-learning-exchange.github.io#3326]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document.
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

Provided below

### Problem

The **Open/Create Pull Request** and **Delete Branch** sections in Step 1 ([Markdown & Forking Workflow](https://open-learning-exchange.github.io/#!./pages/mi/mi-github-and-markdown.md)) 
and Step 6 ([GitHub Issues Tutorial](https://open-learning-exchange.github.io/#!./pages/mi/mi-github-issues.md)) present the same instructions, yet Step 6 has more content and details.  For example,

### Open Pull Request

The screenshot in Step 6 has the pull request template shown while the one in Step 1 doesn't have it, yet I found that template when I was creating a pull request in Step 1, which left me thinking whether I was on the right step or not. 

### Delete Branch

This section in Step 6 has the content displayed in Step 1 with some content added to it. 

### Screenshots (when necessary)

This is the Image provided in the **Open Pull Request** Section in Step 1

![image](https://github.com/user-attachments/assets/51de50bf-eedc-49a7-b6bd-a9a5fb295e90)

This is the Image provided in the **Open Pull Request** Section in Step 6

![image](https://github.com/user-attachments/assets/df246072-d757-4959-8622-9e5e4904df4a)

This is the **Delete Branch** section in Step 1

![image](https://github.com/user-attachments/assets/0806e216-85ba-4203-843c-e9698d1ae323)

This is the **Delete Branch** Section in Step 6

![image](https://github.com/user-attachments/assets/5cc16d06-8857-4df6-bffc-7db4107bf2f5)

### Proposed solution(s)

- Combining Both **Create Pull Request** and **Delete Branch** sections into one section for each that has the same general content and providing the link for it in both Steps 1 and 6.  
- Putting any additional content based on each step right after the link.

**Comment by xyb994** [comment]
Good point, also thank you for pointing out the pull request screenshot is confusing in step 1. Go ahead and create a pull request for it!
