### ISSUE TITLE
mi-github-issues.md: confusing statement

### ISSUE THREAD

**Issue by AdhamElAsfar99** [open-learning-exchange/open-learning-exchange.github.io#3332]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document.
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-github-issues.md

### Problem

In the "Create a New Branch" section, there is a statement saying that we should ignore the angle brackets while writing our branch name; however, angle brackets were never used in the text until later. I believe this could be a typo, but it can be confusing.

### Screenshots (when necessary)

![image](https://github.com/user-attachments/assets/bab6ae31-0b8a-472f-bec1-04246ca320fe)

### Proposed solution(s)

- Fix the typo by adding angle brackets where they should be.
- Adding a small note on the use of angle brackets as place holders in general to clear any further confusion that could happen.

**Comment by xyb994** [comment]
Go ahead and create a pull request for it!
