### ISSUE TITLE
mi-github-issues.md: outdated link

### ISSUE THREAD

**Issue by AdhamElAsfar99** [open-learning-exchange/open-learning-exchange.github.io#3336]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document.
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-github-issues.md

### Problem

- The link provided in section **6.2. Raw.githack** leads to a page different from the one displayed in the picture below it. This will lead the interns to a different page on their forked repository and they won't be able to view the changes they made. 
- The page that the link leads to is under the **Virtual Interns** tap instead of the **Mobile Interns** tap.

### Screenshots (when necessary)

![image](https://github.com/user-attachments/assets/bbcdf210-7909-4b47-8303-aeaf978eafbe)

- **This is the page the link leads to:**

![image](https://github.com/user-attachments/assets/bbc49498-f919-4227-8487-a11439a65e77)

### Proposed solution(s)

Updating the links by changing the last part of the hyperlink from `vi/vi-first-steps.md` to `mi/mi-10-steps.md`.

**Comment by xyb994** [comment]
Nice catch, go ahead and create a pull request for it!
