### ISSUE TITLE
Content Population on myPlanet page Sign In/ Become a Member

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/open-learning-exchange.github.io#3352]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md

### Problem

Empty Sign In/ Member section

## Creating an Account / Becoming a Member

To create an account or become a member, follow these steps:

1. **Click on the "Become a Member" button**.
   
2. A form will pop up for you to enter the following details:
   - **Username**
   - **Password**
   - **First Name**
   - **Last Name**
   - **Email Address**
   - **Preferred Language**
   - **Phone Number**
   - **Birth Date**
   - **Gender**
   - **Education Level**

3. After entering all the required information, your user account will be created.

Make sure to fill in all the fields accurately to complete the registration process.

## Signing Into the App

To sign in using an existing account, follow these steps:

1. **Check the right section of the login page**:
   - This section displays the recently used users.

2. **Tap on your user**:
   - If your user is displayed in the list of recent users, tapping on it will sign you in automatically.

3. **If no user is displayed in the recent users**:
   - Enter your **Username** and **Password** into the appropriate fields.

4. **Sign In**:
   - After entering your credentials, you will be signed in to the app.

Ensure you enter the correct username and password to access your account.

**Comment by xyb994** [comment]
Looks good, go ahead and create a pull request for it!
