### ISSUE TITLE
Add Definitions of terms push and fetch under " Explanation About Repositories and Syncing Process"

### ISSUE THREAD

**Issue by Gavinp14** [open-learning-exchange/open-learning-exchange.github.io#3369]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-github-and-repositories.md

### Problem

I noticed that there is a photo that outlines how to sync a fork. There are no definitions for the words of "fetch" and "push"

### Screenshots (when necessary)

<img width="599" alt="updatedIssue" src="https://github.com/user-attachments/assets/4a2a1be8-ab5b-4f68-bfce-23732dba6c33">

### Proposed solution(s)

I feel adding what these terms mean before presenting the photo of how the syncing process works will give the intern a better idea as to what fetch does and what push is actually doing

**Comment by xyb994** [comment]
Go ahead and create a pull request for it!
