### ISSUE TITLE
Wording in Step 8 is unclear

### ISSUE THREAD

**Issue by prmurphy** [open-learning-exchange/open-learning-exchange.github.io#337]
I think it should be made clear in step 8 that you need to make 3 different pull requests. Step 8 currently says "Please create three issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo" I think it could be changed to something like "Please create three issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests." To make it clearer that you shouldn't fix all of the issues with one pull request.

**Comment by aberdean** [comment]
@prmurphy You're totally right! I didn't even notice that the wording was so unclear. Please, go ahead and change it.
