### ISSUE TITLE
Link to Discord Channel in Step 10

### ISSUE THREAD

**Issue by Gavinp14** [open-learning-exchange/open-learning-exchange.github.io#3375]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md#Step_10_-_Be_Part_of_the_Team

### Problem

In the paragraph in step 10, there is no link to the software engineering virtual intern channel on the discord like it has in the other steps. 

### Screenshots (when necessary)

<img width="610" alt="issue3" src="https://github.com/user-attachments/assets/7761f66c-b659-4e11-b82f-cfdff95aa56f">

### Proposed solution(s)

Just replace the words "vi-software-channel" with the direct link to it. Should be an easy fix

**Comment by xyb994** [comment]
Go ahead!
