### ISSUE TITLE
Step 4: Link To planet is too its GitHub repository and should not be

### ISSUE THREAD

**Issue by Gavinp14** [open-learning-exchange/open-learning-exchange.github.io#3377]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md#Step_4_-_Planet_and_myPlanet_Tutorial

### Problem

The Planet link takes you to the GitHub even though it should take you to the official website instead so users can get more info about the software. 

### Screenshots (when necessary)

<img width="724" alt="issues5Organization" src="https://github.com/user-attachments/assets/ac8d2392-8e93-4d00-b342-c9699d467943">

### Proposed solution(s)

Replace the link to GitHub with a link to https://www.ole.org/our-platform

**Comment by xyb994** [comment]
It was linked to the GitHub repo to show the technical side of it.
I'd say we should still keep the GitHub link somewhere, what do you think about just adding `([Learn more about the Planet Learning platform](https://www.ole.org/our-platform))` to the end of the sentence?

**Comment by Gavinp14** [comment]
I like that idea! I will go ahead and make a pull request for it
