### ISSUE TITLE
Step 3.2 Planet Configurations page: Link to Step 4 is linking back to First Steps 

### ISSUE THREAD

**Issue by RicaRodz** [open-learning-exchange/open-learning-exchange.github.io#3387]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-planet-configurations.md

### Problem

On Planet Configurations (Step 3.2) Page, the link to the next step, step 4 is actually linking back to First Steps

### Screenshots (when necessary)

<img width="1680" alt="Screenshot 2024-10-09 at 3 59 50 PM" src="https://github.com/user-attachments/assets/df788c64-eb6a-41f0-8ccb-fa71b14cfefd">

### Proposed solution(s)

Change the link to https://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md

**Comment by xyb994** [comment]
Sure, go ahead and create a branch and pull request for it!
