### ISSUE TITLE
adding guide on how to locate and traverse directory for repositories

### ISSUE THREAD

**Issue by RheuX** [open-learning-exchange/open-learning-exchange.github.io#3392]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-github-and-repositories.md

### Problem

When following the steps on Github and Repositories, I noticed that the first steps just asked us to clone the repo. I think thats fine for people who are comfortable with terminal (they can pick which directory they want by using `cd`), 

But for people who aren't, especially if they're comfortable cloning from IDE's such as Visual Studio Code or XCode (which has built-in Git integration, allows you to pick the directory). I'm wondering if we should also expect people who are following this instruction to know how to go/pick to their directories. If not, then they will just create a repository on their home directories

I know in the summary, there's a line saying `Open your command prompt/terminal and find the correct directory`, so teaching them how to do it would be beneficial for them, and can let them organize their own files

### Screenshots (when necessary)

<img width="880" alt="Screenshot 2024-10-09 at 4 03 13 PM" src="https://github.com/user-attachments/assets/cfa3deab-90f0-4c30-8b91-0c23fbe6d912">

### Proposed solution(s)

Teaching them about `cd` and `ls` commands  would be enough for them to navigate where they are, and we can give examples also.

Or if needed, creating a small page of guide on how to traverse and create files on the terminal

**Comment by xyb994** [comment]
Thank you for pointing out this issue. 

- We can certainly improve list item 3 in `1.2 Clone Your Repository` to remind virtual interns to navigate to [the dedicated directory they created in Prerequisite step](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-prerequisites.md?plain=1#L9) before running git clone. 
- I don’t think it’s necessary to create our own guide on using ls and cd since those skills should be assumed, but we can link to a good external article about navigating directories in the terminal.

Please proceed with the pull request for this!

**Comment by Gavinp14** [comment]
I like this idea; I know there are some later commands which involve commands like "curl" for example which some interns may not understand what this means nor the purpose of it. I think a general list of commands would be benificial.

**Comment by RheuX** [comment]
Okay sounds good, ill make a pull request
