### ISSUE TITLE
Add alternative method of installing couchapp on html resources and fix some incorrect information

### ISSUE THREAD

**Issue by prmurphy** [open-learning-exchange/open-learning-exchange.github.io#340]
For http://open-learning-exchange.github.io/#!pages/htmlresources.md,I think the windows installation for couchapp could be simpler . I found an exe file for couchapp here https://couchapp.readthedocs.io/en/latest/couchapp/install.html#installing-on-windows 

This might be easier for some users compared to using a command terminal. I would like to add this after some more testing if everyone thinks it's a good idea. 

As well, the instructions say that they will work with python 3.4, but in my experience that isn't true. I'd like to make it clear that it only works for 2.7 

I'd also like to change "Click the source and copy everything from the dummy resource EXCEPT the _id and _rev fields." to "Double-click..." since it took me an embarrassing amount of time to figure that out on my own.

**Comment by mepda** [comment]
Good ideas! A few ideas to add. 
*I think that a few other things could be added as well, like removing the bottom part of the page starting with "Using redirect in index.html file" and everything below it, as this process works without that last step.
*In "Objectives" (at the top) Bell App should be changed to OLE-Vagrant-Vi, also halfway through "Adding the app as resource to Bell App Library" should be changed to "Adding the app as resource to OLE-Vagrant-Vi Library"
*Couchdb Instance isn't necessary as it offers no instruction that can be seen
*Last step should be "Delete the dummy app in your library. Check that it works by opening it. Last, push the App to nation."

**Comment by mepda** [comment]
For windows 7, the way Patrick mentioned should work with a few modifications. First, you need to have MS Visual C++ 9.0 installed. Next, you need to pip install http-parser. After this, you should be able to get an instance of couchapp generated.

**Comment by aberdean** [comment]
@mepda, BeLL stands for Basic e-Learning Library, which is the name of the app. 
ole--vagrant-vi is just the name of a repository. So, that shouldn't be changed (as an example, if you look at the first steps, you learn about the BeLL App, not about the ole--vagrant-vi).

Other than that, I think you're both doing a great job on this!!! ;-)

**Comment by aberdean** [comment]
Fixed with PR #343
