### ISSUE TITLE
Broken Link:  Virtual Interns > FAQ > Helpful Links > Vi Cheat Sheet 

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/open-learning-exchange.github.io#3402]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#Helpful_Links

### Problem

The link to [Vi Cheat Sheet (PDF)](https://www.shell-tips.com/sheets/vi_help_sheet.pdf) 404s. 

### Proposed solution(s)

I think this is the link you want:

https://www.shell-tips.com/cheat-sheets/vim-quick-references/vi_vim_cheat_sheet.pdf

**Comment by xyb994** [comment]
Thank you for catching those!
