### ISSUE TITLE
Video Unavailable: Virtual Interns > FAQ > Helpful Links > GitHub & Git Foundations (Playlist)

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/open-learning-exchange.github.io#3403]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#Helpful_Videos

### Problem

"This video isn't available anymore"

[GitHub & Git Foundations (Playlist)](https://www.youtube.com/watch?list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-&v=FyfwLX4HAxM)

### Proposed solution(s)

I don't know what playlist was linked there, but similar git/github tutorial playlists exist on Youtube. Here's an example. It seems pretty high quality, although it is 7 years old. https://www.youtube.com/watch?v=3RjQznt-8kE&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR

**Comment by RheuX** [comment]
Nice catch,

I like this videos from freeCodeCamp about Git and GitHub, I think both videos are similar, its just that this one is using Visual Studio Code instead of atom, but its 1 hour long, so it may discourage people from watching, instead of the one you have where they split it up. [Git and GIthub by freeCodeCamp](https://www.youtube.com/watch?v=RGOj5yH7evk)

**Comment by Gavinp14** [comment]
I found this video that explains Git in under 2 mins https://www.youtube.com/watch?v=hwP7WQkmECE&t=72s, perhaps this may oversimplify how Git works; however I think interns would be more willing to watch a shorter video as opposed to an hour long.

**Comment by RheuX** [comment]
> I found this video that explains Git in under 2 mins https://www.youtube.com/watch?v=hwP7WQkmECE&t=72s, perhaps this may oversimplify how Git works; however I think interns would be more willing to watch a shorter video as opposed to an hour long.

I think in the original FAQ, there's already a link towards a shorter version of Git and GitHub so I think it's okay for this one to be a bit longer, than usual.
