### ISSUE TITLE
Typos, better wording in Teams page

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/open-learning-exchange.github.io#3410]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/manual/planet/teams.md

### Problem

Actions On Teams Page

After arriving to the Teams page you will see the screen **shown** below. Here are the actions you can perform:
- Search for specific teams by name
- Leave teams (If you are already a_part of a team)
- Request to join (If you **are** not a_part of a team)
- Change pages if there is a **large** amount of teams **listed**
...

You are also able to leave the meeting with the Leave button (This should say "leave the **team**")

### Proposed solution(s)

Grammatical fixes given above

**Comment by xyb994** [comment]
Go ahead!

Also feel free to use ChatGPT to polish up the conciseness as well. My fav is asking it to fix grammar and conciseness. Many of those were written by ESL speakers, including myself.

**Comment by jessewashburn** [comment]
I have submitted a PR with these fixes :)

Business writing is one of my strengths, so I'm sure there's more I could do in terms of improving the overall grammar and flow of the other pages. If I have some time before the meeting, I'll take a pass at some other content.
