### ISSUE TITLE
No detailed overview of time to complete each step 

### ISSUE THREAD

**Issue by Gavinp14** [open-learning-exchange/open-learning-exchange.github.io#3412]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md

### Problem

There is no table or any overview of each step and time estimated to complete each step. 

### Proposed solution(s)

Making a table like this 
| Steps | Est. Time to Complete | 
|----------|----------|
| Step 0 | 1-2 hrs   | 
| Step 1   | 1 hr  |
| Step 2   | 2 hrs  |

This is just a rough idea, but it would be beneficial to add this under the FAQ section, so interns know where to prioritize and manage their time to complete each step.

**Comment by jessewashburn** [comment]
Looks good! I think a clean and simple table like this is perfect. I would probably add the overall time, to save interns a little bit of math :) Also, maybe reiterate the 7-8 day window.

**Comment by Gavinp14** [comment]
> Looks good! I think a clean and simple table like this is perfect. I would probably add the overall time, to save interns a little bit of math :) Also, maybe reiterate the 7-8 day window.

Perhaps just a little statement before the table just stating how the steps on average take around 7-8 days?

**Comment by Gavinp14** [comment]
This is my current outline for how long I think on average each step should take...

| **Step Number** | **Estimated Time (hours)** |
|-----------------|----------------------------|
| Step 0          | 1-2                        |
| Step 1          | 2-3                        |
| Step 2          | 2-4                        |
| Step 3          | 4-6                        |
| Step 4          | 2-3                        |
| Step 5          | 1                          |
| Step 6          | 4-6                        |
| Step 7          | 2-3                        |
| Step 8          | 6-8                        |
| Step 9          | 4-6                        |
| Step 10         | 1                          |

**Comment by RheuX** [comment]
Step Number | Estimated Time (hours)
--         | --
Step 0 | 1
Step 1 | 2
Step 2 | 2
Step 3 | 3
Step 4 | 3
Step 5 | 1
Step 6 | N/A (creating issues and pr takes like 2-3 hours for me)
Step 7 | 3
Step 8 | N/A (same as step 6)
Step 9 | 2-3
Step 10 | 1

Step 6, and step 8, can vary a lot unless you're just specifying about creating issues and pr, but if you're talking about completing them, probably a day or two.

I think step 9, is mostly setting things up, so it wouldn't take that long. Unless maybe you're figuring out how it works and stuff (by reading documentation)

**Comment by jessewashburn** [comment]
I think just a restatement from the FAQ, in case they missed it: "There is no official deadline, so work on your own time. However, please note that most people who continued into the internship program completed the steps within 7-8 days" 

Here is the time I spent on each step. Note, I already had Git, Docker, NPM, etc already installed and was familiar with them, so that saved a lot of time initially.

0 - 1 hrs
1 - 30 mins
2 - 30 mins
3 -  1 hrs
4 - 1 hrs
5 - 30 mins
6 - 1 hr 30 mins
7 - 1 hrs
8 - 3 hrs
9 - 3 hrs

> > Looks good! I think a clean and simple table like this is perfect. I would probably add the overall time, to save interns a little bit of math :) Also, maybe reiterate the 7-8 day window.
> 
> Perhaps just a little statement before the table just stating how the steps on average take around 7-8 days?

**Comment by xyb994** [comment]
Thank you everyone for providing your time estimation.

This is related to @RicaRodz's  #3388. Perhaps @RicaRodz can work on [the change @Gavinp14 suggested](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/3388#issuecomment-2407828922) to `vi-first-steps.md` and each step's individual pages once we get everybody's time estimation.

**Comment by RicaRodz** [comment]
Sounds good to me! Should I go ahead and open a branch to work on it?

**Comment by xyb994** [comment]
> Sounds good to me! Should I go ahead and open a branch to work on it?

Please wait until Monday so I can have a chance to think about #3414 in depth, also give more time for everybody to provide their time estimation.

**Comment by xyb994** [comment]
Closing this as PR #3427 addresses it to a sufficient level
