### ISSUE TITLE
add a navigation feature to the website

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/open-learning-exchange.github.io#3417]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

http://localhost:3300/eng/

### Problem

I think one of the main problems with the website is when you first open it up, there is a lot going on. Although there are videos explaining different features of the website, many could look at it as a burden and just skip through them.

### Proposed solution(s)

I think there should be a pre-built navigation when a new user first logs into their Planet. It should take them step by step through the website, with explanations about each page to make sure that they have a better understanding of the website as a whole. This not only makes it more personable but also is more efficient in getting new users adapted to the website

**Comment by xyb994** [comment]
This issue should be filed in https://github.com/open-learning-exchange/planet and is out of scope for vi first steps. It's a potential feature you can work on once you officially finish the first steps and join us!
