### ISSUE TITLE
Members page former interns dead link

### ISSUE THREAD

**Issue by RicaRodz** [open-learning-exchange/open-learning-exchange.github.io#3424]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-team.md

### Problem

On the members page, the link "Former Interns" doesn't work 

### Screenshots (when necessary)

<img width="1675" alt="Screenshot 2024-10-14 at 2 47 33 PM" src="https://github.com/user-attachments/assets/71b3e5fa-1e81-43d3-86ce-39f942144216">

### Proposed solution(s)

Change the link to:
[vi-former-members.md](https://open-learning-exchange.github.io/#!./pages/vi/vi-former-members.md)

**Comment by xyb994** [comment]
The left side nav is generated by MDwiki with any `##` h2 header in the current page. It may seem to be not working because it's trying to jump to `#Former_Interns` tag but the page is quite short so it looks like nothing happened.

**Comment by RicaRodz** [comment]
That makes sense. Thanks for the clarification I'll look for something else to fix 🫡
