### ISSUE TITLE
content menu interlap with main article content

### ISSUE THREAD

**Issue by G201021** [open-learning-exchange/open-learning-exchange.github.io#3426]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md

### Problem

Having the page in a vertical view causes the index list of the page to interlap with the content in the main page. 

### Screenshots (when necessary)

![Screenshot 2024-10-15 001940](https://github.com/user-attachments/assets/34ec3c81-af5f-4175-972a-c3b36d3e25d1)

### Proposed solution(s)

implement CSS to adjust the relative position of the content to avoid interlap

**Comment by xyb994** [comment]
I'm not quite able to replicate this. Plus this is a [MDwiki](https://github.com/Dynalon/mdwiki/) issue, which is basically in doormat state, except one recent new lease this year.
