### ISSUE TITLE
faq question 19 follow link step 2.1 should say step 3.1

### ISSUE THREAD

**Issue by RicaRodz** [open-learning-exchange/open-learning-exchange.github.io#3429]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-faq.md

### Problem

In FAQ page, in question 19 it says to "Follow Step 2.1". There is no step 2.1, it should say step 3.1.

### Screenshots (when necessary)

<img width="898" alt="Screenshot 2024-10-15 at 5 44 01 PM" src="https://github.com/user-attachments/assets/eeede71d-c3cb-4ffd-afce-15e9971d458e">

### Proposed solution(s)

Change the text link for "Follow Step 3.1"

**Comment by xyb994** [comment]
Good catch, go ahead! Could you update the reference to `2.1` in Q20 as well?

**Comment by RicaRodz** [comment]
Perfect, will do
