### ISSUE TITLE
Planet Configuration Step 3.2 starting over wrong follow link 

### ISSUE THREAD

**Issue by RicaRodz** [open-learning-exchange/open-learning-exchange.github.io#3431]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-planet-configurations.md

### Problem

In Planet Configuration Step 3.2, in starting over section, "Configure Your Planet Community" link directs to another non-existing page

### Screenshots (when necessary)

<img width="1337" alt="Screenshot 2024-10-15 at 6 52 44 PM" src="https://github.com/user-attachments/assets/4f370c13-0f96-43c2-aeb7-27b0debf408e">

<img width="1680" alt="Screenshot 2024-10-15 at 6 52 47 PM" src="https://github.com/user-attachments/assets/140618c7-444f-47fa-8eca-8639ecc0f643">

### Proposed solution(s)

Change the link to:

[Configure Your Planet Community](https://open-learning-exchange.github.io/#!pages/vi/vi-planet-configurations.md#Configure_Your_Planet_Community)

**Comment by xyb994** [comment]
Nice catch! Go ahead with the pull request!
