### ISSUE TITLE
Remove unnecessary link to set up local HTTP Server

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/open-learning-exchange.github.io#3432]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md

### Problem

The link to setup a local HTTP server is outdated in terms of the python code provided, so there shouldn't be a need for the sentence or link to be there

### Screenshots (when necessary)

![Image 10-15-24 at 6 26 PM](https://github.com/user-attachments/assets/ee1d3e58-b7ad-4221-a8af-64f062d54d9b)

### Proposed solution(s)

Remove the link as it might make future virtual interns confused, and instead they could just run the command that is provided right after, which is python3 -m http.server 8080 in the folder where mdwiki.html is located

**Comment by xyb994** [comment]
I did not test this on other platforms other than mac, so it was linked to the original documentation, even though it's a bit outdated. Given that MDwiki's doc mentioned https://www.npmjs.com/package/http-server we might as well include it there. Plus not everybody would have `python3` available out of box?
