### ISSUE TITLE
adding content - 

### ISSUE THREAD

**Issue by G201021** [open-learning-exchange/open-learning-exchange.github.io#3438]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md

### Problem

Adding a section that briefly explains the "community" tab for PLANET. 

### Screenshots (when necessary)

![image](https://github.com/user-attachments/assets/d84cf15d-73eb-401d-99df-0208c5d3d1e4)

### Proposed solution(s)

This could explain the features that the "community" tab has for PLANET. Such as new content being added, sharing opinions, adding group event using its calendar feature.

**Comment by sahilvunnam** [comment]
This is a great idea for new members joining Planet, what if instead of having a tab that explains what the "community" tab is about, we can potentially have a popup when a user first enters Planet describing the "community" tab. Or within each sub-tab of the "community" tab we can have a little section that describes what each sub-tab is about.

**Comment by xyb994** [comment]
> This is a great idea for new members joining Planet, what if instead of having a tab that explains what the "community" tab is about, we can potentially have a popup when a user first enters Planet describing the "community" tab. Or within each sub-tab of the "community" tab we can have a little section that describes what each sub-tab is about.

I see we are missing this somewhat important feature. This would be an issue for [planet](https://github.com/open-learning-exchange/planet/issues)  and is out of scope for the purpose of the first steps.

**Comment by xyb994** [comment]
Sure, go ahead with a pull request! I don't think this navigation menu shows up if you set up planet as a nation, so perhaps we should mention that as well.
