### ISSUE TITLE
rewriting a sentence within the Planet User Manual page

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/open-learning-exchange.github.io#3445]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md

### Problem

Sentence: At the core, Planet is a repository of free, open access, and public domain resources designed to benefit literate and preliterate, young and old, and novice and expert learners of all ages.

I feel like the ending of this sentence is unnecessary if you just say"learners of all ages and backgrounds"

### Screenshots (when necessary)

![Image 10-17-24 at 6 19 PM](https://github.com/user-attachments/assets/ee7e77c4-40f5-41e0-a60a-c2173bc86383)

### Proposed solution(s)

Change the sentence too:

At the core, Planet is a repository of free, open access, and public domain resources designed to support learners of all ages and backgrounds.

**Comment by jessewashburn** [comment]
I agree; your change makes it much more concise. Also, I think it should be "At _its_ core, ..."

**Comment by xyb994** [comment]
Go ahead with a pull request!
