### ISSUE TITLE
move aspect of First Steps Page inside Step 6

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/open-learning-exchange.github.io#3446]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-first-steps.md#Step_8_-_Create_Issues_and_Pull_Requests

### Problem

The description of what should be done after Step 6 should be placed within the Github Issues (Step 6) page instead of the First Steps Page. This would be similar to how Step 8 has the description of what all should be done in the Step 8 Page itself. Also it's easier for future virtual interns, since they don't have to go back to the First Steps Page to see what should be done

### Screenshots (when necessary)

![Image 10-17-24 at 6 28 PM](https://github.com/user-attachments/assets/2a578957-0a9f-489f-a18e-d0e32f15a6bb)

### Proposed solution(s)

Place the bullet points of what should be done at the end of the Github Issues (Step 6) Page

**Comment by jessewashburn** [comment]
Makes sense.

**Comment by RheuX** [comment]
Sounds good, please make a pull request for this :)
