### ISSUE TITLE
adding a second resource to GitHub Issues Page

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/open-learning-exchange.github.io#3449]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md

### Problem

There isn't a problem with what is there currently, just wanted to add another resources of where a virtual intern could look to go to sync their fork.

### Screenshots (when necessary)

![Image 10-18-24 at 1 37 PM](https://github.com/user-attachments/assets/36340aec-34bc-498c-8f21-1068dd161387)

### Proposed solution(s)

Add that another area where an intern could look to sync their fork is found on Step 4 of the Github Issues (Step 6) page.

**Comment by xyb994** [comment]
Go ahead!
