### ISSUE TITLE
Clarify for step 7: Nation Bell

### ISSUE THREAD

**Issue by hikaruit15** [open-learning-exchange/open-learning-exchange.github.io#345]
At the end of Nation page,
> First, click the "Update Available" button and it will reload your homepage with a successful update message. An update refers to a new software update which improves the software. **Next, click on "Publications"** and sync the publications. Publications add new resources or courses to your library. Last, repeat the process of sending an activities sync to the nation.

Because we are in Dashboard now, no "Publications" button here. It makes a newbie for a while to figure out. Should we modify like this?

>First, click the "Update Available" button and it will reload your homepage with a successful update message. An update refers to a new software update which improves the software. **Next, click on "Manager" then click on "Publications"** and sync the publications. Publications add new resources or courses to your library. Last, repeat the process of sending an activities sync to the nation.

**Comment by aberdean** [comment]
@hikaruit15 When you get sent some publications, they appear in the Dashboard page, just next to where the Update appears. ;-)

**Comment by hikaruit15** [comment]
Because I did not get any publications when I do "Update Available". It had made me confuse when I followed the next step.

**Comment by aberdean** [comment]
@hikaruit15 That's because there was a problem on our side. Normally, it works as written there! ;-)
I'll close this issue, because the change isn't needed, but I want to commend you for being a good observer! ;-) Thank you!
