### ISSUE TITLE
update vi-intern-orientation.md and mi-intern-orientation.md

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#3454]
### Please verify the following:

- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-intern-orientation.md
https://open-learning-exchange.github.io/#!./pages/vi/vi-intern-orientation.md

### Problem

We'd like to instruction new vi/mi to make branch on github interface

### Proposed solution(s)

add instruction about starting a branch on github

**Comment by sahilvunnam** [comment]
I think this is a great fix, especially for interns that are unfamiliar or don't have the most experience with using Git. I think teaching them the write way to name a branch, and then create it, is necessary.
