### ISSUE TITLE
docker-tutorial: clarify planet.sh commands

### ISSUE THREAD

**Issue by ssamikshaa** [open-learning-exchange/open-learning-exchange.github.io#3458]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-docker-tutorial.md

### Problem

Since the usage description of the planet.sh commands does not include bash at the start, the user may not understand that Bash is needed to successfully execute the command.

### Screenshots (when necessary)

<img width="888" alt="Screen Shot 2024-10-22 at 2 15 31 PM" src="https://github.com/user-attachments/assets/ddc0902b-cb49-4a2f-b5fc-531819172887">

### Proposed solution(s)

Add "bash" to the start of the usage directions to ensure the user can execute the command.

Thus, it would be changed to:
#### Usage: bash planet.sh <up|stop|start|restart|down|(other docker compose command)...>

**Comment by xyb994** [comment]
go ahead and start a pull request!
