### ISSUE TITLE
docker-tutorial: add YAML file description

### ISSUE THREAD

**Issue by ssamikshaa** [open-learning-exchange/open-learning-exchange.github.io#3459]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-docker-tutorial.md

### Problem

Since a link is provided to show the YAML file for planet, it may leave users confused on how to interpret a YAML file.

### Screenshots (when necessary)

[
<img width="869" alt="Screen Shot 2024-10-22 at 2 35 07 PM" src="https://github.com/user-attachments/assets/68935a5e-93b8-4605-b06a-4513bb26d4a0">
](url)

### Proposed solution(s)

I propose that a link to an article describing the purpose and way to read YAML files be added to provide clarity to the user.

Link: https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started

**Comment by RheuX** [comment]
thats a good idea, since people who doesn't know about YAML would benefit from this.

**Comment by xyb994** [comment]
I agree that adding a link could be helpful for prospective virtual interns interpreting the YAML file. Would it be more useful to link to a resource specifically explaining the Docker Compose YAML file, rather than a generic one on YAML structure? What do you think about this one? https://www.baeldung.com/ops/docker-compose

**Comment by ssamikshaa** [comment]
Yes, that would be a much better fit.
