### ISSUE TITLE
step4.1-planet-tutorial: clarifying Fetch Items step

### ISSUE THREAD

**Issue by ssamikshaa** [open-learning-exchange/open-learning-exchange.github.io#3460]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/vi/vi-planetapps.md

### Problem

The Fetch Items step can be confusing to readers as it does not state to move to the next step if the button is not visible. The user may believe they cannot continue if the button is not visible.

### Screenshots (when necessary)

<img width="871" alt="Screen Shot 2024-10-22 at 2 43 25 PM" src="https://github.com/user-attachments/assets/7f166c84-0eac-4571-82ce-ece62869c7d7">

### Proposed solution(s)

I propose the step be reworded to be: 

"1. Fetch Items: Click on the Fetch Items button, select all, and use the “Get Courses/Resources” button to download the available courses. **If the fetch items button is not visible, proceed to the following step.**"

**Comment by xyb994** [comment]
sure, go ahead with a pr!
