### ISSUE TITLE
step4.1-planet-tutorial: troubleshooting course not visible after syncing

### ISSUE THREAD

**Issue by ssamikshaa** [open-learning-exchange/open-learning-exchange.github.io#3461]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md

### Problem

When completing step 4.1, a problem occurred in which even after the synchronization was complete, the course page still did not update. To fix this issue, I had to re-login to planet in order to view the courses.

### Proposed solution(s)

To help troubleshoot this issue for future users, I propose to add the following sentence within the "Take the Course" section.

"If the courses still do not appear after the synchronization is complete, try re-logging into Planet."

**Comment by sahilvunnam** [comment]
For the URL to the MDwiki page please use the link directly from open-learning-exchange.github.io. Here is the link of what page is containing the problem - https://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md

**Comment by sahilvunnam** [comment]
I like the proposed solution as virtual interns will know what to do if they deal with the same problem

**Comment by xyb994** [comment]
Go ahead with a pull request. Make sure you do not work on github.com interface this time :)
