### ISSUE TITLE
planet-user-manual: spelling and grammer fixes

### ISSUE THREAD

**Issue by ssamikshaa** [open-learning-exchange/open-learning-exchange.github.io#3463]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md

### Problem

On the planet learning page, there are a few grammatical errors and it could benefit from some rewording.

1. "has access to a high quality basic education"
2. "The Planet system exists in the cloud but it can also be configured to run locally without the need for internet connectivity..."
3. "Users can connect to a Community using any device having a web browser like tablet, computer, etc. "
4. "First thing you will see on PLANET is the Login page."

### Screenshots (when necessary)

<img width="869" alt="Screen Shot 2024-10-23 at 11 19 36 PM" src="https://github.com/user-attachments/assets/d5bf2538-409d-48f4-9521-87e1bc54b26a">
<img width="853" alt="Screen Shot 2024-10-23 at 11 20 00 PM" src="https://github.com/user-attachments/assets/40ed9954-a920-4db4-9439-6bdade8dd771">
<img width="805" alt="Screen Shot 2024-10-23 at 11 20 16 PM" src="https://github.com/user-attachments/assets/93f9840f-507b-49ca-8e3f-db3f23687efc">
<img width="850" alt="Screen Shot 2024-10-23 at 11 20 26 PM" src="https://github.com/user-attachments/assets/6f3e5a21-eaa5-4961-81b5-514e361b6d66">

### Proposed solution(s)

Instead replace them with:

1. "has access to a high-quality basic education."
2. "The Planet system exists in the cloud, but it can also be configured to run locally without the need for internet connectivity..."
3. "Users can connect to a Community using any device with access to a web browser, such as a tablet, computer, etc. "
4. "The first thing you will see on PLANET is the Login page."

**Comment by Gavinp14** [comment]
For "The Planet system exists in the cloud, but it can also be configured to run locally without the need for internet connectivity...", I think it could also be beneficial to add in add the end, "specifically, configured with a raspberry pi server" or something roughly along the lines of that. This would be so interns know exactly how the offline process works. What are your thoughts?

**Comment by sahilvunnam** [comment]
I think all four new sentences are now grammatically corrected with the solution

**Comment by ssamikshaa** [comment]
> For "The Planet system exists in the cloud, but it can also be configured to run locally without the need for internet connectivity...", I think it could also be beneficial to add in add the end, "specifically, configured with a raspberry pi server" or something roughly along the lines of that. This would be so interns know exactly how the offline process works. What are your thoughts?

Yes, thats a good point and it could help briefly mention the application of Raspberry Pis. Could change it to:
"The Planet system exists in the cloud, but it can also be configured to run locally, such as through a Raspberry Pi server. Thus, allowing access to the system in locations where internet connection is unreliable or nonexistent."

Also, now looking back at it, it might be better to split up that paragraph as the first part discusses cloud and the latter part discusses the purpose and features of Planet.

<img width="873" alt="Screen Shot 2024-10-24 at 8 58 04 AM" src="https://github.com/user-attachments/assets/c3b92957-bf6f-4d57-99b7-efbb50f35432">

**Comment by xyb994** [comment]
Thanks for catching those issues. Go ahead with a pull request. You may also run the sentences through chatgpt to check for grammar and conciseness.
