### ISSUE TITLE
Section Menu on Each Page

### ISSUE THREAD

**Issue by hikaruit15** [open-learning-exchange/open-learning-exchange.github.io#348]
I think we should use format `##` for sections on each page. It will automatically create a section menu on the left. This helps us navigate easily on the page, especially when we using mobile.

![screen shot 2016-11-16 at 11 05 08 pm](https://cloud.githubusercontent.com/assets/16807118/20376019/2ee31ea8-ac51-11e6-9b88-ca50ad8789bc.png)
![screenshot_2016-11-16-23-07-04](https://cloud.githubusercontent.com/assets/16807118/20376070/8a769af6-ac51-11e6-88b3-5551f792ca07.png)

**Comment by aberdean** [comment]
@hikaruit15 Absolutely! That's a great idea. Go for it!
