### ISSUE TITLE
myPlanet Manual needs an image to be clear about how to configure and sync

### ISSUE THREAD

**Issue by MelonLord8** [open-learning-exchange/open-learning-exchange.github.io#3488]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md#

### Problem

The section on configuring a connection to a planet, then syncing could use an image to make it more clear

### Screenshots (when necessary)

![image](https://github.com/user-attachments/assets/0de57bc8-a78e-4d6f-96b5-173ac8fd9254)

### Proposed solution(s)

Add a screenshot showing the steps in more detail.

**Comment by xyb994** [comment]
go ahead with adding an image for it. Please note there's some update to the configuration screen so perhaps you could mention the preconfigured options in the text as well.

**Comment by Avinash-Codes** [comment]
@MelonLord8 I was just about to create an issue regarding this. Thanks for submitting it!
