### ISSUE TITLE
embed Gitter into MDwiki

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#35]
https://jsfiddle.net/MadLittleMods/5u9h14Lc/ is an example how to add into any webpage. It would be awesome to get this working on our MDwiki instead of the link in the navigation bar ...

**Comment by fsjoyti** [comment]
We could use sidecar.gitter.im to embed gitter in our chat

**Comment by dogi** [comment]
@fsjoyti yes we could, but only
if we can't figure out the iframe way
