### ISSUE TITLE
Edit links that refer to sections on the same page

### ISSUE THREAD

**Issue by hikaruit15** [open-learning-exchange/open-learning-exchange.github.io#350]
In githubandmarkdown.md and gitandrepositories.md, we have links at `Start here` when we click on them, the page will be refreshed. 
For example 

`[Clone your GitHub repository username.github.io](gitandrepositories.md#Clone_your_GitHub_repository_username.github.io) `

Because they are links that refer to sections on the same page, so we don't need to refresh.
Should we change it into:

`[Clone your GitHub repository username.github.io](#Clone_your_GitHub_repository_username.github.io) `

Check it at [my site](https://hikaruit15.github.io/#!pages/githubandmarkdown.md)

**Comment by aberdean** [comment]
@hikaruit15 absolutely! Good catch!
