### ISSUE TITLE
update mi-github-issues.md: grammar mistake

### ISSUE THREAD

**Issue by pavi38** [open-learning-exchange/open-learning-exchange.github.io#3512]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-github-issues.md

### Problem

In Section 6, under "Stage the modified files" , "To stage all modified files show up in git status:"

### Proposed solution(s)

 "To stage all modified files that show up in git status:"

**Comment by xyb994** [comment]
Go ahead and create a pull request for it!
