### ISSUE TITLE
update navigation

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/open-learning-exchange.github.io#3513]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!navigation.md

### Problem

There's nothing important at https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md#Step_5_-_Git_Repositories:_A_Guide_to_Cloning,_Configuring,_and_Syncing_Forks, could point navigation item to the actual page directly

### Proposed solution(s)

Make mi navigation step 5 point to https://open-learning-exchange.github.io/#!./pages/mi/mi-github-and-repositories.md directly

**Comment by pavi38** [comment]
hey xyb994! Did you fix this issue? If not can I work on it?

**Comment by xyb994** [comment]
> hey xyb994! Did you fix this issue? If not can I work on it?

Sure, go ahead!
