### ISSUE TITLE
Fix Subject-Verb Agreement in "myPlanet uses Kotlin" Sentence

### ISSUE THREAD

**Issue by Daunt-99** [open-learning-exchange/open-learning-exchange.github.io#3515]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md

### Problem

There is a grammar mistake in Step 9 - Kotlin Tour in the sentence "myPlanet use Kotlin as the development language."

### Proposed solution(s)

The word "use" should change to "uses". Here is the modified sentence:
"myPlanet uses Kotlin as the development language."

**Comment by xyb994** [comment]
go ahead with a creating a branch and pull request for it!
