### ISSUE TITLE
mi-issues-and-prs.md: dead link

### ISSUE THREAD

**Issue by pavi38** [open-learning-exchange/open-learning-exchange.github.io#3517]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-issues-and-prs.md

### Problem

link not working to take users back to first steps

mi-first-steps.md#Step_8_-_Create_More_Issues_and_Pull_Requests

### Proposed solution(s)

Replacement link 

mi-10-steps.md#Step_8_-_Create_More_Issues_and_Pull_Requests

**Comment by xyb994** [comment]
Good catch, go ahead work on it in a new branch and create a pull request for it!
