### ISSUE TITLE
add Community section in myplanet/overview.md

### ISSUE THREAD

**Issue by pavi38** [open-learning-exchange/open-learning-exchange.github.io#3521]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md

### Problem

There is no section in myplanet/overview.md that describes the community feature of myplanet app.

### Proposed solution(s)

Add Community section below manager section with  following description:

The Community feature offers opportunities to connect with like-minded individuals, fostering the exchange of knowledge and creativity. Here, you can browse upcoming events, participate in those already in progress, or schedule your own using the integrated calendar. Note: you need to be logged in with member account to access this feature.

**Comment by xyb994** [comment]
Sure, go ahead and open a pull request for adding community section.

Since this is a "user manual",  I would avoid being too vague like what's currently on planet manual's community section. Try to include a few screenshots showing how to add an event and view the event on the calendar would be nice. You don't have to cover all the features in the community.

**Comment by pavi38** [comment]
Hey xib, I am able to add the event but I can't view it on the calendar

**Comment by xyb994** [comment]
Feel free to omit that screenshot, just add a section about adding an event would be good

**Comment by xyb994** [comment]
> Hey xyb, I am able to add the event but I can't view it on the calendar

I'm sorry, I was looking at the planet web version instead of myPlanet. This might be a good issue to work once you join the myPlanet team.

**Comment by MelonLord8** [comment]
Perhaps a section explaining what an event is to a new user would be helpful either in ```overview.md``` or in a new page if you plan on making one.
