### ISSUE TITLE
update clarity and structure of step 2 in mi-10-steps.md

### ISSUE THREAD

**Issue by Daunt-99** [open-learning-exchange/open-learning-exchange.github.io#3523]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md

### Problem

In Step 2, the steps for testing the app are presented in one large paragraph, making them harder to follow.

### Proposed solution(s)

I suggest we break it into numbered or bulleted steps for better readability. For example we can do:

- Launch the beta version of the app and grant necessary permissions
- Tap the gear icon in the upper-right corner after passing the intro screen
- Select the "planet learning" server to sync automatically.
- Log in as a guest and explore the app for at least 15 minutes.
- Take screenshots and attempt to crash the app.

**Comment by xyb994** [comment]
Go ahead with the change! I wonder if it's even better to move step 2 into its separate page as well 🤔

**Comment by Daunt-99** [comment]
Yes absolutely that's a wonderful idea.

**Comment by MelonLord8** [comment]
From what I could see on this issue and a few others, is that clarity/brevity is a present issue in this website, perhaps a page listing clear guidelines on how to write clear and concise instructions could be beneficial and a good idea for a new issue.
