### ISSUE TITLE
Section on taking a myplanet course in step 7 is cluttered and hard to read

### ISSUE THREAD

**Issue by MelonLord8** [open-learning-exchange/open-learning-exchange.github.io#3525]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/mi/mi-myplanet-course.md

### Problem

The section titled " "GitHub Issues and Pull Requests" Course " is hard to understand fully in the first read through. 

This can be attributed to an excess in content or simply the way it is presented.  

### Screenshots (when necessary)

![image](https://github.com/user-attachments/assets/e75d1945-ed0d-4c0a-8215-d146e1ddaa36)

### Proposed solution(s)

I suggest spacing out the bullet points and looking towards shortening them as well for more clarity.

**Comment by xyb994** [comment]
Go ahead with the improvement!

**Comment by pavi38** [comment]
Hey! melonlord I also thought that it was little hard to understand in a first read through. I also would suggest you to properly highlight the steps where we need to take the screenshot.

**Comment by Daunt-99** [comment]
Would it be helpful to reorganize the content into smaller sections with clear headings to improve readability and make the key points easier to digest for new readers?
