### ISSUE TITLE
Step 9 of the mobile intern first steps could have a link for kotlin docs

### ISSUE THREAD

**Issue by MelonLord8** [open-learning-exchange/open-learning-exchange.github.io#3533]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md

### Problem

Throughout the rest of the first steps we have always included links to external documentation for the tools we use (such as Github and Markdown). For the sake of providing information about what the interns will be mainly using throughout their internship (and for the sake of consistency) I think we should also include a link for the Kotlin docs: https://kotlinlang.org/docs/home.html

### Screenshots (when necessary)

![image](https://github.com/user-attachments/assets/b2e620d1-bd0b-4199-8e74-7630ef15d637)

### Proposed solution(s)

Add a link for [the Kotlin docs](https://kotlinlang.org/docs/home.html) at the end of step 9 with a bit of text indicating: 
 - Potential future use for a developer.
 - Further reading material for a new intern.

**Comment by xyb994** [comment]
Go ahead!

**Comment by Daunt-99** [comment]
Would it be helpful to also provide a brief explanation of how Kotlin might be used in future projects or tasks to give interns more context on its relevance?
