### ISSUE TITLE
AI Chat section of myPlanet manual is empty

### ISSUE THREAD

**Issue by Daunt-99** [open-learning-exchange/open-learning-exchange.github.io#3534]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md

### Problem

In the manual, the **AI Chat** section is empty.

### Proposed solution(s)

We could add a link to a new page and show an outline of how to interact with the chat, how to create a new chat, and the selection of different gpts.

**Comment by xyb994** [comment]
Go ahead!
