### ISSUE TITLE
Grammatical Error in Step 6 - GitHub Issues Tutorial

### ISSUE THREAD

**Issue by Daunt-99** [open-learning-exchange/open-learning-exchange.github.io#3537]
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document or [myPlanet User Manual](https://open-learning-exchange.github.io/#!pages/manual/myplanet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md

### Problem

There is a grammatical error in the sentence:
"No issue is too big or too small to be filed and it is OK if you are not sure how to fix it yourself."

### Proposed solution(s)

The phrase "it is OK" could be more grammatically correct as "it’s okay" or "it is acceptable."
Correction:
"No issue is too big or too small to be filed, and it’s okay if you are not sure how to fix it yourself."

**Comment by xyb994** [comment]
go ahead with the change!
