### ISSUE TITLE
Minor clarity and formatting improvement for githubandmarkdown.md

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#356]
The part where it says:

> For reference, an example of a link to a personal page is EmilyLarkin.github.io/pages/EmilyLarkin.md, so yours should look similar, just using your own username.

Made me think I was supposed to make my page look the same, but when I did that I was told it didn't have enough Markdown elements. I think changing to be worded like this would be clearer:

> Now, you can edit the files in your repo and the changes you make will be reflected on your <username>.github.io website. To edit, click on the pages folder. Then, click New File and name the file exactly the same as your GitHub username. We created pages for you using your GitHub username, so it is important that you stick with that name. **For reference, an example of a link to a personal page is EmilyLarkin.github.io/pages/EmilyLarkin.md, so yours should be named in the same manner, only using your username.**
> 
> From here, click the pencil icon to edit (as shown below) and type your name, your location/time zone, and OS (including version). Please, make sure to add a short description of yourself as well, so your fellow virtual interns know who you are. **Also try to use several Markdown elements in your page to get an idea for how it works.** Then, scroll down to the bottom of the page, select the Commit directly to the master branch radio box and click Commit New File.

Also the sentence right before the "Open a pull request" heading has the wrong angle brackets in the example URL. (&lt;username&lt;and not &lt;username&gt;)

**Comment by aberdean** [comment]
Awesome! You can go ahead and make a pull request!
