### ISSUE TITLE
gitandrepositories.md refers to a "Next Tutorial" but there is no tutorial.

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#359]
At the end of the `gitandrepositories.md` page it states:

> This process needs to be repeated whenever you begin to work, to make sure that you are always up to date. If there are discrepancies, it will mess up the code and you could potentially lose your saved changes, because it was not updated properly. **We will provide more information on editing and saving changes in the next tutorial.**

Unless it is referring to some external link, there is no "next tutorial" on the OLE first steps site.

**Comment by waryhermit** [comment]
Perhaps it means the "Github issues" but since just a few days ago that came before I assumed it wasn't referring to that. Especially since "Github Issues" doesn't really provide much information about editing and saving changes.

**Comment by aberdean** [comment]
I think that now, with the explanation you added to githubissues.md, that sentence makes sense again, doesn't it?
What do you think, @waryhermit?

**Comment by waryhermit** [comment]
@aberdean Yes, when that pull request is accepted this issues can probably be closed. If you want to be nit picky you could change "tutorial" to "step" since we have been referring to them as steps and not tutorials I guess.

**Comment by aberdean** [comment]
@waryhermit Sure. That's a good idea!

**Comment by waryhermit** [comment]
Looking at the *First Steps* page I can't see how to add "tutorial" to each of the step titles in a eloquent and sensible manner. Since there is now a "next tutorial" I think I will just close this issue.
