### ISSUE TITLE
Reminder to update fork in step 8

### ISSUE THREAD

**Issue by IshanSoni** [open-learning-exchange/open-learning-exchange.github.io#374]
Suggestion to add a reminder to update fork before beginning to create issues in step 8

**Comment by IshanSoni** [comment]
Will be creating a pull request that reminds the user and refers them back to step #6 before they proceed.

**Comment by waryhermit** [comment]
@IshanSoni I think if https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/365 gets accepted than this issue will be fixed. Check it out.

**Comment by aberdean** [comment]
@IshanSoni I agree with @waryhermit, #365 addresses the issue very well.

With the modifications to step 6, the process to follow will be much clearer.
