### ISSUE TITLE
Enabling virtualization question from FAQ should be included in vagrant tutorial

### ISSUE THREAD

**Issue by IshanSoni** [open-learning-exchange/open-learning-exchange.github.io#377]
Aside from the FAQ this question should be included in vagrant tutorial as virtualization is disabled on many PCs as default.

> Q: How can I enable the Virtualization in order to turn vagrant on?
First of all, you have to access the BIOS. To do that, you need to reboot your computer and press the appropriate key while it’s booting. It is usually the "F2" or "Delete" key. Once you have entered the BIOS setup menu, you have to search for an option called "Intel VT-x", "Intel Virtualization Technology" or something similar. Enable this option, save and reset. Now the "vagrant up" command should be working fine.

**Comment by IshanSoni** [comment]
I created a pull request fixing this issue #378

**Comment by aberdean** [comment]
@IshanSoni when the installation scripts detect that virtualization is not enabled on a machine, they give you the link to an explanation on how to enable virtualization in the BIOS.

Do you think that is not enough?

**Comment by IshanSoni** [comment]
@aberdean Oh! I did not know that. Then I believe it should be noted on the beginning of the page that virtualization needs to be enabled along with the short description of what it really is and a link included in the useful link portion. I think its better to do it beforehand just in case, gives a learning opportinity. I will create a new pull request and then let me know how it looks.

**Comment by IshanSoni** [comment]
@aberdean actually never mind. Adding this process might complicate the process. I will just add virtualization article in useful links instead.
