### ISSUE TITLE
Link for CouchDB doesn't work on Firefox

### ISSUE THREAD

**Issue by DarrenJJackson** [open-learning-exchange/open-learning-exchange.github.io#38]
Under the beLL-Apps tab, the link to see a user interface for CrowdDB "http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html." doesn't work for Mozilla Firefox.

**Comment by dogi** [comment]
Hmm - this is not a bug

Can somebody try to explain why?
Remember assignment 1 ...

**Comment by vimalababu4** [comment]
The above link  works for me when my vagrant is up and running with vagrant global-status

**Comment by dogi** [comment]
@vimalababu4 exactly

maybe we should add that to the instructions

**Comment by dogi** [comment]
Think we should add this problem to our possible FAQ's

**Comment by vimalababu4** [comment]
surely.

**Comment by sldaiute** [comment]
I think a quick note on what `vagrant global-status` should return if vagrant is currently running.

**Comment by aberdean** [comment]
Resolved (it has been added to the FAQ and the result of `vagrant global-status` is in a picture at http://open-learning-exchange.github.io/#!pages/vagrant.md).
