### ISSUE TITLE
Add in question to the faq.md 

### ISSUE THREAD

**Issue by hannahgdubin** [open-learning-exchange/open-learning-exchange.github.io#381]
I think it would be helpful to have a question that says "How long do I have to complete these steps?" I believe the answer would be "Complete on your own time. The quality of the work is most appreciated."
I am unsure if there is a specific about of time that I should add such as Complete within a week?

**Comment by IshanSoni** [comment]
@hannahgdubin @dogi said that there is no deadline but most people who made it into the intern program completed the steps in 7-8 days. Maybe consider adding that as well.

**Comment by hannahgdubin** [comment]
@IshanSoni Thank you I will update it.
