### ISSUE TITLE
Link to OLE official site

### ISSUE THREAD

**Issue by DarrenJJackson** [open-learning-exchange/open-learning-exchange.github.io#39]
Pretty obvious and possibly convenient, but maybe we can add a simple link next to the "chat" tab that can direct us to the official site of Open Learning Exchange, just for those of us who are curious to know more about the company.

**Comment by DarrenJJackson** [comment]
http://www.ole.org/ <-- the link to the official website, especially beneficial to those of us that may want to see what this internship can take us within this company. This link should be added under "Navigation" next to "Chat".

**Comment by dogi** [comment]
think we should add a logo in the beginning of the navigation, which bring us to http://ole.org

![favicon](https://cloud.githubusercontent.com/assets/13684059/15467970/5ddda68e-20af-11e6-9e4d-7eb9053727d4.png)
