### ISSUE TITLE
FAQ includes how to enable virtualization for windows. Suggestion to add it for mac and ubuntu as well.

### ISSUE THREAD

**Issue by IshanSoni** [open-learning-exchange/open-learning-exchange.github.io#391]
FAQ should include how to enable "Intel VT-x" on macs and ubuntu as well.

**Comment by IshanSoni** [comment]
I created a pull request adding the instructions for mac and ubuntu #392

**Comment by IshanSoni** [comment]
Created pull request #398

**Comment by dogi** [comment]
@IshanSoni there is a reason we did not do that

all mac hardware of the last 3 years has visualization enabled by default

**Comment by dogi** [comment]
for ubuntu it is not difficult to catch it - command `cat /proc/cpuinfo| egrep "vmx|svm"` will tell if kernel is ready for ...

**Comment by IshanSoni** [comment]
@dogi ok makes sense. So should I add that ubuntu command in the faq or is it fine the way it was?

**Comment by aberdean** [comment]
addressed in #398
