### ISSUE TITLE
One of the command from github issue tutorial doesn't work in Windows 10 command prompt

### ISSUE THREAD

**Issue by IshanSoni** [open-learning-exchange/open-learning-exchange.github.io#395]
>Then use git checkout -b name_of_your_new_branch --track origin/name_of_your_new_branch to create and switch to a new branch.

Using this command gives an error.

**Comment by IshanSoni** [comment]
Using 'git checkout -b name_of_your_new_branch' instead of 'git checkout -b name_of_your_new_branch --track origin/name_of_your_new_branch' works fine. I suggest changing the command in the tutorial to that.

![image](https://cloud.githubusercontent.com/assets/15035794/21143942/add513ae-c116-11e6-916b-b5eadab87fff.png)

**Comment by IshanSoni** [comment]
Pull request fixing the command #395

**Comment by waryhermit** [comment]
The track tag is important, you most likely made a typo. You need the tracking to push/pull from github.

**Comment by IshanSoni** [comment]
@waryhermit I copy pasted the command so whatever was on tutorial I used that. I was able to push/pull from github without any problems without the track tag.

**Comment by aberdean** [comment]
@IshanSoni you wrote:
git checkout -b co**m**_fix --track origin/co**mm**_fix
as shown in your screenshot... that's a typo! ;-)
Closing this and relative pull request!

**Comment by IshanSoni** [comment]
@aberdean I made a typo in the screenshot but I have tried that command without a typo too previously. It doesn't work.

![image](https://cloud.githubusercontent.com/assets/15035794/21172116/0cdebe18-c19e-11e6-83ec-98bfa2c6c80e.png)

**Comment by aberdean** [comment]
An alternative is this,
```
git checkout -b new-branch
initial commit
git push -u origin new-branch
```
Perhaps you can add that to the instructions.

**Comment by waryhermit** [comment]
The command is taken directly from the official git documentation. If it doesn't work there is probably something wrong on your end, maybe you don't have the remote setup correctly. Since it should work for everyone, it seems a little counterproductive to add alternate directions, we want them to come to chat if they did something wrong not ignore the mistake by working around it. Just my 2 cents, I don't feel that strongly about it.

**Comment by aberdean** [comment]
@waryhermit I think you need to add a branch on GitHub manually before using the command you provided. 
If you created the local branch only and you want to push it to remote and track, then you can use the alternative I gave above.

**Comment by waryhermit** [comment]
@aberdean It appears you are correct. I didn't remember creating them manually but I must have. Apologies. 

I would just make the branching step read as follows then:

>Every time you start to work on an issue you need to create a branch to keep your work on various issues separate from each other. Before you create your branch, sync your repo following the process in the [previous step](http://open-learning-exchange.github.io/#!pages/gitandrepositories.md). Then use  `git checkout -b new-branch` to create the branch and `git push -u origin new-branch` to add it to your Github.
