### ISSUE TITLE
Clarify that all branches must be created be you start to work on each individual one in githubissues.md

### ISSUE THREAD

**Issue by hannahgdubin** [open-learning-exchange/open-learning-exchange.github.io#399]
to submit multiple pull requests, you need to use multiple branches (and create all branches at the same time, before you start modifying anything). If you don't create all branches at the same time, then you need to wait for your pull request to be merged and then you need to update your fork, before submitting another one. I think that this useful advise from @aberdean should be clearly stated in the githubissues.md

**Comment by IshanSoni** [comment]
>Every time you start to work on an issue you need to create a branch to keep your work on various issues separate from each other. Before you create your branch, sync your repo following the process in the previous step. Then use git checkout -b name_of_your_new_branch to create and switch to a new branch.

This part in the github issue tutorial already states that

**Comment by hannahgdubin** [comment]
I don't believe that it says you need to create all branches you intend to work on before modifying anything @IshanSoni

**Comment by aberdean** [comment]
@hannahgdubin that's just a suggestion I gave you, because of your specific situation.
Since you already had 3 pull requests ready, creating all branches at the same time would have avoided further possible mistakes. 

However, as @IshanSoni said, the instructions from the GitHub Issues tutorial are accurate.
