### ISSUE TITLE
Step#3 should also state that you may have to delete/replace your current <username>.github.io page if you already have one

### ISSUE THREAD

**Issue by cpanican** [open-learning-exchange/open-learning-exchange.github.io#402]
Although this is already on the [FAQ page](http://open-learning-exchange.github.io/#!pages/faq.md), it will be better if we state this in step#3 or [githubandmarkdown.md](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md). There might be some people who didn't read the FAQ page and are not aware that their GitHub page will be used.  This is the text from the FAQ page:

> Q: What do I do if I already have a github.io with my username?
You have a couple of options.
>1. If you are not using the repo anymore you can delete it and then follow the [First Steps](http://open-learning-exchange.github.io/#!pages/firststeps.md).
>2. If you are still using it and you don't want to remember another login, you can [create an organization](https://help.github.com/articles/creating-a-new-organization-from-scratch/) and name the forked repro <orgname>.github.io
>3. Or you can just create another GitHub account, and use that for OLE work

**Comment by aberdean** [comment]
@cpanican the FAQ page was created to avoid scattering extra information throughout the first steps.

Then, since some people may not read the FAQ page, as you mentioned, I made sure to add this line to the very beginning of the First Steps:
> We created a FAQ page where you can find the answers to some commonly asked questions, and also some very useful links and videos tutorials that will help you become familiar with the tools/languages we use.

Do you think that is still not enough?

**Comment by cpanican** [comment]
@aberdean. I think only a few have a GitHub page beforehand so I do agree with you. Adding this may be unnecessary.
