### ISSUE TITLE
fix in faq that takes the reader directly to the job page and also refers to other opportunities

### ISSUE THREAD

**Issue by IshanSoni** [open-learning-exchange/open-learning-exchange.github.io#407]
It is better if the link in the FAQ to job description takes the reader [here](https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs/Virtual-Software-Engineer-Intern-14d7c793f7606bf2?q=%22virtual+software+engineer+intern%22) instead and also refer them [here](http://www.ole.org/take-action/join-our-team/) if they are interested in other opportunity with ole.

**Comment by mappuji** [comment]
In my humble opinion, the better solution is to create a FAQ on the official OLE homepage instead. So that the prospective intern confident with the opportunity.

**Comment by waryhermit** [comment]
Linking to a certain job posting is inconvenient for use since the job posting URL changes often. If someone can't figure out how use the link to `ole.org` in the job posting and look around than I doubt they will even be reading the FAQ.
