### ISSUE TITLE
Improve and update the team page

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#408]
# virtual intern lead
- @aberdean
# virtual intern
- @FanisGk 
- @mepda 
- @prmurphy 
- @hikaruit15 
- @waryhermit 
- and you @IshanSoni 

## virtual intern summer 2016 lead
- @i5o 
- @EmilyLarkin 
- @DrewPerlman 
## virtual intern summer 2016
all the ones in  http://open-learning-exchange.github.io/#!pages/team.md Steps Completed

remove Steps In Progress @rachelpei

**Comment by IshanSoni** [comment]
@dogi Updating the page.

**Comment by IshanSoni** [comment]
@dogi Check out the pull request #411
