### ISSUE TITLE
Previous Interns should have their dedicated section from the side bar

### ISSUE THREAD

**Issue by cpanican** [open-learning-exchange/open-learning-exchange.github.io#412]
Adding a "Previous Interns" section will make the page look more organized because if this page is updated every year, then we will have a dedicated section for those who worked in this internship.

This is the screenshot of proposed change. Take note of Previous Interns on sidenav as well:
![capture4](https://cloud.githubusercontent.com/assets/18671098/21238052/7a6ab586-c2cf-11e6-911a-aa7573311725.PNG)

And if this page is used in Summer 2018, then it would look like this: 
![capture3](https://cloud.githubusercontent.com/assets/18671098/21238090/ac5b1414-c2cf-11e6-834e-06018c5c4b3f.PNG)

**Comment by aberdean** [comment]
@cpanican I think that's nice, you can go ahead and submit a PR. ;-)
