### ISSUE TITLE
Configuring a remote for my fork is a bit confusing

### ISSUE THREAD

**Issue by cpanican** [open-learning-exchange/open-learning-exchange.github.io#415]
One of the steps in step#5 is configuring our git repo to properly update with ole repo. The current steps are kind of confusing since it only tells us to go to [this link](https://help.github.com/articles/configuring-a-remote-for-a-fork/). It would be better if we modify the instructions from that link and make it more specific/clearer. Maybe if we put specific links, tips, etc. that part could be less confusing.

**Comment by aberdean** [comment]
@cpanican Do you have any specific proposal on how to go about it?

**Comment by cpanican** [comment]
Adding subsections, with specific commands and steps to that part will make it clearer. Here is a screenshot of what I did in my repository: 
![image](https://cloud.githubusercontent.com/assets/18671098/21303342/c2f31622-c58b-11e6-95f1-363c28cf0050.png)
It is similar to the link from github, but the commands specifically points to open learning exchange repository. People won't have to manually type the address and they can just copy paste the command.

**Comment by aberdean** [comment]
@cpanican looks good to me. Please, go ahead and submit a PR (but first, answer my questions in chat!).
