### ISSUE TITLE
Formatting needs fixing on automatedtestingcodeceptjs.md

### ISSUE THREAD

**Issue by aberdean** [open-learning-exchange/open-learning-exchange.github.io#417]
Now it looks like this,
![image](https://cloud.githubusercontent.com/assets/4922217/21457392/4f2da64c-c92f-11e6-85f9-62cea3659c77.png)

But, it should look like this,
![image](https://cloud.githubusercontent.com/assets/4922217/21457408/7387a89e-c92f-11e6-835f-28c7d2dbdece.png)

**Comment by waryhermit** [comment]
For got to change the title to automatically close this issue. This issue was fixed by #456
