### ISSUE TITLE
introduce code review to workflow

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#422]
example
![new style](https://cloud.githubusercontent.com/assets/13684059/21743443/6d90c720-d4d0-11e6-942d-685463c55bb3.png)

this means we have to update step 3
so that virtual interns after they make the pull request they would also add the reviewers ...

secondary question is how would new virtual interns knew who they can add for reviewing

**Comment by fangninghe** [comment]
According to our conclusion, one possible solution is to add the possible reviewer list to the step 3 web page to inform the interns who create pull requests that they have to choose 3 or more reviewers to review their PR as well after they create PR.

**Comment by dogi** [comment]
thanks @fangninghe and congrats to your first comment
by the way forgot to say every github message can to markdown ;)

Let me recap / sum up the chat discussion:

Topic: How to add the new github reviewers feature into our workflow on our mdwiki?

Idea:
Have already the creators of the `pull request` add **all** the possible reviewers.
Right now this initiation of the `review process` is mostly done manually by me which ends up in loosing precious time.
I checked already https://developer.github.com/v3/pulls/review_requests/ and based on this information:
- **pull request authors**
- repository owners
- and collaborators

can do that
- [ ] somebody without any rights on repository needsto test this to confirm this information
@hannahgdubin and/or @IshanSoni could - bingo - maybe @fangninghe wants to do that ;)

Lets assume PR creators are able to then they will see a list like
![rlist](https://cloud.githubusercontent.com/assets/13684059/21752394/06ff0424-d5a5-11e6-99ba-916c9a9ca34f.png)
What should they select?

- all (pro: simple cons: maybe overkill)
- all from a list of reviewers (pro: no overkill cons: where to put that list)

Reason we put so many reviewer is to speed up and/or structure this `reviewing process`
cause it enables them to be part of a decision process
![rlist1](https://cloud.githubusercontent.com/assets/13684059/21752475/bc1d55d0-d5a6-11e6-8b8f-b9bc4e38b78b.png)

**Comment by Chris-Boe** [comment]
Hi @dogi ,
 I looked into this and found this [https://help.github.com/articles/requesting-a-pull-request-review/](https://help.github.com/articles/requesting-a-pull-request-review/), stating the same, that 
"Pull request authors and repository owners and collaborators can request a pull request review from anyone with write access to the repository".

The instructions they give are as follows:
![capture](https://cloud.githubusercontent.com/assets/8600792/22639168/7c3cb00c-ec01-11e6-9920-d5e7648e4dac.PNG)

However, I looked at my own PR and the *Gear* that they mention does not show up for me (aren't I the author of my own PR though?). Any ideas?

**Comment by dogi** [comment]
@Chris-Boe we know about that

@dogi spoke with github support about that and they:
- added a feature request for futur github.com development
- and fixed the documentation about PRs

**Comment by Chris-Boe** [comment]
@dogi Okay, so are we just waiting for them to add that feature?

**Comment by paulbert** [comment]
@dogi Has the team considered including a step that has the interns make a gitter post to request reviews as an option?  That would require the list of reviewers, but we could have those in a gist post that's embedded in step #_3_ to make it a little simpler to keep updated.  I know it's not exactly what gist is for, but I don't see another way to have an embedded document within an mdwiki page.

Let me know if you need me to provide more clarity.

[mdwiki gist gimmick](http://dynalon.github.io/mdwiki/#!gimmicks.md#GitHub_Gists)

**Comment by dogi** [comment]
I am closing this due impossible to be done in `github` as of right now
