### ISSUE TITLE
A confusing step of creating a new file with MD at githubandmarkdown.md

### ISSUE THREAD

**Issue by fangninghe** [open-learning-exchange/open-learning-exchange.github.io#423]
I felt a little confused when running into creating person MD Wiki page. 
======
After I read the sentence "**From here, click the pencil icon to edit (as shown below) and type your name, your location/time zone, and OS (including version)**", I thought I have to use the **_pencil icon_** at the very beginning to write my file and of course I could not make it since the file has to be created first and then can be edited by clicking **_pencil icon_**. 

So can we just make it into something like"In the file, please type your name, your location/time zone, and OS (including version)......Then scroll down to the bottom of the page, select the ```Commit directly to the master branch``` radio box and click ```Commit New File```. If the file needs to be edited again, just click the **_pencil icon_** to edit it again."?

**Comment by dogi** [comment]
@fangninghe do I see that right that you suggest  there is some wording which needs to be improved ;)

**Comment by dogi** [comment]
###Create a new file as your personal MD Wiki page and commit your changes
Now, you can edit the files in your repo and the changes you make will be reflected on your &lt;username&gt;.github.io website. To edit, click on the `pages` folder. Then, click `New File` and name the file exactly the same as your GitHub username. We created pages for you using your GitHub username, so it is important that you stick with that name. For reference, an example of a link to a personal page is EmilyLarkin.github.io/pages/EmilyLarkin.md, so yours should be named in the same manner, only using your username.

From here, click the pencil icon to edit (as shown below) and type your name, your location/time zone, and OS (including version). Please, make sure to add a short description of yourself as well, so your fellow virtual interns know who you are. Also try to use several Markdown elements in your page to get an idea for how it works. Then, scroll down to the bottom of the page, select the `Commit directly to the master branch` radio box and click `Commit New File`.

![Edit](uploads/images/Edit.png)

Now, check what this looks like on your own page (&lt;username&gt;.github.io/#!pages/&lt;username&gt;.md) and post a link to it in the [gitter.im chat](https://gitter.im/open-learning-exchange/chat). Check and double check that everything looks good and is working before initiating a pull request.

###Open a pull request
Then, you can create a pull request by clicking the `Pull requests` button and then clicking `New pull request`. Finally, click `Create pull request` and someone from our team will then approve and merge your pull request, once everything looks good. After the pull request is completed, you'll be able to see this on open-learning-exchange.github.io in addition to your personal page. Let us know when you have completed this step in the [gitter.im chat](https://gitter.im/open-learning-exchange/chat).

##Useful links

**Comment by fangninghe** [comment]
In the new file, please type your name, your location/time zone, and OS (including version). In addition, make sure to add a short description of yourself as well, so your fellow virtual interns know who you are. Also try to use several Markdown elements in your page to get an idea for how it works. Then, scroll down to the bottom of the page, select the `Commit directly to the master branch` radio box and click `Commit New File`. If you need to edit your file again, just click the pencil icon to edit (as shown below).

>Use the paragraph to replace the entire second paragraph above, I mean from "From here..." to "...create new file"
@dogi, how about this?

**Comment by dogi** [comment]
I like it ;)
@waryhermit your thoughts? ;)

**Comment by waryhermit** [comment]
@dogi Yes, this is an improvement. I wonder if the Github UI changed or it was just a mistake.
