### ISSUE TITLE
Some doubts about the relationship between vagrant and Bell-Apps

### ISSUE THREAD

**Issue by fangninghe** [open-learning-exchange/open-learning-exchange.github.io#430]
Frankly, I am not so familiar with vagrant, also step 2 (vagrant) and step 4 (Bell-Apps) are not close to each other. So as a beginner, **I did not realize the relationship between vagrant and Bell-Apps**. For example, I was not sure when starting Bell-Apps, vagrant should be running, and the tips for that in step 4 is only under `MacOS(X) and Ubuntu`  tag but not `Windows` tag. Since I use Windows, I passed to `Windows` tag directly.

Secondly, I notice another thing, as we can see, **step 1, step 2, step 4 and step 7** are about **vagrant and Bell-Apps, step 3, step 5, step 6 and step 8** are about **github**.

**In order to provide some convenience for newbies just like me, my suggestions are as below:**
* Add more content for explaining the relationship between vagrant and Bell-Apps in step 2.
* Add tips for running vagrant under `Windows` tag in step 4.
* Change the sequence of the step list to keep content consistence, like putting vagrant/Bell-Apps together and github tutorial together.

**Comment by waryhermit** [comment]
One thing to note is that vagrant is suppose to start when your computer starts, but right now it doesn't due to this issue: https://github.com/dogi/ole--vagrant-vi/issues/18

**Comment by hikaruit15** [comment]
Hi @fangninghe 
Bell-Apps is a web application. We need a server to host and run it. Right now, we use virtualbox to do setup a virtual machine as server on our local machine for Bell-Apps.
If you do that with virtualbox by yourself without helping from vagrant. It takes a lot of steps. On the other hand, vagrant make you setup everything easily.
You could check here: [Why vagrant](https://www.vagrantup.com/docs/why-vagrant/)

**Comment by fangninghe** [comment]
Hi @hikaruit15 , thanks for the explanation, that makes sense. When I wrote a web application for academic project, I did use Tomcat as a personal server to run the app written in STS. So now I really realize the function of vagrant, thanks.

**Comment by fangninghe** [comment]
**Hey guys, what about like this in bellapps.md:**
----

### Windows
Please, double click on the MyBeLL icon on your desktop. It will open up a Firefox browser. If you see a page as below,

![unable to connect](https://cloud.githubusercontent.com/assets/22717583/21965957/e9e4cb7e-db37-11e6-9e5c-1b8cbb45b053.png)

Then you can check that whether Vagrant in running by going to directory `C:\Users\YOUR_USERNAME\ole--vagrant-vi`(the same way illustrated in Step #2) and typing command `vagrant global-status`.  If the status is **poweroff**, then just type `vagrant up` to restart Vagrant. And if the status is **running**, but you still get that error, type `vagrant halt` first to stop Vagrant then type`vagrant up` to restart Vagrant, the error should be fixed.

 Now  you should see the user interface (see below).

**The rest is the same.......**

>PS: 1. The link of picture will be changed if you agree with me
        2. I am sure about the "restart" process, just list them first.

**Comment by waryhermit** [comment]
@fangninghe I would make it much more minimal. Like this:

> Please, double click on the MyBeLL icon on your desktop. It will open up a Firefox browser and show you the user interface (see below). [If you get an `Unable to connect page` see the FAQ](http://open-learning-exchange.github.io/#!pages/faq.md#Technical_Issues_and_Questions).

**Comment by fangninghe** [comment]
@waryhermit , yep, I totally agree, I made things a little more complicated.

**Comment by waryhermit** [comment]
@fangninghe Want to make a pull request with that change? ;)

**Comment by fangninghe** [comment]
@waryhermit ,sure, I will work on it

**Comment by waryhermit** [comment]
This was fixed by #463 (Forgot to change the title)
