### ISSUE TITLE
Clean up old and unused user pages

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#432]
Since in the last year we had many people trying to be virtual intern an some of them also stopping along the road we collected some **orphans pages** ...

Create a `pull request` where you remove orphans which are older then a half year ;)

**Comment by dogi** [comment]
by the way we are already happy if you get some orphans
I was mostly thinking about 3 ;P

**Comment by shabiba** [comment]
i just try the command

**Comment by Chris-Boe** [comment]
@dogi Would we be deleting old pages that may belong to successful interns as well? Or do they not matter to anyone after a 6-month period has passed? Thanks :)

**Comment by waryhermit** [comment]
@Chris-Boe It is my understanding that we are only deleting people who did not contribute anything after completing the steps or never finished the steps.

**Comment by dogi** [comment]
mostly the ones which never finished the steps ;)

**Comment by paulbert** [comment]
Ok, I'll go ahead and remove agaikwad4.md and alan459.md.  PR in 5, 4, 3 . . .

**Comment by Chris-Boe** [comment]
@dogi  @waryhermit  Is there a way or a list to find out who never completed the steps beyond the MD Wiki?
Also, I was able to use your command, but trying to make a script by combining it with something like 
* find . -maxdepth 1 -type f -newermt 2011-08-01 ! -newermt 2011-08-06 -delete
stumps me. Is there something we can add as a pattern in 
git-ls-files --exclude <pattern>
that would be equivalent?

**Comment by dogi** [comment]
@Chris-Boe ;)

we could - but then this easy task would disappear and many aspiring virtual interns have less option of nice and easy solvable tasks

specially this is a task where you need to search and remove which is not normally done in this early git learning stages

**Comment by sarvanivadali** [comment]
Hi @dogi I came up with the iterative solution (not really efficient but might do the job). Can you comment.

* Extract user names from file names in ./pages which are created more than six months ago.
* Exclude team.md and other non-personal pages (TBD) from the list.
  * This gives us a list of authors/interns who have created their pages more than six months ago.
* Check for every user if they have made contributions to the repository other than their own page in ./pages.
```git log --author='author' --oneline -- . ":(exclude)pages/author.md"```
  * Idea here is that a successful intern would at least make one or more changes to the current repository. Assuming all the interns followed all the 8 steps in <http://open-learning-exchange.github.io/#!pages/firststeps.md> from the beginning.
* Now, we have a list of authors who have not made any contributions to this repository.
  * Remove their corresponding files from ./pages.

**Comment by waryhermit** [comment]
In addition to using the command @dogi provided, @Ebuka-Chibueze has been working on a [script which you can use to check the number of PR someone has]( https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/521). This will help you figure out if the user in question  ever completed the steps.

**Comment by dogi** [comment]
since some days ago we moved all members to a new directory this issue is not working the same way as before ...
that is why I will close it for now
