### ISSUE TITLE
Indroduce basic branching to GitHub and Markdown

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#433]
When we have interns [create their user page](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md) we should have them use the "*Create a new branch for this commit and start a pull request*" like in this image:

![image](https://cloud.githubusercontent.com/assets/5189447/21935402/659376e4-d97b-11e6-8953-d08b240fd6f6.png)

This will enable them to work on other issues before their user page is accepted, without messing up any pull requests.

**Comment by prmurphy** [comment]
That sounds like a very good idea!

**Comment by waryhermit** [comment]
This issue was fixed by #457
