### ISSUE TITLE
Validation Issue in Bell Library

### ISSUE THREAD

**Issue by maninderjheeta** [open-learning-exchange/open-learning-exchange.github.io#438]
I was trying to create a meetup the Bell Library. And I find out that there is no validation being added for the start date and end date. **Start date <= End Date**. While this is not true for the present Bell Library I have access to.

_Please refer the below images. And it is showing that **Start Date > End Date**, which should not be the case._

![meetupissue](https://cloud.githubusercontent.com/assets/25035544/21971514/3f0178f4-db7f-11e6-9daf-0eba95f94649.PNG)

**The same issue is also happening in the create event screen in the calendar as well.**
![eventcalendar](https://cloud.githubusercontent.com/assets/25035544/21971660/c302ecb8-db80-11e6-944e-af31642042bf.PNG)

**Please let me know how can I access the files to fix the issue**

**Comment by dogi** [comment]
@maninderjheeta this is a good issue for BeLL-Apps repository, but for our 10 steps you should speak about issues of https://github.com/open-learning-exchange/open-learning-exchange.github.io

**Comment by maninderjheeta** [comment]
ok sure. I will focus on https://github.com/open-learning-exchange/open-learning-exchange.github.io
