### ISSUE TITLE
Select All & Unselect All problem on Sync with Nation

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/open-learning-exchange.github.io#444]
I have found an issue on **Sync with Nation** functionality. If I click all the choices manually, I can't unselect all the choices. I think it should be better if it is automatically detect if we have choose all the choices.
 
![select-unselect](https://cloud.githubusercontent.com/assets/11813607/22033192/209d8c44-dd1a-11e6-8db1-b781e61ba8d5.PNG)

**Comment by mappuji** [comment]
Sorry, I post an issue in wrong repository. This issue is for the Bell App.

**Comment by dogi** [comment]
@mappuji great :D 
you was faster then me here ...

look at my comment here https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/438
