### ISSUE TITLE
A short description on chat page

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/open-learning-exchange.github.io#446]
I think for a better understanding about our Gitter chat platform. We can add a short description on the chat page here http://open-learning-exchange.github.io/#!pages/chat.md .

**Comment by dogi** [comment]
I like that one

@mappuji What would the description say?

**Comment by mappuji** [comment]
## About Chat
Chat is a good place to _discuss, learn more, and collaborate with others_ to build a better Open Learning Exchange Platform. This chatroom is used as a general channel of communication between Open Learning Exchange's software development team, interns, and volunteer developers.

We believe that communications between contributors in open source project are very important for a successful opensource project. We use Gitter as our chat platform. We choose Gitter because it provides a free public chat room for open source projects on GitHub as well as private communication channels for teams and businesses.

With full rich text support through markdown including full syntax highlighting for code, tight integration with GitHub issues and activity as well as integrations with Trello, Jenkins, Travis and many other services, it is a great platform for us to collaborate.

**Comment by dogi** [comment]
I kinda like this text but I also have to say it sounds like gitter marketing page ;)

@mappuji I think we should tailor this description more to our needs ...

... also other question wonder how you wanna add this page to chat.md? top? bottom?

**Comment by mappuji** [comment]
@dogi thank you for your feedback. I kinda think the same. I regret that yesterday I create an issue for the sake of the vetting process. I will close this issue and raise a more important issue.

**Comment by waryhermit** [comment]
@mappuji I think only the channel owner can change that. What would you change it to?

**Comment by Chris-Boe** [comment]
Hey @mappuji @dogi ,
I think this would be a cool idea, maybe add the first two paragraphs of @mappuji 's explanation to the top of the Chat wiki page (before the preview), as well as a link to the actual Gitter page in case they want to open the real thing.

**Comment by dogi** [comment]
@Chris-Boe ok - can you get more concrete ;)

**Comment by Chris-Boe** [comment]
Hey @dogi , 
Here's what I'd add in a PR. Shout out to @mappuji for the great description, I just edited it a bit ;)

Our **Gitter** chat, previewed below, is a great place to learn, discuss, and collaborate with other members to build a better Open Learning Exchange platform. The chat lets OLE’s development team and interns communicate easily, and signup is simply through each member’s Github account.

Communication is key in every collaborative project, and OLE is no different. Gitter provides tight integration with *Github issues and repositories*, as well as support for *Trello, Jenkins, Travis,* and many other services. It also has full rich text support through **Markdown**, an important tool for clean, efficient communication.

Click [here]( https://gitter.im/open-learning-exchange/chat) for the full Gitter chat page.

**Comment by dogi** [comment]
Sorry @Chris-Boe for taking so long to come back at you

I think we should tailor it even more to our needs ...

... and @Chris-Boe your Text is better then @mappuji s but still not that what I think we should put on this page

@Chris-Boe think we should remove line `Gitter provides tight integration with Github issues and repositories, as well as support for Trello, Jenkins, Travis, and many other services. ` and speak maybe more about good chatting practice

also we should encourage virtual interns to add gitter to their phones and desktop so they are able to follow and/or quicker respond to topic at hand
