### ISSUE TITLE
redesign team.md page

### ISSUE THREAD

**Issue by fangninghe** [open-learning-exchange/open-learning-exchange.github.io#447]
_Can we make a change to merge team leader and members together under one tag as below:_

# Members
## Current virtual interns
Intern Lead: 
* [aberdean](aberdean.md)

---
* [FanisGk](FanisGk.md)
* [mepda](mepda.md)
* [prmurphy](prmurphy.md)
* [hikaruit15](hikaruit15.md)
* [waryhermit](waryhermit.md)
* [IshanSoni](IshanSoni.md)
* [hannahgdubin](hannahgdubin.md)

if you have any questions or need help completing the steps, feel free to ask any of the current interns on [Gitter chat](https://gitter.im/open-learning-exchange/chat)

## Previous Interns
---
>### Summer 2016 virtual interns
>Intern Lead:
>* [EmilyLarkin](EmilyLarkin.md)
>* [DrewPerlman](DrewPerlman.md)
>* [i5o](i5o.md)
>
>---
>* [fsjoyti](fsjoyti.md)
>* [xinglunxu](xinglunxu.md)
>* [pranesh-s](pranesh-s.md)
>* [epistulae](epistulae.md)
>* [ctl74100](ctl74100.md)
>* [AdityaNair99](AdityaNair99.md)
>* [Hulmani](Hulmani.md)
>* [sthak004](sthak004.md)
>* [Neha1990](Neha1990.md)
>* [cw-lin](cw-lin.md)
>
>---

**Comment by dogi** [comment]
@fangninghe I kinda like that we distinguish there.

if it was for me I would add other "distinguish-ments" ;)
like `3months` vs `after 10steps` unfortunately that is maybe too much/harsh ;P

maybe we should just put in the start/end dates ;)
and use a markdown table element for that - so we still can add a `Leader` column

@fangninghe what do you think so far?

easy changes I know already about
- [ ] change `Summer 2016 virtual interns` to `virtual interns 2016`
- [ ] @aberdean @mepda and @IshanSoni left and are now exVIs ;)
- [ ] table?

**Comment by waryhermit** [comment]
Maybe something like:

## Active Interns
| Username        | Initial Steps          | Join Date  |
| ------------- |:-------------:| -----:|
| **MrExample (Intern Lead)**     | Complete | 12/1/2016 |
| l33thax0r1337      | In Progress|   1/7/2017 |
| PingTheDuck | Complete      |    1/17/2017 |
## Inactive Interns
| Username | Join Date  | Leave Date |
| ------------- |:-------------:| -----:|
| **ForgottenHero (Intern Lead)**  | 05/7/2014 | 02/13/2015
| SkinnyOgre   | 08/19/2015 |   1/7/2016 |
| FishbellyMcrow | 12/24/2014 |   2/26/2016 |

**Comment by dogi** [comment]
@waryhermit awesome - <3 your **ForgottenHero**

**Comment by dogi** [comment]
what about linking [**(Intern Lead)**](pages/internlead.md) to pages/internlead.md

**Comment by waryhermit** [comment]
@dogi You mean making the usernames links to their pages, or just some special page about intern leads?

**Comment by dogi** [comment]
@waryhermit both link the username to personal page and (intern lead) to new special page

@dogi still does not exactly knows what to write in special page ...

**Comment by dogi** [comment]
Maybe something like:

I linked only first row ;)

## Active Interns
| Username         | Join Date  |
| ------------- | -----:|
| **[MrExample](pages/<username>.md) [(Intern Lead)](pages/internlead.md)**     | 12/1/2016 |
| l33thax0r1337      |   1/7/2017 |
| PingTheDuck |    1/17/2017 |
## Inactive Interns
| Username | Join Date  | Leave Date |
| ------------- |:-------------:| -----:|
| **ForgottenHero (Intern Lead)**  | 05/7/2014 | 02/13/2015
| SkinnyOgre   | 08/19/2015 |   1/7/2016 |
| FishbellyMcrow | 12/24/2014 |   2/26/2016 |

**Comment by dogi** [comment]
@dogi wonders which date format we should use ;)

**Comment by fangninghe** [comment]
@dogi , date format can be MM/DD/YYYY, so all the same length

**Comment by dogi** [comment]
@fangninghe I am more a fan of 20170117 which is YYYYMMDD ;)

**Comment by fangninghe** [comment]
@dogi , only one question, how can I know all the dates?

**Comment by waryhermit** [comment]
@fangninghe I would guess that for our purposes the date they created their user page is close enough to their join date. Dogi might have a better idea for getting the quitting dates though.

**Comment by fangninghe** [comment]
@waryhermit, oh, one more question, the past interns belong to inactive group? Active group only contains current interns?

**Comment by waryhermit** [comment]
@fangninghe Yes, that is correct. You can use the labels `Current` and `Past` instead of `Active` and `Inactive`. I don't think it matters.

**Comment by fangninghe** [comment]
@waryhermit, @dogi , can we just shorten the date format to month? Like YYYYMM

**Comment by dogi** [comment]
> @dogi , only one question, how can I know all the dates?

I think we will never know all the dates, so I am able to accept some blanks ;P


but this is maybe a good time to ask everybody ;)

@FanisGk @prmurphy @hikaruit15 @waryhermit @hannahgdubin : Do you still remember the date you officially finished the 10steps and join the virtual interns?

@aberdean @EmilyLarkin @DrewPerlman @i5o @IshanSon @mepda @fsjoyti @xinglunxu @pranesh-s @epistulae @ctl74100 @AdityaNair99 @Hulmani @sthak004 @Neha1990 @cw-lin @314159265359 : 
Do you still remember the dates you officially joined and left the virtual interns?

If you do please leave a comment ;)

**Comment by waryhermit** [comment]
@dogi I completed all the steps on 12/8/2016 but was not added to the intern channel until 12/13/2016

**Comment by hikaruit15** [comment]
@dogi I don't remember exactly. Maybe 11/17/2016.
