### ISSUE TITLE
First Steps Page Improvements

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/open-learning-exchange.github.io#448]
I want to suggest an improvement for the First Steps Page shown in [here](http://open-learning-exchange.github.io/#!pages/firststeps.md).

I think it would be better if we give a big picture for the aspiring virtual intern including the big picture of the series of steps on the first step. I would suggest the improvement like this.

- Before the heading of Step 0, I suggest creating two heading. One for the **Introduction** and one for the **The Big Picture**

The example of the page should be shown like this:

> **Introduction**

> _the information on the previous version of the first steps here_

> **The Big Picture**

> We believe that the internship process would be very interesting and excited if the intern has a fair (not to mention strong) background on social coding especially using GitHub. The learning platform of OLE, the BeLL-Apps is an open source software at the heart. In this series of steps the aspiring intern would learn about the GitHub collaboration workflow including git, forking, pull request and repo issue. Through this process, the aspiring intern would practice the skills to the real open source project called open-learning-exchange-wiki. We believe that this skills would help you not only in this intern but also in the future of your career as software engineer professional.

> We will not go to the code right now, we will practice the collaboration skills through creating a wiki page for virtual open learning exchange. Besides that, we will go through to setup our development environment before giving our code to the open learning exchange software. Feeling excited? Let's check this out.

Any better idea?
I believe that by adding this information the aspiring virtual interns would have a better understanding what they would do in this series of steps.

**Comment by waryhermit** [comment]
Hey @mappuji !

Could you walk me through how the paragraph you have would give a "*...better understanding what they would do in this series of steps.*" I can see how this might show **why** they might want to do the internship, but that's a decision they are making when they are reading the job posting not doing the steps. That is what I would think anyway.

The current introduction gives an *OK* big picture, but maybe if you can pinpoint why you didn't consider it a good enough overview you can come up with a improvement. It doesn't need to be a big change like a whole paragraph, just editing, deleting, or adding a sentence might make it better.

**Comment by mappuji** [comment]
Hi @dogi !
Thank you for your suggestion. As a revision, I would suggest adding some short sentences.

**from**

> # First Steps
> 
> Welcome to the first steps for becoming an OLE Virtual Intern! We treat these first steps as a vetting process to prove that you can follow simple steps before you can progress to working on harder projects in bigger teams. Because these steps are simple, we expect high-quality work, which may take a longer time. We want to see that you are capable of using or learning how to use these tools (writing good GitHub issues, creating pull requests, navigating the BeLL, etc.). These steps may seem easy, but we want you to impress us with good GitHub etiquette and quality Markdown. The bare minimum would be to just passively follow the steps; you should do further reading about the tools/languages we use so you can further your understanding and relieve confusion if you're unclear about how something works.

**to**

> # First Steps
> 
> Welcome to the first steps for becoming an OLE Virtual Intern! We treat these first steps as a vetting process to prove that you can follow simple steps before you can progress to working on harder projects in bigger teams. Because these steps are simple, we expect high-quality work, which may take a longer time. We want to see that you are capable of using or **learning how to use these tools (writing good GitHub issues, creating pull requests, navigating the BeLL, etc.). Treat this steps as learning opportunity as the Git and GitHub concepts would very useful for you internship and even in your career as software engineer.** These steps may seem easy, but we want you to impress us with good GitHub etiquette and quality Markdown. The bare minimum would be to just passively follow the steps; you should do further reading about the tools/languages we use so you can further your understanding and relieve confusion if you're unclear about how something works.

**Comment by dogi** [comment]
@mappuji I really like it, everything we should and/or want to say is there ...
... but I am no native english speaker ...

@waryhermit @prmurphy @hannahgdubin @fangninghe please give us you feedback ;)

**Comment by hannahgdubin** [comment]
I made a few minor grammar edits but looks good. Posted below is the paragraph with my edits. @dogi @mappuji  

> # First Steps
> 
> Welcome to the first steps of becoming an OLE Virtual Intern! We treat these first steps as a vetting process to prove that you can follow simple steps before you can progress to working on harder projects in bigger teams. Because these steps are simple, we expect high-quality work, which may take a longer time. We want to see that you are capable of using or **learning how to use these tools (writing good GitHub issues, creating pull requests, navigating the BeLL, etc.). Treat this steps as learning opportunity because the Git and GitHub concepts will be very useful for you throughout this internship and even in your career as software engineer.** These steps may seem easy, but we want you to impress us with good GitHub etiquette and quality Markdown. The bare minimum would be to just passively follow the steps; you should do further reading about the tools/languages we use so you can further your understanding and relieve confusion if you're unclear about how something works.

**Comment by fangninghe** [comment]
Hi @mappuji, I like your idea, we need a little explanation of why we want interns to follow the steps. Only one suggestion, do not mention **not to code**, just mention **practice github**.

**Comment by mappuji** [comment]
@fangninghe my point is I want to highlight that we this series of steps is the learning opportunity for the aspiring intern and in this step they are expected to lean about how to collaborate with tool called GitHub. Please see the complete conversation for complete detail.

**Comment by prmurphy** [comment]
@mappuji @hannIt looks good so far, the only thing I would change would be 
>Treat this steps as learning opportunity because the Git and GitHub concepts will be very useful for you throughout this internship and even in your career as software engineer.

to

>Treat this steps as learning opportunity because Git and GitHub concepts will be very useful for you throughout this internship and even in your career as software engineer.

I think the "the" sounds kind of awkward since were not referring to specific concepts, but concepts in general.
