### ISSUE TITLE
Directories for GitHub

### ISSUE THREAD

**Issue by Ebuka-Chibueze** [open-learning-exchange/open-learning-exchange.github.io#449]
I think the [Github Repositories](http://open-learning-exchange.github.io/#!pages/gitandrepositories.md) page should mention where to clone your repository. Some directories will not allow you to have write access.

**Comment by Ebuka-Chibueze** [comment]
I've noticed certain directories give this message:
<code>fatal: could not create work tree dir 'REPO-NAME': Permission denied </code>

I think the steps should tell people to be in the default directory before using the <code>git clone</code> command. This should prevent that error message.

**Comment by dogi** [comment]
@Ebuka-Chibueze hmm - do understand generally what you are saying,
but from a perspective of the 10steps and all the supported OS'es,
this is a windows issue only and you are only getting into it if you are not following the 10steps

hereby I decide to close it
