### ISSUE TITLE
Create Community Login page.

### ISSUE THREAD

**Issue by mtencza1** [open-learning-exchange/open-learning-exchange.github.io#452]
**waryhermit update**:
To resolve this issue you should:

1. Create a page that has an explanation of what to do if the BeLL apps does not load, and a link to the local vi community.
2. Make "Community Login" menu item point to this new page.

----------
**Old Post**
A few days ago when I started the first steps I noticed that the address that accessed the communityBeLL through Firefox was not working for some reason and it confused me during the installation process as I wasn't sure if I made an error installing. 

I would suggest having a section (preferably near the top) on the BeLL installation page -[https://github.com/dogi/ole--vagrant-vi/blob/master/README.md](url) 
that would say something such as 

> Status - Operational

or 

> Status - Currently down

that should be updated upon any status change of the community BeLL address so that future interns wouldn't be confused when there was an issue if it is only temporary and of no fault of their own.

**Comment by dogi** [comment]
@mtencza96 do I understand you right, you mean the 

![74-9](https://cloud.githubusercontent.com/assets/13684059/22138597/7f513006-deaf-11e6-8c81-2d184e4da61e.png)

`community login` link, which points to http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html

**Comment by mtencza96** [comment]
Yes, that was the one I had an issue with when I started that seemed to resolve itself without any action on my part.

**Comment by dogi** [comment]
@mtencza96 open `git bash` and then type `cd ole--vagrant-vi` and after that `vagrant halt`
now try the link again ...

**Comment by dogi** [comment]
@mtencza96 do you see want I mean?

**Comment by waryhermit** [comment]
@mtencza96 To be more explicit, the website (http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html) is hosted by a virtual machine managed by vagrant. There is no way for `http://open-learning-exchange.github.io` to know if you have the virtual machine on and running. If you don't, you won't be able to access the community page. This is covered in the FAQ, and I think some other interns have just added that information elsewhere as well.

I supposed it might be possible the `Community Login` link bring you to a page with a link to (http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html) and a note explaining what to do if it is unreachable. Doesn't seem that necessary to me, but it seems many people are confused by this so it might not hurt.

@dogi Thoughts?

**Comment by dogi** [comment]
@waryhermit I like that idea - but I do not know how difficult it will be to change navigation.md to do that

**Comment by prmurphy** [comment]
On Jan 20, 2017 12:07 AM, "mtencza96" <notifications@github.com> wrote:
>
> A few days ago when I started the first steps I noticed that the address
that accessed the communityBeLL through Firefox was not working for some
reason and it confused me during the installation process as I wasn't sure
if I made an error installing.
>
> I would suggest having a section (preferably near the top) on the BeLL
installation page -
https://github.com/dogi/ole--vagrant-vi/blob/master/README.md
> that would say something such as
>>
>> Status - Operational
>
> or
>>
>> Status - Currently down
>
> that should be updated upon any status change of the community BeLL
address so that future interns wouldn't be confused when there was an issue
if it is only temporary and of no fault of their own.

**Comment by waryhermit** [comment]
@dogi I think it would be as simple as creating a new page with the info on it, and changing the line `  * [Community Login](http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html)` to `  * [Community Login](pages/newCommunityLogin.md)`

**Comment by dogi** [comment]
@waryhermit I like this idea of go to an new page first ...
... and explain there maybe more stuff

**Comment by Loshma93** [comment]
@mtencza96 I think you have to 
1. Open Command prompt or Command prompt( as admin) or Git Bash
2. Goto ole--vagrant-vi-master by giving the command cd ole--vagrant-vi-master
2. Give the command: vagrant up

**Comment by waryhermit** [comment]
To clear it up for anyone who is wondering - to resolve this issue you should:

1. Create a page that has an explanation of what to do if the BeLL apps does not load, and a link to the local vi community.
2. Make "Community Login" menu item point to this new page.
