### ISSUE TITLE
[Idea] Transform this mdwiki into an htmlapp

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#458]
If our mdwiki was also a working offline standalone HTML app, we could have it as a resource in BeLL-Apps. In order for it to work as a HTML app the markdown wiki must work offline (internet disabled) as local files on your computer **and** still work when uploaded to github.

In other words, this repo should be a working markdown wiki both online and as stand alone files on your computer. This means relative links, and replacing references to remote resources must be converted to local resources. This might mean we have to include a copy of jquery in our repo.

After it works offline and online, it could be added to the BeLL-Apps as a html resource following the steps [here](http://open-learning-exchange.github.io/#!pages/htmlresources.md).

I tried it I tested the [original example mdwiki](https://github.com/Dynalon/mdwiki/releases) and it kinda works.

**Comment by mappuji** [comment]
Hi @dogi , I think it is possible to implement. But, my question is where we will put the htmlapp results? Is it on the open-learning-exchange.github.io and I can raise a PR for this?

**Comment by waryhermit** [comment]
@mappuji I would be rather impressed if you were able to get this working. I updated his post to try and make it more clear - we were just talking about it in the weekly intern meeting. If you can get your personal fork of the `http://open-learning-exchange.github.io` to work online and offline, by all means, make a pull request. :)

**Comment by mappuji** [comment]
@waryhermit and @dogi I have made the htmlapp works offline. Currently pushing the resource to the nation. I found that the upload speed only around 88 Kbps. Still waiting.

**Comment by waryhermit** [comment]
Very good job so far. I am very impressed. When I disable the internet the nav bar goes white. Other than that I didn't notice any problems clicking around. I haven't checked it as a couchapp yet.

**Comment by dogi** [comment]
@mappuji look at https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/462#issuecomment-274483304

**Comment by paulbert** [comment]
I've found another solution to the css and js assets.  Right now we use the "slim" version of mdwiki which uses CDNs for css & js libraries, but the full version puts all of those assets inline in the html. Rather than needing to create this new file structure, if we use a lightly modified version of mdwiki it'll work offline.  I'll make a PR in a minute with the change.

**Comment by waryhermit** [comment]
The markdown wiki now works offline, so this issue should be less difficult. You pretty much just need to follow the directions at [html resources.](http://open-learning-exchange.github.io/#!pages/htmlresources.md)

**Comment by paulbert** [comment]
@waryhermit @dogi So it got a little lost in the shuffle, but I was just now trying to push this to the nation and it's stuck with the spinner going.  It is, however, now in the Pending Resources list on the nation.

**Comment by paulbert** [comment]
Ok, the Virtual Intern mdwiki is now on the VI nation.

**Comment by mappuji** [comment]
I think we can close this issue since @paulbert has ported the app to the BeLL-App.
See #681 for complete docs.
