### ISSUE TITLE
Improve Vagrant pages

### ISSUE THREAD

**Issue by Sheepinav** [open-learning-exchange/open-learning-exchange.github.io#467]
I just noticed that the Windows version of Step 2 contains background on what vagrant is used for and its relation to BeLL. However, the Mac/Ubuntu version of this page does not have that information, so potential interns might miss that information. An explicit introduction to vagrant is also not there on step 1 where we install vagrant on OSX and ubuntu.

Windows Introduction:
![screenshot 2017-01-23 16 38 01](https://cloud.githubusercontent.com/assets/18740303/22229091/606da1e6-e18a-11e6-928e-f11b977090a2.png)

Mac introduction:
![screenshot 2017-01-23 16 38 59](https://cloud.githubusercontent.com/assets/18740303/22229102/75d8c70e-e18a-11e6-8f38-857316f06198.png)

I simply suggest adding the information to the Mac page in another pull request.

**Comment by dogi** [comment]
@Sheepinav to speak a level more meta then you

what are the concrete differences between the both

- introduction in windows terminal `git bash`
- theoretically windows should reboot automatically
- and macubuntu not
- so macubuntu need to start eveything by hand
- ???

missing is
- an windows exercise where after automatic booting aspiring interns stop the virtual machine
- ???

**Comment by waryhermit** [comment]
The vagrant background stuff is short enough perhaps it would make more sense to move it to the http://open-learning-exchange.github.io/#!pages/firststeps.md#Step_#2:_Vagrant_Tutorial: section, instead of duplicating it in both vagrant sections

**Comment by dogi** [comment]
@waryhermit like spot on - I also think we should bundle basic `vagrant` stuff on one page

**Comment by Chris-Boe** [comment]
Hey @dogi , with your last comment, did you mean that you want all the Vagrant Installation instructions (Windows + Mac, Wiki + README.md) on one MD page?

**Comment by dogi** [comment]
@Chris-Boe kinda - since latest windows installer by one line made us split the vagrant step into win and nonwin we did ...

mostly what I am trying to say is that this split was maybe not the best way to do that so I am very happy for suggestions which improve that

I know that is very abstract but I still hope I make sense ;)

**Comment by dogi** [comment]
by the way I was also thinking about splitting it into 3 pieces:
- [ ] only windows
- [ ] mac and ubuntu
- [ ] vagrant overview

**Comment by Chris-Boe** [comment]
@dogi, sounds great! I was thinking then:
  * Vagrant overview on the First Steps page (under [step 2](http://open-learning-exchange.github.io/#!pages/firststeps.md#Step_#2:_Vagrant_Tutorial) with links to the Mac/Ubuntu & Windows sections

  * Have a Mac/Ubuntu section that includes everything except introduction from [mac/ubuntu](http://open-learning-exchange.github.io/#!./pages/vagrant.md). In addition, how Mac/Ubuntu is different from Windows (like your earlier comment), as well as the Mac/Ubuntu instructions from the [readme](https://github.com/dogi/ole--vagrant-vi)

  * Have a Windows section that includes everything except introuduction from [windows](http://open-learning-exchange.github.io/#!./pages/vagrantwin.md). In addition, how Windows differs from Mac/Ubuntu, as well as the Windows instructions from the readme.

The "differences" discussed in each section would be specific to the OS so it would not be repetitive.
i.e. in Windows section:
   **The Windows version has a .bat file that starts up the VM vi when Windows boots...**
  in Mac/Ubuntu section:
   **The Mac/Ubuntu version of vi must be started by hand every time the computer boots by using the commands: ... **

Let me know how this sounds and I can get a draft going

**Comment by waryhermit** [comment]
Here is what I would do:

Change `firststeps.md` Step 2 from this:

> # Step 2 - Vagrant Tutorial:
> ## Windows
>
> Review these Vagrant instructions to get familiar with Vagrant, since you will need to use it during your internship.
> ## MacOS(X) and Ubuntu
>
> Review these Vagrant instructions to ensure that you have fully completed the previous step.

To this:
> # Step 2 - Vagrant Tutorial:
> Vagrant is an open source tool to build development environments. In the previous step, you followed the first instructions on README.md to install a BeLL virtual machine on your system. You may have noticed that one of the programs listed as dependencies was Vagrant.
> 
> We use Vagrant to power up our BeLL virtual machine. While this is done automatically (behind the scenes, as it were), it is useful for you to understand how to use Vagrant, because during your internship you may have to use it manually.
>
> You should follow the [vagrant instructions here](www.somelink.com) to get a good idea for how it works.

Then delete the first paragraph of `vagrant.md` and then append the contents of `vagrantwin.md` at the top of `vagrant.md` (except the first paragraph). Then change the `First Steps` menu to only link to `vagrant.md`.

**Comment by snazzybunny** [comment]
I did something similar in #769, oops.

**Comment by waryhermit** [comment]
@dogi @mappuji @paulbert Did #768 fix this issue?

**Comment by dogi** [comment]
@waryhermit thanks
