### ISSUE TITLE
Markdown tutorial

### ISSUE THREAD

**Issue by shabiba** [open-learning-exchange/open-learning-exchange.github.io#468]
Markdown tutorial

**Comment by shabiba** [comment]
please check this http://www.markdowntutorial.com/lesson/1/

**Comment by mappuji** [comment]
@shabiba , could you explain me a little more about what you mean?

**Comment by dogi** [comment]
I <3 this link @shabiba


@shabiba are you suggesting we should add this link to our 10 steps?

Please be more precise and/or make an example for your suggestion

**Comment by Chris-Boe** [comment]
@shabiba @dogi I love this idea! This site really helped me practice Markdown and it'd be great to have this on the Step 3 [page](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md), then people can practice a little more before they make their page. Being able to see the results as you type really helps.
If @shabiba would let me backpack on this idea, what if we put it on the Step 3 page as an extra resource under the "Useful Links" header near the bottom, as well as right after the cheat sheet where it says "You can also find a bigger cheat sheet with examples here".
Maybe add "If you want practice using Markdown, check out *this site* to explore the MD syntax and see results as you type."

**Comment by hikaruit15** [comment]
Hi @shabiba,
Basically, we already have this link in our site.
Let check it out: http://open-learning-exchange.github.io/#!pages/faq.md#Helpful_Links
And click to `Markdown Interactive Tutorial` link.

**Comment by Chris-Boe** [comment]
Hi @hikaruit15 , maybe we could add that link to the Markdown wiki? I know I didn't think of finding more  helpful links in the FAQ than in the appropriate page, so it'd be helpful to reference that page near the beginning before we start making the personal .md file.

**Comment by dogi** [comment]
@hikaruit15 good point, but also have to say that here I kinda agree with @shabiba and @Chris-Boe 

wonder mostly which markdown elements we will use to advertise this link plus description text ...

**Comment by Chris-Boe** [comment]
@dogi Maybe:
"If you want practice using Markdown, check out [this site](http://www.markdowntutorial.com/lesson/1/) to explore the MD syntax and see results as you type."
in the area I mentioned earlier. Then:
[Markdown Tutorial Lessons](http://www.markdowntutorial.com/lesson/1/)
under the "Useful Links" section near the bottom, above "Mastering Markdown" link.

**Comment by waryhermit** [comment]
@Chris-Boe Seems fine to me. Care to create a branch with the changes and then make a pull for us to review?
