### ISSUE TITLE
Fix directory structure

### ISSUE THREAD

**Issue by sente** [open-learning-exchange/open-learning-exchange.github.io#47]
The top level `ll_CC` directory should be removed (or changed to `en_US` as this wiki is in English only).

**Comment by sente** [comment]
Look at https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/47-fix-directory-structure

**Comment by i5o** [comment]
Tested, and seems to work
https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/47-fix-directory-structure/index.html#!index.md

**Comment by dogi** [comment]
@i5o thanks for this https://rawgit.com
