### ISSUE TITLE
Markdown tutorial could explicitly state "use links and/or images" 

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/open-learning-exchange.github.io#474]
A couple of pages from the markdown tutorial have gotten good feedback except for missing one of the more complex markdown tags.  I propose we add a line to explicitly ask for that in the tutorial.

**Comment by paulbert** [comment]
I think we could simply add the phrase in bold here:

> In the new file, please type your name, your location/time zone, and OS (including version). In addition, make sure to add a short description of yourself as well, so your fellow virtual interns know who you are. Also try to use several Markdown elements in your page to get an idea for how it works, **including some images and/or links to practice the more complex syntax**.

**Comment by Chris-Boe** [comment]
@paulbert I agree, I think this is a good idea as I got the same feedback in your first comment ;) Though having some ambiguity instead of blatant direction does stoke some creativity in potential interns.

**Comment by waryhermit** [comment]
Originally there was no requirement for link or image, you can see that some user pages don't have either of those. (Example: http://open-learning-exchange.github.io/#!pages/prmurphy.md )

If @dogi wants to formally change the requirements, then this could use a pull request.

**Comment by dogi** [comment]
:D 

sorry but some personal pages out of the box look very awesome
and others don't - this are the ones I always suggest to add a markdown link element
but I think I do not wanna make it a rule

anyhow what I mostly like is the interaction between PR'er and the Reviewers
and I think we should write more about what should/will happen after the PR ...
so that aspiring virtual interns are more prepare to the dialog on top of a PR

@paulbert @Chris-Boe does that what I say make sense?

**Comment by Chris-Boe** [comment]
@dogi That makes sense. Is there something specific you wanted to add to the end of the Markdown Wiki about the PRs and Reviewer relationship? If we were to get that Review Process stuff added discussed in [#422](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/422), then we could add those instructions.

**Comment by paulbert** [comment]
@dogi I also think that makes sense.  The PR section is a bit light on the process.  How about (changes in bold):

Then, you can create a pull request by clicking the `Pull requests` button and then clicking `New pull request`. Finally, click `Create pull request` **and someone from our team will review the changes.  Often there will be some feedback from the reviewer at this point for you to address.  If that is the case, make changes to your branch and comment on the pull request when done.  Any changes you make to your branch will automatically affect the pull request.  Once everything looks good, the reviewer will merge your page with the main repository.** 

After the pull request is completed, you'll be able to see this on open-learning-exchange.github.io in addition to your personal page. Let us know when you have completed this step in the [gitter.im chat](https://gitter.im/open-learning-exchange/chat).

@Chris-Boe I also agree that this is quite similar to #422.  Maybe it'll get changed once that one is resolved, but this might help the interns starting out until there review request process in place.

**Comment by dogi** [comment]
@paulbert sorry for my delayed answer 

I very like your suggestion and think that this issue hereby is ready for a `pull request`

**Comment by waryhermit** [comment]
Merged your pull request, #525
