### ISSUE TITLE
Change link for previewing personal page in step #3

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/open-learning-exchange.github.io#475]
The link at the end of Step #_3_: Markdown and Fork will be a blank page the page is not added to the master branch because GitHub Pages builds only off of the master branch.

**Comment by paulbert** [comment]
In Step #_7_ the link for changes is at the rawgit.com domain, which allows us to view changes from other branches.  We should also use this in Step #_3_ so people can preview their pages without merging to the master branch (and put it in a code tag for consistency). Specifically change this:
>Now, check what this looks like on your own page (<username>.github.io/#!pages/<username>.md)
to this:
>Now, check what this looks like on your own page `https://rawgit.com/YourUserName/YourUserName.github.io/YourBranchName/#!pages/YourUserName.md`

**Comment by waryhermit** [comment]
@paulbert That seems like a good idea, feel free to make a pull request. 😄

**Comment by dogi** [comment]
+1

**Comment by hikaruit15** [comment]
@paulbert it's great!

**Comment by waryhermit** [comment]
Fixed by #478
