### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/open-learning-exchange.github.io#479]
Right now if a page isn't found it will just be blank.  Having a generic 404 page would help interns who may be using GitHub Pages for the first time instantly know their new page isn't working because the file isn't found.

**Comment by waryhermit** [comment]
@paulbert Some quick googling gives me the impression that this is actually not very easy in MDwiki. If you can figure out how, go for it!

**Comment by paulbert** [comment]
@waryhermit That did turn out to be a bit more difficult than I thought it would be, but in the end just needed to use a more up to date version of mdwiki.  I ended up manually building it off of their 0.6.x branch.  See the 404 here: https://rawgit.com/paulbert/paulbert.github.io/add_404/#!pages/firststes.md

**Comment by waryhermit** [comment]
@paulbert So what kind of changes would we have to make? You didn't make a pull request so it isn't clear to me how much trouble this would be to add.

**Comment by paulbert** [comment]
@waryhermit Ok, so I just made the pull request to make it easier to view the changes.  It's just a 404.md page and a newer version of mdwiki.
