### ISSUE TITLE
Introduction to Internship on "First Steps" Page

### ISSUE THREAD

**Issue by Chris-Boe** [open-learning-exchange/open-learning-exchange.github.io#481]
Since the "First Steps" page is the first page, in my experience, that a potential intern sees, I think it'd be helpful for potential interns to have a clear idea of OLE and the internship as they start the first steps process. The FAQ page is introduced as more of a technical questions and assistance page than it is a general questions page so people may not think to find this information there.

My proposition is to add a couple of the explanations from the [FAQ](http://open-learning-exchange.github.io/#!pages/faq.md#Helpful_Links) page (slightly edited) to the [First Steps](http://open-learning-exchange.github.io/#!pages/firststeps.md) page, near the top. Specifically, the explanations of:

  * What will I be working on in this internship?
  * What kind of software will we be using for this internship?
  * Where can I find more information about this internship?
  * What happens after the initial steps

Let me know if this would be okay! It would certainly be helpful in my opinion. :) 
Possibly combining this with mappuji's [First Steps Page Improvements](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/448) would be helpful I think.

**Comment by dogi** [comment]
> Possibly combining this with mappuji's First Steps Page Improvements would be helpful I think.

like that the most ;)

**Comment by waryhermit** [comment]
@Chris-Boe I look forward to seeing a pull request with the suggested changes. :)

**Comment by Chris-Boe** [comment]
Hey @waryhermit @dogi @mappuji , here are my suggested changes.
I realize this makes the intro to the Steps a bit long, so feel free to suggest changes, or we could separate out a "First Steps" page with a "Welcome" page (with a link to the steps) and have the Welcome page be the first one the candidates see.
Most changes are in bold, but there are some things that were reordered as well.

# The Big Picture
Welcome to the first steps for becoming an OLE Virtual Intern! We treat these first steps as a vetting process to prove that you can follow simple instructions before you can progress to working on harder projects in bigger teams. **Consider them to be the interview for the internship. 

If you are deemed fit for the internship after completing the steps, you will be officially invited to join the OLE interns team! We’ll add you to the interns Gitter chatroom and assign you to a specific team to work on developing and improving OLE’s BeLL (Basic e-Learning Library) software. The BeLL is a virtual library that is deployed internationally to children in countries that typically do not have access to educational resources. 

Once accepted, you and your team will work on an assignment, and we’ll switch up the assignments each week. As part of this internship, you will be working with software and languages including Git, GitHub, Gitter, Markdown, Vagrant, VirtualBox, Command Line/Terminal, Command Line/Terminal Scripts, Vim, CouchDB, Docker, HTML5, Javascript, and Node.js.

**Note:** *This is an unpaid but intensive internship that requires 16 hours of work each week. More information about the internship can be found [here](https://www.indeed.com/jobs?q=%22virtual+software+engineer+intern%22&l=Cambridge,+MA). If you have further questions, don’t hesitate to ask other members in the Gitter [chat](http://open-learning-exchange.github.io/#!pages/chat.md)!*

# The Steps
Social coding is a huge part of any open source and collaborative project, and the Open Learning Exchange is no different. In the following series of steps, you will learn about the Github team workflow, including git, forking, pull requests, and repository issues. You will also be introduced to Markdown’s rich text formatting and OLE’s Basic e-Learning Library (BeLL), the digital library that hosts the learning materials.**

Because these steps are simple, we expect high quality work, which may take a longer time. We want to see that you are capable of using or learning how to use these tools (writing good GitHub issues, creating pull requests, navigating the BeLL, etc.). These steps may seem easy, but we want you to impress us with good GitHub etiquette and quality Markdown. The bare minimum would be to just passively follow the steps; you should do further reading about the tools/languages we use so you can further your understanding and relieve confusion if you're unclear about how something works. Treat these steps as learning opportunities! The Github and Markdown skills you practice here are very important in both this internship and a future software development career. 

We created a [FAQ page](http://open-learning-exchange.github.io/#!pages/faq.md#Helpful_Links) where you can find the answers to some commonly asked questions, **both technical and general**, and also some very useful links and video tutorials that will help you become familiar with the tools/languages we use. For anything that is not in the FAQ page, Google and Stack Exchange are your friends :)

We also want you to keep us updated a relatively good amount in the [Gitter chat](http://open-learning-exchange.github.io/#!pages/chat.md) as you complete these steps. Generally, you should comment in the Gitter chat when you make an issue or pull request, and then link to it. It's also good form to mention someone in Gitter when you comment on their issue/pull request, and of course link to it. For example: "Hey @dogi, just commented on your issue: https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/15"

A very large part of these steps is finding problems with these steps and this MD wiki, so make sure to take note of any issues that you run into or suggestions for improvement while doing these steps. Think of it as improving these steps and this MD wiki for future interns. 

**There is no official deadline to complete these steps, but most candidates who are approved for the internship program finished the steps within 7-8 days.** Good luck!

**Comment by dogi** [comment]
@Chris-Boe think this is ready for a `pull request` ;)

**Comment by Chris-Boe** [comment]
Thanks @dogi! There's one possible change @hannahgdubin brought up in the closed PR [492](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/492). 
The change would remove the following paragraph:
![image](https://cloud.githubusercontent.com/assets/8600792/23202489/ff5f3bf6-f892-11e6-9ec6-f5553c685bf4.png)

and replace it with 
"We also want you to keep us updated a relatively good amount in the Gitter chat as you complete these steps. Please check the Gitter chat page for more information about how to best communicate in Gitter."

**Comment by dogi** [comment]
`We also want you to keep us updated a relatively good amount in the Gitter chat as you complete these steps. Please check [our Gitter chat page](pages/chat.md) for more information about how to best communicate in Gitter.`
