### ISSUE TITLE
Add temporary vagrant note to BeLL-Apps Page (Step 4)

### ISSUE THREAD

**Issue by Chris-Boe** [open-learning-exchange/open-learning-exchange.github.io#486]
**waryhermit update:**

To resolve this issue someone should create a big Note at the top of the windows directions stating something like:

> **Note**: There appears to be an issue with our vagrant auto start task on windows. You will need to run the command `vagrant up` in the folder `C:\Users\YOUR-USERPROFILE\ole--vagrant-vi` before you can access the BeLL-Apps.
-------
**Original Issue:** 

On the [BeLL-Apps](http://open-learning-exchange.github.io/#!pages/bellapps.md), the MacOSx/Ubuntu instructions say to always make sure the vagrant vi is running when you want to use BeLL, but the Windows section does not state this. This might be missed by potential interns using Windows machines as they read through the steps.
I suggest we add under the **Windows** heading:
*Please, check that your vagrant is up and running with **vagrant global-status**. Assuming that it's running or you launch it using **vagrant up**, please double click on the...*
then continue with the rest of the tutorial.
![capture](https://cloud.githubusercontent.com/assets/8600792/22720140/f6004c66-ed5d-11e6-8244-38c68ad59057.PNG)

**Comment by waryhermit** [comment]
@Chris-Boe Yeah, that is because there is supposed to be a Windows Scheduler Task to make the VM run each time you boot on windows, but it is currently broken. If you want to give a shot fixing it see https://github.com/dogi/ole--vagrant-vi/issues/18 and https://github.com/dogi/ole--vagrant-vi/blob/master/windows/install.ps1

**Comment by Chris-Boe** [comment]
@waryhermit I'll do some research to see if I can help but no guarantees ;)
Regardless, I think it would be a helpful tidbit for Windows users to know that the vagrant VM should be running while working in the BeLL, so that they know they can check it for troubleshooting purposes, especially while the Startup process is malfunctioning.

**Comment by dogi** [comment]
@Chris-Boe I think that https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/467 got created because of a similar reason

that is why I close this issue (duplication)

**Comment by Chris-Boe** [comment]
@dogi, I believe [#467](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/467) is talking about some missing info in the Mac section of the Vagrant installation process of Step 2. My issue concerns the necessary knowledge that Vagrant should be up before opening the BeLL apps on Windows, just in case the Windows task did not get run correctly on boot or if the user suspended or halted the VM.
We can combine these if you like into a single PR :)

**Comment by dogi** [comment]
> We can combine these if you like into a single PR :)
@Chris-Boe Yes ;)

**Comment by waryhermit** [comment]
@Chris-Boe 

As far as vagrant not starting on login, I have a fix that worked for my computer but not @sarvanivadali 

I deleted the scheduled task created be the BeLL install script that didn't work. Then I ran the following script in a Powershell **opened with administrator privileges:**


```ps1
$repo = "ole--vagrant-vi"
$Stt = New-ScheduledTaskTrigger -AtLogon
$Sta = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass  $HOME\$repo\windows\vagrantup.ps1" Register-ScheduledTask TestVagrantUp1 -Action $Sta -Trigger $Stt
```

If you could try this sometime for me that would be nice.

**Comment by waryhermit** [comment]
If someone wants to make it more clear that for most windows users vagrant does not auto start correctly as a temporary note that would be fine.

**Comment by Chris-Boe** [comment]
@waryhermit if we could have more people try your script, we can narrow down why/when it might not work. It seems like it's still working alright on my machine. Also I thought @sarvanivadali uses Mac as it says on her profile? If she tried it on a Windows computer, it'd be nice to know which version of Windows, etc.
It'd also be helpful to separate these issues, since it is not essential to the original idea of this issue ;)

**Comment by waryhermit** [comment]
@Chris-Boe No, she has a mac and a windows, she already tried it on her windows machine. Its the scheduled task that doesn't seem to work though but I don't know why... some kind of group policy or something perhaps. I need to find out if it would make a log anywhere or if I could turn that on. But yeah I need to get more people to try it, and see if I can make the window hidden or at least minimized when it auto starts. That shouldn't be too hard at least.

**Comment by waryhermit** [comment]
To resolve this issue someone should create a big Note at the top of the windows directions stating something like:

> **Note**: There appears to be an issue with our vagrant auto start task on windows. You will need to run the command `vagrant up` in the folder `C:\Users\YOUR-USERPROFILE\ole--vagrant-vi` before you can access the BeLL-Apps.
-------
The real issue here is that there is a problem with our windows vagrant task. I will create an issue for people to test my script at `ole-vi/BeLL-Apps`

**Comment by waryhermit** [comment]
I think the vagrant issue has been fixed, so I will close this unless we get a bunch of people having trouble.
