### ISSUE TITLE
MDWiki Tab name is always "Your wiki name"

### ISSUE THREAD

**Issue by pranesh-s** [open-learning-exchange/open-learning-exchange.github.io#49]
When loading the mdwiki pages, the tab names are initially 'MDWiki', but changes into 'Your wiki name' immediately after.

**Comment by dogi** [comment]
think we should change that into "OLE | Virtual Interns",
but maybe somebody has a better suggestion ...

**Comment by alan459** [comment]
Perhaps we can change the tab name to reflect the content it's displaying, such as naming the Github Issues tab just that.

**Comment by pranesh-s** [comment]
With regards to the tab name, OLE | Virtual Interns seemed to work better than the content itself as content titles seemed a bit generic/misleading by themselves, and the name ended up being too long with both @dogi and @alan459 's suggestions combined. I suppose that we can always change it again if required. For now, I have a submit a pull request with the config.json updated with the new title, "OLE | Virtual Interns".

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/commit/d413e86cc26d2ec34b0998d7fd4fc8a5d6850c68 done
