### ISSUE TITLE
unresolved conflict.

### ISSUE THREAD

**Issue by shabiba** [open-learning-exchange/open-learning-exchange.github.io#494]
Have been getting this error (error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.) whenever i try to  sync to open-learning-exchange.github.io.

**Comment by shabiba** [comment]
will be happy if able to resolve  this issue

**Comment by hikaruit15** [comment]
Hi @shabiba,
I have a little confusion about what you are talking. Can you add more information (such as screenshots..)?

**Comment by shabiba** [comment]
![capture](https://cloud.githubusercontent.com/assets/21336208/23046682/d89a042e-f45f-11e6-8e58-6c5cc2f636a9.PNG)
check this please

**Comment by hikaruit15** [comment]
Did you google it yet?
I found some articles here. It maybe help you.
http://stackoverflow.com/questions/36086202/git-merge-is-not-possible-because-i-have-unmerged-files
http://stackoverflow.com/questions/12961752/git-merge-error-commit-is-not-possible-because-you-have-unmerged-files

**Comment by shabiba** [comment]
thanks @hikaruit15 but still not working

**Comment by hikaruit15** [comment]
Can you show me the steps you do?

**Comment by shabiba** [comment]
ok @hikaruit15

**Comment by shabiba** [comment]
![capture](https://cloud.githubusercontent.com/assets/21336208/23189495/f476f0d0-f847-11e6-8b93-887e247f43f2.PNG)

**Comment by sarvanivadali** [comment]
Hi @shabiba can you also paste a screenshot of git status too?

**Comment by shabiba** [comment]
ok

**Comment by shabiba** [comment]
![capture](https://cloud.githubusercontent.com/assets/21336208/23189890/ff758f6c-f849-11e6-8051-c191a78ad847.PNG)

**Comment by shabiba** [comment]
@sarvanivadali this is the result after using p4 merge
![capture](https://cloud.githubusercontent.com/assets/21336208/23314996/06d8a862-fa79-11e6-99cb-948bd2f9ea3b.PNG)

**Comment by Chris-Boe** [comment]
@shabiba, I PMed you on Gitter concerning this issue. If you still cannot merge your .md, have you tried deleting your **personal** repo (both local and on Github), then reforking it from OLE? Of course, save your .md file and any other files you were planning on committing in another location before deleting the repo.

**Comment by sarvanivadali** [comment]
Hi @shabiba Also if you can, save changes to your personal page (one approach is to save it on yourdesktop or use ```git stash``` to stash your changes), then use ```git checkout upstream/master -- pages/shabiba.md```. Were you trying to modify your file?

**Comment by waryhermit** [comment]
@shabiba Were you ever able to figure this out?

**Comment by waryhermit** [comment]
I will close this for now.
