### ISSUE TITLE
Markdown Tutorial is already linked

### ISSUE THREAD

**Issue by Ebuka-Chibueze** [open-learning-exchange/open-learning-exchange.github.io#497]
The  [Markdown Interactive Tutorial](http://www.markdowntutorial.com/lesson/1/) is listed in the [GitHub and Markdown](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md#Useful_links) page and the [FAQ](http://open-learning-exchange.github.io/#!pages/faq.md#Helpful_Links). I think this is a bit confusing and redundant. Someone could go to that link from the FAQ expecting a different page.

**Comment by Ebuka-Chibueze** [comment]
As far as I can tell, this is the only link that is referenced in both the Useful links section and the Helpful links section for any of the steps in the Markdown wiki.

**Comment by dogi** [comment]
@Ebuka-Chibueze ;)

**Comment by waryhermit** [comment]
Fixed by #514
