### ISSUE TITLE
Suggestion for First Steps

### ISSUE THREAD

**Issue by Ebuka-Chibueze** [open-learning-exchange/open-learning-exchange.github.io#499]
I noticed the [First Steps](http://open-learning-exchange.github.io/#!pages/firststeps.md) page mentions the FAQ and the links it provides. I believe we should make a slight tweak to this page.

 Newcomers are told that "For anything that is not in the FAQ page, Google and Stack Exchange are your friends :)". While this is obviously great advice , they can also save some time using the Useful links at the bottom of each page. This could be mentioned right before the suggestion to look at the FAQ's links. 

 The information at the bottom of each page tends to be more specific for completing the steps. The FAQ's information seems to be more generalized. Because of this I think it would be important to emphasize the Useful links alongside the FAQ and the other sources mentioned.

**Comment by dogi** [comment]
@Ebuka-Chibueze very convincing ;)

but can you also get more concrete?

**Comment by waryhermit** [comment]
Perhaps make a pull request so we can get an idea of what exactly you have in mind

**Comment by waryhermit** [comment]
@Ebuka-Chibueze Does https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/519 address this in your opinion ?
