### ISSUE TITLE
Navigating GitHub Help section

### ISSUE THREAD

**Issue by Ebuka-Chibueze** [open-learning-exchange/open-learning-exchange.github.io#501]
I think it would be great if this [link](https://help.github.com/categories/search/) could be added to the MDwiki. It's also from the GitHub Help section. This search bar can come in handy for finding general information. I think it could go in the useful links for the [GitHub and Markdown](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md#Useful_links) page or the helpful links in the [FAQ](http://open-learning-exchange.github.io/#!pages/faq.md#Helpful_Links).

**Comment by dogi** [comment]
I like this idea very much

@Ebuka-Chibueze how would you procede from here?

**Comment by Ebuka-Chibueze** [comment]
I will add it to the [FAQ](http://open-learning-exchange.github.io/#!pages/faq.md#Helpful_Links) since it covers a lot of topics
