### ISSUE TITLE
Use SSH instead of HTTPS for Git repository as a bonus step.

### ISSUE THREAD

**Issue by sarvanivadali** [open-learning-exchange/open-learning-exchange.github.io#502]
Step #5: Keeping Fork Updated:#
Suggests using HTTPS but most organizations use SSH and two-factor authentications. It would be nice if we add SSH as a bonus step while clone repository.

**Comment by dogi** [comment]
@sarvanivadali you mean working with sshkey?
https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by dogi** [comment]
and with step5 you mean http://open-learning-exchange.github.io/#!pages/gitandrepositories.md

**Comment by sarvanivadali** [comment]
Yes. Sorry I corrected title and subject. I meant using SSH as a bonus step.

**Comment by dogi** [comment]
Awesome I like that ;)

**Comment by dogi** [comment]
@waryhermit @leonardmensah @hikaruit15 @hannahgdubin @mappuji wonder if you also think this worth while making a PR?

@sarvanivadali so concrete how would you do it?
