### ISSUE TITLE
Brainstorm about design work for interns?

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#504]
Since lately many of the virtual intern have also design skills

I wonder if we can create a task for them

Generally I was think about on graphic program (e.g. Gimp, Photoshop, ...) centric action
where the blue print to improve/re-design is:
- [ ] [OLE website](https://ole.org) with subpages
- [ ] [Virtual Intern Wiki](https://open-learning-exchange.github.io) with subpages
- [ ] [Bell-Apps](http://vi.ole.org/)

also to brainstorm if step1 is the best step to add this

**Comment by hannahgdubin** [comment]
@dogi I think this could be an interesting project. I don't have much experience with design but I am taking a computer graphics class and I just learned Adobe Photoshop. I think that the Bell-Apps login page could  use a redesign especially since its for users.

**Comment by hannahgdubin** [comment]
Would you want the aspiring virtual interns to work on this as part of their steps or would you want this to be an intern project? I am a little confused

**Comment by dogi** [comment]
@hannahgdubin good question - I think in the end we will have both ...

right now I wanna just start tiny by making a task to identify interns with good taste and/or skills
also I wanna get ideas on what could be designed differently

maybe out of that later there will be a Project in Virtual Interns but right now wanna mostly think about the task specially the phrasing and where to add it

Does that make sense?

**Comment by ztickm** [comment]
I think we need to define **visions** and **purposes** of each site, also a (or many?) **graphic charter**. We also need an **experienced designer** to supervise the steps of creation. Else, interns might go astray and design stuff that isn't needed/related to OLE.

**Comment by mappuji** [comment]
Hi @dogi it is a good idea btw, but I have some questions.

Since OLE recruit an intern as "virtual software engineer intern" they might think that they will do some code throughout their internship. It would be great I think if we recruit more specific position for the intern e.g. UI/UX designer, web designer, etc. I believe, with keyword "UI/UX" and "web" we still get an intern with git knowledge.

CMIIW

**Comment by waryhermit** [comment]
@mappuji @dogi I don't think any of the interns need to feel obligated to do this issue, and I am not sure we have enough work for an intern to be dedicated to UX right now. If someone is able to do both than this issue is good for them, but we are having trouble getting a keeping interns as it is.

**Comment by mappuji** [comment]
> If someone is able to do both than this issue is good for them, but we are having trouble getting a keeping interns as it is.

I agree with this point @waryhermit . It is kinda a long-term project.

**Comment by sarah-lu102** [comment]
I am learning Adobe illustrator and teaching myself graphic design over the summer; I am willing to throw around some ideas and make mockups!

**Comment by dogi** [comment]
@sarah-lu102 awesome

**Comment by Loshma93** [comment]
@dogi I have knowledge on HTML and CSS. Let me know if my skills match to resolve this issue.
