### ISSUE TITLE
Note for existing github users : Setting your email address for a single repository

### ISSUE THREAD

**Issue by sarvanivadali** [open-learning-exchange/open-learning-exchange.github.io#508]
Add a note in [step 3](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md) to change username, email and other settings for existing github users. I already have a github account and forgot to change my email and accidentally used work email for first commits. All I had to do was to change my email in git config as suggested in <https://help.github.com/articles/setting-your-email-in-git/>

# Proposal:
### Login to Github with your username and password
Since you have already created a username on GitHub, we can assume that you understand the basic layout and functionality. If you don't, please, explore and do some basic googling. When you're editing on GitHub, it is important to always make sure you are working on your own GitHub repository. To that end, make sure there is your own username before the slash and the correct repository after the slash. For example, EmilyLarkin/BeLL-Apps). All of Open Learning Exchange's work can be [found here](https://github.com/open-learning-exchange). All the different repositories represent different types of software used by OLE, and the repositories act as categorizing system.

There is a lot to learn about GitHub, but to acclimatize you to it, we will provide a basic example of how to change something on GitHub. This example will specifically create your own &lt;username&gt;.github.io and allow you to edit and commit your changes.

#### Note: 
Existing Github users, please make sure to set your email address per local repository or make sure global settings are accurate. Follow [this](https://help.github.com/articles/setting-your-email-in-git/) for more information.

**Comment by dogi** [comment]
@sarvanivadali think this PR ready ;)
