### ISSUE TITLE
Github config common settings

### ISSUE THREAD

**Issue by sarvanivadali** [open-learning-exchange/open-learning-exchange.github.io#511]
I'm not sure if this exists in other projects. But it might be helpful if we create a sample github configs having things line suggested line endings ect based on operating systems such that new interns can use it as part of vetting process and need not have change it at a later point. A new file can be added with this information or can be added to [githubandmarkdown](http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md). Please comment if you think this deserves a pull request.

For starters we can have line endings and hope that it evolves as we grow

## Linux/OSX
```git config --global core.autocrlf input```

## Windows
```git config --global core.autocrlf true```

[stackoverflow](http://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings)

**Comment by sarvanivadali** [comment]
To be clear, I'm proposing a new md file with commonly used git configuration setting both recommended and optional. For example, in the past I have had trouble using Visual Studio Code on my Windows machine and realized I have to use ```wait``` flag for it to work : ```git config --global core.editor "code --wait"```. This new file, I'm hoping will capture all these various settings in one place so everyone can benefit from it.

**Comment by dogi** [comment]
OK - I like the direction

but lets first discuss the reasoning behind this and to find out what we want/need and why

@sarvanivadali ;)

**Comment by sarvanivadali** [comment]
Hi @dogi That make sense. The one thing that I noticed so far is line endings. Other config settings like ```user.email``` can also be included.

**Comment by waryhermit** [comment]
So we are unhappy with the default git settings? That is all I have been using.

**Comment by dogi** [comment]
yes we are :P

**Comment by waryhermit** [comment]
@sarvanivadali I think @dogi wants you to explain why we would be unhappy with the default settings. I don't have a good grasp anyway.

**Comment by sarvanivadali** [comment]
Hi @waryhermit @dogi I'm not saying that default configurations are bad. I think we can standardize some configurations that everyone uses. This [discussion](http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git) is one candidate that can be added to the new proposed page. I don't have any other config settings other than the one above stated. 

(OR) 

We could simply add this [link](http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git) to [step # 3](http://open-learning-exchange.github.io/#!./pages/githubandmarkdown.md) in **Useful links** section and let readers decide what is best for their platform?

**Comment by waryhermit** [comment]
So the only setting we are actively having problems with is the line endings then? I was under the impression that they were automatically standardized when you made a pull request for some reason.

**Comment by waryhermit** [comment]
We also have trouble with git commit username not matching github account name

**Comment by kanishk1010** [comment]
@waryhermit My user.name on git config is different from GitHub username, but since my email is the same, I have not faced any issue (maybe I'm naive). However, if it is a good practice, or desirable for this project, we can standardize it along with some other parameters, as suggested by @sarvanivadali
