### ISSUE TITLE
Make all self-referencing links relative

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#515]
So that links to resources on open-learning-exchange such as `http://open-learning-exchange.github.io/#!pages/firststeps.md` would become `/#!pages/firststeps.md`

For more information on the difference between absolute and relative links see: http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/ or google relative links vs absolute links.

If you are clever you could probably find and fix all the files with grep..

**Comment by i5o** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/529
