### ISSUE TITLE
A brief page about resolving merge conflicts

### ISSUE THREAD

**Issue by sarvanivadali** [open-learning-exchange/open-learning-exchange.github.io#516]
I think it would be nice if we add a page that explains how to resolve merge conflicts using 3rd party 3-way merge tools.

**Comment by waryhermit** [comment]
I feel like three way merge conflicts shouldn't be happening in the first 10 steps, and that if they are its a good chance people are not following good git practices. We can't make the MDwiki account for every contingency out there. I have ran into conflicts only a few times the during the months I have been working here and I was always able to resolve them without the use of 3rd party tools. Just my 2 cents.

Could you explain why you think 3rd party merge tools are likely to be needed and not just a super rare case?

**Comment by sarvanivadali** [comment]
Hi @waryhermit I totally agree with you. We as interns doing initial steps should not be facing any merge issues and also agree that we should not be having a page for every issues with git etc. 

I have in the past faced merge issues quite frequently and having a 3rd party tool really helped where auto merge failed. I believe it is a personal choice :-) 

Do you suggest we close this issue?

**Comment by waryhermit** [comment]
@sarvanivadali I'll have some others take a look first, its not a good idea for one person to dismiss ideas most of the time, there may be perspectives and experience I don't have.

@dogi @leonardmensah What do you guys think?

**Comment by dogi** [comment]
@waryhermit I think I lean on your side here

Except if we wanted to tell VI that we want them to learn is everything to not have merge conflicts :)

**Comment by waryhermit** [comment]
@dogi So we are going with closing this issue then?
