### ISSUE TITLE
Clarify when to use merge or rebase in gitandrepositories.md

### ISSUE THREAD

**Issue by sarvanivadali** [open-learning-exchange/open-learning-exchange.github.io#517]
The example in ```gitandrepositories.md``` uses ```git merge upstream/master``` in **Sync your fork** section where as the help links points to ```rebase``` command. Shall we change above example to use ```rebase``` or provide readers with a description about the differences between using ```rebase``` vs ```merge``` ?

**Comment by waryhermit** [comment]
I think it would be good to clarify and expand the line "If you find yourself needing to rebase your forked repository, the following two links should help" yes. Right now its not clear why or when you would *need* to rebase.

**Comment by sarah-lu102** [comment]
@waryhermit  does this explanation work? see #739

**Comment by waryhermit** [comment]
@mappuji @dogi @paulbert Did https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/753 fix this issue?

**Comment by dogi** [comment]
thanks @waryhermit
