### ISSUE TITLE
JavaScript code to fetch Git statistics

### ISSUE THREAD

**Issue by sarvanivadali** [open-learning-exchange/open-learning-exchange.github.io#521]
The following is @dogi 's idea: 

## Context:
During the vetting process, a prospective intern is expected to create 3 issues and a total of 5 pull requests (including creating their own page). Often times, @dogi and active interns need to filter issues/merged pull requests in Github for every user to determine their eligibility.

## Proposal:
@dogi proposed that we should create a JavaScript code that would query Github API and get specific statistics for a given user. This source should be embedded by every new intern going forward such that they and everyone else can track progress.

## Solution:
I believe it is possible to embed JavaScript sources in markdown. This [stackoverflow](http://stackoverflow.com/questions/2754391/embed-javascript-in-markdown) explains how this can be done.

**Comment by Ebuka-Chibueze** [comment]
I think this link to [stackoverflow](http://stackoverflow.com/questions/10341135/example-of-using-github-api-from-javascript) will come in handy as well.

**Comment by Ebuka-Chibueze** [comment]
According to GitHub Developer, the API treats unmerged PR's and issues as the same thing. This script lists issues (such as this one) as an unmerged PR.

**Comment by dogi** [comment]
@Ebuka-Chibueze good to know - anyhow for now we mostly need the number accepted commits ;)

**Comment by waryhermit** [comment]
@Ebuka-Chibueze Says he is nearing completion of the script. Hopefully there will not be a problem including some javascript on the github pages / markdown wiki

**Comment by waryhermit** [comment]
@Ebuka-Chibueze Have you made any progress adding your script to a markdown page?

**Comment by Ebuka-Chibueze** [comment]
@waryhermit For some reason my I can only get it to work if I adjust the link like [this](https://ebuka-chibueze.github.io/pages/track-progress). I'm also having issues with the font.

**Comment by dogi** [comment]
@mappuji if @Ebuka-Chibueze adds the link and/or publishes where he is so far ... can you try your magic?

**Comment by mappuji** [comment]
Closed because issue was solved.
