### ISSUE TITLE
Team member missing from Team page - Karen T

### ISSUE THREAD

**Issue by 314159265359** [open-learning-exchange/open-learning-exchange.github.io#53]
On Team page, member Karen T is missing from list of members.  Tested to see if the member site is active, and it is, but there is no link to the page.  Right now to view page, other team members would have to type the url into their browser address bar.

**Comment by 314159265359** [comment]
Link to member site can be added by editing team.md page to add link to Karen T's page (open-learning-exchange.github.io/ll_CC/pages/314159265359.md) (would fork, edit, commit, and do pull request for merge).

**Comment by dogi** [comment]
:)
go for it

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/commit/0d5ebe52e6f25f7e236192bec7ebb58808163c85 done
