### ISSUE TITLE
Nation BeLL

### ISSUE THREAD

**Issue by mouthz** [open-learning-exchange/open-learning-exchange.github.io#534]
So I was able to sync with Nation BeLL for step #7. But I wasn't able to log in as an administrator for the nation. I used the username: admin and the password: password. But, I keep on getting the message that either one is incorrect.

**Comment by dogi** [comment]
@mouthz I am sorry to hear you are having problems
could you please make a screenshot and add it to this issue?

by the way most of the time when people have the same issue a firewall is disabling them from successfully syncing

**Comment by waryhermit** [comment]
[I think this was resolved on gitter.](https://gitter.im/open-learning-exchange/chat?at=58cc0885ac314c8a1a5d4409)
