### ISSUE TITLE
Improve readability of First Steps page

### ISSUE THREAD

**Issue by blakedelee** [open-learning-exchange/open-learning-exchange.github.io#536]
I find some of the formatting options a little clunky for the listings on First Steps.  Having double colons in the step titles, and the # symbol for each step seems redundant.  

See PR #537

**Comment by blakedelee** [comment]
Please see PR #537

**Comment by mappuji** [comment]
Good inspection @blakedelee , but the hashtag symbol is there for numbering I believe.

> #0

you read that as

> Number 0

--Correct me if I'm wrong

**Comment by Loshma93** [comment]
@blakedelee #536 In First steps I think "#" has been used for Numbering the steps to gain the attention.
![image](https://cloud.githubusercontent.com/assets/24893117/24168353/2d1c3eea-0e37-11e7-988d-46e5cfe676e8.png)

**Comment by kylemathias** [comment]
#1 looks a little sloppy, Might be "cleaner looking" if it was just a number

# Step 1: BeLL Installation:

vs

# Step # 1: BeLL Installation:

**Comment by dogi** [comment]
thanks @Loshma93 and @kylemathias
