### ISSUE TITLE
Videos for First Steps

### ISSUE THREAD

**Issue by Loshma93** [open-learning-exchange/open-learning-exchange.github.io#541]
# Hi Everyone,

I am new to GitHub. I think providing videos for the first steps will be very helpful for the Virtual Interns who are very new to GitHub. They can go through each and every step easily. Correct me if I am wrong.

**Comment by i5o** [comment]
It's -1 from me. If you can't follow a simple text guide, then you
can't follow code documentation (which is more complicated) or so.
We coould have them as a last resource, but I'm pretty sure that there
are (already) videos out there on how to create a pull request, or
push a commit.

**Comment by waryhermit** [comment]
We actually discussed this last Friday in the meeting. While some people may find it easier to follow a video, there a number of problems that make this unfeasible.

1. Part of the process of doing the steps is improving the steps and process. If we had videos interns would need video editing software, and video editing skills.
2. Even if there was good free video editing software, git, and github do not support collaborative video editing. Merging, reviews, etc would not be possible.
3. Way more work than text, slower to update. We need things that take little time and effort as possible, its not like OLE gets a ton of work out of interns.
4. Large file size would increase the difficulty and cost of hosting.
5. As @i5o stated, we need people who can follow written directions and communicate in written form well. As this is a remote internship, face to face time is limited so good reading and writing skills are needed.

I certainly understand why it seems like a good idea, but we don't have the resources to do something like this, sorry.

**Comment by Loshma93** [comment]
@i5o @waryhermit Okay. Thank you for your response. I agree with the points which you raised.

**Comment by dogi** [comment]
+1
