### ISSUE TITLE
Conflicting personal repo with OLE repo fork

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/open-learning-exchange.github.io#543]
### Issue
Under "Go to Settings and rename your repository" if a user already has an existing repository that is being pointed at a for a website, they will get this error "404 there isn't a GitHub pages site here". A user needs to double check that they don't have a repository that is being used as a website. Or figure out how to redirect there GitHub website to there forked [open-learning-exchange.github.io](https://github.com/open-learning-exchange/open-learning-exchange.github.io).

### Context
When I created my GitHub account, I did the [Hello World](https://guides.github.com/activities/hello-world/) GitHub guide to get a basic understanding of how repositories worked on GitHub. Through that setup you create a repository from scratch along with doing some basic branches and edits. For what ever reason, my <https://kylemathias.github.io/#!index.md> was pointing at my repository I created for [Hello World](https://guides.github.com/activities/hello-world/) guide. In that Hello Word repository there is not a index.md file, so it was just returning "404 there isn't a GitHub pages site here". The fix for me was to delete the repository I created in the Hello World guide. 

### Fix
My fix was to delete every repository except for my forked [open-learning-exchange.github.io](https://github.com/open-learning-exchange/open-learning-exchange.github.io). I dont know how to make sure that a user/interns GitHub website is pointing at there forked [open-learning-exchange.github.io](https://github.com/open-learning-exchange/open-learning-exchange.github.io). Any Ideas or suggestions?

**Comment by waryhermit** [comment]
@kylemathias You shouldn't have had to delete any repository.

In the FAQ we have the following:
>Q: What do I do if I already have a github.io with my username?
>You have a couple of options.
> 1. If you are not using the repo anymore you can delete it and then follow the First Steps.
> 2. If you are still using it and you don't want to remember another login, you can create an organization and name the forked repro <orgname>.github.io
> 3. Or you can just create another github account, and use that for OLE work

I think that probably would have addressed your issue, but maybe I didn't understand what you wrote.

**Comment by kylemathias** [comment]
@waryhermit i think that would of solved it. I just didnt know that i needed to delete it. Is there that step some place under "Go to Settings and rename your repository"? if not, might be a good idea to link to it, or suggest it some place. I might of just missed it.

**Comment by kylemathias** [comment]
[GitHub and Markdown](http://open-learning-exchange.github.io/#!./pages/githubandmarkdown.md). I do not see it there.

**Comment by kylemathias** [comment]
@waryhermit seems to have the correct solution for my situation.
