### ISSUE TITLE
Gimmicks

### ISSUE THREAD

**Issue by Loshma93** [open-learning-exchange/open-learning-exchange.github.io#544]
I am trying to edit Loshma93.md page by adding Gimmicks. I tried to add an alert in .md page.
![image](https://cloud.githubusercontent.com/assets/24893117/24167427/f3cae84c-0e33-11e7-9978-93ee540313b7.png)
 It doesn't make any change
![image](https://cloud.githubusercontent.com/assets/24893117/24167450/071d8e9a-0e34-11e7-9d20-0a1bd2367b46.png)
It has to output as follows:
![image](https://cloud.githubusercontent.com/assets/24893117/24167474/1b5bde7a-0e34-11e7-988b-ca8389b86e8f.png)

**Comment by dogi** [comment]
@Loshma93 are you saying something is wrong with our `mdwiki`

cause I really love to see more of this gimmicks ...

**Comment by kylemathias** [comment]
@Loshma93 I tried creating a gimmick in an MD editor and they where not showing up. Might be something more to it then just simply "note! stuff in note".

**Comment by Loshma93** [comment]
@dogi I didn't mean that something wrong with mdwiki. I just want to know the reason why Gimmicks are not working with my .md Is there any issue with the syntax??

**Comment by dogi** [comment]
@Loshma93 I think our mdwiki code is a year old ... and maybe that is the problem
also it would be awesome if you could add the link for this gimmicks here

**Comment by waryhermit** [comment]
Some gimmicks don't show up right for me in the github preview, have you tried previewing it with rawgit or publishing a change to your local repo and viewing your website directly?

**Comment by Loshma93** [comment]
@dogi This is the link for gimmicks which I am following: 
http://dynalon.github.io/mdwiki/#!gimmicks.md

**Comment by waryhermit** [comment]
Gimmicks are a feature of the Markdown **Wiki** software, and are not part of markdown itself. Thus they do not work correctly until the wiki has been built. Only the master branch is built, so you cannot use the built in github preview. You can either preview via rawgit (which can be slow to update), or install the MD wiki on your computer so you can preview the changes. Also note that mixed https content may make your page fail to render.
