### ISSUE TITLE
Markdown Syntax highlighting

### ISSUE THREAD

**Issue by Loshma93** [open-learning-exchange/open-learning-exchange.github.io#545]
I am working on Markdown syntax highlighting.
![image](https://cloud.githubusercontent.com/assets/24893117/24168702/5d206cf0-0e38-11e7-92bc-812b02bc3428.png)

The preview is as follows:
![image](https://cloud.githubusercontent.com/assets/24893117/24168722/6e011fa6-0e38-11e7-927a-61b95cfaad16.png)

Is this the correct way the preview looks. Correct me if there are any errors in that.

**Comment by dogi** [comment]
@Loshma93 I think this correct

**Comment by Loshma93** [comment]
@dogi Ok. Thank you
