### ISSUE TITLE
gimmicks: https 

### ISSUE THREAD

**Issue by Supriyaranjan** [open-learning-exchange/open-learning-exchange.github.io#546]
If I add a google Maps location the page doesn't even render properly. (white page)
This problem occurs in Firefox, chrome and IE (the browsers I tested)
When I call the same page using http then It is fine.

Is there any solution for this or any way to redirect https link to http?
https://rawgit.com/Supriyaranjan/Supriyaranjan.github.io/master/#!pages/Supriyaranjan.md

![image](https://cloud.githubusercontent.com/assets/26332034/24180244/d709606e-0e81-11e7-96de-24718ef5ca74.png)

**Comment by i5o** [comment]
Use  // instead of https:// or http:// when specifying an url
I think that should work

**Comment by Supriyaranjan** [comment]
Yes thats working

**Comment by dogi** [comment]
@Supriyaranjan bingo ;)

**Comment by waryhermit** [comment]
Is this issue solved?
