### ISSUE TITLE
Several intern pages have markdown errors

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#548]
Several people have `=` which I assume were supposed to be horizontal lines. Not sure how they slipped past review 😕 

Active interns with errors:

http://open-learning-exchange.github.io/#!./pages/FanisGk.md
http://open-learning-exchange.github.io/#!./pages/mappuji.md
http://open-learning-exchange.github.io/#!./pages/Ebuka-Chibueze.md

**Comment by Ebuka-Chibueze** [comment]
I can't speak for the other guys but my intention was to make a horizontal line. I think someone can simply replace the errors with  `-` or simply delete them.

**Comment by waryhermit** [comment]
Fixed by #573
