### ISSUE TITLE
Formating team.md dates

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/open-learning-exchange.github.io#550]
Current dates look like this:
## Active Interns
|**Username**|**Join Date**|
|------------|-------------|
|[waryhermit](waryhermit.md) (**Intern Lead**)| 20161213 |
|[FanisGk](FanisGk.md)| 20160801 |
|[prmurphy](prmurphy.md)| 20161023 |
|[hikaruit15](hikaruit15.md)| 20161117 |
|[hannahgdubin](hannahgdubin.md)| 20170101 |
|[mappuji](mappuji.md)| 20170122 |
|[fangninghe](fangninghe.md)| 20170123 |
|[Ebuka-Chibueze](Ebuka-Chibueze.md)| 20170219 |
|[sarvanivadali](sarvanivadali.md)| 20170223 |
|[Chris-Boe](Chris-Boe.md)| 20170226 |
|[paulbert](paulbert.md)| 20170308 |
|[i5o](i5o.md) (**Intern Lead**)| 20170308 |

I am suggesting a simple update to the date format to this:

## Active Interns
|**Username**|**Join Date**|
|------------|-------------|
|[waryhermit](waryhermit.md) (**Intern Lead**)| 2016-12-13 |
|[FanisGk](FanisGk.md)| 2016-08-01 |
|[prmurphy](prmurphy.md)| 2016-10-23 |
|[hikaruit15](hikaruit15.md)| 2016-11-17 |
|[hannahgdubin](hannahgdubin.md)| 2017-01-01 |
|[mappuji](mappuji.md)| 2017-01-22 |
|[fangninghe](fangninghe.md)| 2017-01-23 |
|[Ebuka-Chibueze](Ebuka-Chibueze.md)| 2017-02-19 |
|[sarvanivadali](sarvanivadali.md)| 2017-02-23 |
|[Chris-Boe](Chris-Boe.md)| 2017-02-26 |
|[paulbert](paulbert.md)| 2017-03-08 |
|[i5o](i5o.md) (**Intern Lead**)| 2017-03-08 |

Adding dashes between the year-month-day makes it much more readable. Let me know if i should make these changes and ill update my repository, make the changes then pull request the changes. Ill add the changes to the active interns and the inactive interns.

**Comment by dogi** [comment]
@kylemathias thanks for this suggestion but I am irrational committed to the one we have ;)

**Comment by hannahgdubin** [comment]
@kylemathias I suggested the same thing haha @dogi just likes the military style!

**Comment by kylemathias** [comment]
ha. ok. i will close this out then.
