### ISSUE TITLE
Add InternOrientation.md to Teams menu

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#552]
Add Intern Orientation (`./pages/InternOrientation.md`) to the drop down menu shown below. There should be a horizontal line between Intern Orientation and the other menu items, just like the First Steps menu.

![image](https://cloud.githubusercontent.com/assets/5189447/24302051/a8c034a0-1087-11e7-8691-e54f91beaf94.png)

**Comment by kylemathias** [comment]
I was trying to preview this before i sent it in, but it seems to be working. My change should solve this issue.

**Comment by waryhermit** [comment]
Closed via #558
