### ISSUE TITLE
Open Link in New Tab

### ISSUE THREAD

**Issue by Loshma93** [open-learning-exchange/open-learning-exchange.github.io#563]
In First Steps page when we open a link, it was opening in the same tab. I think it would be better if the link opens in a new tab instead of opening in the same tab.

**Comment by waryhermit** [comment]
I think it would be better to leave it as it is, people can always open in new tab quite easily themselves with the open new tab feature that pretty much all browsers have, but some people might find it opening in a new tab annoying. Did you know you can open a link in a new tab by holding `control` and clicking a link?

**Comment by i5o** [comment]
I like to hold control or command to open new tabs as well :)

I don't think this is necessary

**Comment by waryhermit** [comment]
Since two of us think the same I will close.
