### ISSUE TITLE
UI Cosmetic issue in githubandmarkdown.md

### ISSUE THREAD

**Issue by Supriyaranjan** [open-learning-exchange/open-learning-exchange.github.io#565]
In Markdown page, I noticed the navigation links on the left side, the first three links when selected and clicked, they turn bold but it does not happen when we click and select last link "Useful links".

![image](https://cloud.githubusercontent.com/assets/26332034/24319734/3b2cba38-10f2-11e7-8777-4a47f7c7b3dd.png)

![image](https://cloud.githubusercontent.com/assets/26332034/24319740/7293c5e8-10f2-11e7-9e52-3bd0144e3ae3.png)

**Comment by dogi** [comment]
@Supriyaranjan I really like your suggestion so far - can you be more concrete?

**Comment by Supriyaranjan** [comment]
@dogi - While looking through the Markdown page (http://open-learning-exchange.github.io/#!pages/githubandmarkdown.md), I noticed a cosmetic issue when clicking the header links on the left hand side. I noticed when the link "Useful links" is clicked it does not turn bold like other links above it ("Start here","Prerequisites" etc.)
Can this be a cosmetic bug in the page?

**Comment by dogi** [comment]
@Supriyaranjan now I understand - sorry was completely off ;)

**Comment by sarvanivadali** [comment]
Hi @dogi can @Supriyaranjan work on this issue?

**Comment by waryhermit** [comment]
@Supriyaranjan @sarvanivadali Its a real minor issue but sure -  I am curious to see how it could be fixed.

**Comment by sarvanivadali** [comment]
@Supriyaranjan @waryhermit Is it because there isn't enough room to scroll down and the CSS settings are perhaps not taking effect? I'm not really a CSS expert and curious to know if this can be fixed.

**Comment by Supriyaranjan** [comment]
@sarvanivadali @waryhermit  I looked into file githubandmarkdown.md and noticed that top and left navigation bars remain frozen when we scroll down, also I couldn't find the code for navigation in githubandmarkdown.md file. So is there a separate file for navigation? If yes then which one can you tell me? It is easier to figure out in html and css but looks different in markdown

**Comment by Supriyaranjan** [comment]
code for top navigation is in the file navigation.md but I am not able to find it for left navigation

**Comment by sarvanivadali** [comment]
@Supriyaranjan I'm not really sure if this can be fixed. As you can see, if I minimize my chrome window I see the desired effect.
![image](https://cloud.githubusercontent.com/assets/8753852/24467004/cd6dc810-1480-11e7-8804-833ff2846b07.png)
I'm new to CSS as well :-)

**Comment by waryhermit** [comment]
@Supriyaranjan 
This seems to be a side effect of how the MDWiki CSS chooses which to be bold. From a little testing it seems that it chooses bases on how close it is to the top of the window or something.

As @sarvanivadali hinted at, this is from the MDwiki software, so if you can think of a better way of deciding which gets the **bold** effect I would make an issue there: https://github.com/Dynalon/mdwiki/issues

**Comment by Supriyaranjan** [comment]
May be... I tried again in chrome,mozilla and IE and saw the same issue. :(
![image](https://cloud.githubusercontent.com/assets/26332034/24467184/1cb35fc8-1479-11e7-918b-99f8693a2f99.png)

**Comment by Supriyaranjan** [comment]
If its not happening with everyone then may be it is not an issue.

**Comment by waryhermit** [comment]
@Supriyaranjan You have to make the window small enough that the Useful Links paragraph header is near the top of the screen to get it bold

**Comment by waryhermit** [comment]
![image](https://cloud.githubusercontent.com/assets/5189447/24467250/cb37ee76-1481-11e7-820b-5fe44de4a335.png)

**Comment by Supriyaranjan** [comment]
@waryhermit  I tried that but not working somehow. However "useful links" link in other pages are turning bold. 
![image](https://cloud.githubusercontent.com/assets/26332034/24467342/b90014f2-1479-11e7-8557-e8a4dbf13537.png)
![image](https://cloud.githubusercontent.com/assets/26332034/24467372/ccec6c7c-1479-11e7-9a77-daf751cacfa9.png)

**Comment by Supriyaranjan** [comment]
Anyway I think it is not an issue

**Comment by paulbert** [comment]
@sarvanivadali @Supriyaranjan The short version is that I don't think it's possible to have both the effect of items highlighting as they scroll as well as a bold when clicked cleanly because once the slightest page scroll happens it would revert to what you're seeing.

A bit more to dig into if you're interested in learning about how this works: this is done with javascript in the mdwiki script in index.html.  You can look at the more readable code [here](https://github.com/paulbert/mdwiki/blob/0.6.x/js/bootstrap.js) if you do a search for `md-inpage-anchor`.  When scrolling happens a function is called that first gets the name of the first viewable header and if that matches one of the navigation links that one it is given an `active` CSS class.

**Comment by Supriyaranjan** [comment]
@paulbert thanks for helping us learn something new. It is very useful
