### ISSUE TITLE
Add check commit username vs github username to review steps in internorientation.md

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#566]
In the reviewing check list we should make sure that people use their github usernames and emails when making commits through git. see image for example of problem.
![img](https://files.gitter.im/open-learning-exchange/interns/WdGh/thumb/92-4.png "Usernames don't match")

Updated by @mappuji
> see [here](http://open-learning-exchange.github.io/#!pages/internorientation.md) for the page

**Comment by Yurockkk** [comment]
@waryhermit I encountered this problem, it turns out that I didn't set my username and email to match my GitHub account when creating the commit! Is this issue need to be fixed? If I understand correctly, just add a list item in the reviewing check list right?

**Comment by mappuji** [comment]
@Yurockkk, basically @waryhermit is currently inactive, but you can help us by this sentence
>[x] Make sure that people use their GitHub usernames and emails when making commits through git.

to here http://open-learning-exchange.github.io/#!pages/internorientation.md

**Comment by Yurockkk** [comment]
@mappuji sure, I'll work on it :smile:

**Comment by Yurockkk** [comment]
@mappuji  Done! see [here](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/775)

**Comment by mappuji** [comment]
solved by #775
