### ISSUE TITLE
MDWiki breaks markdown on internorientation.md

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#567]
If you [preview internorientation.md on github](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/internorientation.md) it looks correct, but on the [actual wiki](http://open-learning-exchange.github.io/#!pages/internorientation.md) the lists are messed up. I think additional new lines might fix this.

**Comment by kylemathias** [comment]
i look into fixing this right now
