### ISSUE TITLE
Move all pages which are not user pages to another folder

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#568]
Its hard for me to find files among all the user pages, it would be nice if they were stored separately.

**Comment by blazerchamp** [comment]
A good solution for this is to find out where you are in the directory with the pwd command. You can use the find command to find the files you're looking for, and change to the directories it listed. Then use the mv command to move the files to another folder (don't forget to specify the source and destination path for this command). You can use the 'ls -l' command to list out the files in a directory as well as their file permissions. This will allow you to confirm which pages are user pages and which ones are not.

**Comment by waryhermit** [comment]
I have the mos trouble finding the files when browsing through Github, I just use `control + f` to find it. You can go ahead and make a pull request with the files moved to another folder though.

**Comment by kylemathias** [comment]
I will look into it.

**Comment by kylemathias** [comment]
in order for me to make another folder, i will then have to go into each page file and update the url link from pages/ to pages/newfoldername. Unless there is an easier way to do this that i am not aware about.

**Comment by waryhermit** [comment]
@dogi Is there any reason you wanted the steps files moved and not the user pages? I think it would avoid most of the trouble @kylemathias 

You would still have to update the members page, but it wouldn't be as bad.

**Comment by kylemathias** [comment]
@waryhermit I was thinking about moving the interns page. I would have to update the team.md along with editing the "First Steps" to have new interns make there profile page in the correct folder.

**Comment by waryhermit** [comment]
@kylemathias Yes, that is what I was just saying - but I strongly remember @dogi asking for it to be done the way I originally said in the issue. So wait for his input.

**Comment by dogi** [comment]
OK I see - both solutions are not optimal
I slowly think @waryhermit you was right from start on
I mean that we should move away the personal pages

@dogi kinda feels that the question `move where to?` is more important to answer ...

**Comment by waryhermit** [comment]
Fixed by #670
