### ISSUE TITLE
add notes in firststeps.md to downgrade oracle VM to v5.1.14  for Windows7.

### ISSUE THREAD

**Issue by Supriyaranjan** [open-learning-exchange/open-learning-exchange.github.io#575]
In Step#1(firststeps.md), while installing bellapps and trying to run it using vagrant and oracle VM on Windows 7, the oracle VM version 5.1.16 which is downloaded automatically using chocolatey is not able to up the "vi" virtual server using vagrant. This was caused because of an error in the path of Shared Folders.  

**Proposed Solution** - To add a note at the end of Step#1 (firststeps.md) to downgrade Oracle VM to v5.1.14 on Windows 7 to make it work.

**Comment by waryhermit** [comment]
Could you post the exact error? If its the one I think it is, then its more of a warning than a error and doesn't prevent vi from running.

**Comment by Supriyaranjan** [comment]
@waryhermit - I am sorry I think I was unable to install BellApps rather than running "vi". This is the error which I was getting -
Vagrant was unable to mount VirtualBox shared folders. This is usually because the filesystem "vboxsf" is not available. This filesystem is made available via the VirtualBox Guest Additions and kernel module. Please verify that these guest additions are properly installed in the guest. This is not a bug in Vagrant and is usually caused by a faulty Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

: No such file or directory

Please note it was an error preventing the BellApps to be installed on the vi. Since then I have downgraded my Oracle VMWare to 5.1.14 and then it is working fine..

**Comment by waryhermit** [comment]
@Supriyaranjan Hmm, there was someone else in the channel that was using windows 7 and did not have a problem.. Did you already have virtualbox installed before installing the bellapps I wonder? In any case if its true that it needs to be down graded we need to change the script not make a note in first steps..

**Comment by sarvanivadali** [comment]
Hi @Supriyaranjan Can you try installing ```vagrant plugin install vagrant-vbguest``` plugin and try again. If that works for you then we can update instructions to install above plugin instead of downgrading.

**Comment by Supriyaranjan** [comment]
This is a known issue with VMware 5.1.16 on Windows. Please check the link - http://stackoverflow.com/questions/42796016/vagrant-unable-to-mount-shared-folders
@sarvanivadali - This link states that installing vagrant plugin doesn't work. The only known solution is to downgrade VMware to 5.1.14.
@waryhermit - I was not having VMware installed earlier.

**Comment by sarvanivadali** [comment]
@Supriyaranjan Since installing plugin on your Windows 7 machine did not work for you either, please add this to your description as well.

**Comment by waryhermit** [comment]
@Supriyaranjan Can you find anything explain who is effected by this issue? The link you posted didn't mention Windows 7 specifically.

**Comment by Supriyaranjan** [comment]
@waryhermit if someone else with windows 7 did not have any issue then it might not be the case for all windows 7.

@sarvanivadali  I did not try plugin. I already downgraded and installed 10 days back. However in the link that person has mentioned that plugin didnt work for him.

**Comment by sarvanivadali** [comment]
@Supriyaranjan Since installing plugin worked for me on Windows 10, we should suggest new interns to downgrade if on Windows 7 only.  For Windows 10 - we can suggest to install the plugin. I had hoped that installing plugin worked on Windows 7 too (that way we could add this plugin as part of installation script). My only concern is that - we are unsure of the side effects of downgrading and perhaps ask someone on win7 to check that for us.

**Comment by Supriyaranjan** [comment]
@sarvanivadali  yes that would be better

**Comment by Supriyaranjan** [comment]
So should i close this issue now?

**Comment by waryhermit** [comment]
@Supriyaranjan No, I want to see if anyone else has this problem. You can work on other things though. If you have three issues, three merged pull requests, and three comments you can message Dogi though

**Comment by waryhermit** [comment]
@Supriyaranjan @dogi I haven't noticed anyone else having this problem in the chat, so I think I will close this issue now.
