### ISSUE TITLE
More description on "git fetch upstream" command

### ISSUE THREAD

**Issue by xinglunxu** [open-learning-exchange/open-learning-exchange.github.io#58]
In the Markdown wiki, under the Git Repositories tab, at one point the reader is asked to run the command "git fetch upstream". However, under default condition, the upstream points to nothing so this command will not work. I think we should add instructions telling the users to point the upstream to a repository first.

**Comment by dogi** [comment]
you mean improve that page in the MDwiki?

**Comment by xinglunxu** [comment]
Yes

**Comment by dogi** [comment]
go for it

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/61 done
