### ISSUE TITLE
Add note on adding images to Gitter (bellapps.md)

### ISSUE THREAD

**Issue by zeivhann** [open-learning-exchange/open-learning-exchange.github.io#580]
It's just a small thing that can be solved after a quick google, but perhaps on [bellapps.md](http://open-learning-exchange.github.io/#!./pages/bellapps.md) we could add a note that you can drag and drop an image into the Gitter chat to upload it? (For example, when interns need to upload their configuration settings image)

**Comment by dogi** [comment]
a picture says more then thousand words ;)

@dogi likes this one, but he does not remember if we did not already wrote about it

**Comment by zeivhann** [comment]
I just double checked the page, and it does not appear to be mentioned there. I will go ahead and add that to my branch and submit a pull request if that's quite alright. :)

**Comment by dogi** [comment]
sure @zeivhann - but there are more pages ;)

**Comment by zeivhann** [comment]
Right, right, it probably is mentioned elsewhere but I thought maybe putting it right after mentioning posting the screenshot might help! I just didn't see it on the same page where the screenshot was requested.

**Comment by blazerchamp** [comment]
Google works, as well as a simple check on the main markdown syntax on their website.

**Comment by waryhermit** [comment]
Closed via #581
