### ISSUE TITLE
Suggestion: Add How-to branch correctly

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/open-learning-exchange.github.io#591]
I know I was having to search outside of the First Steps to figure out how to branch, edit the branch and then create a pull request. Would it be a good idea to add a How-to work on a branch locally? What do you guys think?

**Comment by waryhermit** [comment]
You don't find the branching directions in http://open-learning-exchange.github.io/#!pages/githubissues.md adequate?

**Comment by kylemathias** [comment]
Is that linked someplace on the first steps? i might have missed it.

**Comment by kylemathias** [comment]
NVM, i dont know why i didnt see it.
