### ISSUE TITLE
Should we add more information about branching to githubissues.md?

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/open-learning-exchange.github.io#592]
The page talks about how to make a branch, but doesn't talk about how to work on that branch. @waryhermit explained it very well to me.

> @kylemathias git will track any changes you make to your local files, so when you switch to a branch and modify the local files the changes are limited to that branch
@kylemathias and if you switch back to the master branch it will look like in windows explorer that your changes are gone, but if you go back to you patch branch they will come back

Even though this seemed to be the only logical thing that was happening, I couldn't find a definitive information that this was happening. I never really worked on a GitHub project, so adding something simple like "Now you can make changes to your local repository. The changes you make to your local repository will only affect the branch you are on" would save time for new GitHub people like me. Could add it after this section:
![image](https://cloud.githubusercontent.com/assets/26488295/24422554/c718c776-13ae-11e7-8205-884aa91f03bc.png)

BUT...@waryhermit brought up a good point. Do we want to add another step? Do we want interns to figure this out on their own as part of testing there googling powers?

We would like some feedback about the idea. So, thoughts?

**Comment by waryhermit** [comment]
@kylemathias I certainly can see why you wondered what would happen, I look forward to hearing peoples thoughts regarding the cost / benefit of adding more and more information.

**Comment by i5o** [comment]
I suggest adding something like this:

> Then use git checkout -b ... repository.
> *image of this command*
> <img width="603" alt="screen shot 2017-03-28 at 5 30 27 pm" src="https://cloud.githubusercontent.com/assets/2650479/24425984/730aef14-13dc-11e7-8085-2f65e2d924c9.png">
> From now on, changes will be made on this branch and not in master (where we sync with the original repo)

or idk?

**Comment by zeivhann** [comment]
I do feel like it is more beneficial to leave interns to do some googling. I find that in many cases (especially in the classes I've had where I am surrounded by people learning something for the first time) many of them get used to expecting everything to be in one place. Researching on your own is an important part of computer science, or just programming in general.

**Comment by sarah-lu102** [comment]
I personally thought it was intuitive that the purpose of branching was so that you would create a new version that you can edit while preserving the old version before you save changes. However, it does get confusing because (correct me if I am wrong), there are multiple levels where at each level, you clone or fork something from the master or upstream, so it's hard to tell if branching already happened when it seems like so many copies have already been made

**Comment by waryhermit** [comment]
@kylemathias @dogi @sarah-lu102 So do you think this page needs more explanation? Or should we close this issue?

**Comment by sarah-lu102** [comment]
more explanation would be nice. Especially for people brand new to this, having the same information from different sources will make it sink in better, and cross-referencing with the wiki as well as googling will make it less confusing
