### ISSUE TITLE
Make pull/issue/comment requirement more clear.

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#599]
Pull requests / issues / comments for one part of the steps do not count towards the other steps which isn't very clear right now.

For example you need

- 1 pull request from step three (your profile)
- 1 issue, comment and pull request at step 6.
- 3 issues, comments, and pull request at step 8

Thus before you are able to go on to step nine you will have **at least**

- 5 pull requests.
- 4 comments
- 4 issues

Its also not clear that only accepted PR's count towards this requirement.

**Comment by dogi** [comment]
@waryhermit agree -what about if we add this in front of step 9?

I also always check all the community nation actions of step 7
- sync
- publication
- update
- (dummy user)

**Comment by Ebuka-Chibueze** [comment]
@waryhermit  I found a way to count issues separately from PRs. Commits/Comments are more complicated than Issues/PRs It will take some research on my part.

**Comment by waryhermit** [comment]
@Ebuka-Chibueze OK. I think we only care about comments, not commits. Some people make 20+ commits per pull request. Thanks for keeping me updated.
