### ISSUE TITLE
Re-word BeLL-Apps tutorial (Creating configurations). 

### ISSUE THREAD

**Issue by sarvanivadali** [open-learning-exchange/open-learning-exchange.github.io#608]
Creating configuration in [Step 4](http://open-learning-exchange.github.io/#!././pages/bellapps.md) can be re-worded. I and two other interns made a mistake while specifying user and CODE - The note that specifies that both must use github username comes late. This note can either moved or re-worded - Better if someone can edit the existing image and specify the same.

**Comment by waryhermit** [comment]
@sarvanivadali @dogi Maybe we should add to the FAQ what we want people to do when this happens also.

**Comment by Supriyaranjan** [comment]
Hi @sarvanivadali  I will work on it.
Few questions to ask, I can move or edit the note but do I need to edit/change the image?Seems fine to me
http://open-learning-exchange.github.io/pages/uploads/images/configuration.png

**Comment by waryhermit** [comment]
@Supriyaranjan The image is fine, its just that people are seeing the note too late

**Comment by sarvanivadali** [comment]
Hi @Supriyaranjan Any new text or re-wording that makes it more clear. Or change existing image to something like :

![image](https://cloud.githubusercontent.com/assets/8753852/24573651/1d6c249a-1654-11e7-9560-d5e42b17a7c3.png)

Lets see what @waryhermit @dogi have to say.

**Comment by Supriyaranjan** [comment]
@sarvanivadali @waryhermit  Should I move the note before the image? Should I move all three lines from the note? 
![image](https://cloud.githubusercontent.com/assets/26332034/24573702/5c48e2fa-164c-11e7-8057-e99670bf105e.png)

**Comment by waryhermit** [comment]
Oh, you could make the "github username" and "code" text on the image more visible I suppose, but that would be bonus as far as I am concerned.

And yeah, move all lines.

**Comment by Supriyaranjan** [comment]
@waryhermit  Ok I will do that

**Comment by Supriyaranjan** [comment]
@waryhermit  @sarvanivadali  Does this image looks good? 
![c](https://cloud.githubusercontent.com/assets/26332034/24573861/6f8cbad2-164f-11e7-8053-6180b2211dca.png)

**Comment by Supriyaranjan** [comment]
@waryhermit  @sarvanivadali  Does this image looks fine? If yes then I will upload it
![cc](https://cloud.githubusercontent.com/assets/26332034/24573883/f7d6a0d8-164f-11e7-9cbc-234a016e84e2.png)

**Comment by waryhermit** [comment]
If its no bother I might give it a strong color so it catches peoples eye more, but yeah it looks good

**Comment by Supriyaranjan** [comment]
@waryhermit  Like Red? Even I was thinking that before.

**Comment by Supriyaranjan** [comment]
How is this one?
![cc](https://cloud.githubusercontent.com/assets/26332034/24573952/fbafe2f4-1650-11e7-820f-5a09aa4fd96d.png)

**Comment by waryhermit** [comment]
Yep that is good.

**Comment by sarvanivadali** [comment]
@waryhermit so image update is sufficient or need to move test as well ?

**Comment by Supriyaranjan** [comment]
@sarvanivadali  I moved the text before the image. Is that good?

**Comment by sarvanivadali** [comment]
@Supriyaranjan No preference. I guess you have enough information to start on your PR.

**Comment by dogi** [comment]
@Supriyaranjan @waryhermit and @sarvanivadali very good job

**Comment by waryhermit** [comment]
I think this was fixed by #613
