### ISSUE TITLE
Add directions for uploading images and screenshots to chat.md

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#615]
At the bottom? (maybe there is a better place)
Add how to create screenshots (WinMacUbuntu)
and drop them into gitter chat

best thing would be if the picture you drop says `A picture is worth a thousand words` ;)

kinda like this one
![](https://blog.sqlauthority.com/i/b/a-pic-1000-words.png)

**Comment by waryhermit** [comment]
Maybe to the FAQ as well?

**Comment by waryhermit** [comment]
Fixed by #688
