### ISSUE TITLE
The colon(:) in every step title is redundant

### ISSUE THREAD

**Issue by tianhaopx** [open-learning-exchange/open-learning-exchange.github.io#624]
I noticed at the end of each step's title, there is a colon. I think it's redundant since they are titles. Also, the titles consist as the table of contents in the left side. The colons are unnecessary.
<img width="756" alt="wx20170405-003805 2x" src="https://cloud.githubusercontent.com/assets/5724086/24689976/36e8204e-1998-11e7-909a-a99ad31aea0d.png">

See pull request #627

**Comment by kylemathias** [comment]
I think it would look better without ":". Let someone put there thoughts down about it first before making the change.

**Comment by Loshma93** [comment]
Yes, I agree with that. It would look better if we remove semi-colon at the end of title's.
