### ISSUE TITLE
Getting blank pages for automatedtestingcodeceptjs.md and automatedtestingpython.md

### ISSUE THREAD

**Issue by Supriyaranjan** [open-learning-exchange/open-learning-exchange.github.io#625]
I am getting blank pages when trying to open http://open-learning-exchange.github.io/#!pages/automatedtestingpython.md and http://open-learning-exchange.github.io/#!pages/automatedtestingcodeceptjs.md. 
Although these two files are present in "pages" folder. I tried in chrome, mozilla, IE and safari(mobile) browsers

**Comment by waryhermit** [comment]
@paulbert I think this might be related to the recent upgrade of the MDwiki, could you take a look?

**Comment by paulbert** [comment]
The syntax highlighting library is crashing. I'm checking now to see if it'll work with the latest version of that script.
