### ISSUE TITLE
Redundant " # " after each heading.

### ISSUE THREAD

**Issue by prachi-chauhan** [open-learning-exchange/open-learning-exchange.github.io#628]
This "#" appears once you hover the mouse pointer around the end of the title. It is probably trying to redirect to the header of the page but it doesn't do that properly.

Proposed solution:
Instead a semi-opaque arrow head can be provided in the right corner which redirects to the top of the page.[
![screen shot 2017-04-05 at 4 03 10 pm](https://cloud.githubusercontent.com/assets/8962546/24727097/5f2a3092-1a1a-11e7-9cae-80b81768706f.png)
](url)

**Comment by waryhermit** [comment]
That is actually intended - it allows you to link to a specific part of the document. Check the url in the browser bar each time you click one of the `#`

**Comment by dogi** [comment]
thanks @prachi-chauhan and @waryhermit - I am closing this issue

**Comment by prachi-chauhan** [comment]
@dogi @waryhermit i understand that the URL changes, but from a user's perspective(a person with no knowledge in web development) it does not seem to "show" and "visible" effect. it just stays there. I think it would be wiser to use a redirect arrow to the top of the page. And instead of providing this "hard to find" #, we can provide an "go to top" option on the bottom right of the page??

**Comment by prachi-chauhan** [comment]
*any

**Comment by waryhermit** [comment]
@prachi-chauhan Well that would be for an entirely different purpose than the anchor / bookmark tags that are there. The `#` is just so you can link to a certain heading, and when they click on your link it will scroll to that heading. If you think there needs to be something that you can click to go to the top of the pages it doesn't mean the `#` are redundant. 

I agree that having the `#` appear on mouse over is not the best design, perhaps it would be better if the headers were themselves could be clicked for the same effect.

In any case, it sounds like what you should do is create a new issue(s) for either:

- Making anchor links more intuitive
- Having a return to top of page link/button in footer

And we will give our thoughts on those ideas there.
