### ISSUE TITLE
The redirect page to MDwiki is not a smooth redirect.

### ISSUE THREAD

**Issue by prachi-chauhan** [open-learning-exchange/open-learning-exchange.github.io#629]
It kind of shows a mediator page for a second. This is a minor fix that needs to be made.
![screen shot 2017-04-05 at 4 13 13 pm](https://cloud.githubusercontent.com/assets/8962546/24727325/2ff5d000-1a1b-11e7-81b1-47cf671c2e66.png)

**Comment by prachi-chauhan** [comment]
In fact all the tabs on the page header redirect to a different page in this way. In-page redirects work fine!

**Comment by dogi** [comment]
@prachi-chauhan I think I understand - can you also explain how you wanna fix this ;)

**Comment by prachi-chauhan** [comment]
I think there might be some scripting error in the web page, could be an error with the <nav> tag. Would have to see the script for finding the bug. Will have to track the error in the script first and then work on eliminating it.
It could also be a styling error. I think that maybe there is an overlap of script code somewhere , which makes the page hang and then redirect.
So many options to think on!

**Comment by prachi-chauhan** [comment]
*/nav/ tag
did not print in my comment as i put it inside <>

**Comment by waryhermit** [comment]
Have you made any progress on this issue?

**Comment by mappuji** [comment]
@prachi-chauhan 

I want to give a hint. In `index.html` you could find something like this

![image](https://cloud.githubusercontent.com/assets/11813607/25155840/6bbb17ca-24c1-11e7-833a-f7b36e2edabf.png)
