### ISSUE TITLE
Redirect of understanding the flow of the android application leads to a heading that has no content in it!

### ISSUE THREAD

**Issue by prachi-chauhan** [open-learning-exchange/open-learning-exchange.github.io#630]
![screen shot 2017-04-05 at 4 37 56 pm](https://cloud.githubusercontent.com/assets/8962546/24728149/6262f09c-1a1e-11e7-9fc2-b45ec15624d5.png)

**Comment by waryhermit** [comment]
@prachi-chauhan That page literally isn't done 😄 

Problem is we need interns that are working on the android application to update it, I don't think prospective interns will have the knowledge to do it.

**Comment by dogi** [comment]
> @prachi-chauhan That page literally isn't done ￼

@waryhermit I totally agree

@leonardmensah @kylemathias and @zeivhann will soon improve this page ;)

**Comment by prachi-chauhan** [comment]
@waryhermit @dogi i think we can learn it  on the web and try to fix it. Android ain't that complicated. Guys with some idea of app development can handle this!

**Comment by kylemathias** [comment]
@waryhermit @prachi-chauhan @dogi I am going to start some of this today. i want to update the guide with the extra steps i did to get the Android application working.

**Comment by KodyKendall** [comment]
I have a little bit of android experience. If you guys want me to take a look at it, I can.

**Comment by waryhermit** [comment]
@KodyKendall Once you have finished the first steps you could work on this issue, but it looks like kyle is already on it.

@dogi  I think it might have been better for us to have closed this issue and made a new one on ole-vi - this isn't really a good issue for aspiring interns.

**Comment by kylemathias** [comment]
i have started the update. The take home guide is a work in progress. #668
