### ISSUE TITLE
Improve sync publication part in "Step 7 - Nation BeLL"

### ISSUE THREAD

**Issue by tianhaopx** [open-learning-exchange/open-learning-exchange.github.io#632]
The tutorial told me 

> Usually, next to the update, you should also see two publications ready to be downloaded.

But I didn't see that. I need to go to nation side, send the only one publication to me. We should add a more detailed tutorial here.

**Comment by waryhermit** [comment]
@tianhaopx @dogi typically sends the publications when he approves your community - but you bypassed that step 😋

**Comment by tianhaopx** [comment]
@waryhermit so do I need to make some change for #632 and #631 ?

**Comment by dogi** [comment]
@tianhaopx hope you understand if I close this issue since only you by sneaking into nation ever encountered it ;)
