### ISSUE TITLE
URL format is not consistent in MDWiki

### ISSUE THREAD

**Issue by tianhaopx** [open-learning-exchange/open-learning-exchange.github.io#633]
URLs in the left side column and paragraph are in the format: `http://open-learning-exchange.github.io/#!./pages/...`
URLs in the navigation bar are in another format: `http://open-learning-exchange.github.io/#!pages/...`
Although both of them work, we should keep consistent in one website.

**Comment by dogi** [comment]
@tianhaopx ;)

yes - the `./` can (and maybe should?) be removed ...

**Comment by waryhermit** [comment]
@paulbert Did https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/626 fix this issue?

**Comment by paulbert** [comment]
@waryhermit Yes it did.

**Comment by waryhermit** [comment]
@paulbert Thanks, I will close this issue then.

**Comment by tianhaopx** [comment]
@paulbert @waryhermit No, I don't think so.
![image](https://cloud.githubusercontent.com/assets/5724086/24939601/971037f8-1f0c-11e7-9776-49ce8955a1d8.png)

**Comment by waryhermit** [comment]
@tianhaopx I think that is a separate issue which I don't even know if we can fix. The more times you hit that `#` the more `./` are added. As far as I know the anchor links are automatically generated.

But maybe you already realized that. I think me and @paulbert were thinking of link formats that needed to be changed in markdown files. If you want I can rename the issue and reopen it.

**Comment by tianhaopx** [comment]
@waryhermit Yes, please reopen it. 

All links referred to another markdown file and all anchor links are automatically generated by the code in mdwiki.js. But it shouldn't add `./` to these links. You can test it on [mdwiki official website](https://dynalon.github.io/mdwiki/#!index.md).
That's why I replace the mdwiki.js in #636. Check the [result](http://rawgit.com/tianhaopx/tianhaopx.github.io/fix/#!pages/firststeps.md). No more `./` now.

I don't think `./` issue is related with link formats in markdown files. Although #626 changed link formats, it still has `./`
<img width="502" alt="wx20170412-124147 2x" src="https://cloud.githubusercontent.com/assets/5724086/24969076/7c7e38e2-1f7d-11e7-871a-2c76970af4dd.png">

**Comment by waryhermit** [comment]
@tianhaopx I will reopen it depending on your response to @paulbert comment https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/636#issuecomment-293678688

**Comment by tianhaopx** [comment]
@waryhermit Thanks. Just leave this one closed. Reopen it may cause some confusion to other people. For the `./` issue of anchor links, what about open a new one?

**Comment by waryhermit** [comment]
@tianhaopx So basically clicking an anchor link should only add `./` once, right? That is the issue you mean?

**Comment by tianhaopx** [comment]
@waryhermit Yes.

**Comment by waryhermit** [comment]
@tianhaopx Sure, you can open one on that. You might also consider opening an issue at https://github.com/Dynalon/mdwiki/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20anchor as well.
