### ISSUE TITLE
Step 7 title and description modification

### ISSUE THREAD

**Issue by praharpatel** [open-learning-exchange/open-learning-exchange.github.io#634]
# It is better to add 's' after BeLL in Step 7. So, it would go from Nation BeLL to Nation BeLLs. # 

![image](https://cloud.githubusercontent.com/assets/15759751/24734823/679748c2-1a34-11e7-8d4e-5ac677c19ca4.png)

## The reason being, if we follow the link to nation.md, it's title is "Nation BeLLs". It is important that we maintain the same name so there will be less confusion.

![image](https://cloud.githubusercontent.com/assets/15759751/24734914/03317988-1a35-11e7-8c6d-ea7a92be0c55.png)

# Possible Solution- #
 Either we add 's' to the Step 7 title in firststeps.md 
### OR ###
 We remove the 's' from nation.md

**Comment by kylemathias** [comment]
I think it is supposed to be "BeLL". Let someone other than me comment about this issue before you make changes and make a pull request.

**Comment by Loshma93** [comment]
@praharpatel I think it would be better to remove 's' in nation.md page instead of adding 's' in heading of step-7.

**Comment by praharpatel** [comment]
I agree. Removing 's' from nation.md will be less tedious. @Loshma93

**Comment by praharpatel** [comment]
@dogi @waryhermit . What do you guys think?

**Comment by waryhermit** [comment]
Removing the `s` from `nation.md` seems fine to me. Go ahead and create a pull request.

**Comment by waryhermit** [comment]
@praharpatel Do you still plan to make a pull request? Maybe I missed it?
