### ISSUE TITLE
Vagrant.cmd.exe opens every time turn on the computer.

### ISSUE THREAD

**Issue by Rlisa33** [open-learning-exchange/open-learning-exchange.github.io#635]
Command prompt opens and starts vagrant every time I turn on my computer. Interns need to avoid this. I reads "Starting vagrant in power down state. But later says failure to start vagrant. Close command prompt and reopen it with adding these commands
cd  %USERPROFILE%\ole--vagrant-vi
vagrant up
If the screen like this shows up
![image](https://cloud.githubusercontent.com/assets/26748347/25209319/54d8ff36-2548-11e7-8dc2-7a856d676c7e.png)
You need to install hyper -v in windows 7pro software and up to windows. 8.1. Hyper-V is a server-side application up to Windows 8.1 and upcoming version of Windows 10, which include it in the client, too (as the update of Virtual PC)
image

**Comment by waryhermit** [comment]
@Rlisa33 Could you explain more? Right now I am afraid I have no idea what you mean.

**Comment by Rlisa33** [comment]
You can check to see if you follow all the steps on http://open-learning-exchange.github.io/#!./pages/githubandmarkdown.md. In order for the pull request to come up you need to then go to the pull request tab and check the pull request. If no pull request is there click on the green button called new pull request. Then add the repositories you would like to pull. Then also add a name for the pull request and use some mark down syntax with the messages you type. Click create pull request. The link given shows how to rename and fork pull request. You can check on you pull request by going to github.com and signing in. Click on the repository and the click on pull request. If the pull request does not come up and it says error. Delete the pull request and re create a pull request by clicking on the new pull request green button. The choose the repositories to link for a pull request. Type the message and the name of the message topic in the proceeding webpage to create the pull request. then choose either to link to a new branch or an existing branch. press commit changes
 @Rlisa33

**Comment by Supriyaranjan** [comment]
@Rlisa33  As far as I understood is you are getting a blank page? Can you please take a snapshot of that and post here?

**Comment by waryhermit** [comment]
@Rlisa33 
OK, I still don't understand, sorry.

1. What page of the mark down wiki needs to be changed?
2. And what do you think needs to be changed about said page?

**Comment by waryhermit** [comment]
@Rlisa33 Again, please explain what you mean when you say that "_because both links to download software for bellapps is not working._"

What errors do you get?
Screenshots?

**Comment by Rlisa33** [comment]
I paste a screen print to the gitter chat

**Comment by Rlisa33** [comment]
Here is the screen shot 
![image](https://cloud.githubusercontent.com/assets/26748347/25162087/04f2feb4-248e-11e7-9ec2-3f3e0eccfcd9.png)

**Comment by Rlisa33** [comment]
When using the bellapps sodftware download I receive a screen that comes up evertime I power on my computer and it says Starting vagrant from posered down state. Where as after a long period there is a message than says the operation returned because of timed out period. Also I cannot get the bellapps webpage through this second computer I own of that has windows 7 OS. My first computer does not give this problem.

**Comment by waryhermit** [comment]
@Rlisa33 That error does not seem to be related to our software to me, we do not use anything called "OPINIO". I think that belongs to something called "OpinionSquare". If you have something called "OpinionSquare" I would uninstall it and see if the vagrant starts correctly after that,

**Comment by Rlisa33** [comment]
I have uninstalled opinionsquare and the problem is still happening

**Comment by waryhermit** [comment]
@Rlisa33 You get the same error or a different one?

**Comment by Rlisa33** [comment]
The oinionsquare message does not comes up its gone but tje Command prompt comes up. I was waiting a while on my windows seven computer and it stayed blank for quite a while.

**Comment by waryhermit** [comment]
If you open a command prompt do
```
cd  %USERPROFILE%\ole--vagrant-vi
vagrant up
```

What do you get?

**Comment by Rlisa33** [comment]
I am doing it right now.

**Comment by Rlisa33** [comment]
it is taking time. I think my computer is now slower.

**Comment by Rlisa33** [comment]
Well my computer with windows 7.

**Comment by Rlisa33** [comment]
ok somthing is happening.

**Comment by Rlisa33** [comment]
![image](https://cloud.githubusercontent.com/assets/26748347/25208886/863b32fe-2545-11e7-858f-8b52675d5ea3.png)

**Comment by Rlisa33** [comment]
![image](https://cloud.githubusercontent.com/assets/26748347/25209319/54d8ff36-2548-11e7-8dc2-7a856d676c7e.png)

**Comment by Rlisa33** [comment]
I am waiting for the next part of the instructions

**Comment by Rlisa33** [comment]
okay I will soon close command prompt and start all over tomorrow

**Comment by Rlisa33** [comment]
I cl;osed command prompt good night!

**Comment by dogi** [comment]
@Rlisa33 this looks like an error of Bios with disabled or not existing `hyper virtualization`

in FAQ we have some help for you

**Comment by Rlisa33** [comment]
ok can this issue be approved?

**Comment by Rlisa33** [comment]
Okay. I will look it up.

**Comment by mappuji** [comment]
@Rlisa33 thank you for your issue.

If you found any problem and you need assistance, please send your problem and appropriate description on our Gitter chat.

For this repository, you should raise issues related to [open-learning-exchange.github.io site](http://open-learning-exchange.github.io) only.

Last, there is no such issue we formally said as "approved", as long as you raise a proper issue, we can say it is approved for your vetting process.
