### ISSUE TITLE
Can't access intern orientation via calendar address provided

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/open-learning-exchange.github.io#639]
I have some problem when I want to add given calendar address to my Google Calendar.

The given calendar address is:
```
b9jqne24d57p46p886kh861arg@group.calendar.google.com
```

![image](https://cloud.githubusercontent.com/assets/11813607/24810742/97070f7e-1bed-11e7-9220-627f54e13a3f.png)

**Comment by waryhermit** [comment]
@dogi did you restrict access? I think it worked back when I tired it.

**Comment by waryhermit** [comment]
Fixed by #682
