### ISSUE TITLE
Improve Welcome Page for Markdown Wiki

### ISSUE THREAD

**Issue by xinglunxu** [open-learning-exchange/open-learning-exchange.github.io#64]
We are asked to follow open-learning-exchange in the welcome page of the Markdown wiki but github does not allow us to follow organization. We need to remove that.

**Comment by 314159265359** [comment]
I will update the index markdown file to remove mention of the organization in step 2 of Assignment 4.

**Comment by 314159265359** [comment]
Updated index markdown file and sent pull request.  Removed OLE links in Assignment 3 step 4 and Assignment 4 step 2
