### ISSUE TITLE
Suggestion: Seperate intern profile files from pages folder

### ISSUE THREAD

**Issue by yssdnj** [open-learning-exchange/open-learning-exchange.github.io#646]
Hi, I have a suggestion that separate those intern’s profile .md files from the pages folder. Like, we could create a new folder called internProfile under pages folder which is only used to store the candidate intern profile(.md file). It could make the layout clear.

**Comment by Loshma93** [comment]
@yssdnj Yes, that would be great if we implement that. So, personal pages and other pages will be in separate folders without any confusion.

**Comment by sarah-lu102** [comment]
@yssdnj that's a good point; there are also profiles from previous years mixed in with the ones that have been recently added, so separating intern profiles into folders by year would work!

**Comment by waryhermit** [comment]
@yssdnj I like this idea, but there is already [an issue for it here](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/568).
