### ISSUE TITLE
Confusion between Step 6 and 8.

### ISSUE THREAD

**Issue by yssdnj** [open-learning-exchange/open-learning-exchange.github.io#647]
- When I read Step 9, I find that step 6 and step 8 are no big difference.  Both are asking interns to create issues, add comments to certain issues and pull requests. So I think there is no necessary to part them as two steps. If step 6 is an issue tutorial, it should provide a test material to create a test issue and a posted issue which interns can make comments on. If not, I think step 6 and 8 could merge as one. 

- a small suggestion
It is a little weird to put step 7 between step 6 and 8. Step 7 should be put behind step 4 (BeLL-Apps Tutorial), because they are both about BeLL-App.

- [ ] <img width="864" alt="screen shot 2017-04-10 at 6 35 31 pm" src="https://cloud.githubusercontent.com/assets/15866693/24886014/d3e6f81c-1e1f-11e7-9f50-d686ca657af4.png">

**Comment by mappuji** [comment]
As far I know the main reason to separate step 6 with step 8 is in step 6 we only want the aspiring intern to learn about how to create an issue. The point is to familiarize. For the step 8, we want the aspiring intern to exercise.

Let others point their opinion.

**Comment by sarah-lu102** [comment]
I think the instructions in step 8 were more explicit; it said to create issues about the wiki, whereas in step 6 it just said to create an issue, which was a bit confusing. Also the fact that step 6 was named Issues tutorial gave me the impression that it was something to just read through, rather than to actually implement (since I read ahead to step 8 and figured that would be the actual implementation). Maybe moving the tutorial of step 6 to step 8 would make it easier so we can just do the issues all at once.

**Comment by yssdnj** [comment]
Suggestion of arrange the steps like below imag.

Reason: group the similar topic steps together. 

- Step 0 is the brief overview. 

- Step 1 - 4 are all about BeLL-App from installation, environment building to BeLL web introduction(community and nation). 

- Step 5 - 9 are all about how to operate GitHub including the basic GitHub knowledge and how to collaborate (create an issue and discuss it, pull a request)

<img width="500" alt="screen shot 2017-04-11 at 10 31 39 am" src="https://cloud.githubusercontent.com/assets/15866693/24914392/1c8952f4-1ea2-11e7-974f-c5039a5d1347.png">

**Comment by yssdnj** [comment]
@sarah-lu102 I agree with what you said. When I read Step 9, I realize that I need to do severial implementations in Step 6.

**Comment by dogi** [comment]
thank you all for this suggestions and comments

as @mappuji suggest one of the reasons is in step 6 to learn and in step 8 to exercise
other reasons are:
- handle at step 6 one open PR - at step 8 do the same with 3 contemporaneous open PRs on the same time ...
- some steps of BeLL-Apps need hands from my side, the nations side: like accepting communities and sending publication (after step4 and before step 7) and survey (after step 7 and before end)

@yssdnj if we had an auto-accepting community feature we could maybe change the steps order ...

... therefore I open an issue on https://github.com/open-learning-exchange/BeLL-Apps/issues/736
