### ISSUE TITLE
Suggestion: Replace "First Steps" with "Guide"

### ISSUE THREAD

**Issue by yssdnj** [open-learning-exchange/open-learning-exchange.github.io#649]
How about replace "First Steps" with "Guide" in main navigation bar? 
I think that is more reasonable. How do you guys think?

<img width="1424" alt="screen shot 2017-04-10 at 1 13 44 pm" src="https://cloud.githubusercontent.com/assets/15866693/24886439/91ae7da0-1e22-11e7-889a-62681b6a48d4.png">

**Comment by sarah-lu102** [comment]
I think it might be more clear if we kept the first steps, because the process is composed of steps- it'll make it easier for people to break down all the things they have to do before becoming an intern

**Comment by waryhermit** [comment]
To me "Guide" gives a more optional feeling. These are the `First Steps` you **must** do in order to become a intern.

**Comment by dogi** [comment]
@yssdnj thanks ;)
