### ISSUE TITLE
Step 1 installation clarifications

### ISSUE THREAD

**Issue by sarah-lu102** [open-learning-exchange/open-learning-exchange.github.io#651]
I already had virtualbox installed on my computer before we were supposed to install it for step 1-- I had a vm for my programming class already on my virtualbox, and I was afraid that the installation would reinstall virtualbox and erase the vm that I needed for class. I would add on to the instructions [here](https://github.com/dogi/ole--vagrant-vi) that if you already have virtualbox or any of the other applications installed, nothing will happen to them.

**Comment by sarah-lu102** [comment]
this is what the vm looks like- if people happen to use other vms on virtualbox, I've found it convenient to open the vm through the app itself instead of vagrant up (although maybe you would prefer if we used the command line?)
<img width="399" alt="vm" src="https://cloud.githubusercontent.com/assets/12993520/24895703/aceaa16a-1e46-11e7-81d1-3e33aa3cd02a.PNG">

also, an alternative to vagrant suspend or vagrant halt commands, these options pop up when I close the vm.
<img width="194" alt="vmclose" src="https://cloud.githubusercontent.com/assets/12993520/24895851/3712917c-1e47-11e7-8d08-2d4f9a0aa15c.PNG">

**Comment by waryhermit** [comment]
Vagrant up will only start the vm corresponding to the vagrant file in the directory you have you shell window pointed at the moment. So it shouldn't matter if you have other VM's installed I think.

**Comment by sarah-lu102** [comment]
Yes-- but for the installation of virtualbox itself in step 1 (BeLL installation), I would like to add that if you already have existing VMs, the virtualbox installation won't mess those up (I was afraid they would when I ran the command in my admin command prompt)

**Comment by waryhermit** [comment]
Well, make a pull request and we will think about it.
