### ISSUE TITLE
Step 7 dummy user clarification

### ISSUE THREAD

**Issue by sarah-lu102** [open-learning-exchange/open-learning-exchange.github.io#652]
before syncing with the nation, we have to create a dummy user in our community. The instructions specified to create a dummy with a username and a password that isn't our password. It is unclear whether we should remember the dummy username and password if we wanted to delete that person from our community. It is also unclear if the dummy user would eventually be removed from the community. If it is only to sync with the nation (a one-time thing), it would be helpful to know what would happen to the dummy user and whether or not we should remember the login credentials. @dogi @waryhermit  Am I understanding the purpose of the dummy correctly?

**Comment by sarah-lu102** [comment]
I would edit it here
<img width="867" alt="dummyuser" src="https://cloud.githubusercontent.com/assets/12993520/24896159/7b002722-1e48-11e7-8b83-7de9040a1c51.PNG">

**Comment by waryhermit** [comment]
@sarah-lu102 Basically what happens with the dummy after you finish the steps is irrelevant, so we didn't clutter up the steps talking about it much.
