### ISSUE TITLE
First Steps menu in header doesn't match with the actual steps

### ISSUE THREAD

**Issue by sarah-lu102** [open-learning-exchange/open-learning-exchange.github.io#653]
<img width="956" alt="menu" src="https://cloud.githubusercontent.com/assets/12993520/24896637/9f54ac9a-1e4a-11e7-99cf-9eac6bcb6ac6.PNG">

In order to get to steps 0, 1, and 8, we can't access it through the header dropdown menu for the First Steps section. It may also be helpful to include the step number for easier access and to keep it consistent with the content on the First Steps page.

**Comment by yssdnj** [comment]
Hi, @sarah-lu102 Do you mean to add all of step 0 - 9 to the dropdown menu? If So, I think the dropdown menu would be a little complicated. If someone would like to see all the steps, he or she could click "Start Here". In my opinion, we could add some key words of different topics. For example, BeLL Installation, BeLL Tutorial, Markdown, Git Rpositories, Git Issues. It also could give the beginner an overall sense of what this FirstStep page.

**Comment by mappuji** [comment]
Hi @sarah-lu102 , I agree with @yssdnj better to not clutter the header menu with all the steps, and since because no follow up on this issue, I will close this issue.
