### ISSUE TITLE
Change date format in the Members tab

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#662]
Currently, the Join Date and the Leave Date use the format **YYYYMMDD**.
![screen shot 2017-04-11 at 10 57 49 pm](https://cloud.githubusercontent.com/assets/13564371/24940681/556449f4-1f0a-11e7-857f-087df8e6dffb.png)

I think we should change to the standard format  **YYYY-MM-DD**.
For example, if one copies the table to Excel, it will automatically format as date.

**Comment by dogi** [comment]
thanks @duongdo27 - please check https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/550
