### ISSUE TITLE
Improve index.md

### ISSUE THREAD

**Issue by sarah-lu102** [open-learning-exchange/open-learning-exchange.github.io#666]
The text is more important than the image, but right now the image is overpowering, and the text is too small. I think it takes away from its purpose of informing readers about OLE. Perhaps we could resize the image and increase the font of the text?

---
Description update after the discussion.
2017-04-01 by @mappuji
> Summarizing @dogi 
>After some thinking I came to the decision that we should re-purpose this page,
which @EmilyLarkin and I created to fill the empty spot ;P
>
>so that in the future we can accommodate more groups then just the virtual interns ...
>
>... but also:
>- Volunteers
>- Techgeniuses (people in charge of Communities in field) 
>- normal BeLL-Apps user which for example wanna find the MAnual
>- ...

**Comment by mappuji** [comment]
@sarah-lu102 could you tell us specific page you are talking about? so that we will in the same page with your suggestion.

**Comment by dogi** [comment]
@sarah-lu102 maybe you just add a screenshot to this tread ...

**Comment by waryhermit** [comment]
@mappuji @dogi Its the page nobody goes to 😛 
http://open-learning-exchange.github.io/#!index.md

**Comment by kylemathias** [comment]
@sarah-lu102 The image i think is fine for its size. You want people, on there very first visit, to get this image into there heads that this is what the whole OLE program is about. That image, is essentially, a snap shot of the OLE environment.

This is my opinion, and of course could be wrong, but i think it is fine as is.

**Comment by Supriyaranjan** [comment]
@dogi  @waryhermit @mappuji @kylemathias I kind of agree with @sarah-lu102 . I think a little smaller image on the page would look nice and we don't have to scroll down to look at the whole image.
I have tried resizing the image in index.md. Please look at https://rawgit.com/Supriyaranjan/Supriyaranjan.github.io/Supriyaranjan-patch-11/#!index.md
If it looks fine the I will create the pull request

![oleinternational](https://cloud.githubusercontent.com/assets/26332034/24989639/a256afb2-1fd3-11e7-8f40-b682934f710c.png)

**Comment by sarah-lu102** [comment]
@Supriyaranjan yes, that is the [page ](http://open-learning-exchange.github.io/#!index.md)I'm talking about!

**Comment by dogi** [comment]
After some thinking I came to the decision that we should re-purpose this page,
which @EmilyLarkin and I created to fill the empty spot ;P

so that in the future we can accommodate more groups then just the virtual interns ...

... but also:
- Volunteers
- Techgeniuses (people in charge of Communities in field) 
- normal BeLL-Apps user which for example wanna find the MAnual
- ...

**Comment by waryhermit** [comment]
@dogi I don't think anyone will work on this issue until you can give more concrete details about the re-purposing. Might be a good thing to discuss during some happy hacking session.
