### ISSUE TITLE
Broken link on internorientation.md

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/open-learning-exchange.github.io#667]
This link...
![image](https://cloud.githubusercontent.com/assets/26488295/24970861/bb3edc8e-1f6a-11e7-9824-22184be7ab6f.png)
...leads to this page:
![image](https://cloud.githubusercontent.com/assets/26488295/24970924/e70bae8c-1f6a-11e7-8b84-7e934717c83b.png)

Would be a simple fix for a future intern. can someone post the correct link?

**Comment by mappuji** [comment]
Hi @kylemathias I have posted the same issue here #639

**Comment by dogi** [comment]
@kylemathias and @mappuji since this was fixed I am closing the issue
