### ISSUE TITLE
Improve BeLL App's log-in page by adding "Forgot password?" for the user

### ISSUE THREAD

**Issue by shahswet** [open-learning-exchange/open-learning-exchange.github.io#671]
![snip-password](https://cloud.githubusercontent.com/assets/17865137/24983880/47cee3a6-1fa7-11e7-922a-dfac66719521.PNG)

We need to improve BeLL App's log-in page by adding "Forgot password?" for the user. Giving the user the chance to log-in to BeLL App when s/he forget's the password enhances the BeLL App's user-friendly feature.

**Comment by yssdnj** [comment]
Totally agree! This issue should be in high prority

**Comment by mappuji** [comment]
hi @yssdnj and @shahswet it is a good suggestion, but issues and improvement suggestions in this repository is limited to [OLE MD Wiki](http://open-learning-exchange.github.io/#!index.md ). Issue for 
BeLL App particularly must posted here on [OLE VI BeLL Apps](https://github.com/ole-vi/BeLL-Apps)

**Comment by waryhermit** [comment]
We have an issue already for this on the BeLL-Apps repo: https://github.com/open-learning-exchange/BeLL-Apps/issues/629
