### ISSUE TITLE
Hover popup for first steps and teams menu in the header

### ISSUE THREAD

**Issue by shahswet** [open-learning-exchange/open-learning-exchange.github.io#672]
![hovervsclick](https://cloud.githubusercontent.com/assets/17865137/24989065/19cf94b2-1fc7-11e7-8cff-9948e270cd4e.JPG)

We should have hover popup for the First Steps and Teams menu in the header rather than a mouse click. Hover popup will let the user make the decision to take that action or not, giving them more control over their experience. Many users believe that when their menus open on hover, they’re faster and easier to use. And the menus that open on hover save users a click.

**Comment by kylemathias** [comment]
I think this is more of a preference issue. Windows start menu is a click to open situation, a lot of things are. Hover over and open is more of what happens once you are in the menu. You can let others comment before anything happens to this issue, but your time might be better spent fixing something that is broken.

**Comment by praneetharra** [comment]
@shahswet I think bringing this feature is not in bounds of OLE. CSS for changing the tabs is part of the MDWiki theme used.

**Comment by paulbert** [comment]
Hi @shahswet. Good thought, but I'll echo @kylemathias to say this isn't a high priority for us because the menu isn't broken.  If you have a solution or can create one please submit a pull request.  Otherwise we'll close this issue in 5 days.

**Comment by mappuji** [comment]
Closed because of less urgent and no follow up.
