### ISSUE TITLE
Click on anchor # continually adds ./ in the URL

### ISSUE THREAD

**Issue by tianhaopx** [open-learning-exchange/open-learning-exchange.github.io#673]
When we click on anchor `#` next to the title multiple times, it continually adds `./` in the URL. 
It should just add `./` once.
![](https://cloud.githubusercontent.com/assets/5724086/24939601/971037f8-1f0c-11e7-9776-49ce8955a1d8.png)

**Comment by kylemathias** [comment]
look at closed issue #633 . there is some discussion about this specific issue.

**Comment by duongdo27** [comment]
I think the anchor link its own are generated by MDWiki, which we do not have control over. 
However, we can remove the href attribute with JavaScript on our page.

> $(".anchor-highlight").children().removeAttr('href')
