### ISSUE TITLE
FAQ questions in bold fonts

### ISSUE THREAD

**Issue by shahswet** [open-learning-exchange/open-learning-exchange.github.io#674]
![faq](https://cloud.githubusercontent.com/assets/17865137/24990156/027e1696-1fcf-11e7-95fd-8ea9cc4090c8.JPG)

The questions and answers looks like some paragraphs in above screenshot. The questions font are not contrast which makes us difficult to find the answer of particular question. If the questions are written in __bold__ font then I believe it will look more attractive and will be easier to find the answers.

![faq changes](https://cloud.githubusercontent.com/assets/17865137/24990407/012b00ae-1fd1-11e7-9437-b5d802619987.JPG)

**Comment by waryhermit** [comment]
Sounds good

**Comment by mappuji** [comment]
@shahswet good idea, you can implement your idea and raise a PR for this :smile:
