### ISSUE TITLE
Left column overlap the main content

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#676]
When we go to any page in Open Learning Exchange and **scroll down**, the left column **always overwhelm** the main content.
I think we should make changes to avoid that.
![screen shot 2017-04-13 at 1 22 06 pm](https://cloud.githubusercontent.com/assets/13564371/25018674/8158a066-204d-11e7-905b-785a6c92e3bf.png)

**Comment by yssdnj** [comment]
Hi, @duongdo27 it is actually an issue - that is what issue #622 is for. If you have any thoughts, you could make comments there 😊.

**Comment by waryhermit** [comment]
Closing since duplicate issue.

**Comment by duongdo27** [comment]
@waryhermit My suggested fix for the issue is change .css("width") to .width().
According to jQuery documentation

> The .width() method is recommended when an element's width needs to be used in a mathematical calculation.

Please checkout the fix on [my version of OLE](https://duongdo27.github.io/open-learning-duongdo.github.io/#!pages/faq.md)

Here is [my commit](https://github.com/duongdo27/open-learning-duongdo.github.io/commit/e1ee9be86eba66634793b4f48c80d38c691b239f)
