### ISSUE TITLE
Port (another) HTML Apps to BeLL-App Platform

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/open-learning-exchange.github.io#681]
>Update
Right now we are able to upload htmlapp as a zip on BeLL-App.

Hi Aspiring Interns and Interns,

Throughout my internship journey, I have *ported* some HTML Apps to BeLL-App platform, but since I will work on some other issues, I will encourage you to try this exercise.

It is a fun exercise which you could follow the steps [here](http://open-learning-exchange.github.io/#!pages/htmlresources.md) and [this is](https://docs.google.com/document/d/1aAzah833gWCQ2hWtGyMJLIK83nmunPJn42bnliLrxDk/edit) the background of the project. Basically, we want to port an educational HTML app to our platform. The kind of HTML app is educational games/materials.

By doing this exercise you would empower people in rural area to learn and enjoy educational stuffs.

Here are some apps you could port:
- [x] Adverse Selection [repository](https://github.com/tomasreimers/adverse-selection) and [preview](http://tomasreimers.github.io/adverse-selection/) by @Loshma93 [finished](http://vi.ole.org:5999/resources/ad0280d0fcccbfe1a38aab770100206a/index.html)
- [x] Exploding Bob [repository](https://gelatolabs.xyz/explodingbob/) and [preview](https://gelatolabs.xyz/explodingbob/game/index.html) @Supriyaranjan [finished](http://vi.ole.org:5999/apps/_design/bell/bell-resource-router/index.html#open/da6621457de466585455b8aec4001052/Explodingbob)
- [x] Reciclar [repository](https://github.com/alexishida/reciclar) and [preview](http://alexishida.com/reciclar/) by @Supriyaranjan in [finished](http://vi.ole.org:5999/resources/da6621457de466585455b8aec4003cc3/index.html)
- [x] First Step MDWiki OLE #458 [repository](https://github.com/open-learning-exchange/open-learning-exchange.github.io) and [preview](http://open-learning-exchange.github.io/#!pages/firststeps.md) by @paulbert [finished](http://vi.ole.org:5999/resources/3c1b7db56201da89eba5c1fc4d0021ac/index.html#!index.md)
- [ ] and please update the list if you have one

Suggested workflow:
1. Please give a sign that you work on a specific porting by giving a comment or edit this post if you can.
2. After you have successfully *ported* an app, please give the link here to be able to test the result.
3. I will update this issue if someone has finished the specific porting.

Have fun :smile:

**Comment by waryhermit** [comment]
Another issue like this one is to make the first steps markdown wiki a BeLL App html resource: https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/458

**Comment by Supriyaranjan** [comment]
@mappuji @dogi  I am working on to port "Exploding Bob" HTML app

**Comment by Supriyaranjan** [comment]
@mappuji  @dogi @Loshma93 I am working on Reciclar

**Comment by mappuji** [comment]
@Supriyaranjan awesome, please do it carefully (I suggest to do it one by one :smile: )

Exploding Bob then Reciclar. Good luck.

**Comment by Supriyaranjan** [comment]
@mappuji  Sure I will start working on another after first one is done and confirmed

**Comment by Loshma93** [comment]
@mappuji I am encountering problems while downloading "Almost Bejeweled" App from the repository. I think it would be better to remove it from the list.

**Comment by mappuji** [comment]
done @Loshma93 

For others, you can add another app to the list.

**Comment by Loshma93** [comment]
@mappuji I will add more apps to the list if I find some.
