### ISSUE TITLE
Confusion in "GitHub and Markdown" step while setup

### ISSUE THREAD

**Issue by praneetharra** [open-learning-exchange/open-learning-exchange.github.io#685]
![issue](https://cloud.githubusercontent.com/assets/4139870/25068075/fa46c7e4-220c-11e7-80d2-8ca2f3dc3d53.JPG)

The link mentioned in the second block _https://USERNAME.github.io_ isn't active right after completing the task in first block. The link is active only after cloning the repo to the local storage. It is a bit confusing for the new interns who try to access the __url__ and find a __404__ instead. It would be better if the necessary changes are made to avoid confusion.

**Comment by praneetharra** [comment]
I know cloning has been explained in _Step 5_ of the _First Steps_, but it would be better if you can update _Step 3_ to avoid confusion for new interns.

**Comment by mappuji** [comment]
Hi @praneetharra thank you for your issue.

I don't agree with this statement
> The link is active only after cloning the repo to the local storage.

The link or Github page is nothing to do with cloning to the local storage. Basically, Github needs a couple of seconds sometimes a couple of minutes to finish upping your Github page. Basically, you have forked the repository and change the name of your forked repository.

Please take a look to (this)[https://pages.github.com/] page if you confuse.

**Comment by praneetharra** [comment]
@mappuji if you see the link you mentioned, the process for setting up the pages completes at step 5 and before you can access the page, the step 2 is where you clone your repository. Before cloning the repo, I couldn't access my page(praneetharra.github.io) for more than a day, so even I followed the steps in the link you mentioned and eventually could access the page. Were you able to access without cloning?

**Comment by mappuji** [comment]
@praneetharra yes I did, I were make my page up without cloning the page. I just need to **fork** and change the name of the repository. Remember, fork is different with clone.

**Comment by praneetharra** [comment]
@mappuji Yea, I understand they are both different, I wasn't able to access page for a day, so I read through that same link and followed along. After doing that I could access it, so I thought that is the process.

**Comment by mappuji** [comment]
@praneetharra I think it is because Github server does not immediately refresh your changes, not because of cloning.

CMIIW 😄

**Comment by praneetharra** [comment]
@mappuji may be true, I'll read it further and let you know 😄
