### ISSUE TITLE
Unaligned indentation in FAQ

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#689]
![screen shot 2017-04-17 at 1 29 48 pm](https://cloud.githubusercontent.com/assets/13564371/25099585/8d67beb4-2372-11e7-8328-6b0361371fbd.png)

The sections **Virtual Box**  and **Vagrant** do not align with the rest.

**Comment by duongdo27** [comment]
The solution is adding blank lines between each list and each section header. 
Here is [the commit](https://github.com/duongdo27/open-learning-duongdo.github.io/commit/376ab4be2fa328caf2c0e07f7ac949e8592aa5ff) on my personal fork of OLE.

**Comment by waryhermit** [comment]
@duongdo27 Feel free to make a pull request

**Comment by duongdo27** [comment]
@waryhermit  Here is the [pull request](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/696). Thank you.
