### ISSUE TITLE
Couchapp page doesn't exist in htmlresources.md

### ISSUE THREAD

**Issue by Loshma93** [open-learning-exchange/open-learning-exchange.github.io#690]
![image](https://cloud.githubusercontent.com/assets/24893117/25108928/265016ba-238e-11e7-9e38-47674208c12a.png)

When I click on Couchapp it doesn't show anything.

When I tried to open it in new tab, it say's page doesn't exist.

![image](https://cloud.githubusercontent.com/assets/24893117/25108950/51b59e10-238e-11e7-8a28-00079b4a4a14.png)

**Comment by praneetharra** [comment]
@Loshma93 I don't think its a new page that is supposed to be brought up, instead that link should redirect to the installation instructions mentioned few lines down in the same page.

**Comment by waryhermit** [comment]
@praneetharra I agree, but since its right below that it almost seems pointless. I would either change the link to `http://open-learning-exchange.github.io/#!./pages/htmlresources.md#Couchapp_Installation` or remove the link entirely.
