### ISSUE TITLE
Add another key for opening BIOS in FAQ answers

### ISSUE THREAD

**Issue by shahswet** [open-learning-exchange/open-learning-exchange.github.io#693]
![faq](https://cloud.githubusercontent.com/assets/17865137/25140714/74b82f1e-241e-11e7-986a-ee0987198f53.JPG)

I want to add **esc** key for enabling virtualization. In most of the laptops,including mine, **esc** key is used to access the BIOS. In the beginning I tried with *F2* and *delete* as stated in the FAQ and it didn't work so I wasted some time to figure out. So, I want to add the **esc** key to access the BIOS.

**Comment by waryhermit** [comment]
OK, sounds fine.

**Comment by dogi** [comment]
@shahswet ;) with me too
