### ISSUE TITLE
HTML and CSS for Tabs in navigation

### ISSUE THREAD

**Issue by praneetharra** [open-learning-exchange/open-learning-exchange.github.io#698]
![navigation_control](https://cloud.githubusercontent.com/assets/4139870/25166057/4a9a2e24-248e-11e7-8ae6-58577554e4fd.png)

@dogi @mappuji @waryhermit @Loshma93 Hi guys, I was trying to locate the __html__ highlighted in the image for modifying the navigation and its corresponding __css__ in our code base. Can someone direct me where to access it.

**Comment by mappuji** [comment]
@praneetharra have you check the ``index.html`` ?

**Comment by waryhermit** [comment]
@praneetharra Pretty sure that CSS is part of the MDwiki theme we use. Why do you want to open it?

**Comment by praneetharra** [comment]
@waryhermit I was trying to address the issue https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/672
