### ISSUE TITLE
Adding Crowdin in the list of Software used in THE BIG PICTURE

### ISSUE THREAD

**Issue by shahswet** [open-learning-exchange/open-learning-exchange.github.io#700]
![crowdin](https://cloud.githubusercontent.com/assets/17865137/25194287/39d9a18c-24f7-11e7-87c1-4340702d95e8.JPG)

I think we should add **Crowdin** in above list as we use this software frequently during the internship. And by looking the above list new interns/volunteers can have some knowledge and idea about all the software and languages that is used by OLE before starting the steps through 0 to 8.

**Comment by dogi** [comment]
@shahswet do I get you right like github gitter that we should name all the services we use?
services
- gitter
- travis
- saucelabs
- crowdin
- quantifiedcode
- hangout
- @dogi's linux cloud services on freedom server ;P
- ...

maybe ;)

but I just realized that some languages are also missing
- codeceptJS
- python
- ...

**Comment by shahswet** [comment]
@dogi I didn't know that interns will be using so many software. I just wanted to add the software that is used widely during the internship so that the interns will have some idea before starting their first step but Never Mind :) :)

**Comment by mappuji** [comment]
@shahswet don't be discourage by @dogi 's comment.

He was meant to put only necessary list. Basically, Crowdin is only a platform which enables us to do translation easily.

**Comment by shahswet** [comment]
@dogi @waryhermit you can close this issue.

**Comment by waryhermit** [comment]
@shahswet Okay
