### ISSUE TITLE
Solution for issue #622

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#701]
I figure out the solution for problem #622.
 
@waryhermit My suggested fix for the issue is change **.css("width")** to **.width()**.
According to jQuery documentation 

> The .width() method is recommended when an element's width needs to be used in a mathematical calculation.

Please checkout the fix on [my version of OLE](https://duongdo27.github.io/open-learning-duongdo.github.io/#!pages/firststeps.md)

@waryhermit Here is [my commit](https://github.com/duongdo27/open-learning-duongdo.github.io/commit/e1ee9be86eba66634793b4f48c80d38c691b239f)

**Comment by Loshma93** [comment]
@duongdo27 It looks great. Now it's not disturbing main content.

**Comment by waryhermit** [comment]
@duongdo27 We make solutions with Pull Requests, not issues. We already have an issue for this problem. I have assigned @paulbert to look at your solution. While you are waiting you can create a pull request, work on other issues, etc. Thanks for your patience.
