### ISSUE TITLE
Vagrant in First Steps

### ISSUE THREAD

**Issue by praneetharra** [open-learning-exchange/open-learning-exchange.github.io#702]
In the First Steps dropdown, we have 2 different links for Vagrant installation. I feel this is damaging the proper structure. Is it because of any specific reason? Can we merge the installation for windows in the same [vagrant.md](http://open-learning-exchange.github.io/#!pages/vagrant.md) like shown in the second image.

![vagrant 1](https://cloud.githubusercontent.com/assets/4139870/25199789/de90a9ec-2500-11e7-94c9-56c84dadb8cd.png)

### Suggested changes:
* Remove [vagrantwin.md](http://open-learning-exchange.github.io/#!pages/vagrantwin.md) and merge it with  [vagrant.md](http://open-learning-exchange.github.io/#!pages/vagrant.md) like shown in the image.

![vagrant 2](https://cloud.githubusercontent.com/assets/4139870/25199794/e3e557da-2500-11e7-83bb-5f8f2d921e54.png)

@dogi @waryhermit @Loshma93 @mappuji Please let me know your thoughts.

**Comment by waryhermit** [comment]
@praneetharra I believe you are saying the same thing as in this issue? https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/467#issuecomment-290833341

**Comment by praneetharra** [comment]
@waryhermit Yes, I see that you had the similar suggestion in the end. What's the reason for not executing it already?

**Comment by waryhermit** [comment]
@praneetharra We reserve all these issues for aspiring interns 99% of the time - you realize you can work on issues others have created as long as they have not started working on it already themselves right?

I could have this issue queue empty in no time, but then we wouldn't have anything safe to evaluate potential interns with.

**Comment by waryhermit** [comment]
Fixed by #768
