### ISSUE TITLE
Counting Tasks Link in Step 9

### ISSUE THREAD

**Issue by praneetharra** [open-learning-exchange/open-learning-exchange.github.io#706]
![task count](https://cloud.githubusercontent.com/assets/4139870/25216898/90137ebc-2559-11e7-9bae-071df03f476c.png)

When I first tried to count my total number of __PRs__ or __issues__ using [this link](https://github.com/open-learning-exchange/open-learning-exchange.github.io/commits/master) mentioned in the above image, it took a while for me to figure out how to filter things. It's be better if we update the link to a new _count.md_ file that has pictures and description on how to count someone's status. It will be easier for the prospective interns to understand how to keep track of their work.

### Filter issues by _"Author"_:

![task count](https://cloud.githubusercontent.com/assets/4139870/25217022/23a449fe-255a-11e7-9c39-ad883a779751.png)

### Filter Pull Requests by _"Author"_:

![task count](https://cloud.githubusercontent.com/assets/4139870/25217088/683a2804-255a-11e7-8d7b-80092daa706d.png)

**Comment by mappuji** [comment]
Interesting suggestion. Basically, we are working on a page to count PRs and issues created automagically. Btw, you give us a good suggestion.

Wonder how you think @dogi ?

**Comment by Loshma93** [comment]
@praneetharra I like your suggestion. It would be easy for interns to count how many they have created. Let's wait for other's suggestion.

**Comment by Supriyaranjan** [comment]
@praneetharra  Very good suggestion. It will be easier for interns to follow the screenshots and also it is 
easier to implement.

**Comment by kylemathias** [comment]
Anything that helps with clarity is a good change IMO. I say make changes and make a PR to let us preview it.

**Comment by snazzybunny** [comment]
I don't think it would be that hard for an intern to count. I think there are more important issues to address.

**Comment by mappuji** [comment]
Agree with @snazzybunny point 😄 
Basically, we can easily count via Issue/Pull Request tab on GitHub.

**Comment by kylemathias** [comment]
Im going to close this out. been 17 days with no changes.
