### ISSUE TITLE
Missing how to install homebrew cask

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#716]
In the section of installing Vagrant for Mac OS(X), it assumes people have `homebrew` installed. However, they may not know how to get the `homebrew cask`.     

![screen shot 2017-04-21 at 11 09 27 pm](https://cloud.githubusercontent.com/assets/13564371/25301251/a9759162-26e7-11e7-9b66-4dbcb152e39b.png)

**Comment by duongdo27** [comment]
**Solution**: Add this line 

`brew tap  caskroom/cask`

**Comment by mappuji** [comment]
hi @duongdo27 , you give a good suggestion.
Go on and raise your PR for this and don't forget to refer to this issue.

Anyone here working with mac? please confirm his proposed step.

**Comment by dogi** [comment]
@Loshma93 why did you close this?

If it was based on a PR it would be awesome to know which one ...
can you please add the link?

PS: automatic closing with (fixes #<issue number>) is preferred

**Comment by waryhermit** [comment]
@dogi https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/721/files

**Comment by dogi** [comment]
thanks @waryhermit
