### ISSUE TITLE
Duplicate sentences on the HTML Resources page

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#723]
In the HTML resources page, the sentence *"Visit following link to learn more about it."* is duplicated.

![screen shot 2017-04-25 at 11 03 47 pm](https://cloud.githubusercontent.com/assets/13564371/25417739/cdd0ac5a-2a0b-11e7-85a0-f9a545a6ebb5.png)

**Comment by duongdo27** [comment]
Solution: Remove the duplicated sentence.

**Comment by Supriyaranjan** [comment]
@duongdo27  I will work on it.

**Comment by Loshma93** [comment]
@Supriyaranjan I think this issue is resolved. Can I close this Issue??

**Comment by Supriyaranjan** [comment]
@Loshma93  yes
