### ISSUE TITLE
Some improvements for the Crowdin Integration page.

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#724]
1. The two main objectives should be separated in two lines and in bigger font for clarity.

![screen shot 2017-04-25 at 11 16 24 pm](https://cloud.githubusercontent.com/assets/13564371/25417936/87c21f58-2a0d-11e7-9b43-1a0acb64a7f7.png)
---
2. The section number should be `2.1` here.
![screen shot 2017-04-25 at 11 15 26 pm](https://cloud.githubusercontent.com/assets/13564371/25417924/6f0ecc7c-2a0d-11e7-8ea5-444a6e6e0932.png)
---
3. The section number should be `2.2` here.
![screen shot 2017-04-25 at 11 15 37 pm](https://cloud.githubusercontent.com/assets/13564371/25417927/75b52b3e-2a0d-11e7-8af4-132d23ea1053.png)

**Comment by dogi** [comment]
@duongdo27 hmm - try a PR and post it with the rawgit link ... ;)

**Comment by waryhermit** [comment]
Fixed by https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/747
