### ISSUE TITLE
Raw Git Sample Picture and Link

### ISSUE THREAD

**Issue by Ebuka-Chibueze** [open-learning-exchange/open-learning-exchange.github.io#725]
Refer to [Step8](http://open-learning-exchange.github.io/#!pages/githubissues.md ). I think It would help to show a picture of a typical raw git page in addition to the template shown there.  Also, it could help to add the [RawGit](https://rawgit.com/) website to the [Useful Links](http://open-learning-exchange.github.io/#!././pages/githubissues.md#Useful_Links).

**Comment by mappuji** [comment]
I agree with you @Ebuka-Chibueze, but the solutions must be simple.

it is also useful if we change `https://rawgit.com/YourUserName/YourUserName.github.io/YourBranchName/#!index.md` to `https://rawgit.com/{YouGitHubUsername}/{YouGitHubUsername}.github.io/{YouGitHubUsername}/#!index.md` and give a simple example there with a simple sample..

**Comment by paulbert** [comment]
I like this, too, but would like to clarify that the last part is branch name not user name:
`https://rawgit.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md`

**Comment by kylemathias** [comment]
@Ebuka-Chibueze are you still working on this? If not i will close this out by the end of the week.

**Comment by Ebuka-Chibueze** [comment]
@kylemathias I plan to finish it soon.

**Comment by dogi** [comment]
@Ebuka-Chibueze awesome
