### ISSUE TITLE
Missed header in vagrantwin.md

### ISSUE THREAD

**Issue by jmgamer12** [open-learning-exchange/open-learning-exchange.github.io#729]
At the very end of the document, there is a final line which says "#### Return to First Steps." The hashtags appear in text and the header is not the correct size. Check the attached image for a visual descriptor of the issue. I do not know if this intentional but it does appear to be an error.
![header issue](https://cloud.githubusercontent.com/assets/6437686/25496011/09618444-2b45-11e7-96a9-06916848aebc.PNG)

**Comment by Supriyaranjan** [comment]
@jmgamer12  I could not find this issue on the page http://open-learning-exchange.github.io/#!pages/vagrantwin.md

![image](https://cloud.githubusercontent.com/assets/26332034/25497476/4cf25e9a-2b4a-11e7-9ef4-ea6457db4e93.png)

**Comment by dogi** [comment]
@Supriyaranjan think it already got merged ;)
