### ISSUE TITLE
simpleinstall.md Title formatting

### ISSUE THREAD

**Issue by jmgamer12** [open-learning-exchange/open-learning-exchange.github.io#732]
Within this page, it seems all titles and subtitles are left in a format of  "[several hashtags] title/subtitle" which I believe can be cleaned up by using the hashtags to make the titles & subtitles formatted to the correct header size. This look will make the page cleaner overall and more aesthetically pleasing.

**Comment by mappuji** [comment]
I have merged your PR of these fixes. :+1:
