### ISSUE TITLE
typos in Yurockkk.md

### ISSUE THREAD

**Issue by Yurockkk** [open-learning-exchange/open-learning-exchange.github.io#737]
**[problem]** there are two typos in Yurockkk.md as shown in the picture:

![screen shot 2017-04-28 at 8 42 31 pm](https://cloud.githubusercontent.com/assets/11954766/25551519/f787fe3c-2c53-11e7-89ba-4555b7500f16.png)

**[solution]** modify "enjoys" to "enjoy", "excercise" to "exercise"

**Comment by mappuji** [comment]
I have merged your PR @Yurockkk
