### ISSUE TITLE
Inconsistent formatting of "NOTE" alert

### ISSUE THREAD

**Issue by Yurockkk** [open-learning-exchange/open-learning-exchange.github.io#740]
To improve the readability of the Virtual Interns tutorial, There should be a standard formatting for "NOTE" alert. Right now there are five different formattings:

1. Start without "Note:"
  in nation.md
![screen shot 2017-04-29 at 6 47 07 pm](https://cloud.githubusercontent.com/assets/11954766/25559598/538294d2-2d0c-11e7-88ff-1e081656c8f9.png)

2. Start with "NOTE:" (bold, all capes)
  in githubissues.md
![screen shot 2017-04-29 at 6 43 16 pm](https://cloud.githubusercontent.com/assets/11954766/25559580/cdcbd736-2d0b-11e7-9b3f-046fe3dacc65.png)

3. Start with "Note:" (bold)
  in firststeps.md
![screen shot 2017-04-29 at 6 45 13 pm](https://cloud.githubusercontent.com/assets/11954766/25559590/12fd2d82-2d0c-11e7-9715-505da5852644.png)

4. Start with “Note:” (bold) and start a new line for the content
  in githubandmarkdown.md
![screen shot 2017-04-29 at 6 49 01 pm](https://cloud.githubusercontent.com/assets/11954766/25559615/afac85b0-2d0c-11e7-9943-2958bff05c0c.png)

5. Start with "Important Note:" (bold)
  in githubandmarkdown.md
![screen shot 2017-04-29 at 6 55 37 pm](https://cloud.githubusercontent.com/assets/11954766/25559670/81064632-2d0d-11e7-873d-fbe73d1156b3.png)

**Comment by Yurockkk** [comment]
Solution: we can set a standard formatting for “NOTE:” alert, change other formatting to the standard one. I'll prefer the second one: start with "NOTE" (bold, all caps)

**Comment by mappuji** [comment]
Hi @Yurockkk, I agree with your idea and solution. I think you can create a solution and raise PR for this. Good luck :smile:

**Comment by Yurockkk** [comment]
@mappuji  Done! #742

**Comment by mappuji** [comment]
Closed with #742
