### ISSUE TITLE
improvement for githubissues.md

### ISSUE THREAD

**Issue by Yurockkk** [open-learning-exchange/open-learning-exchange.github.io#743]
In [GitHub issues page](http://open-learning-exchange.github.io/#!./pages/githubissues.md), In order to allow prospective interns to better understand the important of keeping their repository clean, maybe we can add some words about they might want to delete the branch after each pull request has been approved and merged by OLE staff or their repository will getting bigger and become a mess of defunct branches

**Comment by Supriyaranjan** [comment]
Sounds good. Go ahead and create a pull request for this issue

**Comment by Yurockkk** [comment]
@Supriyaranjan After doing some googling ([here](https://help.github.com/articles/deleting-and-restoring-branches-in-a-pull-request/)), it seems to me that one of the easiest way to delete the defunct branch in remote repository (your username.github.io) is using GitHub interface as shown in the figure.

<img width="545" alt="screen shot 2017-05-01 at 10 10 02 pm" src="https://cloud.githubusercontent.com/assets/11954766/25601571/285f0b72-2ebb-11e7-9bcb-8de99d1b1892.png">

 For the local repository, use the command `git branch -d yourLocalBranchName` to delete the defunct branch. Any suggestions are welcome :smiley: . In the meantime, I’ll start to draft a short paragraph along with the same image shown above and make a pull request.

**Comment by mappuji** [comment]
solved by #748
