### ISSUE TITLE
Improve Markdown Wiki Page -provide links to GitHub accounts of Dogi, Emily on Markdown wiki page

### ISSUE THREAD

**Issue by chinmayakelkar** [open-learning-exchange/open-learning-exchange.github.io#75]
Assignments 3 and 4 ask to follow Dogi, Emily and Open Learning Exchange on GitHub. We could provide direct links to their GitHub accounts. Secondly, you can't follow an organization on GitHub. So that instruction needs to be changed.

**Comment by jkesh93** [comment]
Thank you for pointing this out -- I was not able to follow ole and thought I was doing something wrong...

**Comment by EmilyLarkin** [comment]
@chinmayakelkar @jkesh93 @fsjoyti thanks for catching this and working on it. My oops:)
