### ISSUE TITLE
Embedded image in Chat.md

### ISSUE THREAD

**Issue by jmgamer12** [open-learning-exchange/open-learning-exchange.github.io#751]
In chat.md there is supposed to be an embedded image linking to Gitter but instead, a viewer sees the code for this as shown below in the screenshot.
![chat-md](https://cloud.githubusercontent.com/assets/6437686/25641363/54283668-2f59-11e7-9336-3232829bb3f9.PNG)

**Comment by Yurockkk** [comment]
@jmgamer12 I've checked on chrome, safari and firefox and they all look just fine as shown below, just curious what browser are you using?

![screen shot 2017-05-02 at 6 28 47 pm](https://cloud.githubusercontent.com/assets/11954766/25642045/54e8a068-2f65-11e7-906f-ecfcf1874974.png)

**Comment by jmgamer12** [comment]
Chrome

**Comment by kylemathias** [comment]
@jmgamer12 depending on how you view the source code, it will often be different then the live version.

With rawgit, the page looks like this:
![image](https://cloud.githubusercontent.com/assets/26488295/25644149/b749ec7e-2f58-11e7-9d5d-257db710612b.png)
that is the most accurate way to try and view changes you make to a file in a branch before it gets merged to the master.

But if you view the code Preview in the GitHub repository, it looks all funky like what you have:
![image](https://cloud.githubusercontent.com/assets/26488295/25644228/3eebebb4-2f59-11e7-8839-9a4a549ae0e3.png)


I know the steps of using rawgit was somewhat not clear in the first steps. I dont know if it got fixed already, but if you want, you could make a new issue about how it is unclear and then add clarity to the first steps on how to use rawgit.

**Comment by jmgamer12** [comment]
Oooh ok got it.
