### ISSUE TITLE
Inconsistent page layout

### ISSUE THREAD

**Issue by Yurockkk** [open-learning-exchange/open-learning-exchange.github.io#752]
I notice that all of the pages in virtual interns tutorial have table of contents on the left except [Step6](http://open-learning-exchange.github.io/#!./pages/githubissues.md) and [Step7](http://open-learning-exchange.github.io/#!./pages/nation.md). Maybe we can come up with one or two headers along with the “Useful Links” to make table of contents for those two pages. It can not only increase our consistency but also improve the user experience when user view our web page on mobile device as shown below (hyperlink table of contents and “go back to top” button) 

![tableofcontentshyperlink](https://cloud.githubusercontent.com/assets/11954766/25647245/513cca10-2f8e-11e7-9cea-7831d13ef437.png)

Also, if you click the “go back to top” button in the page without table of contents like [Step6](http://open-learning-exchange.github.io/#!./pages/githubissues.md) and [Step7](http://open-learning-exchange.github.io/#!./pages/nation.md), it won’t jump to the top of the page.

Another minor inconsistence is in githubandmarkdown.md, The header should be “Useful Links” instead of “Useful links”.

**Comment by mappuji** [comment]
Agree, go on with a PR good luck! :smile:

**Comment by Yurockkk** [comment]
@mappuji Done! please take a look at #755 :grinning:
