### ISSUE TITLE
Improvements in clarity in FAQ Section/"Synopsis"

### ISSUE THREAD

**Issue by aurinsomnia** [open-learning-exchange/open-learning-exchange.github.io#761]
Something I've noticed while going through the 'First Steps' process of internship acceptance is that at times I'm sort of absentmindedly following instructions, and not really understanding the importance of each piece of software, and how they intertwine. Currently the technical section of the FAQ primarily deals with specific issues, such as "How do I enable virtualization in order to turn Vagrant on?", while this is certainly helpful for a user troubleshooting, I think a summary would help a great deal in giving prospective interns clarity in why they are doing what they are. In principle, I understand that we are supposed to learn the "ins-and-outs" of each piece of software by reading up, and following the steps, but I think that having an "In Brief" section where we cover at a surface level what all of these programs are and how and why we are using them would be helpful to get a general sense of the scope and layout of the project. I know this would have been a help for me, as I initially struggled to understand what each piece of software was used for, and how we'll use them later on. If this is too broad for an FAQ section, I understand, but I think it truly would be helpful for initial clarity.

Update:
see #767

**Comment by snazzybunny** [comment]
I agree. I think there should be a troubleshooting section as well and perhaps something to let the user know if the latest build of the program matches with the most recent guide. The UI and some of the instructions might be different now than when it was first created.
