### ISSUE TITLE
Step 6 seems like a guide than a step by step tutorial

### ISSUE THREAD

**Issue by snazzybunny** [open-learning-exchange/open-learning-exchange.github.io#763]
Hello. I read the steps and thought step 6 just showed you how to use Github and what to expect on the other side once you've submitted something. The previous guides told you what to do along with the screenshots. I thought the bold such as "Create an Issue" were just headings and not instructions. Perhaps it is a good idea to keep the tutorials consistent? I found out that we had to create an issue only by reading Step 9, which suggested to check whether or not I've fulfilled all of the requirements for each step.

**Comment by aurinsomnia** [comment]
In a similar sense, perhaps an "Objective" tab or something similar could help for each step. Right now, only Step 5 (Keeping Fork Updated) has a clear Objective. All other steps start out with an introduction that aim to cover the material the steps pertain to, but these intros often lack clarity. It can be confusing at times to understand exactly what is required, and adding a clear objective to each section would help that.

**Comment by snazzybunny** [comment]
I think there is too much text in general. Might just be me. Maybe we could follow Archlinux's style of writing a manual?

**Comment by mappuji** [comment]
Hi @aurinsomnia and @snazzybunny thank you for your input. I really appreciate it. Basically, Open Learning Exchange is an open source movement at heart and open to everyone input as long as it is constructive.

@aurinsomnia has already suggested "Objective" as a must-have section on the steps and I think it is a good move. For @snazzybunny could you explain more about Archlinux's style of writing a manual?

**Comment by snazzybunny** [comment]
Basically it is very short and to the point. Gives the necessary commands without much additional information. Perhaps we could make a quick guide or a longer guide because not interns have the same level of experience. Another useful case for this style is if we want to make a quick reference manual. 

The link can be found here: [https://wiki.archlinux.org/index.php/installation_guide](url)

**Comment by kylemathias** [comment]
@snazzybunny @mappuji @aurinsomnia Is this still being worked on? i am going to close this by the end of the week if i don't hear back. You can make the changes and put in a pull request. Just make sure you reference this issue.

**Comment by aurinsomnia** [comment]
@kylemathias I haven't touched it in a while. I still think it is a good idea to include an objective section, however many of the pages are lacking them still. It might take a bit, but I could definitely get it done, and I do think it would be a positive change. Currently the pages missing objective sections on the "First Steps" are vagrant.md, bellapps.md, nation.md and githubissues.md. I don't think vagrant.md needs to be changed, as it is essentially a reference document, but I think the others could use some sprucing up. Thoughts?

**Comment by kylemathias** [comment]
@aurinsomnia sounds good. Go ahead and make the changes and reference this issue.

**Comment by snazzybunny** [comment]
@aurinsomnia Do you think vagrant.md, bellapps.md and githubissues.md shoud have an objective section?

**Comment by aurinsomnia** [comment]
@snazzybunny as I mentioned prior, I think it makes it easier to digest, and helps with clarity. I'll work on them tonight and then throw up some PR's for you guys to take a look at and give some feedback.

**Comment by snazzybunny** [comment]
#834 and #833 are merged. Closing this issue.
