### ISSUE TITLE
Inconsistency in First Steps Pages

### ISSUE THREAD

**Issue by aurinsomnia** [open-learning-exchange/open-learning-exchange.github.io#764]
As I commented on Issue #763, there is currently an inconsistency in formatting between the steps. Only Step 5 covering Forked Repositories had a clear Objective tab as pictured. 
<img width="1440" alt="screen shot 2017-05-07 at 8 54 22 pm" src="https://cloud.githubusercontent.com/assets/25090351/25786696/606a79c4-3367-11e7-9636-77eb648d188e.png">
The rest all began with "Introduction" sections, some with different types of formatting per page as pictured below.
<img width="1440" alt="screen shot 2017-05-07 at 8 54 53 pm" src="https://cloud.githubusercontent.com/assets/25090351/25786721/a94ffd30-3367-11e7-8243-dec43f1f828f.png">
 I believe unifying the formatting to have Objective tabs on each individual would greatly increase clarity on what each step requires to pass. This isn't to say that we should eliminate the Introduction pages necessarily, but if we revise them so that the prospective intern has his tasks clearly laid out in an objective tab at the beginning of each step, it would benefit the overall formatting of the site and simultaneously improve its readability.

**Comment by snazzybunny** [comment]
It's nice but may introduce clutter. Maybe a video can make sense of how everything should work or a diagram. Also, I think step 4 and 7 can go together.

**Comment by aurinsomnia** [comment]
@snazzybunny I don't think it's too much clutter. I don't add any content really, only take the main points/tasks of each page, and place them at the top so that the intern has an idea of what must be accomplished in that particular step. As for a video, I'm unsure how much that will help. I also think step 4 and 7 are intentionally separated, because they are supposed to be learned/accomplished in that order.

**Comment by aurinsomnia** [comment]
@kylemathias With regards to the gitandrepositories.md page, it is the only page with a "Prerequisites" header, and the prerequisite listed is merely to have completed all previous steps. As such, with the continued goal of unifying formatting, I'd say that we could easily remove the prerequisites section with no loss in clarity or content. The section of the page following the "Objective" and "Prerequisites" tabs could easily serve as an introduction section as well. It follows the general style of each other page in that it gives a broad overview of the topic, before diving deeper into the nitty-gritty in later sections.
