### ISSUE TITLE
Error when running the command vagrant up

### ISSUE THREAD

**Issue by snazzybunny** [open-learning-exchange/open-learning-exchange.github.io#765]
Had problems running vagrant. Running vagrant up resulted in the error, "vi: Box 'ole/jessie64' could not be found. Attempting to find and install...". The latest version of vagrant may have bundled an old version of curl which is breaking the application. To fix this, perform the command /opt/vagrant/embedded/bin/curl. After this, the vagrant executed as expected.

For more information: http://stackoverflow.com/questions/23874260/error-when-trying-vagrant-up

**Comment by snazzybunny** [comment]
Pull request found here #766

**Comment by waryhermit** [comment]
Fixed by #766
