### ISSUE TITLE
Everything about Vagrant and how to install it should be in its own file.

### ISSUE THREAD

**Issue by snazzybunny** [open-learning-exchange/open-learning-exchange.github.io#769]
Many installation guides show how to install a program on many different operating systems and are usually found in the same manual or webpage. Having two different vagrant references is like having two different manuals and adds more clutter. The tutorial should merge windows and osx/unix versions so they can find everything in one place. It is very confusing otherwise.

**Comment by snazzybunny** [comment]
#768

**Comment by snazzybunny** [comment]
If we look at #764, in the second screenshot, the page displays both MacOS/Ubuntu and Windows on the same page. I think it should be consistent throughout the page.

**Comment by mappuji** [comment]
Solved #768
