### ISSUE TITLE
MDWiki improvements

### ISSUE THREAD

**Issue by AdityaNair99** [open-learning-exchange/open-learning-exchange.github.io#77]
Some of the markdown code on the wiki is hard to visualize. Is there a way to insert a preview tab?

**Comment by sente** [comment]
Perhaps it would be easiest to write the markdown in one of these: https://www.google.com/search?q=markdown+editor+online ?

**Comment by dogi** [comment]
if you work only in github you can easily switch between edit and preview,
if not you can still always your stuff on your personal github.io page
@AdityaNair99 in your just look onto https://adityanair99.github.io
