### ISSUE TITLE
Syntax for githubandmarkdown.md's and githubissues.md headers are incorrect

### ISSUE THREAD

**Issue by snazzybunny** [open-learning-exchange/open-learning-exchange.github.io#773]
Simiary to #770, the headers are incorrect. The headers look like this"#inserttexthere" instead of "# inserttexthere". It needs to have a space inbetween. The page does not display correctly when loaded in Github otherwise.

**Comment by aurinsomnia** [comment]
Given the issue has been resolved, shouldn't this thread be removed?

**Comment by mappuji** [comment]
Thank you for reminding me @aurinsomnia . Issue is solve by #774
