### ISSUE TITLE
Add documentation for take-home

### ISSUE THREAD

**Issue by zeivhann** [open-learning-exchange/open-learning-exchange.github.io#776]
We have a lot of groundwork to cover for the take-home (Android build) part of the OLE project.

We need to make at least one page that goes into the nitty-gritty of the application, for example:
- The backend workflow
- How the app updates automatically and receives resources
- Interactivity with the RPi server
- Plans for the future of the mobile project (Bluetooth capabilities, building on an alternative platform, etc.)

I think it of utmost importance to document these things well so that it will be easier to pull users into the project, and so that way we (hopefully) wouldn't have to explain every little detail and help newcomers to better understand the overall workflow of the project.

**Comment by leonardmensah** [comment]
👍
