### ISSUE TITLE
Replace deprecated bootstrap script for setuptools 

### ISSUE THREAD

**Issue by duongdo27** [open-learning-exchange/open-learning-exchange.github.io#778]
In the [HTML Resources page](http://open-learning-exchange.github.io/#!./pages/htmlresources.md#Couchapp_Installation) , the bootstrap script to install `setuptools` is **deprecated**. Therefore, we should use a more reliable method.   

![screen shot 2017-05-08 at 10 16 58 pm](https://cloud.githubusercontent.com/assets/13564371/25834390/409301b2-343d-11e7-81bf-4aed89ec4836.png)

**Comment by duongdo27** [comment]
**Solution:** According to the DEFAULT_DEPRECATION_MESSAGE in the bootstrap script, we should install `setuptools` with `pip`.
> pip install setuptools

**Comment by mappuji** [comment]
Hi @duongdo27 

You remind me of the first time when I run the instructions. You can go on with a pull request and suggest in the document that `pip install setuptools` is an alternative for installing the setuptools.

**Comment by snazzybunny** [comment]
I did some changes which can be found at #783 regarding this issue.

**Comment by mappuji** [comment]
Solved by #783
