### ISSUE TITLE
Lack of clarity with counting contributions using link in Step 9

### ISSUE THREAD

**Issue by aurinsomnia** [open-learning-exchange/open-learning-exchange.github.io#779]
In Step 9 of the First Steps page, the step lists the different items a prospective intern must have completed before taking the survey. These items are pull requests, comments, and issues, and the last bullet point in the list is a simple piece of text saying "You can count them here." "Here" is a link to the list of commits to the master branch of the ole github.io. In my eyes, this isn't a very good tool to use, as it will only list certain completed items. It will show the commits that have been made, but gives no way to count the number of issues, or contributions to issues through comments. Because it only relates to pull requests, the link isn't extremely useful and is borderline misleading. 

I believe it should either be placed right after the pull requests description, or removed entirely, as it gives no valuable information on either the comments or issues, which are a major part of completing the Step.

**Comment by snazzybunny** [comment]
I agree. Interns should be able to count themselves anyway.

**Comment by kylemathias** [comment]
@aurinsomnia I agree. I would just remove that check box. I think interns with this step should learn how to find and count there pull request.
