### ISSUE TITLE
Clarification needed on tutorials

### ISSUE THREAD

**Issue by jkesh93** [open-learning-exchange/open-learning-exchange.github.io#78]
### One of the instructions is as clear as it should be and so I wanted to help point where this occurred. My experience with learning has shown me that individuals succeed when things are as clear as possible. This applies beyond learning, but we'll stick to that since this organization has learning in its name.

![image](https://cloud.githubusercontent.com/assets/3229717/15663629/e8e17a50-26ca-11e6-9dc3-15490cb9d356.png)

This should be "Commit New File" as for users they will be seeing this: 
![image](https://cloud.githubusercontent.com/assets/3229717/15663633/fda267ec-26ca-11e6-95b3-78295d605fc8.png)

when they scroll down. 

Learning anything new is a time when simplicity, clarity, and ease should be greatest to help achieve familiarity.

**Comment by jkesh93** [comment]
The best way to solve this is to update/recheck the steps a user will go through and make those changes -- what you listed is correct, change it to "Commit new file" as the button suggests and tell the user which of the radio buttons to click as well.

**Comment by fsjoyti** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/10965471/15770867/8b469ee0-291b-11e6-9cee-accdb33a47cb.PNG)

I think the instruction mean it to follow the open learning exchange repository  by clicking watch so that you get all the  updates in the open learning exchange repository :/
