### ISSUE TITLE
githubissues.md at step 6 does not have PR instructions or PR structure

### ISSUE THREAD

**Issue by snazzybunny** [open-learning-exchange/open-learning-exchange.github.io#786]
The link [here](http://open-learning-exchange.github.io/#!./pages/githubissues.md) does not have instructions on submitting PR. Also, it would be a good idea for interns to know what to include in the PR.

**Comment by snazzybunny** [comment]
#787

**Comment by aurinsomnia** [comment]
I think this issue should be removed, because snazzybunny resolved it in merge #787.
