### ISSUE TITLE
Add Check list for PR aproval

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/open-learning-exchange.github.io#797]
I really like the format @mappuji is using to aprove pull request:

> Thank you for your PR @snazzybunny 
>
> Things I've reviewed:
>
> - [x] Check for issue number in pull request title
> - [x] Are there any unneeded files in the pull request?
> - [x] Did they make a branch for their patch?
> - [x] Does the pull request actually fix the issue?
> - [x] Check the pull request on rawgit, does it display without any errors?
> - [x] Is there any merge conflicts?
> - [x] Check the committer name?
> 
> Notes:
> * For the future PR please add the issue number to the title
> * Please add rawgit for this kind of changes.

Some newer interns are already using this format, and i think we could all benefit from using it as a standard. I think it should be added some place in the first steps. Thoughts?

**Comment by sarah-lu102** [comment]
I think that's a good idea as well!

**Comment by Yurockkk** [comment]
Agree!! I think it's very helpful for reviewer so I post the checklist in every PR I merge with only slightly difference in formatting. I just copy and past the "Reviewing pull requests and issues" section in internorientation.md. it looks like this:

[x] Check for issue number in pull request title
[x] Are there any unneeded files in the pull request?
[x] Did they make a branch for their patch?
[x] Does the pull request actually fix the issue?
[x] Check the pull request on rawgit, does it display without any errors?
[x] Is there any merge conflicts?
[x] Make sure that people use their GitHub accounts when making commits through git

**Comment by snazzybunny** [comment]
I will add it to the PR tutorial.
