### ISSUE TITLE
Minor issues in takeHomeEmulatorSetup.md

### ISSUE THREAD

**Issue by Yurockkk** [open-learning-exchange/open-learning-exchange.github.io#803]
Here are some minor issues I found while following the step in takeHomeEmulatorSetup.md

1. the file directory is app -> java __-> pbell.offline.ole.org.pbell__ -> FullscreenActivity 

2. the command of finding IP address on Mac is `ifconfig` instead of `ipconfig`

3. Do we still need the Note below? Or it has been solved [here](https://github.com/open-learning-exchange/take-home/pull/55) ?

<img width="999" alt="screen shot 2017-05-22 at 5 27 13 pm" src="https://cloud.githubusercontent.com/assets/11954766/26301566/27d94636-3f14-11e7-9d3b-7847840d2729.png">

**Comment by kylemathias** [comment]
@Yurockkk for 1, 2 and 3 i think you are correct. You can add the extra step for ```ifconfig``` for mac. For the other step, you can also just remove it if you like.

**Comment by Yurockkk** [comment]
Solved by [#808](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/808)
