### ISSUE TITLE
Document zip upload of HTML resources

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/open-learning-exchange.github.io#816]
Now that we can add HTML resources as a zip file, we should include that in the HTML resources documentation.  We should keep the old way as well since that gives interns an opportunity to learn about CouchDB and Couchapps.

The steps for the new way are as follows:

- Delete all unnecessary files from the app (.git folder, node_modules, maybe bower. If you're not sure, leave it in, but more files means longer upload)
- Add resource like a normal resource, but select `HTML` under Open and put the file name of the main page (i.e. `index.html`) in Open Which File like below:
![bell app add](https://cloud.githubusercontent.com/assets/9203229/26499451/b20eee20-4200-11e7-87f9-afbc84502f95.png)
- Adding to your community will take some time (30 seconds - 5 minutes maybe).  Post to the gitter & check devtools if it's not working.
- Pushing to the nation will take even longer depending on your internet connection.

Try it out and let me know if you need more info for the page.

**Comment by sarah-lu102** [comment]
@paulbert where in the app are the files .git folder and node_modules? I can't find it in couchapp, or the apps that I've generated

**Comment by snazzybunny** [comment]
I may be wrong but I think he means that there may be unnecessary files included in some apps. Some apps might have git data etc. And depending on how the app is developed it might not be using node or package managers like bower, so there is nothing really to delete.

**Comment by paulbert** [comment]
@snazzybunny @sarah-lu102 Yes there are some situations where you'll end up with unnecessary files.  The most common is probably the .git folder which will be created if you clone a repository from GitHub or if it's a repository you created.

As I type this, I'm realizing that in Windows that folder will be hidden until you show hidden files 
https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files
You should add this link for windows users

The other examples (node_modules & bower) are from package managers and will often be excluded from a repository.  If they aren't, they can often include 1,000s files which would really slow the process up.  They are often unnecessary for the final app and are just for development, but occasionally these will be needed.

So I guess include a step in between adding to your community and pushing to nation:

- Test opening the app from your community.  If it isn't working and you can't figure out the cause, post to the Gitter chat and somebody can help

**Comment by Loshma93** [comment]
@paulbert Yes your'e correct. It's better to remove unnecessary files from the App. I encountered this problem while I am pushing App to nation. It took more than an Hour. It may be due to number of files in the App folder.
