### ISSUE TITLE
Incorrect no. of steps in FAQ

### ISSUE THREAD

**Issue by kanishk1010** [open-learning-exchange/open-learning-exchange.github.io#827]
The FAQ page in the Markdown Wiki mentions 10 initial steps in the answers to Q6 and Q7. However, as a new member, I could see there are only 9 steps involved in the 'FirstSteps.md' page.

![image](https://cloud.githubusercontent.com/assets/22456494/26746138/033ef234-47bc-11e7-8904-0d3dafddbc3f.png)

**Comment by kanishk1010** [comment]
'faq.md' can be updated with correct information

**Comment by Loshma93** [comment]
@kanishk1010 I think the steps starts from 0-9. If I am correct there are 10 steps in firststeps.md page

**Comment by kanishk1010** [comment]
You are right. I missed that. We can close this one. Thanks!
