### ISSUE TITLE
Incorrect <username>.md link in 'firststeps.md'

### ISSUE THREAD

**Issue by kanishk1010** [open-learning-exchange/open-learning-exchange.github.io#828]
The step 3 in the 'firststeps.md' instructs the interns to post the following link in the gitter chat:
\<username\>.github.io/#!pages/\<username\>.md
![image](https://cloud.githubusercontent.com/assets/22456494/26746713/475e2c8e-47bf-11e7-9985-8162e2e254dd.png)
However, this link seems to be defunct at that point of time.

The rawgit link mentioned in 'githubandmarkdown.md' seems to be the accurate one.

**Comment by kanishk1010** [comment]
The link in the step 3 in 'firststeps.md' can be replaced by the 'rawgit' link mentioned in 'githubandmarkdown.md'.

**Comment by aurinsomnia** [comment]
@kanishk1010 Good catch! 
The proper format should be <username>.github.io/#!pages/profiles/<username.md> it's correct when given as an example in the actual githubandmarkdown page, but in the first steps page it's given incorrectly. Why don't you make a new branch and change that to be correct, not just replace it with the rawgit link.

**Comment by kanishk1010** [comment]
@aurinsomnia Thanks for pointing me to the right direction. Pull request #831 created with the suggested changes.
