### ISSUE TITLE
Ask interns explicitly to create and fix at least one issue in step 6

### ISSUE THREAD

**Issue by kanishk1010** [open-learning-exchange/open-learning-exchange.github.io#838]
Step 6 in 'firststeps.md' should explicitly ask the interns to create and fix at least one issue get it reviewed before proceeding to the next step, so that the intern knows how to work on an issue before creating more. 

Also, it will prevent confusion, when starting with step 8 and suddenly finding out that they were expected to work on an issue already in step 6.

**Comment by kanishk1010** [comment]
An instruction can be added at the end of step 6 like "Before proceeding to the next step, make sure you have created and fixed at least one issue in this Markdown Wiki"

**Comment by aurinsomnia** [comment]
I don't think the step is unclear on the fact that you are creating an issue, resolving it in a branch, and merging it. Perhaps the introduction could use a concluding sentence that states explicitly you need to create and resolve an issue, but other than that I think the step is fine. That said I'll assign this to you, and you can make a pull request with changes you think might benefit the page, and we'll go from there.

**Comment by kanishk1010** [comment]
While I am working on this, there is one more thing which is not very clear. It says "If you know how to solve an issue, be sure to provide a detailed account of your research and show how to fix it". Where exactly should one provide these details? 
@Loshma93 Is this what you were referring to in the requested changes in #831 
@mappuji You mentioned that this is no longer required "since the necessary detail is already explained" in one of the tutorials. Should I remove this statement from step 6, as it unclear and probably obsolete?

**Comment by kanishk1010** [comment]
Step 6 updated as per initial suggestions. Please refer pull request #853.

**Comment by Loshma93** [comment]
@kanishk1010 In #831 I asked you to create an example like this Loshma93.github.io/#!pages/profiles/Loshma93.md. I hope you are clear about what I meant.

**Comment by kanishk1010** [comment]
@Loshma93 Thanks for clarifying!
