### ISSUE TITLE
Briefly introducing Crowdin and the 'Translation' tab in 'index.md' for any potential translator

### ISSUE THREAD

**Issue by kanishk1010** [open-learning-exchange/open-learning-exchange.github.io#840]
I am not really sure if we want it this way but just a thought - we can add a brief introduction to the 'Crowdin' platform and the 'Translation' tab in the 'index.md' page for any potential translator landing on/visiting the index page.

**Comment by aurinsomnia** [comment]
I personally don't think that that's necessary to be quite honest. Crowdin, while important, isn't the primary point of the project, and it's also introduced right away (in step 0). While the index isn't perfect, I don't think this is one of the changes I'd make. With that said, I'm only one voice, so if another admin thinks this is a relevant or important change, we can consider it.

**Comment by kanishk1010** [comment]
@aurinsomnia I understand that. Being new to the project, I do not have the complete picture of the priorities and objectives.

**Comment by dogi** [comment]
@kanishk1010 thanks - but due importance of other issues and the nearly 2 months of nobody taking this issue to a new level (comment and/or PRs)
I am closing it
