### ISSUE TITLE
The git commit message style should be mentioned in GitHub Issues

### ISSUE THREAD

**Issue by ChenjieZhou** [open-learning-exchange/open-learning-exchange.github.io#841]
[Create a Commit](http://open-learning-exchange.github.io/#!./pages/githubissues.md#Create_a_Commit) in Github Issues does not mention the style of commit.

It is important for everyone in a team to write a standard style of commit. This [commit style guide](http://udacity.github.io/git-styleguide/) was created by Udacity is a good reference, we could add this link to there.

**Comment by kylemathias** [comment]
I agree a "commit style" would greatly help clarity for everyone. I think everyone would agree that it is a good idea, but i think the biggest hurdle is getting people to use it.

The challenge is not getting this idea approved, its getting the leaders to commit to enforcing it. I am wiling to enforce it and use it, but every leader needs to agree to it.

So before you make the change, wait for approval from @paulbert @Loshma93 @zeivhann @sarah-lu102 @dogi @leonardmensah to say they are willing to enforce it.

**Comment by Loshma93** [comment]
@ChenjieZhou That's a good explanation about "Commit". I agree with your point.

**Comment by zeivhann** [comment]
Sure, I feel that this would make things streamlined and uniform. Sounds like a good plan to me.

**Comment by sarah-lu102** [comment]
Yes, this is a good idea

**Comment by kanishk1010** [comment]
I think this is a good idea. We can at least incorporate the "type: subject" format, which will also include the (issue#). Elaborate explanation might not be necessary as we already explain the issue and the fix whenever we create one and we mention the issue# in the commit comment.

**Comment by ChenjieZhou** [comment]
@kanishk1010 It may work for the pull requests which fix issues but not all of them. Some pull requests are adding new features or updating.

**Comment by adhikara** [comment]
I, too, agree as I found difficulty understanding expectations.

**Comment by leonardmensah** [comment]
Good resource to include https://chris.beams.io/posts/git-commit/
