### ISSUE TITLE
Typos in FAQ

### ISSUE THREAD

**Issue by ChenjieZhou** [open-learning-exchange/open-learning-exchange.github.io#842]
Last line of Q7, "until you **compete** the first steps" should be **complete**.

Third part of Q14, "**preferrably** one that" should be "**preferably**"

**Comment by ChenjieZhou** [comment]
The [link](http://open-learning-exchange.github.io/#!pages/faq.md) of FAQ page.

**Comment by kylemathias** [comment]
@ChenjieZhou Go ahead and make the changes and create a pull request.

**Comment by ChenjieZhou** [comment]
@kylemathias Yes, I created a pull request #843
