### ISSUE TITLE
make table alignment in 'team.md' consistent

### ISSUE THREAD

**Issue by kanishk1010** [open-learning-exchange/open-learning-exchange.github.io#854]
This is a minor one but I feel the table alignment of 'Active Volunteers' and 'Active Interns' should be consistent.

reference [team.md](http://open-learning-exchange.github.io/#!pages/team.md)

**Comment by aurinsomnia** [comment]
I agree, especially given we have three tables on the page, it looks too haphazard and disorganized to have all 3 tables with different dimensions. This might be a little tricky, but if you could fix the tables, I think it would be a worthwhile change.

**Comment by kanishk1010** [comment]
I will work on it. Would be a good learning experience!

**Comment by sarah-lu102** [comment]
@kanishk1010 just a suggestion for next time- put a link in your issue description so people can reference it more easily. It's a good idea though!

**Comment by kanishk1010** [comment]
@sarah-lu102 That makes sense. I would keep that in mind. Thanks for the advice!

**Comment by kanishk1010** [comment]
I have made some changes to the structure and formatting. Please have a look. Pull request #858 created.
