### ISSUE TITLE
Grammatical error fix in Git Repositories, under Sync Your Fork 

### ISSUE THREAD

**Issue by adhikara** [open-learning-exchange/open-learning-exchange.github.io#856]
As part of step 6, here is my first issue, for the following page:

http://open-learning-exchange.github.io/#!pages/gitandrepositories.md

"You should see some variation **on** this response:"

This should be changed to _in_ this response.

**Comment by sarah-lu102** [comment]
good catch but I think it should be "of this response"

**Comment by adhikara** [comment]
Ahh, you're right. Should have checked the context. Should I send a pull request?

**Comment by sarah-lu102** [comment]
yes!
