### ISSUE TITLE
Update Nation BeLL with "internet connection" error.

### ISSUE THREAD

**Issue by ChenjieZhou** [open-learning-exchange/open-learning-exchange.github.io#859]
In Nation BeLL [Different kinds of update](http://open-learning-exchange.github.io/#!./pages/nation.md#Different_Kinds_of_Update), I got this "internet connection" error at the first time. I could not update my Nation BeLL which happened on Safari. After I changed my browser to Chrome, it worked.
We could add a tip for this error.

**Comment by kanishk1010** [comment]
@ChenjieZhou I think we have been instructed to access BeLL with Firefox as of now. Please check [this link](http://open-learning-exchange.github.io/#!./pages/bellapps.md#MacOS(X)_and_Ubuntu)
