### ISSUE TITLE
Step 3 Improvement

### ISSUE THREAD

**Issue by kkearney95** [open-learning-exchange/open-learning-exchange.github.io#862]
I think it would be a nice addition to add an example picture of a github profile. It would help convey the minimum requirement and hopefully increase new profile quality. Attached is a very basic template of my idea. 
![johnsmith md](https://user-images.githubusercontent.com/27171307/26901067-7abadab4-4ba2-11e7-8136-e111abae1ee1.png)

**Comment by Loshma93** [comment]
Instead of adding a picture I would suggest to add link to sample profile pages: https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/master/pages/profiles. By doing this you can go through more pages to have an idea. This is my view let others give their view too.

**Comment by adhikara** [comment]
I would say that one of the pages I saw there was quite limited and was what I chose to model mine after -- and it was denied the first time, citing a need for more features.

**Comment by sarah-lu102** [comment]
maybe we should edit the instructions to tell them to add as many markdown elements as possible, and if not, their pull request may not be approved until they do so.

**Comment by lucy811** [comment]
maybe we can edit a more detailed instructions such as "be sure to add pictures or charts"  and "add the short description in the head of page" and so on.  I think we can call out the reader or the learner should do like this.

**Comment by sarah-lu102** [comment]
@lucy811 we already resolved this issue in another PR, so there is no need to make another one
