### ISSUE TITLE
Fixing typo in index page

### ISSUE THREAD

**Issue by adhikara** [open-learning-exchange/open-learning-exchange.github.io#867]
http://open-learning-exchange.github.io/#!index.md

"Our Virtual Interns program is part of the software development strategy by Open Learning Exchange (**OLÉ**)" should probably be corrected to _OLE_. Fun note: "Olé" means "Bravo!" in Spanish. I will send a pull request.

**Comment by adhikara** [comment]
https://rawgit.com/adhikara/adhikara.github.io/master/#!index.md

**Comment by prajwalajayaprakash** [comment]
@adhikara I believe this issue has been resolved. Hence I will be closing it.
