### ISSUE TITLE
Standardized intro page has been changed in Github?

### ISSUE THREAD

**Issue by adhikara** [open-learning-exchange/open-learning-exchange.github.io#875]
I noticed here, 

http://open-learning-exchange.github.io/#!./pages/gitandrepositories.md#Clone_your_GitHub_repository_username.github.io

that there is an instruction asking us to clone the forked repository like this:

`git clone https://github.com/EmilyLarkin/EmilyLarkin.io.git`

Shouldn't that be now something more like, `https://github.com/EmilyLarkin/EmilyLarkin.github.io`

Let me know!

**Comment by snazzybunny** [comment]
The first command doesn't work for me but using https://github.com/EmilyLarkin/EmilyLarkin.github.io.git does. Just missing the github part I believe.

**Comment by sarah-lu102** [comment]
<img width="672" alt="capture" src="https://user-images.githubusercontent.com/12993520/27036189-07e73e20-4f52-11e7-9b5e-5d4ba1bff52f.PNG">
