### ISSUE TITLE
adding a little bit of clarification

### ISSUE THREAD

**Issue by adhikara** [open-learning-exchange/open-learning-exchange.github.io#879]
http://open-learning-exchange.github.io/#!./pages/nation.md#Different_Kinds_of_Update

I got really confused here

"Next, click on "Publications" and sync the publications. "

I think it would be useful to write, 'Next, click on "Publications", under the Manager page, and sync the publications.'

**Comment by yoeng327** [comment]
Hello,
Right. 
I think it should write that "Publications" is under the Manager page. Thus, new interns can realize that they should click "Publications" under the Manager page, and sync the publications.
