### ISSUE TITLE
Space after step numbers in Introductory steps 

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#881]
Not a big deal, but in Step 0 @ http://open-learning-exchange.github.io/#!pages/firststeps.md, there is no space after the step number and the sentences.

**Comment by aurinsomnia** [comment]
This is an incredibly minor issue that appears to have been ignored, but I think this should be an easy fix, and the steps as they are are currently are a bit of an eyesore. Go ahead and make a pull request with the changes.

**Comment by aurinsomnia** [comment]
@alexkarasik Oops, just took a look at the PR's and you did make a request there. It hasn't been merged though, because your branch is out of sync with the rest of the page. If you could update your branch, I'd be happy to merge the change.

**Comment by alexkarasik** [comment]
@aurinsomnia I think it is taken care of now. Should i close this issue?
