### ISSUE TITLE
Add a brief description to the videos in Useful links

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#882]
The titles are pretty self evident, but I think an additional sentence describing the content on the videos on each page will be a useful addition.

**Comment by kylemathias** [comment]
@alexkarasik what videos are you talking about? want to give us an example of how you would change it.

**Comment by alexkarasik** [comment]
Sorry, I meant just any of the useful links. Some of them were videos so that is what came to mind. 
Here's an example and I can do it for them on all of the pages.
https://rawgit.com/alexkarasik/alexkarasik.github.io/linkexample/#!pages/gitandrepositories.md

**Comment by kylemathias** [comment]
Sure, little details about what the links are about would help. go ahead and make the changes and pull request.
