### ISSUE TITLE
Add a gitter.im link to all sidebars

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#883]
I think with the frequency of how often gitter.im is used, it may be helpful to have an additional tab on the left hand sidebars that links automatically to gitter.im. It may take a moment for some people to find the link to get back there if it is not already open.

**Comment by duongdo27** [comment]
We already had the **Chat** in the top nav. You can go check and see.

**Comment by alexkarasik** [comment]
Gotcha!
