### ISSUE TITLE
Include a FAQ section on each page

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#884]
I think some unique FAQ's will come up for each page and we can use it clarify the goals of the page and section and address and question that comes up more than once. We can add those all to the FAQ page itself as well.

**Comment by kylemathias** [comment]
@alexkarasik giving us details on what exactly you would add to a FAQ would help. It would be a good idea to keep in mind when you are going over a page, but we shouldn't add a FAQ with out at least 5+ questions and answers. You can make a pull request for this change, but it might take  a little bit before we can get to 5+ questions for each page we thing we should add a FAQ to.

**Comment by alexkarasik** [comment]
I don't think I'd be in the best position to write this out actually. I've had a few questions and made a couple of mistakes along the way, but I have no idea how common or frequent they may be. If there were some common questions about the process that come up that might be helpful, but I wouldn't really know what those would be, so this should probably be left for another day. Should I close this issue?

**Comment by kylemathias** [comment]
i will close this issue for now (for cleanliness), but as you move along into the internship, keep this in mind. Then if you ever come up with a solid 5 FAQs, then go ahead and make the changes and pull request.
