### ISSUE TITLE
Make the exit button more noticeable 

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#886]
The exit button that appears when you click on the image in the index page is hard to notice and in an odd place. I suggest moving it to the top right corner where exit buttons are usually place. I have attached a basic idea of what it would like.
![basic idea](https://user-images.githubusercontent.com/6295956/27112904-5a96315c-507f-11e7-90cf-496dd23d6c8d.png)

**Comment by kylemathias** [comment]
You can  go ahead and make a PR.  but i caution you and fixing cosmetic issues over functional. We can touch up visual bugs once our foundation code is running smoothly.

**Comment by LKhadka** [comment]
can you please take a look at [this?](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/889)
