### ISSUE TITLE
Steps on syncing local (origin/master) and username.github.io on GitHub

### ISSUE THREAD

**Issue by sagun98** [open-learning-exchange/open-learning-exchange.github.io#892]
[Click here](http://open-learning-exchange.github.io/#!./pages/gitandrepositories.md) for the link of the "Keeping Fork Updated" page of Step 5

The description in the highlighted red box explains the process to sync the local repo to the remote Github repo. However, adding few more screenshots of the steps in this [page](http://open-learning-exchange.github.io/#!./pages/gitandrepositories.md) can help the upcoming interns even better to keep their local and remote repositories synchronized with the https://github.com/open-learning-exchange/open-learning-exchange.github.io. 

![imageedit_2_9370960671 2](https://user-images.githubusercontent.com/15079734/27146018-79450b4a-50fd-11e7-88b8-8188c3744886.png)

**Comment by kylemathias** [comment]
Sound good to me.  i like adding visuals to steps.  go ahead and make a PR with the changes so we can see what you are talking about.

**Comment by sagun98** [comment]
@kylemathias  I have the PR #934 ready. Would you mind having a look at it ?
