### ISSUE TITLE
Consider switching to specific tag or commit hash in the URL instead of a branch name

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#894]
Rawgit caches files permanently on the first request ([more info](https://github.com/rgrove/rawgit/issues/41)). When I made changes to my profile in the Github and Markdown tutorial step, my rawgit was not updated and I ended up making several unnecessary commits. 
![image](https://user-images.githubusercontent.com/6295956/27153584-a6856c66-5117-11e7-96bb-02a30a4961b2.png)

**Comment by sagun98** [comment]
I ran into the similar problem. It would be better to put a warning tip in MDwiki to alert upcoming interns about this problem and suggest them to get rid of caches by going incognito or clearing cache manually.

**Comment by LKhadka** [comment]
I guess that would be much easier than looking for specific commit hash.
