### ISSUE TITLE
Problem while going back to github page from http://open-learning-exchange.github.io/#!index.md

### ISSUE THREAD

**Issue by sagun98** [open-learning-exchange/open-learning-exchange.github.io#896]
Whenever I click on the [link](https://github.com/open-learning-exchange/open-learning-exchange.github.io) highlighted in the picture below and try to come back using back button, it does not work. It seems like the back button is redirecting users to the same [page](http://open-learning-exchange.github.io/#!index.md) again and again.   

![imageedit_6_9198180127](https://user-images.githubusercontent.com/15079734/27149141-3b877134-5108-11e7-92f1-d1fe7a4cd8c3.gif)     

Now I get to  http://open-learning-exchange.github.io/#!index.md and try to use back button.

![imageedit_10_6827310200](https://user-images.githubusercontent.com/15079734/27149528-93d0b502-5109-11e7-9d29-7f190cbac41a.gif)

**Comment by kylemathias** [comment]
I just tried going to http://open-learning-exchange.github.io/#!index.md , and then hit the back button to this issue, i am able to get back here fine. Windows 10, Chrome.

**Comment by Loshma93** [comment]
@sagun98 I tried to go back from index.md to back. I encountered the same issue which you have specified. I am using Windows 8, chrome. I think it will differ from OS to OS. Because it is working fine for @kylemathias

**Comment by LKhadka** [comment]
I think this only happens when you go to http://open-learning-exchange.github.io/ and not when you go directly to http://open-learning-exchange.github.io/#!index.md. Ubuntu, Chrome.

**Comment by kylemathias** [comment]
I think i will close this for now, feel free to reopen if you find a solution.
