### ISSUE TITLE
Reduce the spacing between the header and the content

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#898]
The space between the header and the content is quite big. The margin-top value is set to a value of 71px and I think it would look better if the gap was not so big.
![image](https://user-images.githubusercontent.com/6295956/27198199-cf2296f2-51d6-11e7-91cb-0e761a1cf644.png)

**Comment by kylemathias** [comment]
This is a preference more than functionality issue. Issues like this are going to be fine to be left alone for some and others not. Try to focus on issues that are unquestionably needed to be changed/fixed.

**Comment by LKhadka** [comment]
gotcha
