### ISSUE TITLE
Use Sticky Footer

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#899]
Make the footer always stick to the bottom of the page even where there is not enough content to push it down. I think it will look nicer and consistent that way.
![image](https://user-images.githubusercontent.com/6295956/27150704-da20523e-510d-11e7-9227-dfe85adeca3d.png)

**Comment by kylemathias** [comment]
Sounds like a good change to me. Go ahead and make the changes and a Pull request. Let us know when you have a rawgit example in chat.
