### ISSUE TITLE
Checkbox for the completed steps 

### ISSUE THREAD

**Issue by sagun98** [open-learning-exchange/open-learning-exchange.github.io#900]
Create a checkbox in front of the steps to track the progress as shown in figure below in the [first step](http://open-learning-exchange.github.io/#!pages/firststeps.md) page.

![imageedit_26_9899613793](https://user-images.githubusercontent.com/15079734/27151394-0eafafa2-5110-11e7-84d1-6a795b7bc878.gif)

**Comment by LKhadka** [comment]
That sounds pretty useful. I think local storage can be used to persist the checked items even after the browser is closed.

**Comment by kylemathias** [comment]
This is a good feature to implement. I think this might be more cumbersome project than it first appears. We do not have an active data base in witch you could store this server side(i think), but you could look into making a cookie for individual users when they first visit the site and track the check boxes that way.

You can make the fix and Pull request when ever. I wish you luck.

**Comment by yoeng327** [comment]
Hello.
I think it is a good for new interns to have personal account's checkboxes. 
The reason is that it would be complicated not having checkboxes while some steps have not finished. 

I think it should be created at the beginning of "First Steps"!

**Comment by 21stChannel** [comment]
It will be better if a checklist of tasks can be added at the bottom of each task...
