### ISSUE TITLE
Request for more clarification in step3 of "First Steps"

### ISSUE THREAD

**Issue by yoeng327** [open-learning-exchange/open-learning-exchange.github.io#901]
Hello.
Previously, I was working on the step3, but I struggled with it for a long time because of directory's location.

On the beginning of the step3, could you specify that people need to change the directory to "usename.github.io" in order to work on step3?

I will add the explanation, "In order to do Step 3 and Step 5, you should be in the directory, "username.github.io". If not, you would have errors on changing branches in Step 5."

I'll really appreciate your help.

**Comment by kylemathias** [comment]
This sounds like a perfect little pull request you could do. Feel free to make the changes and then create a pull request while referencing this issue. Fixing issues like this is what the intern first steps is all about.
