### ISSUE TITLE
Request for more specification and clarification in step4 of "First Steps"

### ISSUE THREAD

**Issue by yoeng327** [open-learning-exchange/open-learning-exchange.github.io#902]
Hello.

Previously, I was working on the step4, but I struggled with it for a long time because of directory's location.
It did not mention that new interns should be in "ole--vagrant-vi" directory in order to work on step4 and step7.

On the beginning of the step4, could you specify that people must be in "ole--vagrant-vi" in order to work on step4 and step7?

Moreover, could you specify that "Vagrantfile" should be in the "ole--vagrant-vi", not "Vagrantfile.txt"?  

I'll really appreciate your help.

**Comment by kylemathias** [comment]
like i said in your previous issue #901, i think it would still apply here:
"This sounds like a perfect little pull request you could do. Feel free to make the changes and then create a pull request while referencing this issue. Fixing issues like this is what the intern first steps is all about."
