### ISSUE TITLE
Dates in readable format in Team.md   

### ISSUE THREAD

**Issue by sagun98** [open-learning-exchange/open-learning-exchange.github.io#907]
Link to Team.md: http://open-learning-exchange.github.io/#!pages/team.md

The dates could be separated by '**/**' or '**-**' to make it readable. 
For example: Change `20170610` to `2017-06-10`
![joindat](https://user-images.githubusercontent.com/15079734/27159637-0c5b3900-5134-11e7-8c75-de5c0e6d4a3a.png)

**Comment by Loshma93** [comment]
@sagun98 I agree with you. The format 2017-06-10 is more readable format than 20170610. But let's wait for others opinion as well.
