### ISSUE TITLE
NationBell Assignment Clarification

### ISSUE THREAD

**Issue by pranesh-s** [open-learning-exchange/open-learning-exchange.github.io#91]
As part of the fifth assignment, we are supposed to log onto NationBell to explore and see that our community is synced. However, the instructions specifying this are fairly vague.

> On the nation side, you can log in as admin/password and check that the sync worked. Click on "Manager" once again.

Mainly, other than specifying nation side, there is no indication of where to go in order to log in nation side (vi.ole.org). It was only because I was browsing the group chat at the right time that I recognized where to go. The change I am proposing is fairly simple, just add (vi.ole.org) in brackets.

Also, I felt that the explanation of NationBell vs LocalBell wasn't really covered completely. I noticed that Emily had posted what seemed to be a much clearer explanation in chat and wanted to bring up the idea of including it or an edited version of it in the intro to the assignment.

> So we have three levels: local, community, and nation. We need to make sure they are always synced and on the same page, otherwise you'll have merge conflicts and essentially run the risk of messing up the code pretty good. We use communities in places without internet because they are local. Whereas nations are connected to the internet and it allows a connection process between us (with internet) and those on communities (without internet). Communities are either run on RPis or laptops but are intranet, not internet connected and to sync the communities with the nations, we connect to internet so that information is sent in both directions.

I have submitted a fix for the first issue but thought there should be a discussion before addressing the second one.

**Comment by Hulmani** [comment]
We can highlight "On the nation side (vi.ole.org), you can log in as admin/password and check that the sync worked. Click on "Manager" once again." to make things clear

**Comment by dogi** [comment]
@Hulmani that little fix of yours just scratched the surface on this problem

**Comment by Hulmani** [comment]
@dogi could you please elaborate, I tried to fix what I felt was confusing.

**Comment by aberdean** [comment]
No longer relevant (was already addressed).
