### ISSUE TITLE
Sidebar disappears when scrolling up

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#910]
The sidebar with the table of contents on the start here page is prominent when initially scrolling down, but when a user scrolls back up, it disappears, even if they scroll back down again after they have scrolled up. It simply disappears and goes back to the the top again, but I think it would be most useful if it remains on the side, no matter what the action by the user may be. 

I think a little bit of CSS should do the trick: https://tickera.com/blog/creating-sidebar-scrolls/

**Comment by LKhadka** [comment]
I don't have this issue. Can you add a screenshot or something?

**Comment by sarah-lu102** [comment]
@LKhadka I think he is saying that the sidebar is static and does not move when scrolling (you can only see it at the top of the page)- but it would be more useful if the sidebar stayed in the same position relative to the screen no matter how you scroll up and down. 

@alexkarasik you should go ahead and make a PR for this

**Comment by LKhadka** [comment]
@sarah-lu102  I see. I just noticed it. My bad.

**Comment by alexkarasik** [comment]
Hey guys, sorry for the delay on responding to this issue... I want to do a pull request, but I don't actually see where these sidebars are in any of the pages when I look at their markdown. Does anyone know where I would find them to fix this?

**Comment by duongdo27** [comment]
@alexkarasik, That [issue](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/622) may help you. See my comment in that issue

**Comment by alexkarasik** [comment]
@LKhadka It does stay relative until a user goes all the way down to the bottom of the page. But once they scroll up again, it disappears until you go all the way to the top and it is static.
@duongdo27 thank you for the reference, but I am finding it very difficult to find the relevant part of this line since it is so long.
I am trying to figure out where in the index.html page I can find the mechanics of the sidebar and I believe it is line 246, but its really hard to make out what part of it I am looking for. 
In any event, this is a very, very minor issue
