### ISSUE TITLE
Tell new Users to implement at least 5 new pieces Markdown in their profiles

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#911]
I think some people are not sure about how many different pieces of markdown they should be using in the Github and Markdown section. I think recommending using 5 different pieces of syntax will help give them more guidance on this issue.

**Comment by kylemathias** [comment]
sounds good to me. Adding something like "use a minimum of 5 different markdown elements" would help. Go ahead and make the changes and the pull request.

**Comment by yoeng327** [comment]
I think it is good idea because that many interns should use diverse Markdown functions at first. It will help for new interns to learn how they can use Markdown in flexible ways. At lease 5 should be good. Make the changes and the pull request.

**Comment by alexkarasik** [comment]
I think this is resolved now. Closing this issue.
