### ISSUE TITLE
Make the headers link to their specific pages in First Steps

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#912]
When I am going through the first steps, sometimes I get confused about which link I should click to view the instructions in detail especially in those which have a lot of text. I think it would be easier to navigate if the headings were to link to their respective instructions.

**Comment by kylemathias** [comment]
I agree with the headings being links, BUT there was an issue i found out while making the [Take-Home](http://open-learning-exchange.github.io/#!pages/takehome.md) pages. If you make the headers a link, the list menu dose not display correctly. The way i fixed this was by adding an additional link at the top of the description paragraph like so.
![image](https://user-images.githubusercontent.com/26488295/27200336-36a14f16-51ce-11e7-99fd-aeb0ba4875e8.png)

Its not as "optimal" as it could be by having the headers be links, but i would rather have the side menu be working with this work around than not having a side menu at all.

**Comment by LKhadka** [comment]
You're right. I had a similar issue when I was trying to link them. All the steps have a link to their pages in their descriptions. So, would it still be okay to add a link at the top of the description paragraph?

**Comment by kylemathias** [comment]
That would be my soultion, but it should be a majority voted for IMO. You can make the changes and the pull request.

Be wary, this might be more work then initial perceive. You are going to have to change the paragraphs that each of these links are in in-order to keep clarity.

**Comment by LKhadka** [comment]
I am closing it because I think it would be redundant to have so many links and only step 8 which has a lot of text would benefit from it.
