### ISSUE TITLE
Tell users to include their rawgit and add a link to sample profile pages

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#914]
When people are doing their first pull request, they either forget to add a link to their rawgit or do not have enough markdown or styling and I always see the reviewers reminding them to do so. I think it would be better to add a small note about this at the end of the GitHub and Markdown page

**Comment by duongdo27** [comment]
@LKhadka  I agree with you. Makes some changes for it.

**Comment by kylemathias** [comment]
I don't think its said anyplace to make a rawgit when making a PR. If you can find the right place to put it, im all for the change.

**Comment by yoeng327** [comment]
Hello.

It would be good to write down the rawgit when making a PR. Previously, a leader asked me to put down the rawgit link in my PR, so I did that. However, many first interns seem not to include the link in their PR.

Go ahead and make it changes and PR.

**Comment by navneetkarnam** [comment]
It is mentioned to comment the rawgit link in the gitter.im chat. I suggest that we add below the same that the rawgit link has to be mentioned while creating a PR. 

<img width="1011" alt="screen shot 2560-06-16 at 6 17 34 pm" src="https://user-images.githubusercontent.com/16421653/27246583-86212762-52c0-11e7-9b90-dce8806acdae.png">

**Comment by kylemathias** [comment]
I would make a change to the explanation and to say when making a pull request to add a rawgit to the PR.

Something like:
"Rawget dose_____. its good because of _____, it helps others see exactly what the change would look like"

**Comment by LKhadka** [comment]
i think it would be better to update the open a pull request section to include all these new instructions

**Comment by Yurockkk** [comment]
solved by #915
