### ISSUE TITLE
Request for diverse tutorials of Markdown 

### ISSUE THREAD

**Issue by yoeng327** [open-learning-exchange/open-learning-exchange.github.io#919]
Hello.

I think it would be better to post the links of various tutorials of Markdown in the "Github and Markdown". 
If we post the some excellent links of Markdown tutorials in "Github and Markdown", it would be efficient for new interns to create diverse things with Markdown. 

Could we post more links of Markdown tutorials in the "First Steps"?

Sincerely,
Evan

**Comment by LKhadka** [comment]
I think it would be hard for beginners to make changes to javascript since its written in jquery and looks complicated. I agree that it would be nice to have some Javascript tutorials.

**Comment by 21stChannel** [comment]
Good advice as MD will be heavily used in the project. It will be better if examples for each MD syntax can be given.
