### ISSUE TITLE
Further explanations about the "Become an Administrator" page in step4 

### ISSUE THREAD

**Issue by yoeng327** [open-learning-exchange/open-learning-exchange.github.io#924]
Hello.

I think it would be better to post the further explanations about "Become an Administrator" page.
The following explanations are better to be added:
1. If someone turns off the laptop or computer while staying on "Become an Administrator" page, it would go to "Member Login". 
2. If it pops up "Member Login" page instead of "Become an Administrator" page, you should use the code "vagrant init" and then use "vagrant up" to start the virtual box again.

Could you add those explanations on step4 please? 

Sincerely,
Evan(Inyong)

**Comment by sarah-lu102** [comment]
good clarification. You can make a pull request for this

**Comment by 21stChannel** [comment]
Hi, I have a question is, if someone destroy the virtual box by mistake, how can he recover the admin & configuration info?

**Comment by navneetkarnam** [comment]
@21stChannel Just use the code "vagrant init" and then once it's initialised you can use "vagrant up" to start the virtual box again!

**Comment by 21stChannel** [comment]
@navneetkarnam Thanks for your reply. But seems like "vagrant init" actually creates your own vi environment from scratch and is not compatible with the app.

**Comment by kylemathias** [comment]
@yoeng327 i don't know exactly what you are talking about. You can make the change and the PR, but you might be doing something that might not get approved because of not fully understanding the exact change you are trying to make.

**Comment by navneetkarnam** [comment]
@yoeng327 Are you still working on this? Did you make a PR?

**Comment by dogi** [comment]
Hmm - this mean this issue is now a free for all
