### ISSUE TITLE
More troubleshooting in step 2 & 4

### ISSUE THREAD

**Issue by 21stChannel** [open-learning-exchange/open-learning-exchange.github.io#926]
When I first tried accessing http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html, I was redirected to an error page saying "no_db_found". And I checked that the "apps" and some other DBs were missing even if "vagrant up" did not show any error messages. There might be some glitches in downloading/unarchiving the files that corrupted the integrity. 

So my suggestion for weird problems in step 2 & 4 is to do a "vagrant destroy" and rebuild the app, that fixes the problem I've faced.

**Comment by navneetkarnam** [comment]
I faced a similar situation too. I believe the **"Vagrant destroy"** and rebuilding with **"vagrant init"** would work and then we can **"vagrant up"** and check the status. It worked for me this way.

**Comment by sarah-lu102** [comment]
sounds good. Make a PR and we will check it!
