### ISSUE TITLE
Number of Pull requests, comments in First steps

### ISSUE THREAD

**Issue by navneetkarnam** [open-learning-exchange/open-learning-exchange.github.io#929]
- We should add the number of pull requests, comments and issues that the intern would have completed after each step in the **"first steps"** page. So that it is easier for them to keep track of the work they have completed. 
- I see that this has been specified at **step 8**. But its good to specify the same after the previous steps too.

**Comment by 21stChannel** [comment]
Very good suggestion, as I sometimes need to go back to the big picture and check it :P

**Comment by kylemathias** [comment]
It might be better to just add were the pull request is located in the summary. "1 PR in step 3 and 2 in step 4" or something like that.

**Comment by navneetkarnam** [comment]
@kylemathias yup I did the same and created a PR #940 please take a look :)

**Comment by navneetkarnam** [comment]
This issue was resolved with PR #957 . Hence will close it.
