### ISSUE TITLE
Markdown and HTML 

### ISSUE THREAD

**Issue by navneetkarnam** [open-learning-exchange/open-learning-exchange.github.io#930]
- This page that shows the cheatsheet of Markdown which is compared with the HTML elements I feel gets a bit confusing at the first look. 
- I think we must just put the Markdown cheatsheet in here instead of having a comparison of it with HTML so as to reduce confusions while creating the md page. 
- I personally got confused with this and had used the HTML elements in between while creating my Markdown page.
* * * 
<img width="874" alt="screen shot 2560-06-16 at 6 21 39 pm" src="https://user-images.githubusercontent.com/16421653/27246648-f7db801e-52c0-11e7-8db3-fadc882753a5.png">

**Comment by 21stChannel** [comment]
Yes, I think we should replace the HTML example with the actual MD layout. Sometimes I need to think about how this HTML layout looks, quite confused.

**Comment by kylemathias** [comment]
I agree. Just a markdown page would help, or at least having a header saying "This is html and this is markdown". make the change a pull request for it to be reviewed.

**Comment by navneetkarnam** [comment]
@kylemathias sure I will go ahead and make the changes and create a PR for this!
