### ISSUE TITLE
Followed step 7 and got something weird

### ISSUE THREAD

**Issue by 21stChannel** [open-learning-exchange/open-learning-exchange.github.io#935]
Hi all,

I followed the procedure in step 7, updated the app to version 0.13.* I guessed, then got a "crashed" page like this:
<img width="1265" alt="qbjietu20170616-194404 2x" src="https://user-images.githubusercontent.com/24657165/27249518-796d6e34-52cc-11e7-9697-9c092229d58b.png">
I have no idea how to fix it...Is it always safe to update?

**Comment by navneetkarnam** [comment]
Try updating this using the google chrome or Firefox browser! It should work. I got the same error when I tried updating using the safari browser on Mac and later tried with google chrome, it worked fine!

**Comment by 21stChannel** [comment]
@navneetkarnam Thanks bro. But I have a question is, how can you manage to update again since the page is crashed? Seems like I am not able to click anything on this page even if I refresh it several times...Thanks!
