### ISSUE TITLE
Need for rephrasing the instruction in step 2

### ISSUE THREAD

**Issue by 21stChannel** [open-learning-exchange/open-learning-exchange.github.io#936]
In step 2, it says:
Now that you are in the right directory, check the status of your Vagrant machine with vagrant global-status. You should have the following message:
```
id       name   provider   state   directory
---------------------------------------------------------------------------
2198a3d  vi     virtualbox running /Users/Emily/ole--vagrant-vi

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
```
If you have a different message, either your Vagrant machine is powered off, or you have multiple machines with the same name, or you are experiencing some other technical issue.
***
For the first look to the instruction, new vagrant users may think the attributes (id, name, etc) need to be the same as shown above, but actually the id and directory may vary for different users. I think this should be rephrased to be more clear.

**Comment by sarah-lu102** [comment]
Good point- this may not be intuitive for some people. Go ahead and make a pr for this

**Comment by navneetkarnam** [comment]
@21stChannel have you made a PR for resolving this issue?

**Comment by dogi** [comment]
hmm - this means that this issue now is a free for all

**Comment by dogi** [comment]
open-learning-exchange/open-learning-exchange.github.io#948
