### ISSUE TITLE
Updating image of Nation bell of step 7

### ISSUE THREAD

**Issue by sagun98** [open-learning-exchange/open-learning-exchange.github.io#937]
In the [Nation Bell Step 7](http://open-learning-exchange.github.io/#!./pages/nation.md), it is mentioned that we could see a publications ready to be downloaded in the description but the image shows the "Update Available" button only.

We could update the image and add the Publication button too. 
![issuue1](https://user-images.githubusercontent.com/15079734/27250104-1f69c9cc-52eb-11e7-8c7e-1bf6a4b7c834.png)
![issue_circle](https://user-images.githubusercontent.com/15079734/27250105-2862d924-52eb-11e7-94e4-38402b876d0e.jpg)

**Comment by 21stChannel** [comment]
And I have an additional question is, the Publications is 1 for me, but the instruction says it seems to be 2...Hmm

**Comment by sagun98** [comment]
@21stChannel  Yes. I also had just one publication to update. I raised a [new issue](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/941) on that. Lets see what others have to say about this.

**Comment by navneetkarnam** [comment]
Yes I had just one publication to update too.
