### ISSUE TITLE
Should add step tag to the "first step" dropdown

### ISSUE THREAD

**Issue by 21stChannel** [open-learning-exchange/open-learning-exchange.github.io#938]
<img width="365" alt="qbjietu20170616-212558 2x" src="https://user-images.githubusercontent.com/24657165/27250108-6d8d6250-52da-11e7-8bef-9da3011959e5.png">
When using this dropdown for fast navigation, it's good to have something like Step 2: Vagrant, Step 3: GitHub and Markdown, etc to indicate which step it is related to.

**Comment by kylemathias** [comment]
I wouldn't mind having a second drop down for each step in "Start here" drop down link, so long as "Start here" is still clickable.

**Comment by tjyothsna16** [comment]
I totally agree. I deeply felt the need for it. In fact, As @kylemathias mentioned, dropdown menu popping out when hovered on "Start Here" is not a bad idea. Personally, I would rather want to have it as a primary dropdown, since I felt the need for jumping between the steps multiple times.

**Comment by tjyothsna16** [comment]
@kylemathias I do not think we can add multi-level dropdowns in the current implementation of markdown. Here's the <a href="https://github.com/Dynalon/mdwiki/issues/326">explanation</a> given.

**Comment by kylemathias** [comment]
ok, i will close this out for now. if we can find a way to do it, just reopen the issue.
