### ISSUE TITLE
The number of publication in the Nation Bell page

### ISSUE THREAD

**Issue by sagun98** [open-learning-exchange/open-learning-exchange.github.io#941]
The description in the [nation bell ](http://open-learning-exchange.github.io/#!pages/nation.md)page says that there are two publication ready to be downloaded but I see only one. 

If number of publication is going to vary then it would be better to replace "two publication" with just "publication(s)."

![imageedit_1_3912125445](https://user-images.githubusercontent.com/15079734/27250792-81541702-52fd-11e7-9ae3-31270a8eac09.gif)

![pr_circle](https://user-images.githubusercontent.com/15079734/27250806-efc395d2-52fd-11e7-8b66-1e785944dc3b.jpg)

**Comment by kylemathias** [comment]
You can change the description so people know exactly what we are referring to. Go ahead and make the change and the Pull request.

**Comment by sagun98** [comment]
@kylemathias  I had already made the PR. Would really appreciate if you could review it #942 .
