### ISSUE TITLE
Problem checking vboxmanage version 

### ISSUE THREAD

**Issue by snoopy860228** [open-learning-exchange/open-learning-exchange.github.io#95]
I'm having problems with checking the vboxmanage version on the Command Prompt. I get the following message.
"vboxmanage is not recognized as an internal or external command..."

**Comment by snoopy860228** [comment]
there should be another command to check for the vboxmanage version

**Comment by fsjoyti** [comment]
You can run the vboxmanage version by going into the directory where the executable is located or you can follow the directions I gave to add it as a path variable through advanced system properties. I added the directions in the vagrant tab.
