### ISSUE TITLE
re-ordering the members

### ISSUE THREAD

**Issue by prajwalajayaprakash** [open-learning-exchange/open-learning-exchange.github.io#952]
I suggest re ordering of the members to put the intern leads on top as bold statements placed randomly in the list don't look pleasing. Else we can make a separate list of the leads.
<img width="565" alt="re-ordering members" src="https://user-images.githubusercontent.com/29417343/27300811-0a04f42e-54ff-11e7-8a4f-254db46a9290.PNG">

**Comment by aurinsomnia** [comment]
Personally I think the layout is fine as is, given that it is listed by seniority with the most senior members at the top. That said, I do agree that the lead labels, as they are currently, seem a little out of place. I think that might have more to do with formatting than anything, but I'll defer to the more senior members on this one, as it is more a matter of preference than anything else.

**Comment by sagun98** [comment]
I also agree with @aurinsomnia as the interns are sorted in the order of their joined dates. Alternatively, I think referencing could be done to make this page visually pleasing. 

For example: 

Loshma93 (W)
kylemathias(M)

W-> Wiki Intern Lead
M-> Mobile Intern Lead

**Comment by kylemathias** [comment]
Its ordered by date, witch i think is more important. I say leave it before @dogi realizes his date format he prefers was changed.

**Comment by prajwalajayaprakash** [comment]
Okay I'll leave it :)
