### ISSUE TITLE
Add title for the images in Nation Bell page

### ISSUE THREAD

**Issue by tjyothsna16** [open-learning-exchange/open-learning-exchange.github.io#958]
It would be nice to have a title for the images in Nation Bell page. Something like this:

![capture](https://user-images.githubusercontent.com/29378988/27363657-df3f3726-5603-11e7-81b1-b17ff7fb7c50.PNG)

**Comment by duongdo27** [comment]
It looks good. Make a pull request for it if you want.

**Comment by LKhadka** [comment]
Solved by #959
