### ISSUE TITLE
Mismatch in the adding new resources screenshot in step-4(BeLL-Apps tutorial)

### ISSUE THREAD

**Issue by prajwalajayaprakash** [open-learning-exchange/open-learning-exchange.github.io#962]
There is a slight mismatch between the screenshot given for adding a new resource and the actual dialog box that appears. The media, open and resource for tabs appear in a different order. I suggest updating the page with a new screenshot as I was personally confused for a bit while doing it for the first time.

1. old screenshot
![addresourceold](https://user-images.githubusercontent.com/29417343/27405193-9cac0cc2-569e-11e7-9293-178162a8c70a.JPG)

2. actual appearance
![addresourcenew](https://user-images.githubusercontent.com/29417343/27405199-a1b20000-569e-11e7-83e2-a69b7fd53b46.JPG)

**Comment by aurinsomnia** [comment]
This seems like a reasonable and easy fix. Go ahead and make a pull request for the change.
