### ISSUE TITLE
Remove an unnecessary space

### ISSUE THREAD

**Issue by tjyothsna16** [open-learning-exchange/open-learning-exchange.github.io#968]
Remove unnecessary space after "OS X operation system". This space can cause a new line with only period as part of line.
![image](https://user-images.githubusercontent.com/29378988/27439736-a6b91cbc-5736-11e7-9dfc-c02c4ca4843a.png)

**Comment by navneetkarnam** [comment]
* This issue was resolved and hence I'm closing it.
