### ISSUE TITLE
GitHub and Markdown page clarification

### ISSUE THREAD

**Issue by pranesh-s** [open-learning-exchange/open-learning-exchange.github.io#97]
As part of Assignment 2, we have to follow the instructions on the GitHub and Markdown page. One of those instructions is to create our own markdown page introducing ourselves. While the instructions on how to do this is clear, what is not specifically mentioned is that this is an opportunity for us to experiment with markdown. As such, many initial pages were created very simple, and then edited to have more markdown elements after feedback from the gitter chat. So, I thought it would be a good idea to add a line to encourage experimentation and the usage of various markdown elements in the process of creating an introductory page. It could be something like this:

> Feel free to experiment with Markdown and use various Markdown elements when creating your page. After all, this is an opportunity to familiarize yourself with the language.

**Comment by DrewPerlman** [comment]
:+1:

**Comment by rachelpei** [comment]
I agree. It does show in the picture example that Markdown has been used, but maybe a side-by-side comparison of the .md and the resulting formatted page would help to show how it works, similar to the first image on the "GitHub and Markdown" instructions. The current image only shows the result.

**Comment by aberdean** [comment]
No longer relevant (already been addressed).
