### ISSUE TITLE
Minor grammatical errors

### ISSUE THREAD

**Issue by tjyothsna16** [open-learning-exchange/open-learning-exchange.github.io#970]
There are a couple of minor grammatical errors that need correction.

![image](https://user-images.githubusercontent.com/29378988/27443729-0ada3374-5742-11e7-929e-1c5863d53b27.png)

![image](https://user-images.githubusercontent.com/29378988/27443757-26bfc41e-5742-11e7-98b9-95f8f82293d2.png)

**Comment by kylemathias** [comment]
go ahead and max the fix and the pull request
