### ISSUE TITLE
Capitalize and rephrase note on Git Repositories page

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#973]
It would be better to rewrite the first line of the note as "While rebasing and merging are similar, there is a difference between them". If not it would be just better to capitalize the first word.
![image](https://user-images.githubusercontent.com/6295956/27454336-1c23801e-575f-11e7-9038-6be38cac0c7c.png)

**Comment by kylemathias** [comment]
Sounds good, make the PR and mention this issue.
