### ISSUE TITLE
Change the sample pull request image on Github and markdown page

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#974]
The image in the open a pull request should be changed with one which has a rawgit link as suggested by the note below it. 
![image](https://user-images.githubusercontent.com/6295956/27454825-e9b1ce2c-5760-11e7-953d-0d5f351133ad.png)

**Comment by Yurockkk** [comment]
Sounds good to me! go ahead and make a PR 👍
