### ISSUE TITLE
Making one of the steps under Step3 (Markdown and fork tutorial) more clear.

### ISSUE THREAD

**Issue by apurva-g** [open-learning-exchange/open-learning-exchange.github.io#975]
**Create a new file as your personal MD wiki page and commit your changes**  one of the steps under Step 3 of First Steps where I made a mistake: Here it requires us to create a new branch before creating your file, while I was doing this, though I had followed the instructions I missed creating a branch and I happened to move to the next step of creating a file without cross checking to see if the branch was created or not. 

I feel making it a bit more clear on creating the branch would be helpful.

**Comment by apurva-g** [comment]
I think it could be made clear by adding these lines:
 **To create a branch:** Click on the **Branch** drop down menu and name your branch (you can give any name to your branch) then click **Create branch**. Once you are done with that now you can see that your branch is listed in the menu.

**Comment by kylemathias** [comment]
@apurva-g I think for the MD wiki page that new user create, all current interns understand it is going to be made in the master. That being said, it would be better to have interns start off on the right foot by making a branch and then creating there wiki. By doing this, we are setting up interns to how we want them to make branches and fix issues.

I say go ahead and make the changes and pull request so we can see how this would look/sound.
