### ISSUE TITLE
Adding a screenshot in Step-0 

### ISSUE THREAD

**Issue by navneetkarnam** [open-learning-exchange/open-learning-exchange.github.io#976]
- I feel we must add a screenshot of the GitHub page showing where the watch and follow buttons are actually located. 
- This would make it more easier for the new interns to follow the steps.
<img width="901" alt="screen shot 2560-06-22 at 4 52 51 pm" src="https://user-images.githubusercontent.com/16421653/27455564-b6d5da6a-576b-11e7-8bf4-8393724f075b.png">

**Comment by sarah-lu102** [comment]
ok, you can make a pr for this!

**Comment by navneetkarnam** [comment]
Sure will go ahead and make a PR for this! :)

**Comment by kylemathias** [comment]
!!!!

**Comment by navneetkarnam** [comment]
Haha 😄
