### ISSUE TITLE
Git Repositories addition

### ISSUE THREAD

**Issue by pranesh-s** [open-learning-exchange/open-learning-exchange.github.io#98]
In the Git Repositories tutorial, we are taught how to clone a repository, and sync up with relevant master/upstream repositories. However, already some people have had to rebase their forked repositories and there aren't any helpful instructions or links on the page about the process. The following two links:

https://git-scm.com/docs/git-rebase
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

are fairly helpful but I was unsure of how to go about adding it into the instructions on the Git Repositories page.

**Comment by AdityaNair99** [comment]
Hi @pranesh-s!

So as far as I know, the best way to do this is to make the changes in your repository to gitandrepositories.md and then create a pull request, and then someone will check it out and ok the changes - which should change the file on the master

**Comment by dogi** [comment]
@pranesh-s I really like the links
Hope somebody tries to create a "pull request"
