### ISSUE TITLE
Vagrant Tutorial page warning

### ISSUE THREAD

**Issue by navneetkarnam** [open-learning-exchange/open-learning-exchange.github.io#981]
- We should create a __BOLD__ warning message on the vagrant tutorial page about the __"vagrant destroy"__ command, that it will destroy their community BeLL and they'll have to completely rebuild it and will have to send another registration request to @dogi . 
- Many of them are making this mistake so I suppose writing this in bold and putting in more clarification will at least warn them.
<img width="1277" alt="screen shot 2560-06-22 at 11 38 14 pm" src="https://user-images.githubusercontent.com/16421653/27465988-294ec618-57a5-11e7-8742-dbae6621f1dc.png">
.

**Comment by kylemathias** [comment]
Sounds good. make the change and the pull request.

**Comment by navneetkarnam** [comment]
@kylemathias sure will do a PR for this one!
