### ISSUE TITLE
Community Manage Page needs an updated screenshot in Step 7

### ISSUE THREAD

**Issue by tjyothsna16** [open-learning-exchange/open-learning-exchange.github.io#982]
Old:
![nation md3](https://user-images.githubusercontent.com/29378988/27466511-3cbd4964-57a9-11e7-9dcb-b3e4f984238a.png)

New:
![nation md3](https://user-images.githubusercontent.com/29378988/27466493-23d3b8ac-57a9-11e7-87c9-1238ef33ad7b.PNG)

**Comment by aurinsomnia** [comment]
Go ahead and make a pull request. This isn't a huge issue of course, but accuracy is always important.
