### ISSUE TITLE
Placing virtualization information under corresponding operating system

### ISSUE THREAD

**Issue by prajwalajayaprakash** [open-learning-exchange/open-learning-exchange.github.io#985]
I suggest placing the information links for enabling virtualization under the corresponding operating system instructions in the vagrant tutorial page. For example placing the windows virtualization enabling information under windows tab. Some people would only check the information regarding their OS and not scroll down the entire page and hence miss the virtualization information at the end in case their systems do not have virtualization enabled already. I think this change would be really helpful.

<img width="635" alt="virtualinfo" src="https://user-images.githubusercontent.com/29417343/27497279-c4698e8a-5827-11e7-8fb3-6566307a69e7.PNG">

**Comment by sarah-lu102** [comment]
this is a good idea
