### ISSUE TITLE
Wrong information about a screenshot in markdown tutorial page

### ISSUE THREAD

**Issue by prajwalajayaprakash** [open-learning-exchange/open-learning-exchange.github.io#988]
While the markdown tutorial image was updated with a new one, the information about it on the top wasn't and it still refers to HTML. The right column shows the text preview and not HTML syntax.

<img width="654" alt="markdowntutorial" src="https://user-images.githubusercontent.com/29417343/27498350-a166d73a-582c-11e7-9844-cfcb228ee0f2.PNG">

**Comment by ChenjieZhou** [comment]
Yes, please make a pull request for it.
