### ISSUE TITLE
Provide a link to community login in step 7 introduction

### ISSUE THREAD

**Issue by prajwalajayaprakash** [open-learning-exchange/open-learning-exchange.github.io#995]
I see that there is no link to Community login in the introduction part of step 7(Nation bell tutorial). I suggest putting this link : http://127.0.0.1:5985/apps/_design/bell/MyApp/index.html. under the introduction part just above the note to avoid going back to step 4 in search of this link.

<img width="668" alt="step7intro" src="https://user-images.githubusercontent.com/29417343/27563353-13326496-5a9f-11e7-9040-2279282d80ed.PNG">

**Comment by alexkarasik** [comment]
I agree. This would be helpful and also avoid confusion about where exactly someone should be working.

**Comment by prajwalajayaprakash** [comment]
@alexkarasik I have created a PR#996 to resolve this issue. Please have a look.
